### ISSUE TITLE
Multiple Remap methods

### ISSUE THREAD

**Issue by EliiasG** [FlaxEngine/FlaxEngine#1000]
**Issue description:**

In Mathf.cs and Mathd.cs there are both "Map" and "Remap" methods that seem to do the exact same thing.
This is not the case in Math.h, it only contains "Remap".

**Steps to reproduce:**

Go on github and read the code.

**Minimal reproduction project:**

The code on github:
[Mathd](https://github.com/FlaxEngine/FlaxEngine/blob/master/Source/Engine/Core/Math/Mathd.cs)
[Mathf](https://github.com/FlaxEngine/FlaxEngine/blob/master/Source/Engine/Core/Math/Mathf.cs)

**Flax version:**

The master branch.

**Comment by Withaust** [comment]
Btw, congrats on the issue №1000 :D
