### ISSUE TITLE
Scale Transform Gizmo issue when enabling Scale Snap

### ISSUE THREAD

**Issue by RuanLucasGD** [FlaxEngine/FlaxEngine#1002]
**Issue description:**
When I duplicate an object and change its scale with Snap enabled, the object's scale is messed up

**Steps to reproduce:**

1. Enable Scale Snap
2. Duplicate the object
3. Change to Gizmo to Scale mode
4. Click on Scale Gizmo

[Development 2023.04.15 - 14.09.05.01.webm](https://user-images.githubusercontent.com/79365912/232246586-a7d31a4a-02ce-476e-ae78-d8d42d182e98.webm)

**Flax version:**
1.5

**Comment by mafiesto4** [comment]
Fixed in #1152
