### ISSUE TITLE
[Feature Request] Disconnecting nodes by removing the link between them

### ISSUE THREAD

**Issue by TheJustLink** [FlaxEngine/FlaxEngine#1010]
If I want to delete a connection between nodes, I have to delete one of the nodes or make a dot on the connection of the nodes to delete it later (the connection will go away). This is a bit annoying, you can't even highlight the connection. And you can't RMB click on the connection.

![image](https://user-images.githubusercontent.com/29580493/232482016-a2d02a4d-5b5f-4459-b5af-27de920bb7b4.png)

**Flax version:** 1.5

**Comment by Tryibion** [comment]
I agree that there should be an easier way to do this. But you can left click on the incoming connection (for example the 'A' of the Consine) and drag it off of the node and then click `ESC` to cancel the search results and that should disconnect the node.

**Comment by mafiesto4** [comment]
You can also hold `Alt` and click on a box to disconnect it. It can also be done by right-clicking that box's context menu to disconnect any connections with it or even for a whole node.
Anyway, we could add Middle Mouse Button (mouse wheel) click on box or connection to delete it quickly via a single action.

**Comment by mafiesto4** [comment]
Added in f3e6b74043d7bfdd636a2ea5f9e540e278975d60
