### ISSUE TITLE
Nested prafabs on scene don't apply changes from root prefab, also Transform changes in root don't change nested

### ISSUE THREAD

**Issue by TheJustLink** [FlaxEngine/FlaxEngine#1015]
**Issue description:**
Nested prefabs that are placed on scene do not apply changes from the root prefab.
However, in the nested prefab itself, the changes have been applied. Only the scene where the nested prefab is being used did not apply.

**Steps to reproduce:**
1. Create empty object in scene
2. Create prefab
![image](https://user-images.githubusercontent.com/29580493/233070298-9e1a0752-14e5-4a34-ac04-03f18df7b3a6.png)

3. Change any object parameters in scene (I change name)
4. Create another one prefab (nested prefab) with these modifications
![image](https://user-images.githubusercontent.com/29580493/233071573-c467fd50-2226-493c-b2e3-ea05a56a267e.png)

5. Change root prefab parameters (I changed static flags to None)
![image](https://user-images.githubusercontent.com/29580493/233071872-e7abe352-7eda-4d2c-b0a7-6c2f22a6bce3.png)

6. Look at the object that is on the scene. It will not have these changes applied.
NestedPrefab:
![image](https://user-images.githubusercontent.com/29580493/233072129-02554ec1-2925-4e27-b00f-099d66a7a8d8.png)
NestedPrefab on scene:
![image](https://user-images.githubusercontent.com/29580493/233072470-d3c3ddd9-6ad4-46cb-bce6-f3937cfa5ad6.png)

I can imagine how annoying it would be to use nested prefabs. I also recommend trying to change the Transform values in the root prefab, then the changes to the nested prefabs don't come at all.

(I tested this all on a blank scene)

**Flax version:** [1.5.6339](https://github.com/FlaxEngine/FlaxEngine/releases/tag/1.5.6339)

**Comment by mafiesto4** [comment]
Fixed in 0c3d1e3ec6e2eb9f64b47f88f7f06ec82d59453b

Added automated test in dd7dc2882890255d94f70cdbc963a140d84dc04c so we always have this case working fine for prefabs
