### ISSUE TITLE
GenerateProjectFiles.bat

### ISSUE THREAD

**Issue by Timor666** [FlaxEngine/FlaxEngine#102]
从GitHub上下载zip项目，第一次运行GenerateProjectFiles.bat时出现。
安装Windows 8.1 SDK或更高版本
为桌面安装Microsoft Visual C ++ 2015.3 v140工具集（x86，x64）
![111](https://user-images.githubusercontent.com/35324214/103845309-c5ff5300-50d6-11eb-8b2d-e7d992ec2d74.png)
![111](https://user-images.githubusercontent.com/35324214/103845853-e24fbf80-50d7-11eb-985e-649acc841086.png)

好吧，我再换个方法试试。
![111](https://user-images.githubusercontent.com/35324214/103846314-cac50680-50d8-11eb-9c44-675c134aefbd.png)
![QQ截图20210107110652](https://user-images.githubusercontent.com/35324214/103846322-cef12400-50d8-11eb-8303-90e5333deca5.png)
![1](https://user-images.githubusercontent.com/35324214/103846327-d1ec1480-50d8-11eb-8740-bf76f773b2d2.png)

![22](https://user-images.githubusercontent.com/35324214/103846482-2a231680-50d9-11eb-962f-4d9f3ee8cc51.png)

不知道为什么会出现，请原谅我是个菜鸟。
-
![1111](https://user-images.githubusercontent.com/35324214/103845031-2e9a0000-50d6-11eb-91cb-a89c404fe4da.png)
![2222](https://user-images.githubusercontent.com/35324214/103846657-943bbb80-50d9-11eb-9983-59fa2cc02d5e.png)

**Comment by stefnotch** [comment]
We sadly don't have any Chinese developers on the team and I'm slightly struggling with figuring out how to type the characters into Google Translate.

Could you post the error logs either in English or at least as plain Chinese text instead of screenshots?

**Comment by mafiesto4** [comment]
It looks like missing binary files. The solution is to clone repo with LFS.
