### ISSUE TITLE
Create Multiple Collision Assets dont work

### ISSUE THREAD

**Issue by RuanLucasGD** [FlaxEngine/FlaxEngine#1028]
[This implemented feature](https://github.com/FlaxEngine/FlaxEngine/commit/2eea7abc2771c9cea67f3f3aa0c54f1337e63317) don't work for many meshs.

Many collision assets are created with null Mesh.

**Comment by mafiesto4** [comment]
Fixed: 37032810c96212d3a61cdc3993f69afb12eb2714
