### ISSUE TITLE
OpenAL audio quality is low or lacking bass

### ISSUE THREAD

**Issue by GoaLitiuM** [FlaxEngine/FlaxEngine#1032]
Audio clips played in the Editor and also in-game seems to lack bass or sound much worse than the original asset:

https://user-images.githubusercontent.com/4064397/233784472-84c2873b-4bda-4456-bc97-0044b08d8bc0.mp4

With XAudio2-backend enabled in the engine, the clip in Editor sounds exactly the same as in other programs.

The audio sample used in the clip:
[whooshimpact012.zip](https://github.com/FlaxEngine/FlaxEngine/files/11301313/whooshimpact012.zip)

**Comment by mafiesto4** [comment]
Could you try reimporting this asset with the latest `master` or `1.6` branch?

I tried and it seams to be quite close to the original now:

https://github.com/FlaxEngine/FlaxEngine/assets/3464853/bfa2a044-582e-4c2d-8e32-5a0e8bb46552

**Comment by GoaLitiuM** [comment]
No difference. I think I tried these changes after the recent refactoring, and I noticed the issues sometime last year, so it didn't regress from those changes.

**Comment by GoaLitiuM** [comment]
It also happens with mono-channel sound samples as well. I also tried changing my audio output device sample rate from 48khz to 44.1khz to rule out resampling, but that didn't affect this at all.

**Comment by GoaLitiuM** [comment]
HRTF was causing this, I had no idea it was enabled by default and XAudio2 had no support for it right now.
