### ISSUE TITLE
Editor Crash when remove Particle Emitter from Particle System

### ISSUE THREAD

**Issue by RuanLucasGD** [FlaxEngine/FlaxEngine#1044]
**Issue description:**
When i remove some particle emitter that contains parameters, the editor crashes.

**Steps to reproduce:**
1. Create a Particle Emitter.
2. On your emitter, add parameters.
3. Create a Particle System.
4. Add your emitter on your particle system
5. Select your emitter on Particle System editor
6. Enable emitter parameters.
7. Try to remove the emitter from particle system.
8. The Editor crashes.

**Minimal reproduction project:**

[Debug 2023.04.24 - 12.55.27.01.webm](https://user-images.githubusercontent.com/79365912/234066297-a9d8e1e6-d914-44f9-82be-c55d3b2c4c46.webm)

**Flax version:**
1.5 master

**Comment by mafiesto4** [comment]
Thanks for reporting this. Fixed in 285a824858670f9d52dc92327819a1b010169183
