### ISSUE TITLE
[Improv usability] Save subgroups state

### ISSUE THREAD

**Issue by RuanLucasGD** [FlaxEngine/FlaxEngine#1049]
**Issue description:**
when i open a subgroup and select another actor, the subgroup opened isn't saved and when i reselect actor  i need to open the sub group again.

Please save the subgroup state so i don't need to reopen the subgroup.

**Steps to reproduce:**

[Desktop 2023.04.26 - 22.10.35.02.webm](https://user-images.githubusercontent.com/79365912/234742864-69b2cef5-fb1f-4adc-9d56-5d530382b61a.webm)

**Flax version:**
1.5

**Comment by mafiesto4** [comment]
Implemented in c305bed829f8a973337e054b87b1af898ff371f3

**Comment by RuanLucasGD** [comment]
@mafiesto4 lovi u
