### ISSUE TITLE
Inconsistent Vehicle Moviment Direction

### ISSUE THREAD

**Issue by RuanLucasGD** [FlaxEngine/FlaxEngine#1050]
**Issue description:**
I made a simple vehicle but when I accelerate the vehicle it is moved right or left but it is wrong because the forward is Z not X.

**Expected**

![image](https://user-images.githubusercontent.com/79365912/234916916-6b62dae5-c256-4223-a05d-79a166aa0965.png)

**Reality:**

[Desktop 2023.04.27 - 11.51.07.01.webm](https://user-images.githubusercontent.com/79365912/234917472-262761bf-4b68-46a4-bf5a-a40d1745c498.webm)

And also the debug gizmos are in incorrect direction.

**Minimal reproduction project:**
[VehicleTest.zip](https://github.com/FlaxEngine/FlaxEngine/files/11345768/VehicleTest.zip)

**Flax version:**
1.6

**Comment by Tryibion** [comment]
I took a look at this. I think the biggest issue is that a forward axis direction can not be set. By default the vehicle has to be setup to face the x-axis as its forward axis. This vehicle is facing the z-axis and that is why it is not working. 

Here is the vehicle with the x direction as forward for the colliders:
https://github.com/FlaxEngine/FlaxEngine/assets/71274967/250572dc-5434-4498-bdad-38b5a04dc4e3

**Comment by RuanLucasGD** [comment]
yes, it gets confusing, all other objects the corrector would be Z, but the vehicle breaks this pattern

**Comment by mafiesto4** [comment]
Fixed in f1c98320fcc7f559d49458f696e21c7f7b581d6a.

Updated docs, added migration guide entry and updated default car prefab in docs: https://github.com/FlaxEngine/FlaxDocs/commit/cb5cc97d02b167e1d022d18fc9ae0c366ac68fda
