### ISSUE TITLE
Add close list item no list/array fields

### ISSUE THREAD

**Issue by RuanLucasGD** [FlaxEngine/FlaxEngine#1057]
It would be nice if array/list fields can close/open elements.

This request it's a complement of #803 

**Like this:**

![image](https://user-images.githubusercontent.com/79365912/235317539-bf5e6d76-338e-4099-87db-f5ef5e760db7.png)

**Actually in Flax:**

Each element is very large and cannot be closed, which makes it difficult to work with a lot of data.

![image](https://user-images.githubusercontent.com/79365912/235318117-9e1d2ef1-af0d-4dae-8056-31382e191db2.png)

**Flax version:**
1.6

**Comment by mafiesto4** [comment]
Added in #2208
