### ISSUE TITLE
Flax stops responding when exception gets thrown in certain methods

### ISSUE THREAD

**Issue by stefnotch** [FlaxEngine/FlaxEngine#106]
**Issue description:**
Okay, I've been implementing the node autoformatter and realized that some errors don't get caught properly but rather lead to Flax being unresponsive.

**Steps to reproduce:**
1. In [`VisjectSurface.ContextMenu.cs`](https://github.com/FlaxEngine/FlaxEngine/blob/d586f828b223152959371aa60c7c160787864cf9/Source/Editor/Surface/VisjectSurface.ContextMenu.cs#L152), I added
```cs
menu.AddButton("Format node(s)", () =>
{
  throw new System.Exception("crashy crashy");
});
```
2. Build Flax
3. Start Flax with the debugger attached
4. Open a material, open the context menu and click on `Format node(s)`

**Flax version:**
Flax 1.0

**Comment by mafiesto4** [comment]
Not a case anymore.
