### ISSUE TITLE
LocalizationSettings, "Add Locale" not working

### ISSUE THREAD

**Issue by ReyAnthony** [FlaxEngine/FlaxEngine#1060]
**Issue description:**
In LocalizationSettings, "Add Locale" is not working.

[ 00:02:49.122 ]: [Info] Adding culture 'en - English' to localization settings
[ 00:02:49.123 ]: [Warning] Win32::GetLastError() = 0x3
[ 00:02:49.123 ]: [Error] Cannot save 'FlaxEngine.LocalizedStringTable, 05dd387846c3415a3cc136b036d4ecc4, C:\Users/areyb/AppData/Local/Temp/6c6aa76a-4598-5cc1-b818-6389f0ad651a/554a4556498bba0fc71b7fbd5b97b583.flax'

**Steps to reproduce:**
- Create Blank Project 
- Go to LocalizationSettings 
- Click Add Locale and select any locale in the picker

**Minimal reproduction project:**
Can be reproduced on the empty project template

**Potentially useful specifics** 
Using a computer on which Windows is setup to French

**Flax version:**
1.5.6339

**Comment by ReyAnthony** [comment]
Tested and not reproducing on 1.4.6334

**Comment by mafiesto4** [comment]
Thanks for reporting this. Fixed in 37e8fa7b767916c764567a877c4af2803d4d5cb2
