### ISSUE TITLE
Submitting original text in `TextBox` does not trigger `EditEnd`

### ISSUE THREAD

**Issue by Withaust** [FlaxEngine/FlaxEngine#1074]
**Issue description:**
`TextBox` does not dispatch `EditEnd` when submitting empty string.

**Flax version:**
Flax 1.5.6339 on Windows 10 x64

**Comment by mafiesto4** [comment]
What are the reproduction steps for this issue? I tested setting the text field to empty test and confirming with `Enter` which triggers `EditEnd` properly.

**Comment by Tryibion** [comment]
Looking at the code that the PR removes, I am guess that it is because they are starting from an empty string and then trying to submit an empty string, so the starting and ending value are both empty strings and not triggering the actions.

**Comment by Withaust** [comment]
Yeah, sorry for confusion, I originally thought that this issue was due to empty string,s but it turns out that it was primarily due to the "sameness" check that I have deliberately removed with my commit.

**Comment by mafiesto4** [comment]
Why the event should be triggered if the text doesn't change? We have lots of placed in the Editor where that event is used to handle text modification in the end.

**Comment by Withaust** [comment]
Then I am not sure which event I am supposed to be listening for. Example: I have a chat box.
1. Player presses open chat button
2. TextBox grabs focus
3. Player decides not type anything and instead presses ESC/Enter which loses focus of the TextBox
4. Sameness check prevents from dispatching any events
5. ???
6. Profit?

**Comment by mafiesto4** [comment]
You can handle this with `KeyDown` event or override `OnEditEnd` in a custom text box inside your game project.
