### ISSUE TITLE
Delete Folder don't work correctly

### ISSUE THREAD

**Issue by RuanLucasGD** [FlaxEngine/FlaxEngine#1084]
If i try to delete a folder from left Content panel, sometimes it doesn't work.

[Debug 2023.05.07 - 10.20.35.03.webm](https://user-images.githubusercontent.com/79365912/236683904-b4daed37-a625-4555-823f-76facf47953c.webm)

**Flax version:**
   master

**Comment by Tryibion** [comment]
Are there any logs or exceptions thrown?

**Comment by RuanLucasGD** [comment]
@Tryibion nop

**Comment by mafiesto4** [comment]
Fixed in 159fb8f5eec7e1b4d1c65b4aeb02271a44d01c82
