### ISSUE TITLE
The size of the editor window doesn't return completely after minimizing

### ISSUE THREAD

**Issue by TheJustLink** [FlaxEngine/FlaxEngine#1090]
**Issue description:**
The size of the editor window doesn't return completely after minimizing 🤔

Normal size/position:
![image](https://user-images.githubusercontent.com/29580493/237052542-22f6f3bd-038b-47e7-acba-525c03fcda30.png)
After minimize:
![image](https://user-images.githubusercontent.com/29580493/237052711-df2779a0-f598-4196-ac8f-7209615a509f.png)

I constantly have to return to windowed mode, and then to maximized mode to get the correct size back 🙈

**Steps to reproduce:**
1. Maximize Editor window
2. Minimize Editor
3. Go back to the Editor

**Flax version:** last 1.6, 1.5

**Comment by mafiesto4** [comment]
Fixed in b5d927baa542f2320b0d23b81708301159a21285.
