### ISSUE TITLE
Area lights (source radius, source length in PointLight/SpotLight) don't work

### ISSUE THREAD

**Issue by TheJustLink** [FlaxEngine/FlaxEngine#1094]
**Issue description:**
Area lights (source radius, source length in PointLight/SpotLight) don't work.

I also think it would be nice to add the ability to create square lamps. Or the ability to set the source length in multiple dimensions.

In scene view:
![image](https://github.com/FlaxEngine/FlaxEngine/assets/29580493/81ac1205-9efb-4d8b-bb01-a699dd5af91d)
In game:
![image](https://github.com/FlaxEngine/FlaxEngine/assets/29580493/c9c053b9-6e18-4ccf-aeff-401fc6d03ee6)

**Flax version:** 1.6

**Comment by mafiesto4** [comment]
They do work but affected is mostly by specular highlights. The diffuse part is missing the area-light modification.

**Comment by mafiesto4** [comment]
If you want to have diffuse with area light properly attenuate then use `Inverse Squared Falloff` on a light (as light on the right):

![image](https://github.com/FlaxEngine/FlaxEngine/assets/3464853/3e806fc2-8eca-4f79-9a2c-bd9cc3c147ec)

**Comment by TheJustLink** [comment]
Thank you! It might be useful to add this clarification to the documentation as well 🤔
