### ISSUE TITLE
Win32 in solution configuration

### ISSUE THREAD

**Issue by stefnotch** [FlaxEngine/FlaxEngine#11]
**Issue description:**
It's possible to select Win32 from the solution configuration. This causes errors to pop up everywhere.

e.g. BasicTemplate
![image](https://user-images.githubusercontent.com/10220080/102695960-2105fe80-422b-11eb-8931-14ddbdbbb614.png)

Is Win32 intentionally left in the solution configuration? Would it be better to change [Flax.Build](https://github.com/FlaxEngine/FlaxEngine/blob/master/Source/Tools/Flax.Build/Build/Builder.Projects.cs) so that it's excluded? (And under which circumstances?)

**Steps to reproduce:**
1. Open the basic template Flax Sample in Visual Studio
2. Open a random script
3. Switch from `Win64` or `Any CPU` to `Win32`
4. Wait a bit

**Minimal reproduction project:**
[Flax Samples](https://github.com/FlaxEngine/FlaxSamples/)

**Flax version:**
Flax 1.0

**Comment by mafiesto4** [comment]
I guess we could improve configurations picking for win32 or drop support for it anyway soon.

**Comment by mafiesto4** [comment]
Finally fixed in #1466
