### ISSUE TITLE
Issue with dragging `ActorTreeNode` in 1.6 branch

### ISSUE THREAD

**Issue by Tryibion** [FlaxEngine/FlaxEngine#1104]
**Issue description:**
Trying to drag an actor tree node to drop it into the properties of another actor will not work because it selects the node that is being dragged.

https://github.com/FlaxEngine/FlaxEngine/assets/71274967/6a1469a3-b7c8-45db-aa9d-a211bb642d37

**Steps to reproduce:**
Try dragging an ActorTreeNode, it will select the node.

**Flax version:**
1.6.6340

**Comment by mafiesto4** [comment]
Fixed in 1af69421fa5c9bb36238c215f4644044aadfee29 (will merge back into 1.6 branch)

**Comment by Tryibion** [comment]
Hmm I am still having this issue after that commit.

**Comment by Tryibion** [comment]
Nevermind, I did a clean of the engine binaries and cache and then it started working. Thanks!
