### ISSUE TITLE
Flax Engine Crashes: DirectX 11 Error

### ISSUE THREAD

**Issue by AirtonGamer** [FlaxEngine/FlaxEngine#1111]
**Issue description:**
When i open a project in Flax Engine it doesn't open and shows an error saying:
**DirectX error: E_INVALIDARG at
F:\FlaxEngine\Source\Engine\GraphicsDevice\DirectX\DX11/GPUShader
DX11.cpp:142**

**Steps to reproduce:**
open a project in Flax Engine

**Minimal reproduction project:**
Any of the Sample Projects

**Flax version:**
Flax Engine 1.5

i think the cause of the problem is my gpu as it:
Intel hd graphics 3000 which supports only DirectX 10.1 although in the requirments page it says it support DirectX 10 and higher

**Comment by mafiesto4** [comment]
Intel GPU drivers lack quality. It's been a known problem for many years. You could try using `Vulkan` by running Flax with `-vulkan` command line (https://docs.flaxengine.com/manual/editor/advanced/command-line-access.html or via Launcher cmd arg option for engine installation).
