### ISSUE TITLE
Footstep Sounds Improvements

### ISSUE THREAD

**Issue by PhyresiCompany** [FlaxEngine/FlaxEngine#1112]
It is not possible to extract 100% of the Footstep Sounds system in the Flax Engine because it is not possible to use this system for several biomes in the terrain

**(Demo video with audio)**

https://github.com/FlaxEngine/FlaxEngine/assets/101017436/c4375c31-fd10-4f06-b88f-1e661f9bb7bf

In Unreal it is possible because the Physical Material, in addition to being able to be attached to the Physics Collider, is also possible to attach to the material graph
![Captura de Tela (100)](https://github.com/FlaxEngine/FlaxEngine/assets/101017436/60dda523-4568-438c-8ef2-e1de9087477d)

Unreal Engine creates a LayerInfo file for each layer to allow you to add a Physical Material for each layer separately
 In Flax I didn't find anything about a LayerInfo file

https://github.com/FlaxEngine/FlaxEngine/assets/101017436/728d26fa-0ae9-4b3b-b0cd-cc09291ec1bc

**LayerInfo**
![Captura de Tela (99)](https://github.com/FlaxEngine/FlaxEngine/assets/101017436/8cbfc2e8-80ab-4b19-8145-0cec96d4aa01)

In Flax Engine it is only possible to add Physical Material only in a PhysicsColliler
![Captura de Tela (101)](https://github.com/FlaxEngine/FlaxEngine/assets/101017436/29194924-a2b4-4ecf-bd49-35f2f06e1962)

**Improvements**
- To improve footstep sounds in Flax Engine, you need to allow adding physical material in material graph
- And also create a LayerInfo for each terrain layer and in the LayerInfo allow adding a Physical Material

**Comment by RuanLucasGD** [comment]
If add a collision layer for each terrain material layer is a great feature

**Comment by mafiesto4** [comment]
Added in https://github.com/FlaxEngine/FlaxEngine/commit/42b4443e14030baca6658eb525b1e064041dec4a.

Tutorial: https://github.com/FlaxEngine/FlaxDocs/blob/9f61338e5abc583163f6cf37f8381108333d4de3/manual/physics/tutorials/footsteps.md
