### ISSUE TITLE
Improvements to the Visual Graph

### ISSUE THREAD

**Issue by PhyresiCompany** [FlaxEngine/FlaxEngine#1114]
**Add Context Sensitive to Node Search**
Dragging a node shows only the possible nodes this parameter can connect to
![Captura de Tela (98)](https://github.com/FlaxEngine/FlaxEngine/assets/101017436/da3a1824-bacb-453c-9af9-0db7481e09ce)

**Comment by mafiesto4** [comment]
Added in #1522 (in future we will keep improving it to provide smarter contextual options)
