### ISSUE TITLE
Scale linking 🔗 doesn't work as expected

### ISSUE THREAD

**Issue by TheJustLink** [FlaxEngine/FlaxEngine#1117]
**Issue description:**
Scale linking 🔗 doesn't work as expected when one of the axis is zero.
It adds the change linearly ➕➖ to all axes. It doesn't preserve the proportion ✖️➗

**Steps to reproduce:**
1. Create a cube
2. Set scale (1; 0; 1)
3. Enable scale link
4. Change X or Z.

Original scale:
![image](https://github.com/FlaxEngine/FlaxEngine/assets/29580493/60b1e0c4-4493-4724-9f05-31466e321ffb)
Resulting scale:
![image](https://github.com/FlaxEngine/FlaxEngine/assets/29580493/4b390933-83c5-4184-b3b6-927f58bbac18)
Expected scale:
![image](https://github.com/FlaxEngine/FlaxEngine/assets/29580493/1fca16e8-8766-47a0-a3a1-23df547dfb56)

**Flax version:** Last 1.6, 1.5

**Comment by TheJustLink** [comment]
@Tryibion, Thank you! 👍
So, it's works fine for my case, but in case below not ⬇️

Original scale:
![image](https://github.com/FlaxEngine/FlaxEngine/assets/29580493/82c9a0ef-2d74-42ff-8f53-6849c6e5eff3)
Resulting scale:
![image](https://github.com/FlaxEngine/FlaxEngine/assets/29580493/807dbda1-419e-4af1-920b-58989969110f)
Expected scale:
![image](https://github.com/FlaxEngine/FlaxEngine/assets/29580493/a43e9755-8381-4602-b56c-d82eb9fd38c6)

In Unity this cases works as expected.
Try to get a vector ratio like in [Unity](https://github.com/Unity-Technologies/UnityCsReference/blob/5cdad00d1e7c84b665fd57bb779562502c4d40f6/Editor/Mono/Inspector/ConstrainProportionsTransformScale.cs#L161) 🤔

**Comment by Tryibion** [comment]
What are you trying to do in this case? I can not tell by the pictures...

**Comment by TheJustLink** [comment]
> What are you trying to do in this case? I can not tell by the pictures...

I changed the Y axis from 1 to 2.
(4; 1; 4) => (4; 2; 4).

I'am expect (8; 2; 8), but got (5; 2; 5). It doesn't keep the proportion 🔗

**Comment by Tryibion** [comment]
@TheJustLink Changed #1118  to fix that issue as well.

**Comment by TheJustLink** [comment]
👍 I will check it in free time (today/tomorrow)

**Comment by TheJustLink** [comment]
@Tryibion, Everything works great 👍
And I see that you've added other improvements, that's great!
Thanks for contribution!

**Comment by mafiesto4** [comment]
Fixed in #1118
