### ISSUE TITLE
Ctrl C+Ctrl V ing a prefab will not create a new prefab ID

### ISSUE THREAD

**Issue by Bits360** [FlaxEngine/FlaxEngine#1123]
**Issue description:**
Duplicating a prefab works fine, but ctrl c+ctrl v will cause it to be an exact copy, which will copy changes between the 2 prefabs, which has caused me so many problems.

**Steps to reproduce:**
Read above

**Minimal reproduction project:**
Can be replicated in any project

**Flax version:**
Can be replicated in any version, but am currently am on 1.5

**Comment by RuanLucasGD** [comment]
I confirm this, you can paste the prefab only in another folder, when you try modify the prefab all changes go to original asset, this is very bad

**Comment by mafiesto4** [comment]
Fixed in #1124
