### ISSUE TITLE
View Scale issue in ContentView

### ISSUE THREAD

**Issue by Tryibion** [FlaxEngine/FlaxEngine#1127]
**Issue description:**
Change the view scale in the content view below 0.61 will cause the editor to freeze.

**Steps to reproduce:**
Change the view scale to lower than 0.61.

**Flax version:**
1.6.6340. Does not happen on master branch.

**Comment by mafiesto4** [comment]
Fixed in 5a45ccf70dba13b0c56739220697b3597481ac87
