### ISSUE TITLE
UI - Dropdown WorldSpace

### ISSUE THREAD

**Issue by GhettoScouser** [FlaxEngine/FlaxEngine#1129]
UI dropdown closes when trying to select entries if **UI canvas** is set to **worldSpace** and **using mouse**

Make a UI canvas, set it to World Space then add a Dropdown control.
Add some entries to the dropdown.
Enter play mode and try and select different entries, Dropdown box will not change to any selected entries and will instead just close.

Also in project attached, rendering issue on dropdown.

FLAX ver: 1.5.6339

[Report.zip](https://github.com/FlaxEngine/FlaxEngine/files/11585426/Report.zip)

**Comment by mafiesto4** [comment]
Fixed in 6a482c987c7128688af7eb088f7c459b3b3b4d2c
