### ISSUE TITLE
Window bug fixes in Flax

### ISSUE THREAD

**Issue by PhyresiCompany** [FlaxEngine/FlaxEngine#1135]
- Bug when you reopen the engine with a window open you can't click on that window to open it.
You can only access this window if you close this window and open it again 🥲

https://github.com/FlaxEngine/FlaxEngine/assets/101017436/4454e2d5-0ad1-40f1-80e6-cd6cc1804dac

- Problem with SkinnedModel window in Dock Fill

https://github.com/FlaxEngine/FlaxEngine/assets/101017436/33954e4e-2fbf-4efd-adc2-47c93ab08919

- Another dev reported this other bug about Flax windows @TheJustLink
https://github.com/FlaxEngine/FlaxEngine/issues/1090

These problems with windows greatly hinder usability

**Comment by mafiesto4** [comment]
1) Fixed in 6cd45a58f891ad98bc9cc77a84ad9ccec1bb52c7.
2) Fixed in d0fbf12b926a1cc4b595889468b2581180bf85de.
3) Fixed in b5d927baa542f2320b0d23b81708301159a21285.
