### ISSUE TITLE
Add logs count on debug window

### ISSUE THREAD

**Issue by PhyresiCompany** [FlaxEngine/FlaxEngine#1136]
- To send less spam in the console do a grouping and add only the amount
![Captura de Tela (192)](https://github.com/FlaxEngine/FlaxEngine/assets/101017436/8ce3f1b2-a08f-4ae1-a328-8dffab4b4cff)

- Flax

https://github.com/FlaxEngine/FlaxEngine/assets/101017436/4dc18a2c-1088-47ec-8028-f6f4e669847c

**Example: False (3741)**

**Comment by mafiesto4** [comment]
Added in #1248
