### ISSUE TITLE
Crash when using SetRoot in Prefab

### ISSUE THREAD

**Issue by PhyresiCompany** [FlaxEngine/FlaxEngine#1138]
- I created a `Prefab` and when I used `SetRoot` Flax crashed and now I can't open my project anymore 

**My Project - Flax 1.6.6340**
https://drive.google.com/file/d/1GjOY_gesWEQZsY5umesg-ys4-q12aOqv/view?usp=sharing

**Crash**
[Log.txt](https://github.com/FlaxEngine/FlaxEngine/files/11620385/Log.txt)

**Log**
[Log_2023_05_31_22_08_09.txt](https://github.com/FlaxEngine/FlaxEngine/files/11620387/Log_2023_05_31_22_08_09.txt)

**Comment by TheJustLink** [comment]
Good catch! Please, as well, attach logs ("project folder"/Logs/ last txt log and crash log in Crash folder) in the future 🙏
[The crash log](https://github.com/FlaxEngine/FlaxEngine/files/11619328/CrashLog.txt)
[Project opening log after the crash](https://github.com/FlaxEngine/FlaxEngine/files/11619331/Log_2023_05_31_22_08_09.txt)

**Comment by PhyresiCompany** [comment]
> Good catch! Please, as well, attach logs ("project folder"/Logs/ last txt log and crash log in Crash folder) in the future 🙏 [The crash log](https://github.com/FlaxEngine/FlaxEngine/files/11619328/CrashLog.txt) [Project opening log after the crash](https://github.com/FlaxEngine/FlaxEngine/files/11619331/Log_2023_05_31_22_08_09.txt)

@TheJustLink  Thanks

**Comment by mafiesto4** [comment]
Weird that nested prefab was not properly updated after changing root of the base prefab. Probably due to file revert via version control or via undo. Anyway this needs to be fixed.

**Comment by PhyresiCompany** [comment]
> 

@mafiesto4 Thanks
