### ISSUE TITLE
Visual Studio Code script projects lack code completion

### ISSUE THREAD

**Issue by GoaLitiuM** [FlaxEngine/FlaxEngine#115]
Generated VSCode projects does not have the required information for C# Omnisharp extension to enable Intellisense/code completion support. Omnisharp uses VS solution and project files for Intellisense, so these files needs to be generated for VSCode projects as well.

Workaround for this issue is to generate VS2019 project files first followed by generating VSCode project files, then Omnisharp active project (`Omnisharp: Select Project` in Command Palette) must be changed to the generated solution file, after that Intellisense starts working properly for the game project.

**Comment by GoaLitiuM** [comment]
Intellisense is only partially working, the correct `Script` class for example can't be found, showing the following errors:
![image](https://user-images.githubusercontent.com/4064397/109684135-a6415400-7b88-11eb-8c2e-4b41d162b1d0.png)

**Comment by mafiesto4** [comment]
In `1.1` it works fine in pre-built engine. The problem persist when using source-build engine due to using generated bindings code (`*.Gen.cs` files eg. from `Cache/Intermediate/FlaxEditor/Windows/x64/Debug/Scripting/Scripting.Gen.cs`).
