### ISSUE TITLE
Add `Play Game` button, and rename current button into `Play Scenes`

### ISSUE THREAD

**Issue by Withaust** [FlaxEngine/FlaxEngine#1151]
**Issue description:**
Currently, if you were going to load up any arbitrary scenes in any order in the editor and press `Play Game` its not really the game that you are playing, but that specific arbitrary set of scenes. There needs to be a separate button that would start the game from the `First scene` in according with the game settings, since a lot of the games cant really just outright launch on any arbitrary scene and work as expected. If this feature would get implemented, current `Play Game` would also have to be renamed into `Play Scenes` instead.

**Comment by mafiesto4** [comment]
Maybe we could add option in Editor Options to allow users to specify what play button does? Like playing current scene, or playing the first scene or maybe use `Cook & Run` option to run a standalone game?

**Comment by Withaust** [comment]
Implemented with https://github.com/FlaxEngine/FlaxEngine/pull/1215
