### ISSUE TITLE
Problems with Spline

### ISSUE THREAD

**Issue by PhyresiCompany** [FlaxEngine/FlaxEngine#1158]
**Flax 1.6.6340**
- It is not possible to create new `Spline Keyframes` with the shortcut `CTRL + D` and it is not possible to delete the Spline.

https://github.com/FlaxEngine/FlaxEngine/assets/101017436/7c9113e6-bb81-4084-b4ef-d637109cdefa

- The Spline Actor has the `Spline Keyframes` parameter. For me it doesn't appear

![14](https://github.com/FlaxEngine/FlaxEngine/assets/101017436/2de45f86-d26a-4c72-8bf3-ab18c583b11b)

- When I set the Material to `Deformable` the model is invisible in the `ModelWindow` and `CollisionWindow`

https://github.com/FlaxEngine/FlaxEngine/assets/101017436/72c6f871-c532-4f3d-a97c-8a4a86d96397

**ABC Project:**  https://drive.google.com/file/d/1CeRkefGW9Z0gQe5h4aLzw1ceBjmCsqAY/view?usp=sharing

[Output Log.txt](https://github.com/FlaxEngine/FlaxEngine/files/11713690/Output.Log.txt)

**Comment by RuanLucasGD** [comment]
#1292

**Comment by mafiesto4** [comment]
1) Works now. Also, move+shift duplicates selected keyframe as well.
2) Works on the latest master
3) Won't fix as it's how the material shader is generated and used for now.
