### ISSUE TITLE
Game mode tweaks

### ISSUE THREAD

**Issue by PhyresiCompany** [FlaxEngine/FlaxEngine#1159]
- Allow using Transform Gizmo in game mode

https://github.com/FlaxEngine/FlaxEngine/assets/101017436/cb561040-cc9f-4e76-956a-2fa1683f1734

- Allow use of Pilot Actor in game mode

https://github.com/FlaxEngine/FlaxEngine/assets/101017436/86e815da-d440-4e53-be75-87b2638bad71

**Comment by RuanLucasGD** [comment]
You can move your Actor using Transform gizmo if you set "Static Flags" to none

**Comment by RuanLucasGD** [comment]
I don't know if use "Pilot mode" on game mode is a nice feature, because the camera can be controled from any script. If add pilot mode can be conflict with scripts
