### ISSUE TITLE
Spawning multiple prefabs with a task crashes

### ISSUE THREAD

**Issue by W2Wizard** [FlaxEngine/FlaxEngine#116]
**Issue description:**
After many hours of trying to pin down the issue as to why Flax keeps getting a stroke and just crashes everytime I spawn my prefabs I was able to write some code that reproduces my issues exactly.

The issue is the following, I want to spawn a lot of prefabs however on a separate thread in order to avoid blocking the main thread as I do some additional heavy calculations while looping.
Below is a code snippet that is similar to what I'm doing. It will run just fine at first, however, after multiple executions the editor completely crashes.

I executed the function below using a custom script editor that just adds a button inorder to invoke it, when pressing the button multiple times, usually after 2-3 times, the editor's UI completely dies and when checking the logs it is full of errors.

It does not matter if I disable the button to avoid multiple threads, wait till the previous thread is done executing, etc etc. After a couple clicks the editor will inevitably crash.

After the executing the function multiple times: (Resuts may vary)
![image](https://user-images.githubusercontent.com/63303990/104859324-cee8f380-5924-11eb-9197-e98a6fec78b8.png)

**Log + Minidump:**
[Download Log + MiniDump](https://github.com/FlaxEngine/FlaxEngine/files/5827022/Crash_Log%2BMiniDump.zip)

**Steps to reproduce:**
1. Create a new C# Script and a scene in a blank project (or any project).

2. In your script class paste the following code:

```csharp
// Prefab to spawn
public Prefab Prefab;

// List to keep track of our actors
private List<Actor> actors = new List<Actor>();

// Using OnStart will cause a similar but different issue as well!
public async void RunTask()
{
    Debug.Log("Running construction");

    await Task.Run( () => 
    {
        // First clean up all old actors
        actors.ForEach((actor) => Destroy(actor));

        // Simulate some form of heavy task or calculation in here
        for (int i = 0; i < 25; i++)
        {
            for (int y = 0; y < 25; y++)
            {
                actors.Add(PrefabManager.SpawnPrefab(Prefab));
            }
        }
    });

    Debug.Log("Finished construction");
}
```

3. Create a new C# script and paste now the following into it, this is for the CustomEditor in order to invoke the function.

```csharp
#if FLAX_EDITOR
using FlaxEditor.CustomEditors;
using FlaxEditor.CustomEditors.Editors;
using FlaxEngine;


namespace Game
{
    [CustomEditor(typeof(<YourClass>))]
    public class <YourClass>Editor : GenericEditor
    {
        private static <YourClass> Script;

        public override void Initialize(LayoutElementsContainer layout)
        {
            Script = Values[0] as <YourClass>;

            // Button
            var genButton = layout.Button("Execute", Color.DimGray);
            genButton.Button.Clicked += () => Scripting.InvokeOnUpdate(() =>
            {
                Script?.RunTask();
            });

            base.Initialize(layout.Group("Settings"));
        }
    }
}
#endif
```

4. Compile everything, assign the script to something and then assign a prefab.
5. Hit 'Execute' multiple times and watch Flax die, when closing a error is prompted and the log is made.

**Minimal reproduction project:**
[Reproduction project](https://github.com/FlaxEngine/FlaxEngine/files/5827061/RIPFlax.zip)

**Flax version:**
1.0.6215

**Comment by jb-perrier** [comment]
As a first reply, you should not spawn prefab / actor on any other thread than the main one.
https://docs.flaxengine.com/manual/scripting/advanced/multithreading.html
