### ISSUE TITLE
Suggestion of Variable Hook in High Level Network

### ISSUE THREAD

**Issue by PhyresiCompany** [FlaxEngine/FlaxEngine#1172]
**Basically you call a function when the value of a variable changes**

- `Mirror` in Unity has `SyncVar Hooks` https://mirror-networking.gitbook.io/docs/manual/guides/synchronization/syncvar-hooks
- `Unreal` has `RepNotifies` https://docs.unrealengine.com/5.2/en-US/multiplayer-programming-quick-start-for-unreal-engine/#2.replicatingtheplayer'shealthwithrepnotifies

**I didn't find anything like this hook system in Flax doc about NetworkVariable.
The hook variable system would be a great feature for the High Level Network if Flax doesn't already have it.** https://docs.flaxengine.com/manual/networking/high-level.html?tabs=code-csharp#object-serialization

**Comment by mafiesto4** [comment]
In Flax, you can use properties to receive value modification notification.
```cpp

private:
    float MyValue = 0.0f;

public:

    API_PROPERTY(NetworkReplicated) float GetMyValue() const { return MyValue; }
    API_PROPERTY(NetworkReplicated) void SetMyValue(float value)
    {
        if (MyValue != value)
        {
            MyValue = value;
            // run custom logic...
        }
    }
```

Maybe we could add an additional utility so the setter function could check whether a value is modified by the replication system, not the local gameplay.

**Comment by PhyresiCompany** [comment]
@mafiesto4 OK. Thanks, and also the modification notification should persist for all clients, even those that later connect to the server/game

**Comment by Withaust** [comment]
> @mafiesto4 OK. Thanks, and also the modification notification should persist for all clients, even those that later connect to the server/game

I mean, it already will be, since when the game would start syncing all networked properties, it would also get assigned with the latest data according to the server.
