### ISSUE TITLE
Play the game in more than one instance

### ISSUE THREAD

**Issue by PhyresiCompany** [FlaxEngine/FlaxEngine#1173]
- Add field for number of instances
- Add a DropDown on the game type: `Standalone / Server / Client`

**Standalone:** Local play without network
**Client:** Clients connect to a remote server.
**Server:** It has a server that also has a local player that is hosting the game, available to other players on the network.

With these improvements it will facilitate the usability of the `High Level Network` to encode.

https://github.com/FlaxEngine/FlaxEngine/assets/101017436/4d256023-8a96-42c4-b7d3-ba804677b557

**Comment by mafiesto4** [comment]
Added in #1215
