### ISSUE TITLE
Rename executable according to settings

### ISSUE THREAD

**Issue by PhyresiCompany** [FlaxEngine/FlaxEngine#1174]
Currently when a build is done in **Flax** the name of the executable is `FlaxGame`

![Captura de Tela (378)](https://github.com/FlaxEngine/FlaxEngine/assets/101017436/dc707b61-3f5c-4a02-bdda-6c7454608510)

- My suggestion is that the **Product Name** of the `GameSettings` file receives the name defined when creating our project.
- And the name of the executable will be the same as the **Product Name**

![Captura de Tela (380)](https://github.com/FlaxEngine/FlaxEngine/assets/101017436/364417d1-ae01-4066-ad14-823c165b26b0)

**Comment by mafiesto4** [comment]
Added in 640f3802375f994658a42338842dfa51ceadf675.

Some other changes related to this feature: 6af6edb4feffd53ea0b6151a49851aa8358b9fd6 + 6cad1e33093d53579586954eb6b108c3fa154e19 + ee6a3114061d180ad9a31e8a7c95cc51c1c95a19
