### ISSUE TITLE
Build dedicated server

### ISSUE THREAD

**Issue by PhyresiCompany** [FlaxEngine/FlaxEngine#1175]
- Add a tab to do a `Windows` or `Linux` build for the Dedicated Server

![Captura de Tela (382)](https://github.com/FlaxEngine/FlaxEngine/assets/101017436/ccbf7199-ab7d-4f27-85cf-1afe5461e9ed)

**Comment by mafiesto4** [comment]
Game Cooker presets handle this: building custom configurations (eg. including build defines injection) which can be called from Editor UI or via Editor Command Line:

https://docs.flaxengine.com/manual/editor/game-cooker/index.html#presets
