### ISSUE TITLE
ConvexMesh doesn't work on my model

### ISSUE THREAD

**Issue by PhyresiCompany** [FlaxEngine/FlaxEngine#1176]
1. Flax is closed when using `Cook` on `ConvexMesh`

![Captura de Tela (386)](https://github.com/FlaxEngine/FlaxEngine/assets/101017436/58b779c0-f77d-48dc-839f-dc76d720c1de)

**Download the Model:** [Tractor.zip](https://github.com/FlaxEngine/FlaxEngine/files/11749658/Tractor.zip)

**Comment by mafiesto4** [comment]
Fixed in 329a6ce0efd617bf2d54a1ffeacb6906c96649d2

**Comment by Withaust** [comment]
I hope you are not planning on using that in production

**Comment by Withaust** [comment]
> It was just PhysX Conex Mesh Cooking allocation so should be fine, then runtime uses small and fast convex for collisions.

I was talking to OP about that abysmal collision mesh :P

**Comment by PhyresiCompany** [comment]
@mafiesto4 Thanks
