### ISSUE TITLE
Implement/allow for networked variables to ONLY be synced upon initial replication

### ISSUE THREAD

**Issue by Withaust** [FlaxEngine/FlaxEngine#1178]
**Issue description:**
Sometimes you need to have a variable that would only get synced just once upon client joining, and then later on managed through external RPC calls. 

**Reason:**
This is primarily used in games that enforce client-sided simulation of an entity that does some constant processing in the background, and the only events that change the course of internal simulation are the events from the server (example: Factorio, it uses the exact same system of clients simulating entire factories on their ends and only syncing stuff like player movement). This MASSIVELY frees up bandwidth if you know what you are doing, since you are no longer constantly updating those entity states every N-th tick, and are instead simulating everything on the client-side. But all of this is impossible without the mechanism of allowing to only sync states initially on connection, without any further automatic replication.

**Potential implementation:**
`ReplicationFPS` in `NetworkHierarchy` could be set to -1 for this, or maybe split `NetworkReplicated` attribute into `NetworkSync` and `NetworkSpawn`. And as for examples how other engines are handling this, here is how Godot is tackling this exact scenario:
![image](https://github.com/FlaxEngine/FlaxEngine/assets/118038102/a19aeb6b-26f1-4e14-8a10-b6fc1d4b1211)

**Comment by Withaust** [comment]
If there are people that might need a bandaid solution for this issue, just set object's `ReplicationFPS` in `NetworkHierarchy` to max int value.

**Comment by Withaust** [comment]
@mafiesto4 If I were going to implement this feature on my own, which approach should I pick for implementation? Lay it out in simple text form and I will use that as a reference for the implementation.

**Comment by mafiesto4** [comment]
@Withaust I think it's a big task to do as the current networking system doesn't have a per-property replication design but it's rather oriented around whole objects (eg. via replication hierarchy).

From the implementation site, `NetworkingPlugin` is responsible for automatic codegen for C++ and C#. It generates the network stream write/read functions and could in theory send/receive bit flags with replicated properties indices (each bit to mark each property sent). This could handle partial replication of the object to reduce network transfer usage. I would say it's a complex task.

https://github.com/FlaxEngine/FlaxEngine/blob/master/Source/Tools/Flax.Build/Build/Plugins/NetworkingPlugin.cs

**Comment by Withaust** [comment]
Fixed by https://github.com/FlaxEngine/FlaxEngine/pull/1188

**Comment by Withaust** [comment]
Did not really fix the issue, it simply prevented the object from replicating indefinitely under any circumstances.

**Comment by Withaust** [comment]
Even while implementing track keeping with `NetworkClientsMask` for every `NetworkReplicationHierarchyObject` in order to sync stuff only once, it looks like that `result->AddObject(obj.Object);` keeps being dropped if it only gets fired once in the update that changes the client list. This is really strange. Because of that, I cant even implement forcefully sync objects when I know that they require syncing.

**Comment by Withaust** [comment]
Also, objects with extremely low `ReplicationFPS` (like once per 10 seconds) also never get synced on join, so if you managed to join the server after this object has already been synced, you will have to wait 10 seconds for the next replication to make object up to date with the server.
