### ISSUE TITLE
Parameter bug in AnimationGraph

### ISSUE THREAD

**Issue by PhyresiCompany** [FlaxEngine/FlaxEngine#1183]
**Flax 1.6.6342**

**I used the Animation Graph as an example but this bug happens in any asset that I put add parameter**
- The bug happens with the bool parameter and with the float, but it is possible that it is also happening with other types

I was developing a project and I got this bug. I believe it may be related to the spline bug #1158 
I honestly believe there is something in 1.6 that is breaking some Flax actors/assets.

https://github.com/FlaxEngine/FlaxEngine/assets/101017436/c167bd39-9ff7-43d6-8b6e-b8da8b12fc79

Output Log 
[Log.txt](https://github.com/FlaxEngine/FlaxEngine/files/11782669/Log.txt)

**Comment by mafiesto4** [comment]
Thanks for reporting this. Fixed that regression in e17eed7029ffd63c46e7be1d4227769adc603dbc.
