### ISSUE TITLE
Bug in InputSettings Action/Axis

### ISSUE THREAD

**Issue by PhyresiCompany** [FlaxEngine/FlaxEngine#1184]
**Flax 1.6.6342**

If I set `Size to 0` and try to `Add a new item` I get an error
I believe this bug is related to this other bug in AnimationGraph parameters https://github.com/FlaxEngine/FlaxEngine/issues/1183

https://github.com/FlaxEngine/FlaxEngine/assets/101017436/c9b8fe42-b5df-4306-9763-317f5abd9bca

Output Log 
[Input OutputLog.txt](https://github.com/FlaxEngine/FlaxEngine/files/11782692/Input.OutputLog.txt)

**Comment by mafiesto4** [comment]
Fixed  in e17eed7029ffd63c46e7be1d4227769adc603dbc.
