### ISSUE TITLE
Problem in creating Particle Emitter

### ISSUE THREAD

**Issue by PhyresiCompany** [FlaxEngine/FlaxEngine#1193]
**Flax Engine 1.6.6342**

There is a bug in the creation of some particles

https://github.com/FlaxEngine/FlaxEngine/assets/101017436/0e21474e-3655-4821-b26f-10b14cf5926c

**Output Log:** [OutputLog Particle.txt](https://github.com/FlaxEngine/FlaxEngine/files/11796921/OutputLog.Particle.txt)

**Comment by Tryibion** [comment]
Same issue as #1103

**Comment by mafiesto4** [comment]
Fixed in #2418
