### ISSUE TITLE
Editor grid is rendering above particle emitter

### ISSUE THREAD

**Issue by tecnessino** [FlaxEngine/FlaxEngine#1196]
**Issue description:**
Editor grid is rendering above particle emitter

**Minimal reproduction project:**
  Just create a smoke particle emitter

**Flax version:**
Latest

**Comment by RuanLucasGD** [comment]
It also bothers other things. Grid is rendered above icons
![image](https://github.com/FlaxEngine/FlaxEngine/assets/79365912/b597707c-11c1-4a89-b259-aa853ac3be8d)

**Comment by mafiesto4** [comment]
Fixed in 64a7985376109c646fd9b38d6d01a7df4364b278.

![image](https://github.com/FlaxEngine/FlaxEngine/assets/3464853/467bf153-9464-4d96-af32-30ffac9bd193)

**Comment by mafiesto4** [comment]
Duplicate of #196
