### ISSUE TITLE
Custom Editor Window keeps opening new instance each time project is recompiled

### ISSUE THREAD

**Issue by MinhCT** [FlaxEngine/FlaxEngine#1208]
**Issue description:**

Following the tutorial stated here: https://docs.flaxengine.com/manual/scripting/tutorials/custom-window.html
Then, every time scripts are recompiled, all previous instances of the custom window got open again, and have not been disposed

**Steps to reproduce:**

1. Click the custom button to open the custom window, then close it
2. Go to File -> Recompile Scripts
3. One custom windows will appear
4. Keep doing step 1->3 until 2,3,4, etc. and more will appear

**Minimal reproduction project:**

[Demo.zip](https://github.com/FlaxEngine/FlaxEngine/files/11867491/Demo.zip)

https://github.com/FlaxEngine/FlaxEngine/assets/22948637/32b98109-b047-4f46-8e1e-e043b09ce495

**Flax version:**

1.5.6339

**Comment by mafiesto4** [comment]
Fixed in ac54838eea13d6caafb2c3dda75317d0f9becf69.
