### ISSUE TITLE
It is impossible to use `Array<T>` as an RPC argument

### ISSUE THREAD

**Issue by Withaust** [FlaxEngine/FlaxEngine#1209]
**Issue description:**
Currently, using something like this:
```cpp
API_FUNCTION(NetworkRpc = "Client, Reliable") void SendData(NetworkRpcParams info, Array<uint32>& ids);

void IComponent::SendData(NetworkRpcParams info, Array<uint32>& ids)
{
    NETWORK_RPC_IMPL(IComponent, SendData, info, ids);
}
```
results in generated code like this:
```cpp
static void SendData_Execute(ScriptingObject* obj, NetworkStream* stream, void* tag)
{
    Array ids;
    stream->Read(ids);
    ASSERT(obj && obj->Is<IComponent>());
    ((IComponent*)obj)->SendData(NetworkRpcParams(stream), ids);
}
```
which makes it impossible to use `Array<T>` as an RPC argument

**Flax version:**
[master](https://github.com/FlaxEngine/FlaxEngine/commit/9282bcfbbfaca4ed83bb2355f1292f40053df305)

**Comment by mafiesto4** [comment]
Ez fix in 04c1cf469d12d86a6f69ce7d70f667adf07cde98.

**Comment by Withaust** [comment]
@mafiesto4 If I am sending a byte stream in a reliable RPC call, what would be your recommendation for which container should I pick? I've been using Variant in a blob mode up until this fix, maybe there is a better way?

**Comment by mafiesto4** [comment]
`Variant` blob of data is fine. I would use `Array<byte>` as it's serialized to `int+data` while variant send additional `byte` which is it;'s type.

**Comment by Withaust** [comment]
> `Variant` blob of data is fine. I would use `Array<byte>` as it's serialized to `int+data` while variant send additional `byte` which is it;'s type.

Then it was a good thing that I've raised this problem then, thanks again!
