### ISSUE TITLE
Weird Behaviour on Update camera position / rotation 

### ISSUE THREAD

**Issue by RuanLucasGD** [FlaxEngine/FlaxEngine#1218]
I've been doing some camera control scripts. Sometimes very strange behavior happens that I have no idea if it was my fault or if it's a Flax bug. Basically I make a camera control script and then it behaves strangely, then I change anything in the code, it recompiles and it works fine. But that doesn't always work, sometimes I need to recompile the code several times for it to work again. Restarting the editor and clearing the cache doesn't work.

This has been quite disturbing.

It doesn't just happen to this project, it can happen to anyone.

https://github.com/FlaxEngine/FlaxEngine/assets/79365912/80e9acff-9e9e-40be-9df5-c99f7540bf6c

**project:**
[Car Test.zip](https://github.com/FlaxEngine/FlaxEngine/files/11895731/Car.Test.zip)

**Flax version:**
1.6

**Comment by Tryibion** [comment]
I can not seem to replicate this. What is your editor FPS?

**Comment by RuanLucasGD** [comment]
@Tryibion this happen sometimes in some projects. I need reload the editor or recompile the editor to fix this. Fps is normal, 60 always.

**Comment by RuanLucasGD** [comment]
this happen on 1.5 too

**Comment by RuanLucasGD** [comment]
another project, this don't happen in all projects, only sometimes...

[Third Person Camera Tutorial.zip](https://github.com/FlaxEngine/FlaxEngine/files/11926819/Third.Person.Camera.Tutorial.zip)




after many reloads, the code works fine (on minute 1:09):

https://github.com/FlaxEngine/FlaxEngine/assets/79365912/eac5a37b-b27d-443d-a017-3aacb1a75748

**Comment by Tryibion** [comment]
> another project, this don't happen in all projects, only sometimes...
> 
> [Third Person Camera Tutorial.zip](https://github.com/FlaxEngine/FlaxEngine/files/11926819/Third.Person.Camera.Tutorial.zip)
> 
> after many reloads, the code works fine (on minute 1:09):
> 
>  Desktop.2023.07.01.-.14.00.13.56.mp4

This one may just be jittering because you dont have any smoothing or use `Time.DeltaTime` to smooth out your camera orientation.

**Comment by RuanLucasGD** [comment]
@Tryibion can send your changes?

**Comment by Tryibion** [comment]
```
public override void OnUpdate()
        {
            UpdateCameraPosition();
            UpdateCameraRotation();
        }
        
        private void UpdateCameraRotation()
        {
            var _mouseX = Input.GetAxis("Mouse X") * MouseSensitive * Time.DeltaTime;
            var _mouseY = Input.GetAxis("Mouse Y") * MouseSensitive * Time.DeltaTime;
            

            _currentHorizonta222 += _mouseX;
            _currentVertical += _mouseY;
            _currentVertical = Mathf.Clamp(_currentVertical, MinRotation, MaxRotation);

            var _finalRotation = Quaternion.Euler(_currentVertical, _currentHorizonta222, 0);
            Actor.Orientation = Quaternion.Slerp(Actor.Orientation, _finalRotation, 0.1f);
        }
```

**Comment by RuanLucasGD** [comment]
@Tryibion this works for me, thanks!
But do you know why this problem happen only sometimes?

**Comment by Tryibion** [comment]
> @Tryibion this works for me, thanks!
> But do you know why this problem happen only sometimes?

Not really. My guess is that sometimes your "step" for the rotation is landing closer to the tick and other times it is not.

**Comment by RuanLucasGD** [comment]
@Tryibion thanks, i go to close this issue
