### ISSUE TITLE
Highlight selected skeleton node in model view

### ISSUE THREAD

**Issue by HydrogenC** [FlaxEngine/FlaxEngine#1220]
**Issue description:**
Now all the bone nodes are rendered in green. Please add a highlight to the selected bone node in the model view, or it will be difficult to figure out which bone corresponds to which name. 
![image](https://github.com/FlaxEngine/FlaxEngine/assets/33123710/a0b74bef-5b44-42cb-8068-d914ea695c08)

**Steps to reproduce:**
Import a skinned model and inspect it. 

**Minimal reproduction project:**
N/A

**Flax version:**
1.5.6339

**Comment by mafiesto4** [comment]
Added in 12f5157bfbd0dbbc56975a46e243b86504f8ddf2 and 46353365da53f31857531c356f7278a56421e1d8.
