### ISSUE TITLE
Issue with IES texture and spot light

### ISSUE THREAD

**Issue by Tryibion** [FlaxEngine/FlaxEngine#1234]
**Issue description:**
For some reason having the spot light point specific ways with and IES texture does not show the light.

https://github.com/FlaxEngine/FlaxEngine/assets/71274967/6a8f6745-a8a3-4df0-ac54-49b8c6eae6ab

**Flax version:**
1.6.6344

**Comment by Menotdan** [comment]
I had this same issue.

**Comment by mafiesto4** [comment]
Fixed in #1636
