### ISSUE TITLE
Particles not rendering

### ISSUE THREAD

**Issue by TalkingWallnut** [FlaxEngine/FlaxEngine#124]
**Issue description:**
 When I put graphics settings on ultra some of the first instances or no instances of particles will emit particles, after some time particles will start getting emitted. 

**Steps to reproduce:**
 Make a script that spawns any kind of particles and put graphics settings on ultra and spawn a couple of instances (atleast that did it in my case).

**Minimal reproduction project:**
 
[first test.zip](https://github.com/FlaxEngine/FlaxEngine/files/5844105/first.test.zip)
 

**Flax version:**
1.0

**Comment by stefnotch** [comment]
Apparently when switching to the GPU simulation mode, the `Constant Spawn Rate` behaves slightly differently from how it behaves in the CPU simulation mode

To reproduce
1. Download the test project above
2. Open the `rocket fire emitter` particle system
3. Set the `Capacity` to `10`
4. Set the `Rate` parameter to `100`
5. Switch between the `CPU` and `GPU` simulation modes
- CPU: Particles wait until the older ones are gone
- GPU: Particles replace the older ones

**Comment by mafiesto4** [comment]
If the capacity is smaller than spawn rates the result is undefined. Setting capacity to be higher is a way to go.

**Comment by TalkingWallnut** [comment]
It doesn't work even if I set capacity to the max value

**Comment by TalkingWallnut** [comment]
> If the capacity is smaller than spawn rates the result is undefined. Setting capacity to be higher is a way to go.

It doesn't work even if I set capacity to the max value
