### ISSUE TITLE
FBX Skinned Animated Mesh Issues

### ISSUE THREAD

**Issue by mtszkarbowiak** [FlaxEngine/FlaxEngine#1241]
# Description

Importing skinned animation mesh issues using FBX format results in mesh being completely deformed.

>  The issue does not occur for DAE files.

# Reproduction

1. Download [example animation asset](https://github.com/FlaxEngine/FlaxEngine/files/12008572/CubeAnim.zip).
2. Import the asset as a model and as an animation (the animations must include scale tracks).
3. Observe deformation (using the animation preview).

Try using both FBX and DAE.

Image 1 - *Deformed animation*

![image](https://github.com/FlaxEngine/FlaxEngine/assets/69864511/49ab6372-3d19-40f6-b46e-da0989ab86bc)

Image 2 - *Animation without deformations*

![image](https://github.com/FlaxEngine/FlaxEngine/assets/69864511/7d505bc6-6bec-4f44-a907-251aac8772b8)

# Flax Version

At least 1.3, 1.5 and 1.6

No plugins, Windows 10

# Potential Cause

Maybe this is caused by the binding issues?

**Comment by mafiesto4** [comment]
It looks like sth related to the scale tracks in fbx import pipeline.

**Comment by mafiesto4** [comment]
Fixed in #2672
