### ISSUE TITLE
Launcher versions of 1.6/master are missing massive heaps of `Source` files

### ISSUE THREAD

**Issue by Withaust** [FlaxEngine/FlaxEngine#1242]
**Issue description:**
Currently, if you were going to download `1.6`/`master` from the launcher, you would get a dedicated `Source` folder stripped down exclusively to only contain necessary headers due to a precompiled nature of the engine. This poses a problem, that a LOT of headers are actually missing from said folder: 
1) `Editor/Utilities` folder is completely gone, which prevents C++ scripts from extending the engine with stuff like custom viewport icons.
2) `Engine/Factories` folder is also gone, which prevents using plugins that register custom assets like `RmlUi` plugin.
3) ... probably some other folders that I might have missed ...

**Flax version:**
`1.6`/`master` from the launcher

**Comment by mafiesto4** [comment]
Actually, that's not a regression but just some parts were exposed but not marked to be shipped with the engine package.

**Comment by mafiesto4** [comment]
Fixed in 40fc2f82950a967d09c59524346bab1ce5eb1a4e.
