### ISSUE TITLE
Fix gizmo sizes in orthographic viewport mode

### ISSUE THREAD

**Issue by Withaust** [FlaxEngine/FlaxEngine#1251]
**Issue description:**
Currently, if you wanted to edit position of something in orthographic viewport mode, it is almost impossible due to the size of gizmo being too big to actually see anything. 
Example: pressing `Top` in viewport settings without an object selected, and then enabling `Orthographic` mode produces this enormous gizmo where you can barely see this 100x100x100 CSG brush:
![image](https://github.com/FlaxEngine/FlaxEngine/assets/118038102/4ccc9f92-1961-4b63-ae2f-4d712d5c3773)

**Flax version:**
https://github.com/FlaxEngine/FlaxEngine/commit/84c99ea1c3efe713ab9c363c305e5cd6a6042c17

**Comment by NoriteSC** [comment]
i will fix this i'm rewriting transform gizmo anyway

**Comment by NoriteSC** [comment]
so found the problem it is not gizmo itself but whole camera
system the mouse wheel and w,s is not bound to each other
whole rendering engine gets incorect ViewPosition
in orthographic viewport mode
i will look to it any way
when i finish with gizmo

**Comment by NoriteSC** [comment]
fixed in https://github.com/FlaxEngine/FlaxEngine/pull/1695

**Comment by mafiesto4** [comment]
Fixed in #1695
