### ISSUE TITLE
Prefab variants instance in active scene don't update when modifying original prefab directly

### ISSUE THREAD

**Issue by Vityy** [FlaxEngine/FlaxEngine#1256]
**Issue description:**

I created a prefab variant and put an instance of it in the active scene. When I modified the original prefab directly, the change didn't occur on the prefab variant instance already in the scene but new instances of the variant apply the changes.

If you select the variant instance in the scene and click "revert all", it reverts to the original prefab's position and scale. It should keep its global position and just apply local changes to its instance.

**Steps to reproduce:**

-Create a prefab
-Create an instance of the prefab in the active scene
-Create a new prefab from the scene instance (it should create a new prefab that is a variant of the original one)
-Add an instance of the prefab variant to the active scene
-Open the original prefab and modify anything in it, save your changes (that will apply the change to all instances of the original prefab)
-You'll see that the instance of the prefab variant you previously created is not updated. If you select that instance and click "view changes" then "revert all" it will take all parameters from the original prefab instance

**Minimal reproduction project:**

Works on any project

**Flax version:**

Flax 1.6

**Comment by mafiesto4** [comment]
Fixed in 716e643f2a609cbc829dc8c117bd3ed4d2cf14e0
