### ISSUE TITLE
Nested Animation Issue

### ISSUE THREAD

**Issue by Tryibion** [FlaxEngine/FlaxEngine#1258]
**Issue description:**
After adding a nested animation it is very different from the imported animation... It looks like it sets it to double of the length of the original animation and is very slow and resets the animation before it is complete?

This video captures the odd behavior. The Right window is the imported animation and the right is the nested animation.

https://github.com/FlaxEngine/FlaxEngine/assets/71274967/4194675e-8620-4505-84d8-22f641a305e5

**Flax version:**
1.6.6344 - master

**Comment by mafiesto4** [comment]
Fixed in 543433440ea0e46fc81712f78744843f77626c16.

**Comment by Tryibion** [comment]
Hmmm. I still have the same issue after that fix...

**Comment by mafiesto4** [comment]
Fixed in 595bb2b7fa55525658b8b5251c88baf061c2d34a.

**Comment by Tryibion** [comment]
That is much better! Thanks!
