### ISSUE TITLE
`GameSettings` platform fields ignore header guards

### ISSUE THREAD

**Issue by Withaust** [FlaxEngine/FlaxEngine#1259]
**Issue description:**
Currently, in `GameSettings` most of the fields have a proper working filters.
![image](https://github.com/FlaxEngine/FlaxEngine/assets/118038102/cff265c9-54f7-4e20-b351-60a73bd7c262)
This is not the case for the platform settings, that have their filters defined with an external string instead of a `typeof`. This seem to allow for for any json asset to be assigned to it instead.
![image](https://github.com/FlaxEngine/FlaxEngine/assets/118038102/cd1a0ad3-faef-4437-8d8d-235c468c7bc8)
This is probably due to the fact that most header guards that should have been preventing addition of those fields don't actually get properly injected in according with the compilation settings.

**Flax version:**
https://github.com/FlaxEngine/FlaxEngine/commit/b2b10ce7da7f3ac47e8f5688bb2693e1a3d7a8c4

**Comment by Tryibion** [comment]
Hmmm it looks like only the Playstation, xbox, and switch settings are the only ones that this happens for. I would guess it has something to do with those settings not actually existing in the code sue to licensing terms with those platforms. So maybe the code is setup to default to any json asset if the type doesnt exist.
