### ISSUE TITLE
Default `CapsuleCollider` orientation is horizontal instead of vertical

### ISSUE THREAD

**Issue by Withaust** [FlaxEngine/FlaxEngine#1269]
**Issue description:**
Currently, default `CapsuleCollider` orientation is horizontal instead of vertical. I know that this is not intentional, since the field `Height` actually grows it horizontally instead of vertically.
![image](https://github.com/FlaxEngine/FlaxEngine/assets/118038102/42c0a472-e9da-44c0-a76d-338497029152)

**Steps to reproduce:**
1. Spawn `CapsuleCollider`
2. Profit.

**Flax version:**
https://github.com/FlaxEngine/FlaxEngine/commit/80bcc0f32e56b132faa62e0ccb2623a042aece66

**Comment by Tryibion** [comment]
Believe it or not that is the default orientation in PhysX. Anyways I have a PR in for this. #1141

**Comment by Withaust** [comment]
Closed in favor of https://github.com/FlaxEngine/FlaxEngine/pull/1141
