### ISSUE TITLE
DebugDraw now showing in game window

### ISSUE THREAD

**Issue by NoriteSC** [FlaxEngine/FlaxEngine#1276]
![image](https://github.com/FlaxEngine/FlaxEngine/assets/53096989/118a2a46-548d-4763-9c7c-e7fbc1794880)

**Comment by Tryibion** [comment]
![image](https://github.com/FlaxEngine/FlaxEngine/assets/71274967/31c5b7c5-eaa2-4ec4-b31b-2fcb6c566031)

It works just fine for me if I enable it by right clicking on the game window tab and enabling it.

**Comment by NoriteSC** [comment]
o super secret menu 
and default for show debug draw is false...
