### ISSUE TITLE
Editor silent crash

### ISSUE THREAD

**Issue by NoriteSC** [FlaxEngine/FlaxEngine#1278]
![image](https://github.com/FlaxEngine/FlaxEngine/assets/53096989/6966acfd-6b96-4086-8a86-310cabb78cbe)
**flax version**: curent master
test script
```cs
    public class test  : Script
    {
        public Collider Collider;
        public override void OnStart()
        {
            Collider.CollisionEnter += CollisionEnter;
            Collider.CollisionExit += CollisionExit;
        }
        private void CollisionExit(Collision obj)
        {
        }
        private void CollisionEnter(Collision obj)
        {
        }
        public override void OnDestroy()
        {
            Collider.CollisionEnter -= CollisionEnter;
            Collider.CollisionExit -= CollisionExit;
            base.OnDestroy();
        }
    }
```
**steps to reproduce**:
1. place test script to actor
2. set the collider field
3. press play 
4. stop playing in any means
5. editor closes without any errors in the logs
 (normal person will end up at nr 5)
6. run editor from vs and redo steps above to see what is wrong

**Comment by mafiesto4** [comment]
Thanks for reporting this. Fixed in 1948a84301099ba73c910e03434f5e3149dff6e8.
