### ISSUE TITLE
(Linux) Editor Crash (Assertion Failed) when opening material selection dropdown

### ISSUE THREAD

**Issue by Flavelius** [FlaxEngine/FlaxEngine#1289]
Ubutuntu 22.04, Nvidia gtx 1060 6GB, proprietary drivers (v535)

**Issue description:**

I created a new scene, opened it and selected the 'Floor' object; then clicked the material selection dropdown, to select a different one (to see if the default seemingly unlit pure white is not just a visual artifact). This triggered an assertion:
![grafik](https://github.com/FlaxEngine/FlaxEngine/assets/8841352/a3c1934c-0c27-412a-874e-27da7e0be750)

**Steps to reproduce:**

As described above, just opening the dropdown triggered the assertion.

It looks like it chokes when rendering the preview for the DDGIDebugProbes material.

**Minimal reproduction project:**

It's the default project generated via commandline, with the only modification of disabling some distracting post processing effects.
[FlaxTest.zip](https://github.com/FlaxEngine/FlaxEngine/files/12249589/FlaxTest.zip)

**Flax version:**

1.6.6344

**Comment by nothingTVatYT** [comment]
I just had the same exception when trying to setup a model and the material for foliage. This is on ArchLinux running the current GIT master branch (reported as version 1.6.6345). GPU is a RTX 4060 Ti with nvidia driver 535 and Vulkan instance version 1.3.264.

**Comment by mafiesto4** [comment]
Yeah it's related to `DDGIDebugProbes` material which uses additional custom Constant Buffer which is unused in default materials pipeline so it's crashing on Vulkan backend.

**Comment by mafiesto4** [comment]
Fixed in 70f0fbe954fd37338df044e652f205201abdc1f6.
