### ISSUE TITLE
Can't build on linux debian

### ISSUE THREAD

**Issue by KevinMagnifico260** [FlaxEngine/FlaxEngine#130]
hello sir/mam can you help me in this case

![Screenshot from 2021-01-22 05-35-08](https://user-images.githubusercontent.com/55334636/105415422-a68a2d80-5c73-11eb-9655-031d3d8189ed.png)

**Comment by mafiesto4** [comment]
Ensure to have Git LFS installed and then clone repo. It looks like binary files are missing (probably just 1kb pointer files on your drive after clone).
