### ISSUE TITLE
Problem with "Enable Simulation" on vehicles

### ISSUE THREAD

**Issue by RuanLucasGD** [FlaxEngine/FlaxEngine#1323]
If I set "Enable Simulation" as false on the wheeled vehicle and press Start, the editor crash. Also, if I start with "Enable Simulation" as true and set to false, try to accelerate and set it to true again in the game, the vehicle is thrown.

[Development 2023.08.19 - 09.31.04.01.webm](https://github.com/FlaxEngine/FlaxEngine/assets/79365912/8eac9d2c-86dd-4033-b2aa-54bfdf9173b9)

**Steps to reproduce:**
1. create a simple vehicle
2. add wheels
3. add a script to control vehicle
4. start game with "enable simulation" as true on wheeled vehicle actor (rigidbody editor)
5. accelerate vehicle
6. disable "enable simulation" on your vehicle
7. the vehicle is thrown.

another test:

1. create a simple vehicle
2. add wheels
3. add a script to control vehicle
4. start game with "enable simulation" as false on wheeled vehicle actor (rigidbody editor)
5. editor crash (if you has scene saved you cannot reopen the project because flax will crash on start)

**Minimal reproduction project:**
[Car Test.zip](https://github.com/FlaxEngine/FlaxEngine/files/12385929/Car.Test.zip)

**Flax version:**
1.6 master

**Comment by mafiesto4** [comment]
Fixed in a8cc4d7fcbf336cab76c6bc1e69cac6e15e3f491.
