### ISSUE TITLE
Change vehicle suspension "Max Raise" or "Max drop" in game don't work very well

### ISSUE THREAD

**Issue by RuanLucasGD** [FlaxEngine/FlaxEngine#1324]
**Issue description:**
Change vehicle suspension configuration in game causes problem on wheel position.

https://github.com/FlaxEngine/FlaxEngine/assets/79365912/d7fa3435-b099-4e69-9c52-54cffc714506

**Steps to reproduce:**
1. Create a vehicle
2. Start game
3. Try change Max Raise or Max drop on suspension settings.
4. Wheel position is incorrect.

**Minimal reproduction project:**

[Car Test.zip](https://github.com/FlaxEngine/FlaxEngine/files/12386098/Car.Test.zip)

**Flax version:**
1.6 master

**Comment by mafiesto4** [comment]
Fixed in b0ec8525aab51fea854d1e71c971244deeab7d83.
