### ISSUE TITLE
Auto create prefab when import models

### ISSUE THREAD

**Issue by RuanLucasGD** [FlaxEngine/FlaxEngine#1329]
I started a game project and one of the things that is bothering me is having to import a lot of models. Flax is unable to preserve the center of model geometry.

That way I need to export all the models separately, and import them into the editor. And then I need to reassemble the whole model.

Please add a way to import the model and generate a prefab with the mesh structure.

related to https://github.com/FlaxEngine/FlaxEngine/issues/1023

**Flax version:**
1.6

**Comment by mafiesto4** [comment]
Added in 63773f2ddf71418cf7fb6b86e1a7e33dcb95c9dc.
