### ISSUE TITLE
UI child positiong wrong

### ISSUE THREAD

**Issue by honzapatCZ** [FlaxEngine/FlaxEngine#133]
**Issue description:**
Iam playing with UI creation and one of my must haves for this feature is children nesting. Ignoring the graphical glitches where childrens sometime render behind, which makes dynamic stuff like Icon over button impossible, there is issue with parenting
![image](https://user-images.githubusercontent.com/26117393/105514214-88541a00-5cd3-11eb-99bb-0cb4d0e34958.png)
![image](https://user-images.githubusercontent.com/26117393/105514248-9013be80-5cd3-11eb-8db7-0b5a27988cbd.png)

**Steps to reproduce:**
Create something nested, for example the grid as I have

**Flax version:**
1.0

**Comment by jb-perrier** [comment]
Looks like there is a DPI bug with the selection rectangle.

**Comment by stefnotch** [comment]
Is this still an issue?

**Comment by Zbyl** [comment]
I don't see selection around UI elements, but transform gizmos for them are drawn in wrong places, as seen in the attached video.
https://user-images.githubusercontent.com/1767676/128614271-caee3fed-70ef-4e1a-99b2-eb3d5c3bd8b4.mp4

**Comment by stefnotch** [comment]
> 
> 
> I don't see selection around UI elements, but transform gizmos for them are drawn in wrong places, as seen in the attached video.
> https://user-images.githubusercontent.com/1767676/128614271-caee3fed-70ef-4e1a-99b2-eb3d5c3bd8b4.mp4

Could you open a new issue for that? Just so that it's easier to keep track of all the little bugs that we have to fix :)

**Comment by Zbyl** [comment]
Transform gizmos issue registered as #588

**Comment by mafiesto4** [comment]
Uniform Grid Panel seams to work fine now (tested the latest 1.6 version). Incorrect selection outline for controls and missing transform gizmo for UI is another matter to be worked on soon.
