### ISSUE TITLE
Editor crash on try export terrain

### ISSUE THREAD

**Issue by RuanLucasGD** [FlaxEngine/FlaxEngine#1330]
If i try export terrain the editor crash.

![image](https://github.com/FlaxEngine/FlaxEngine/assets/79365912/f1f31eac-42a5-4893-9973-677f1b6c8ec3)

**Flax version:**
1.6

**Comment by Withaust** [comment]
Any logs/asserts?

**Comment by mafiesto4** [comment]
Fixed in 87e19ef4bcf07aeae724af55a4200bd48724dd08.
