### ISSUE TITLE
Script Randomly Deleted

### ISSUE THREAD

**Issue by Swiggies** [FlaxEngine/FlaxEngine#1331]
**Issue description:**

I was editing my C# script with Visual Studio 2022 when VS prompted me that my project had been modified externally and prompted me to reload. This usually happens after compiling (alt-tabbing back to Flax) but I did not prompt a compile this time and I pressed ignore and my entire script had been deleted from my PC.

**Steps to reproduce:**

Unable to repro consistently. Happened twice in one session.

**Minimal reproduction project:**

**Flax version:**

1.6

**Comment by Menotdan** [comment]
I have had the same issue once, after a similar sequence of events. I was editing a C++ script though.

**Comment by Swiggies** [comment]
Just had it happen again. Nothing in the logs specifies why it might have happened.

`[ 24/08/2023 5:36:01 PM ]: [Info] Content item 'D:\Projects/Flax/FlaxPrototypingTools/Source/PrototypeTools/PrototypingActor.cs' has been removed
[ 24/08/2023 5:36:01 PM ]: [Info] Command: "C:\Program Files (x86)/Flax/Flax_1.6/Binaries/Tools/Flax.Build.exe" -log -genproject  
[ 24/08/2023 5:36:01 PM ]: [Info] Flax.Build 1.0.0
[ 24/08/2023 5:36:01 PM ]: [Info] Generating project files...
[ 24/08/2023 5:36:01 PM ]: [Info] Missing Android SDK. Cannot build for Android platform.
Missing Linux Toolchain. Cannot build for Linux platform.
[ 24/08/2023 5:36:01 PM ]: [Info] Total time: 00:00:00.4623194
[ 24/08/2023 5:36:03 PM ]: [Info] Starting scripts compilation...
[ 24/08/2023 5:36:03 PM ]: [Info] Command: "C:\Program Files (x86)/Flax/Flax_1.6/Binaries/Tools/Flax.Build.exe" -log -logfile= -build -mutex -buildtargets=PrototypeToolsEditorTarget -skiptargets=FlaxEditor -platform=Windows -arch=x64 -configuration=Development -hotreload=".HotReload.6" 
[ 24/08/2023 5:36:03 PM ]: [Info] Flax.Build 1.0.0
[ 24/08/2023 5:36:03 PM ]: [Info] Building targets...
[ 24/08/2023 5:36:03 PM ]: [Info] Missing Android SDK. Cannot build for Android platform.
[ 24/08/2023 5:36:03 PM ]: [Info] Missing Linux Toolchain. Cannot build for Linux platform.
[ 24/08/2023 5:36:03 PM ]: [Info] Building C# only
Building target PrototypeToolsEditorTarget in Development for Windows x64
[ 24/08/2023 5:36:03 PM ]: [Info] Building referenced target Flax
[ 24/08/2023 5:36:04 PM ]: [Info] Found 2 valid and 1 invalid actions in Task Graph cache
[ 24/08/2023 5:36:04 PM ]: [Info] Executing 1 task using 1 thread
[ 24/08/2023 5:36:04 PM ]: [Info] Compiling D:\Projects\Flax\FlaxPrototypingTools\Binaries\PrototypeToolsEditorTarget\Windows\x64\Development\PrototypeTools.CSharp.dll
[ 24/08/2023 5:36:04 PM ]: [Info] D:\Projects\Flax\FlaxPrototypingTools\Source\PrototypeTools\PrototypingRamp.cs(11,36,11,52): error CS0246: The type or namespace name 'PrototypingActor' could not be found (are you missing a using directive or an assembly reference?)
D:\Projects\Flax\FlaxPrototypingTools\Source\PrototypeTools\PrototypingStairs.cs(16,38,16,54): error CS0246: The type or namespace name 'PrototypingActor' could not be found (are you missing a using directive or an assembly reference?)
D:\Projects\Flax\FlaxPrototypingTools\Source\PrototypeTools\PrototpyingCylinder.cs(16,40,16,56): error CS0246: The type or namespace name 'PrototypingActor' could not be found (are you missing a using directive or an assembly reference?)
D:\Projects\Flax\FlaxPrototypingTools\Source\PrototypeTools\PrototypingBox.cs(13,35,13,51): error CS0246: The type or namespace name 'PrototypingActor' could not be found (are you missing a using directive or an assembly reference?)
D:\Projects\Flax\FlaxPrototypingTools\Source\PrototypeTools\PrototypingToolsPlugin.cs(54,32,54,48): error CS0246: The type or namespace name 'PrototypingActor' could not be found (are you missing a using directive or an assembly reference?)
D:\Projects\Flax\FlaxPrototypingTools\Source\PrototypeTools\PrototypingToolsPlugin.cs(24,37,24,53): error CS0246: The type or namespace name 'PrototypingActor' could not be found (are you missing a using directive or an assembly reference?)
D:\Projects\Flax\FlaxPrototypingTools\Source\PrototypeTools\PrototypingToolsPlugin.cs(26,36,26,52): error CS0246: The type or namespace name 'PrototypingActor' could not be found (are you missing a using directive or an assembly reference?)
[ 24/08/2023 5:36:04 PM ]: [Info] Task C:\Program Files\dotnet\dotnet.exe exec "C:\Program Files\dotnet\sdk\7.0.306\Roslyn\bincore\csc.dll" /noconfig /shared @"D:\Projects\Flax\FlaxPrototypingTools\Cache/Intermediate\PrototypeToolsEditorTarget\Windows\x64\Development\PrototypeTools.CSharp.response" failed with exit code 1

1 task failed
[ 24/08/2023 5:36:04 PM ]: [Info] Total time: 00:00:01.6312021
[ 24/08/2023 5:36:04 PM ]: [Error] Failed to run build tool, result: 1`

**Comment by davevanegdom** [comment]
Bumping this as we had this happen today!

**Comment by mafiesto4** [comment]
Fixed by #1402 (on `master` - use daily builds or wait for Flax 1.7 release). Reopen if it will happen again.
