### ISSUE TITLE
UI rendering icons over button

### ISSUE THREAD

**Issue by honzapatCZ** [FlaxEngine/FlaxEngine#134]
**Issue description:**
Trying to make an image(like an icon) over button, doesnt work, it doesnt render under nor over the button(also tried with manualy positiong it over the button(as described in #133 ) even if by the parenting it should have the default postiion at the anchor point in the parent)
![image](https://user-images.githubusercontent.com/26117393/105515526-1381df80-5cd5-11eb-9570-eed9a5b8d415.png)

**Steps to reproduce:**
Create a button and create image under it

**Flax version:**
1.0

**Comment by honzapatCZ** [comment]
@mafiesto4  Is this actually intended? If so then I would backport some parts of Container Control to normal UI control, so it renders all its children

**Comment by mafiesto4** [comment]
The order of the controls rmight be incorrect in this case.

**Comment by honzapatCZ** [comment]
@mafiesto4 like praent renders over children? That doesnt make sense, gonna ffnishm my jam game and make some mqjor adjustments in ui, while its still not set

**Comment by stefnotch** [comment]
So, this issue is because a `Button` is a `Control` and not a `ContainerControl`. Thus, the child (image) ends up not having a parent.

I suppose we should warn the user when a UI control is missing its parent?

**Comment by mafiesto4** [comment]
Fixed by https://github.com/FlaxEngine/FlaxEngine/pull/355.
