### ISSUE TITLE
Critical bug in network replication

### ISSUE THREAD

**Issue by Withaust** [FlaxEngine/FlaxEngine#1344]
**Issue description:**
Currently, if you have many objects that you want to spawn in a single frame (in my case I have about 6-7 components attached to the player prefab that all do `NetworkReplicator.AddObject(this)` inside `OnEnable`), you will eventually ran into this assert:
![image](https://github.com/FlaxEngine/FlaxEngine/assets/118038102/58f76d93-78fc-49bd-9b72-0b8a41359623)

**Steps to reproduce:**
Spawn a networked prefab with a lot of networked scripting objects attached and see the assert for yourself.

**Flax version:**
https://github.com/FlaxEngine/FlaxEngine/commit/50c85aec6d6929b119f92d7dd0672587c62ae826

**Comment by mafiesto4** [comment]
Fixed in 21b90fb8297d21e9b9f35ea277fc5fa1e7477544. Spawn messages can be sent in parts to handle large objects properly.
