### ISSUE TITLE
Incorrect transform on change model scale

### ISSUE THREAD

**Issue by RuanLucasGD** [FlaxEngine/FlaxEngine#1350]
**Issue description:**

If i change actor scale, the model child don't change your local scale and local position correcly.

Unity:

[Desktop 2023.08.27 - 09.53.15.01.webm](https://github.com/FlaxEngine/FlaxEngine/assets/79365912/cd5e98c2-137c-4698-af83-00f2b923c71f)

Flax:

[Development 2023.08.27 - 09.54.31.02.webm](https://github.com/FlaxEngine/FlaxEngine/assets/79365912/5d727d21-c53e-4253-ad55-556f6f1ef55e)

**Minimal reproduction project:**
[Transform Test.zip](https://github.com/FlaxEngine/FlaxEngine/files/12448122/Transform.Test.zip)

**Flax version:**
1.6

**Comment by mafiesto4** [comment]
That's because Flax inverts the normal vectors (inversed culling) when object's scale is negative:

![image](https://github.com/FlaxEngine/FlaxEngine/assets/3464853/a07777f7-4f23-4604-adb6-e3e674f37e7c)

This allows to easily build environments with objects being inverted. But I guess we could invert only along the negative axis. You can overcome this now by using two-sided material.

**Comment by Menotdan** [comment]
> That's because Flax inverts the normal vectors (inversed culling) when object's scale is negative:
> 
> ![image](https://user-images.githubusercontent.com/3464853/267034423-a07777f7-4f23-4604-adb6-e3e674f37e7c.png)
> 
> This allows to easily build environments with objects being inverted. But I guess we could invert only along the negative axis. You can overcome this now by using two-sided material.

I don't believe this is the only issue being pointed out, I think they are also pointing out the difference in how the actual object scales. I'm not sure how to make it work properly though.

**Comment by mafiesto4** [comment]
That's the same problem as #1796. We probably need a different of calculating Matrix for rendering.

**Comment by mafiesto4** [comment]
Fixed in 9a21cfd092621fdb5bc8bfe31e6d968c8095094a.
