### ISSUE TITLE
Vehicle don't identify wheel type correctly

### ISSUE THREAD

**Issue by RuanLucasGD** [FlaxEngine/FlaxEngine#1352]
**Issue description:**

One thing that got me really confused was that I added wheels to my vehicle and defined the type of each wheel (Forward left, Forward Right, Rear Left, Rear Right). However, when I started the game, the direction of the vehicle was completely wrong, and I just noticed something... 

Wheel order needs to be EXACTLY:

1. Forward Left
2. Forward Right
3. Rear Left
4. Rear Right

If you create the list in a different order your car will not behave properly.

[Development 2023.08.28 - 19.48.31.09.webm](https://github.com/FlaxEngine/FlaxEngine/assets/79365912/051c5744-7e3c-4c8b-838c-97237fe1634d)

**Steps to reproduce:**
Change wheels order on vehicle configuration

**Minimal reproduction project:**
[Car Test.zip](https://github.com/FlaxEngine/FlaxEngine/files/12458894/Car.Test.zip)

**Flax version:**
1.6

**Comment by mafiesto4** [comment]
It looks like it's only happening in `Drive4W` mode (`DriveNW` works fine).

**Comment by mafiesto4** [comment]
Fixed in 36dca16991ddcf3504834402d495c53a1d85dfc1.
