### ISSUE TITLE
Dictionary iterator creating unnecessary copies of its source

### ISSUE THREAD

**Issue by mtszkarbowiak** [FlaxEngine/FlaxEngine#1361]
# Description

Entire code causing the issue is located in `Engine/Core/Collections/Dictionary.h`.

Theoretically, `Dictionary<...>` can be iterated with `Dictionary<...>::Iterator`. The `Iterator` has trivial constructors and specialized ones accepting `Dictionary&` and `const Dictionary&` which further casts away the `const` qualifier. Those do not cause issues.

The `Iterator` has only [copy re-assignment operator](https://github.com/FlaxEngine/FlaxEngine/blob/36dca16991ddcf3504834402d495c53a1d85dfc1/Source/Engine/Core/Collections/Dictionary.h#L314) and does not have move re-assignment operator. **The issue lies in [the line](https://github.com/FlaxEngine/FlaxEngine/blob/36dca16991ddcf3504834402d495c53a1d85dfc1/Source/Engine/Core/Collections/Dictionary.h#L316C24) where reference to the dictionary should be copied. Unfortunately `Dictionary&` comes from `const` argument. Then it becomes `const Dictionary&` which triggers `Dictionary<...>` 's copy constructor.** Therefor each time `Iterator` is being re-assigned new copies of original `Dictionary` are being allocated.

The problem is aggravated by the fact that there exists no move re-assignment operator for `Iterator`. Universal reference `Iterator&&` collapses to `Iterator&` and to `const Iterator&` which continues to create new instances of `Dictionary`. Using `Begin()` immediately creates a new copy.

Entire issue is not easy to spot from distance. Resolving it means improvement of performance.

# Suggested Resolutions

I think I could work on the problem, but right solution needs to be selected first. My ideas are:

1. Accepting suspicious practice of casting away `const` qualifier. Fixing re-assignment operators and moving on.
2. Splitting the iterator into mutable and constant versions by adding a class `ConstIterator` or by specialization with bool template argument.

**Comment by mafiesto4** [comment]
Thanks. Fixed in 9291295a4d9997e3257037db7135d3a5e52d3962
