### ISSUE TITLE
Crash when setting "Slope Limit" on Controller to 90

### ISSUE THREAD

**Issue by W2Wizard** [FlaxEngine/FlaxEngine#137]
**Issue description:**
When you set a controller's "Slope Limit" to 90 and attempt to play, the editor crashes.

**Log:**
![image](https://user-images.githubusercontent.com/63303990/105558110-206ef500-5d0e-11eb-9c46-6389649655e1.png)

**Steps to reproduce:**
1. Open any project.
2. Create a new controller.
3. Set its "Slope Limit" to 90 & hit Play.
4. RIP

**Flax version:**
1.0.6215

**Comment by TalkingWallnut** [comment]
It is fixed, devs just need to accept the pull request.

**Comment by mafiesto4** [comment]
Fixed by #147
