### ISSUE TITLE
Show mouse on all windows except Game Window

### ISSUE THREAD

**Issue by RuanLucasGD** [FlaxEngine/FlaxEngine#1370]
**Issue description:**
Hello, this is a suggestion about usability. I'm making a game where i need the Screen.Visible = false, but Screen.CursorLock = CursorLockMode.None. I made this because i made a custom cursor icon.

The problem happen when i need change any value on editor on game mode why i cannot see the cursor XD.
Please , if possible set cursor as visible (in all windows except GameWindow) always on game mode., this can help a lot.

**Flax version:**
1.6

**Comment by mafiesto4** [comment]
Fixed in #859 and f2a3338dce85b2b9a6fb9c7957349b27fdf92e72
