### ISSUE TITLE
Launcher requires Admin, even for public folder

### ISSUE THREAD

**Issue by Hunanbean-Collective** [FlaxEngine/FlaxEngine#1381]
**Issue description:**

Launcher requires admin privileges to install, even into public folder 

**Steps to reproduce:**

try to install as non-admin. watch it demand admin, even to a public install location

**Minimal reproduction project:**

**Flax version:**

1.6 launcher downloaded bin, not compiled

**Comment by mafiesto4** [comment]
Yeah we could check if admin rights are needed for the operation.

**Comment by mafiesto4** [comment]
Fixed in the upcoming Launcher update - coming out around this week with Flax 1.7
