### ISSUE TITLE
How to modify engine path in the dashboard?

### ISSUE THREAD

**Issue by Visow** [FlaxEngine/FlaxEngine#139]
I want to modify the engine path of the flax Launcher, but I can't find out how to modify it.

**Comment by GoaLitiuM** [comment]
The known engines are stored in `%APPDATA%\Flax\Versions.txt` file.

**Comment by mafiesto4** [comment]
Yeah, you can move them manually and edit that `%APPDATA%\Flax\Versions.txt` file or uninstall and install somewhere else.

Also for source-build, we have useful `RegisterEngineLocation.bat`.
