### ISSUE TITLE
Vehicle wheels are sorted on editor edit mode

### ISSUE THREAD

**Issue by RuanLucasGD** [FlaxEngine/FlaxEngine#1394]
**Issue description:**
If i add some wheels on vehicle and set your types (eg. no drive, forward left, no drive, forward right) the wheels has ben sorted altomaticaly to forward left/right and after no drive. This makes edit wheels a bit dificult because the wheel change your horder and you don't see this.

If add a way of set wheels only when game starts would be good.

**minimal project:**
[Car Test.zip](https://github.com/FlaxEngine/FlaxEngine/files/12622435/Car.Test.zip)

**Flax version:**
1.6 master

**Comment by mafiesto4** [comment]
Issue with PhysX. We could add remapping table to access `Vehicle` wheels depending on that table order.

**Comment by mafiesto4** [comment]
Fixed in #2192.
