### ISSUE TITLE
Error on edit particle emitter parameter using an particle effect actor

### ISSUE THREAD

**Issue by RuanLucasGD** [FlaxEngine/FlaxEngine#1395]
**Issue description:**
Hello, if you add many emiters on a particle actor on your scene and try change parameters of your emitter the editor cannot save your changes.

**Steps to reproduce:**
1. create a emitter with parameter.
2. create a particle system asset to your emiter.
3. add your emmiter to your particle (need add the same emitter more than 1 time, 4 ou 5)
4. add the particle system to scene
5. try change some parameters of your emiters using Particle Effect actor.
6. See your console my buddy :)

[Desktop 2023.09.15 - 15.44.02.04.webm](https://github.com/FlaxEngine/FlaxEngine/assets/79365912/0a4b1670-828d-414a-b8c5-9bdd8faea42e)

**Minimal reproduction project:**
[TestParticle.zip](https://github.com/FlaxEngine/FlaxEngine/files/12623337/TestParticle.zip)

**Flax version:**
1.6

**Comment by mafiesto4** [comment]
Fixed in 523a14af56c50811b47664c0b92184a9ac77d44a.
