### ISSUE TITLE
Tooltip Flashing

### ISSUE THREAD

**Issue by nocxtious** [FlaxEngine/FlaxEngine#14]
**Issue description:**

Hovering over items that provide tooltips results in rapidly flashing tooltips.

**Steps to reproduce:**

1. Create/open a project
2. Find an asset or property that will provide a tooltip
3. Hover over it

**Minimal reproduction project:**

1. Basic scene new project

**Flax version:**

1.0

Extra info:
- Using a 4k screen, with windows scaling set to 150%. 
- Maximizing the window fixes the issue with asset tooltips, but property tooltips continue to flash.

Video:
https://youtu.be/8jJ_02enIbs

**Comment by jb-perrier** [comment]
Should be resolved by #28, keep me updated if it's fixed when the next update come out ( or you can build it from source ).

**Comment by nocxtious** [comment]
Just pulled in master and tried it, seems to have resolved all the flashing issues that I was running into in both windowed and maximized, thank you!
