### ISSUE TITLE
Bug with raycasting and layers

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#140]
I believe I've discovered a bug with raycasting and layers in the current Build (1.0.6215)

Please see the video to understand the bug:

https://drive.google.com/file/d/1IksHpVowkp_syg0COxypnEdUdQWN4KeF/view?usp=sharing

**Comment by stefnotch** [comment]
Could you post your layer settings?

**Comment by Evildea** [comment]
![image](https://user-images.githubusercontent.com/35228400/105576825-997f5280-5dc9-11eb-93ca-2371249da5df.png)

**Comment by Evildea** [comment]
![image](https://user-images.githubusercontent.com/35228400/105576854-c9c6f100-5dc9-11eb-8494-91d993941d32.png)

**Comment by Evildea** [comment]
![Uploading image.png…]()

**Comment by stefnotch** [comment]
You'll want to mask out layer 1 by doing `layerMask: ~(1U << 1)`

**Comment by Evildea** [comment]
Ok, I see how it works now. 

The previous documentation was a bit confusing so I misunderstood how the Layers worked. I was going to suggest we update the documentation, but I see you've just done that so nothing else is needed!

Thanks,
