### ISSUE TITLE
Particles don't receive fog even with fog enabled

### ISSUE THREAD

**Issue by Mmeroo** [FlaxEngine/FlaxEngine#1408]
**Issue Description:**
Particles don't receive fog even with fog enabled in the sample project
![image](https://github.com/FlaxEngine/FlaxEngine/assets/30769296/7b5a3014-3937-4957-9bda-eb5885be032a)

**Steps to reproduce:**
Add ExponentialHeightFog volumetric fog to sample particle project and set density to 3

**Flax version:**
1.6

**Comment by mafiesto4** [comment]
Fixed in 4a42aa8c443555e741259f566753f3184aa55c73
