### ISSUE TITLE
Particles don't receive light unless the source point is in the range

### ISSUE THREAD

**Issue by Mmeroo** [FlaxEngine/FlaxEngine#1409]
**Issue Description:**
Particles don't receive light unless the source point is in the range

https://github.com/FlaxEngine/FlaxEngine/assets/30769296/5c7b61ab-49b0-4a83-bcd5-ae81e015c818

**Steps to reproduce:**
add translucent smoke particles and put a light inside the particles with a small radius

**Flax version:**
1.6

**Comment by mafiesto4** [comment]
Fixed in 8cd8ae93c3281e525970931eb380fc05e6ea8afb.
