### ISSUE TITLE
Engine crash when editing Localized String Table

### ISSUE THREAD

**Issue by mtszkarbowiak** [FlaxEngine/FlaxEngine#1415]
# Description

Engine crashes when localized table is saved with at least one entry.

# Reproduction

1. Create a *Localized String Table*
2. Add arbitrary entry. The value must not be empty.
3. Save the asset.

Works on the master.

**Comment by mafiesto4** [comment]
Fixed in 1134cfa6a6964837d6391247a899a95573ce6f91 and 48d4a51c1b589ec2b7560812cecc3af5154422fd and 8bd66495101e40bd6626a30d0c36227dd8b2d33f.
