### ISSUE TITLE
Physics.RayCast ignores SphereCollider and CapsuleCollider

### ISSUE THREAD

**Issue by MineBill** [FlaxEngine/FlaxEngine#1417]
**Issue description:**
The `Physics.RayCast` function will ignore any rigidbodies with a sphere or capsule collider, including CharacterController. Box and mesh colliders work correctly.

https://github.com/FlaxEngine/FlaxEngine/assets/30367251/87ac5e59-d3ea-4b13-b8d0-d02f52a2a5da

Notice how the raycast completely ignores the sphere and passes through the capsule half of the time.

**Steps to reproduce:**
Open MRP. Click anywhere to place a first point and raycast will be cast to the mouse position. Press spacebar to remove the point. The raycast will be visualized and will turn green when there is a hit.

**Minimal reproduction project:**
[RaycastingMRP.zip](https://github.com/FlaxEngine/FlaxEngine/files/12643087/RaycastingMRP.zip)

**Flax version:**
Master

**Comment by GoaLitiuM** [comment]
The ray direction is not normalized in the last raycast in your code, fixing it seems to address this bug:
```csharp
if (Physics.RayCast(_first.Value, (_second.Value - _first.Value).Normalized, out var hit))
```

**Comment by MineBill** [comment]
You are correct, I completely forgot that the direction needs to be normalized.
