### ISSUE TITLE
Animation system root motion has no effect

### ISSUE THREAD

**Issue by QQ1273459693** [FlaxEngine/FlaxEngine#1429]
**Issue description:Animation system root motion has no effect,I made sure to check the "Enable" status in the animation view and resources**

**Steps to reproduce:Check the "Enable" option in Animation View, as per the API documentation,Animation resources like FBX**

**Minimal reproduction project:**

**Flax version:1.6**

![D1CY%H9G_A(25A1OH3Q41W7](https://github.com/FlaxEngine/FlaxEngine/assets/71361736/eae356c0-aa1f-4fb9-ad91-95802bfca1fc)
![J3XKLX%9`W%CB5Q`6$WZXUW](https://github.com/FlaxEngine/FlaxEngine/assets/71361736/eb4a1051-7a50-4693-90d2-48db64aea512)
[Walking_2.zip](https://github.com/FlaxEngine/FlaxEngine/files/12651162/Walking_2.zip)

**Comment by Muzz** [comment]
I found i had to set the root node name manually. 

Also i had to setup my root  motion bone differently than how it worked in other game engines. 
I couldn't just set the hips, i  needed another parent bone that only had x and y translation, which is transferred over with a blender script. 

But if setting the node name is necessary, then it should show some feedback to the user, about the lacking name. Ultimately having it on  dropdown or search through bone names would be ideal.

**Comment by QQ1273459693** [comment]
Do I just set the Root name to solve the problem? I'll try

**Comment by QQ1273459693** [comment]
OK, I think it's fixed, really need to set RootName,However, the API documentation does not specify it in detail, and I think the documentation needs to be updated

**Comment by Muzz** [comment]
Reading the docs 

"Root Node Name | The custom node name to be used as a root motion source. If not specified the actual root node will be used."

I can't see the hierarchy of your animation in that file, so i'm unsure which bone is the default root, but it appears that the actual root has no motion. 

![image](https://github.com/FlaxEngine/FlaxEngine/assets/2074204/f3a49f3e-8108-4a57-b266-d19dfb454d15)

I do think the UI should show what bone it has selected as root by default, it being an override is unnecessary imo, if it was a combo box that only let valid bones be picked.

**Comment by QQ1273459693** [comment]
My animation file is downloaded from https://www.mixamo.com, the preview effect in flax engine is perfect, I don't quite understand what I need to do with my animation file, my English is translated, please forgive me, and I have tried all the mobile state animation downloaded by mixamo, but nothing has worked

,This is my 3D model




无颜&nbsp;?女丿冀
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FlaxEngine/FlaxEngine"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月19日(星期二) 中午12:17
***@***.***&gt;;
抄送:&nbsp;"无颜 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [FlaxEngine/FlaxEngine] Animation system root motion has no effect (Issue #1429)





 
Reading the docs
 
"Root Node Name | The custom node name to be used as a root motion source. If not specified the actual root node will be used."
 
I can't see the hierarchy of your animation in that file, so i'm unsure which bone is the default root, but it appears that the actual root has no motion.
 

 
I do think the UI should show what bone it has selected as root by default, it being an override is unnecessary imo, if it was a combo box that only let valid bones be picked.

**Comment by QQ1273459693** [comment]
..

**Comment by mafiesto4** [comment]
I guess we could try to extract the root movement in more complex way for this animation.

@QQ1273459693 could you post the source animation file here? (not the `Walking.flax` but source animation `.fbx`)

**Comment by QQ1273459693** [comment]
My mistake, I uploaded a flax file that I thought was the source file
[Running.zip](https://github.com/FlaxEngine/FlaxEngine/files/12658126/Running.zip)
![Uploading GIF 2023-9-19 17-25-59.gif…]()

**Comment by alcoranpaul** [comment]
I tested the rootmotion as well with 2 characters Xbot from Mixamo and a synty character (using a guide by _Brennek_ in discord). The result was that the transform of both animation tends to get wonky. Moving at forward direction the characters goes up in the Y-dir. I also tested with a Right moving animation and it still goes up in the Y-dir.

Unsure if its just the animations or something but here is a zip file that contains the .fbx of mixamo xbot and walking animation and a video of what I tested 

[RootMotionTest.zip](https://github.com/FlaxEngine/FlaxEngine/files/12842374/RootMotionTest.zip)

**Comment by Menotdan** [comment]
> I tested the rootmotion as well with 2 characters Xbot from Mixamo and a synty character (using a guide by _Brennek_ in discord). The result was that the transform of both animation tends to get wonky. Moving at forward direction the characters goes up in the Y-dir. I also tested with a Right moving animation and it still goes up in the Y-dir.
> 
> Unsure if its just the animations or something but here is a zip file that contains the .fbx of mixamo xbot and walking animation and a video of what I tested
> 
> [RootMotionTest.zip](https://github.com/FlaxEngine/FlaxEngine/files/12842374/RootMotionTest.zip)

I think this should be reported as a separate issue. Seems like its a different thing than the root motion not working at all. Thank you for the test file though.

**Comment by mafiesto4** [comment]
Fixed in d08843900e11e41e89707fb46c6bf0d806903a8d.

https://github.com/FlaxEngine/FlaxEngine/assets/3464853/60e4c833-9918-424c-b5ca-b3aa1318c777

New **Root Motion Flags** allows to apply root motion only over XZ plane so the character won't float like here. Plus I added root motion extraction mode **Extract Center Of Mass** which can extract motion based on the character pose movement, even if `Hips` node is unused.

![root-motion-flags](https://github.com/FlaxEngine/FlaxEngine/assets/3464853/7165961b-97b3-4118-9b8e-291f78a748fe)
