### ISSUE TITLE
Undo doesn't trigger properly when values are scrolled

### ISSUE THREAD

**Issue by Muzz** [FlaxEngine/FlaxEngine#1430]
**Issue description:**
When sliding properties in the editor, such as position on a 3d mesh, if you  immediately undo, it doesn't fire the undo event. 

If  you do the same thing but input the number manually, the undo will fire after just fine. 

**Steps to reproduce:**
Make a mesh, slide the x position by dragging the mouse  on the far drag option, then try to undo.

**Flax version:**
master

**Comment by mafiesto4** [comment]
Well it works fine to me

**Comment by Muzz** [comment]
This was 7 months ago, I do remember this happening, but perhaps got fixed in that time? Anyway happy to close.
