### ISSUE TITLE
Shift tab on editor inputs 

### ISSUE THREAD

**Issue by Muzz** [FlaxEngine/FlaxEngine#1431]
**Issue description:**
While we can tab through inputs in the editor just fine, shift tab doesn't work as expected and go backwards through inputs. 
This is both a usability and accessibility issue. 

**Steps to reproduce:**
Click numerical input in editor, hit tab, and it will move forwards, but shift will not reverse the tab. 

**Flax version:**
Master

**Comment by mafiesto4** [comment]
Added in #1503
