### ISSUE TITLE
Engine Crash on custom post process material

### ISSUE THREAD

**Issue by Myterian** [FlaxEngine/FlaxEngine#1435]
**Issue description:**
Engine crashes when you deselect a post processing volume with an empty, custom material. Also, you can't remove the material anymore because of the crashing and editing didn't save the material either.

**Steps to reproduce:**
1. Open a new or exsisting sample project.
2. Create a new post processing volume in the scene hierarchy
3. Create a new material in contents
4. Set the material domain to post processing, save and exit material view. Don't set a color or anything
5. Add the material to the custom materials in the post processing volume. Scene should be black
6. Select something else in the hierarchy and eventually move in the scene view

**Minimal reproduction project:**
Can be a blank project with a new scene, but also works with any sample scene.

**Flax version:**
1.6.6344

**Comment by mafiesto4** [comment]
Thanks for reporting this. It was fixed in #1314. You can download `master (daily)` build via Flax Launcher to have engine version with it fixed.
