### ISSUE TITLE
Crash when loading projects with cyrillic in the path

### ISSUE THREAD

**Issue by KirillianAmu** [FlaxEngine/FlaxEngine#1439]
**Issue description:**
Loading any/or default example projects crashes the engine with an error 0xe0434352, likely due to cyrillic in the folder's path as moving the project out to another drive w/o cyrillic in the path allows the sample projects to load. 
Logs:
[Log_2023_09_19_16_48_57.txt](https://github.com/FlaxEngine/FlaxEngine/files/12661017/Log_2023_09_19_16_48_57.txt)
[Log_2023_09_19_09_10_17.txt](https://github.com/FlaxEngine/FlaxEngine/files/12661022/Log_2023_09_19_09_10_17.txt)

**Steps to reproduce:**

Have a PC in cyrillic, basically any symbols but english in the path, for example "Documents" would be "Документы"

**Minimal reproduction project:**
None. Install Flax Engine onto a Virtual Machine or something like that with one of the languages in cyrillic, then try to open the project, it will crash with error 0xe0434352

**Flax version:**
1.6

**Comment by mafiesto4** [comment]
Could you upload `C:\Users/stops/OneDrive/Документы/Flax Projects/FlaxSamples/FirstPersonShooterTemplate/Logs/Crash_2023_09_19_09_10_17/Minidump.dmp` file? It will contain more detailed info about crash location. It looks like engine properly starts, just something related to scripting crashed.

**Comment by KirillianAmu** [comment]
Hi! Uploaded. I think, barely use github. Let me know if anything else is required.
[crash.zip](https://github.com/FlaxEngine/FlaxEngine/files/12666735/crash.zip)

**Comment by mafiesto4** [comment]
Fixed in c374127de1d7979f218a49e0f29f5ba9cbed4886.
