### ISSUE TITLE
New LayersMask layers does not update visually on actors after creation/edit

### ISSUE THREAD

**Issue by yjplapian** [FlaxEngine/FlaxEngine#1440]
After accessing the Layers and Tags settings, adding new layers and saving out the changes the layers gets internally and visually updated in the settings object, but does get visually updated on an actor object. For now, you have to restart the editor to access edited layers on an actor object.

**Reproduction Steps**
1. Put an actor in the scene if there isn't one
2. Open up the Layers and Tags Settings object
3. Add a new layer in the LayersMask
4. Save changes in the Layers and Tags Settings object
5. Access any actor and navigate to the layersmask in the properties window under section general

**Flax version**
v1.6

**Comment by RuanLucasGD** [comment]
This is a normal behaviour:
https://discord.com/channels/437989205315158016/538664104856911883/1149351322034913290
https://github.com/FlaxEngine/FlaxEngine/issues/921

**Comment by Menotdan** [comment]
> This is a normal behaviour: https://discord.com/channels/437989205315158016/538664104856911883/1149351322034913290 #921

I don't think it should be. Would be nice to change it.

**Comment by yjplapian** [comment]
It feels pretty counter-intuitive as it is. I personally would think it would be nice to change it too.

**Comment by mafiesto4** [comment]
Game Settings (and all nested settings such as Layers and Tag settings) are `reloaded`/`applied` on editor start and when game starts in Editor but I guess we should sync those layers and tags better to provide smoother development to the devs.

**Comment by mafiesto4** [comment]
Added in fd679f0af59eb73244c39cb69107faf93b9358b9
