### ISSUE TITLE
Scale not applied to skeleton when importing glTF model

### ISSUE THREAD

**Issue by Arcnor** [FlaxEngine/FlaxEngine#1443]
**Issue description:**

As the title says, importing a glTF model and applying a scale to it doesn't apply said scale to the skeleton.

**Steps to reproduce:**

1. Import this model [character.zip](https://github.com/FlaxEngine/FlaxEngine/files/12663289/character.zip)
 (CC0 licensed, made by Kenney) as skinned with scale 100.
2. Check how it looks completely broken because limbs are too short.

**Minimal reproduction project:**

**Flax version:**

1.7 as of 5 days ago (commit 722133165)

**Comment by mafiesto4** [comment]
Fixed in 8007417fe53ad1dd2767abfe7a9312bbd5ec3cf7.
