### ISSUE TITLE
Scale not being applied when importing glTF model

### ISSUE THREAD

**Issue by Arcnor** [FlaxEngine/FlaxEngine#1445]
**Issue description:**

For some reason, changing the scale when importing some specific assets doesn't work.

**Steps to reproduce:**
1. Import this model [coin.zip](https://github.com/FlaxEngine/FlaxEngine/files/12663907/coin.zip) (CC0 license, made by Kenney) and try applying any scale to it.

**Minimal reproduction project:**

**Flax version:**

1.7 as of 5 days ago (commit https://github.com/FlaxEngine/FlaxEngine/commit/722133165b21757bbe643f7baae9a5c3442b4681)

**Comment by Arcnor** [comment]
@Tryibion not sure why you think this is a "Suggestion", the scale works correctly with other models, so I'd say this is a bug, like the previous similar issues I opened :)

**Comment by Tryibion** [comment]
We can change it ;)

**Comment by mafiesto4** [comment]
Fixed in 8007417fe53ad1dd2767abfe7a9312bbd5ec3cf7.
