### ISSUE TITLE
Renaming a directory in the project via the OS does not update when switching back to the project

### ISSUE THREAD

**Issue by slipster216** [FlaxEngine/FlaxEngine#1464]
**Issue description:**
Max OSX, did not check on windows. I renamed a folder outside of the editor, and it still showed the older folder name when switching back to flax. Expect that it would show the correct directory structure. 

**Steps to reproduce:**
Create a project. Add a folder. Go into explorer and rename a folder. Flip back to flax, notice the old name is used in the content browser.

**Flax version:**
1.6

**Comment by mafiesto4** [comment]
I wonder if #1454 fixed it

**Comment by mafiesto4** [comment]
Fixed in 5fe135e10b788dc5199ba6d5a49313cb095c8f38.
