### ISSUE TITLE
macOS Silicon "Cannot find compatible metal driver"

### ISSUE THREAD

**Issue by jzapdot** [FlaxEngine/FlaxEngine#1469]
**Issue description:**

I recently installed the latest version of Flax from the CI build [here](https://github.com/FlaxEngine/FlaxEngine/actions/runs/6247175989) for silicon mac (Ventura 13.5). After overcoming the .Net Core SDK issues outlined [here](https://github.com/FlaxEngine/FlaxEngine/issues/1254) and successfully launching the Flax editor to the graphics sample project I noticed in the console log that the Vulkan SDK was not being found, but it seemed like other Vulkan related functionality was being detected. I could still run the Flax player and see the sample FX, but I wanted to resolve this log warning.

> Building for Mac without Vulkan rendering backend (Vulkan SDK is missing) 

As a result I closed Flax and installed the latest version of the Vulkan SDK for mac found [here](https://vulkan.lunarg.com/sdk/home#mac:~:text=fc59dab871d0786c11aded33bcc07aabc2259e6a6f1d5484b02cd3aba20d943a-,Latest%20SDK,-MacOS). There was an interesting warning after completing the installation.

![image](https://github.com/FlaxEngine/FlaxEngine/assets/40764984/f0fd004a-dfda-429f-850b-6477a6490a12)

After installing the Vulkan SDK I reopened Flax and quickly got this error modal below.

![image](https://github.com/FlaxEngine/FlaxEngine/assets/40764984/8457d027-139e-40b6-bccd-5cf7c64a4e3f)

These are the two relevant log files to look at (before and after the Vulkan SDK installation).
**Before Vulkan SDK Install**
[Log_2023_09_20_16_09_20.txt](https://github.com/FlaxEngine/FlaxEngine/files/12678182/Log_2023_09_20_16_09_20.txt)

**After Vulkan SDK Install**
[Log_2023_09_20_18_59_00.txt](https://github.com/FlaxEngine/FlaxEngine/files/12678179/Log_2023_09_20_18_59_00.txt)

**Steps to reproduce:**

1. Download the latest mac editor above as linked and run on an macOS Silicon machine.
2. Clone the Flax sample projects
3. Install the latest Vulkan SDK.
4. Attempt to open the graphics sample project with Flax.

**Minimal reproduction project:**

None needed as in this case it uses the latest engine binaries as-is and uses the sample project as content.

**Flax version:**

https://github.com/FlaxEngine/FlaxEngine/commit/5c5c64cf761ebc79c4f53fb6eec6c88d0536a93d

**Comment by karlingen** [comment]
+1

**Comment by mafiesto4** [comment]
Seams like related to https://github.com/ocornut/imgui/pull/6109

![image](https://github.com/FlaxEngine/FlaxEngine/assets/3464853/b94f4aba-9f7d-47e4-a1f6-16316a798abe)

**Comment by mafiesto4** [comment]
Should be fixed in 17291a8a139bdd95715ffac21c2ead5139e67109.
