### ISSUE TITLE
StaticModel Actor Does Not Rotate with custom RigidBody Actor When the StaticModel is Parented to the custom RigidBody

### ISSUE THREAD

**Issue by Colten-Haggard-dev** [FlaxEngine/FlaxEngine#1471]
**Issue description:**

StaticModel transform does not transform when setting it as the child of a custom RigidBody actor after alter the StaticModel's Transform properity in the OnBeginPlay function of the custom RigidBody actor.

**Steps to reproduce:**

1. Create a custom actor derived from a RigidBody
2. Create a public Transform variable as a member of the custom RigidBody
3. Set the Transform variable to anything (I specifically changed only the scale)
4. Create a private StaticModel variable and a public Model variable as members of the custom RigidBody
5. Override the OnBeginPlay function
6. Inside of the function, add a StaticModel to the custom RigidBody as a child using the AddChild<> function and have its return set the StaticModel member variable
7. Set the newly created StaticModel actor's Model property to the Model member variable
8. Compile, put the custom actor into a scene with some objects to collide with, add a collision shape to the custom RigidBody, set any public member variables to desired values
9. Run the game and notice a lack of rotation from the model as the RigidBody rotates freely

**Minimal reproduction project:**

[NoRotateExample.zip](https://github.com/FlaxEngine/FlaxEngine/files/12679237/NoRotateExample.zip)

**Flax version:**

1.6.6344

**Comment by MineBill** [comment]
Make sure to initialize your custom transform variable to Identity:
```cs
public Transform CustomTransform = Transform.Identity;
```
Delete your current DerivedRigidBody actor to clear any serialized data it has and create new one.

**Comment by Colten-Haggard-dev** [comment]
I did that and it worked, before I close the issue, can you explain why that works?

**Comment by MineBill** [comment]
The Transform doesn't store a rotation but an orientation, which is a Quaternion. Quaternions have a fourth component, `w`, which is usually set to 1. When using an uninitialized Transform, the position, orientation and scale are all set to 0, including this `w` component. As a result, all matrix multiplications that happen with this transform produce wrong results. Initializing the transform with `Transform.Identity`, will set position to `Vector3.Zero`, scale to `Vector3.One` and lastly it will set the `w` component of the quaternion to 1.
