### ISSUE TITLE
Compile an error after changing BuildNativeCode to true

### ISSUE THREAD

**Issue by xiaoye97** [FlaxEngine/FlaxEngine#1473]
**Issue description:**
Compile an error after changing BuildNativeCode to true.

[Info] C:\Program Files (x86)\Flax\Flax_1.6\Source\ThirdParty\fmt\format.h(467): error C2039: "begin":
[Info] C:\Program Files (x86)\Flax\Flax_1.6\Source\ThirdParty\fmt\format.h(467): error C2794:
[Info] 2 tasks failed
[Error] Failed to run build tool, result: 1

**Steps to reproduce:**
Create new project, change `BuildNativeCode = false;` to `BuildNativeCode = true;`

**Minimal reproduction project:**
[CompileBugTest.zip](https://github.com/FlaxEngine/FlaxEngine/files/12681540/CompileBugTest.zip)

**Flax version:**
1.6

**Comment by MineBill** [comment]
Already fixed in #1283. You need a master build to compile c++ code on windows.

**Comment by xiaoye97** [comment]
> Already fixed in #1283. You need a master build to compile c++ code on windows.

Thank you, I'll give it a try right away
