### ISSUE TITLE
Split objects with multiple materials is not importing every material.

### ISSUE THREAD

**Issue by Menotdan** [FlaxEngine/FlaxEngine#1483]
**Issue description:**
When I try to import a model with multiple objects and multiple materials using the Split Objects option, it only imports one material, and the rest of the material slots are unfilled. It seems the recently added logic to prevent crashes when trying to do with with multiple objects having the **same** material has caused this. It also appears, from testing, that the `options.SplitObjects` field is not getting properly passed to the material importing code, as when I log it in my build, it shows false.

**Steps to reproduce:**
Drag TV.fbx (from .zip file) into content window, in import options, scroll down to split objects, and enable it. Then click import. You will notice that only one material gets imported into the `TV/` directory. There is several materials, however.

**Reproduction file:**
[TV.zip](https://github.com/FlaxEngine/FlaxEngine/files/12689138/TV.zip)

**Flax version:**
Master branch @ [97ed46b](https://github.com/FlaxEngine/FlaxEngine/commit/97ed46bc4ff36a0269b50b138c08908461ee9f96)

**Comment by mafiesto4** [comment]
Yeah it's a bug from the recent changes.

**Comment by mafiesto4** [comment]
Fixed in 248304a78f3ded68bc05e2cc0b488e02619f54a5
