### ISSUE TITLE
Specific cases of deleting a folder when it has files in it causes the folder itself to not be deleted, and you must delete it a second time.

### ISSUE THREAD

**Issue by Menotdan** [FlaxEngine/FlaxEngine#1484]
**Issue description:**
When I import a model, it created a folder with contents, but I later want to delete it, and then it will only delete the contents of the folder, and the folder itself has to be deleted a second time. 

**Steps to reproduce:**
Import the following model with split objects enabled, and then try to delete the created folder that contains the materials. The folder will need to be deleted twice. This may be related to #1483.
[TV.zip](https://github.com/FlaxEngine/FlaxEngine/files/12689230/TV.zip)

**Flax version:**
Master build @ [97ed46b](https://github.com/FlaxEngine/FlaxEngine/commit/97ed46bc4ff36a0269b50b138c08908461ee9f96)

**Comment by davevanegdom** [comment]
This issue also exists without importing as split objects

**Comment by mafiesto4** [comment]
That's the case when removing assets that loading or have been just loaded. Probably we need to safely unload all assets and add some delay for engine to close file handles before removing folders so that action won't fail leaving some empty folders around.

**Comment by mafiesto4** [comment]
Fixed in abd6881d7bee1db377ef63154d1b9a0082945e48.
