### ISSUE TITLE
Dublication via Ctlr + C, Ctrl + V crash the Editor (Assertion)

### ISSUE THREAD

**Issue by schmidt-florian** [FlaxEngine/FlaxEngine#1487]
**Issue Description:**
Tried to duplicate a content (file inside the content folder) file. It looks like a source file is not affected, because it does not duplicate that at all via Ctrl + C / V.

Ctrl + D works fine.
Ctrl + C and then Ctrl + V in the same places crash the editor.

![Pasted image 20230922005538](https://github.com/FlaxEngine/FlaxEngine/assets/14238126/e47bfd93-0048-4e38-ad4e-19fb02f247e6)

The ```dstId``` is valid and returns ```true```. But the ```srcPath``` equals the ```dstPath```, so the ```Assert``` fails.

What I would expect is the same duplication behavior as Ctrl + D.

**Steps to reproduce:**
Open any project, select any content file (Scene, Prefab, Material, etc.), press Ctrl + C, Ctrl + V -> Crash

**Minimal reproduction project:**
any project

**Flax version:**
1.6.6344

**Comment by mafiesto4** [comment]
Fixed in #1488
