### ISSUE TITLE
Material Sample Layer not updating if child Material is updated

### ISSUE THREAD

**Issue by schmidt-florian** [FlaxEngine/FlaxEngine#1489]
**Issue Description:**
The material does not update if the sample layer material is updated.
If I force save the Material with a small node position update, it updates, or via ```Refresh thumbnail```.

GIF (4MB):
![GIF](https://github.com/FlaxEngine/FlaxEngine/assets/14238126/a767b1bd-7905-4757-959e-3e19c4839770)

**Steps to reproduce:**
Open the Test project and navigate to Content/Materials
***OR***
Any Project:
Create two Materials A & B
Add a Sample Layer to Material A and select Material B; Save.
Material A has Material B as a Sample Layer included.
Change the Color of Material B. Material A does not update.

**Minimal reproduction project:**
[Test.zip (500kb)](https://github.com/FlaxEngine/FlaxEngine/files/12694285/Test.zip)

**Flax version:**
1.6.6344

**Comment by mafiesto4** [comment]
Fixed in 4a8c94e9d419b0393968dc70b2b3f70ee2daa720.
