### ISSUE TITLE
Objects slide off each other if top weight is heavier than the bottom

### ISSUE THREAD

**Issue by SeaPeaMe** [FlaxEngine/FlaxEngine#15]
When I place two objects on top of each other (Bottom 10kg, top 30kg), they seem to stay put, but as soon as I move the top one so that it is slightly off-center, it just starts sliding around until I make it near the center again.

https://user-images.githubusercontent.com/39147581/102701988-6f5de080-42b1-11eb-8a54-817bd4b78ed2.mp4

**Steps to reproduce:**
1. Create 2 cubes, one on top of the other
2. Make top cube 30kg, and bottom cube 10kg
3. Move the top cube off-center and watch it magically slide off

**Flax version:**
Ver 1.0

**Comment by mafiesto4** [comment]
@RuanLucasGD configrmed that it's fixed in the upcoming *Flax 1.6* (with PhysX 5)
