### ISSUE TITLE
FBX model import silently fails, logs "Minimum supported version is 6.2"

### ISSUE THREAD

**Issue by heckert-gamedev** [FlaxEngine/FlaxEngine#1507]
**Issue description:**

Following the YT tutorial series part two I tried to import a skinned mesh model.
The one used in the video isn't available anymore (at all, and also tagged costing  money, so sadly not a good choice anymore), so I tried a different one:

https://www.cgtrader.com/free-3d-models/character/other/berry-twig

When I imported the model, nothing happened (no model appeared in the Content's folder).

Checking the log:

```
[ 01:08:19.634 ]: [Info] Importing model from '/home/username/Downloads/CG_Trader202309/uploads_files_1917358_fox.fbx'
[ 01:08:19.636 ]: [Error] Cannot import model file. Unsupported FBX file format version. Minimum supported version is 6.2
[ 01:08:19.636 ]: [Error] Cannot import file '/home/username/Downloads/CG_Trader202309/uploads_files_1917358_fox.fbx'! Result: Error
```

Checking the FBX file shows:

```
uploads_files_1917358_fox.fbx:     Kaydara FBX model, version 6100
```

If the model import fails then this shouldn't be silent but at least give feedback to the user so they know what happened and why.

**Steps to reproduce:**

Import model's FBX `uploads_files_1917358_fox.fbx`

**Minimal reproduction project:**

I would think any freshly created project will do.

**Flax version:**

Released version 1.6 (running on Linux but I doubt this makes a difference for the importer code)

**Comment by mafiesto4** [comment]
Fixed in #2672
