### ISSUE TITLE
Editor Fails to compile scripts when setting BuildNativeCode to true in blank project

### ISSUE THREAD

**Issue by AlanWills** [FlaxEngine/FlaxEngine#1508]
**Issue description:**

I've been attempting to create a C++ script which is then exposed to C# by following [this tutorial](https://docs.flaxengine.com/manual/scripting/cpp/index.html).
I seem to be having issues enabling C++ script support - I get compiler errors when enabling BuildNativeCode on the Game project without any C++ scripts in the project.
I've tried to use a separate GameModule and seem to encounter issues with the MODULE_API macro not being defined and numerous other compiler errors.
I'm wondering if it has something to do with my Toolset, so I will try installing v140, but this is a bit of a blocker for me as I am unable to use any C++ scripts (I wish to port over some C++ code I have into Flax).

I have VS 2022 installed
I have Windows 10 SDK installed (see below): 
![image](https://github.com/FlaxEngine/FlaxEngine/assets/8849391/606c792b-eb66-4def-b829-476d0421c805)
I have MS VS C++ Toolset 140 or newer (143, see below)
![image](https://github.com/FlaxEngine/FlaxEngine/assets/8849391/6960a0e8-64ac-448c-8f38-40ab5ff07e1a)

[Log_2023_09_24_12_22_51.txt](https://github.com/FlaxEngine/FlaxEngine/files/12708383/Log_2023_09_24_12_22_51.txt)

**Steps to reproduce:**

1) Create a new Project
2) Open Game.Build.cs
3) Set BuildNativeCode to true
4) Observe that scripts now fail to compile

**Minimal reproduction project:**

[CppBuildFailure.zip](https://github.com/FlaxEngine/FlaxEngine/files/12708381/CppBuildFailure.zip)

**Flax version:**

v1.6.6344

**Comment by MineBill** [comment]
#1473

**Comment by AlanWills** [comment]
Closing as a duplicate of linked ticket.
