### ISSUE TITLE
[BUG] Physics layers matrix is incorrect

### ISSUE THREAD

**Issue by Vizepi** [FlaxEngine/FlaxEngine#153]
**Issue description:**
When editing the Physics Settings, the Layers matrix is incorrect.
One of the row or column order should be inverted.
Maybe it is not incorrect code-wise, but it is for sure not displayed properly.

**Steps to reproduce:**
- Open a project
- Open Game/Content/Settings/Physics Settings.json
- See the matrix is not correct

**Flax version:**
1.0.6215

**More Infos:**
![image](https://user-images.githubusercontent.com/9052852/105643736-ee869b80-5e91-11eb-953c-7f0ff2d04503.png)
You can see on this image that it is not possible to edit layer interactions between *Layer 3* and *Player*, between *Layer 3* and *Bullets* or between *Bullets* and *Bullets*. The expected matrix is the following:
![image](https://user-images.githubusercontent.com/9052852/105643817-7076c480-5e92-11eb-862d-72c199a130d3.png)

**Comment by mafiesto4** [comment]
Fixed by #227
