### ISSUE TITLE
Editor crash if disable vehicle

### ISSUE THREAD

**Issue by RuanLucasGD** [FlaxEngine/FlaxEngine#1530]
If you disable a vehicle actor with "use CCD" enabled on vehicle Rigidbody and press play the editor crash

**Steps to reproduce:**
1. create a vehicle
2. mark "use CCD" as enabled on vehicle rigidbody
3. disable vehicle
4. press f5 to start game
5. crash

**Minimal reproduction project:**
[Car Test.zip](https://github.com/FlaxEngine/FlaxEngine/files/12730716/Car.Test.zip)

**Flax version:**
1.6 master

**Comment by mafiesto4** [comment]
It looks like a bug in PhysX itself. We can update to the latest PhysX and try to fix it (if it has not been there yet).

**Comment by abrasivetroop** [comment]
I discovered a different bug that might be related to this. If you try to duplicate disabled vehicle actor editor crashes.

**Comment by mafiesto4** [comment]
Fixed in 6289b9d15a2c1c7a5e87f6bc69227bcfbf4fe626.
