### ISSUE TITLE
Volume corrupted after setting up a postfx material

### ISSUE THREAD

**Issue by Lymdun** [FlaxEngine/FlaxEngine#1531]
**Issue description:**

Project ends up corrupted after setting a postfx material in a postfx volume, as the editor crashes every time I try to open the PostFxVolume, and have a corrupted look when trying to look at its properties:
![](https://i.imgur.com/0cMZqK4.png)

Might be related, but if I remove the postfx volume and set the postfx material in graphics settings instead, it doesn't work and the material isn't saved.

Logs:
[Log_2023_09_24_01_40_02.txt](https://github.com/FlaxEngine/FlaxEngine/files/12732512/Log_2023_09_24_01_40_02.txt)

**Steps to reproduce:**
Try to set up a simple postfx material (such as https://forum.flaxengine.com/t/made-a-cel-shader-in-flax-engine/568) and set it as a postfx material in a postfx volume.

**Minimal reproduction project:**
[repro.zip](https://github.com/FlaxEngine/FlaxEngine/files/12732525/repro.zip)

**Flax version:**
1.6.6344

**Comment by mafiesto4** [comment]
Fixed in #1314
