### ISSUE TITLE
Terrain.SetupPatchHeightMap changes in editor are not saved to the scene.

### ISSUE THREAD

**Issue by AlTheSlacker** [FlaxEngine/FlaxEngine#1532]
Using some C# to modify a terrain heightmap in the editor results in the heightmap changes being lost when closing the editor and re-opening.

Forum Reference: 
https://forum.flaxengine.com/t/problem-saving-terrain-heightmap-data-after-change-in-editor/1280

Steps to reproduce:
Create new project
Create terrain
Modify terrain using a C# custom editor to create a heightmap and apply it using Terrain.SetupPatchHeightMap()
Observe the terrain change in the editor and save the scene, upon reloading the changes are lost.

Reproduction Code
```
using System;
using FlaxEngine;
using FlaxEditor.CustomEditors.Elements;

#if FLAX_EDITOR
using FlaxEditor.CustomEditors.Editors;
using FlaxEditor.CustomEditors;


namespace TerrainSystem
{
    [CustomEditor(typeof(Terrain))]
    public class Reproducer : GenericEditor
    {
        public override DisplayStyle Style => DisplayStyle.Inline;

        public override void Initialize(LayoutElementsContainer layout)
        {
            base.Initialize(layout);
            Terrain terrain = (Terrain)this.Values[0];

            layout.Label("Not Saved:", TextAlignment.Near);
            layout.Space(10);

            ButtonElement button = layout.Button("Generate Height Map", Color.Gray);
            button.Button.Clicked += () => GenerateMap(terrain);

        }

        private void GenerateMap(Terrain terrain)
        {
            Debug.Log("Updating heightmap");
            int heightMapSize = terrain.ChunkSize * FlaxEngine.Terrain.PatchEdgeChunksCount + 1;
            int mapSize = 509;
            int heightMapLength = heightMapSize * heightMapSize;
            float[] heightmap = new float[heightMapLength];
            Random rnd = new Random();

            for (int y = 0; y < mapSize; y++)
            {
                for (int x = 0; x < mapSize; x++)
                {
                    heightmap[y * mapSize + x] = ((float)rnd.NextDouble()) * 500;
                }
            }

            Int2 patchCoord = new Int2(0, 0);
            terrain.SetupPatchHeightMap(ref patchCoord, heightmap, null, true);

        }
    }
}
#endif
```

Create a new terrain, scroll to the bottom of properties and click “Generate Height Map”
You will see a random noise heightmap. Save All.

Flax version: 1.6.6344

Additional:
Upon re-loading the scene, the height map data is lost. There also seem to be some robustness issues with the terrain material data being lost on re-load. But the loss of height map data is apparent regardless of the terrain material being set to Default Terrain Material or left blank.

After a while of doing this data can be seen accumulating in Content/ SceneData/ Scene/ Terrain/ as previously generated heightmap data.

**Comment by mafiesto4** [comment]
That works by design because you pass `forceUseVirtualStorage=true` which forces using virtual (in-memory) heightmap instead of an asset on drive. If you change this to:
```cs
terrain.SetupPatchHeightMap(ref patchCoord, heightmap);
```
then terrain heightmap is saved in project and will be usable later (incl cooked game).

**Comment by AlTheSlacker** [comment]
Thanks so much for explaining that, sorry I did not properly investigate SetupPatchHeightMap, I just pasted it from the dynamic terrain example.
