### ISSUE TITLE
Feature Request: Ability to Set Custom Projection Matrix for Camera Transitions

### ISSUE THREAD

**Issue by schmidt-florian** [FlaxEngine/FlaxEngine#1536]
**Issue description:**
Currently, Flax Engine does not provide a way to directly set a custom projection matrix for the camera. This feature is essential for achieving smooth transitions between different camera modes, such as orthographic and perspective. 

**Use Case:**
A common use case for this feature is to smoothly transition between orthographic and perspective camera modes. This is especially useful in applications like level editors, architectural visualization, and games that require dynamic camera perspectives.

**Example**
This source code is from an old plugin I wrote for Unity. It is halfway converted to Flax.
I am aware of the Method GetMatrices. I did not implement GetMatrices to the code because I did not find a way to set the matrices back. 

Please note that the code below is not optimized or bug-free, but it worked in unity.

```csharp
public static void TransitionProspectiveOrthographic(this Camera camera, float time, bool toOrtho)
{
    bool currentlyOrthographic = !toOrtho;
    Matrix orthoMat, persMat;
    if (currentlyOrthographic)
    {
        orthoMat = camera.projectionMatrix;
        camera.UsePerspective = true;
        camera.ResetProjectionMatrix();
        persMat = camera.projectionMatrix;
    }
    else
    {
        persMat = camera.projectionMatrix;
        camera.UsePerspective = false;
        camera.ResetProjectionMatrix();
        orthoMat = camera.projectionMatrix;
    }
    camera.UsePerspective = !currentlyOrthographic;            
    if (time < 1.0f)
    {
        if (currentlyOrthographic)
        {
            camera.projectionMatrix = MatrixLerp(orthoMat, persMat, time);
        }
        else
        {
            camera.projectionMatrix = MatrixLerp(persMat, orthoMat, Interpolate.Ease(Interpolate.EaseType.EaseInCubic)(0f, 1f, time, 1f));
        }
    }
    else
    {
        camera.UsePerspective = currentlyOrthographic;
        camera.ResetProjectionMatrix();
    }
}
```

**Flax version:**
Flax Engine Version: master 248304a

**Comment by mafiesto4** [comment]
`Camera` in Flax doesn't support changing matrix manually but the rendering layer does, here is an example code where you can use custom view/projection matrices for game rendering: https://docs.flaxengine.com/manual/graphics/cameras/index.html#override-view
