### ISSUE TITLE
No .sln file generated for visual studio community

### ISSUE THREAD

**Issue by LeVoid** [FlaxEngine/FlaxEngine#1537]
## **Issue description**

I created a new project.
In my old project I was able to double-click any script to launch Visual Studio Community (presumably) using the the .sln file in the project.
Now when I create a new project, no solution file is generated and as a result the IDE doesn't open.

Log-File: 
[Log_2023_09_27_18_26_08.txt](https://github.com/FlaxEngine/FlaxEngine/files/12741214/Log_2023_09_27_18_26_08.txt)

## **Steps to reproduce**

- Create new project in Version 1.6 of Flaxengine
- Create a .cs file
- Double-click script to try to open it

The status-bar in the bottom right will open telling you it's "Starting code editor...", but disappear after a short while with no editor opening.

## **Minimal reproduction project**

[MinimalReproProject.zip](https://github.com/FlaxEngine/FlaxEngine/files/12740944/MinimalReproProject.zip)

## **Flax version**

Flaxengine: 1.6
Visual Studio Community: 2022 (Version: 17.7.4)
.NET: 7.0

**Comment by GoaLitiuM** [comment]
Can you post the log files from a session where you try to select the script in Flax Editor? Have you tried regenerating the project files?

**Comment by LeVoid** [comment]
> Can you post the log files from a session where you try to select the script in Flax Editor? Have you tried regenerating the project files?

Hi, yes. Updated the initial issue with the log file.

**Comment by mafiesto4** [comment]
Should be fixed by 4149da5f9edbfdae923c6ad7f84d3136d265c9b0 so the build tool won't fail when there are missing Windows SDK components not needed for `.sln` file generation (for C#-only game).
