### ISSUE TITLE
Prefab Issue: Reset actor position on prefab

### ISSUE THREAD

**Issue by RuanLucasGD** [FlaxEngine/FlaxEngine#1545]
**Issue description:**
If i create a prefab on scene with non identity position and reset position on prefab editor the actor on scene reset your position too. The expectation would be to mantain its positon.

**Steps to reproduce:**
1. Create an actor on your scene (not on 0, 0, 0). 
2. Create a prefab
3. Open the prefab
4. Reset position of the actor on your prefab editor
5. The actor of your scene has your position reseted too

**Minimal reproduction project:**

[Desktop 2023.09.28 - 09.04.19.01.webm](https://github.com/FlaxEngine/FlaxEngine/assets/79365912/341e0b93-2144-4ccb-a2c5-c2d1606bacac)

**Flax version:**
1.6 master

**Comment by mafiesto4** [comment]
Should the same be applied to rotation and scale? (instance transformation preserved over the prefab values for the prefab actor root) What if prefab gets modified default scale and applied - should we apply this scale to instances or preserve scale of spawned actors?

**Comment by RuanLucasGD** [comment]
@mafiesto4 position and rotation needs to be preserved and scale applied (if the actor scale of scene hasn't modified).

Position and scale needs to be preserved because if i'm making a level with various duplicated prefabs and reset the transform i can lose the level.

**Comment by mafiesto4** [comment]
Okay, let's preserve the local changes to the whole transformation of the root actor (unless it uses default, then prefab value can be used - eg. for the scale).

**Comment by ElevenArt** [comment]
@mafiesto4 Once the Disallowed Apply transform to Prefab is resolved, then
it would be good if Create Prefab from Scene Hierarchy did not save the transform to the Prefab. The position of the instance should be given by the instance and not by the prefab unless I change it in the Prefab asset.

**Comment by mafiesto4** [comment]
@ElevenArt Good idea!

**Comment by mafiesto4** [comment]
Implemented in 21edb43bb1a72773c86d4b09ea3295b2584a555d.

**Comment by ElevenArt** [comment]
It works, thanks.
