### ISSUE TITLE
Prefab Issue: I canno't reset array list correctly

### ISSUE THREAD

**Issue by RuanLucasGD** [FlaxEngine/FlaxEngine#1546]
**Issue description:**
Reset array data to prefab don't work correctly.

**Steps to reproduce:**
1. Create a prefab with script, this script need a array.
2. Add the prefab to your scene
3. Edit the array of your prefab
4. Try reset.

**Minimal reproduction project:**

https://github.com/FlaxEngine/FlaxEngine/assets/79365912/d34c7756-cce6-4eb9-aafb-266e5f6543d2

**Flax version:**
1.6 master

**Comment by Menotdan** [comment]
Can confirm this. It appears that the code behind "Revert to Prefab" is looping over every value editor in the array and checking if it has a reference value in the prefab, which the extra array elements don't, so it can't replace them. I haven't investigated the code much beyond just watching it through a debugger though.

**Comment by Menotdan** [comment]
@mafiesto4 I saw https://github.com/FlaxEngine/FlaxEngine/commit/fe1a65565420cd9b3b6e88fea00e044b1b0fe8a1 fixes #1548, does it also fix this issue? Or are there other issues still?

**Comment by mafiesto4** [comment]
Yeah it's fixed now.
