### ISSUE TITLE
Prefab usability adjust: Add marker for changed values of arrays

### ISSUE THREAD

**Issue by RuanLucasGD** [FlaxEngine/FlaxEngine#1548]
**Issue description:**
When you edit a value of prefab on your scene, the property is marked with a blue indicator, but this indicator don't exist on arrays.

Edited properties
![image](https://github.com/FlaxEngine/FlaxEngine/assets/79365912/0c98df0a-702e-462a-b88c-6562caee8d14)

Edited arrays (no indicator)
![image](https://github.com/FlaxEngine/FlaxEngine/assets/79365912/706a94d9-443b-44f1-9849-1242cf95e50d)

**Flax version:**
1.6 master

**Comment by mafiesto4** [comment]
In fe1a65565420cd9b3b6e88fea00e044b1b0fe8a1 I added prefab modification indicator (blue line) to array size field and each item to indicate modifications. Also, right-click context menu allows to revert value to prefab easily (with undo).
