### ISSUE TITLE
UI needs Bordered Sprites

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#155]
Flax needs sprite borders for buttons and panels so textures can be scaled with different dimensions and not cause stretching to the border.

Unity has this and its called Sprite Borders:
![image](https://user-images.githubusercontent.com/35228400/105647608-f595c400-5efa-11eb-9c90-5b2d389ee6a9.png)

Unreal has this and its part of the Draw As function:
![image](https://user-images.githubusercontent.com/35228400/105647947-f7608700-5efc-11eb-82e1-cde47df55a0b.png)

To understand how this function works and why it is important, please see here:
https://www.youtube.com/watch?v=SJJtEPhV_MI

**Comment by honzapatCZ** [comment]
There are Sprites already, so the sprite editor could support borders, needed to say this starts to be real mandatory with 2D support

**Comment by mafiesto4** [comment]
Implemented in 44433bf3b4ffc0fee16db8e79f0b0b442d135cb8.
