### ISSUE TITLE
Visual Scripting: Get LengthSquared (and other nodes) throw exception and return null

### ISSUE THREAD

**Issue by Chikinsupu** [FlaxEngine/FlaxEngine#1552]
**Issue description:**

Depending on the version:

Version 1.6:
Using Get LengthSquared, Get Length, Distance node, and probably many other nodes of the same kind on vector3 throws Failed to call Method exception.

> [ 00:00:07.988 ]: [Error] Failed to call method 'FlaxEngine.Vector3.get_LengthSquared' (args count: 0) with invalid object instance of type 'FlaxEngine.Float3'
> [ 00:00:07.988 ]: [Error] Visual Script stack trace:
> [ 00:00:07.988 ]: [Error]     at Culprit:b41ab51744e77610f0ff009855f0b55b in node FlaxEngine.Vector3.get_LengthSquared()
>     at Culprit:b41ab51744e77610f0ff009855f0b55b in node FlaxEngine.Debug.Log()
>     at Culprit:b41ab51744e77610f0ff009855f0b55b in node OnEnable()
> 

Version Master:
Using Get LengthSquared, Get Length, Distance node, and probably many other nodes of the same kind on vector3 throws native interop exception: Invalid ManagedHandle exception.

> 
> [ 00:00:17.712 ]: [Error] Native interop exception!
> [ 00:00:17.725 ]: [Warning] Exception has been thrown during InvokeMethod. Invalid ManagedHandle
> Stack strace:
>    at FlaxEngine.Interop.ManagedHandle.ManagedHandlePool.GetObject(IntPtr handle) in D:\a\FlaxEngine\FlaxEngine\Source\Engine\Engine\NativeInterop.Managed.cs:line 537
>    at FlaxEngine.Interop.NativeInterop.Invoker.InvokerRet0`2.MarshalAndInvoke(Object delegateContext, ManagedHandle instancePtr, IntPtr paramPtr) in D:\a\FlaxEngine\FlaxEngine\Source\Engine\Engine\NativeInterop.Invoker.cs:line 841
>    at FlaxEngine.Interop.NativeInterop.InvokeMethod(ManagedHandle instanceHandle, ManagedHandle methodHandle, IntPtr paramPtr, IntPtr exceptionPtr) in D:\a\FlaxEngine\FlaxEngine\Source\Engine\Engine\NativeInterop.Unmanaged.cs:line 704
> [ 00:00:17.725 ]: [Error] Exception has been thrown during InvokeMethod.
> Invalid ManagedHandle
> [ 00:00:17.725 ]: [Error] Visual Script stack trace:
> [ 00:00:17.725 ]: [Error]     at Culprit:b41ab51744e77610f0ff009855f0b55b in node FlaxEngine.Vector3.get_LengthSquared()
>     at Culprit:b41ab51744e77610f0ff009855f0b55b in node FlaxEngine.Debug.Log()
>     at Culprit:b41ab51744e77610f0ff009855f0b55b in node OnEnable()

**Steps to reproduce:**
![image](https://github.com/FlaxEngine/FlaxEngine/assets/6757167/8b500157-95e4-4f15-9d55-e712d28fbb3a)

1. Create Visual Script
2. Create Vector3 of any kind, doesn't matter if its a parameter, constant, got packed etc.
3. Connect Vector3 to Get LengthSquared node or any other listed node
4. Exception gets thrown in output log when node gets invoked
5. Node itself returns null

**Minimal reproduction project:**
[GetLengthException.zip](https://github.com/FlaxEngine/FlaxEngine/files/12754049/GetLengthException.zip)

1. Open project
2. Open scene
3. Press play
4. Exception gets thrown (see output log)
5. null gets printed in console log

There are 2 log files in the zip. One with the master exception and one with the 1.6 exception.
Master Log: Master_Log_2023_09_29_23_18_22
1.6 Log: OneSix_Log_2023_09_29_23_20_14

**Flax version:**
Welp 1.6 or master :)))))

**Comment by mafiesto4** [comment]
Fixed in #1555
