### ISSUE TITLE
HDRI not working on DirectX 10

### ISSUE THREAD

**Issue by alec1o** [FlaxEngine/FlaxEngine#1558]
**Issue description:**

The HDRI skybox not working on DirectX 10 build

**Steps to reproduce:**
* Create new project
* Add skybox hdri
* Windows setting ``Only enable DirectX 10``
* Build

**Minimal reproduction project:**

DirectX 10
![dx10 result](https://github.com/FlaxEngine/FlaxEngine/assets/100610503/659230fc-3f86-42e6-a27b-eab0d4397bfb)
![dx10 setting](https://github.com/FlaxEngine/FlaxEngine/assets/100610503/e0cbc0e9-ce47-424f-9b50-a114ee273f62)

DirectX 11
![dx11 result](https://github.com/FlaxEngine/FlaxEngine/assets/100610503/2e8c0a16-f89b-4158-a966-0b29b1a6c800)

![dx11 setting](https://github.com/FlaxEngine/FlaxEngine/assets/100610503/779ab8ff-ec6a-46a4-b461-037d7ed4147b)

**Flax version:**
1.6.6344

**Comment by mafiesto4** [comment]
That texture probably uses BC6/BC7 format thus it's not supported by GPU driver that runs in DirectX 10 mode. We could add a software decoder for runtime to decompress this texture on CPU and send in a raw `RGBA16` format as a fallback. But ofc D3D10 is super old graphics API with very low usage in players specs stats.

**Comment by alec1o** [comment]
Yes i know, DX10 will soon is legacy. Never mind about it i'm just exploring FlaxEngine resources i won't use it
