### ISSUE TITLE
Crash when selecting Sprite from the Type dropdown box in UI

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#156]
Process to repeat.
Select the Sprite option.
![image](https://user-images.githubusercontent.com/35228400/105647742-d481a300-5efb-11eb-9112-15c4cc12a08a.png)

You will get this error:
![image](https://user-images.githubusercontent.com/35228400/105647768-f7ac5280-5efb-11eb-9d80-fe1526d2e44c.png)

Appears that a null is coming through:
![image](https://user-images.githubusercontent.com/35228400/105647726-b5831100-5efb-11eb-8b97-ad6d9b3c8d1b.png)

### Possible Solution
Crash is related to this line (which appears multiple times across various functions):
    RENDER2D_CHECK_RENDERING_STATE;
    if (spriteHandle.Index == INVALID_INDEX || !spriteHandle.Atlas->GetTexture()->HasResidentMip())
        return;

Changing it to this stops the crashing, although I don't know if it breaks this check:
    RENDER2D_CHECK_RENDERING_STATE;
    if (spriteHandle.Index == INVALID_INDEX || **!spriteHandle.Atlas ||** !spriteHandle.Atlas->GetTexture()->HasResidentMip())
        return;

**Comment by Zbyl** [comment]
This is already fixed in code, as suggested in the comment above.
This issue can be closed.

**Comment by mafiesto4** [comment]
Yeah, it has been fixed for 1.2 update 42461f1b4ae7a2bc48f6120e1f4429d8ae1f35e4
