### ISSUE TITLE
Can't view UI in Prefab or Editor when in Screen Space

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#157]
There is currently no way to view your UI in the prefab or in the Editor when in Screen Space.

Prefab:
![image](https://user-images.githubusercontent.com/35228400/105652242-e4ee4980-5f0c-11eb-815c-5bf9434bd794.png)

Editor and Game:
![image](https://user-images.githubusercontent.com/35228400/105652355-20891380-5f0d-11eb-9529-13950660d596.png)

**Comment by honzapatCZ** [comment]
Not a bug, its completely missing feature

**Comment by mafiesto4** [comment]
There was already a preview of the control in a prefab (root only).
![image](https://user-images.githubusercontent.com/3464853/106963703-45695c00-6741-11eb-9155-4346c6e69709.png)

I added support for previewing UI Canvas in the prefab editor (all modes: Screen Space, Camera Space, and World Space) https://github.com/FlaxEngine/FlaxEngine/commit/78e4ba2f1711a5bc2f10735e0ca890fd08ee9b53.

https://user-images.githubusercontent.com/3464853/107084109-e7974b80-67f6-11eb-8115-10e76756a648.mp4
