### ISSUE TITLE
1.7: Access folders from the root folder of a project crashes when running under Visual Studio.

### ISSUE THREAD

**Issue by Menotdan** [FlaxEngine/FlaxEngine#1576]
**Issue description:**
When I try to access any direct child of a project's root folder from the content window, the editor crashes as shown here:
[Video](https://youtu.be/uP_sD4EurG8), but it only appears to happen when running the build under Visual Studio. If I run my dev build through the launcher, the crash does not occur.

**Steps to reproduce:**
Build latest 1.7 and run under visual studio, open a new project (the one I used originated from master branch 1.6, in case that matters, it doesn't appear to on my end, both one from 1.6 and 1.7 crash), and go to the project's root folder, then double-click the "Content" folder, and the editor will crash.

**Flax version:**
1.7.6400

**Comment by mafiesto4** [comment]
I'm pretty sure that it's not a crash but C# exception that is caught by C++ debugger in Visual Studio.

Could you attach a log from that run?

**Comment by Menotdan** [comment]
> I'm pretty sure that it's not a crash but C# exception that is caught by C++ debugger in Visual Studio.
> 
> Could you attach a log from that run?

Sorry, forgot to close this, it was already fixed. The crash was from Tryibion's tooltip changes not having the null check merged.
