### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by NoriteSC** [FlaxEngine/FlaxEngine#1579]
**Issue description:**

the  [               `var items = target.Folder.Children;`](https://github.com/FlaxEngine/FlaxEngine/blob/6d92d0b58f4a38b1273b236702153d95983b5224/Source/Editor/Windows/ContentWindow.cs#L995) crashes the editor because Folder is null
**Steps to reproduce:**

**Minimal reproduction project:**

run editor without any project

**Flax version:**

master

**Comment by mafiesto4** [comment]
Fixed in #1590
