### ISSUE TITLE
Editor sometimes crashes when dragging bars.

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#158]
**Issue:**

Editor crashes sometimes when dragging the center bar (red) from the left all the way to the far right (green). I've been unable to replicate exactly which actions cause it to crash.

![image](https://user-images.githubusercontent.com/35228400/105652757-31865480-5f0e-11eb-87f5-8fc29ba4f54c.png)

I did manage to capture a screen shot of it crashing once:
![image](https://user-images.githubusercontent.com/35228400/105652871-790ce080-5f0e-11eb-9401-72c563ca9f7e.png)

**Comment by W2Wizard** [comment]
The issue should be closed, it was already fixed by @VNNCC .
