### ISSUE TITLE
Rider sets all files automatically to ignored

### ISSUE THREAD

**Issue by schmidt-florian** [FlaxEngine/FlaxEngine#1580]
**Issue description:**
Every script is automatically set to ignored and it is not possible to stop ignoring the file.

![image](https://github.com/FlaxEngine/FlaxEngine/assets/14238126/03321954-23c0-406b-9465-51dae06f77ec)

**Additional Information**
The behavior is the same in Visual Studio with Resharper. I can't say for sure that it's a Flax bug. However, I never saw this behavior with Rider with normal C# Projects and Unity projects in the past 5 years. So I think this is an issue from Flax Project Generation or something like that. I searched Rider's log files more or less successfully and couldn't find any error messages. Of course, clearing the cache, etc. doesn't help either, as it's a brand-new project. (But of course, I tried)

**Steps to reproduce:**
Create a new project.
Create a script and open Rider
Produce a compiling error.
The error is detected in the file. However, the solution-wide analysis stays without error.
If inspected in the Error Window, there can be found the file as ignored.
It is not possible to stop ignoring the file.

**Flax version:**
master [6d92d0b](https://github.com/FlaxEngine/FlaxEngine/commit/6d92d0b58f4a38b1273b236702153d95983b5224)

Toolbox Rider 2023.2.2

**Comment by MineBill** [comment]
Cannot reproduce:
![image](https://github.com/FlaxEngine/FlaxEngine/assets/30367251/f18c8306-8147-4f9c-ba5c-c5efccf12af4)

**Comment by schmidt-florian** [comment]
This is very strange. I recreated the problem on my two PCs.

Can you tell me which Rider version and installation type (standalone, toolbox) you are using?

**Comment by MineBill** [comment]
Try setting the configuration for the Plugin by right-clicking in the Solution -> Properties:
![image](https://github.com/FlaxEngine/FlaxEngine/assets/30367251/70ccf231-1bcc-40c2-b4cd-d015299096d1)

**Comment by schmidt-florian** [comment]
Thanks for the tip, that gives the right hint. The Configuration was already set to Dev | Win64. However, the "Build" Checkbox was not set on the plugin projects. I just needed to set on the plugin projects "Build" to true and then I could uningore existing errors and new errors are tracked correctly.
