### ISSUE TITLE
[Bug] Flax destroys all pending objects registred with Destroy() after overflow

### ISSUE THREAD

**Issue by averon420** [FlaxEngine/FlaxEngine#1584]
**Issue description:**
while playing arround with the example of third person shooter and modifing the firerate I noticed a strange behaviour of flax:
when you have too many (many in sense of triggering this bug) bullets registred with `Destroy(object, timeout)` the engine will lag and wipe all pending objects at the same time.

**Steps to reproduce:**

1. Download the "ThirdPersonShooter" example and increase the firerate to about 1000
2. Keep shooting till all bullets go vanish
[Youtube video](https://www.youtube.com/watch?v=mC6Z3tw6Drw)

**Flax version:**
1.6

**Comment by mafiesto4** [comment]
Fixed in 8e23781153894bea467c30b634e1af1082516897.
