### ISSUE TITLE
Navigation Grid remains visible even after deleting the Nav Mesh Bounds Volume.

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#159]
Navigation Grid remains visible even after deleting the Nav Mesh Bounds Volume.

Steps to reproduce:

1. Create a Nav Mesh Bounds Volume.
2. Turn on View -> Show -> Navigation.
2. Delete the Nav Mesh Bounds Volume.

![image](https://user-images.githubusercontent.com/35228400/105674928-601b2400-5f3c-11eb-9d2f-5902990a8ef4.png)

**Comment by mafiesto4** [comment]
Probably fixed for 1.1 version but I'll check it later.

**Comment by mafiesto4** [comment]
Fixed in 822d8c947ea7e6e533959feeb67e4f33fd1bc536.
