### ISSUE TITLE
Segfault in ContentWindow prohibits saving editor option changes

### ISSUE THREAD

**Issue by nothingTVatYT** [FlaxEngine/FlaxEngine#1591]
**Issue description:**
Change the medium font size in the editor options and watch the output log for segfault errors. You may have to try and revert your changes . The segfault breaks the signal processing of the options window so no changes can be saved at this point.

**Steps to reproduce:**
Just change the medium font size in the editor options and the segfault appears.

**Minimal reproduction project:**
It happens independent on the project.

**Flax version:**
Version 1.6.6345

This PR fixes the crash with a null check:  Fix segfault: target can be null when font size is changed #1590 https://github.com/FlaxEngine/FlaxEngine/pull/1590/commits/78b074e7da62acbd30ace3213c4dabea255f34a1

**Comment by mafiesto4** [comment]
#1579

**Comment by mafiesto4** [comment]
Fixed in #1590
