### ISSUE TITLE
maximized window gets out of screen bound

### ISSUE THREAD

**Issue by NoriteSC** [FlaxEngine/FlaxEngine#1592]
**Issue description:**

maximized window get out of screen bound when gets minimalized and restored on windows 10
**Steps to reproduce:**

**maximize the window**
u should see, something this
![image](https://github.com/FlaxEngine/FlaxEngine/assets/53096989/ec1d88df-1af5-465f-b146-3f6ac1c935ab)

**minimize window and restore it**
u should see, something this
![image](https://github.com/FlaxEngine/FlaxEngine/assets/53096989/eca140ba-dd7c-47fe-87b9-58fdc7563258)

**Minimal reproduction project:**

none

**Flax version:**

master

**what i think is wrong**
when window gets restored the bounds is not including the window frame

**Comment by Tryibion** [comment]
Putting this here. On my monitor the client size increases in size by exactly 16x16.

**Comment by mafiesto4** [comment]
Fixed in #1596
