### ISSUE TITLE
Flax crashes 100% all the time on: 'tools --> bake lightmaps' --> DirectX error in:  dx11/gpushaderdx11.cpp:152 

### ISSUE THREAD

**Issue by Lykdraft** [FlaxEngine/FlaxEngine#16]
Crashes 100% all the time as soon as 'bake lightmaps' gets clicked.

Windows 10, Nvidia GTX 680, Intel CPU.

![Screenshot 2020-12-19 at 15 32 38](https://user-images.githubusercontent.com/18437561/102703619-7bc24900-4271-11eb-92cd-ea4ac3cbc1dc.png)

**Comment by W2Wizard** [comment]
Is this issue still valid?

**Comment by mafiesto4** [comment]
You could try baking lightmaps using Debug build (from `<flax_installation>\Binaries\Editor\Win64\Debug\FlaxEditor.exe`) and see what log says.
Probably, not supported GPU as we bake lightmaps on GPU only.

**Comment by Lykdraft** [comment]
Sorry for the late response.

> Probably, not supported GPU as we bake lightmaps on GPU only.

Yeah, I figured that out as well. Windows was running on a VM. That's why. Was the same with Unigine (crashed on start, but same error) In the meantime I got a new PC system and a PC Laptop anyways. Problem is gone on both of em.
