### ISSUE TITLE
Is not possible change audio attenuation distance? (XAudio2)

### ISSUE THREAD

**Issue by RuanLucasGD** [FlaxEngine/FlaxEngine#1612]
**Issue description:**
I'm trying change audio volume by distance but don't work for large distances.

**Minimal reproduction project:**

[Debug 2023.10.04 - 21.00.05.48.webm](https://github.com/FlaxEngine/FlaxEngine/assets/79365912/d5e3f05d-dc6c-41a9-89b0-a599dde70822)

**Flax version:**
1.6 master

**Comment by RuanLucasGD** [comment]
Builded with XAudio2

**Comment by mafiesto4** [comment]
Fixed in 4df56cb50683fc7271baaaf1b6dbdddcb009fcd2.
