### ISSUE TITLE
DDGI overshadow or overlit problem

### ISSUE THREAD

**Issue by TheOmnisimush** [FlaxEngine/FlaxEngine#1614]
**Issue description:**
With DDGI enabled, in some position or angle (especially when an object is close to another) 
the light probe will go black or white

And this will make an overshadowed (black) color on the object
https://forum.flaxengine.com/uploads/default/original/2X/4/42e75c7bab219f8b580d899078a9209c833cca70.jpeg

Or, make an overlit color (as if there is a point light in the spot eventhough there is none)
https://forum.flaxengine.com/uploads/default/optimized/2X/f/f0f3e86d160797d6e84a00773cb5a67702508f7e_2_690x442.jpeg

I also posted the same issue in the forum: 
https://forum.flaxengine.com/t/ddgi-overshadow-or-overlit-problem/1320

**Flax version:**
1.6.6344

**Comment by mafiesto4** [comment]
Yeah for Flax 1.8 we have scheduled a few weeks of work time specifically for DDGI, here is a roadmap with some ideas: https://trello.com/c/O9r1hWPg/345-ddgi-improvements

In general, the goal would be to improve the quality (eg. those areas that don't have proper DDGI probe sampling) and improve performance.

**Comment by TheOmnisimush** [comment]
Thanks for the reply. I look forward to Flax 1.8 then.

**Comment by mafiesto4** [comment]
DDGI quality has been improved for Flax 1.9. Probes placement is more precise, many SDF tracing issues were fixed and overall GI quality is better. We will update Tech Demo 2022 to include new shading improvements that remove those blocky artifacts. DDGI won't solve high-quality per-pixel GI as it still uses world-space probes but I think we're reaching production-ready quality level.

Before:
![gi_before](https://github.com/FlaxEngine/FlaxEngine/assets/3464853/4207e4bc-9616-4bea-8d4e-72821b02e5e8)

After:
![gi_after](https://github.com/FlaxEngine/FlaxEngine/assets/3464853/352fd5a4-0539-45c7-bbe7-b19e2da3029d)
