### ISSUE TITLE
ErrorCS0117: 'Utilities' does not contain a definition for 'SortVersionDirectories'

### ISSUE THREAD

**Issue by TheOmnisimush** [FlaxEngine/FlaxEngine#1615]
**Issue description:**
Error when compile and build the Flax Project.
Maybe there are some files not properly added to commit.

**Flax version:**
Master branch, latest tested in 2023/10/15

**Comment by mafiesto4** [comment]
Build `Flax.Build` project (manually or via `GenerateProjectFiles` script). Recently we changed some API so it's good to update build tools once a while.
