### ISSUE TITLE
Create a localized string for a parameter to a script in the editor causes the properties area of the script to become filled with the localized string editor.

### ISSUE THREAD

**Issue by Menotdan** [FlaxEngine/FlaxEngine#1616]
**Issue description:**
When creating a localized string as a parameter to a script, the localized string editor will take up the whole script's field editor area.

**Steps to reproduce:**
Create a `LocalizedString` property for a script, give it editor properties (maybe not important I didnt test much), open in editor, press the plus icon next to the property.

**Flax version:**
Master Branch 94611c7 

https://github.com/FlaxEngine/FlaxEngine/assets/32620310/959932ae-d05b-4fe3-ad63-e7a62029ca3b

**Comment by mafiesto4** [comment]
Fixed in 74bcf7d9e598be82635086570555b41cd85b9988.
