### ISSUE TITLE
Duplication of Project causes Materials to partial losing reference

### ISSUE THREAD

**Issue by schmidt-florian** [FlaxEngine/FlaxEngine#1631]
**Issue Description:**

If you duplicate a project, the material reference gets partially lost.
If you delete all temporary folders e.g. Binaries/Cache/Logs after duplication, the reference is fully lost and gets replaced with the default material.
Clarification: "Duplicate ": Copy/Paste the Project Folder via Windows Explorer.

![image](https://github.com/FlaxEngine/FlaxEngine/assets/14238126/5ed6c7b0-e027-466b-8e67-c5f6f7f8ac99)

**Steps to reproduce:**

- Create a new project with the Basic Scene Template.
- Check everything is OK.
- Close the Editor.
- Duplicate the root Project folder.
- Open the new duplicated project. The material should be partially missing. Rendering should be without error. But inspector is blank and shows some assigned material, but does not know anything about it. You can even duplicate the object with the partially missing reference.
- If you close the project, delete the cache folder and reopen it. The material reference is fully lost.

**Flax version:**
master a698095

**Comment by mafiesto4** [comment]
Fixed in d7e9e2ed1679c527790a149120c6a7a33b993824.
