### ISSUE TITLE
View keeps panning when zooming in and out

### ISSUE THREAD

**Issue by Thev2Andy** [FlaxEngine/FlaxEngine#164]
Issue description.

Steps to reproduce:
1) Open a Texture2D, preferably IconAtlas.
2) Zoom in and out.
3) Notice the view panning.

Minimal reproduction project:
The bug occured on Material Features Tour, but any project should work.

Flax version:
Issue occured in Flax 1.0.6215

https://user-images.githubusercontent.com/69793166/105832269-69ee6700-5fd0-11eb-95ab-6d7c7b87958f.mp4

**Comment by stefnotch** [comment]
Relevant code (if you want to try taking a stab at fixing it)
https://github.com/FlaxEngine/FlaxEngine/blob/054aa18e3173ace5b51ef0cd174842dbb062de1a/Source/Editor/Viewport/Previews/TexturePreview.cs#L153-L170

**Comment by stefnotch** [comment]
Thanks for reporting this! 

Decided to try fixing it and have to admit, it took me longer than expected...
