### ISSUE TITLE
Importing more than one image file at a time is not possible on Linux/KDE

### ISSUE THREAD

**Issue by nothingTVatYT** [FlaxEngine/FlaxEngine#1646]
**Issue description:**
Using the import function in the context menu of the content window there is an open-file dialog that accepts multiple selections but Flax editor will only accept the first one instead of all selected. No error in the debug, the remaining files are ignored.
On top of that the file chooser always opens at the current working directory where the editor was started, i.e. you have to navigate to the folder you want to import from for every file.

**Flax version:**
1.6.6345

**Comment by mafiesto4** [comment]
Fixed in #1657
