### ISSUE TITLE
Material Bug with Plane

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#165]
There are two minor bugs with the material editor.

The first bug is that when you change the view to plane. The view is facing away from the plane making it seem like your material has just randomly disappeared. You can see this in the video I attached.

The second issue is that there seems to be a weird lighting artifact on the plane. This is probably caused by the way the light hits the plane, but it is very distracting to the user. This can also be seen in the attached video.

https://drive.google.com/file/d/1SspeN-28uQDZern4w3L0QLNTvfTE6yUh/view?usp=sharing

**Comment by stefnotch** [comment]
The second one is apparently because the default plane has odd normal vectors

![image](https://user-images.githubusercontent.com/10220080/106055287-77e5da00-60ed-11eb-9a0e-64a5aa3b5b86.png)

**Comment by mafiesto4** [comment]
Fixed by a226ff87623533989cab90d60efd91f66ca15408 and 50f6a01f83a36824d6bc011f1d186d6bda08621c
