### ISSUE TITLE
Rider ignors files of plugin projects

### ISSUE THREAD

**Issue by schmidt-florian** [FlaxEngine/FlaxEngine#1651]
**Issue description:**
Rider by default ignores files of plugin projects in his solution-wide analysis.
I do not know if there is another reason. But as long the Project are generated to bo as "not build" for rider, the errors are ignored.
If I set it to build, the errors are not ignored. The issue is that this is overwritten by Flax on Regenerate Project files. Even it does now happen not always, it is annoying to set it every time to build. Especially if you have 5 Modules in 2 Plugin Projects.

**Steps to reproduce:**

1. Open attached project (or create a project with a plugin project and produce a script error in the plugin project)
2. Generate Project files.
3. Open Project in Rider, after rider has finished his analysis, there will be no errors. Image. 1
4. Open Solution Properties and check the build option on the project "Test" Image. 2/3
5. Rider will now show the error. Image. 4
6. On regenerate Project files, it will be set to "not build" and the error will be ignored again.

Image. 1
![image](https://github.com/FlaxEngine/FlaxEngine/assets/14238126/77c3bbe8-81f7-46ef-873a-18d9b19a9778g|width=400px)
Image. 2
![image](https://github.com/FlaxEngine/FlaxEngine/assets/14238126/883f9ed6-c61e-4867-807b-cf455670f0a2|width=400px)
Image. 3
![image](https://github.com/FlaxEngine/FlaxEngine/assets/14238126/5b774492-0dab-4c99-8287-24bbad4f8a20|width=400px)
Image. 4
![image](https://github.com/FlaxEngine/FlaxEngine/assets/14238126/2cf72cc2-2145-4448-8db1-ee86747c2ef4|width=400px)

**Minimal reproduction project:**
[TestPluginError.zip](https://github.com/FlaxEngine/FlaxEngine/files/12841159/TestPluginError.zip)

**Flax version:**
master 5283337

**Comment by mafiesto4** [comment]
Fixed in #1673
