### ISSUE TITLE
FBX-Model has some wrong vertices

### ISSUE THREAD

**Issue by schmidt-florian** [FlaxEngine/FlaxEngine#1660]
**Issue description:**
The model is not imported correctly. There are some Vertices wrong. Screw holes are half or fully covered, as well as some parts of the inner circle around the knob.
Also, the OBJ Model is invisible.

I don't need to mention that it's obviously not about the textures.

Original: 
https://www.cgtrader.com/free-3d-models/industrial/other/emergency-button-657362a5-b65e-44ef-a2a1-bd1f20a850ae
![image](https://img-new.cgtrader.com/items/3282607/930ef423b2/emergency-button-3d-model-obj-fbx-blend.jpg)

Flax:
![image](https://github.com/FlaxEngine/FlaxEngine/assets/14238126/01159aa2-16be-4a42-a9fc-3744b893ae55)

Unity:
![image](https://github.com/FlaxEngine/FlaxEngine/assets/14238126/d213406f-3591-4273-a51b-b134edd3c99a)

**Steps to reproduce:**
1. Import model
2. Inspect Model.

**Minimal reproduction project:**
No project, it is the model itself (blend file is also available at the cgtrader link above):
[Button.zip](https://github.com/FlaxEngine/FlaxEngine/files/12851232/Button.zip)

**Flax version:**
master 00100e1

**Comment by RuanLucasGD** [comment]
try disable mesh optimization on import settings

**Comment by schmidt-florian** [comment]
I had already tried it with another mesh and it did not help. Unfortunately, it has no effect on this mesh either.

![image](https://github.com/FlaxEngine/FlaxEngine/assets/14238126/dacf7961-67b0-4c2f-89cd-214fbe9d1354)

**Comment by Menotdan** [comment]
This model appears to have many n-gons, which game engines don't like, however, manually triangulating the mesh does not fix the issue. maybe whatever flax does to triangulate it breaks something.

**Comment by Menotdan** [comment]
As for the OBJ model, it is not invisible, just extremely tiny.
![image](https://github.com/FlaxEngine/FlaxEngine/assets/32620310/9ea1d4ba-736c-4a3c-8821-841c7d067c8a)
![image](https://github.com/FlaxEngine/FlaxEngine/assets/32620310/80d6b70c-0c5e-418e-85f8-cfe3f94e3a70)
(remember flax measurements are in cm, so that's 0.08 cm)

![image](https://github.com/FlaxEngine/FlaxEngine/assets/32620310/68f57b09-7a7a-4fd2-8b97-b9f5d1a44d2c)
Seems like flax (for OBJ files) assumes CM measurement when really its M measurement.

**Comment by mafiesto4** [comment]
Using `Scale` on model import settings allows to make mesh bigger if it was exported for a different application.

For incorrect triangle there I think we gonna need to update to the latest OpenFBX version with those changes: https://github.com/nem0/OpenFBX/commit/15e70cc00cafbcc0877d674c91b464142c945d30 or implement own triangulation (see https://github.com/nem0/OpenFBX/issues/56).

**Comment by mafiesto4** [comment]
Fixed in #2672
