### ISSUE TITLE
The editor font does not contain Chinese or Japanese

### ISSUE THREAD

**Issue by xiaoye97** [FlaxEngine/FlaxEngine#1661]
**Issue description:**

![flax font](https://github.com/FlaxEngine/FlaxEngine/assets/34893504/f49cf6a6-def2-43df-a894-eca9f6d3cd99)
The font of the editor does not support languages such as Chinese and Japanese. 
Suggest adding fallback font function.
This is important for the localization of the game

**Flax version:**

master

**Comment by yunnibbd** [comment]
Strongly requires the editor to support Chinese

**Comment by HydrogenC** [comment]
I'm working on a PR to enable font fallback and multi-font text rendering, and I've already made a working prototype.  
![20231127232740](https://github.com/FlaxEngine/FlaxEngine/assets/33123710/73314127-ad71-4531-9aba-440a138f8830)

However, I would have to replace all the Font in the editor to FontCollection, which is a large workload. So it will still take some time for me to finish the whole refractoring.
