### ISSUE TITLE
Editor crash when saving a prefab sometimes

### ISSUE THREAD

**Issue by lifeformed** [FlaxEngine/FlaxEngine#1663]
Sometimes when I save a prefab it crashes the editor.  I thought it was from this issue, but that has been resolved, and I'm using a very recent version (481a3cfb).
https://github.com/FlaxEngine/FlaxEngine/issues/1432#issuecomment-1750586073

If I debug the editor it throws a SystemAccessViolationException here, in LibraryImports.g.cs:31209.
![image](https://github.com/FlaxEngine/FlaxEngine/assets/1567199/767e1702-a90a-4ca1-9dbf-8bead808b008)

I haven't found reproducible steps yet but I'm trying.  Maybe my prefab is just too old of a version, and has some bad data in it from the previous bug?  Is there a way to "refresh" a prefab to clean up anything in it?

**Comment by mafiesto4** [comment]
ANy log from that run? Here we can see exception inside C# code that calls C++ backend so it's somewhere internal the engine. Or maybe we fixed it for 1.7.2 while bugfixing similar issue.
