### ISSUE TITLE
Basic usage of INetworkSerializable crashes

### ISSUE THREAD

**Issue by lifeformed** [FlaxEngine/FlaxEngine#1664]
I'm getting a lot of problems using INetworkSerializable.  It crashes when I had a FixedUpdate function in my script, and once it tried to deserialize my script as the wrong type.

I couldn't find any way to use it correctly.  I found this method of reproducing a crash:
- Use the Arizona Framework Sample
- Create an empty actor
- Put this script on it:
```
public class test : Script, INetworkSerializable
{
    public override void OnEnable()
    {
        NetworkReplicator.AddObject(this);
    }

    public override void OnDisable()
    {
        NetworkReplicator.RemoveObject(this);
    }

    public void Serialize(NetworkStream stream) { }
    public void Deserialize(NetworkStream stream) { }
}
```

- Cook and run.
- Run in the editor and host.
- On the cooked version, connect.
- The editor one will crash.  I noticed it crashes immediately if you give the empty actor static flags of None, but only crashes on disconnect if you make it Fully Static (but then the cooked version crashes immediately).

I'm using master branch but I think it's broken in 1.6 too.

**Comment by mafiesto4** [comment]
Fixed in fa96707c578e681dd90517d98d063e3a32d60388.
