### ISSUE TITLE
Script will lose all data when one property throws an exception

### ISSUE THREAD

**Issue by schmidt-florian** [FlaxEngine/FlaxEngine#1675]
**Issue description:**
A script will lose all its serialized data if one property of it throws an exception and you press play.
If you notice before pressing play and want to fix the issue, the recompile will wipe the data.

The worst thing: If you are happily coding, and Flax does a recompile in the background... (or you tab accidentally to Flax) your data is gone.
(Until you recover it from git, ofcourse) But then you have a mostly painful merging process of the scene file :D

**Steps to reproduce:**
1. Create a script
2. Add this code
```csharp
public float GoodValue;
// public float BadValue
// {
//     get => throw new System.NotImplementedException();
//     set => throw new System.NotImplementedException();
// }
```
3. Add the script to an actor, and set the good value to something.
4. Go back and uncomment the block of BadValue.
5. Go to Flax, and notice the serialization warning, now, either press play or go back and comment out the error
6. GoodValue is wiped.

**Flax version:**
master fa96707

**Comment by mafiesto4** [comment]
Side note: In C# and Visual Scripts that problem won't occur.

**Comment by schmidt-florian** [comment]
One solution would be to catch the error not for each property but for the entire script. The important thing would be not to throw away the last serialized data.

If the serialization fails, do not delete/overwrite the last working data but keep it until no more errors occur, and then write the data into the script as normal. Because the user can then see in the log that something is wrong, can fix the error and it would be nice if the script was then there as it was before the error and not just completely reset.
