### ISSUE TITLE
AssertionException in ContentItem when importing an FBX model

### ISSUE THREAD

**Issue by nothingTVatYT** [FlaxEngine/FlaxEngine#1679]
**Issue description:**
When importing an FBX file an AssertionException is thrown in the GUI (ContentItem.AddReference see logs) and the editor crashes.
[Log.txt](https://github.com/FlaxEngine/FlaxEngine/files/12875690/Log.txt)

**Steps to reproduce:**
It's an FBX created by Blender and I tried to import it into Flax running on Linux. As the exception is thrown in the UI I assume the actual importing was almost complete but updating the content window failed. This might be independent on the model.
Actually when I restart the editor and load the project, the model is imported and available.

**Flax version:**
1.7.6401 (master branch)

**Comment by mafiesto4** [comment]
Fixed in db52be59363cc4c3c512c3a301a83e340a61bd02

**Comment by mafiesto4** [comment]
Actually fixed in 9a636468e0d6378be117317dedd913e6dbb11727.
