### ISSUE TITLE
Cooked Game with CrowdSystem Not working

### ISSUE THREAD

**Issue by alcoranpaul** [FlaxEngine/FlaxEngine#1680]
**Issue description:**

Taken from [official example](https://docs.flaxengine.com/manual/navigation/nav-crowd.html), in a **cooked build fails to initialize/add an agent** but **runs perfectly fine in development** in 2 different version on initializing the CrowdSystem.

### Same copy what is on the official example
- When cooked build is launch, it will crash on start up
- By removing `PluginManager.GetPlugin<CrowdSystem>().AddAgent(this);` on OnEnable function of agent does the game not crash
- _Log output_ does not throw any Expection saying that Crowd was failed to initialize but the Debug.Log still ran successfully. See 
[OfficialNavCrowd.txt](https://github.com/FlaxEngine/FlaxEngine/files/12876116/OfficialNavCrowd.txt)

 ```
internal void AddAgent(NavAgent agent)
    {

        if (_crowd == null)
        {
            // Lazy init
            _crowd = new NavCrowd();
            if (_crowd.Init(agent.Properties, MaxAgents))
                throw new Exception("Failed to initialize crowd");
            if (_system == null)
                Engine.UpdateGraph.AddSystem(_system = new CrowdTaskGraphSystem { System = this });
            Debug.Log("CrowdSystem Initialized");
        }

        // Add agent to the crowd
        agent.ID = _crowd.AddAgent(agent.Actor.Position, agent.Properties);
        if (agent.ID == -1)
            throw new Exception("Failed to add agent to the crowd");
        agent.Crowd = _crowd;
    }
```
https://github.com/FlaxEngine/FlaxEngine/assets/67833935/8012e885-ffd1-427c-9639-4e8523586d12

### Moved Lazy init block into Initialized and hardcoded the Agent Properties
- When cooked build is launch successfully, but Agent will not move since initialization was failed
- _Log output_ shows that an Error exception "Failed to initialize crowd" was thrown. See [ModifiedNavCrowd.txt](https://github.com/FlaxEngine/FlaxEngine/files/12876117/Log_2023_10_11_20_27_25.txt)

```
public NavAgentProperties Properties = new NavAgentProperties
    {
Radius = 34.0f,
        Height = 144.0f,
        StepHeight = 35.0f,
        MaxSlopeAngle = 60.0f,
        MaxSpeed = 500.0f,
        CrowdSeparationWeight = 2.0f,
    };
public override void Initialize()
  {
      //base.Initialize();

      if (_crowd == null)
      {
          // Lazy init
          _crowd = new NavCrowd();
          if (_crowd.Init(Properties, MaxAgents))
              throw new Exception("Failed to initialize crowd");
          if (_system == null)
              Engine.UpdateGraph.AddSystem(_system = new CrowdTaskGraphSystem { System = this });
          Debug.Log("CrowdSystem Initialized");
      }
  }
internal void AddAgent(NavAgent agent)
  {

      // if (_crowd == null)
      // {
      //     // Lazy init
      //     _crowd = new NavCrowd();
      //     if (_crowd.Init(Properties, MaxAgents))
      //         throw new Exception("Failed to initialize crowd");
      //     if (_system == null)
      //         Engine.UpdateGraph.AddSystem(_system = new CrowdTaskGraphSystem { System = this });
      //     Debug.Log("CrowdSystem Initialized");
      // }

      // Add agent to the crowd
      agent.ID = _crowd.AddAgent(agent.Actor.Position, agent.Properties);
      if (agent.ID == -1)
          throw new Exception("Failed to add agent to the crowd");
      agent.Crowd = _crowd;
  }
```

https://github.com/FlaxEngine/FlaxEngine/assets/67833935/745a921c-13dc-443c-a27f-6fde2f5d9117

**Steps to reproduce and Setup**
- Added NavMeshBounds, UICanvas + Button UI, Character Controller + Capsule
- Button UI for Setting a boolean for NavAgent to move 

**Flax version:**
Master and 1.6

[NavTest - Master.zip](https://github.com/FlaxEngine/FlaxEngine/files/12876177/NavTest.-.Master.zip)

**Comment by mafiesto4** [comment]
1) There was a bug because navmesh could not be yet loaded (we have async asset streaming) but I fixed it in a5f00ed624af7ab22f900d6b316549fed2f7c8bd so crowd init will wait for data to be there.

2) NavCrowd init fails because there is no navmesh loaded when plugin is initialized (navmesh exists on a scene but plugins are loaded before any level is opened).

In editor the logic is a little different because we already have scenes in a game so navmesh can be already in memory thus it was working better in Play Mode.

Also, there was  abug where plugins were disposed before scenes when exiting engine in cooked game, fixed in e4b89e1badbcdd4bfa69b5d72650ba10f2f425b8.

Thanks for reporting those problems.
