### ISSUE TITLE
Content Finder crashes when the results contain a particle emitter.

### ISSUE THREAD

**Issue by MineBill** [FlaxEngine/FlaxEngine#1683]
**Issue description:**
The content finder will crash when searching and the default particle emitter comes up. Initially, i thought it was random but searching for "particle" will crash the editor. Because of the stacktrace and log i attached below, i suspect it might be caused by the generation of the thumbnail for some of the default particle emitters the editor contains.
![image](https://github.com/FlaxEngine/FlaxEngine/assets/30367251/4bf9fc0d-2ac2-4520-a706-ec291b9f16bb)

Here is the stacktrace i get when debugging the editor:
![image](https://github.com/FlaxEngine/FlaxEngine/assets/30367251/948d28d1-5c20-40a9-9f98-0432b4989f0b)

[Log.txt](https://github.com/FlaxEngine/FlaxEngine/files/12884415/Log.txt)

**Flax version:**
master

**Comment by mafiesto4** [comment]
Fixed in 84d615935e5bf803239bf47917d61eee490d5ea4.
