### ISSUE TITLE
Cannot create a mesh collider on a virtual model

### ISSUE THREAD

**Issue by nothingTVatYT** [FlaxEngine/FlaxEngine#1687]
**Issue description:**
The documentation at https://docs.flaxengine.com/manual/physics/colliders/collision-data.html says how to create a mesh collider from a virtual model but when I try that I get:
[ 00:32:08.496 ]: [Error] Cannot access CPU data of virtual models. Use GPU data download
[ 00:32:08.496 ]: [Error] Failed to download mesh 0 data from model FlaxEngine.Model, 08dbcaaf55957d7f351ea57e1698a879,  LOD0

**Steps to reproduce:**
Create a virtual asset as Model according to the documentation and add a triangle mesh collider to it like:
```
var model = Content.CreateVirtualAsset<Model>();
            model.SetupLODs(new[] { 1 });
            mesh = model.LODs[0].Meshes[0];
            var childModel = childByMaterial.GetOrAddChild<StaticModel>();
            childModel.Model = model;
            childModel.LocalScale = Vector3.One;
            if (material != null)
                childModel.SetMaterial(0, material.CreateVirtualInstance());
            var collisionData = Content.CreateVirtualAsset<CollisionData>();
            collisionData.CookCollision(CollisionDataType.TriangleMesh, model);
            childModel.GetOrAddChild<MeshCollider>().CollisionData = collisionData;
```

**Flax version:**
1.7.6401 (git master branch) on Linux KDE/X11 with Vulkan (instance version 1.3.264)

[Log_2023_10_12_22_37_06.txt](https://github.com/FlaxEngine/FlaxEngine/files/12885939/Log_2023_10_12_22_37_06.txt)

**Comment by mafiesto4** [comment]
It's not supported because virtual models data (vertices) are stored on GPU-only. In theory we could cache the data on CPU too but cooking is not a fast process so running it in async is a good idea.

You can do sth like this:
```cs
public class CollisionFromCode : Script
{
    public Material material;

    /// <inheritdoc />
    public override void OnStart()
    {
        var model = Content.CreateVirtualAsset<Model>();
        model.SetupLODs(new[] { 1 });
        var mesh = model.LODs[0].Meshes[0];
        var childModel = Actor.GetOrAddChild<StaticModel>();
        childModel.Model = model;
        childModel.LocalScale = Vector3.One;
        if (material != null)
            childModel.SetMaterial(0, material.CreateVirtualInstance());
        System.Threading.ThreadPool.QueueUserWorkItem(_ => CookCollision(model, childModel));
    }

    private void CookCollision(Model model, Actor childModel)
    {
        // Cook collision in async
        var collisionData = Content.CreateVirtualAsset<CollisionData>();
        collisionData.CookCollision(CollisionDataType.TriangleMesh, model);

        // Add it to the scene on main thread
        Scripting.InvokeOnUpdate(() => childModel.GetOrAddChild<MeshCollider>().CollisionData = collisionData);
    }
}
```

I added some tweaks to make it more usable in 1a5606a45cd6cd4f21b5afe3a75432a3e2c302ac. Also, if you build virtual geometry and you need to have collision you can pass the vertices+indices directly to `CookCollision` method instead of model asset.
