### ISSUE TITLE
Importing multiple texturer folders crashes the engine

### ISSUE THREAD

**Issue by LordCocoNut** [FlaxEngine/FlaxEngine#1691]
## What happend
I downloaded multiple PBR mats from cc0textures. Extracted them to folders and tried to drag and drop like 4 folders (16 or so textures) into the asset browser. Engine crashed.

## How to replicate
Drag and drop few folders with 2k textures into the asset browser.

Setup > PopOs 22.04 LTS 
Amd RX 6800XT
Flax 1.6 Build v. 6344

Error message attached > [assets_import_crash.txt](https://github.com/FlaxEngine/FlaxEngine/files/12886679/assets_import_crash.txt)

**Comment by Menotdan** [comment]
I also get funky behaviour importing folders of textures on the latest master branch.

**Comment by mafiesto4** [comment]
Most likely fixed in fdd6b171bbdbde729e936c45d025f70a66d75478 and db52be59363cc4c3c512c3a301a83e340a61bd02. Reopen issue if it will still occur on the next master builds.

**Comment by mafiesto4** [comment]
Actually fixed in 9a636468e0d6378be117317dedd913e6dbb11727.
