### ISSUE TITLE
GenerateProjectFiles returns an error

### ISSUE THREAD

**Issue by StRaToX123** [FlaxEngine/FlaxEngine#17]
Running the GenerateProjectFiles.bat file returns the trace shown on the image 
I have all the prerequisites installed. I'm running VS 2019
![Screenshot_1](https://user-images.githubusercontent.com/26925590/102703709-b2e52a00-4272-11eb-893f-8def65042a50.jpg)

**Comment by nocxtious** [comment]
Are you sure you have the specific build tools component installed?  I ran into this same problem because it wans't, also using 2019 community: 
![image](https://user-images.githubusercontent.com/72276215/102708465-8fb17f00-4260-11eb-810e-991140f22790.png)

**Comment by StRaToX123** [comment]
That fixed it, everything works fine now
