### ISSUE TITLE
Prerender doesnt work(stays at warmup) + long wait after clicking on debug log afterwards

### ISSUE THREAD

**Issue by honzapatCZ** [FlaxEngine/FlaxEngine#170]
**Issue description:**
Tried to prerender, but it stays at warming up, clicking on Debug Log makes the editor unresponsible.

**Minimal reproduction project:**
Make some scene anim

**Flax version:**
1.0

https://youtu.be/ezf9MudVYXg

**Comment by mafiesto4** [comment]
Could you post that scene animation asset?

**Comment by honzapatCZ** [comment]
[Cutscene.zip](https://github.com/FlaxEngine/FlaxEngine/files/5880810/Cutscene.zip)
