### ISSUE TITLE
Height Layer Blend node in material graph fails to generate correct code, and effect does not appear correctly.

### ISSUE THREAD

**Issue by Menotdan** [FlaxEngine/FlaxEngine#1705]
**Issue description:**
Flax fails to generate proper shader code for the "Height Layer Blend" node.

**Steps to reproduce:**
Create a height layer blend node, pick two materials, set them for top and bottom layer. Connect the output layer to the material output. You will get a shader compilation error in the output. A workaround is to multiply the alpha node by one, and this will at least compile. 

Reading the shader code, I find these lines and snippets like it, where 0.727 is the alpha value (notice where it is assigning to a constant):
```hlsl
float local21 = 1.00000000 * (1.0 - 0.72700000);
float local22 = 0.50000000 * 0.72700000;
float local23 = max(local21, local22) - 0.05;
float local24 = max(local22 - local23, 0.0001);
0.72700000 = local24 / (max(local21 - local23, 0) + local24);
local20.PositionOffset = lerp(local18.PositionOffset, local19.PositionOffset, 0.72700000);
local20.TessellationMultiplier = lerp(local18.TessellationMultiplier, local19.TessellationMultiplier, 0.72700000);
```

However, I think it is still generating something wrong, because after playing with the settings for a while, it seems quite strange in behaviour. Very thin tolerances for height, with no visual change other than opacity, opacity not really doing its thing properly. Maybe this is unrelated and I should post a project with my issue, but I figured I'd add it here.

**Flax version:**
Master commit [1a5606a](https://github.com/FlaxEngine/FlaxEngine/commit/1a5606a45cd6cd4f21b5afe3a75432a3e2c302ac)

**Comment by mafiesto4** [comment]
Fixed in 2f3929efe0d2952c420b65a4bc52d59134b23677. (codegen error)
