### ISSUE TITLE
Editor Freezes for couple of minutes if importing a bunch of script files.

### ISSUE THREAD

**Issue by schmidt-florian** [FlaxEngine/FlaxEngine#1706]
**Issue description:**
I imported roughly 20 script files at once. I dragged the files in the Windows Explorer and tabbed to Flax.
Flax freezes for at least 2-3 minutes. It will become responsive again if you wait long enough.
Or.. just kill flax and start it, it will start without problems or freezing with the new script files.

**Flax version:**
master

**Comment by GoaLitiuM** [comment]
Do you have log files from this session? Did you drag the files to the content area in Flax or in Explorer under the Source folder?

**Comment by schmidt-florian** [comment]
For this log file, I imported 210 scripts via Windows Explorer. Flax freezes for 5 minutes.

[Log_2023_10_14_18_10_12.txt](https://github.com/FlaxEngine/FlaxEngine/files/12906699/Log_2023_10_14_18_10_12.txt)

**Comment by GoaLitiuM** [comment]
I only get two Flax.Build calls when I drag 14 files in a source folder in content browser, one for recompiling the scripts and one for generating the project files. Can you take a short clip or more descriptive steps how to reproduce this?

**Comment by schmidt-florian** [comment]
Reproduce:
- Drag some greater amount of scripts in the source folder of flax via windows explorer
- Switch to flax and wait...


Sec 0-2 responsive flax
Sec 2-16 copy 211 source files
Sec 20- flax is now unresponsive, probably 5 minutes.

https://github.com/FlaxEngine/FlaxEngine/assets/14238126/a5a86802-da82-46e7-bca3-277ff1ac5a0a

As mentioned before, if you would do that without flax running, it would be a normal startup without much delay.
