### ISSUE TITLE
Flax Popup flashes every 10 seconds if minimized.

### ISSUE THREAD

**Issue by schmidt-florian** [FlaxEngine/FlaxEngine#1707]
**Issue description:**
If you let a popup open, minimize flax and do something else, the popup will flash every 10 seconds.
It only happens if you minimize flax. If it stays open and you just overlay another program, nothing happens.

Second 7 and 17.

https://github.com/FlaxEngine/FlaxEngine/assets/14238126/2db619ad-c4f9-488d-8cef-cfc16d1d80c5

**Steps to reproduce:**

1. Open Flax, open any popup (gamesettings)
2. Minimize the FlaxEditor (not popup)
3. Wait for it

**Flax version:**
master (windows)

**Comment by mafiesto4** [comment]
This must be a recent regression in Window window impl.
