### ISSUE TITLE
The engine doesn't see the .net on Linux

### ISSUE THREAD

**Issue by nnbveh** [FlaxEngine/FlaxEngine#1717]
**Issue description:**
I've downloaded the latest stable linux build and tried to run the editor but it tells me that .net is needed. I've installed the .net7 and can issue the dotnet command in terminal, but the editor still doesn't see it
**Steps to reproduce:**
install .net according to the instructions, run the flaxengine editor

**Minimal reproduction project:**

**Flax version:**

**Comment by mafiesto4** [comment]
We gonna need some logs: from project's subfolder `Logs` or run editor with cmd line arg `-std` to capture engine output.

**Comment by MineBill** [comment]
What distro are you using? Some distros change the RID of the runtime and that can cause issues.

**Comment by nnbveh** [comment]
I'm on Steam Deck so it's Steam Os.

Actually starting the editor from the terminal seem to solve the issue, it
started and could open the default project!
Gives me the following errors though:

AL lib: (EE) GetLoadedHrtf: Invalid header in
/usr/share/openal/hrtf/Default HRTF.mhr: "MinPHR03"
AL lib: (EE) GetLoadedHrtf: Failed to load /usr/share/openal/hrtf/Default
HRTF.mhr
AL lib: (EE) GetLoadedHrtf: Invalid header in
/usr/share/openal/hrtf/Default HRTF.mhr: "MinPHR03"
AL lib: (EE) GetLoadedHrtf: Failed to load /usr/share/openal/hrtf/Default
HRTF.mhr

Steam Os is some sort of protected distro, sorry, totally new t Linux,
maybe all the problems are because of that...

**Comment by MineBill** [comment]
That is something different, it has to do with audio. So, is everything else working now?

**Comment by nnbveh** [comment]
Yes, but only if I run the editor from the command line. Thanks!

**Comment by MineBill** [comment]
Hmm, since there isn't a launcher for Linux, how else did you start it?

**Comment by nnbveh** [comment]
Double-clicked on the editor file, just like I'd do on windows...most the
time it works, haha

**Comment by MineBill** [comment]
Shouldn't make any difference, anyway if it works ok now, you can close the issue.

**Comment by nnbveh** [comment]
It does somehow, that's why I've raised the issue but as long as I'm able
to start it some way it's fine. Thanks!
