### ISSUE TITLE
Selecting a foliage type hangs the editor

### ISSUE THREAD

**Issue by nothingTVatYT** [FlaxEngine/FlaxEngine#1724]
**Issue description:**
When I select the only foliage type (tree2 in this example) the editor on Linux hangs with no further entries in the log file.

**Steps to reproduce:**
Open the linked project and select the foliage type tree2.

**Minimal reproduction project:**
https://drive.google.com/drive/folders/1o3Ed2q153jbfRtvBWZaWlZ71eLjJXfZJ?usp=sharing

**Flax version:**
1.7.6401 (master branch)

**Comment by mafiesto4** [comment]
Fixed in 2d0eabc8be5b6fbdf6411a0153ef2690d29aa926.
