### ISSUE TITLE
Collider: Contact Offset Improvement

### ISSUE THREAD

**Issue by madsfs** [FlaxEngine/FlaxEngine#1728]
The current implementation of the Colliders have two issues:
- Their default Contact Offset value is 10 for some reason meaning that when you first start using Colliders their `CollisionEnter` event will be wildly inaccurate until you adjust the value.
- There is no visual indicator for what the Offset actually means. The current collider shows a Green wireframe of how big the Collider is in relation to the object it's attached to. It would be good to have a Blue (or other colored) wireframe that shows how the Offset is going to affect that because otherwise it's just an arcane value that is really hard to adjust and might as well be 0 at all times.

**Comment by Menotdan** [comment]
> Some PhysX docs as a reference to this topic:
> 
> ![image](https://user-images.githubusercontent.com/3464853/275744873-5ad82a30-b5d5-4165-b2cf-4b61dd1df22e.png)
> 
> ![image](https://user-images.githubusercontent.com/3464853/275745183-c275b439-5bb1-41b7-ab66-246ac08e0006.png)

What does this mean exactly? What's our `PxToleranceScale::length` in flax?

**Comment by mafiesto4** [comment]
`PxToleranceScale::length` is `100` units which is 1m (https://github.com/FlaxEngine/FlaxEngine/blob/master/Source/Engine/Physics/PhysX/PhysicsBackendPhysX.cpp#L1114)

**Comment by Menotdan** [comment]
> `PxToleranceScale::length` is `100` units which is 1m (https://github.com/FlaxEngine/FlaxEngine/blob/master/Source/Engine/Physics/PhysX/PhysicsBackendPhysX.cpp#L1114) 

So why is the default contact offset not 2?

**Comment by mafiesto4** [comment]
I don't remember exactly why. Probably to get more stable contact events for games scripting. Maybe we could evaluate it (eg. in Flax Samples) and try to reduce it a little (probably for better perf). I wonder if it would improve Flax Per Test project stability: https://github.com/Tryibion/FlaxPerformanceTest
