### ISSUE TITLE
Keep material slots on reimport not working as expected.

### ISSUE THREAD

**Issue by Menotdan** [FlaxEngine/FlaxEngine#1732]
**Issue description:**
When I reimport a model that has "Keep Material Slots On Reimport" enabled, and if I am using materials that were imported by "Import Materials", it will reimport the materials from the model, thus destroying any properties I changed.

**Steps to reproduce:**
(A case similar to what I was doing)
1. Create a material with a color parameter and plug it into the Base Color output of the material.
2. Import a model, with "Import Materials" enabled and "Import Materials as Instances" enabled, and the material instance set to the material you created.
3. Change the color of the created material instance using the parameter.
4. Reimport the model with "Keep Material Slots On Reimport" enabled.
5. Your color property will be reset.

**Flax version:**
Master branch 582cf9419

**Comment by mafiesto4** [comment]
That's because the material was reimported from the source file. Do you think we should skip importing material if it already exists?

**Comment by Menotdan** [comment]
> That's because the material was reimported from the source file. Do you think we should skip importing material if it already exists?

Yes, that's what it implies to me. It should keep the materials' properties if it reimports and the file exists. One small problem exists if the user changes the properties of the model's material and are using the actual imported material, maybe if there is way to check if the material was changed after import and only then skip the importing, but I think that would be much more complicated, and would conflict with #1659. I think a good current solution is just what you said, but maybe in the future you can add an option to each individual material slot to always reimport it even if "Keep material slots" is enabled.
