### ISSUE TITLE
Animation Interruption for Current State AND Next State

### ISSUE THREAD

**Issue by TheOmnisimush** [FlaxEngine/FlaxEngine#1735]
Flax Animation interruption only checks for current state transition.
This is an extension from this Post in the forum
https://forum.flaxengine.com/t/animation-transition-interrupt-suggestions/1050

**The Problem:**

Flax fails to play interruption in this case :
**Move -> Break -> Idle -> Move**

If currently "Break->Idle" transition is playing, and User inputs "Play Move!" 
Flax fails to interrupt the transition because it only checks current state (Break & Idle) but not "Move"
As you can see in the video below, the animation needs to wait until "Break->Idle" transition finishes, in order to go to "Move" state.
Even if the script already called the AnimGraphParameter to play "Move" animation
-> This results in Character moving but the animation is locked in "Idle" state for a while, making it look like the Character is "Sliding on ice"

https://www.veed.io/view/21f1039f-e886-43e0-aacd-373a32e2f833?panel=share

- The same StateMachine in Unity

As you can see in the video below, Unity correctly plays interruption for the next state
So even when "Break->Idle" transition is playing, it will blend with the "Move" state
if interrupted by User input (Script)
https://www.veed.io/view/4618bebb-5b68-48c3-8a4e-86ded449a559?panel=share

**Expected Result**
Animation can be interrupted correctly by next state, making a seamless blending.

**Flax Version:**
1.6.6344

**Comment by mafiesto4** [comment]
Added in 8c2a156e1f124479d0aaed5e26ab22e58577b1e0. Now transition can be interrupted by other transition in the source or destination state. The interruption can be instant (if set in options) or with smooth blend (by default) from the pose that model was when original transition was interrupted.
