### ISSUE TITLE
Editor: Hierarchy Ordering Overhaul

### ISSUE THREAD

**Issue by madsfs** [FlaxEngine/FlaxEngine#1741]
Whatever code is responsible for reordering hierarchies in the Editor needs a do-over. It is incredibly tedious to reorder objects without accidentally making them children of random objects and the order of objects is reversed when you move multiple of them at a time.

See the attached Gifs for examples.

What I propose is that perhaps Key modifiers could be used to help the process. So if you hold down, say Shift while moving an object in the hierarchy then it can only be reordered, it can't be parented. But I'm sure the UI might just be in need of a better implementation as other engines don't seem to have this issue.

https://github.com/FlaxEngine/FlaxEngine/assets/113017777/b361c5e2-3822-4a9f-a28e-28b994ff13f1

https://github.com/FlaxEngine/FlaxEngine/assets/113017777/f446dd09-84b5-4cd0-a55d-e25b1f24d458

**Comment by madsfs** [comment]
Order not being kept seems to be an issue in general. I copied a structure and when I paste it, the order gets very messed up. (see the attached pictures)
![image](https://github.com/FlaxEngine/FlaxEngine/assets/113017777/01f4cc8f-3a9e-49df-ac84-69da7acea668)
![image](https://github.com/FlaxEngine/FlaxEngine/assets/113017777/89340a99-55fb-4c89-b81c-c3fb23ece044)

**Comment by mafiesto4** [comment]
Fixed in c561d684eba1e0cea290b5d07a2b2603132bce72 and ed3ac0af8ea7f2ab4b740f34313a5f38ab4898a8.
Improved visuals of drag&drop in 8de2249ed82d6072641226fb5af7b7027d5817f4.
