### ISSUE TITLE
Editor freezes when opening attached scene

### ISSUE THREAD

**Issue by schmidt-florian** [FlaxEngine/FlaxEngine#1743]
**Issue description:**
I tried to find a bug and remove one script that was used in the scene, while recompiling, I tried to attach the debugger. I don't know if this is relevant. The Editor froze @ 20% process bar from compiling. After restarting I am unable to open the scene. If i do the Editor just freezes. The log is pretty much clean, besides the warning of the missing script.

[Log_2023_10_19_03_20_37.txt](https://github.com/FlaxEngine/FlaxEngine/files/13035517/Log_2023_10_19_03_20_37.txt)

**Steps to reproduce:**
1. Open attached project
2. Open the scene `Content\Scene`

**Minimal reproduction project:**
[TestPluginError.zip](https://github.com/FlaxEngine/FlaxEngine/files/13035502/TestPluginError.zip)

**Flax version:**
master 55ad5ae

**Comment by mafiesto4** [comment]
Thanks for reporting this! That's a regression from my commit 3e7368b1cb31aedfa37d9cdae1d8612b08e99967. Fixed in 0ea00a09cabe4bf4c6797d47fd92c25ea4c1d986.
