### ISSUE TITLE
Delete Source Module folder don't clean module references

### ISSUE THREAD

**Issue by RuanLucasGD** [FlaxEngine/FlaxEngine#1747]
**Issue description:**
If you create a module and try delete it, you need manually remove all references from your project files, delete your old module sln/Build files, this isn't user friendly. 

**Steps to reproduce:**

https://github.com/FlaxEngine/FlaxEngine/assets/79365912/3e405514-f453-4679-b92f-e3b08659a5e7

**Flax version:**
1.7 master

**Comment by MineBill** [comment]
It looks to me that GameTarget.Build.cs is meant to be user modifiable so deleting code from it is extremely dangerous and could lead to a loss of data. I believe the current solution is a good compromise but there should at least be a popup, notifying the user that they need to remove the reference from the build file.

**Comment by RuanLucasGD** [comment]
@MineBill yes but i think *Gen.cs" can be delete and maybe delete/comment only reference line from GameTargetBuild?

**Comment by mafiesto4** [comment]
Yeah, we could add some improvements in this area to make it more usable (eg. clean up those generated files and remove reference to removed module in build scripts).
