### ISSUE TITLE
Editor: Undocking the lower window of a Horizontal splitted area will close the above one.

### ISSUE THREAD

**Issue by schmidt-florian** [FlaxEngine/FlaxEngine#1750]
**Issue description:**

If you undock the lower window via dragging, the upper one closes.

**Steps to reproduce:**

1. Arrange some windows like in the video shown.
2. Drag the lower window to undock.
3. The upper one closes.
4. Arrange the windows again
5. Drag the upper window
6. The lower one will stay as expected.

https://github.com/FlaxEngine/FlaxEngine/assets/14238126/18120204-32e3-4a81-9674-ae445cb7485f

**Flax version:**

master 770d215

**Comment by schmidt-florian** [comment]
I think this is not limited to horizontal. A vertical Split area makes the same. I have a 2 monitor setup.

1. Main Window + Editor + Game + Scene
2. Toolbox + Properties + Content + Debug Log + Output Log

I wanted to move the property window and everything besides the toolbox and the properties window that I moved closed.

I recreated it with some windows:

https://github.com/FlaxEngine/FlaxEngine/assets/14238126/652a8443-a1cf-4fe0-8454-9eafa351a253

**Comment by mafiesto4** [comment]
Fixed in 7d43a0cc8bc8598cf29a685064772d6823cc4489.

It might not be ideal yet (there could be a case of not preserving the docked windows hierarchy). But now it won't lose any open tab - they might be merged into a series of tabs in a worst-case scenario.
