### ISSUE TITLE
Editor: Undo/Redo History doesn't Preserve Actor Hierarchy

### ISSUE THREAD

**Issue by madsfs** [FlaxEngine/FlaxEngine#1751]
I made a bunch of Actors and childed them to a Parent Actor.
They had their numbering perfectly from 0 to N. I deleted a couple of them and while the Actors returned to their correct position on screen, they were added to the bottom of the hierarchy they were part of and not placed where they belonged in the hierarchy.

So if you had the following hierarchy:
* Parent
  - Child0
  - Child1
  - Child2
  - Child3
  - Child4
  - Child5

And then you deleted a couple of the children so you had a Hierarchy like so (Deleting Child3, then Child0, then Child1):
* Parent
  - Child2
  - Child4
  - Child5

Then used Undo to get the children back, the children will be added back in the order reverse order they were deleted in, as expected however the Hierarchy will now look like this:
* Parent
  - Child2
  - Child4
  - Child5
  - Child1
  - Child0
  - Child3

I would have expected the Undo history to preserve the hierarchy.

**Comment by mafiesto4** [comment]
Fixed in 28da656ed13aacc5639d8a6e0d0038b73e1c3128,
