### ISSUE TITLE
Editor crash on try import model with LOD generation (Linux Mint Cinnamon)

### ISSUE THREAD

**Issue by RuanLucasGD** [FlaxEngine/FlaxEngine#1756]
**Issue description:**
If you disable Sloppy Optimization, set LOD target to 0.01 and triangle reduction to 0.1 the editor crash when you try reimport.

**Steps to reproduce:**
* Set triangle Reduction to 0.1
* Disable Sloppy Optimization
* Set LOD Target error to 0.01
![image](https://github.com/FlaxEngine/FlaxEngine/assets/79365912/3afa77fa-8439-4ffc-9770-598344d4ef03)

* Try reimport model
* Crash

My assets:
[Assets.zip](https://github.com/FlaxEngine/FlaxEngine/files/13054282/Assets.zip)

**Flax version:**
1.7 master https://github.com/FlaxEngine/FlaxEngine/commit/3188798152641c4a7c90ee8f384b9bbe5c641445

**Comment by mafiesto4** [comment]
@RuanLucasGD Could you attach the source file to test reimporting?
`/home/capy/Documents/Dev/Hook-and-Loop-Mobile/Assets/LEVELS/Armasing_Park/Models/Barraquinha_Central/Barraquinha_Central.fb`

**Comment by RuanLucasGD** [comment]
@mafiesto4 
[Assets.zip](https://github.com/FlaxEngine/FlaxEngine/files/13170587/Assets.zip)

**Comment by mafiesto4** [comment]
Fixed in bcbc1cd413cd562c00650de6fe7e186cc05edfdc and 3f632b7d15bd16d994dcfbaa9dcf8a1b16bd91cc.
