### ISSUE TITLE
Editor Cursor Visibilty affected by game if editor is in the background.

### ISSUE THREAD

**Issue by schmidt-florian** [FlaxEngine/FlaxEngine#1757]
**Issue description:**
If you have, for example, an FPS camera that sets the cursor to lock and invisible and you tab out of Flax via ALT+TAB, every time the cursor touches Flax, the cursor turns invisible. Even Flax is not focused.

I would prefer this: 
If the Flax Editor loses Focus, it tells Windows not to hide the Cursor until Flax Editor Game Viewport regains focus again.

This would prevent hiding occasionally your cursor if Flax Editor runs in the background and you move your mouse over it.

**Steps to reproduce:**
1. Open the Flax Editor Maximized.
2. Open any other software on top on Flax not maximized.
3. Create a script that turns the cursor invisible and attach it to the scene
4. Goto play mode
5. Tab out of Flax to the other software
6. If the cursor is over flax, the cursor turns invisible even if Flax is not focused.

**Flax version:**
Windows
master 3188798

**Comment by mafiesto4** [comment]
Fixed in f0c2e65b5cb578c39407761e5ad288a1a374ced1.
