### ISSUE TITLE
Particle Preview: Strange Scene Shadow leakage

### ISSUE THREAD

**Issue by schmidt-florian** [FlaxEngine/FlaxEngine#1758]
**Issue description:**
The particle preview has some strange scene shadow leakage.

https://github.com/FlaxEngine/FlaxEngine/assets/14238126/62cf7d86-6092-429d-9a82-3480edddba37

**Steps to reproduce:**
1. Open any project, unpack, and add the particle emitter
2. While having a scene open, like the default cube scene, open the particle emitter
3. Observe the shadow of the scene

[TestParticles.zip](https://github.com/FlaxEngine/FlaxEngine/files/13059489/TestParticles.zip)

**Flax version:**
master 3188798

**Comment by mafiesto4** [comment]
Fixed in 9a9e32d4c5aa7bcb414b3c21560b329763ca94aa.
