### ISSUE TITLE
[Critical] Editor Freezes on drag&drop frequently

### ISSUE THREAD

**Issue by schmidt-florian** [FlaxEngine/FlaxEngine#1761]
**Issue description:**
The problem has been occurring for about 2-3 days. Something was probably changed in the last 50 commits that triggers this.

The Flax Editor works perfectly and sometimes, unfortunately, too rarely to say which action, no matter what you drag. On drop the editor freezes. It also happened once when I wanted to cancel the drag using "ESC". As I said, it's not specific what you do and where. It occurs while working sometimes after minutes. Sometimes after 30 minutes.
But it's so often that I have around 2-4 freezes per hour,
The problem is, that there is no log entry and no error message. Flax just freezes.
I have tried to debug that situation a little:

The MainThread is waiting in WindowsWindow.DragDrop.cpp:616 for the task that doesn't seem to end.
![image](https://github.com/FlaxEngine/FlaxEngine/assets/14238126/4ef105cb-131f-49b6-8f44-ead876aa6fd9)

The ThreadPool5 is in DebugDraw.cpp:919. Even after briefly unpausing and pausing again, the thread is here.
![image](https://github.com/FlaxEngine/FlaxEngine/assets/14238126/201e53e0-3414-425a-9f95-ec3268f24085)

Here are all Thread Stacks:
![image](https://github.com/FlaxEngine/FlaxEngine/assets/14238126/f821baa3-05fd-41b2-88b5-c199ac9de325)
![image](https://github.com/FlaxEngine/FlaxEngine/assets/14238126/c1dec875-a9e2-4d73-a953-44214e489483)
![image](https://github.com/FlaxEngine/FlaxEngine/assets/14238126/81b7e362-8d03-4878-a79d-d4aca5470408)

**Flax version:**
master; Approximately since the last 50 commits, not 100% sure

**Comment by Menotdan** [comment]
I've had the same issue. Not reliably reproducible though, at least for me. I would love to try to git bisecting it otherwise.

**Comment by MineBill** [comment]
I still don't understand why drag and drop happens on a different thread. Makes debugging some issues with drag n drop on the hierarchy hell because i can't Debug.Log.

**Comment by schmidt-florian** [comment]
I have updated the Issue in terms of frequency. Because the more intensively you work with the editor, the more often it occurs. The last few days I've mostly been doing scripting things. Right now I'm trying to animate things and it happens all the time.

**Comment by lbstorey** [comment]
For what it's worth, I'm experiencing this as well with drag and drop, and only today so far. Happens randomly with no log entry or error message.

**Comment by mafiesto4** [comment]
Related to #1773

**Comment by schmidt-florian** [comment]
With master 806590d, the bug occurred after around 1h of usage again. I have this time only the managed debug stack.
![image](https://github.com/FlaxEngine/FlaxEngine/assets/14238126/b7610d30-b964-4471-9f74-49e7bdbca27d)
![image](https://github.com/FlaxEngine/FlaxEngine/assets/14238126/670917ea-e7d2-44a5-b3ad-8839d7a133d8)

**Comment by schmidt-florian** [comment]
I have no idea if I'm causing memory leaks or breaking other things. However, I have now simply commented out `Engine\Platform\Windows\WindowsWindow.DragDrop.cpp:616`. Because I had to restart the editor every 5-15 minutes and of course lost any progress since the last save, although Ctrl+S is already a reflex for me :D
To everyone who is also affected by this and cannot wait for the fix: Use the information with caution. Like I said, I have no idea what I broke with it. But I've been using Flax for 2 hours without any freezes or other strange events.

**Comment by XeroWolf** [comment]
Experiencing this as well. Currently on build 1.7.6402. It's hard to replicate but usually happens after 15 mins or so when dragging and dropping in pretty much anywhere in the editor.

**Comment by XeroWolf** [comment]
Looks like the issue has been fixed. Well for me at least. It hasn't freezed all day after using the last daily build.

**Comment by mafiesto4** [comment]
@schmidt-florian I wonder if it works fine with the latest master?

**Comment by schmidt-florian** [comment]
@mafiesto4 I have it not tested yet on my work laptop. But on my home PC with 70a06c5 it is fine now. I have not had one freeze in 3h of usage of Flax.
