### ISSUE TITLE
Better way to make Editor UI

### ISSUE THREAD

**Issue by NoriteSC** [FlaxEngine/FlaxEngine#1762]
# API Change for internal Editor / Custom Editors
generating GUI is not a good experience
it feels like a spaggety

the https://github.com/FlaxEngine/FlaxEngine/issues/1126 has suggestion for making a Widget asset what about having a version for Editor
and re make editor GUI to use this system ?
of course the saving to binary will not do (Git LFS)

**Comment by mafiesto4** [comment]
We don't have time resources to rewrite Editor anytime soon.

**Comment by NoriteSC** [comment]
> We don't have time resources to rewrite Editor anytime soon.

what about just having a opcion for it there is no need to rewrite Editor this can be done slowly
