### ISSUE TITLE
Rapidjson crash on null-string

### ISSUE THREAD

**Issue by stefnotch** [FlaxEngine/FlaxEngine#178]
**Issue description:**
Rapidjson crashes when it expects a string but gets null.

This, in conjunction with the Android settings, leads to an error.

**Steps to reproduce:**
1. Open the Android settings
2. In the permissions, add a lot of useless empty lines. Don't write anything in there
3. Save the settings
4. Now you should have a file with some `null` Permissions

Android settings
```json
{
	"ID": "a8a9d9cb47117c3c1a1694946f3a420f",
	"TypeName": "FlaxEditor.Content.Settings.AndroidPlatformSettings",
	"EngineBuild": 6215,
	"Data": {
	"PackageName": "com.${COMPANY_NAME}.${PROJECT_NAME}",
	"Permissions": [
		null
	],
	"OverrideIcon": "ec3354de4c5d4e5733065d8b1b02c0bb"
}
}
```

**Minimal reproduction project:**

[PillFight PC.zip](https://github.com/FlaxEngine/FlaxEngine/files/5892546/PillFight.PC.zip)

**Flax version:**
Flax 1.0

**Comment by Vizepi** [comment]
It seems to be intended by the standard:
https://benohead.com/blog/2018/01/15/null-valid-json-text/#:~:text=One%20of%20the%20changes%20in,object%20is%20indeed%20%E2%80%9Cnull%E2%80%9D.

**Comment by stefnotch** [comment]
I suppose my favourite way of fixing this would be to upgrade to C# 8 and add support for nullable reference types. And then make that string array non-nullable and handle it in the [Array Editor](https://github.com/FlaxEngine/FlaxEngine/blob/7e4afbc4ff31b333523934c6272cd7e5ca6ae689/Source/Editor/CustomEditors/Editors/ArrayEditor.cs) and [List Editor](https://github.com/FlaxEngine/FlaxEngine/blob/7e4afbc4ff31b333523934c6272cd7e5ca6ae689/Source/Editor/CustomEditors/Editors/ListEditor.cs).
