### ISSUE TITLE
Material Editor: Reordering of Parameters

### ISSUE THREAD

**Issue by madsfs** [FlaxEngine/FlaxEngine#1781]
It would be a neat feature to be able to reorder the list of the Parameters you introduce as you make the shader in the node editor.
Currently it seems the only thing you can do is delete the parameter and re-add it to change the order in which they appear.

**Comment by Menotdan** [comment]
Currently, you can add an `EditorOrder` attribute through Right Click on Parameter > Edit Attributes. But I agree, there should be a much easier to reorder parameters.

**Comment by mafiesto4** [comment]
Yeah, and we could add a quicker utility to set group name for parameters (aside from `Edit Attributes`) so the user can quickly reorder and group parameters (not only in material but also in Visual Script, Particle Emitter, etc.).

**Comment by mafiesto4** [comment]
Added in #2670
