### ISSUE TITLE
Material Variant: The Variant does not update properly when de-selecting master material properties

### ISSUE THREAD

**Issue by madsfs** [FlaxEngine/FlaxEngine#1783]
I have this Material Variant which is based on a Master Material. As can be seen it has a MaskTexture which is applied to the material in the preview (transparent and solid lines). However for this Material I don't want the texture part. I just want the Emissive color parts.
![image](https://github.com/FlaxEngine/FlaxEngine/assets/113017777/024597e2-b269-4e40-973a-79a6a16ed8a4)

So I disable the Texture, but as you can see even though I did that the Material Variant still has the Transparent/Solid lines as if the texture was still applied. It should just be a solid white color when turning off or removing that texture.
![image](https://github.com/FlaxEngine/FlaxEngine/assets/113017777/98590385-ab34-4bfd-b407-f2d010ac4083)

**Comment by madsfs** [comment]
On further inspection it seems that the Master Material also does not care whether the Texture is present or not after the fact. The material simply doesn't update.

**Comment by mafiesto4** [comment]
Still works fine to me.
