### ISSUE TITLE
Material Editor: Allow the usage of a custom Model in the Preview Window

### ISSUE THREAD

**Issue by madsfs** [FlaxEngine/FlaxEngine#1784]
When creating Materials allow for the usage of a Custom mesh in the Preview Window.
This makes it much easier to preview changes to a Material you are working on, while it is attached to the mesh you expect it to be.
![image](https://github.com/FlaxEngine/FlaxEngine/assets/113017777/65a381b4-d17c-4906-9716-75c1a667f05e)

**Comment by Menotdan** [comment]
Will be added by #1785

**Comment by mafiesto4** [comment]
Added in #1785
