### ISSUE TITLE
Editor: Dynamic Initialization of Lists And Multi-Add

### ISSUE THREAD

**Issue by madsfs** [FlaxEngine/FlaxEngine#1787]
So as you can see in the video below, if you try to drag an element to a list, it will not expand to accomodate and assign the element automatically. You must set a specific size of the list and then drag an element to a separate slot.
In my example I'm only moving 3 elements to this list, so it's not that big a deal to assign them one at a time, however it is still tedious. This would be an issue if you had 10, 20 or 100 elements you needed to add to a list this way (for any reason).

My proposal is that whenever elements are dragged over a list like this, expand the list with the number of slots needed to add the elements and then append them to the end of the list in the order they appeared (as you can see me attempt in the video at the start as well).

This would be a great QoL improvement for the editor.

https://github.com/FlaxEngine/FlaxEngine/assets/113017777/39fa9cda-c612-4ee7-8492-333c372f422f

**Comment by MineBill** [comment]
I have an initial implementation for this and i would like some feedback on it:

https://github.com/FlaxEngine/FlaxEngine/assets/30367251/df6c2b31-85c5-478f-9deb-1e366451721e

Does this look intuitive to you? What if you were a new user?

**Comment by madsfs** [comment]
> I have an initial implementation for this and i would like some feedback on it:
> 2023-10-30.22-35-43.mp4
> 
> Does this look intuitive to you? What if you were a new user?

So if I am not mistaken it seems like when you drag over, the entries get replaced?
I would expect that entries just get appended, not replaced.

**Comment by mafiesto4** [comment]
Added in #1850
