### ISSUE TITLE
[C++][PhysX] Compilation fail when including Physics headers in C++

### ISSUE THREAD

**Issue by Vizepi** [FlaxEngine/FlaxEngine#180]
**Issue description:**
When compiling a C++ script including "Engine/Physics/Actors/Rigidbody.h", there is a missing header file.

**Steps to reproduce:**
Create a C++ script
Add the line `#include "Engine/Physics/Actors/Rigidbody.h"` before the class
Compile for Development/Win64

**Flax version:**
1.0.6215

PS: It seems that PhysX public headers are not installed along with the engine
In `C:\...\Flax_1.0\Source\ThirdParty\PhysX` there is only a License.txt file and a PhysX.Build.cs file.

**Comment by mafiesto4** [comment]
Fixed by https://github.com/FlaxEngine/FlaxEngine/commit/283714a39f4582c3d5d7cc849791be22ce95d330
