### ISSUE TITLE
Rough Start with C++

### ISSUE THREAD

**Issue by vitormaduro** [FlaxEngine/FlaxEngine#1800]
Hello, sorry if posting this as an Issue is not the correct way to provide feedback, but I really feel my experience can represent how someone new to the engine may feel about certain issues.

First of all, I have a full-time job as a C# programmer, so I decided to step out of my comfort zone and mess around with C++ code. I downloaded the v 1.6 .exe from the site, installed it, and created a new project with the default objects (Cube, Plane, and Camera). Reading the documentation, I saw what needed to be installed to write code in C++, so I updated my (already installed) Visual Studio 2022 with the missing features.

The first step was to change the value of `BuildNativeCode` to `true`, and then I should be able to write and run the code, but as soon as I changed that value, the engine was unable to compile the scripts properly:

![image](https://github.com/FlaxEngine/FlaxEngine/assets/49737868/b8f6ea29-c015-43c0-9420-e971a075029f)

There were quite a few errors, but the first one is enough to understand what was going on. With a quick search online, you can see that the "xxx is not a member of yyy" happens when you try to compile a newer C++ file with an old compiler lacking some used features. Searching a little more, I was able to learn how to change the compiler version used by Visual Studio, but no files generated by the engine are set to be compiled with it.

After hours (and I mean it, I spent a whole afternoon trying to get things to work), I understood how the Flax.Build file works, and so I tried to find a way to set the compiler's version used by it. More time was spent digging through the menus, the documentation, the info provided by running the Flax.Build executable with the `-help` flag, and nothing. Then I noticed one thing printed to the Output Log:

![image](https://github.com/FlaxEngine/FlaxEngine/assets/49737868/95fc09a0-ddea-4f6b-aa68-65b545dca81d)

The game was being compiled with C++ 14, but I had no idea how to change that. Eventually I decided to read the source code of the Build application to see how those flags were being set. The code is not available with the installed files, so I went to GitHub and started searching for some of the flags included. In little time I was able to find the code responsible for setting those flags, and learned that the `/std:c++14` flag was being used because no other value was set in the `CompileEnv`.

Dug a little more, and landed on the file were the class was defined. Saw the `CppVersion` property, and saw the list of available values. With that information in hand, I opened the Build script again, and added the line `options.CompileEnv.CppVersion = CppVersion.Latest;` to it, thinking the latest version of C++ will have everything needed... Then another error happened:

![image](https://github.com/FlaxEngine/FlaxEngine/assets/49737868/ace6f625-3af2-4c1e-9519-7dc3a9f28dd4)

More searching, more debugging, and eventually I learned this error message was a somewhat new addition to the C++ standard. I was getting really tired at this point, so I just decided to try different version to see if any of them worked. `CppVersion.Cpp20` resulted in the same error. Changed it again to `CppVersion.Cpp17` and... It worked.

After all that I was able to continue following the tutorial provided in the documentation, and print 1 line of text to the Output Log once the game started...

Now, I totally understand this is not a commercial project with a huge team and funding behind it, but I hope you all can understand how digging through source code is not something someone new is expected to do, specially if they're new to programming altogether. During my time with the engine I noticed how some parts of the documentation were outdated, and I know it's hard to maintain everything 100% updated at all times, but more critical info (like the required compiler version and how to change it) should be displayed somewhere, probably in the same page teaching people how to get started coding with C++...

Anyways, sorry if this ended up too long, or if this is not the right place to post it, but I wanted to share my feedback. Also, sorry if any part sounded too harsh. I'm actually quite impressed with the current state of the engine, and I'm eager to play with it when I have the time.

**Minimal reproduction project:**
As said earlier, this all happened with a blank project, and GitHub is also complaining because the .zip is too large to be uploaded. Let me know if there's anything else I can do to help replicate the issues I had

**Flax version:**
1.6.6344

**Comment by Menotdan** [comment]
This is a bug that is fixed on the master branch. We are hoping to adopt a better release cycle for flax versions as well, so users won't experience these issues on stable versions in the future after they get fixed on master.

**Comment by mafiesto4** [comment]
Yeah Visual Studio update broke the compilation, engine update with this fix will be released this week,

**Comment by vitormaduro** [comment]
Oh, I'm glad to hear it was a bug and it's already fixed. Looking forward to more updates!
