### ISSUE TITLE
`API_FIELD() Dictionary<VectorXBase<T>, ...> Test;` fails to serialize

### ISSUE THREAD

**Issue by Withaust** [FlaxEngine/FlaxEngine#1802]
**Issue description:**
Currently, using something like `API_FIELD() Dictionary<Int2, String> Entries;` for example is impossible due to the fact that editor assignment seems to fail, resulting in the container being empty at runtime, while also not being able to be serialized in order to preserve state between different editor runs.

This affects all `VectorXBase`'d types when used in `API_FIELD() Dictionary<???, ...> Test;` scenario such as:
`Float2`, `Double2`, `Int2`, `Vector2`, `Float3`, `Double3`, `Int3`, `Vector3`, `Float4`, `Double4`, `Int4`, `Vector4`

**Flax version:**
https://github.com/FlaxEngine/FlaxEngine/commit/806590d1c3350136ae6d0043fa22e06a3faf7002

**Comment by Withaust** [comment]
What seems to be strange is that `API_FIELD() Dictionary<String, Array<AssetReference<Texture>>> Test;` apparently works, which means something wrong is happening with Int2 as a key.

**Comment by mafiesto4** [comment]
Fixed in 966cd973c660e76feeac8547a8314960f389e967 and c27187bd0ab0a5c5065d1e05df0772264062588e
