### ISSUE TITLE
Editor Rename Field checks lenght for all actors.

### ISSUE THREAD

**Issue by schmidt-florian** [FlaxEngine/FlaxEngine#1806]
**Issue description:**
If you have for what ever reason a super long actor name and try to rename other short/normal name actors, the field is as long as the longest actor name.

**Steps to reproduce:**
Have a ultra long actor name.
Try to rename a short actor name.

https://github.com/FlaxEngine/FlaxEngine/assets/14238126/36a74a6f-0334-42a8-89db-3c5993e3473b

**Flax version:**
master 806590d

**Comment by mafiesto4** [comment]
Fixed in #1807
