### ISSUE TITLE
Support Animations for Prefabs

### ISSUE THREAD

**Issue by schmidt-florian** [FlaxEngine/FlaxEngine#1809]
**Issue description:**
If I understand the [Docs](https://docs.flaxengine.com/manual/animation/scene-animations/scene-animation-player.html#objects-and-tracks-mapping) correctly, the only way to animate prefabs would be the use of a custom script that remaps the GUIDs.

This workaround is not very intuitive and easy.
It should be possible to open up the Prefab Preview and drag Prefab References to the Scene Animator. (While this is currently possible, the references are lost if the prefab window is closed)

A solution that would be probably not so hard is: An internal remapping of GUIDs when spawning the prefab. The prerequierment would be, that you animate from the Prefab window so that the Prefab GUIDs are used. Just as an Idea.

**Flax version:**
any

**Comment by mafiesto4** [comment]
`Scene Animation` editor has built-in support for animating objects in prefab and `Scene Animation Player` automatically performs object mapping if **UsePrefabObjects** is checked.
Tutorial: https://docs.flaxengine.com/manual/ui/tutorials/ui-prefab-animation.html
