### ISSUE TITLE
Need API to affect/edit bones' transforms

### ISSUE THREAD

**Issue by TheOmnisimush** [FlaxEngine/FlaxEngine#1812]
**Issue description:**
- Currently AnimatedModel only supports "GetNodeTransformation()" to get Transform of Model's bones.
  https://docs.flaxengine.com/api/FlaxEngine.AnimatedModel.html#methods
- A Script API to affect the Transform of bones is needed, to enable user to move/rotate bones as needed
  (something like "SetNodeTransformation()" will be nice)
- For example, creating a "BoneCloth/SpringBone"
   https://forum.flaxengine.com/t/what-is-the-best-correct-way-to-implement-spring-bone-in-flax/1412/2
  or to make a procedural animation by script
  
**Flax version:**
1.6.6344

**Comment by mafiesto4** [comment]
You can use `GetCurrentPose` to get `Matrix[]` with all nodes, modify them, and then set via `SetCurrentPose`. For example, during `AnimationUpdated` which is called when Anim Graph is evaluated and game can post-process nodes. The current design mostly depends on the Anim Graph to handle nodes in an efficient way (native code that runs in async by default). But ofc it makes sense to have more possibilities.

**Comment by TheOmnisimush** [comment]
Thanks for replying, I will try `GetCurrentPose` and `SetCurrentPose`. 
One question though, since I will be getting only the array of `Matrix[]`, How can I identify Bone Ids by its name?
I could not find something like `BoneNameDictionary` or `GetBoneIdByName`

**Comment by mafiesto4** [comment]
@TheOmnisimush you can get list of nodes from the skinned model asset: `var nodes = animatedModel.SkinnedModel.Nodes;`
