### ISSUE TITLE
Prefab editor window resizing handles losing functionality while editing UI.

### ISSUE THREAD

**Issue by Menotdan** [FlaxEngine/FlaxEngine#1815]
**Issue description:**
While editing a Prefab with UI in it, I went to edit some code, then came back. I wanted to test how the UI would look on different resolutions, so I grabbed the resizing handles:

![image](https://github.com/FlaxEngine/FlaxEngine/assets/32620310/c50fc6c4-744b-4dd4-9089-7b4fc6c30fb9)
And tried to move it.

However, now the resizing handle is detached:
![image](https://github.com/FlaxEngine/FlaxEngine/assets/32620310/ff7f36c1-a8cb-4137-960c-746ac9541190)

**Steps to reproduce:**
1. Create a prefab
2. Add UI to the prefab
3. Add a script to the prefab
4. Open the prefab, and dock it to your main Flax window.
5. Try resizing the viewport, it should work.
6. Edit the script attached in the prefab, save it, and re-focus flax.
7. Try to drag the resizing handles, and they should be broken.

**Flax version:**
master https://github.com/FlaxEngine/FlaxEngine/commit/70a06c5db362624f51358d6e0afc8f76b0197ba5

**Comment by mafiesto4** [comment]
I was unable to reproduce it.
