### ISSUE TITLE
Canvas scaler not scaling context menus.

### ISSUE THREAD

**Issue by Menotdan** [FlaxEngine/FlaxEngine#1816]
**Issue description:**
When I use a canvas scaler, set to "Scale With Resolution", context menus fail to scale the same way.

Before scaling:
![image](https://github.com/FlaxEngine/FlaxEngine/assets/32620310/cca240ce-21eb-4ecb-b2bb-3a93d710a744)

After scaling:
![image](https://github.com/FlaxEngine/FlaxEngine/assets/32620310/9d550e11-18e1-4f59-9f50-4eb8229521ee)

**Steps to reproduce:**
1. Create a canvas, and add a canvas scaler using "Scale With Resolution" to it.
2. Add a dropdown with some items to the canvas scaler.
3. Open the context menu, observe results.
4. Scale the window a large amount.
5. Open the context menu again, observe results.

**Flax version:**
master https://github.com/FlaxEngine/FlaxEngine/commit/70a06c5db362624f51358d6e0afc8f76b0197ba5

**Comment by mafiesto4** [comment]
Fixed in #1826.
