### ISSUE TITLE
[Suggestion] Add scrolling option to Dropdown context menus.

### ISSUE THREAD

**Issue by Menotdan** [FlaxEngine/FlaxEngine#1817]
You should be able to scroll down larger context menus. Even for a simple list like of all allowed resolutions, it goes off-screen and becomes unusable. 
![image](https://github.com/FlaxEngine/FlaxEngine/assets/32620310/512053ca-03fa-4a57-afe2-19675ba3c4fe)

**Flax version:**
master https://github.com/FlaxEngine/FlaxEngine/commit/70a06c5db362624f51358d6e0afc8f76b0197ba5

**Comment by mafiesto4** [comment]
Added in #1826
