### ISSUE TITLE
Cannot change the material on 2 or more actors at the same time.

### ISSUE THREAD

**Issue by schmidt-florian** [FlaxEngine/FlaxEngine#1818]
**Issue description:**
You can change on multiple selected actors the meshes, but not the materials. Even all the Actors have the same number of materials.

**Steps to reproduce:**
Spawn 2 Cubes.
Try to assign in one move on both cubes a new material.

**Flax version:**
master 70a06c5

**Comment by mafiesto4** [comment]
Fixed in 36daa38e0fb249c479ccaba767967846fc15e276.
