### ISSUE TITLE
Suggestion: Add Tooltips that state what the selected class is

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#182]
This isn't a crucial feature but would improve my work flow:

### Problem:
In this graphic, I have renamed the CharacterController to Player. 
![image](https://user-images.githubusercontent.com/35228400/106353352-06e93100-633e-11eb-8bcb-08517ff2fd9f.png)

If I forget what class **Player** is, I can't quickly figure out what it is. The class name is neither in its properties, nor visible by hovering the mouse over the top of the actor. Basically, I need to look at the actor properties and try guess what it is based on the properties it comes with.

### Solution:
Add an extra field that states what the class is:
![image](https://user-images.githubusercontent.com/35228400/106353428-9a226680-633e-11eb-846b-26f94b16c8ec.png)
or add a hover text that appears and tells me what class it is:
![image](https://user-images.githubusercontent.com/35228400/106353464-d786f400-633e-11eb-99c3-d0d71154cdf9.png)

**Comment by mafiesto4** [comment]
Very good idea. Tooltip with class typename and documentation comment would help.

**Comment by mafiesto4** [comment]
Added in 141022caf82b26faa78cbfe5b0154761b1bc55d4.
