### ISSUE TITLE
Editor: Add a "New Script" button to the "Add Script" context menu

### ISSUE THREAD

**Issue by mads-fs** [FlaxEngine/FlaxEngine#1820]
When you press the "Add Script" button you are shown a list of all the scripts you've made so far. It would be helpful in the cases where you might be missing something that you can press "New..." or something to that effect in order to create a new script and attach it.

However this poses an issue as it seems Flax does not replace scripts whose name it cannot find, so the issue is likely two-fold.
![image](https://github.com/FlaxEngine/FlaxEngine/assets/146040109/4bffdb55-0e61-4215-bbf7-eb23846e7f20)

**Comment by mafiesto4** [comment]
Added in #1827
