### ISSUE TITLE
[Request] Editor Grid Snapping: Add custom grid size

### ISSUE THREAD

**Issue by schmidt-florian** [FlaxEngine/FlaxEngine#1823]
**Issue description:**
For my special case, it would be useful to have 500 as a grid. So instead of having tons of options, maybe add a custom option where the user can enter the grid size. Split it in X/Y, maybe someone wants a non-uniform grid.

**Flax version:**
any

**Comment by mads-fs** [comment]
I concur that this is a good feature and should be on the same level as Vertex Snapping in editor in terms of usability severity.

**Comment by NoriteSC** [comment]
> **Issue description:** For my special case, it would be useful to have 500 as a grid. So instead of having tons of options, maybe add a custom option where the user can enter the grid size. Split it in X/Y, maybe someone wants a non-uniform grid.
> 
> **Flax version:** any

added it to my task list

**Comment by xxSeys1** [comment]
Please keep the preset around though, add it as an extra option

**Comment by mafiesto4** [comment]
Added in d9aa123bce0b186f3861318cb89482faece4ff0a.
