### ISSUE TITLE
memory leek in DrawSprite ? leeks 4 bytes of memory 

### ISSUE THREAD

**Issue by NoriteSC** [FlaxEngine/FlaxEngine#1829]
**note**
this is from my small testing
**Steps to reproduce:**

run engine overnight
now engine teaks up 5-6gb insted of 1-3

**Minimal reproduction project:**

anny

**Flax version:**

https://github.com/FlaxEngine/FlaxEngine/commit/9f3221c533cd75716b2fbe4b0ce9ab20f6f1e959

**Comment by mafiesto4** [comment]
`DrawSprite` seams to work fine now. But maybe there is another leak.

**Comment by mafiesto4** [comment]
Fixed in f434ff2efe76ecaadbbbb7c075dd561febf2fd2a.
