### ISSUE TITLE
Sphere Mask shader node does not appear to function

### ISSUE THREAD

**Issue by Zapgun** [FlaxEngine/FlaxEngine#1830]
*NOTE* This does work if you put the Texcoord node in 'A' and Center Offset Vector2 in 'B', but this still does not work as the example provided. Ideally these should default values should be added and labels provided for 'A' and 'B'.

**Issue description:**
The existing Sphere Mask shader node does not appear to function as previously described in this post: https://discord.com/channels/437989205315158016/509056735844106251/803352662908993566.

**Steps to reproduce:**
Follow example screenshot to see results.

**Minimal reproduction project:**
As per the screenshot provided.

**Flax version:**
1.7.6402

![image](https://github.com/FlaxEngine/FlaxEngine/assets/330793/7cff8e46-a8e9-4516-90e1-c31c88b08916)

**Comment by mafiesto4** [comment]
Added in a685918e1012639cdaea134ee83e9e2de627aaec

![image](https://github.com/FlaxEngine/FlaxEngine/assets/3464853/3d28331e-661e-4696-9f5c-59e0309b1f2d)
