### ISSUE TITLE
Unable to spawn a Prefab at 0,0,0 when the Prefab itself has a position.

### ISSUE THREAD

**Issue by schmidt-florian** [FlaxEngine/FlaxEngine#1831]
**Issue description:**
If a Prefab Position Value is not 0,0,0 and you try to spawn it at 0,0,0, it will not spawn at 0,0,0 but at the Prefab Position Value.

![image](https://github.com/FlaxEngine/FlaxEngine/assets/14238126/409213d1-a253-4935-97f6-0986b2c46bea)

**Steps to reproduce:**

1. Create a Prefab
2. Set the Root Position of the Prefab to 100,0,0
3. Create a script and spawn it at 0,0,0 via `PrefabManager.SpawnPrefab(Prefab, Vector3.Zero, Quaternion.Identity);`
4. The Prefab will spawn at 100,0,0.
5. Try spawn it at 1,0,0, it will spawn at 1,0,0

**Flax version:**
master 70a06c5

**Comment by NoriteSC** [comment]
ops this one is on me [if (transform != Transform::Identity)](https://github.com/FlaxEngine/FlaxEngine/blame/master/Source/Engine/Level/Prefabs/PrefabManager.cpp#L194) idk if i can removing the **if** without any a problems
i will make a fix for it
but it will need some testing

**Comment by schmidt-florian** [comment]
I find the possibility of giving the root object in the prefab a TRS... strange. I would also say this shouldn't be possible since you define this when spawning.

I accidentally created such values after I simply made an Object from the Scene as a prefab, whereupon these values were set.

I'm not sure if this is a feature... or just a source of confusion. At least I assumed that the Root object Transform is always Identity.

**Comment by NoriteSC** [comment]
oo i just remember why i added this [if (transform != Transform::Identity)](https://github.com/FlaxEngine/FlaxEngine/blame/master/Source/Engine/Level/Prefabs/PrefabManager.cpp#L194) the 1 of [overloads](https://github.com/FlaxEngine/FlaxEngine/blob/master/Source/Engine/Level/Prefabs/PrefabManager.cpp#L39) spawns the prefab where the root is set in the prefab

**Comment by NoriteSC** [comment]
@mafiesto4  so what do u think ? spawn at 0,0,0 when using [this overload](https://github.com/FlaxEngine/FlaxEngine/blob/master/Source/Engine/Level/Prefabs/PrefabManager.cpp#L39)
or make a copy of Spawn Prefab and spawn the prefab where is set in the asset

**Comment by schmidt-florian** [comment]
I don't know if it causes problems, but instead of `Identity`, use `default`? So .. if a Transform comes with `default`, it means use the Prefab `Transform`... also like the `Identity`, but it is unlikely that someone will set 0,0,0 and 0,0,0 Scale. Or... use a flag? ^^

**Comment by mafiesto4** [comment]
Fixed in 56c9429e253960e2dbb16b80462877d812dc1662.
