### ISSUE TITLE
Visual Script: Vector3 Set X / Y / Z not working

### ISSUE THREAD

**Issue by CunningBanana** [FlaxEngine/FlaxEngine#1832]
**Issue description:**
Using the Nodes to set the Component of a Vector3 doesn't work.

[Error] Failed to set field 'FlaxEngine.Vector3.X' with invalid object instance of type 'FlaxEngine.Float3'

**Steps to reproduce:**
![grafik](https://github.com/FlaxEngine/FlaxEngine/assets/149301922/09488d4e-8d20-468f-8a94-c2149972743c)

**Flax version:**
1.6.6344

**Comment by mafiesto4** [comment]
That's a current limitation of the Visual Scripting system here as this `Set X` modified the structure value not the reference of the structure in script variables. We could introduce concept of reference type connection for those cases so the modified value would be propagated back to the script property data.
