### ISSUE TITLE
Some mouse buttons don't work

### ISSUE THREAD

**Issue by RuanLucasGD** [FlaxEngine/FlaxEngine#1840]
**Issue description:**
Extended1 and Extended2 don't return true when press.
Try this code:
```
Debug.Log(Input.Mouse.GetButtonDown(MouseButton.Extended2));
```
**Flax version:**
1.7 master

**Comment by mafiesto4** [comment]
On Windows it maps to `XButton2` from XInput interface.

**Comment by RuanLucasGD** [comment]
@mafiesto4 i'm using linux

**Comment by mafiesto4** [comment]
Not yet implemented on Linux: https://github.com/FlaxEngine/FlaxEngine/blob/master/Source/Engine/Platform/Linux/LinuxWindow.cpp
