### ISSUE TITLE
Update tracy version to v0.10

### ISSUE THREAD

**Issue by MineBill** [FlaxEngine/FlaxEngine#1842]
Tracy recently released version 0.10 and the protocol is incompatible.
![image](https://github.com/FlaxEngine/FlaxEngine/assets/30367251/2069c16d-f88c-4141-8c1d-f7a44ae56708)

**Comment by mafiesto4** [comment]
Yeah Tracy was updated recently so we gonna migrate to the latest version soon. Most likely for 1.8. Meanwhiel you can use previous Tracy version for profiling.

**Comment by mafiesto4** [comment]
Added in 7dc645c1147e61895ef39500c6c7b451d74b3a35.
