### ISSUE TITLE
Prefab Root Actor Position Not Saved When Set to Zero

### ISSUE THREAD

**Issue by XeroWolf** [FlaxEngine/FlaxEngine#1845]
**Issue description:**
The position transform of the root Actor of a Prefab is not saved when all values are set zero. It has the same behaviour if you set all the xyz values to zero manually or use the "reset default" right click menu option. This only affects the Position Transform of the Root Actor in the Prefab Editor. This is a quirky one indeed.

**Steps to reproduce:**
1. Create a Prefab either from the Scene or the Content Panel.
2. Edit the Prefab in Editor and set the Position of any of the XYZ values. Save and close the Prefab Editor Window.
3. Reopen the Prefab and set **All** the Position values to **Zero**. 
4. Save, Close and Reopen the Prefab. All the Position values a reloaded back to their previous values.

**Flax version:**
1.7.6404 and Master Branch (I'm guessing these are the same as 1.7 was released today 🥳)

**Comment by Menotdan** [comment]
Investigating this.. seems like in the "Deserialize and apply changes" step of applying the prefab, since the new transform is 0, 0, 0, it doesn't get serialized to anything, and therefore that doesn't get registered as a change... but it wouldn't make sense for it to only affect the root, I think.

**Comment by Menotdan** [comment]
It looks like the child actors are getting serialized with a blank transform field if they have `0, 0, 0`, but I'm not sure why the root actor doesn't.

**Comment by Menotdan** [comment]
Ok, I've found out the root issue. In [line 75 of Prefab.cpp](https://github.com/FlaxEngine/FlaxEngine/blob/306dd43b18bbf6eb9684774e89898adc29325562/Source/Engine/Level/Prefabs/Prefab.cpp#L79), the prefab is spawned with the identity transform, which means the "default instance" of the prefab that everything compares to is always going to have 0,0,0 for the transform.
