### ISSUE TITLE
Editor: Include Engine Version in the Title Bar

### ISSUE THREAD

**Issue by mads-fs** [FlaxEngine/FlaxEngine#1847]
A simple request really, but a small improvement to the UX.
![image](https://github.com/FlaxEngine/FlaxEngine/assets/146040109/6c761b0f-52a4-42c5-9730-49bdf0921a24)

Include here what version of Flax I am currently using for clarity's sake. It's akin to what Unity does in their status bar and I always found it a useful piece of info to occasionally have to look at when you, at times, have to fiddle with multiple versions of an engine while jumping between projects.
Here is how they show it in Unity:
![image](https://github.com/FlaxEngine/FlaxEngine/assets/146040109/23f198d3-9c7b-4747-b68a-7d601a118b0b)

**Comment by mafiesto4** [comment]
Added in 42e83117365e241c9b070a62a4f9b2c06ca30541.
