### ISSUE TITLE
Launcher: Add Engine Version used to Project Thumbnails

### ISSUE THREAD

**Issue by mads-fs** [FlaxEngine/FlaxEngine#1848]
The Launcher currently is very rudimentary right now in a couple of ways, but one way it shouldn't be is one of the most important areas; aka the Projects.

I would like to see the Project thumbnail cards include what version of the engine was used last to work on them.

**Comment by mafiesto4** [comment]
Added for the next launcher update:

![image](https://github.com/FlaxEngine/FlaxEngine/assets/3464853/a65abd0b-1f50-4fa3-b5df-9f955b1173f6)
