### ISSUE TITLE
[Critical] Project does not open when Lens Dirt texture assigned.

### ISSUE THREAD

**Issue by Myterian** [FlaxEngine/FlaxEngine#1852]
**Issue description:**
When assigning a Lens Dirt texture in the Graphics settings, you get an error when trying to reopen the project. Opening process then gets canceled.
![grafik](https://github.com/FlaxEngine/FlaxEngine/assets/30194679/7daf9e78-04ba-49c3-ab20-ddb284bc7b87)
![grafik](https://github.com/FlaxEngine/FlaxEngine/assets/30194679/d6f1eda1-e4ed-4e4f-bdea-1dc9b79fb84b)

Current workaround / fix is to go to the Grapics Settings file in the explorer and resetting the Lens Dirt texture parameter to null in a code editor.
![grafik](https://github.com/FlaxEngine/FlaxEngine/assets/30194679/4bce2bbb-7893-4fb8-a107-65b810b9bbdd)

**Steps to reproduce:**
1. Create new project
2. Assign texture to Lens Dirst in Graphics Settings
3. Save and try to reopen

**Minimal reproduction project:**
Blank project

**Flax version:**
1.7.6404

**Comment by mafiesto4** [comment]
Fixed in 224e43ea555a21d6c701dec40a273e624d8c69fd.
