### ISSUE TITLE
Weird UI container resize/aligment 

### ISSUE THREAD

**Issue by RuanLucasGD** [FlaxEngine/FlaxEngine#1856]
**Issue description:**
I'm trying create a "collectible items bar" for my game, but i cannot align the items inside a container (Panels don't work correctly too, i think it is another bug). If i change resolution the position gets messed

**Steps to reproduce:**
1. Have a Canvas
2. Create a Container Control
3. Set the container anchors to follow left and right of screen
4. Add some children controls and set anchors to follow left and right of container
5. Resize your game viewport
6. Children has your messed positions

https://github.com/FlaxEngine/FlaxEngine/assets/79365912/7b2dffbe-1077-4c9b-b2e3-e8fea22c1e9b

**Minimal reproduction project:**
[BasicTemplate.zip](https://github.com/FlaxEngine/FlaxEngine/files/13230079/BasicTemplate.zip)

**Flax version:**

**Comment by mafiesto4** [comment]
It looks like the bug is gone now (on the latest `master` 41cff47ca36a0d64da7438f39b2ea8d0990505fa)
