### ISSUE TITLE
Camera: Hide Options based on UsePerspective

### ISSUE THREAD

**Issue by mads-fs** [FlaxEngine/FlaxEngine#1858]
If the Camera Actor has `UsePerspective` set to true then it would make sense to hide the Orthographic Scale flag or grey it out.
Similarly, if `UsePerspective` is set to false, then `FieldOfView` should be hidden or greyed out as well as `CustomAspectRatio`.

**Comment by mafiesto4** [comment]
Added in 4fdeb773a5a6dcf758ddb021d2dc11b073e9f903.
