### ISSUE TITLE
Random Crash after Closing the Flax Editor

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#186]
I'm unable to provide steps on how to repeat this. It seems to happen from time to time that after closing the Editor I get the following error:

![image](https://user-images.githubusercontent.com/35228400/106374205-fafc7e00-63d4-11eb-9d7a-99b45dd943dd.png)

I've include the memory dump for you to explore.
[Crash.zip](https://github.com/FlaxEngine/FlaxEngine/files/5899167/Crash.zip)

**Comment by mafiesto4** [comment]
Thanks for reporting this but I was unable to detect what exactly crashed 😢
