### ISSUE TITLE
A C# Exception that is thrown inside a JobSystem method is not catched.

### ISSUE THREAD

**Issue by schmidt-florian** [FlaxEngine/FlaxEngine#1861]
**Issue description:**
If you have an exception thrown inside a jobsystem method it will crash the editor.

```
[ 00:00:54.046 ]: [Error] Critical error! Reason: Unhandled Exception: System.Exception: Test
   at Game.MyScript.<>c.<OnStart>b__1_0(Int32 arg0) in D:\BugTest1\Source\Game\MyScript.cs:line 17
```

It should be catched and redirected to the debug log if possible.

**Steps to reproduce:**
1. Create a script with
```csharp
JobSystem.Dispatch(arg0 => throw new System.Exception("Test")); 
```
2. Play the script

**Flax version:**
master 536be6c

**Comment by SinnersSum** [comment]
In general I notice that exception handling around a lot of key areas is pretty lax. `Scripting` events also have this issue, meaning that a single errant delegate in `Scripting.Update` can prevent every other delegate from executing.

**Comment by mafiesto4** [comment]
> In general I notice that exception handling around a lot of key areas is pretty lax. `Scripting` events also have this issue, meaning that a single errant delegate in `Scripting.Update` can prevent every other delegate from executing.

That's a general C# thing.

**Comment by mafiesto4** [comment]
Actually, I'm not sure if we will be able to fix this without performance overhead. Right now, Job System calls directly C# function from C++ code without any `try`/`catch` block so we catch the exception via `AppDomain.CurrentDomain.UnhandledException` to log it but the .NET Runtime simply terminates the app.

I would advise using your own try/catch to be safe or writing code with that in mind - Job System usage aims to be high-performance first.

**Comment by schmidt-florian** [comment]
Is it possible to catch this only in the Editor? I mean, per preprocessor Symbol `#if EDITOR` or something. You could add a log message that states like. `That will crash the game @ runtime`

Most times if I report such stuff with exception handling, I do not care about the runtime. Such stuff is only annoying because the Editor Application itself crashes. 

For runtime it would be nice to have log entries. Of course log entries requires some catching to. So you already have the Option "Development build" So only catch if Editor for not crashing the Editor and logging; For Development only log and crash; For Runtime just crash.
