### ISSUE TITLE
Animation not working

### ISSUE THREAD

**Issue by Exice175** [FlaxEngine/FlaxEngine#1862]
**Issue description:**
   The Animation is just not running

**Steps to reproduce:**
   Open animation Graph in Flax 
   Drag and Drop animation in the Graph
   connect them
   Then there should play the animation in the preview but there is nothing happening

**Flax version:**
1.7.6404 

**Animation:**
[Standing Idle.zip](https://github.com/FlaxEngine/FlaxEngine/files/13239395/Standing.Idle.zip)
**Model:**
[rigged_human_character_free.zip](https://github.com/FlaxEngine/FlaxEngine/files/13239381/rigged_human_character_free.zip)

**Comment by mafiesto4** [comment]
This animation doesn't match the skeleton (node names are different):

![image](https://github.com/FlaxEngine/FlaxEngine/assets/3464853/238a7353-f558-4ead-90d0-317312f63ffb)

You can use animation retargeting to redirect animation channels: https://docs.flaxengine.com/manual/animation/animation/retargeting.html
