### ISSUE TITLE
Android build of game does not launch

### ISSUE THREAD

**Issue by gaberilde** [FlaxEngine/FlaxEngine#1864]
**Issue description:**

The game dosent load, expected for the game to load

**Steps to reproduce:**

Open the game on android, black screen or closes entirely or error message as shown in the video below 
Recorded on a Sony xperia Xa2

https://github.com/FlaxEngine/FlaxEngine/assets/6341453/7d6d3968-0734-47af-8c6e-5162673f6eb3

**Minimal reproduction project:**

All projects are affected for me

**Flax version:**

1.7

**Comment by mafiesto4** [comment]
Oh that was critical issue. Fixed in a7bb236344f9c289bea50c8c78fd75447c09e5f3.

**Comment by gaberilde** [comment]
> Oh that was critical issue. Fixed in [a7bb236](https://github.com/FlaxEngine/FlaxEngine/commit/a7bb236344f9c289bea50c8c78fd75447c09e5f3).

Ok thanks
