### ISSUE TITLE
Prefabs: Adding a Prefab to Another Prefab Renames it to Actor Type

### ISSUE THREAD

**Issue by XeroWolf** [FlaxEngine/FlaxEngine#1865]
**Issue description:**
If you add a Prefab to another Prefab opened in the Prefab Editor the root of the added Prefab is renamed to whatever type the root actor is.
**Steps to reproduce:**
1. Open a Prefab in it's editor.
2. Drag and drop another Prefab in to the opened one.

![Screenshot 2023-11-02 164921](https://github.com/FlaxEngine/FlaxEngine/assets/2533461/a656d125-6fac-4627-8fb9-6ede6fe25cbe)

**Flax version:**
1.7.6404 and Master Branch

**Comment by RuanLucasGD** [comment]
I can confirm this

**Comment by mafiesto4** [comment]
Fixed in d26b9818d881bfa7723837fc79e26dcd3fcc233c.
