### ISSUE TITLE
Flax 1.7: Failed to initialize editor! Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Dalfi** [FlaxEngine/FlaxEngine#1872]
**Issue description:**
Download Flax 1.7 created a new empty Project and open it.
During launch of editor i get the following exception message:
Failed to initialize editor! Object reference not set to an instance of an object.

[Log_2023_11_04_16_33_45.txt](https://github.com/FlaxEngine/FlaxEngine/files/13257071/Log_2023_11_04_16_33_45.txt)

**Minimal reproduction project:**
Just created a new empty Project

**Flax version:**
Flax 1.7

**Comment by MineBill** [comment]
Do you have Visual Studio installed?

**Comment by Dalfi** [comment]
yes

**Comment by mafiesto4** [comment]
Fixed in 22e34cb2b4458b16dfb95961484959e0475705fb.
