### ISSUE TITLE
Calculation of SplineLength wrong

### ISSUE THREAD

**Issue by schmidt-florian** [FlaxEngine/FlaxEngine#1876]
**Issue description:**
The calculation of the SplineLength does include the offset to the Spline Actor.

**Steps to reproduce:**
1. Open attached project
2. Look at the Spline Actor. The script tells you the length.

It says 1500 Units in length... the reality is more like 25 units. (The Cube is the default Cube)
![image](https://github.com/FlaxEngine/FlaxEngine/assets/14238126/a8be0b37-3fe2-430c-930b-682a3be9c8bc)

**Minimal reproduction project:**
[Test Blank 2.zip](https://github.com/FlaxEngine/FlaxEngine/files/13257961/Test.Blank.2.zip)

**Flax version:**

master c0a8d29

**Comment by mafiesto4** [comment]
Fixed in 930b1b978cad606c4db54230015fd0cd3f07d375,
