### ISSUE TITLE
C# api is missing quaternion FindBetween series of functions from C++ api

### ISSUE THREAD

**Issue by SinnersSum** [FlaxEngine/FlaxEngine#1885]
The very useful [FindBetween](https://github.com/FlaxEngine/FlaxEngine/blob/c025b4414cf6ff67d7bce6f9dbd93ccc07d2b36d/Source/Engine/Core/Math/Quaternion.h#L579) quaternion function is implemented in the C++ api, but is missing from the C# api.

For naming consistency with the rest of the quaternion api it might appropriate to add it as `RotationBetween` to the C# api.

**Comment by mafiesto4** [comment]
Added in 11b60390b6caddf9d26da581473a2448b8465936
