### ISSUE TITLE
Cannot Create Actor Through Scripts

### ISSUE THREAD

**Issue by AshtonK5** [FlaxEngine/FlaxEngine#1889]
**Issue description:**

So when I tried to make a custom actor through C# and C++ It didn't let me drag It Into the Scene
![Screenshot 2023-11-01 230535](https://github.com/FlaxEngine/FlaxEngine/assets/53506112/f87f7574-724e-47c4-8848-e42e636de081)
![Screenshot 2023-11-07 020036](https://github.com/FlaxEngine/FlaxEngine/assets/53506112/0b4b70ca-ad17-404e-a6a0-d3c07bc64d9d)
![Screenshot 2023-11-07 020122](https://github.com/FlaxEngine/FlaxEngine/assets/53506112/8e1a926f-a230-450c-80d4-2fb3f3e15e8f)
![Screenshot 2023-11-07 020139](https://github.com/FlaxEngine/FlaxEngine/assets/53506112/5faeb675-1e7d-4552-9e95-d6c0a1f99734)
![Screenshot 2023-11-07 020146](https://github.com/FlaxEngine/FlaxEngine/assets/53506112/ab488244-1bcf-449e-9568-f58b8e1aa17c)

https://github.com/FlaxEngine/FlaxEngine/assets/53506112/f16bcee6-e950-4f17-bc86-e54f732bf3ad
( HAD TO DOWNSCALE RES AND SPEED UP )

**Flax version:**

( FLAX 1.7 )

**Comment by MineBill** [comment]
You can't drag an actor script in the hierarchy to create a new actor. You need to use the [ActorContextMenu](https://docs.flaxengine.com/api/FlaxEngine.ActorContextMenuAttribute.html) to allow you to create this new actor from either the scene hierarchy or the toolbox. [Here](https://github.com/FlaxEngine/FlaxEngine/blob/4fdeb773a5a6dcf758ddb021d2dc11b073e9f903/Source/Engine/Physics/Colliders/CapsuleCollider.h#L13) is an example of how to do this in C++ and here is for C#:
```cs
[ActorContextMenu("New/My Actor")]
public class MyActor : Actor
{
...
}
```

**Comment by AshtonK5** [comment]
> You can't drag an actor script in the hierarchy to create a new actor. You need to use the [ActorContextMenu](https://docs.flaxengine.com/api/FlaxEngine.ActorContextMenuAttribute.html) to allow you to create this new actor from either the scene hierarchy or the toolbox. [Here](https://github.com/FlaxEngine/FlaxEngine/blob/4fdeb773a5a6dcf758ddb021d2dc11b073e9f903/Source/Engine/Physics/Colliders/CapsuleCollider.h#L13) is an example of how to do this in C++ and here is for C#:
> 
> ```cs
> [ActorContextMenu("New/My Actor")]
> public class MyActor : Actor
> {
> ...
> }
> ```
> 
> For future reference, JsonAssets and other custom assets can be similarly created using the [ContentContextMenu](https://docs.flaxengine.com/api/FlaxEngine.ContentContextMenuAttribute.html) attribute.

O Weird because I tried it in both C# and C++ and It Still Doesn't work for me do I got to reinstall the engine? I Also built from my IDE and It Still Doesn't Work

**Comment by AshtonK5** [comment]
> > You can't drag an actor script in the hierarchy to create a new actor. You need to use the [ActorContextMenu](https://docs.flaxengine.com/api/FlaxEngine.ActorContextMenuAttribute.html) to allow you to create this new actor from either the scene hierarchy or the toolbox. [Here](https://github.com/FlaxEngine/FlaxEngine/blob/4fdeb773a5a6dcf758ddb021d2dc11b073e9f903/Source/Engine/Physics/Colliders/CapsuleCollider.h#L13) is an example of how to do this in C++ and here is for C#:
> > ```cs
> > [ActorContextMenu("New/My Actor")]
> > public class MyActor : Actor
> > {
> > ...
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > For future reference, JsonAssets and other custom assets can be similarly created using the [ContentContextMenu](https://docs.flaxengine.com/api/FlaxEngine.ContentContextMenuAttribute.html) attribute.
> 
> O Weird because I tried it in both C# and C++ and It Still Doesn't work for me do I got to reinstall the engine? I Also built from my IDE and It Still Doesn't Work

Also Before you even add that tag on the tutorial page It just says you can drag It Into the Scene Without adding Tags or anything ( on doc page ) "The next step is to drahg&drop actor from Content window into scene or scene tree." Before you even add attributes
