### ISSUE TITLE
Visual Script Editor Freeze 

### ISSUE THREAD

**Issue by Andre13187** [FlaxEngine/FlaxEngine#1890]
https://github.com/FlaxEngine/FlaxEngine/assets/150161010/2154fbd3-0bbc-4f58-a5bc-f48f81f91a14

I have attached a visual script to an object and when I edit and save the script the editor freezes. If the script is not attached, I can save as normal. It seems to be a bug in version 1.7. This error does not occur in version 1.6.

**Comment by mafiesto4** [comment]
Fixed in 1a7770fba2bad83f9c4285f1a0fa78aa8af37436.
