### ISSUE TITLE
AI Crowd System crash editor

### ISSUE THREAD

**Issue by RuanLucasGD** [FlaxEngine/FlaxEngine#1891]
**Issue description:**
If you have a crowd system and by some reason throw any error, the editor crash with out logs.

This happen if you don't have a NavMeshVolume or another error.

Try this code:
```
using System;
using FlaxEngine;

namespace Game;

public class CrowdPlugin : GamePlugin
{
    private NavCrowd _crowd;
    private CrowdTask _task;

    public void AddAgent(CrowdAgent agent)
    {
        if (!_task)
        {
            _crowd = new NavCrowd();
            _crowd.Init(500, 1000, null);
            _task = new CrowdTask(_crowd);
            Engine.UpdateGraph.AddSystem(_task);
        }

        Debug.Log("added");
    }

    public void RemoveAgent(CrowdAgent agent)
    {
        Debug.Log("removed");
    }
}

public class CrowdTask : TaskGraphSystem
{
    private NavCrowd _crowd;

    public CrowdTask(NavCrowd crowd)
    {
        _crowd = crowd;
    }

    public override void Execute(TaskGraph graph)
    {
        base.Execute(graph);
        _crowd.Update(Time.DeltaTime);
        throw new Exception();
    }
}

public class CrowdAgent : Script
{
    public override void OnEnable()
    {
        PluginManager.GetPlugin<CrowdPlugin>().AddAgent(this);
    }

    public override void OnDisable()
    {
        PluginManager.GetPlugin<CrowdPlugin>().RemoveAgent(this);
    }
}

```

I noticied another bug, if i have some errors, my hot-reload don't work, my code stop compile even if i delete all cache (the game works normal but any changes on code don't have effect) but i cannot reproduce it.

1. Try without navmesh.
2. Try with some exception (see CrowdTask.Execute)

**Flax version:**
1.7 master

**Comment by mafiesto4** [comment]
Have you had a crash with a debugger attached? Because if you have C# exception as in your example it stops the debugger so C# runtime can handle it - only the case when debugging C++ code only.

Also, in Editor you might want to clear crowd and task of the GamePlugin as you don't use `Deinitialize` method.

I can't reproduce those issues. This bug might be related to the problems mentioned above.

**Comment by RuanLucasGD** [comment]
@mafiesto4 disable debugger exception worked, thanks a lot
