### ISSUE TITLE
PhysX crash under specific circumstances with RigidBodies.

### ISSUE THREAD

**Issue by dch-GH** [FlaxEngine/FlaxEngine#1893]
**Issue description:**

Flax will crash if a RigidBody is destroyed during a collision with another RigidBody(?). I'm not sure.

A user error on my part from forgetting to set a threshold for deletion led me to this crash. I was doing a distance check to delete an Actor if it strayed to far from its starting position and forgot to set the required distance in the inspector. I was unable to reproduce this crash by trying to delete in OnStart, or with no conditional in OnFixedUpdate, or Destroy with a small time argument passed in.

Important info from log file:
```
[ 00:04:50.819 ]: [Error] Critical error! Reason: Unhandled exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0
[ 00:04:50.949 ]: [Error] Stack trace:
[ 00:04:50.949 ]: [Error]     at FlaxEditor.exe!SimulationEventCallback::SendCollisionEvents() in F:\FlaxEngine\Source\Engine\Physics\PhysX\SimulationEventCallbackPhysX.cpp:line 49
[ 00:04:50.949 ]: [Error]     at FlaxEditor.exe!PhysicsBackend::EndSimulateScene() in F:\FlaxEngine\Source\Engine\Physics\PhysX\PhysicsBackendPhysX.cpp:line 1739
[ 00:04:50.949 ]: [Error]     at FlaxEditor.exe!Physics::CollectResults() in F:\FlaxEngine\Source\Engine\Physics\Physics.cpp:line 207
[ 00:04:50.949 ]: [Error]     at FlaxEditor.exe!Engine::Main() in F:\FlaxEngine\Source\Engine\Engine\Engine.cpp:line 165
[ 00:04:50.949 ]: [Error]     at FlaxEditor.exe!wWinMain() in F:\FlaxEngine\Source\Engine\Main\Windows\main.cpp:line 55
[ 00:04:50.949 ]: [Error]     at FlaxEditor.exe!__scrt_common_main_seh() in D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:line 288
[ 00:04:50.949 ]: [Error]     at KERNEL32.DLL 0x7ff9feba257d
[ 00:04:50.949 ]: [Error]     at ntdll.dll 0x7ff9fed6aa78
[ 00:04:50.949 ]: [Error] Used Physical Memory: 10.34 Gb (32%)
[ 00:04:50.949 ]: [Error] Used Virtual Memory: 263.87 Gb (0%)
[ 00:04:50.949 ]: [Error] Process Used Physical Memory: 333.96 Mb
[ 00:04:50.949 ]: [Error] Process Used Virtual Memory: 990.33 Mb
```
Line: https://github.com/FlaxEngine/FlaxEngine/blob/74bcf7d9e598be82635086570555b41cd85b9988/Source/Engine/Physics/PhysX/SimulationEventCallbackPhysX.cpp#L49

**Steps to reproduce:**
1. Create a simple RigidBody prefab.  Just a RigidBody and a collider of any kind will do. 
![image](https://github.com/FlaxEngine/FlaxEngine/assets/66768086/b228c86c-8059-4adb-9721-4a07d602a537)
2. Attach this script to the prefab's RigidBody:
```cs
using FlaxEngine;

namespace Game;

internal class TestScript : Script
{
    private Vector3 _startPos;

    public override void OnStart()
    {
        _startPos = Actor.Position;
    }

    public override void OnFixedUpdate()
    {
        var distance = Vector3.Distance(Actor.Position, _startPos);
        if (distance > 0)
            DestroyNow(Actor);
    }
}
```
2. Create new actor in the Scene and attach a script that spawns the two prefabs at the same location:
```cs
using FlaxEngine;

namespace Game;

internal class PrefabSpawnerScript : Script
{
    public Prefab Prefab;

    public override void OnStart()
    {
        PrefabManager.SpawnPrefab(Prefab, Vector3.One * 100);
        PrefabManager.SpawnPrefab(Prefab, Vector3.One * 100);
    }
}
```
3. Assign the TestPrefab you made to the script instance, and play the scene.
4. Crash because of a PhysX error.

**Minimal reproduction project:**

All of the above is pre-configured in the repro project, you just need to open and play the scene "Main" to crash.
[CrashRepro.zip](https://github.com/FlaxEngine/FlaxEngine/files/13289547/CrashRepro.zip)

**Flax version:**

Flax 1.7

**Comment by mafiesto4** [comment]
Fixed in 22c8ec53426543c1d8192c2bf5744c0bb37b384c.
