### ISSUE TITLE
Object Splitting not working if index is set on something other than -1.

### ISSUE THREAD

**Issue by d1kkop** [FlaxEngine/FlaxEngine#1894]
1. Import an .FBX model (with multiple meshes).
2. Go to object splitting. Enable it, and put starting index on 0 or 1.
3. Import.
4. Result: model not split.
5. Expected: model is split.

[TestModel](https://wetransfer.com/downloads/bc13720ae18120248d94bbb775e7cc5420231107001010/6775e4?utm_campaign=TRN_TDL_05&utm_source=sendgrid&utm_medium=email&trk=TRN_TDL_05)

While trying to demo this, it crashed on in the demo. 

[Demo with crash](https://wetransfer.com/downloads/7a662d3d5837d0178c6e91af314b074c20231108152525/a8807c3815ec82d350ccf4db3c557a7820231108152540/90c9ae?trk=TRN_TDL_01&utm_campaign=TRN_TDL_01&utm_medium=email&utm_source=sendgrid)
[Log.txt](https://github.com/FlaxEngine/FlaxEngine/files/13298478/Log.txt)

Flax 1.7

**Comment by mafiesto4** [comment]
Fixed in crash in 4ae57e7769d03899182a1a81b9c264934b8189a5 (most likely - repoen issue if it happens again in future)
