### ISSUE TITLE
Editor console log time is not local time.

### ISSUE THREAD

**Issue by d1kkop** [FlaxEngine/FlaxEngine#1895]
Minor, but just noticed.

![image](https://github.com/FlaxEngine/FlaxEngine/assets/10207653/077e3ebb-1748-48b4-916b-d5d05af5a426)

**Comment by Menotdan** [comment]
I believe the console log time is time since editor launch.

**Comment by MineBill** [comment]
![image](https://github.com/FlaxEngine/FlaxEngine/assets/30367251/a0d29301-0616-4c38-90b2-b8cca2aac6b4)

**Comment by Menotdan** [comment]
![image](https://github.com/FlaxEngine/FlaxEngine/assets/32620310/73114eeb-f105-4890-a4dc-974e290dd5b3)
I see

**Comment by d1kkop** [comment]
Ah ok, couldnt find that. Thank you.
