### ISSUE TITLE
[Suggestion] Support Multi-Editing for UI Control properties.

### ISSUE THREAD

**Issue by Menotdan** [FlaxEngine/FlaxEngine#1897]
**Issue description:**
It would be nice if we could select multiple UI controls and edit their properties. This could include things like the position or width/height, but, of course, there would have to be anchor type checks to make sure everything is supported. If you wanted to support more than just position you would also have to add a check for if the UI controls have all the same control type.

**Comment by Menotdan** [comment]
@mafiesto4 can this be added to 1.9? It's quite annoying to not be able to move multiple controls.

**Comment by mafiesto4** [comment]
I'm not sure if I will have time left for 1.9 but Flax contributors can pick it.

**Comment by mafiesto4** [comment]
Added in eb5dfcd6bf9f6254c90383aa6bd0ab96b059ef06.
