### ISSUE TITLE
FlaxEditor freezes when it starts compiling scripts

### ISSUE THREAD

**Issue by Crawcik** [FlaxEngine/FlaxEngine#19]
**Issue description:**
FlaxEditor freezes when it stats compiling script. It happens sometimes

**Steps to reproduce:**
I'm not sure, but try to save the C # file during compilation

**Flax version:**
1.0

**Comment by jb-perrier** [comment]
I cannot reproduce this freeze, can you post logs here when you're encountering this issue ?

**Comment by W2Wizard** [comment]
@Crawcik Any update ?
