### ISSUE TITLE
UI Vertical Panel Doesn't Update when Adding Children

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#190]
There's currently a bug in the system. 
Please see the attached video to understand what causes it.

Basically, If you have a vertical box with a button in it, then you add another button, the second button will appear on top of the first. The only way to make it lay out correctly is to press the "Play Game" button.

Link: https://drive.google.com/file/d/1o4x9wcU0N9Fn3SAIyxsaX4k1TJa-0vCk/view?usp=sharing

**Comment by honzapatCZ** [comment]
You can turn the parent off and on.
