### ISSUE TITLE
Terrain data files (Heightfield, Heightmap etc.) are not deleted when the terrain is deleted.

### ISSUE THREAD

**Issue by AlTheSlacker** [FlaxEngine/FlaxEngine#1902]
**Please search existing issues for potential duplicates before filing yours:**
No reference to heightmap found

**Issue description:**
Ref: https://forum.flaxengine.com/t/possible-bugs-terrain-issues/1443/1

After deleting a terrain from the scene the Heightfield.flax, Heightmap.flax and (by a report in the referenced forum thread) Splatmap0.flax remain in the Content/SceneData/Scene/Terrain folder. 

Expected behaviour: These files would be deleted with the terrain object.

**Steps to reproduce:**
Creating and deleting terrains in the scene leads to an accumulation of files in Content/SceneData/Scene/Terrain

**Minimal reproduction project:**
Not required, just new project, create/delete terrain.

**Flax version:**
1.7.6404, but was also apparent in 1.6

**Comment by mafiesto4** [comment]
Added in fc66738dca3edbbc55f0069c70e1965f27aa3b35. Now, those files will be removed if the terrain is not used anymore on editor shutdown.
