### ISSUE TITLE
[Visject] Unpack Float3 appears to return `null` (at least after Get EulerAngles)

### ISSUE THREAD

**Issue by Menotdan** [FlaxEngine/FlaxEngine#1903]
**Issue description:**
When using the `Unpack Float3` node to unpack the output from an `Actor`'s `Get EulerAngles`, the outputs are null.

**Steps to reproduce:**
1. Create this visual script:
![image](https://github.com/FlaxEngine/FlaxEngine/assets/32620310/422a2a79-f17f-4f94-94c3-eb18bbb66abe)
2. Attach it to an object.
3. Enter playmode, and look at the debug log.

**Minimal reproduction project:**
[Test VS 1.zip](https://github.com/FlaxEngine/FlaxEngine/files/13309373/Test.VS.1.zip)

**Flax version:**
Launcher master branch as of the date of posting this. (1.7 and my custom build as well)

**Comment by Tryibion** [comment]
Some issue with unpacking variant structures.

**Comment by mafiesto4** [comment]
Fixed in 057d1fbcc681ecf0191006624261eb4221e4aaee.
