### ISSUE TITLE
UI Horizontal Panel is broken

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#191]
The Horizontal Panel is just broken for me. I can never get it to display anything correctly.

You can see a video of me struggling with the Horizontal Panel in this video:
https://drive.google.com/file/d/1w3BJSByhjwuYUWMUwHcYO2HvxH89b3sf/view?usp=sharing

**Comment by mafiesto4** [comment]
Fixed by https://github.com/FlaxEngine/FlaxEngine/commit/a572e581e5614da8a2a58a6c59ef2c8222b2daa9
