### ISSUE TITLE
Bindings add support for fields inside interface

### ISSUE THREAD

**Issue by NoriteSC** [FlaxEngine/FlaxEngine#1912]
**Issue description:**
u cant use API_FIELD() inside interface
but generated code C# for fields inside classes is valid code inside interface

rules of interface in c# u cant make 
object A;
but  
object A { get { internal call} set { internal call}};
is a valid code

**Comment by mafiesto4** [comment]
> u cant use API_FIELD() inside interface

This kind of is the base design of interfaces. They don't provide content but just schematic of API.

**Comment by NoriteSC** [comment]
cant be done
