### ISSUE TITLE
When creating a prefab from an actor in a scene, the scene is not marked dirty.

### ISSUE THREAD

**Issue by Menotdan** [FlaxEngine/FlaxEngine#1916]
**Issue description:**
When you drag and drop an actor into the content window to create a new prefab from an actor, it does not mark the scene dirty after creating the prefab link. This means the prefab link is lost if you make no other changes to your scene.

**Steps to reproduce:**
1. Find any actor in the scene
2. Drag it into the content window
3. Close flax (notice there is no "do you want to save the scene" warning)
4. Open it, and the prefab link is gone.

**Flax version:**
Launcher 1.7 at least

**Comment by SinnersSum** [comment]
I've noticed this too. There also seems to be an issue actually creating the link between the scene objects and the new prefab; I had model in a prefab revert after saving it.

**Comment by mafiesto4** [comment]
Fixed in 31ce41c5a4ee8469d3895a68c0b4b44abf43f8cd.
