### ISSUE TITLE
Invert mouse Y-axis option for editor viewport camera

### ISSUE THREAD

**Issue by GoaLitiuM** [FlaxEngine/FlaxEngine#1918]
Add option to invert the camera Y-rotation to Editor options for the viewport camera (maybe under the Mouse Sensitivity options?).

**Comment by mafiesto4** [comment]
**Invert Panning** setting in Editor Viewport options?

**Comment by NoriteSC** [comment]
> **Invert Panning** setting in Editor Viewport options?

nope invert mouse Y axis 
so down is up 
and 
up is down 
while rotating the camera
