### ISSUE TITLE
[LINUX BUG] Exception when exiting game mode

### ISSUE THREAD

**Issue by TiToMoskito** [FlaxEngine/FlaxEngine#1920]
**Issue Description:**
When I start and then exit the Menu Scene, there are no issues.
However, starting and then exiting the Main Scene triggers an assertion fail. I've attached a screenshot for reference. The error appears to be related to an object that is trying to execute Game.ExitOnEsc (or something similar—I'm unable to find the exact variable now).

![Screenshot_20231110_232314](https://github.com/FlaxEngine/FlaxEngine/assets/7590208/ea16c1e4-4af3-4459-a77e-c803603387b1)

**Steps to Reproduce:**
Start the ArizonaFramework sample on a Linux (Arch) system.
Navigate to and start the Main Scene.
Attempt to exit the Main Scene.

**Expected Behavior:**
The Main Scene should close without any assertion fails or exceptions, as it does when running the Menu Scene.

**Actual Behavior:**
An assertion fail is thrown when attempting to exit the Main Scene. (Refer to the attached screenshot for the specific error message).

**Additional Information:**
This issue does not occur on a Windows system, as tested by a colleague. The application runs and exits as expected on Windows, which leads me to believe this might be a Linux-specific problem.
I would appreciate any guidance or suggestions on how to resolve this issue. Thank you for your time and assistance.

**Flax version:**
Latest master branch

**Comment by TiToMoskito** [comment]
I just bought Rider and used the Debugger, here are the results, maybe this helps you.
![callstack_1](https://github.com/FlaxEngine/FlaxEngine/assets/7590208/a252b105-6bbf-4273-ab62-9709e37cd3ef)
![callstack_2](https://github.com/FlaxEngine/FlaxEngine/assets/7590208/02ec2b78-ddb9-463a-b489-fd341babc4ef)

**Comment by apo-egix** [comment]
We tried debugging, but it seems neither Visual Studio Code nor JB Rider can debug .Net and C++ stuff at the same time. What we figured so far is that stopping playmode in the editor triggers Level::UnloadAllScenes() which in turn tirggers the Destructors of all Actors, which again starts calling all delegates. One of those seems to be (unfortunatly my knowledge is non existent, since i started using it yesterday) ScriptingObjectReferenceBase::OnDeleted. Checking the debug data we can see that _obj seems to be (at least with the current setup) the PlayerController (from ArizonaFramework). Now we encountered that _object of ScriptingObjectReferenceBase is either 0x0 or something completly different but seemingly already deleted, which causes an ASSERT which again eventually calls Engine::Exit(-1). This in turn tries to unload the Scene again (which of course can't work since stuff is already half way gone).

On windows it runs fine and my personal assumption is that either some platform-specific stuff on the c# side is causing it OR there is a bug in .Net core for linux

**Comment by TiToMoskito** [comment]
We attempted to apply a 'hotfix' to the ASSERT part in Scripting.cpp to investigate a potential memory leak. Here's the change we made:
`void ScriptingObjectReferenceBase::OnDeleted(ScriptingObject* obj)
{
    //ASSERT(_object == obj);
    if(_object != obj)
    {
        LOG(Warning, "[ScriptingObjectReferenceBase::OnDeleted] Assertion fail. Custom Bug Fix for Linux Platform");
        return;        
    }
    ....
}
`
This is the output log in the editor:
[Log_2023_11_12_14_40_59.txt](https://github.com/FlaxEngine/FlaxEngine/files/13328166/Log_2023_11_12_14_40_59.txt)

This resulted in some errors such as: 'Objects registry already contains an object with ...'
And every time I re-enter the game mode, the errors multiply.

I hope this information helps you identify the bug.

**Comment by TiToMoskito** [comment]
After further testing, I realized that when I enable USE_OBJECTS_DISPOSE_CRASHES_DEBUGGING in Scripting.cpp, everything works fine.

**Comment by mafiesto4** [comment]
Would you mind testing with the latest master?

**Comment by TiToMoskito** [comment]
The assertion fail still exists.
[Log_2023_11_14_10_01_41.txt](https://github.com/FlaxEngine/FlaxEngine/files/13346740/Log_2023_11_14_10_01_41.txt)

**Comment by apo-egix** [comment]
After further testing with the current master branch, we encountered a strange phenomenon. If you look at the provided screenshot, you'll quickly see that ScriptingObject::_object is 0x200000000, which is highly unlikely. The incoming parameter obj seems to stay the same, but ScriptingObject::_object is changing from execution to execution
![2023-11-15_13-27](https://github.com/FlaxEngine/FlaxEngine/assets/16270939/c46d2a1a-f9ec-430f-ad52-bb15cd6c3a7e)

Maybe a racing condition? might also be a problem with memory alignment in unix, but that should have caused other problems before.

**Comment by apo-egix** [comment]
We tried to figure out who sets ScriptingObjectReferenceBase::_object to 0x200000000 and set a conditional breakingpoint.
**It did NOT hit**
So something is setting its value **without** calling ScriptingObjectReferenceBase::OnSet(...).
I guess that means a memory alignment issue, or some module goes rouge and changes raw pointers

See pic attached
![image](https://github.com/FlaxEngine/FlaxEngine/assets/16270939/b971a2d8-c985-4b33-a68f-abf9d1ebb844)

**Comment by Menotdan** [comment]
> We tried to figure out who sets ScriptingObjectReferenceBase::_object to 0x200000000 and set a conditional breakingpoint.
> **It did NOT hit**
> So something is setting its value **without** calling ScriptingObjectReferenceBase::OnSet(...).
> I guess that means a memory alignment issue, or some module goes rouge and changes raw pointers

If you can figure out how, you should set a watchpoint on the variable maybe.. but I'm not sure how to start with that especially since you said you couldn't even gey the debugger up.

**Comment by mafiesto4** [comment]
I fixed important issue in allocators in 4f8aff4352745bc86bb9e9c0a7cc6604cf7e6b7a which might fix this problem as I've managed to get sth similar with events/delegates.

**Comment by mafiesto4** [comment]
I'm not sure the exact cause of it - probably will need to run some address sanitizer or other tool to debug memory access on Linux. I did quick fix in: 84d3103278ccd79b4da5839d8b39bd4ce061fafc
