### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION Crash after opening first time

### ISSUE THREAD

**Issue by getmyisland** [FlaxEngine/FlaxEngine#1921]
**Issue description:**
After cloning the ArizonaFrameworkSample and opening it in Flax the following Error appears and crashes the engine after pressing OK.

![image](https://github.com/FlaxEngine/ArizonaFrameworkSample/assets/92424965/6cc26e5c-e59b-4b95-82b6-f5b8e9124b9b)

After restarting Flax and opening the project the error doesn't appear again.

I freshly installed the project 2 times to make sure it wasn't bad luck but it happened both times. This isn't a huge issue but nice to know I guess.

Contents of `Logs/Crash_2023_11_10_13_05_00`
[Log.txt](https://github.com/FlaxEngine/FlaxEngine/files/13319092/Log.txt)
[Minidump.dmp](https://github.com/FlaxEngine/FlaxEngine/files/13319094/Minidump.dmp)

**Steps to reproduce:**
1. Follow the [Installation](https://github.com/FlaxEngine/ArizonaFrameworkSample#installation) tutorial
2. After opening the project in Flax it should instantly show the Error and crash after

**Flax version:**
Flax_master (10/11/2023)

**Comment by mafiesto4** [comment]
I'm pretty sure that's an issue related to C++ and our build system which didn't properly rebuild after recent changes to core headers like `Dictionary.h`. Could you perform full recompilation of the engine?

**Comment by getmyisland** [comment]
I cloned the repository from GitHub and build it using Visual Studio 22. No problems and it works fine.
