### ISSUE TITLE
Adding/Removing 2 Entries of a List in Properties window collapses the Group

### ISSUE THREAD

**Issue by schmidt-florian** [FlaxEngine/FlaxEngine#1926]
**Issue description:**
If you add or remove 2 entries in a row from a list in the properties window it will collapse the list.

https://github.com/FlaxEngine/FlaxEngine/assets/14238126/c336e6f6-5e49-47e7-b2ac-fee9ca2e303c

**Steps to reproduce:**
Have a list field. Add/Remove 2 entries and it will collapse.

**Flax version:**
master 1.7.6404

**Comment by MineBill** [comment]
Are you sure you are on the latest master? This should've been fixed in ddaa5f9161fceb4c1120a49fa434e8668605c919.

**Comment by schmidt-florian** [comment]
No i am not the latest master. I am currently using the launcher master and I updated 2 days ago. I will update and take a look.
