### ISSUE TITLE
StopSlotAnimation bug

### ISSUE THREAD

**Issue by alcoranpaul** [FlaxEngine/FlaxEngine#1927]
**Issue description:**
Using Stop slot animation to interrupt currently playing animation clip on animation default slot does not restart duration of new clip being played. It is rather playing at the previous animation's last duration.
- Say 1st animation was played till half then the next animation will start from that time rather than from the beginning.

**Expectation**
- If Stop slot animation is called it will interrupt the currently, if any animation is playing, animation on default slot and plays from the start of the new animation.

**Steps to reproduce:**
- Using Thirdperson Template, and character script. Add the following code below.
- 2 animations to be played on animation default slot
```csharp
 public override void OnUpdate(){
            if (Input.Mouse.GetButtonDown(MouseButton.Left))
            {
                if (animModel.IsPlayingSlotAnimation())
                {
                    Debug.Log("Animation playing");
                    animModel.StopSlotAnimation("Default", prevAttack);
                }
                animModel.PlaySlotAnimation("Default", attacks[numIndex], speedTest, 0.2f, 0.2f);
                prevAttack = attacks[numIndex];

                numIndex++;
                if (numIndex >= attacks.Length)
                {
                    numIndex = 0;
                }
            }
}
```

https://github.com/FlaxEngine/FlaxEngine/assets/67833935/cf91d7c6-2139-4c9e-91f5-eac210a2ee1a

**Flax version:**
1.7 - Master

**Comment by mafiesto4** [comment]
Fixed in b6337c748c25f91c195ea7aa1825facab7637e7d.
