### ISSUE TITLE
UI Vertical Panel + Spacer has a bug

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#193]
This issue might be related to the other issues I posted. 
All my issues seem to be related to the system having issues figuring out the size of the viewport and updating appropriately. I'm not sure if this should be rolled into the other tasks.

**The problem:**
Vertical Panel doesn't fill the entire screen when a Spacer is Used. 

You can see a video of this here: 
https://drive.google.com/file/d/1tjKf7Mc7vG-aYaND9FBtRBPPd-juk5_y/view?usp=sharing

**Comment by mafiesto4** [comment]
Okay so the problem with layout not updated when adding controls is already fixed but the case of spacer not filling the entire area is a different thing.

Basically, the vertical panel won't stretch the Spacer as it's not how it supposed to work (it stretches controls width and places them one after another vertically with preservation of controls height). If you want to align the second button to the bottom edge use anchor docking:
![image](https://user-images.githubusercontent.com/3464853/111466111-2a680f80-8723-11eb-936d-e7ef456133d8.png)

Is it correct solution for you?

**Comment by honzapatCZ** [comment]
I suppose this is resolved......
