### ISSUE TITLE
FlaxEditor runs in an endless loop reporting an exception in Window.OnDraw

### ISSUE THREAD

**Issue by nothingTVatYT** [FlaxEngine/FlaxEngine#1932]
**Issue description:**
On reloading the scripts the Flax editor was unresponsive and had to be killed because according to the log it ran in an endless loop reporting an exception.

After killing the editor and restarting the script reloading worked again.

This is a shortened log file. The actual one is 45 MB but the section starting with the warning repeats over and over again.

[Log_2023_11_14_23_59_03.txt](https://github.com/FlaxEngine/FlaxEngine/files/13343619/Log_2023_11_14_23_59_03.txt)

**Flax version:**
1.7 (git master)

**Comment by mafiesto4** [comment]
Fixed in c0f0bd87aa8a1c5efca38d90a1df1154f26b449e.
