### ISSUE TITLE
Raycast on Character Controller don't work correctly

### ISSUE THREAD

**Issue by RuanLucasGD** [FlaxEngine/FlaxEngine#1935]
**Issue description:**
Raycast on character controllers are not very precise, some times don't detect with different Character radius 

**Steps to reproduce:**
See the console, needs to print Raycast hit collider name, but even if the ray is intersecting the character, the raycast don't works fine.

https://github.com/FlaxEngine/FlaxEngine/assets/79365912/7c9d25f9-9856-4cd9-8eb4-305b1c415ab0

**Minimal reproduction project:**
[ThirdPersonShooterTemplate.zip](https://github.com/FlaxEngine/FlaxEngine/files/13349063/ThirdPersonShooterTemplate.zip)

**Flax version:**
1.7 master

**Comment by MineBill** [comment]
Can confirm, it's not an issue with normalization of the direction vector of the ray.

**Comment by envision3d** [comment]
In at least some situations, I think an issue is present when you make a prefab from a CharacterController with a non-standard center offset on the collider.  I think there may be an order of operations issue with when the center offset is applied.

When I spawn a prefab with a modified center offset, I see issues with where the engine thinks the collider is.  Separately, if I manually add a CharacterController into a scene and then change the values on the collider, the issue doesn't occur.

**Comment by mafiesto4** [comment]
That's how PhysX Character Controller is implemented. It uses a special area around the collider which cannot be properly hit with raycast:

![image](https://github.com/FlaxEngine/FlaxEngine/assets/3464853/713b44e2-da19-41b1-a343-acf2d1a3d3e0)

More docs: https://nvidia-omniverse.github.io/PhysX/physx/5.3.1/docs/CharacterControllers.html

FYI: It works the same in Unity:

https://github.com/FlaxEngine/FlaxEngine/assets/3464853/c093ed03-4234-46eb-b938-b2b139dd70d5
