### ISSUE TITLE
NetworkPeer Listen() function Fails on Occupied Port, Causing Editor Crash

### ISSUE THREAD

**Issue by KyuubiYoru** [FlaxEngine/FlaxEngine#1937]
**Issue description:**
When the Listen() function on NetworkPeer is invoked on a port already in use, the editor crashes. According to the function's description, which states "Returns: True when succeeded," it should return 'False' when it fails.

![image](https://github.com/FlaxEngine/FlaxEngine/assets/33806787/04b04828-4456-442b-bba0-6f84d1b693ca)

**Flax version:**
Master branch as of 14.11.2023

**Comment by mafiesto4** [comment]
Seams to be fixed on the latest master.
