### ISSUE TITLE
[Launcher] If master updated failed, unable to do it again.

### ISSUE THREAD

**Issue by schmidt-florian** [FlaxEngine/FlaxEngine#1939]
**Issue description:**
If for whatever reason the master update fails, you can not start it again the update fails because it tries to remove the master folder which is already removed.

After restarting the Launcher i can start the update of course without errors. But i need to select the location again.

**Steps to reproduce:**
1. start update master
2. disconnect network
3. Wait for fail
4. connect network
5. try start updating master

**Comment by mafiesto4** [comment]
Fixed for the next engine update to use smaller timeout (`60s`) and use new engine installation path based on the launcher path or currently selected engine version path which should improve the workflow.

Also, it works fine to me after timeout and I can retry downloading Github master build.
