### ISSUE TITLE
[Linux] Opening project issue with ImGui 

### ISSUE THREAD

**Issue by TiToMoskito** [FlaxEngine/FlaxEngine#1941]
It's not possible to load the project on Linux (Distro: Arch). Another person with Fedora has the same issue. Here is the attached log:

[Log_2023_11_15_10_20_20.txt](https://github.com/FlaxEngine/ArizonaFrameworkSample/files/13362802/Log_2023_11_15_10_20_20.txt)

FlaxEngine: Latest master from 14.11.2023

**Comment by mafiesto4** [comment]
Fixed in 2175f46a10b260eed4f961a88a5d9dcf5cf0a74a.
