### ISSUE TITLE
GPU Particles not visible or spawning at heightened positions.

### ISSUE THREAD

**Issue by buzzdx** [FlaxEngine/FlaxEngine#1944]
Description:

It seems that GPU particles with world coordinate system do either not spawn correctly or get not drawn correctly when the particle system is placed at a higher spot. Note however that the y-position alone is not the reason as there are places where, despite being higher, they still show.

Reproduction:

I could reproduce this behaviour in the Particle Demo level. I moved up the whole scene by around 1200. After that i checked the smoke particle system. On the original spot in the level, you can see both the smoke and the little spark particles flying upwards.

Then i placed that same particle system on another spot, and the little sparks are gone. For some reason it does not affect the smoke although they both use GPU and world coordinates.

I've attached the modified particle demo so you can see for yourself.

[ParticlesFeaturesTour.zip](https://github.com/FlaxEngine/FlaxEngine/files/13376689/ParticlesFeaturesTour.zip)

Another note: By turning the particles to CPU particles, they get drawn normally. Keeping them GPU particles but using local coordinates instead of world coordinates, also shows them normally, but that's probably because using local coordinates makes it so they are not on a higher spot, at least internally.

Version:

Version 1.7.6404

**Comment by mafiesto4** [comment]
Fixed in 0b3835f593e7bf3c063442fe5cdb2969ff994942.
