### ISSUE TITLE
Missing Check for Mouse over GUI

### ISSUE THREAD

**Issue by schmidt-florian** [FlaxEngine/FlaxEngine#1952]
**Issue description:**

I need to disable my interaction with the world if the mouse is over the GUI. (RTS Style game)
The only way i found is `Canvas.GUI.IsMouseOver` and this returns always true, probably because the Cursor is always inside the UI Root element. A function is missing that checks only for elements that are visible for the player (Colors, Textures etc). Or we need a way to disable the mouse over check for certain, layout only ui controls so we can check from the root object if the current pointer position hits any valid controls and not layout controls that are invisible to the player or are invisible to the method by disabling "raycast hit" option or something like that.

**Flax version:**
any

**Comment by mafiesto4** [comment]
Maybe we should add a generic utility function to raycast UI?
