### ISSUE TITLE
Weird UI logic in graphic settings

### ISSUE THREAD

**Issue by HydrogenC** [FlaxEngine/FlaxEngine#1954]
**Issue description:**
I've noticed that there are a checkbox in the left of every option in the graphics settings editor panel. It's somehow confusing and I can't understand how it makes sense. Take Bloom as an example, the checkbox left to Enabled is obviously redundant. Moreover, since the `Threshhold` value is required for the bloom effect, if I enable the effect and uncheck the checkbox next to `Threshhold`, then which threshhold value will it use? The default value? If so, why do we need the checkbox? Only those values that are truly "optional" should have those checkboxes. 

![微信图片_20231118181707](https://github.com/FlaxEngine/FlaxEngine/assets/33123710/949c02b5-5327-4a37-97cb-1d0ff4bff03d)

**Steps to reproduce:**
N/A

**Minimal reproduction project:**
N/A

**Flax version:**
1.7

**Comment by Menotdan** [comment]
The checkboxes on the left create an override of the default settings, and the settings on the right are the overridden values. This is important because if you have many PostFX volumes (lets you change postfx based on camera location), you only want to override some postFX settings.

**Comment by mafiesto4** [comment]
PostFX settings are very large and usually, games tend to use some layering system for this. For example, there are engine-default values specified in Flax, then game ca setup own project-defaults in Graphics Settings, then level can override specific options per area or per-camera via PostFx Volume, finally game scripts can inject custom overrides too from code. This accounts for very scalable system where editing a single property or set of properties doesn't interfere with other options cofnigred elsewhere.

**Comment by HydrogenC** [comment]
Thanks for your explanation!
