### ISSUE TITLE
[Suggestion] Fullscreen for Game View

### ISSUE THREAD

**Issue by Myterian** [FlaxEngine/FlaxEngine#1957]
I think it's helpful to preview the game in fullscreen in the editor, since this can help adjusting cameras position, UI size and scaling and some post processing effects like vignette. 

Also, a game in fullscreen comes across / feels different than in maximized window and that has to be taken into account during developent as well.

**Comment by MineBill** [comment]
When in play mode, try pressing F11. That should maximize the Game window.

**Comment by Myterian** [comment]
yeah, I'm almost always using that. But I'm talking about proper fullscreen, so you can play the game like a player would do. Actually, borderless window would already be enough

**Comment by mafiesto4** [comment]
Implemented in #2116
