### ISSUE TITLE
Copying structs will make it share IDs

### ISSUE THREAD

**Issue by Bits360** [FlaxEngine/FlaxEngine#1959]
**Issue description:**
When you press + to add a struct, if it said struct an array that references a prefab, said array will share IDs, causing both to be edited. This is annoying

**Flax version:**
1.7

**Comment by mafiesto4** [comment]
Could you post an example code of such a script?

**Comment by Bits360** [comment]
public struct ArrayStruct{
      public Prefab[] BuggedArray;
   }
   public ArrayStruct[] StructArray;

This, copied inside a script is the smallest example. Create 1 index of StructArray, fill out BuggedArray with anything, Press + to add a new index on StructArray, the BuggedArray on index 2 will copy index 1 and vice versa whenever you change either.

**Comment by mafiesto4** [comment]
That's a feature of the Editor to duplicate the last array item value.

**Comment by Bits360** [comment]
@mafiesto4 This is a bug because it copies all changes across 2 variables, forcing you to remake the array.

**Comment by mafiesto4** [comment]
Fixed in bbe08be462ee66b8c55594d20360b0284eef66f4.
