### ISSUE TITLE
Grid passes through transparent material in the Editor

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#196]
This is a minor bug.

If you have a transparent material and set the Opacity to 1 the grid passes through the material in the editor.
![image](https://user-images.githubusercontent.com/35228400/106548969-1ba70e00-6564-11eb-9b13-1a6ada846da9.png)

Here you can see the grid passing through the material.
![image](https://user-images.githubusercontent.com/35228400/106548889-f4e8d780-6563-11eb-9092-71b52e4263bc.png)

**Comment by mafiesto4** [comment]
Fixed in 64a7985376109c646fd9b38d6d01a7df4364b278
