### ISSUE TITLE
Preview in Material Editor shows sky texture instead of the edited one

### ISSUE THREAD

**Issue by nothingTVatYT** [FlaxEngine/FlaxEngine#1965]
**Issue description:**
While the preview in the material editor usually shows the edited material once in a while it decides to show the sky texture instead. From the first instance of this error on you cannot preview any material anymore until the editor is closed and the cache folder removed.

This happens frequently on Linux/KDE (X11).

![Screenshot_BarkMaterial_2](https://github.com/FlaxEngine/FlaxEngine/assets/34131388/7a03f95d-bee4-4240-8926-7ffcdf5433ab)

**Flax version:**
1.7.6405 (git master)

**Comment by mrunion** [comment]
I had this happen for the first time today. I am on a Mac M1 running Sonoma (latest) on Flax 1.7.6404 (the DMG download for Apple Silicon for Flax 1.7).

I removed all files in the ./Cache/Shaders/Cache/VK_SM5 folder (it was the only folder in the Shaders/Cache/Shaders path with files in it) to see if that worked and it didn't. I removed the entire Cache folder in the project folder and restart Flax and the preview returned.

**Comment by mafiesto4** [comment]
Anything in the Log file? Maybe shaders are still compiling, or more likely an error in Editor code.

**Comment by nothingTVatYT** [comment]
The last time I checked there was neither an error nor a warning regarding shader and/or vulkan related. Although I think it's no surprise that both mrunion and me are on non-Windows platform. That could point to the renderer, right?

**Comment by nothingTVatYT** [comment]
Even after removing the Cache directory there is no preview anymore. It always looks like this:
![Screenshot_34](https://github.com/FlaxEngine/FlaxEngine/assets/34131388/80632e07-db8e-4c28-b1f6-b15e44156b0b)

[Log_2023_12_16_07_07_25.txt](https://github.com/FlaxEngine/FlaxEngine/files/13691571/Log_2023_12_16_07_07_25.txt)

**Comment by nothingTVatYT** [comment]
I just created a new project, waited a bit until there was nothing new reported in the logs (i.e. shader compilation should be completed) and created a new material. The preview worked.
Then I created a new scene and without any changes to it went back and created another material. The preview is showing the sky instead of the default sphere.
So, maybe it's not a shader or cache issue?

Here is the log: [Log_2023_12_16_08_12_37.txt](https://github.com/FlaxEngine/FlaxEngine/files/13691691/Log_2023_12_16_08_12_37.txt)

**Comment by Zaya6** [comment]
This is something I'm getting for all asset previews, whether it's a model or a material. Can confirm deleting cache works most of the time, but around 10 minutes later it happens again. This is really starting disrupt my workflow. I get it, this engine is still pretty fresh but it would be cool to get a menu option to rebuild the cache. Based on what I've heard on the discord there's quite a few people this is happening to and it would at least make it less painful while a solution is being formulated.

**Comment by nothingTVatYT** [comment]
Yeah! Today the preview came back!
So that's how the material editor should look like? ;-)
