### ISSUE TITLE
Crash when saving prefab sometimes

### ISSUE THREAD

**Issue by lifeformed** [FlaxEngine/FlaxEngine#1967]
Sometimes I get this when saving a prefab:
![image](https://github.com/FlaxEngine/FlaxEngine/assets/1567199/92c90cf8-09ca-428a-b35b-ae797a151d30)

I'll be playing the scene, then stop running it, and then make a change and save in the editor.  It gives that error even though it's no longer in play mode.

**Comment by mafiesto4** [comment]
Could you attach that prefab file or script it uses? It might be engine bug specifically related to your code (eg. spawning sub-objects inside prefab script).

**Comment by mafiesto4** [comment]
This was probably fixed in 075f40b93ab0624d04fcc9057e571231d110a226. Reopen with repro steps if it happens again with the latest `master` or next engine version.
