### ISSUE TITLE
Crash when using INetworkObject

### ISSUE THREAD

**Issue by lifeformed** [FlaxEngine/FlaxEngine#1969]
If I have something implement INetworkObject and try to spawn it with NetworkReplicator.Spawn, sometimes I get this error when I connect a client:
![image](https://github.com/FlaxEngine/FlaxEngine/assets/1567199/c046c13d-e739-4264-b870-df205b5f269a)
![image](https://github.com/FlaxEngine/FlaxEngine/assets/1567199/bacdf72d-c724-49ce-9a57-cea88f2a1f62)

**Comment by mafiesto4** [comment]
Does it happen in Editor? After hot-reload of code? Do you have any loose repro steps?

**Comment by lifeformed** [comment]
I haven't got this in a long time, so I'll close it.
