### ISSUE TITLE
Editor Properties Window: Fields With Very Large Numbers Stored in Floats or Doubles Are Buggy (C++)

### ISSUE THREAD

**Issue by intolerantape** [FlaxEngine/FlaxEngine#197]
The value of a script field sometimes changes unexpectedly when the Property Window input box corresponding to the field loses focus in the editor. The issue occurs when the following conditions are met:

A) The type of the field is float or double; and 
B) The value of the field was large enough to require scientific notation when the input box gained focus.

To reproduce the issue: 

1. Create a new empty C++ script. Give it a public field of type float or double (marked with API_FIELD(), of course). Initialize it to zero for the purpose of reproducing this issue.
2. Save the script.
3. Open the editor and place the new script on an empty actor. Select the actor.
4. In the Properties Window, select the input box for the field and enter a very large number. The number should be large enough to require scientific notation. On my machine, this means ([field] >= 1E+7) for floats and ([field] >= 1E+15) for doubles.
5. Hit enter to submit the new value to the field. The value in the field should change to scientific notation and correctly reflect the inputted value.
6. Select the input box again. This time do not change the value. Hit enter.
7. The value in the input box should change to a different number.

The issue occurs for the master branch in the github repo.

**Comment by mafiesto4** [comment]
Fixed with https://github.com/FlaxEngine/FlaxEngine/commit/e3142e640853b5c6cbd269c604946da000f45efb.
Added support for scientific (aka exponential) notation with https://github.com/FlaxEngine/FlaxEngine/commit/880a8c9f58044f0a6cee99638ac6074e53c84da8
