### ISSUE TITLE
Incosistent isometric rendering scale

### ISSUE THREAD

**Issue by RuanLucasGD** [FlaxEngine/FlaxEngine#1970]
**Issue description:**
Render scale if different for each resolution, see 1920x1080 to 2560x1440.
Maybe related with #1710

https://github.com/FlaxEngine/FlaxEngine/assets/79365912/35811c4c-bc94-4a66-b765-37682f4dcb14

**Steps to reproduce:**
* set camera to isometric
* change game screen resolution

**Minimal reproduction project:**
any

**Flax version:**
1.7 master

**Comment by mafiesto4** [comment]
Added in 73a596cb2f06c41f2ea49b4ea3ea1abe0621c977. Now you can specify the ortho projection size instead of using the one from the viewport size.
