### ISSUE TITLE
Trying to put an empty actor on the ground hangs the editor

### ISSUE THREAD

**Issue by nothingTVatYT** [FlaxEngine/FlaxEngine#1971]
**Issue description:**
When you select an empty actor in the scene tree and hit the End key the editor won't respond anymore.

There are no more entries in the log file, the editor just won't react to any keys or mouse actions.

**Flax version:**
1.7.6405 (git master)

**Comment by mafiesto4** [comment]
Fixed in d01990e3bb77bd7ee6158912f5883a2c2961f3f1.
