### ISSUE TITLE
Blend2d Crash 

### ISSUE THREAD

**Issue by Muzz** [FlaxEngine/FlaxEngine#1975]
**Issue description:**
Blend 2d when reloading animations, or interacting with the dots to drag, can throw this error.
![image](https://github.com/FlaxEngine/FlaxEngine/assets/2074204/cd88e0ab-6478-40c7-a5d0-7e52fc46058e)

I replicated it on two pc's using master, though someone else in the discord could not repro it. 

**Steps to reproduce:**

**Minimal reproduction project:**

[Anim_Bug_Repro.zip](https://github.com/FlaxEngine/FlaxEngine/files/13433575/Anim_Bug_Repro.zip)
Follow the steps in this video exactly. 

[animbug.webm](https://github.com/FlaxEngine/FlaxEngine/assets/2074204/30d83478-b123-4f30-b5da-71738cdd7cc6)

**Flax version:**
Master as of today

**Comment by Muzz** [comment]
Ok some further details. 

The nan error also will randomly fire when i'm playing with the dots in the editor. I can't find a rhyme or reason for it. 

Also the person yesterday that couldn't get the repro to fire, got it to fire by downloading master in flax launcher and following the steps. but when they compiled from source the bug was absent.

**Comment by mafiesto4** [comment]
Fixed in ea81ac6a7152af436ec7785c775fb04b0a1385f2.
