### ISSUE TITLE
Dragging prefab onto hierarchy doesn't mark scene dirty (when not dropping onto another actor)

### ISSUE THREAD

**Issue by Flavelius** [FlaxEngine/FlaxEngine#1976]
**Issue description:**

I dragged a prefab/model onto the scene hierarchy and clicked 'Save All'. After reopening flax/the scene, the model i dragged there was gone. I noticed that even though the instance appeared in the scene (-tree), the scene itself wasn't marked dirty, so the save function probably just skipped it.

https://github.com/FlaxEngine/FlaxEngine/assets/8841352/9ff82e58-8e92-4acb-a309-a748db8c1806

This doesn't happen when dragging the asset onto another actor (then the scene is correctly marked dirty)

**Steps to reproduce:**

Drag and drop a prefab onto the scene hierarchy panel without targeting an existing actor.
The instance will appear, but the scene will not be marked dirty.

**Minimal reproduction project:**

**Flax version:**

1.7 (downloaded via launcher)

**Comment by mafiesto4** [comment]
Fixed in fc2d9a745f12da8fb856199aa56733ca60a9fed8.
