### ISSUE TITLE
Flax Editor can no longer be started.

### ISSUE THREAD

**Issue by Andre13187** [FlaxEngine/FlaxEngine#1978]
![Screenshot (18)](https://github.com/FlaxEngine/FlaxEngine/assets/150161010/66285d65-e602-4344-8959-4ac9998c6478)

**Issue description:**
Since yesterday, Flax can no longer be started and crashes with the error message shown in the screenshot.

**Flax version:**
1.7_Master
22.11.2023
**Log**
[Log.txt](https://github.com/FlaxEngine/FlaxEngine/files/13441303/Log.txt)

**Comment by Menotdan** [comment]
This is a bug where CI builds happen with .net8, and flax looks for .net8 because of that. Hopefully fixed soon..

**Comment by Andre13187** [comment]
> This is a bug where CI builds happen with .net8, and flax looks for .net8 because of that. Hopefully fixed soon..

Thanks for the hint. I installed the .NET 8.0 SDK and updated Visual Studio to the latest version. The FlaxEditor can now be run again.
