### ISSUE TITLE
Flax Engine Editor froze when trying to compile C# script from Visual Studio 2019

### ISSUE THREAD

**Issue by kwalt95** [FlaxEngine/FlaxEngine#198]
**Issue description:**

**What happened:** Flax Engine Editor froze when trying to compile C# script from Visual Studio 2019 with only a few lines of code.
**What was expected:** Flax Engine compiling C# scripts from Visual Studio 2019 properly without freezing the editor.

**Steps to reproduce:**

- Open basic template.
- Make a C# script and open it in Visual Studio 2019.
- Write C# code in Visual Studio 2019 and save changes.
- Go back to Flax Engine. Compilation bar in the bottom right says the scripts are compiling, but the editor becomes unresponsive.

**Flax version:**

Version 1.0

**Comment by mafiesto4** [comment]
It was probably unresponsive when opening that script in Visual Studio due to VS stall. What was the exact delay in seconds?

**Comment by kwalt95** [comment]
> It was probably unresponsive when opening that script in Visual Studio due to VS stall. What was the exact delay in seconds?

Unfortunately, I don't recall the exact delay. Would that be recorded in the output logs? I'm not close to my computer at the moment, but I'll repeat the steps mentioned a few or more times and get back with an update within the next 12 hours.

**Comment by kwalt95** [comment]
I reinstalled Flax, and now, unfortunately, the editor won't launch.

**Comment by kwalt95** [comment]
I couldn't seem to reproduce the issue. Perhaps it was an issue on my end.

**Comment by mafiesto4** [comment]
Ok, if it happens again feel free to reopen this issue and share the log so we could investigate it 👍
