### ISSUE TITLE
Editor crash when compiling multiple generic uses of a generic interface 

### ISSUE THREAD

**Issue by lifeformed** [FlaxEngine/FlaxEngine#1983]
This script crashes the editor for me when I compile:

```
using FlaxEngine;
interface IInterface<T> { }
class MyClass1<T> : Script, IInterface<T> { }
class MyClass2<T> : Script, IInterface<T> { }
```

I get this error:
![image](https://github.com/FlaxEngine/FlaxEngine/assets/1567199/78b986ae-ad61-4490-b3a7-64621fcb99a2)

**Comment by mafiesto4** [comment]
Fixed in 8898c20ad1c7809cfead0df0374b4dd142c84065.
