### ISSUE TITLE
Non-loop animations frame don't reset after reactivation by parameter

### ISSUE THREAD

**Issue by Miniputs** [FlaxEngine/FlaxEngine#1984]
**Issue description:**
I have a parameter set up to activate a non-loop animation in Animation Graph, and it works fine when I preview in editor. But when I use the parameter in run-time the animation frame doesn't reset after first activation, it starts at same frame where last activation ended.
I would have used a one-shot animation if available like in Godot: https://docs.godotengine.org/en/stable/classes/class_animationnodeoneshot.html

**Steps to reproduce:**
In Animation Graph use a loop and a non-loop animation and switch between them by a parameter

**Flax version:**
1.17

![AG-Bug](https://github.com/FlaxEngine/FlaxEngine/assets/53795477/e4d41965-d093-4222-a337-da19d226de3a)

**Comment by mafiesto4** [comment]
Have you tried using Animation Slot for playing single-shot animation?
It's usually driven from code and fits very well when playing hit-reactions and reload/shoot/attack anims. Also, for strafe-left anim I think you want to use Blend Space (1d or 2d) as character movement works better with it (eg. controlled via movement vector from code).

https://docs.flaxengine.com/manual/animation/anim-graph/animation-slots.html?tabs=code-csharp

**Comment by Miniputs** [comment]
Animation Slot works, so for me the issue is solved
