### ISSUE TITLE
Add `BehaviorTreeKnowledgeBooleanDecorator` for conditionals based on bool/pointer value

### ISSUE THREAD

**Issue by mafiesto4** [FlaxEngine/FlaxEngine#1985]
When using `Actor` (or other object) references in Behavior Knowledge it would be nice to have an easy way to check if value is not null. Similarly, it could check if a boolean value is set (eg. `bool HasTarget`). Optionally allow inverting condition. Add automatic title based on condition if no custom name is provided.

**Comment by NatreexTV** [comment]
Maybe a while is not or is true or false repeat this could be interesting too.

**Comment by mafiesto4** [comment]
Added in d5f4254a7314a9ef9ac930678d1faa2c04e4983c.
