### ISSUE TITLE
Flax Engine Crashed when updating C# Script

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#199]
I was updating a Debug message in my C# script when I experienced this crash.
I managed to capture a screenshot of the source of the crash in the engine here:
![image](https://user-images.githubusercontent.com/35228400/106698005-08fc0a00-6634-11eb-9a77-0ba3d3d462e6.png)
I've experienced this same crash on two separate occassions. 

I've attached the Log that was generated at the time of the crash:
[Crash_2021_02_03_15_13_16.zip](https://github.com/FlaxEngine/FlaxEngine/files/5916084/Crash_2021_02_03_15_13_16.zip)

I also experienced a secondary crash here:
![image](https://user-images.githubusercontent.com/35228400/106700143-5b3f2a00-6638-11eb-97c2-bce10fd119f4.png)

There was no log generated for this crash.

I also experienced a random crash here (again no log was generated):
![image](https://user-images.githubusercontent.com/35228400/106706619-0f927d80-6644-11eb-972d-a1bde2fd53b7.png)

**Comment by mafiesto4** [comment]
Fixed in https://github.com/FlaxEngine/FlaxEngine/commit/6ea897b0f5aa4ebc94d65641a26433fdd6763f18 (https://github.com/FlaxEngine/mono/commit/63f7e4ffc0826b0a077d560061f8f2e04f0e6835).
