### ISSUE TITLE
editor crash when marking class deriving from script as abstract and it has already been assigned to an actor in scene

### ISSUE THREAD

**Issue by arvenyon** [FlaxEngine/FlaxEngine#1990]
**Issue description:**
When declaring a class deriving from Script as "abstract", and reloading them in-editor, the editor crashes. This only happens however, when the script has already been assigned to an Actor in the scene, because then it's instantiated - which is not a thing. You cannot instantiate abstract classes.

**Steps to reproduce:**
* Create dummy script
* Hook up to an actor in the scene
* Go back to the script and mark it as abstract
* Switch back to editor - should now crash

**Minimal reproduction project:**
This is nothing complicated, no example project needed imho.

**Flax version:**
v1.7 (64bit)

**Proposal:**
Since the whole instantiating objects is done via reflection (as far as I'm aware), we should simply run some validation logic on the class to be instantiated, which would cover such (imho) simple "gotchas".

**Additional Info:**
You can find the stacktrace attached. 
[flax_abstract_instantiation_crash_st.txt](https://github.com/FlaxEngine/FlaxEngine/files/13465296/flax_abstract_instantiation_crash_st.txt)

**Comment by arvenyon** [comment]
Also, as some additional info:
Once this issue occures, you can't start the editor anymore with that project. Which makes sense, it's trying the same shit again, which is, instantiating an abstract class.
The fix is relatively easy -> simply go into source via code editor and remove the abstract keyword again.

**Comment by mafiesto4** [comment]
Fixed in 2df3d0f7477e682464dcf8dbf8c7e96100cb0106.
