### ISSUE TITLE
[Bug] When there is no camera and you are in the game view, the camera pans

### ISSUE THREAD

**Issue by Bits360** [FlaxEngine/FlaxEngine#1997]
**Issue description:**
[Bug] When there is no camera and you are in the game view, the camera stretches the fov to to the right.

**Steps to reproduce:**
1: Not have a camera
2: Enter "Game" window
3: If "No camera" shows on screen, it should start doing the thing, this might be due to taa or something but thats not tested.

**Flax version:**
1.7

**Comment by mafiesto4** [comment]
Fixed in fa606ce5f6a5260d2629bdf5435bd7e91d5a2914.
