### ISSUE TITLE
X and Z Scale Flipped

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#200]
I don't know what caused this bug to occur but basically, the X and Z scale seemed to scale the wrong axis. I think it might be related to the fact that the object is at 90 degrees but I can't be sure. See the video to understand the issue better.

https://drive.google.com/file/d/10w2YeWu7bLmK5IUzat9y5a9mkOiLLXfv/view?usp=sharing

**Comment by W2Wizard** [comment]
Its definitely because of the rotation, not only to X, seems like scaling does not take it into consideration.

**Comment by mafiesto4** [comment]
Yep, it's a bug. If you use Local Space gizmo it works better for rotated objects but still, this case should be fixed.
![image](https://user-images.githubusercontent.com/3464853/106949729-a5560780-672d-11eb-8f7b-a7151abdba2d.png)
