### ISSUE TITLE
Odd Visject freeze and/or crash.

### ISSUE THREAD

**Issue by Menotdan** [FlaxEngine/FlaxEngine#2001]
**Issue description:**
Some odd set of steps in Visject causes a freeze or crash..
Video: 

https://github.com/FlaxEngine/FlaxEngine/assets/32620310/16c48fed-3629-46f5-96e5-71a9c43d5a71

**Steps to reproduce:**
1. Open the attached project, and open up the "Broken Mat" material.
2. Unplug the R channel from the emissive, and save the material
3. Switch the Scene Texture node to use "Scene Color"
4. Plug the Alpha channel into the emissive output, and then save the material
5. Plug in the B, then G, then R channel into the emissive output, without saving.
6. Switch the scene texture node back to "World Position", and save the material
7. Move the scene texture node, and save the material again. It should still show the `*` icon, indicating the saving didn't work.
8. Press save again, it will freeze, or crash the editor.
NOTE: This is only working 50% of the time for me.

**Minimal reproduction project:**
No cache version, to recreate the initial crash:
[scenetexturebug.zip](https://github.com/FlaxEngine/FlaxEngine/files/13478209/scenetexturebug.zip)

With cache, this will crash any time you modify and save the broken material:
[scenetexturebug with cache.zip](https://github.com/FlaxEngine/FlaxEngine/files/13478214/scenetexturebug.with.cache.zip)

**Flax version:**
1.7.1

**Comment by mafiesto4** [comment]
Caused by leftover asset property reference caused by using fixed memory allocation for postFx material array. Fixed it here: 4f8aff4352745bc86bb9e9c0a7cc6604cf7e6b7a
