### ISSUE TITLE
Unable to use transparency with the multiply blend mode

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#201]
There is currently a bug in the system. I'm unable to use transparency with the multiply blend mode.
![image](https://user-images.githubusercontent.com/35228400/106747494-1d61f600-6678-11eb-99fb-4747a5a22f69.png)

**Comment by mafiesto4** [comment]
Actually, after rethinking it I guess it works fine. As in this example, you multiply background colors with particle material Opacity which is 0 so it gets black.
If you use Additive blend mode it will make the overlay.
I guess you wanted to make sth like this:
![image](https://user-images.githubusercontent.com/3464853/106949332-1648ef80-672d-11eb-9e50-8312e8cfeec1.png)
