### ISSUE TITLE
[bug] Mousing over a prefab to see where it is in project is broken

### ISSUE THREAD

**Issue by Bits360** [FlaxEngine/FlaxEngine#2016]
**Issue description:**
Mousing over a prefab to see where it is in project is broken, its description vanishes in 1 frame after it appears.

**Steps to reproduce:**
Mouse over a parameter that takes a prefab as input

**Flax version:**
1.7.1

**Comment by mafiesto4** [comment]
It looks like a bug when tooltip goes over a second screen (the right edge of it).

**Comment by mafiesto4** [comment]
Fixed in 228239632a32da70b2131c01efbdf4d15b72e590,
