### ISSUE TITLE
Clone master failed

### ISSUE THREAD

**Issue by sainimu78** [FlaxEngine/FlaxEngine#2018]
**Issue description:**

clone the master failed and got erorrs:
```
error: external filter 'git-lfs filter-process' failed
fatal: Content/Editor/Camera/M_Camera.flax: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```
if run "GenerateProjectFiles.bat", got:
```
Generating Flax Engine project files...
CallBuildTool ERROR: Repository was not cloned using Git LFS
Flax.Build tool failed.
```

**Steps to reproduce:**

Just using TortoiseGit to clone the repo

**Flax version:**

branch of master on 2023.12.01

**Comment by mafiesto4** [comment]
Does `git lfs fetch --all` helps?

We use Git LFS on our own server: https://gitlab.flaxengine.com/flax/flaxengine (Github prices for LFS transfer are too high.

**Comment by sainimu78** [comment]
> Does `git lfs fetch --all` helps?
> 
> We use Git LFS on our own server: https://gitlab.flaxengine.com/flax/flaxengine (Github prices for LFS transfer are too high.

Thank you.
I confirmed this issue was solved, but I did nothing special actually, I just clone the repo again.
Maybe you guys know what happened to that server about 4 hours ago.
