### ISSUE TITLE
Visual artifacts when overlaying plane with Terrain

### ISSUE THREAD

**Issue by W2Wizard** [FlaxEngine/FlaxEngine#202]
**Issue description:**
Creating a terrain and overlaying a plane on it (like creating a water plane) creates lots of weird visual artifacts when far away as well as creating weird shadows here and there

Additionally going close up creates weird shadows on the terrain.

**Steps to reproduce:**
1. Create a terrain and apply the heightmap (or play around with the noise tool to create some uneven formations)
2. Overlay a plane on it, make sure its slightly raised.
3. Move the camera around and closer and further away from the terrain and notice all the weird artifacts.

https://user-images.githubusercontent.com/63303990/106805506-1088d680-6667-11eb-8436-33d760f2d112.mp4

*My heightmap that I used:*
![Heightmap](https://user-images.githubusercontent.com/63303990/106804826-2f3a9d80-6666-11eb-8cd1-a6e00ffe9006.png)

**Flax version:**
1.0.6216

**Comment by mafiesto4** [comment]
That's Z-fighting (https://en.wikipedia.org/wiki/Z-fighting). Using inversed depth buffer (already on roadmap) would reduce this issue. You can make camera near plane higher or far plane lower to reduce this effect.
The second problem with shadowing artifact is common and adjusting shadow normal offset and bias helps to fix it (done per-light, per-scene for a particular game, the default options won't work always).
