### ISSUE TITLE
Vertical Panel and Horizontal Panel Layout Bug

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#203]
I've just pulled the most recent Github fixes for UI. The previous issues I reported are now gone but there is a new bug.

Make this Layout:
![image](https://user-images.githubusercontent.com/35228400/106817145-8eca9480-66ca-11eb-9fd3-e253828d4884.png)

The result is this:
![image](https://user-images.githubusercontent.com/35228400/106817185-a013a100-66ca-11eb-94b9-58cf663520f3.png)

Please see the video here to see the bug in action:
https://drive.google.com/file/d/1XdJ22P_uLNpTxYrp2CQWOSat9fcl5MR9/view?usp=sharing

**Comment by mafiesto4** [comment]
I think it's related to the height of that Horizontal Panel (it's very large) and it has anchors set to fill the whole parent control. I did a clean setup of this hierarchy and it works fine. Probably, this was caused by editing UI and one of the options left big control height.

**Comment by Evildea** [comment]
@mafiesto4 I tried doing a clean setup and it went bad again for me. Perhaps I'm doing something wrong? I'm coming at this from a UE4 mindset. 

Here is a video of me performing the setup, perhaps this will inform you of the problem (whether me or the system):
https://drive.google.com/file/d/1bPkbMxPgWEBqyDb6GSylgMS8QhaKNw0Y/view?usp=sharing
