### ISSUE TITLE
Editor Crash When Editing Prefabs "!IsDuringPlay()"

### ISSUE THREAD

**Issue by buzzdx** [FlaxEngine/FlaxEngine#2031]
When editing prefabs after changing something, doesn't really matter what, but for example when assigning an animgraph, the editor crashes with an assertion failed msg with "!IsDuringPlay()". 

I do not have a 100% sure way to reproduce it. But i've been working with prefabs a lot in the last two days and it happened so much that I'm now filing this issue and sending the logs in hopes it can be traced down and fixed.

[ 00:00:01.132 ]: [Info] Starting scripts compilation...
[ 00:00:01.132 ]: [Info] Command: C:\Program Files (x86)/Flax/Flax_1.7/Binaries/Tools/Flax.Build.exe -log -logfile= -build -mutex -buildtargets=GameEditorTarget -skiptargets=FlaxEditor -platform=Windows -arch=x64 -configuration=Development
[ 00:00:01.198 ]: [Info] Flax.Build 1.0.0
[ 00:00:01.259 ]: [Info] Building targets...
[ 00:00:01.277 ]: [Info] Found Android SDK at C:\Users\buzzdx\AppData\Local\Android\Sdk
[ 00:00:01.294 ]: [Info] Building C# only
Building target GameEditorTarget in Development for Windows x64 
[ 00:00:01.301 ]: [Info] Building referenced target Flax
[ 00:00:01.553 ]: [Info] Saving assets cache to 'C:\Users/buzzdx/Documents/Flax Projects/Our3DQuest/Cache/AssetsCache.dat', entries: 486
[ 00:00:01.957 ]: [Info] Building for Windows without Vulkan rendering backend (Vulkan SDK is missing)
[ 00:00:01.965 ]: [Info] Using .NET SDK 7.0.403, runtime 7.0.13 (C:\Program Files\dotnet\)
[ 00:00:02.465 ]: [Info] Found 5 valid and 0 invalid actions in Task Graph cache
Done! 
[ 00:00:02.466 ]: [Info] Total time: 00:00:01.2905861
[ 00:00:02.487 ]: [Info] Scripts reloading start
[ 00:00:02.489 ]: [Info] Loading binary modules from build info file C:\Users/buzzdx/Documents/Flax Projects/Our3DQuest/Binaries/GameEditorTarget/Windows/x64/Development/GameEditorTarget.Build.json
[ 00:00:02.489 ]: [Info] Loading binary module Game
[ 00:00:02.545 ]: [Info] Assembly Game.CSharp loaded in 56ms
[ 00:00:02.549 ]: [Info] Caching classes for assembly Game.CSharp took 4ms
[ 00:00:02.550 ]: [Info] Assembly 'Game.CSharp' scanned for custom editors in 0 ms
[ 00:00:02.550 ]: [Info] Scripts reloading end. Total time: 63ms
[ 00:00:02.551 ]: [Info] Editor end init
[ 00:00:02.552 ]: [Info] Changing editor state from FlaxEditor.States.LoadingState to FlaxEditor.States.EditingSceneState
[ 00:00:02.559 ]: [Info] Searching for valid Actor
[ 00:00:02.562 ]: [Info] Found 51 types (in 2 ms)
[ 00:00:02.764 ]: [Info] Loading editor windows layout from 'C:\Users/buzzdx/Documents/Flax Projects/Our3DQuest/Cache/WindowsLayout.xml'
[ 00:00:02.808 ]: [Info] Closing splash screen
[ 00:00:02.811 ]: [Info] Loading last opened scene: Level1
[ 00:00:02.814 ]: [Info] Changing editor state from FlaxEditor.States.EditingSceneState to FlaxEditor.States.ChangingScenesState
[ 00:00:02.822 ]: [Warning] Unable to find scripting object with ID=936132764b686c3d3173cb98f747ae64. Required type FlaxEngine.Actor.
[ 00:00:02.837 ]: [Warning] Unable to find scripting object with ID=936132764b686c3d3173cb98f747ae64. Required type FlaxEngine.Actor.
[ 00:00:02.857 ]: [Info] Loading scene...
[ 00:00:02.888 ]: [Info] Actor  (FlaxEngine.CharacterController; cd2ac2a142918140986e34bbfe8705db) has missing child object (PrefabObjectID: fdafa5014c618a9aad30c2a9a492e264, PrefabID: 6ebe2c2c421a9f474457c7af1d92a93a, Path: C:\Users/buzzdx/Documents/Flax Projects/Our3DQuest/Content/Prefabs/ZombieCCPrefab.prefab)
[ 00:00:02.889 ]: [Info] Actor  (FlaxEngine.CharacterController; cd2ac2a142918140986e34bbfe8705db) has missing child object (PrefabObjectID: 9f3c2fb14ac6dfd65e8f30bac3b6d465, PrefabID: 6ebe2c2c421a9f474457c7af1d92a93a, Path: C:\Users/buzzdx/Documents/Flax Projects/Our3DQuest/Content/Prefabs/ZombieCCPrefab.prefab)
[ 00:00:03.001 ]: [Info] Created graph for scene 'Scene' in 4 ms
[ 00:00:03.001 ]: [Info] Changing editor state from FlaxEditor.States.ChangingScenesState to FlaxEditor.States.EditingSceneState
[ 00:00:03.001 ]: [Info] Scene loaded in 143 ms
[ 00:00:03.086 ]: [Info] Resizing navmesh Default from 0 to 32 tiles capacity
[ 00:00:03.121 ]: [Info] Starting Atmosphere Pre Compute service
[ 00:00:08.943 ]: [Info] Applying prefab changes from actor CharacterController (FlaxEngine.CharacterController; c5f7b2c54af53de458b03c8bb855d0f9) (total objects count: 4) to FlaxEngine.Prefab, 6ebe2c2c421a9f474457c7af1d92a93a, C:\Users/buzzdx/Documents/Flax Projects/Our3DQuest/Content/Prefabs/ZombieCCPrefab.prefab...
[ 00:00:08.944 ]: [Info] Updating prefab data
[ 00:00:08.944 ]: [Info] Creating json resource of type 'FlaxEngine.Prefab' at 'C:\Users/buzzdx/Documents/Flax Projects/Our3DQuest/Content/Prefabs/ZombieCCPrefab.prefab'
[ 00:00:08.944 ]: [Info] Reloading asset FlaxEngine.Prefab, 6ebe2c2c421a9f474457c7af1d92a93a, C:\Users/buzzdx/Documents/Flax Projects/Our3DQuest/Content/Prefabs/ZombieCCPrefab.prefab
[ 00:00:08.945 ]: [Info] Reloading prefab instances
[ 00:00:08.948 ]: [Info] Prefab synced! (1 instances)
[ 00:00:08.948 ]: [Info] Updating referencing prefabs
[ 00:00:08.948 ]: [Info] Prefab updated! 24 ms
[ 00:00:09.192 ]: [Info] Saving assets cache to 'C:\Users/buzzdx/Documents/Flax Projects/Our3DQuest/Cache/AssetsCache.dat', entries: 486
[ 00:00:09.809 ]: [Info] Creating package at 'C:\Users/buzzdx/Documents/Flax Projects/Our3DQuest/Cache/Thumbnails/cache_da65e18484f7437b9b90f6a725560ca0.flax'. Silent Mode: true
[ 00:00:09.809 ]: [Info] File 'C:\Users/buzzdx/Documents/Flax Projects/Our3DQuest/Cache/Thumbnails/cache_da65e18484f7437b9b90f6a725560ca0.flax' is in use. Trying to release handle to it.
[ 00:00:27.736 ]: [Info] Applying prefab changes from actor CharacterController (FlaxEngine.CharacterController; c5f7b2c54af53de458b03c8bb855d0f9) (total objects count: 4) to FlaxEngine.Prefab, 6ebe2c2c421a9f474457c7af1d92a93a, C:\Users/buzzdx/Documents/Flax Projects/Our3DQuest/Content/Prefabs/ZombieCCPrefab.prefab...
[ 00:00:27.736 ]: [Info] Updating prefab data
[ 00:00:27.736 ]: [Info] Creating json resource of type 'FlaxEngine.Prefab' at 'C:\Users/buzzdx/Documents/Flax Projects/Our3DQuest/Content/Prefabs/ZombieCCPrefab.prefab'
[ 00:00:27.737 ]: [Info] Reloading asset FlaxEngine.Prefab, 6ebe2c2c421a9f474457c7af1d92a93a, C:\Users/buzzdx/Documents/Flax Projects/Our3DQuest/Content/Prefabs/ZombieCCPrefab.prefab
[ 00:00:27.742 ]: [Info] Reloading prefab instances
[ 00:00:27.742 ]: [Info] Prefab synced! (1 instances)
[ 00:00:27.743 ]: [Info] Updating referencing prefabs
[ 00:00:27.743 ]: [Info] Prefab updated! 12 ms
[ 00:00:28.064 ]: [Info] Saving assets cache to 'C:\Users/buzzdx/Documents/Flax Projects/Our3DQuest/Cache/AssetsCache.dat', entries: 486
[ 00:00:28.064 ]: [Info] Creating package at 'C:\Users/buzzdx/Documents/Flax Projects/Our3DQuest/Cache/Thumbnails/cache_da65e18484f7437b9b90f6a725560ca0.flax'. Silent Mode: true
[ 00:00:28.064 ]: [Info] File 'C:\Users/buzzdx/Documents/Flax Projects/Our3DQuest/Cache/Thumbnails/cache_da65e18484f7437b9b90f6a725560ca0.flax' is in use. Trying to release handle to it.
[ 00:00:58.262 ]: [Info] Applying prefab changes from actor CharacterController (FlaxEngine.CharacterController; c5f7b2c54af53de458b03c8bb855d0f9) (total objects count: 4) to FlaxEngine.Prefab, 6ebe2c2c421a9f474457c7af1d92a93a, C:\Users/buzzdx/Documents/Flax Projects/Our3DQuest/Content/Prefabs/ZombieCCPrefab.prefab...
[ 00:00:58.262 ]: [Info] Updating prefab data
[ 00:00:58.262 ]: [Info] Creating json resource of type 'FlaxEngine.Prefab' at 'C:\Users/buzzdx/Documents/Flax Projects/Our3DQuest/Content/Prefabs/ZombieCCPrefab.prefab'
[ 00:00:58.263 ]: [Info] Reloading asset FlaxEngine.Prefab, 6ebe2c2c421a9f474457c7af1d92a93a, C:\Users/buzzdx/Documents/Flax Projects/Our3DQuest/Content/Prefabs/ZombieCCPrefab.prefab
[ 00:00:58.271 ]: [Info] Reloading prefab instances
[ 00:00:58.271 ]: [Info] Prefab synced! (1 instances)
[ 00:00:58.271 ]: [Info] Updating referencing prefabs
[ 00:00:58.271 ]: [Info] Prefab updated! 14 ms
[ 00:00:58.557 ]: [Info] Saving assets cache to 'C:\Users/buzzdx/Documents/Flax Projects/Our3DQuest/Cache/AssetsCache.dat', entries: 486
[ 00:00:58.824 ]: [Info] Creating package at 'C:\Users/buzzdx/Documents/Flax Projects/Our3DQuest/Cache/Thumbnails/cache_da65e18484f7437b9b90f6a725560ca0.flax'. Silent Mode: true
[ 00:00:58.824 ]: [Info] File 'C:\Users/buzzdx/Documents/Flax Projects/Our3DQuest/Cache/Thumbnails/cache_da65e18484f7437b9b90f6a725560ca0.flax' is in use. Trying to release handle to it.
[ 00:01:14.532 ]: [Info] Found Game.HealthComponent type for type HealthComponent (assembly Game.CSharp)
[ 00:01:14.978 ]: [Info] Found Game.HealthComponent type for type HealthComponent (assembly Game.CSharp)
[ 00:01:17.262 ]: [Info] Applying prefab changes from actor CharacterController (FlaxEngine.CharacterController; c5f7b2c54af53de458b03c8bb855d0f9) (total objects count: 5) to FlaxEngine.Prefab, 6ebe2c2c421a9f474457c7af1d92a93a, C:\Users/buzzdx/Documents/Flax Projects/Our3DQuest/Content/Prefabs/ZombieCCPrefab.prefab...
[ 00:01:17.262 ]: [Info] Updating prefab data
[ 00:01:17.262 ]: [Info] Creating json resource of type 'FlaxEngine.Prefab' at 'C:\Users/buzzdx/Documents/Flax Projects/Our3DQuest/Content/Prefabs/ZombieCCPrefab.prefab'
[ 00:01:17.263 ]: [Info] Reloading asset FlaxEngine.Prefab, 6ebe2c2c421a9f474457c7af1d92a93a, C:\Users/buzzdx/Documents/Flax Projects/Our3DQuest/Content/Prefabs/ZombieCCPrefab.prefab
[ 00:01:17.268 ]: [Info] Reloading prefab instances
[ 00:01:17.269 ]: [Fatal] Assertion failed!
File: F:\FlaxEngine\Source\Engine\Scripting\Script.cpp
Line: 268

Expression: !IsDuringPlay() 
================================================================
[ 00:01:17.368 ]: [Error] Critical error! Reason: Assertion failed!
File: F:\FlaxEngine\Source\Engine\Scripting\Script.cpp
Line: 268

Expression: !IsDuringPlay() 
[ 00:01:17.457 ]: [Error] Stack trace:
[ 00:01:17.457 ]: [Error]     at FlaxEditor.exe!Log::Logger::Write() in F:\FlaxEngine\Source\Engine\Core\Log.cpp:line 260
[ 00:01:17.457 ]: [Error]     at FlaxEditor.exe!PlatformBase::Assert() in F:\FlaxEngine\Source\Engine\Platform\Base\PlatformBase.cpp:line 447
[ 00:01:17.457 ]: [Error]     at FlaxEditor.exe!Script::Initialize() in F:\FlaxEngine\Source\Engine\Scripting\Script.cpp:line 268
[ 00:01:17.457 ]: [Error]     at FlaxEditor.exe!PrefabInstanceData::SynchronizePrefabInstances() in F:\FlaxEngine\Source\Engine\Level\Prefabs\Prefab.Apply.cpp:line 429
[ 00:01:17.457 ]: [Error]     at FlaxEditor.exe!PrefabInstanceData::SynchronizePrefabInstances() in F:\FlaxEngine\Source\Engine\Level\Prefabs\Prefab.Apply.cpp:line 572
[ 00:01:17.457 ]: [Error]     at FlaxEditor.exe!Prefab::ApplyAllInternal() in F:\FlaxEngine\Source\Engine\Level\Prefabs\Prefab.Apply.cpp:line 1036
[ 00:01:17.457 ]: [Error]     at FlaxEditor.exe!Prefab::ApplyAll() in F:\FlaxEngine\Source\Engine\Level\Prefabs\Prefab.Apply.cpp:line 707
[ 00:01:17.457 ]: [Error]     at FlaxEditor.exe!PrefabManager::ApplyAll() in F:\FlaxEngine\Source\Engine\Level\Prefabs\PrefabManager.cpp:line 556
[ 00:01:17.457 ]: [Error]     at 0x7ff7c2cdff8a
[ 00:01:17.457 ]: [Error] Used Physical Memory: 7.66 Gb (48%)
[ 00:01:17.457 ]: [Error] Used Virtual Memory: 264.29 Gb (0%)
[ 00:01:17.457 ]: [Error] Process Used Physical Memory: 466.55 Mb
[ 00:01:17.457 ]: [Error] Process Used Virtual Memory: 1.27 Gb
[ 00:01:17.458 ]: [Error] Creating Mini Dump to C:\Users/buzzdx/Documents/Flax Projects/Our3DQuest/Logs/Crash_2023_12_02_20_29_37/Minidump.dmp
================================================================
[ 00:01:17.676 ]: [Error] Crash info collected.

![grafik](https://github.com/FlaxEngine/FlaxEngine/assets/26144397/0cc4a617-74eb-408f-93b6-f545c7063f92)

**Flax version:**
1.7.6404.1

**Comment by RuanLucasGD** [comment]
@buzzdx can try this on master? maybe this was fixed

**Comment by Menotdan** [comment]
Yeah I didn't get the crash on master but I got it on an older build I have locally.

**Comment by buzzdx** [comment]
is it safe to work on my project on master? or is it just meant for testing?

i do have another one btw that sometimes pops up, less often, but also crashes and always the same error msg:
![grafik](https://github.com/FlaxEngine/FlaxEngine/assets/26144397/bbf609af-1150-423f-ac6a-27487a6d917f)
