### ISSUE TITLE
Rename `Navigation.ProjectPoint` into `Navigation.FindClosestPoint` to have consistent API naming

### ISSUE THREAD

**Issue by Withaust** [FlaxEngine/FlaxEngine#2034]
Currently, we have `FindPath`, `FindRandomPoint` and `FindRandomPointAroundCircle` as methods of `Navigation`. Upon initial search for a function that would help to find closest pathfindable point to an arbitrary Vector3 I skimmed over `ProjectPoint` because from the name of the method it sounded like it was doing something different. I propose to rename it into `FindClosestPoint` in order to be consistent with the rest of the `Find` methods, while also being more self-explanatory with its distinct name.

**Comment by mafiesto4** [comment]
Implemented in 5de5e576e5037d7617e8f6ffed43954a338609d9. Marked old API as deprecated - will be removed after 1 year (or later).
