### ISSUE TITLE
Wrong structure used for size parameter (but works for now)

### ISSUE THREAD

**Issue by nothingTVatYT** [FlaxEngine/FlaxEngine#2037]
In this line, the structure should be get_hostfxr_parameters according to the runtime docs:

https://github.com/FlaxEngine/FlaxEngine/blob/712c400e432c6f3649567cc17b95cc6d06497279/Source/Engine/Scripting/Runtime/DotNet.cpp#L1660

It works because both structures result in size being initialized to 24 but just in case this is changed for future dotnet versions it's safer to fix it.

**Comment by mafiesto4** [comment]
Thanks for spotting this! 8faaaaaf54f57e36bbfac5499a9d9daa14f5f285
