### ISSUE TITLE
Minor Bug with Label Text Field

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#204]
There is a minor bug with the Label text field. 

After you make a change in the text field, it doesn't update in the Editor until you press on the Editor window.

You can see a video of this bug here:
https://drive.google.com/file/d/1ffW8ykylFO993sLQnnjkTrRFkjLLmDbl/view?usp=sharing

**Comment by mafiesto4** [comment]
It's not updating because text field sets the property value on the editing end.
