### ISSUE TITLE
Adding a script to a prefab does not mark it dirty or allow you to save it.

### ISSUE THREAD

**Issue by Menotdan** [FlaxEngine/FlaxEngine#2041]
**Issue description:**
When you add a Script to an Actor in a Prefab, the prefab is not marked dirty, and so the script can't be added to the scene.

**Steps to reproduce:**
1. Create a prefab with one actor
2. Drag the prefab into the scene
3. Save the scene
4. Add a script to the one actor
5. Try to save the prefab.

**Flax version:**
Master 526edb83de5a427daf787025e5334dead5ecd2cf

**Comment by mafiesto4** [comment]
Fixed in 59fe448987f3a70567735645c96c1617220ba549.
