### ISSUE TITLE
Particle system crash on MaxSpriteSize

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#205]
Particle system randomly crashes with the following assertion. We thought that we could perhaps get around this issue by simply clamping the max and min sprite size of the particle but this didn't fix the issue. 
My artist has been working with the particle system all day and has experienced this exact same crash 8 times today.
![image](https://user-images.githubusercontent.com/35228400/106833511-bed46080-66e7-11eb-89ad-61d810c7d5da.png)

**Comment by Evildea** [comment]
Here is the project with particles that crashes with the above error from time to time.

He was primarily working in Content/Particles/P_FireBall_Impact when it crashed.

[Particles test.zip](https://github.com/FlaxEngine/FlaxEngine/files/5924253/Particles.test.zip)

**Comment by stefnotch** [comment]
Okay, after some checking, it seems like the `Particle Normalized Age` node can sometimes return NaN or Infinity in this setup.
I think this would happen when the `Lifetime` is 0 and the particle gets updated.

**Comment by mafiesto4** [comment]
I added some checks to prevent division by 0 in particles code even if particle has some invalid data like mass or radius equal to 0 (https://github.com/FlaxEngine/FlaxEngine/commit/25f35b22be9e757dbf95e653ff76cf5b470ff021).

Then I send some time debugging graph and trying to find any place that could cause this problem and I think it should work now. In case of crashes please send crashdump to evaluate it. If it won't help we could add some reporting for particles data (eg. profiling utility to check particle data for NaN/Infinity).
