### ISSUE TITLE
[Bug] Changing prefab root and deleting the previous root, then saving causes issues

### ISSUE THREAD

**Issue by Bits360** [FlaxEngine/FlaxEngine#2050]
**Issue description:**
Changing prefab root and deleting the previous root, then saving deletes the prefab visually, but leaves it as invalid data, causing errors (though 1.7 deletes invalid data automatically it seems, which is better than a trip through the files, still annoying).

**Flax version:**
1.7.1

**Comment by mafiesto4** [comment]
This was pretty hard to fix but I did it in e0a085adfef9a6955528b28a567dd3bc4f276834. I added an automated test to cover 2 cases: loading prefab with root changes and loading prefab with root  that was changed+deleted as in this case. In general, prefabs system should work far better at reconstructing prefab instances.
