### ISSUE TITLE
AI Decorators invisible node duplication

### ISSUE THREAD

**Issue by NatreexTV** [FlaxEngine/FlaxEngine#2059]
I search about it, and I don't find any error like this one.

**Issue description:**
I was wondering why when I add a decorator node, when the return is true all goes well, but once it's failed (return false) the node isn't play at all, no matter where you add the decorator node.

After few test and by trying to discover deeper in Flax with the source, I find that the nodes seem to be duplicated, but invisible. Starting from the start to the bottom of the Behvaior tree order.

After testing on two projects, it seem to be on my main project and I try to replicate the same things on another project and seem to be normal. So, it's not the fact I move from V1.7.1 to master branch and coming back to 1.7.1 make this issue.

So i tryed with a test project, adding node, change Engine version, nothing reproduce it. I'm not sure if it will be a bug on longer term or it's just a block into my project, but I think is not supposed to be like that if another test project I done with the same things work perfectly.

I link my project on the with the issue for try it in your end, but seem to be the project itself doing that.

[Octopeur project from Google Drive](https://drive.google.com/file/d/1jy_UWVziUkDPPqDSfrVMUZYnr_AEO1cX/view?usp=drive_link)

[Video about the issue](https://drive.google.com/file/d/143RMBp_MoSe1T_psoSiLVpD5E-sKOhCv/view?usp=drive_link)

**Flax version:**
1.7.1 and master branch

**Comment by NatreexTV** [comment]
After investigation, It seem to happen when you a decorator to the parent, delete it and put another one to the children.

Hard to explain, that why I recreate another video that show the bug.

The bug goes at the same order as the Behavior tree execute order, but in reverse.

[Link to the second video](https://drive.google.com/file/d/1uU1VNwb7l9uZL6h--Ku2h26hB8fAV-0g/view?usp=drive_link)

**Comment by mafiesto4** [comment]
Fixed in c145042f52f11630ecb8ecac44197ef6297c3678.
