### ISSUE TITLE
Crash after opening project, compiling, saving then closing.

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#206]
I've found that about 25% of the time after closing the editor I get a crash. I've managed to figure out that simply opening a project, compiling scripts, saving, then closing the editor can cause it to happen about 25% of the time.

Here is a video of me repeating the above process:
https://drive.google.com/file/d/1TB0GrMY_eHjVeZAAMSrPp47IP5YHFXVG/view?usp=sharing

Here is the crash log:
[Crash_2021_02_05_22_05_38.zip](https://github.com/FlaxEngine/FlaxEngine/files/5925335/Crash_2021_02_05_22_05_38.zip)

**Comment by mafiesto4** [comment]
I was unable to detect the actual crash location 😢 

![image](https://user-images.githubusercontent.com/3464853/107269935-997a8600-6a4a-11eb-910d-01e41401972e.png)

**Comment by W2Wizard** [comment]
![image](https://user-images.githubusercontent.com/63303990/107270459-4228e580-6a4b-11eb-812b-6610272b3de2.png)
