### ISSUE TITLE
Actor bounding boxes slightly wrong with rotation.

### ISSUE THREAD

**Issue by Menotdan** [FlaxEngine/FlaxEngine#2062]
**Issue description:**
When you rotate an actor, it's bounding box is calculated with extra space that is not needed.

**Minimal reproduction project:**
[ActorBounds.zip](https://github.com/FlaxEngine/FlaxEngine/files/13626075/ActorBounds.zip)

Steps to Reproduce:
1. Open the project, and enter playmode.
2. Ctrl + Shift + Tab to return to the Editor viewport in play mode.
3. Investigate the bounding boxes of the actors.

![image](https://github.com/FlaxEngine/FlaxEngine/assets/32620310/8885c46d-a5f5-4183-8324-0cc7ab0719bd)
(Hard to get a good screenshot)

**Flax version:**
Launcher master branch as 12/09/2023.

**Comment by mafiesto4** [comment]
That's simply how `BoundingBox` works - it represents an axis-aligned bounding box in three-dimensional space.
We have `OrientedBoundingBox` which can represent bounds with rotation but actors have to use an optimized version due to performance (`OBB` uses `Vector3` + `Transform` while `ABB` is 2x`Vector3`).

**Comment by Menotdan** [comment]
> That's simply how `BoundingBox` works - it represents an axis-aligned bounding box in three-dimensional space.
> We have `OrientedBoundingBox` which can represent bounds with rotation but actors have to use an optimized version due to performance (`OBB` uses `Vector3` + `Transform` while `ABB` is 2x`Vector3`).

I know this, but the box is still bigger than the actor's minimum and maximum points after rotation. Maybe that's too expensive to be recalculated after rotating?

**Comment by Menotdan** [comment]
Hm, there also seems to be some odd behavior calculating the bounds for empty actors:
![image](https://github.com/FlaxEngine/FlaxEngine/assets/32620310/21c6e6a9-7a2b-46d5-95ba-3b26759b9d30)
But maybe outside the scope of this issue?
