### ISSUE TITLE
[Bug] Dragging an actor from 1 prefab to another causes issues

### ISSUE THREAD

**Issue by Bits360** [FlaxEngine/FlaxEngine#2065]
**Issue description:**
Dragging an actor from 1 prefab to another causes them to duplicate, and share an ID

Also, even though i have no idea how flax works under the hood, there should not be a way to copy an actor, prefab, struct, etc that doesnt involve changing its ID, because that alone is the source of who knows how many bugs.

**Flax version:**
Master

**Comment by mafiesto4** [comment]
Fixed in b297b9f185735ec67db4ec7a500700556439f338.
