### ISSUE TITLE
Add API for runtime Terrain editing

### ISSUE THREAD

**Issue by mafiesto4** [FlaxEngine/FlaxEngine#2068]
Source: https://discord.com/channels/437989205315158016/1183408048337858590

"Add API to edit terrain in a runtime setting,  as terrain tools are only  available in editor. and although Terrain Tools will allow you to edit during play mode in editor,  they will cause errors in builds when you build if you don't add the #if editor,  So I can not edit for instance "Splat Maps" during runtime."

![image](https://github.com/FlaxEngine/FlaxEngine/assets/3464853/f76f4dfa-3a31-4ffd-b7b1-efdb18bcab9c)

![image](https://github.com/FlaxEngine/FlaxEngine/assets/3464853/90effd79-704a-4e45-acba-eb004986bf2f)

Can be enabled via changing `TERRAIN_UPDATING` from `USE_EDITOR` to `1` to be enabled in game.

**Comment by Withaust** [comment]
Related somewhat https://github.com/FlaxEngine/FlaxEngine/pull/1733
