### ISSUE TITLE
[Bug] When the project saves, ui elements duplicate

### ISSUE THREAD

**Issue by Bits360** [FlaxEngine/FlaxEngine#2069]
**Issue description:**
When the project saves, ui elements inside prefabs duplicate themselves visually, causing what was there to not be hidden when changing the is active, and will stack transparency

**Flax version:**
Master

**Comment by mafiesto4** [comment]
I was unable to reproduce it. Do you have repro steps? Maybe usage of prefabs?

**Comment by Bits360** [comment]
Oops. Forgot to mention the prefab part.

**Comment by Bits360** [comment]
This appears to have been fixed since last week.
