### ISSUE TITLE
[Bug] UI elements inside a UI image are always visible

### ISSUE THREAD

**Issue by Bits360** [FlaxEngine/FlaxEngine#2070]
**Issue description:**
UI elements inside a UI image, with is active disabled, will show up anyways in the editor until is active is toggled again.

**Flax version:**
master

**Comment by mafiesto4** [comment]
I was unable to reproduce it. Do you have repro steps?

**Comment by Bits360** [comment]
I was wrong and this seems to be some strange reaction between prefabs on specifically an image, too specific for me to easily replicate.
