### ISSUE TITLE
Backface Threshold setting for SDF generation is not saved

### ISSUE THREAD

**Issue by abrasivetroop** [FlaxEngine/FlaxEngine#2075]
**Issue description:**

![image](https://github.com/FlaxEngine/FlaxEngine/assets/47716519/4e1c227d-955e-47f8-b68c-dc2c556dfef0)

Backface threshold is never saved and on restart it will revert the generated sdf to default 0.6 value which lowers the quality greatly. 

**Steps to reproduce:**
* Set the value to any other number than 0.6
* Generate SDF
* Restart Flax

**Flax version:**
master

**Comment by mafiesto4** [comment]
We could cache it locally in Editor (per-asset) or in `ModelBase::SDFData` (would require model-data serializer update).

**Comment by Menotdan** [comment]
> We could cache it locally in Editor (per-asset) or in `ModelBase::SDFData` (would require model-data serializer update).

The serializer doesn't care about if default values aren't serialized right? I think updating the serialization would be fine.

**Comment by mafiesto4** [comment]
Added in 6dacf9e1f1e49fa5fed2b35356871179b0a34571. Value will be cached in project Cache folder.
