### ISSUE TITLE
Volumetric Fog visual glitches 

### ISSUE THREAD

**Issue by abrasivetroop** [FlaxEngine/FlaxEngine#2076]
**Issue description:**

Low scattering distribution value for volumetric fog creates weird visual glitches in dark areas.
This happens if:
* Fog density is too high
* Or Eye adaption is enabled

There are more issues I encountered with volumetric fog. I will update this issue in the future.

![image](https://github.com/FlaxEngine/FlaxEngine/assets/47716519/7b6a50dd-ab3e-4ab0-84cf-93dd0ab890fb)

![image](https://github.com/FlaxEngine/FlaxEngine/assets/47716519/97b8ee95-94da-4517-8d03-51648d176480)

**Flax version:**
master

**Comment by mafiesto4** [comment]
That's because default settings are a midpoint between quality and performance. If your project needs a more foggy environment then I would increase the fog `quality`, and reduce its `Distance` to get higher quality (at cost of performance).

**Comment by abrasivetroop** [comment]
Okay thanks for the explanation!
