### ISSUE TITLE
Resizing game view with a screenspace UICanvas causes the RenderTargetPool to be overallocated.

### ISSUE THREAD

**Issue by Menotdan** [FlaxEngine/FlaxEngine#2077]
**Issue description:**
When I rescale my game view with a UICanvas in the scene, I get a crash stating that the RenderTargetPool limit has been reached.

**Steps to reproduce:**
1. Open the attached project
2. Switch to game view
3. Scale the game view around using the side bars of the game view
4. It should crash

**Minimal reproduction project:**
[RenderTargetPoolBug.zip](https://github.com/FlaxEngine/FlaxEngine/files/13664495/RenderTargetPoolBug.zip)

**Flax version:**
Launcher master branch as of 12/13/2023

**Comment by Menotdan** [comment]
An initial skim of the code suggests this is because the `TemporaryRTs` array stores a description has which includes the resolution, and the code will allocate a new RT if it doesn't find an empty slot that has a matching description. With the variety of resolutions possible by scaling the screen, this causes issues.

**Comment by mafiesto4** [comment]
Then we should maybe flush the pool when resolution changes to prevent this overallocation bug.

**Comment by mafiesto4** [comment]
Fixed in 2bef880e214c2473248d72a7a413142a41a6c888.
