### ISSUE TITLE
FileSystem::DeleteFile(path) reports error on success in Content.cpp

### ISSUE THREAD

**Issue by nothingTVatYT** [FlaxEngine/FlaxEngine#2078]
**Issue description:**
The DeleteFile function returns true on success which makes sense logically but the check in Content.cpp assumes true means an error occurred.

On the other hand DeleteDirectory returns true on error and this is all quite confusing and error-prone.
SetReadOnly returns true on success while CopyFile returning true means it failed.

There should be a clear guide line what a bool return value means in terms of success/error condition and the functions be amended to follow that rule.

**Steps to reproduce:**
Run the editor on Linux, delete a file from Content and see the log output.

**Flax version:**
1.7.6406.1

**Comment by nothingTVatYT** [comment]
The PR #2079 fixes the problem in Content.cpp by using a new MoveFileToRecycleBin but there are more places where an error is reported which shouldn't.
I found it in AssetsCache and BinaryAssetFactory.

**Comment by nothingTVatYT** [comment]
Could we add two constants for operation success and operation failed? Testing a boolean return value that returns true on failure and false on success is not intuitive. With constants we could at least hide that.
Something along the line of ```#define SUCCESS false``` although a define may not be the most elegant solution.

**Comment by mafiesto4** [comment]
That was a bug in Linux impl of file removal (copy pasted over to Android and Mac impls). We always return `true` on error in engine so I fixed that in b4c23c969aba6994c5b47dee5c679930606e6e90. Thanks for reporting that. Also, PR for Linux trash bin will be a good improvement.
