### ISSUE TITLE
Importing FBX/Models creates empty folders

### ISSUE THREAD

**Issue by W2Wizard** [FlaxEngine/FlaxEngine#208]
**Issue description:**
When importing models with the "Import Materials" bool checked flax ends up creating empty folders

**Steps to reproduce:**
1. Download these models: [Click here](https://www.kenney.nl/assets/city-kit-suburban)
2. Drag and drop them to import.
3. Congrats you now have lots of empy folders!

https://user-images.githubusercontent.com/63303990/106951446-11d20600-6730-11eb-9d87-4827dd61f55e.mp4

**Logs:**

![image](https://user-images.githubusercontent.com/63303990/107069127-c6783000-67e1-11eb-880f-d5f101a6b26c.png)

**Flax version:**
1.0.6216

**Comment by mafiesto4** [comment]
It looks like the empty folders appear because it fails on importing materials because the have `::` character in the name (invalid for path).
