### ISSUE TITLE
operator != in Tags.cs uses ==

### ISSUE THREAD

**Issue by nothingTVatYT** [FlaxEngine/FlaxEngine#2081]
Probably a copy'n'paste error in Tags.cs line 48: it should read `return left.Index != right.Index;`

**Flax version:**
1.7.6406.1

**Comment by Menotdan** [comment]
@mafiesto4 I would assume you already made a commit for this locally, since its an easy change? It could easily be a PR but I would think you fixed it already.

**Comment by mafiesto4** [comment]
Fixed in 9c4857a20597db83d4d5189c3a1ac8e35ae4a000 and #2083

**Comment by nothingTVatYT** [comment]
This typo caught my eye while I was looking for something else so I had no urgent need for a fix.
I honestly don't know what is easier for you: fixing it in your code, committing and pushing or pulling a PR. This is such a small change - literally just a single character and that made me wonder what you prefer.

Anyway I created a PR now but would like to know what you prefer as I would like to keep your workload low.
