### ISSUE TITLE
Editing the root of a model prefab will not update nested instances of the prefab in other prefabs.

### ISSUE THREAD

**Issue by Menotdan** [FlaxEngine/FlaxEngine#2085]
**Issue description:**
When I use a model prefab as a nested prefab in another prefab, updating the root of the model prefab will not update the nested instances.

**Steps to reproduce:**
https://streamable.com/b4zio1

1. Import a model prefab.
2. Drag the model prefab into the scene.
3. Create an empty actor and add the model prefab in the scene as a child of the empty actor.
4. Save the scene.
5. Drag the new empty actor into the content window to make a prefab.
6. Update the root object of the model prefab.
7. The nested instance doesn't get updated.

**Flax version:**
master https://github.com/FlaxEngine/FlaxEngine/commit/9c4857a20597db83d4d5189c3a1ac8e35ae4a000

**Comment by Menotdan** [comment]
I believe this is related to #2088

**Comment by mafiesto4** [comment]
This issue is the opposite of #1545 where we should preserve root transformation for he prefab instance. What should we do? :)

**Comment by Menotdan** [comment]
> This issue is the opposite of #1545 where we should preserve root transformation for he prefab instance. What should we do? :)

Perhaps preserve the transform but update things like scripts? Or maybe that already happens and I didn't test enough

**Comment by MineBill** [comment]
Prefab instances know which of their properties differ from the base prefab right? In my mind, any property not modified by the instance should be updated when the base prefab changes. So, if you drop a prefab into the scene without modifying its position but change its' rotation, when the base prefab position and rotation get modified, only the position should be applied to the instance.

**Comment by mafiesto4** [comment]
Fixed in 8e6bd07322ec1d283c21b2e8969bbc0e10a26c33.
