### ISSUE TITLE
Editor crashes when you try to create a prefab from terrain.

### ISSUE THREAD

**Issue by Menotdan** [FlaxEngine/FlaxEngine#2087]
**Issue description:**
When you try to create a prefab from a terrain, the editor crashes from trying to draw the terrain to generate a thumbnail.

**Steps to reproduce:**
1. Create a terrain in the scene.
2. Drag the terrain into the content window.
3. Crash.

Here is some context for where it is crashing and some debug info. It seems like the neighboring chunks array is empty.
![Screenshot 2023-12-15 181829](https://github.com/FlaxEngine/FlaxEngine/assets/32620310/17dfdba4-110a-4268-be03-7b4ef7c936d8)

**Flax version:**
master https://github.com/FlaxEngine/FlaxEngine/commit/9c4857a20597db83d4d5189c3a1ac8e35ae4a000

**Comment by mafiesto4** [comment]
Fixed in 6d5d61589423bad5489826970bceb59866b80585.
