### ISSUE TITLE
Creating a new project on an existing path overwrites data

### ISSUE THREAD

**Issue by nothingTVatYT** [FlaxEngine/FlaxEngine#2092]
**Issue description:**
Using the command line arguments "-new" and "-project <path>" creates a new project in that path. Although if there was already a project using plugins they are lost after you accidentally run the same command again.

A better way would be to stop that attempt with an error or optionally ignore the "-new" in such a case.

**Flax version:**
1.7.1

**Comment by mafiesto4** [comment]
Fixed in d5a6083a557eae64c98732623ea835e2db670580.
