### ISSUE TITLE
Terrain doesn't report collisions

### ISSUE THREAD

**Issue by abrasivetroop** [FlaxEngine/FlaxEngine#2102]
**Issue description:**
Terrain collisions are not reported in CollisionEnter. 

```
    public void OnCollisionEnter(Collision collision)
    {
        Debug.Log(collision.OtherCollider);
    }
```
This will print nothing if the collider is colliding with Terrain.

**Flax version:**
1.7.1

**Comment by mafiesto4** [comment]
Works fine to me. Recently I added some fixes for collision data conversion in C# bindings, maybe it fixed the problem.

https://github.com/FlaxEngine/FlaxEngine/assets/3464853/fc2ff04f-0254-4271-b20f-842d3fa177b7

**Comment by mafiesto4** [comment]
Also, you might want to use `OtherActor`/`ThisActor` properties from `Collision` for Terrain as terrain is not a collider actor.
