### ISSUE TITLE
Local transform of an actor created in a prefab does not equal to Identity

### ISSUE THREAD

**Issue by abrasivetroop** [FlaxEngine/FlaxEngine#2103]
**Issue description:**
When you creeate an actor in a prefab it's position is not gonna be zero. Which is the expected behaviour.
 

**Steps to reproduce:**

https://github.com/FlaxEngine/FlaxEngine/assets/47716519/2c385e77-9f85-4030-810e-acc8b41d9609

**Flax version:**
1.7.1

**Comment by Tryibion** [comment]
I assume you are copying and pasting an actor? If this is the case, I would expect it to act how it does instead of resetting the transform.

**Comment by abrasivetroop** [comment]
> I assume you are copying and pasting an actor? If this is the case, I would expect it to act how it does instead of resetting the transform.

No I created from context menu > new 
It doesn't show up in the recording
