### ISSUE TITLE
Prefab import should keep scale and rotation as default

### ISSUE THREAD

**Issue by abrasivetroop** [FlaxEngine/FlaxEngine#2108]
**Issue description:**

Prefab importing scales every actor by 100 and rotates it on X axis by 90 degrees. This causes several issues. For example SDF generation is very broken with these models.

![image](https://github.com/FlaxEngine/FlaxEngine/assets/47716519/53489b84-bfa8-438f-a631-daef642f5b9c)

**Flax version:**
1.7.2

**Comment by ElevenArt** [comment]
I found a way to correctly export the model from Blender to Flax Engine and these 2 issues are not a problem. I wrote more about it in the discussion about importing models, the link is above.

**Comment by Menotdan** [comment]
> I found a way to correctly export the model from Blender to Flax Engine and it seems that these 2 issues are not a problem on the Flax side. I wrote more about it in the Model importing workflow discussion, the link is above.

The model importing workflow (at least OpenFBX) is supposed to handle the scale and direction conversion automatically. You can tell that it's trying to because of the modified transform of the models in the prefab.

**Comment by ElevenArt** [comment]
That's a good news. It would be good if Model Prefab Import also made automatic rotation and scale corrections, which would have the correct transform values in the Prefab.
