### ISSUE TITLE
Constant crash after a few minutes of use — Possibly Navigation Related

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#211]
I've been working a lot of this prototype for my game and it seems to have become very unstable especially in play mode. I think it might be related to the navigation system or my use of the navigation system.

At first, I was using the Binary version and I would just get a lot of Exceptions and Unexpected errors. I then changed to the Github repo and ran it in Debug mode and it always seems to crash at the exact same point.

Here is a video of the crash. I also included a snapshot of what I was doing up until that point as it might inform your debugging: 
https://drive.google.com/file/d/1ni8iaifN60zFnSuqpBhcBMFMHiTvyq8I/view?usp=sharing

Here is a copy of my project:
[FinalProject.zip](https://github.com/FlaxEngine/FlaxEngine/files/5928869/FinalProject.zip)

**Comment by Evildea** [comment]
@mafiesto4 I believe I figured out what was causing this issue although I'm not 100%. It was mainly my own stupidity but maybe there is something you could implement in the script compile so people don't make the mistake I was making.

In my base class, I had a reference to another class that managed the Flax navigation system. Unfortunately, I named the variable for my NavigationController as Navigation which I'm now assuming was conflicting with the Flax class called Navigation. This must have become an issue when I dereferenced Navigation later in code to access my own variables. 
![image](https://user-images.githubusercontent.com/35228400/107101267-e0118a00-686a-11eb-9b00-1f7b4a6ebc2b.png)

I'm not 100% sure if this was the issue, but since I renamed the variable from Navigation to NavigationController, I haven't experienced this crash which I was experiencing every 30 seconds after playing the game.

Therefore, it might be a good idea to put a compile time check in that makes sure the user doesn't accidentally do what I did.

**Comment by mafiesto4** [comment]
Also, the problem could be `NavigationController` inheriting from `Script` while it was used just like a normal object class and when you've created it manually with `new` it wasn't cleared with `Delete(Navigation)` but Flax should handle this in general.

I've spent some time testing this project and did some minor fixes to improve stability https://github.com/FlaxEngine/FlaxEngine/commit/8c1f56b7db86fc7c6aa98cd3b39d1d31cb19f91a and https://github.com/FlaxEngine/FlaxEngine/commit/6ea897b0f5aa4ebc94d65641a26433fdd6763f18 -  so it should work better now.
