### ISSUE TITLE
Resave assets as unprettified before cooking

### ISSUE THREAD

**Issue by Withaust** [FlaxEngine/FlaxEngine#2120]
This will help trimming unnecessary tabulation from the exported JSON based assets on release.

**Comment by mafiesto4** [comment]
We do resave json assets (eg. scene or prefab) with compact json format and store them with LZ4 compression to use less disk space: https://github.com/FlaxEngine/FlaxEngine/blob/master/Source/Editor/Cooker/Steps/CookAssetsStep.cpp#L332
