### ISSUE TITLE
[Prefab Suggestion] Disallow to Apply position or rotation from the Prefab Instance to Prefab

### ISSUE THREAD

**Issue by ElevenArt** [FlaxEngine/FlaxEngine#2125]
Positions and rotations of all prefab instances in the scene are always unique. If I change the position or rotation of a prefab аctor in a scene, it should not be possible to apply this to the prefab asset, to avoid unwanted changes of position and rotation on all prefab instances used in the scene.

![1](https://github.com/FlaxEngine/FlaxEngine/assets/154741707/1a85c555-84b7-4d6e-942f-35cfdfbeb723)

![2](https://github.com/FlaxEngine/FlaxEngine/assets/154741707/abd2b333-0198-44d2-82ed-3346a414027c)

Related to #1545.

Flax version:
1.7.2

**Comment by ElevenArt** [comment]
Something new about this? I think it's one of the critical issues of prefabs, which makes it impossible to save changes from prefab instance to prefab without breaking something and its not logical. In this way, you can safely make changes in Prefabs only from the Prefab Editor, which is a shame, because the potential for working with Prefabs in Flax is not fully utilized in this way. It should be fixed in the near future.

**Comment by mafiesto4** [comment]
@ElevenArt okay let me put it to 1.8 milestone for quick fix

**Comment by mafiesto4** [comment]
Fixed in 7428ecfe63e5189efb2e25a8ad6c866ce0f1ba74.

**Comment by ElevenArt** [comment]
@mafiesto4, @Tryibion I discovered another case where a Prefab Instance applies a Transform to a Prefab root, I wrote more about it on Discord in my [Prefab thread](https://discord.com/channels/437989205315158016/1270707042834845747/1322970508412846172)

A possible solution for this issue is in my [Prefab thread here](https://discord.com/channels/437989205315158016/1270707042834845747/1322972403072237608)
