### ISSUE TITLE
Boxcollider wrongly resizes after saving prefab

### ISSUE THREAD

**Issue by abrasivetroop** [FlaxEngine/FlaxEngine#2128]
**Issue description:**

Box collider size changes after saving prefab

How it looks like:
![image](https://github.com/FlaxEngine/FlaxEngine/assets/47716519/7a924ba5-93c7-4413-b879-0d4d57b05e58)

How it should look like:
![image](https://github.com/FlaxEngine/FlaxEngine/assets/47716519/9f0ec7fb-f468-4a16-8d84-e4b901df9281)

**Flax version:**
1.7.2

**Comment by mafiesto4** [comment]
Any reproduction steps?
