### ISSUE TITLE
Trigger boxes behave strangely with Vehicles

### ISSUE THREAD

**Issue by abrasivetroop** [FlaxEngine/FlaxEngine#2132]
**Issue description:**
I have a box collider with Is Trigger checked and its only checking for Vehicles layer. Vehicles strangely collide with it even though Is Trigger is checked. It doesn't stop them completely but acts really strangely. Here is the video:

https://github.com/FlaxEngine/FlaxEngine/assets/47716519/fe722fff-01b8-443d-a371-32d5b2148300

**Steps to reproduce:**
1. Create a vehicle controller and set it to its own physics layer.
2. Create a trigger box and set it to check the vehicle layer only.
3. Drive through trigger box

**Minimal reproduction project:**

**Flax version:**
1.7.2 master

**Comment by mafiesto4** [comment]
Fixed in eb12c630a775a0efb3f0917d892dc3998e0ed5ec.
