### ISSUE TITLE
Cloth painting doesn't save changes in prefab

### ISSUE THREAD

**Issue by abrasivetroop** [FlaxEngine/FlaxEngine#2136]
**Issue description:**
Cloth painting doesn't save changes in prefabs.

**Steps to reproduce:**
1. Paint cloth
2. Exit prefab

Changes won't be saved unless you change a property in the prefab and then you can save the prefab which will save the cloth painting changes as well.

**Minimal reproduction project:**

**Flax version:**
1.7.2

**Comment by mafiesto4** [comment]
Fixed in ee4fc7c2017e379200d1a0a6a0fcb416a0faa125.
