### ISSUE TITLE
DebugDraw.DrawLines Crashes the Editor

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#214]
**Issue description:**
Using the following code with a broken number of points will results in an editor crash:
`DebugDraw.DrawLines(Path, Transform.GetWorld(), Color.Red);`

![image](https://user-images.githubusercontent.com/35228400/107107148-64700700-6883-11eb-82b8-d5505c52c601.png)

It shouldn't crash the entire editor but simply throw an output error during run-time.

**Comment by W2Wizard** [comment]
Issue can be closed, one down, plenty more to go!
