### ISSUE TITLE
FBX importer ignores shininess, emissive, specular color

### ISSUE THREAD

**Issue by nothingTVatYT** [FlaxEngine/FlaxEngine#2153]
**Issue description:**
On importing FBX into Flax the textures and the diffuse color is taken from the OpenFBX material structure but the emissive and specular color is ignored as well the shininess value.
While Flax does not use shininess but roughness it would be an easy conversion (1-value). Blender apparently does that.

Ignoring these details results in imported materials that may miss a color and typically are way too shiny.

**Flax version:**
1.7.2

**Comment by mafiesto4** [comment]
Added some more properties import in 01d123b09988edc6332a6f7f3dc93ddc03977184.
