### ISSUE TITLE
Unitialized string in C# land passes into C++ land as a null pointer, causing some issues.

### ISSUE THREAD

**Issue by Menotdan** [FlaxEngine/FlaxEngine#2161]
**Issue description:**
If you have an uninitialized string in C#, and you pass it to a function that calls into C++, it will be a `nullptr`, resulting in some bugs.

**Steps to reproduce:**
Copy the following script:
```cs
using FlaxEngine;
namespace Game;
public class crasher : Script
{
    string test;
    public override void OnEnable()
    {
        Level.FindActor(test);
    }
}  
```
Attach it to any object in the scene and enter play mode. You will see a crash, or if you are running a local build, the debugger will throw you a nice error showing you that `str2` in `StringUtils::Compare()` is null.

I'm not sure if this a problem with the interop stack or if functions should be checking for null strings. (I would guess the former)

**Flax version:**
Launcher master branch as of Jan 5. 2024

**Comment by mafiesto4** [comment]
Fixed crash in 1094abce5a8ffe3f5bb88ab3a3864f820a29bd31.
