### ISSUE TITLE
Minor bug in Prefab with Screen Space UI

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#217]
There is a minor bug with the "Is Active" feature in the Prefab for the UI. This bug only affects the Prefab view.

**Steps to repeat:**
1. Create a UICanvas and then place a UIControl below it in a Prefab. Preferably use a Label so you can see the bug.
2. Untick the "Is Active" in the UICanvas.
3. The Canvas and its children turn grey as they are now disabled. However, the Children continue to display in the Prefab.

**Example:**
![image](https://user-images.githubusercontent.com/35228400/107132044-f03f6d00-692f-11eb-94aa-8ff891931183.png)

**Minimum Version:**
This affects the current version in Github.

**Comment by mafiesto4** [comment]
I was unable to reproduce it. Maybe it was already fixed?

https://user-images.githubusercontent.com/3464853/107157114-99af4e80-6982-11eb-9e72-b7bf5ee7d49c.mp4

**Comment by Evildea** [comment]
@mafiesto4 I just tried to replicate this bug again and it seems to no longer occur.
