### ISSUE TITLE
Realtime environment probes doesnt work

### ISSUE THREAD

**Issue by abrasivetroop** [FlaxEngine/FlaxEngine#2191]
**Issue description:**
Realtime environment probes dont work after running the game once. It only works in the editor the first time I open the project. If I run the game it stops working. So after running the game it doesn't even work in the editor.

**Steps to reproduce:**
1. Add an env probe and set the update mode to Realtime.
2. It should work in editor
3. Run the game
4. Env probe stops working

**Flax version:**
1.7.2/1.8.1

**Comment by LoxyMono** [comment]
Having this issue too, it appears to only work in the editor after startup, then once you enter play mode the real-time reflections are broken until you restart the editor again.
However, I found out that it works within a cooked game, both mobile devices and pc.
Minimum repro (Flax 1.8.1): 
[SurvivalProgram.zip](https://github.com/FlaxEngine/FlaxEngine/files/15280493/SurvivalProgram.zip)

**Comment by mafiesto4** [comment]
Fixed in f983be61044e313cbacb942f494da377f06ac23f.
