### ISSUE TITLE
TextBox Possible Bug or Missing Feature

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#220]
I'm not sure if this is a bug but changing the size of the font for the Text Box doesn't change the height of the Text Box.

I decided to try and manually increase the size of the Text Box from the Prefab, but this adjustment was ignored by the editor until I manually changed the size of the Text Box outside of the Prefab in the editor. I never previously set this value in the editor so the Prefab changes should have updated this field.

Please see this video to understand the issue:
https://drive.google.com/file/d/1xK_tuCiDgcPzWxRNOKujkMnw9ea4OGcV/view?usp=sharing

**Comment by mafiesto4** [comment]
I'm no longer able to reproduce it so it should be fixed now. Can you confirm it?

**Comment by Evildea** [comment]
Seems to be. I'll test further in the future.
