### ISSUE TITLE
Tag/Layer drop downs doesn't update after editing Layers And Tags Settings

### ISSUE THREAD

**Issue by Vizepi** [FlaxEngine/FlaxEngine#221]
**Issue description:**
When you add/remove/edit a layer or tag in *Content/Settings/Layers And Tags Settings.json*, the two dropdown lists in Actor's general properties doesn't update. One have to close and re-open Flax to see the updated lists.

**Steps to reproduce:**
Add a new element in Content/Settings/Layers And Tags Settings.json
Edit the Layer or the Tag of the Scene actor
Observe that the new element is not here

**Flax version:**
1.0.6216

**Comment by jb-perrier** [comment]
It's expected, you can see it in docs here ( bottom ) : https://docs.flaxengine.com/manual/editor/game-settings/layers-and-tags-settings.html

**Comment by Vizepi** [comment]
Woops, didn't see this. Maybe it could help to have a note in the Layers & Tags editor
