### ISSUE TITLE
Attempting to create a prefab from the scene with a colon (:) in the name results in an empty, non-prefab file

### ISSUE THREAD

**Issue by envision3d** [FlaxEngine/FlaxEngine#2212]
**Issue description:**
As stated in the title.

**Steps to reproduce:**
1. Add an actor to the scene
2. Change its name, including a colon; ex: "Test: Actor"
3. Drag the actor to the content window to attempt to create a prefab
4. Observe the file that gets created

**Flax version:**
Recent master from git

**Comment by mafiesto4** [comment]
Fixed in 169024ae478d3b7e6151163bf004d4fa5829dec2.
