### ISSUE TITLE
Sprite parameters cannot exceed 4096

### ISSUE THREAD

**Issue by Pikanchion** [FlaxEngine/FlaxEngine#2218]
**Issue description:**
No parameter of a `Sprite` within a `SpriteAtlas` can be manually set in the editor to a value greater than 4096 regardless of the atlas' actual dimensions. 

**Steps to reproduce:**
1. Import an image with dimensions greater than 4096x4096 as a `SpriteAtlas`.
2. Add a `Sprite` to the atlas.
3. Attempt to set any individual value of the `Size` or `Location` to a number greater than 4096.

**Flax version:**
1.7.2

**Comment by mafiesto4** [comment]
Fixed in d33ff4306f2e0baa84a99ce9ecb387ee67796f1b.
