### ISSUE TITLE
Random Assertion on adding Script to a Particle Prefab

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#222]
I tried to add a Script to my Particle Prefab.

The structure of the Prefab is:
Sphere Collider (Parent)
Particle System (Child)

![image](https://user-images.githubusercontent.com/35228400/107296080-d1beaa80-6ac4-11eb-8276-a86a7ae4dc0b.png)

After I opened the editor again, the script was attached to the Prefab.

**Comment by mafiesto4** [comment]
Works fine on the latest Flax 1.6. Probably fixed some time ago...
