### ISSUE TITLE
JSON Asset instance base type guessing issue.

### ISSUE THREAD

**Issue by mtszkarbowiak** [FlaxEngine/FlaxEngine#2224]
# Exaplanation

The issue is that `JsonAsset<T>` does not have an interface to return the object instance, if a subclass of the T is used.

Unfortunately, `GetInstance<T>` fails to deliver such feature. This is because, even if creating an asset succeeds, the get instance does not comply to the restriction:

https://github.com/FlaxEngine/FlaxEngine/blob/169024ae478d3b7e6151163bf004d4fa5829dec2/Source/Engine/Content/JsonAsset.h#L142

# Example

The issue is very simple to explain using an example: Assuming there are 3 API classes: `Animal`, `Dog : Animal`, `Cat : Animal`... 

To deserialize of the animals a workaround is required, which involves guessing underlying type.

```
JsonAsset* asset = assetReference.Get(); // Asset reference restricted to JSON asset of `Animal`

Animal* animal = asset.GetInstance<Animal>(); // Not necessary. But animal is already deserialized here!
if (!animal) animal = asset.GetInstance<Dog>();
if (!animal) animal = asset.GetInstance<Cat>();
if (!animal) animal = asset.GetInstance<Horse>();

DoStuff(animal);
```

# Version

Flax version: 1.7

**Comment by mafiesto4** [comment]
Fixed in 6548ca1148a4164cac9c6799b35430ddd041bf3f.
