### ISSUE TITLE
UI bug: The slider button on float input boxes does not work

### ISSUE THREAD

**Issue by nothingTVatYT** [FlaxEngine/FlaxEngine#2226]
**Issue description:**
On float input boxes there is the small slider button to the right that is supposed to let you change the value with a mouse swipe. That used to work sometimes (unreliable) but at some point it has lost all its functionality. Clicking on the button simply selects the value instead and moving the mouse does not do anything.

https://github.com/FlaxEngine/FlaxEngine/assets/34131388/ab2cdc14-8c64-440b-80bf-d394a5f17310

**Flax version:**
1.7.2 (current master as of Feb 7th)

**Comment by Tesla-J** [comment]
Greetings.
I'm having one of the issues listed in the list of issue #1699 

I can't set the name of folders and files when I create or try to modify them. It's like the keyboard stops working, I can't even move the cursor with it.
When I create a folder and unfocus it when it asks for a name, it's created with a default name (e.g: "New Folder (0)") but when I do the same with a file (e.g: a scene) the file disappears, so I can't even use the editor.

This it what is shown on my terminal when I run Flax Editor

```
AL lib: (EE) GetLoadedHrtf: Invalid header in /usr/share/openal/hrtf/Default HRTF.mhr: "MinPHR03"
AL lib: (EE) GetLoadedHrtf: Failed to load /usr/share/openal/hrtf/Default HRTF.mhr
```

**My system details:**
| **OS** | Fedora 39 x86_64 |
|  --- | --- |
| **Processor** | Intel Core i3-7020U 2.30GHz |
| **Graphic card** | Mesa Intel HD graphics 620 |
| **RAM** | 12GB DDR4 |
| **KDE plasma version** | 5.27.10 |
| **Graphics platform** | Wayland |
| **Qt version** | 5.15.11 |

I'm using the latest Flax Editor for Linux, this is the first time I use it, so I don't know if this is only in the version I'm using.

After installing the Flax Editor on Fedora I had the issue mencioned here #2188 but I could "fix" it using the same strategy mencioned in issue #2187 (moving the Flax Editor to a path without UTF-8 characters).

**Comment by Tesla-J** [comment]
I found a workarround for this problem, these are the steps I followed:

1- Create a file (eg: a scene), It will ask for a name
1- Click on the canvas (I don't know if this is the real name), the file will be created with the default name istead of disappearing

The name can be changed in the properties.

I hope it helps someone.
