### ISSUE TITLE
Linker error if non-POD struct is argument in a virtual function or key/value in Dictionary etc.

### ISSUE THREAD

**Issue by z1dev** [FlaxEngine/FlaxEngine#2227]
**Issue description:**

I use structs a lot in C++, and pass them around. Everything works fine, until I try to make a non-POD struct type an argument in a virtual API_FUNCTION(). It also breaks if the struct is the value type in a Dictionary<> and that dictionary is the argument of an API_FUNCTION(). In that case the function doesn't have to be virtual.

The source file compiles but I get linker errors like this:

`
6>Fudgets.Bindings.Gen.obj : error LNK2019: unresolved external symbol "public: struct DotNetObject * __cdecl MConverter<struct FudgetPadding,void>::Box(struct FudgetPadding const &,class MClass const *)" (?Box@?$MConverter@UFudgetPadding@@X@@QEAAPEAUDotNetObject@@AEBUFudgetPadding@@PEBVMClass@@@Z) referenced in function "public: static struct DotNetObject * __cdecl ManagedDictionary::ToManaged<enum FudgetVisualState,struct FudgetPadding>(class Dictionary<enum FudgetVisualState,struct FudgetPadding,class HeapAllocation> const &,struct DotNetType *,struct DotNetType *)" (??$ToManaged@W4FudgetVisualState@@UFudgetPadding@@@ManagedDictionary@@SAPEAUDotNetObject@@AEBV?$Dictionary@W4FudgetVisualState@@UFudgetPadding@@VHeapAllocation@@@@PEAUDotNetType@@1@Z)
`

I don't know if this is possible to fix, but it's annoying to work around and makes me write really bad c++ code.

**Steps to reproduce:**

Create an API_STRUCT() with a non default copy constructor, add some non default operator= or similar just to make sure it is not a POD.
Add an `API_FUNCTION() virtual void ThisDoesNothing(TheStructName &something) {};` in a class that generates code for C#.

**Minimal reproduction project:**

**Flax version:**

Whatever was the last 1.7 master.

**Comment by mafiesto4** [comment]
That might be bug/limitation related to C++ where structure with copy ctor or move operator defines is no longer blitable as POD types and our bindings generator has problems to properly link stuff.

The easiest solution is to add the following code below that structure:
```cpp
template<>
struct TIsPODType<TheStructName>
{
    enum { Value = true };
};
```

**Comment by z1dev** [comment]
I don't know why but that actually works. That will save me a lot of headache :D
