### ISSUE TITLE
Debug draw shapes are drawn permanently

### ISSUE THREAD

**Issue by W2Wizard** [FlaxEngine/FlaxEngine#223]
**Issue description:**
When using the debug draw methods like `OnDebugDrawSelected()` for instance, having the actor selected then pressing F5 or play, will cause the shapes to still appear permanently until engine restart.

**Steps to reproduce:**
1. Create a C# script
2. Add the following code:
```csharp
using FlaxEngine.Utilities;

//...

public override void OnDebugDrawSelected()
{
       base.OnDebugDrawSelected();

       Random random = new Random(0);       

       for (int i = 0; i < 100; i++)
       {
           DebugDraw.DrawSphere(new BoundingSphere(random.NextVector3(),20), Color.Red, Time.DeltaTime);
       }
}
```
3. Attach the script and select the actor
4. Press play and then stop play
5. You now will still see the debug shapes being drawn

Here you can see how my actor is still drawing the shapes even when I'm not selecting it.
![image](https://user-images.githubusercontent.com/63303990/107344727-0f223880-6ac3-11eb-9d75-c6ccaf644da2.png)

**Flax version:**
1.0.6216

**Comment by mafiesto4** [comment]
Fixed  by 31d1932
