### ISSUE TITLE
SpriteRender doesn't update when assigned material changes at runtime

### ISSUE THREAD

**Issue by Pikanchion** [FlaxEngine/FlaxEngine#2233]
**Issue description:**
Changes performed at runtime to a `Material` are not displayed by any `SpriteRender` using it (ever in the case of a build or instanced material, or until exiting play mode in the case of the editor when not instancing the material).

**Steps to reproduce:**
1. Assign a `Material` to a `SpriteRender`.
2. Change some parameter of the assigned `Material` at runtime.

**Minimal reproduction project:**
[MyProject.zip](https://github.com/FlaxEngine/FlaxEngine/files/14231669/MyProject.zip)

**Flax version:**
1.7.2

**Comment by mafiesto4** [comment]
Fixed in 3ecb7c1d81aeb74b77f2e3965ee6bf6c67c2caf2.
