### ISSUE TITLE
headless editor crashes on an invalid project path

### ISSUE THREAD

**Issue by nothingTVatYT** [FlaxEngine/FlaxEngine#2235]
**Issue description:**
A headless instance of FlaxEditor crashes instead of signalling that a project folder is invalid.
![Screenshot_55](https://github.com/FlaxEngine/FlaxEngine/assets/34131388/56c24d06-7500-40e2-9fcc-ecbf9f4357e0)

**Flax version:**
1.7.2 (latest master)

**Comment by nothingTVatYT** [comment]
Actually it tries to print the error message but because on non-windows platform Char is set to 16bit which is wrong, the error message won't print characters but format the memory address. This is related to issue #2090.

**Comment by mafiesto4** [comment]
Fixed in 04761c69f14b84ae9c5d53f5cf2c866d398b0339.
