### ISSUE TITLE
[Suggestion] Add pop-count math function

### ISSUE THREAD

**Issue by mtszkarbowiak** [FlaxEngine/FlaxEngine#2238]
The suggestion is to add pop-count function to `Math.h` which counts bits with a single CPU cycle.

**Comment by mafiesto4** [comment]
https://github.com/FlaxEngine/FlaxEngine/blob/04f1c9a59b59a79b1ecd4005c8bfea25afe40a5f/Source/Engine/Core/Utilities.h#L82-L96

**Comment by mtszkarbowiak** [comment]
Thank you. Expected that in the math libs.
