### ISSUE TITLE
[Bug] Vertical Panel child-elements being moved from de- and reactivating the containing Canvas object.

### ISSUE THREAD

**Issue by xormak** [FlaxEngine/FlaxEngine#2242]
**Issue description:**
Running into really strange behavior wit the the UI system.

Menus
- MainMenu
  - Vertical Panel
- Settings
  - Vertical Panel

Whenever I set the property "is Active" of the object "Menus" to false and back to true in the Editor/Game views, the VerticalPanel controls inside the hierarchy move to the right and the bottom and stay there. Each consecutive de- and reactivation moves them further and further from their original position by an amount that is, as far as i can tell, half of the viewport width.

I have no scripts attached that act on these objects and both vertical panels are set to Middle Center and Vertical Stretch Center respectively.
Playing around with canvas scaling etc didn't change/improve this behavior either.

It feels like somehwere in the layout code for the vertical panel it adds the actual x and y coordinates to the objects position every time the objects are enabled.

**Steps to reproduce:**
1. Open the default Scene.
2. Enter Game View for the live preview.
3. Select the "Menus" object in the scene hierarchy and toggle the "Is Active" property.

**Video depicting the process and result:**

https://github.com/FlaxEngine/FlaxEngine/assets/16300312/c290fbed-34e1-4cad-b359-7e3b996574de

**Minimal reproduction project:**
[UI_Bug_Reproduction.zip](https://github.com/FlaxEngine/FlaxEngine/files/14275198/UI_Bug_Reproduction.zip)

**Flax version:**
1.7.6407.2

**Comment by Tryibion** [comment]
Related : https://github.com/FlaxEngine/FlaxEngine/issues/851

**Comment by mafiesto4** [comment]
Fixed in 0a9f746abb662975ff6bddf00aa7ac8600b141c5.
