### ISSUE TITLE
Linking fails for Flax structs in c++

### ISSUE THREAD

**Issue by z1dev** [FlaxEngine/FlaxEngine#2245]
**Issue description:**

I was trying to use `TextRange` and `FontLineCache` in Span<> array in a c++ plugin and this resulted in a linker error.

`6>Fudgets.Bindings.Gen.obj : error LNK2001: unresolved external symbol "public: static struct ScriptingTypeInitializer TextRange::TypeInitializer" (?TypeInitializer@TextRange@@2UScriptingTypeInitializer@@A)
6>g:\projects\Flax\UIPluginTest\Plugins\Fudgets\Binaries\FudgetsEditorTarget\Windows\x64\Debug\Fudgets.dll : fatal error LNK1120: 1 unresolved externals`

Adding the `Render2D` module to the .Build file(s) in my project didn't help. These structs don't have the `FLAXENGINE_API` in the engine source, so I added them. Doing that fixes the issue, but I don't know if that's the right solution. 

**Steps to reproduce:**

Make some custom struct in a c++ project, and add for example `API_FIELD() Span<TextRange> LineCache;` and it will result in link error.

**Minimal reproduction project:**

**Flax version:**

1.7 latest master

**Comment by z1dev** [comment]
There are many other structs in `Font.h` without the `FLAXENGINE_API` too.

**Comment by mafiesto4** [comment]
Fixed in 5cada42842f2e30e3d9abe8e5a4bcc1abeac958a.
