### ISSUE TITLE
Assignment of a custom NetworkReplicator Hierarchy does not persist after first editor launch

### ISSUE THREAD

**Issue by envision3d** [FlaxEngine/FlaxEngine#2247]
**Issue description:**
Attempting to use a custom NetworkReplicator Hierarchy does not function properly.

Setting a custom hierarchy exhibits signs of the hierarchy seeming to be in place upon first launch of the game in the editor, but subsequent launches revert back to the default hierarchy.

**Steps to reproduce:**
Note: this issue was observed using C#.

1. Create a custom hierarchy and assign it.  (I've tried assigning in various ways; plugin, script, no change in results.)
```
public class CustomHierarchy : NetworkReplicationHierarchy { }
// somewhere
NetworkReplicator.Hierarchy = new CustomHierarchy();
```
2. Add code to log out the type
```
Debug.Log(NetworkReplicator.Hierarchy.GetType().ToString());
```
4. Launch game and observe the type should read `CustomHierarchy`
5. Stop the game
6. Launch again, and observe the logged type now reads `ArizonaFramework.ReplicationHierarchy`

I've also overridden the `AddObject` method and added logging when it's invoked, and the logs appear consistent with the results above (`AddObject` logs are present when the logging above indicates the `CustomHierarchy` is active; they're not present otherwise.)

**Flax version:**
This has been observed for quite some time now (6+ months?); current version: 1.7.6407.2

**Comment by mafiesto4** [comment]
Have you used Game Instance Settings from Arizona Framework? Those are setup to use in-built rep hierarchy by default with custom settings. You can plug own one there:

![image](https://github.com/FlaxEngine/FlaxEngine/assets/3464853/e8140e32-0bdb-4283-9750-d21f58053759)

**Comment by envision3d** [comment]
I didn't recall this being here, thank you for the reminder!  It looks like my custom hierarchy persists now.
