### ISSUE TITLE
Failed cooking process do not return error code 1 (from command line)

### ISSUE THREAD

**Issue by brmassa** [FlaxEngine/FlaxEngine#2249]
**Issue description:**

In case the cooking process initiate from the command line/terminal fails, it does not return the error code (typically 1) to indicate it stoped with problems.

In a CI/CD scenario, it's needed to indicate the that building process failed. The way it is now, the job continues, and if nothing breaks in a subsequent step, it ends as a success.

I had to add a bash script to check if the Output folder exists after the cooking process, which is not ideal because the brash could happen in a later step.

```bash
# Flax do not return fail code when it fails to compile. So we have to check if the output is there
if [[ ! -d "Output" ]]; then
  echo "App was not created."
exit 1
```

**Steps to reproduce:**
#2248 

**Minimal reproduction project:**
Blank project created by the launcher will suffice.

**Flax version:**
1.7.2

**Comment by mafiesto4** [comment]
Fixed in 318b00c617140b487c8cb60ee46fb44bd7545338.
