### ISSUE TITLE
[TERRAIN] Position of terrain vertices are sometimes incorrect, depending of camera orientation

### ISSUE THREAD

**Issue by Vizepi** [FlaxEngine/FlaxEngine#2256]
**Issue description:**
There are visual glitches when using terrain in editor. Using wireframe view, we can see the vertices positions are sometimes incorrect.

**Steps to reproduce:**
- Import a heightmap image in Hdr RGB format, without compression
- Open a scene
- In menu bar, select Scene->Create Terrain
- Assign imported heightmap
- Press create
- Navigate in the terrain using editor camera
- Observe there are some visual glitches
- Enable Debug View->Wireframe
- Observe the verteices are not correctly positioned where the glitches occur

**Minimal reproduction project:**
[TerrainBug.zip](https://github.com/FlaxEngine/FlaxEngine/files/14323344/TerrainBug.zip)
Already at a buggy position, just rotate the camera and observe the visual glitch.

**Flax version:**
1.7.2

**Comment by mafiesto4** [comment]
Fixed in e5f0e05d43f3359cd5fdf1eaaab7096b93ca6103.
