### ISSUE TITLE
Particle system crash

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#226]
The particle system crash related to infinity seems to have been resolved for the most part, but I still get this crash from time to time.
I have been building the engine using the source files in Github.
![image](https://user-images.githubusercontent.com/35228400/107472710-8b9c4080-6bc3-11eb-8f86-2910cca35757.png)

**Comment by mafiesto4** [comment]
I finally was able to reproduce it and fix it! The problem was that particle data was initialized but just for the first spawned particle. So if emitter spawned 10 during frame the reaming 9 were using dirty memory with some INF numbers.
