### ISSUE TITLE
DebugDraw.DrawText() consistently crashes

### ISSUE THREAD

**Issue by envision3d** [FlaxEngine/FlaxEngine#2260]
**Issue description:**
Started occurring today.

`Font.cpp:75`
![image](https://github.com/FlaxEngine/FlaxEngine/assets/17469837/42219b98-dd47-479f-bcb8-adfcdada4462)

**Comment by mafiesto4** [comment]
Should be fixed in db65b8037d8ffd59324a2015d5cba6cff57db26d.

**Comment by envision3d** [comment]
Confirmed.
