### ISSUE TITLE
Terrain physical materials do not persist after an editor reload.

### ISSUE THREAD

**Issue by Menotdan** [FlaxEngine/FlaxEngine#2262]
**Issue description:**
When I paint the splatmap and immediately run my test case, I can read physical materials from the terrain correctly using raycasts. However, if I restart the editor, the materials no longer read correctly until I paint again.

**Steps to reproduce:**
1. Download the test project in the plugin.
2. Notice the terrain has a splatmap painted with green and blue sections.
3. Open the test scene, and click on "Generate" in the PLCT volume.
4. You will notice debug points get drawn on the box collider, but not on the terrain. The terrain filter is looking for the physical material tagged "Stone". If you check the physical materials list on the terrain, it shows PhysMat1, which is tagged "Wood", and PhysMat2 which is tagged "Stone".
5. Now, paint like half of the section inside the PLCT Volume with layer 1 on the terrain. Click generate again, and you will see points being drawn on the green area.

Reloading the editor will result in the drawn section being broken again.

(hopefully this isn't my fault like last time lol)

**Minimal reproduction project:**
https://github.com/Menotdan/PLCT

**Flax version:**
master f8d9817911d182fa09cc5125e49abcb24de24b5a

**Comment by mafiesto4** [comment]
I think that's because that terrain was created before Physical Materials feature was added and the cooked collision doesn't contain physical material ids baked into PhysX heightfield..

Fixed in 5ec737ef800a4a89f5358172311b71e86f64d068.

**Comment by Menotdan** [comment]
@mafiesto4 This is broken again, can you reopen it?

**Comment by mafiesto4** [comment]
I tested on the current `master` and layers ar properly assigned to physx heightfield.
