### ISSUE TITLE
Inconsistency in the appearance of Materials when viewed through a transparent surface

### ISSUE THREAD

**Issue by Pikanchion** [FlaxEngine/FlaxEngine#2271]
**Issue description:**
`Material`s, when viewed through a transparent surface, have inconsistent appearances. The behaviour of said inconsistencies appear to vary by type of `Actor`, but always flips between two states. Judging only from visual inspection, one appears to act as if the `Material` were "Lit" and the other as if it were "Unlit".

Examples:
Each individual `SpriteRender` randomly chooses between "Lit" or "Unlit" on every serialization (i.e. on `Scene` Loading, on Play, and on Stop).
`Model`s, on the other hand, seem to randomly choose their state once per project load, and do so as a collective, i.e. if the project is opened and any `Model` is displaying the `Material` as "Unlit", then all of them will display it as "Unlit", and this will persist until the next opening of the project regardless of `Scene` changes, Play, or Stop actions.

**Steps to reproduce:**
1. Create a `Material` and assign it to one or more `Actor`(s).
2. Create a transparent `Material` and assign it to another `Actor`, placed between the `Camera` and the `Actor`(s) created in the first step.
3. Save/Load the project, enter/exit Play, or perform other actions and observe the `Actor`s created in the first step.

**Minimal reproduction project:**
[MyProject1.zip](https://github.com/FlaxEngine/FlaxEngine/files/14376959/MyProject1.zip)
This project contains a simple scene of multiple "A"s as either `SpriteRender`s (foreground, with solid backdrop) or as default "Plane" `Model`s (background, floating). Every project load, `Scene` change, Play, or Stop, each individual `SpriteRender` "A" will pick a state at random (though there appears to be a loose tendancy for the majority to copy the state of the `Model` "A"s). Every project load, the `Model` "A"s pick a state as a group.

![Untitled-1](https://github.com/FlaxEngine/FlaxEngine/assets/137227636/6e512b6d-25b5-4267-b928-8f12f8d49af2)

**Flax version:**
1.7.2

**Comment by mafiesto4** [comment]
That comes from the transparency sorting algorithm which uses distance to the object position (over view plane). In this case, there is some noise coming from objects batching keys generation but even without it there is still this issue. it's impossible to decide which object should be rendered first due to close proximity of them. Implementing Ordered Independant Transparency could solve this but it comes at perf cost.

**Set `Sort Key` to `-1` on that plane.** to fix this problem.

**Comment by mafiesto4** [comment]
Additionally improved sorting by distance in 499ef51875b9febee667d8c4d9bc52e13d9a89bd.
