### ISSUE TITLE
[Suggestion] Automatic assignment of Materials from Material Entries to submeshes in Model Prefab, when the model is imported without Materials

### ISSUE THREAD

**Issue by ElevenArt** [FlaxEngine/FlaxEngine#2275]
When I import a model without a material via Model Prefab and assign the Materials I previously created in Flax to all sub-meshes  Actors via Material Entry in Prefab Editor, save and click Reimport, I get a model without Materials. I found that when I assign materials directly to the submeshes through the Model Editor, it automatically assigns all the materials to the Material Entries in the Model Prefab editor. After Reimport, asigned Materials preserved.

https://github.com/FlaxEngine/FlaxEngine/assets/154741707/5c6252fe-6816-4a5b-a4c4-1072fd5e1e8f

This is quite complicated workflow. It would be better if Materials assigned to Material Entries were automatically assigned to sub-meshes as well.. And it should also work like this if Materials assigned to Material Entries via Model Prefab instance in Properties panel. Then reimporting of materials in the Model Prefab would be much easier.

Related to #1973 

Test model, Flax materials:
[TestModel.zip](https://github.com/FlaxEngine/FlaxEngine/files/14393246/TestModel.zip)

Flax version:
Master branch (23.2.2024)

**Comment by mafiesto4** [comment]
93d9b9877cc5fa1b2f52c4d91fb8c0b9cb7a50d4 fixes this issue by preserving any local changes applied to the prefab (eg. shadows casting, materials, etc)
