### ISSUE TITLE
Private visual script members still have a per-instance value when added to an actor.

### ISSUE THREAD

**Issue by Menotdan** [FlaxEngine/FlaxEngine#2276]
**Issue description:**
If you make a private variable on a visual script, and add it to an actor, it will have a hidden value that overrides the value set in the visual script.

**Steps to reproduce:**
1. Create a visual script.
2. Add a private `int` variable.
3. Add a debug log in `OnEnable()` to log the variable.
4. Set the variable to some number, save it, and then add the script to an actor.
5. Change the variable in the visual script, and then enter playmode, you will notice the log still shows the old value.
6. Re-add the script, the value logged will be correct.

**Flax version:**
master 318b00c617140b487c8cb60ee46fb44bd7545338

**Comment by mafiesto4** [comment]
Fixed in cc019520590428ec896fab37e0079a386036dec5.
