### ISSUE TITLE
Blur Panel blurs everything, including stuff in front of it.

### ISSUE THREAD

**Issue by ghost** [FlaxEngine/FlaxEngine#228]
**Issue description:**
The blur panel UIControl actor blurs everything in front and behind it.
Expected: The blur panel should not blur stuff in front of it, and should not blur gizmos.

**Steps to reproduce:**
1) Get a blur panel in the scene view.
2) Create a bunch of gizmos and objects in front of it.
3) Move the camera around.

**Minimal reproduction project:**
Any project should work.

**Flax version:**
Issue occured on version 1.0.6126.

https://user-images.githubusercontent.com/69793166/107569920-86ee8100-6bf1-11eb-9704-c997825fd39c.mp4

**Comment by mafiesto4** [comment]
It works fine for me. In both `World Space` and `Camera Space` modes for UI Canvas.
![image](https://user-images.githubusercontent.com/3464853/107881922-d9c48300-6ee6-11eb-8837-280dc2f57ffe.png)

Could you provide that simple project to reproduce it?

**Comment by Thev2Andy** [comment]
[Project.zip](https://github.com/FlaxEngine/FlaxEngine/files/6011632/Project.zip)

**Comment by mafiesto4** [comment]
Unchecking `Ignore Depth` option on UI Canvas will make it use depth buffer thus prevent blurring objects before the canvas:
![image](https://user-images.githubusercontent.com/3464853/181283263-3e023980-9de7-47b6-ba59-e6bd754a0ff0.png)
