### ISSUE TITLE
Potential issue with PlayerController/PlayerPawn

### ISSUE THREAD

**Issue by envision3d** [FlaxEngine/FlaxEngine#2282]
I'm not sure if this is an issue, nor if it belongs here vs. in the `NetworkTransform`, but I think it belongs here.

When I add the below code to my Pawn class (which also has a `NetworkTransform`) and observe the values that get output while moving a non-local pawn, I see a steady stream of non-zero values as expected, but I see a number of `0` values mixed in between when there shouldn't be any.

Given the `NetworkTransform` is general and not tied specifically to a `CharacterController`, I'm assuming `Velocity` is being updated somewhere within the Arizona code.

I'm wondering if this could be having an impact on the smoothness of movement of non-local pawns if `Velocity` is used to interpolate between updates.

```
public override void OnUpdate()
{
    if (PlayerState.NetworkClientId != NetworkManager.LocalClientId)
    {
        Debug.Log(">>> " + Controller.Velocity.Length);
    }
}
```

**Comment by mafiesto4** [comment]
Character Controller physics are not fully replicated over network so maybe that velocity could be invalid in some cases. I think it would be better to collect some value and calculate moving average.

Also, there is a task on a roadmap to add `NetworkRigidBody`, similar to `NetworkTransform`, where more physics state (like velocity) could be synced. Then similar solution would make sense for characters.
