### ISSUE TITLE
Prefab invalid parent object when child hierarchy changes

### ISSUE THREAD

**Issue by artzn** [FlaxEngine/FlaxEngine#2285]
**Issue description:**
When a prefab hierarchy is changed, an error occurs in scenes that use it. This causes many cascading issues when interacting with the prefab from code. One example when using Level::FindActor on one of the changed child actors may cause the StringUtils::Compare(const Char* str1, const Char* str2) to pass null into str1. The issue is not that Level::FindActor allows that to happen but that the scene has some weird data.

**Steps to reproduce:**
1. Create a prefab with 2 child actors, save.
2. Create two scenes.
3. Place the prefab in one scene, save.
4. Open the scene that does not have the prefab.
5. In the prefab, parent one of the actor's to the other actor, save.
6. When opening the scene that contains the prefab there will be an error similar to: `[Info] Object {id_1} has invalid parent object {id_2} -> {id_3} (PrefabObjectID: {id_4}, PrefabID: {id_5}, Path: {file path to prefab})
`

https://github.com/FlaxEngine/FlaxEngine/assets/87765703/36ee27d7-661f-4fc9-83ea-7a01c99e353f

**Minimal reproduction project:**
[Prefab_Hierarchy_Child_Issue.zip](https://github.com/FlaxEngine/FlaxEngine/files/14448515/Prefab_Hierarchy_Child_Issue.zip)

**Flax version tested:**
launcher 1.7.2, github 1.8, github master.

**OS:**
Microsoft Windows 11 Pro 10.0.22631 Build 22631

**Comment by mafiesto4** [comment]
Actually that's just informative log (bot a warning nor error) as when loading prefabs or scenes we validate the hierarchy in case someone edited prefab used there. If you open that scene and resave it it will be serialzied with proper structure and log will be gone.
