### ISSUE TITLE
Very short Audio Clip causes UI divide by zero error

### ISSUE THREAD

**Issue by artzn** [FlaxEngine/FlaxEngine#2286]
**Issue description:**
When a very short audio clip is opened the audio clip viewer has a divide by zero error. This impacts adjusting the re-import options if someone wants to change the "Is 3D" for example.

**Steps to reproduce:**
1. Import the included audio `Pip2.wav` from the minimal project zip.
2. Remember where your other tabs are.
3. Open the audio clip.
4. Close or switch to a different tab so the audio clip view is not rendered so the log is not getting spammed.
5. Check the output log.

https://github.com/FlaxEngine/FlaxEngine/assets/87765703/da31fdce-07a5-4ee8-a8b5-6ae350c12013

**Minimal reproduction project:**
[Very_Short_Audio_Clip_Issue.zip](https://github.com/FlaxEngine/FlaxEngine/files/14449996/Very_Short_Audio_Clip_Issue.zip)

Github does not support uploading wav files but the sound effect is included in the minimal reproduction project zip.

**Sound Effect being played (remember to unmute):**

https://github.com/FlaxEngine/FlaxEngine/assets/87765703/7400c586-af19-41d4-b9f2-0af1653482dc

**Flax version tested:**
launcher 1.7.2, github 1.8, github master.

**OS:**
Microsoft Windows 11 Pro 10.0.22631 Build 22631

**Comment by artzn** [comment]
To note: Other media players' playback bugs for short audio clips are unrelated to this UI issue. Attached is Flax Engine playing back the sound (remember to unmute).

https://github.com/FlaxEngine/FlaxEngine/assets/87765703/b4974b2c-a27a-429c-9ab5-bcf224f75850

**Comment by mafiesto4** [comment]
Fixed in 0604a0393dc534bcd9793fb19368633ded32388c.
