### ISSUE TITLE
Funky behavior with scales and rotation when changing actor hierarchy.

### ISSUE THREAD

**Issue by Menotdan** [FlaxEngine/FlaxEngine#2297]
**Issue description:**
I have a rotated and non-uniformly scaled table, which I would like to child some objects to. However, when I do so, their position and scaling is messed up and becomes unusable.
https://streamable.com/ijnjet

**Steps to reproduce:**
1. Create an empty actor.
2. Rotate it around the Y axis by some small amount, maybe 15 degrees.
3. Scale the actor by some non-uniform set of numbers.
4. Create a cube actor and rotate it a bit.
5. Add the cube as a child of the empty actor, the transformation will break.

**Minimal reproduction project:**
[break scale.zip](https://github.com/FlaxEngine/FlaxEngine/files/14479600/break.scale.zip)
(under "Repro" in the main scene, take the empty actor with children and child it to the empty actor without children)

**Flax version:**
master e68c7366071df0615d1d8f6f1fc70dc5e9f7a6ad

**Comment by Menotdan** [comment]
@mafiesto4 is there a reason this is on 1.9? I think this is a pretty big bug considering it's basic transformation operations, those should probably be stable for a release version lol

**Comment by mafiesto4** [comment]
Ah okay. This will account for more delay on the update tho.

**Comment by Menotdan** [comment]
This might be a regression from 9a21cfd092621fdb5bc8bfe31e6d968c8095094a.

**Comment by mafiesto4** [comment]
I don't know how to fix this. Clearly `Actor::SetParent` should calculate `_localTransform` differently when `worldPositionsStays=true` but `Transform` is limited to a single Translation+Rotation+Scale so when changing transformation hierarchies this might not be possible to preserve transformation properly. We would need to migrate to matrix-only usage representing any linear transformation. I tested this and Unity seems to not handle it properly as well so it's not an obvious issue.

**Comment by Menotdan** [comment]
I've asked in the Unity discord about this issue, and apparently it is expected behavior or at least a known problem that needs to be worked around. Maybe this can be closed.
