### ISSUE TITLE
Are there any plans on serializing type info?

### ISSUE THREAD

**Issue by asusralis** [FlaxEngine/FlaxEngine#23]
It seems Flax is already more capable in most ways when it comes to serialization compared to Unity - notably properties, most c# objects, etc. However, I'm coming from using Unity w/ Odin Inspector, and one of the strengths of that is being able to serialize type info. As far as I can tell peeking in a prefab, it doesn't do this. Is there any consideration on implementing this?

**Comment by mafiesto4** [comment]
As you can easily spot in the engine and editor codebase we use full typaname for types identification (eg. 'FlaxEngine.PointLight').
For serialization in C# we have _Newwtonsoft.Json_ which can serialize type reference, for serialization in C++ the _ScriptingType_  could be used to save typeinfo.

We do have type reference picker for properties:
```cs
[TypeReference(typeof(FlaxEngine.Object)]
public Type MyType;
```

**Comment by asusralis** [comment]
I was speaking about prefabs. If you have a property in a script file that is a list of Fruit and have a child Apple class, there is no way to add an apple to the list in the editor.

**Comment by mafiesto4** [comment]
Actually this can be impl with Custom Editor inheriting from `ObjectSwitcherEditor` as shown in this example:
https://github.com/FlaxEngine/FlaxEngine/blob/master/Source/Editor/CustomEditors/Editors/IBrushEditor.cs

It simply adds a picker for selecting object type to edit. I'm not sure if it will work out for a list of objects but can be used to easily configurate editing for those inherited objects (like property of type `Fruit` and options to setup it as `Apple`, `Orange`...).
