### ISSUE TITLE
Crash when selecting things in the Editor during Play

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#230]
I experience the following crash when trying to select things during runtime in the Editor. 

I've recorded a video to repeat the process.
This happens 100% of the time when performing these exact actions with my game.
https://drive.google.com/file/d/1eNuAB_ffo9bqetDB48oSDmRIsWklbaJW/view?usp=sharing

There was no memory dump files, only the log:
[Log_2021_02_11_13_50_48.txt](https://github.com/FlaxEngine/FlaxEngine/files/5962963/Log_2021_02_11_13_50_48.txt)

Even though there was no memory dump, I've uploaded the Editor files here just in case it helps:
https://drive.google.com/file/d/1XgGJlfHeJRj3eEnEtt6dm4L6cScaoYER/view?usp=sharing

**Comment by GoaLitiuM** [comment]
Fixed in #236
