### ISSUE TITLE
Particle Depth not correct relativ to other particle effects.

### ISSUE THREAD

**Issue by schmidt-florian** [FlaxEngine/FlaxEngine#2306]
**Issue description:**

If both particle effects have the same sort order priority, the other particle effect is always in front.
In the case of the sample project, the GPU Particles are always in front of the Light Particles and Model Particles Demo.

![image](https://github.com/FlaxEngine/FlaxEngine/assets/14238126/0c743093-5458-4d0d-99f2-bccdecafe734)

**Steps to reproduce:**
Open the Particle Sample Project and stand like in the Picture
For better visualization, allow more GPU particles to spawn.

**Flax version:**
1.7.2

**Comment by mafiesto4** [comment]
Fixed in 499ef51875b9febee667d8c4d9bc52e13d9a89bd.
