### ISSUE TITLE
Duplicating objects with weird selection order causes double actors with the same GUID.

### ISSUE THREAD

**Issue by Menotdan** [FlaxEngine/FlaxEngine#2309]
**Issue description:**
When selecting some actors in a weird order, and then duplicating them, the child actors are copied with the same GUID, which causes a bunch of issues all around the engine.

**Steps to reproduce:**
1. Create a new project and open the default scene.
2. Using the scene view:
3. Click on the corner of the 'Cube' to select the Box Collider instead of the mesh.
4. Ctrl+Select the 'Floor' so it actually selects the mesh.
5. Ctrl+Select the 'Cube' mesh.
6. Ctrl + D to duplicate the actors.
7. Check the child actors of the duplicated actors, and one of them will have two box colliders. These have the same GUID.
8. Check the output log and you will notice errors about matching GUIDs and duplicate objects.

Bonus bug:
Create a prefab out of the parent object that has duplicated box colliders, and it will crash. There is not proper handling for duplicated objects as there is in scene loading. I'm attempting to fix this myself but having it fixed would be good.

**Flax version:**
master @ 2e305da286e194920c9e70652fc6265708416ce7

**Comment by mafiesto4** [comment]
Fixed in 56a33e4c98f5a81770f298609af1507f19a24430.
