### ISSUE TITLE
Marking a collider as trigger nulls out the overlapping collision

### ISSUE THREAD

**Issue by W2Wizard** [FlaxEngine/FlaxEngine#231]
**Issue description:**
When having 2 colliders and marking on as trigger, that trigger will effectively null out that part of the collision of the other collider, this could also be maybe be a useful feature perhaps sort of like the additive and subtractive CSG Brush just with collision?

**Steps to reproduce:**
1. Create a collider (Box preferably)
2. Add another collider
3. Mark the second one as trigger
4. Have some physics object pass through the trigger
5. It broke the matrix

https://user-images.githubusercontent.com/63303990/107696742-a00b3680-6cb2-11eb-94bb-de1f73e5e287.mp4

**Flax version:**
1.0.6216

**Comment by mafiesto4** [comment]
Could you describe it a little more? I created 2 boxes that overlap and one of them is a trigger (the upper one in the vid) and the ball goes through the trigger but collides properly.

https://user-images.githubusercontent.com/3464853/107883609-324c4e00-6ef0-11eb-91d4-f2ed82773145.mp4
