### ISSUE TITLE
Bone sockets transforms do not update when animation graph is assigned. 

### ISSUE THREAD

**Issue by Muzz** [FlaxEngine/FlaxEngine#2341]
**Issue description:**
Bone sockets update their transforms when you set which bone they are looking at,  but they don't if even the simplest blank graph is assigned. Once it's assigned, even if it's then unassigned they will no longer update at all. 

Added the project here. 
[BoneSocketBug.zip](https://github.com/FlaxEngine/FlaxEngine/files/14662931/BoneSocketBug.zip)

Assign the empty graph and notice how the socket transform no longer updates. 

**Minimal reproduction project:**

**Flax version:**
Master. 

https://github.com/FlaxEngine/FlaxEngine/assets/2074204/e571272a-4cc4-4673-a7fe-7c253bfd5a21

**Comment by Muzz** [comment]
Ok this is more odd. If you assign the graph first, and THEN the rig, it works fine. It's only if you assign gun rig then graph that it breaks

**Comment by mafiesto4** [comment]
Fixed in a3c088bb05474be1d5927e32878580dfee648520.
