### ISSUE TITLE
'End' key in editor fields appear to move the actor for some reason.

### ISSUE THREAD

**Issue by Menotdan** [FlaxEngine/FlaxEngine#2342]
**Issue description:**
When I'm trying to edit a position of an actor, for example, if I hit 'End' on my keyboard to go to the end of the text (very common text editing shortcut), that part works, but it also moves my actor up by some unknown amount.

https://github.com/FlaxEngine/FlaxEngine/assets/32620310/bd5cca01-3e28-4155-ad0d-ab49a9cc98ce

You can also see in this video that there are several steps to this action, as when I spam undo, it changes the Y position multiple times before reverting to the original position.

**Flax version:**
master at 9e11d45c1cb2fa6faae02c989a4ca10fa004b380

**Comment by mafiesto4** [comment]
Fixed in 70b2e4aa5a69f67812853a03a599c9e780ace06a.
