### ISSUE TITLE
Inconsistent naming in Rectangle.

### ISSUE THREAD

**Issue by z1dev** [FlaxEngine/FlaxEngine#2345]
**Issue description:**

I'm always confused for a second when I try to access the corner positions of rectangles. For example it has UpperLeft (accessed by GetUpperLeft in C++) but not LowerLeft. Instead it has BottomLeft. To not break compatibility I suggest keeping the original names, but make these all work:

Existing: UpperLeft, UpperRight, BottomLeft, BottomRight
Add these: TopLeft, TopRight, LowerLeft, LowerRight.

I can make the PR if this is accepted, I just want to make sure I'm not requesting something stupid.

**Comment by mafiesto4** [comment]
Yeah it makes sense to add those additional variants to keep the naming consistent.
