### ISSUE TITLE
Linux editor crash when do some random actions

### ISSUE THREAD

**Issue by Snakemonster** [FlaxEngine/FlaxEngine#2356]
**Issue description:**
Linux editor when making some random things like maximizing whole engine window, changing Editor windows size, detaching tab to window, entering play mode several times, etc. 

**Steps to reproduce:**
Open some project that have on scene some stuff like sunlight, directional light, skybox, etc. On scene where only camera, actor and UI work without crash. 

**Flax version:**
latest master

There is log file from Debug mode
[Log.txt](https://github.com/FlaxEngine/FlaxEngine/files/14726506/Log.txt)

P.S. I have removed parts below from log for more comfortable view:
[Info] [Vulkan] Validation Error:931531651(VUID-VkShaderModuleValidationCacheCreateInfoEXT-validationCache-parameter) Validation Error: [ VUID-VkShaderModuleValidationCacheCreateInfoEXT-validationCache-parameter ] Object 0: handle = 0x6402de8807900 type = VK_OBJECT_TYPE_INSTANCE; | MessageID = 0x37860b83 | vkCreateShaderModule(): pCreateInfo->pNext<VkShaderModuleValidationCacheCreateInfoEXT>.validationCache Invalid VkValidationCacheEXT Object 0x6402df7744400 The Vulkan spec states: validationCache must be a valid VkValidationCacheEXT handle (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkShaderModuleValidationCacheCreateInfoEXT-validationCache-parameter)

**Comment by RuanLucasGD** [comment]
I can confirm it. I can't use editor, it's crash when i resize the viewport.


https://github.com/FlaxEngine/FlaxEngine/assets/79365912/7e4aa9b6-a989-47d1-981d-76f5d0601921

**Comment by Zode** [comment]
Can confirm crash from viewport resize also, seems like the stencil isn't updated in time for the rendering and the height difference causes it to invalidate itself -- purely educated guess based on the debug vulkan output.
git bisect gave me hash `8488a8d387461cb1932158fc461eedd025aa8460` as the first bad commit and its all changes relating to stencil stuff, so definitely a regression as versions prior to that have no issues at all.

**Comment by mafiesto4** [comment]
Fixed in 705856da24b9bb8ba8c39b74087ef7dc3b09ba01.
