### ISSUE TITLE
Visual Script. 'Sin (Double)' function.

### ISSUE THREAD

**Issue by MajesticGames** [FlaxEngine/FlaxEngine#2359]
**Issue description:**

In Visual Script, when adding the 'sin (double)' function and multiplying it by a value, the result obtained is the first value indicated in the 'multiply' node. In the example shown in the figure, the result of the 'sin' function displayed in the 'log' is 0.8414709848078965. After multiplication, the result is 150 and not 150 * 0.841...

**Steps to reproduce:**
![sin_double](https://github.com/FlaxEngine/FlaxEngine/assets/33732701/228da886-4a75-4f6c-aa38-50810ac9092c)

**Flax version:**
1.8

**Comment by mafiesto4** [comment]
Fixed in 1864574a92e083da413b75b3b4ff07c83ae5d739.
