### ISSUE TITLE
Blur panel drawing over prefab window in UI editing mode.

### ISSUE THREAD

**Issue by Menotdan** [FlaxEngine/FlaxEngine#2361]
**Issue description:**
A blur panel in my UI widget is drawing over the prefab editor window when I pan so they overlap.
![image](https://github.com/FlaxEngine/FlaxEngine/assets/32620310/61a3f955-d18c-414a-9fba-ad104d364d5c)

**Steps to reproduce:**
1. Create a new widget.
2. Add a fullscreen blur panel.
3. Zoom in and pan it so the panel is overlapping with the left-hand side of the prefab window.

**Flax version:**
master at 4cd788cedca1a8ba51db3ba34220dd475ff00f44

**Comment by xxSeys1** [comment]
@mafiesto4 Wasn't this fixed already? Maybe "accidentally" in #1575 ?
I am no longer able to replicate this on the latest master, though this issue still has the 1.10 milestone assigned.
