### ISSUE TITLE
Animation graph uses Base model for bones, not the assigned rig. 

### ISSUE THREAD

**Issue by Muzz** [FlaxEngine/FlaxEngine#2364]
**Issue description:**
In the animation graph window, there is a base model input, but when you are using the animation graph in engine, you put a graph on a skinned mesh. 

In many cases you want to use the same graph across different objects, because rigs have the same setup, in terms of heirachy and names, but not in placement. 

This means that it will use the wrong bone placement if you put the graph on a different valid rig.  

**Flax version:**
Master

**Comment by Muzz** [comment]
Now it's debatable it this is a valid use-case of anim graphs as you ideally should use the animation graph functions, but it's possible to do this and break things, so it's worth discussing, even if it's a way to prevent this use.

**Comment by mafiesto4** [comment]
That's on purpose so there can be a base skeleton for multiple characters in a game and then different characters can just swap the mesh. I know that we share mesh and skeleton in a single asset. Additionally, the model that is used to play Anim Graph can use skeleton remapping to translate source animated pose from graph onto the different pose of the actual mesh.
