### ISSUE TITLE
Transparent Material instances use only one Environment Probe

### ISSUE THREAD

**Issue by bertodelrio256** [FlaxEngine/FlaxEngine#2365]
**Issue description:**
Transparent Materials shared by multiple objects will only use the last Environment Probe seen by an object. I have 2 glass pipes that share the same glass material on 2 locations in the scene. in one location, the glass is using the probe that the other one outside is using. if i delete all of the env probe cubemaps and just rebake the hallwall one, the probes will use that one, but when i bake the outdoor probe, the ones in the hall will switch to the outdoor probe.

![image](https://github.com/FlaxEngine/FlaxEngine/assets/98141558/141faad6-583f-4986-9395-7f1a0452bfe0)

![image](https://github.com/FlaxEngine/FlaxEngine/assets/98141558/db02bed0-fb99-4bf9-b26f-6b83c9157cb3)

**Steps to reproduce:**
create a shiny transparent surface material and assign it to 2 spheres. place one sphere near one env probe and another near a different probe. bake both probes and note only one probe displays on both (usually the last baked)

**Minimal reproduction project:**

**Flax version:**
1.7.6407.2

**Comment by mafiesto4** [comment]
That's the current limitation of the forward renderer. We could add option to material to specify the max count of supported probes (eg. `4`) for higher quality lighting.

**Comment by bertodelrio256** [comment]
ahh i see. well perhaps its better to just use separate material instances for them in my case.

**Comment by bertodelrio256** [comment]
thanks
