### ISSUE TITLE
World Space UI Canvases don't clip Container Control child elements

### ISSUE THREAD

**Issue by lifeformed** [FlaxEngine/FlaxEngine#2371]
When using a UI canvas in world space, it doesn't clip children correctly.  Specifically, container controls like panels don't clip the children.

Here's what it looks like.  The "child" label doesn't have a panel parent, while the "child of panel" one does.
![image](https://github.com/FlaxEngine/FlaxEngine/assets/1567199/1f84176a-10fe-4335-af89-da4ce5775ba5)

Here's the same thing but in screen space. It clips correctly:
![image](https://github.com/FlaxEngine/FlaxEngine/assets/1567199/07ed37b7-d40c-4e96-830e-1ea9fca60a36)

Here's the object as a prefab:
[test.zip](https://github.com/FlaxEngine/FlaxEngine/files/14789162/test.zip)

**Comment by mafiesto4** [comment]
Fixed in 6113af2dc19bf337dfc49319e17219936314b53f.
