### ISSUE TITLE
[Suggestion] Add Visual Feedback for Gizmos if Actor is Static

### ISSUE THREAD

**Issue by schmidt-florian** [FlaxEngine/FlaxEngine#2373]
**Issue description:**

It already had people confused that the gizmo gives no visual feedback that it can be moved. (#1159)

Render the gizmos transparent if the object is static.
Or if transparent is an issue, the gizmo color could be all grey.

Additional a small (maybe transparent text) could it make idiot-proof... [or at least near that.](https://forum.unity.com/threads/transform-tool-handles-greyed-out-says-static.225447/)

**Steps to reproduce:**
Have a Static Actor
Press Play
Try to move the actor via gizmos.

**Flax version:**
master

**Comment by Menotdan** [comment]
Agreed. Even though I know it's the case I constantly make this mistake lol
