### ISSUE TITLE
Shader compilation failed with buildin nodes if connection is used for PS/VS

### ISSUE THREAD

**Issue by schmidt-florian** [FlaxEngine/FlaxEngine#2376]
**Issue description:**

I tinkered around with the shader and found a bug.
The issue is (i think) that i try to use a Frac Shader Value in the Vertex Shader side.
When I try to use for the non-sense reason the computed output for normal in position offset or world displacement, the compilation fails.

I think this should be possible even if it makes no sense; it would probably mean it must produce double code for VS and PS.

**Steps to reproduce:**

Create a project
Add the provided shader file.
Open the shader and try to connect as this picture shows:
![image](https://github.com/FlaxEngine/FlaxEngine/assets/14238126/daaebf70-aa77-4469-ad67-b79326441101)

**Minimal reproduction file:**

[Ground Shader.zip](https://github.com/FlaxEngine/FlaxEngine/files/14806528/Ground.Shader.zip)

**Flax version:**

master 0b80122

**Comment by mafiesto4** [comment]
Fixed in 3696501050f48f5637cd5c86706fcaeaeb402f4e.
