### ISSUE TITLE
Shadow bug.  Wird shadow behavior with particle system.

### ISSUE THREAD

**Issue by zuksoon** [FlaxEngine/FlaxEngine#238]
**Issue description:**
Shadow bug.  Wird shadow behavior with particle system. Video:

https://user-images.githubusercontent.com/58657263/107851472-7e24c780-6e0a-11eb-9156-7d44bf9396b8.mp4

**Steps to reproduce:**
Create paricle system with smoke preset.

**Minimal reproduction project:**
[BasicTemplate.zip](https://github.com/FlaxEngine/FlaxEngine/files/5975736/BasicTemplate.zip)

**Flax version:**
1.0

PS.I tried to find settings but i can't find it.   Ps. Those "Graphic Settings"
 
![obraz](https://user-images.githubusercontent.com/58657263/107851460-6ea57e80-6e0a-11eb-8cf9-d38a3a9ad7f5.png)

are kinda... not telling anything. There is no control over the light settings, e.g. low / high resolution, cascade settings etc. Maybe I'm blind but ... 
(Ps2. I came from unity)

**Comment by mafiesto4** [comment]
Should be fixed in the recent master (0a474772900d97b62c62ae3c0df41d8d497b7559).

That's how to works now:
![shadows](https://user-images.githubusercontent.com/3464853/125264911-9985f700-e304-11eb-9e88-3388350ecbbd.gif)
