### ISSUE TITLE
Calculation of SplineLength wrong

### ISSUE THREAD

**Issue by schmidt-florian** [FlaxEngine/FlaxEngine#2385]
**Issue description:**

The calculation of the SplineLength is wrong. My test calculation does not include bezier for simplification but is at least right for linear points. However, my issue is that the built-in method does not correctly calculate the linear point distance.

EDIT: GetSplineSegmentLength calculates also the wrong length for me.

![image](https://github.com/FlaxEngine/FlaxEngine/assets/14238126/e8fa84e6-8a50-4ff7-b113-a32cb5306c51)

**Steps to reproduce:**

1. Open Attached Project
2. Open `Content/Scene`
3. Inspect Spline Actor

**Minimal reproduction project:**

[Test Blank.zip](https://github.com/FlaxEngine/FlaxEngine/files/14822961/Test.Blank.zip)

**Flax version:**

1.8

**Comment by mafiesto4** [comment]
Fixed in abb684aed2365686d4e56a928a754aae78590148.
