### ISSUE TITLE
Text bug in particle system

### ISSUE THREAD

**Issue by zuksoon** [FlaxEngine/FlaxEngine#239]
**Issue description:**
Overlapping text in particle system editor

**Steps to reproduce:**
Create new particle system. Add folder or particle emitter.  

https://user-images.githubusercontent.com/58657263/107851543-1fac1900-6e0b-11eb-8620-c78e694a7369.mp4

**Flax version:**
1.0

**Comment by mafiesto4** [comment]
Fixed by 40a3fb96a20bc13a3459de455a50df5c8e36c114.
