### ISSUE TITLE
Prefab fields of objects in the scene randomly not reverting to prefab properly.

### ISSUE THREAD

**Issue by Menotdan** [FlaxEngine/FlaxEngine#2399]
**Issue description:**
Sometimes various operations on prefabs stop working properly between the scene and the prefab. In this case it failed to revert to the prefab multiple times. There was no errors or warnings in the output log. 

https://github.com/FlaxEngine/FlaxEngine/assets/32620310/a46cc070-90cb-4c4c-b1f1-8f41b5a0c1e8

**Flax version:**
master at ce07edd1ec093fa3c7696c29d401d0292b0005c5

**Comment by mafiesto4** [comment]
Fixed in 16554fe742b2264e220f06f4fbc9ec0b7422e0a2.
