### ISSUE TITLE
Visual Studio 2019 16.8.5 unable to debug projects

### ISSUE THREAD

**Issue by LCRW** [FlaxEngine/FlaxEngine#240]
**Issue description:**
Flax extension fails to attach properly to open editor when trying to debug on any generated solutions.
Race condition exists between msbuild in use by visual studio and flax editor.

**Workaround:**
inserting this:
```
if exist "%VSINSTALLDIR%\MSBuild\Current\Bin" (
  set MS_BUILD_PATH="%VSINSTALLDIR%\MSBuild\Current\Bin\MSBuild.exe"
  goto End
)
```
after ``` set MSBUILD_PATH= ``` in GetMSBuildPath.bat

***Conclusion***
The above tells it to use the same path that vs uses for detection, it is still capable of building on your required toolset thanks to ms backwards compat.
Might need more thought or testing where multiple versions of vs are installed.

**Flax version:**
1.0 and master branch

**Comment by LCRW** [comment]
Unable to reproduce in 1.1 might have been a weird edge case

**Comment by GoaLitiuM** [comment]
Sometimes the editor might not close properly and leave running in background, so the extension fails to attach to anything and launches a new instance even if you have another working instance open at the time. Was this the issue you had?
