### ISSUE TITLE
Random DDGI crash/bug with RectPack.

### ISSUE THREAD

**Issue by Menotdan** [FlaxEngine/FlaxEngine#2400]
**Issue description:**
Occasionally when I enter or exit playmode, I will get a fatal editor crash from DDGI attempting to free some data structure when it isn't in use. I don't know how to reproduce this, but I guess the fix would just be to add a check for if it's not used. Although, it not being marked as used may be the bug instead..

![image](https://github.com/FlaxEngine/FlaxEngine/assets/32620310/03640862-bb3d-4511-81c4-efbcf44365ce)
![image](https://github.com/FlaxEngine/FlaxEngine/assets/32620310/71fd27ae-fbf7-427f-a515-746d84d2a860)

**Flax version:**
master at ce07edd1ec093fa3c7696c29d401d0292b0005c5

**Comment by mafiesto4** [comment]
Fixed crash in 37a02e3a7e68187e832b3eb16b864f6bfae2b5af.
