### ISSUE TITLE
RichTextBox underlines are not displayed at the correct position.

### ISSUE THREAD

**Issue by Menotdan** [FlaxEngine/FlaxEngine#2401]
**Issue description:**
When I use the underline feature of a rich text box, it's draw too high up, covering much of the text.
![image](https://github.com/FlaxEngine/FlaxEngine/assets/32620310/932806ac-e122-496b-8b47-18b5143e0f5b)

**Steps to reproduce:**
1. Create a UI Canvas.
2. Add a rich text box, and type some text.
3. Set the underline brush to "solid color" and the underline will be drawn incorrectly.

**Flax version:**
master at ce07edd1ec093fa3c7696c29d401d0292b0005c5

**Comment by Tryibion** [comment]
Is your interface scale != 1?

**Comment by Menotdan** [comment]
> Is your interface scale != 1?

Well my editor's interface scale is, but that shouldn't be affecting the game UI, hopefully
