### ISSUE TITLE
RichTextBox freezes the engine when using broken formatting.

### ISSUE THREAD

**Issue by Menotdan** [FlaxEngine/FlaxEngine#2402]
**Issue description:**
I was using an incorrect tag by accident, and it resulted in the engine freezing when it tried to parse the text.

**Steps to reproduce:**
1. Create a UI Canvas.
2. Add a `RichTextBox`.
3. In the text box, type: `<align=center><font size=30>Information</font-size></align>`, submit the text, and it will freeze.

**Flax version:**
master at ce07edd1ec093fa3c7696c29d401d0292b0005c5

**Comment by mafiesto4** [comment]
Fixed in 56d3b4f01277b0324bafe88cd7408275a864f74a.
