### ISSUE TITLE
GameplayGlobals serialization broken

### ISSUE THREAD

**Issue by xxSeys1** [FlaxEngine/FlaxEngine#2412]
**Issue description:**

When creating a new GameplayGlobal, adding parameters and changing their values and then entering playmode, the values reset to the previous values.

It's a serialization problem from what I could find out.

In editor:
![image](https://github.com/FlaxEngine/FlaxEngine/assets/111653551/54fa668f-2ad7-4583-808e-11b3202cbafd)

In play mode:
![image](https://github.com/FlaxEngine/FlaxEngine/assets/111653551/8dfad455-4f89-4afd-acb1-9efac1fc3473)

**Steps to reproduce:**

1.) Create a new GameplayGlobal
2.) Add a new parameter
3.) Enter play mode and watch the values in the GameplayGlobal change

**Minimal reproduction project:**

[GameplayGloTest.zip](https://github.com/FlaxEngine/FlaxEngine/files/14922785/GameplayGloTest.zip)

**Flax version:**

1.8

**Comment by Menotdan** [comment]
This appears to be mitigated by restarting the editor. Definitely not ideal though.

**Comment by mafiesto4** [comment]
After editing asset and starting play mode the editor asks if we want to save those variables before:
![image](https://github.com/FlaxEngine/FlaxEngine/assets/3464853/a822beaa-bd0e-4365-b583-b60097d0cffb)

I guess, then sure can decide if wants to use modified values or revert back to the asset as Gameplay Globals can be modified at runtime by game scripts so we want to separate them from editor-state while allowing to preview/edit simulated values in play mode.
