### ISSUE TITLE
Improve missing asset warning message. 

### ISSUE THREAD

**Issue by Muzz** [FlaxEngine/FlaxEngine#2414]
**Issue description:**
Often we get these warnings, 

![image](https://github.com/FlaxEngine/FlaxEngine/assets/2074204/ee952ed8-056f-4798-b671-b7195862e592)

but we don't get more information  about what asset is referencing it, so it makes it a time sink tracking down the source of the warning. 
We should improve this message

**Flax version:**
Master

**Comment by Menotdan** [comment]
#2368 implements the beginnings of that.

**Comment by Muzz** [comment]
Just dropping a comment here to bump this is actually becoming a huge time sync for us. Working on a team using git and LFS means that it's easy for broken references to happen, and it's very difficult to track down what broke when we pull. it's probably not a huge issue if working by yourself, but on a team this is a frustrating thing. 

@Menotdan any updates?

**Comment by Menotdan** [comment]
> Just dropping a comment here to bump this is actually becoming a huge time sync for us. Working on a team using git and LFS means that it's easy for broken references to happen, and it's very difficult to track down what broke when we pull. it's probably not a huge issue if working by yourself, but on a team this is a frustrating thing.
> 
> @Menotdan any updates?

Not much I can do about it, I don't have merge perms XD

**Comment by mafiesto4** [comment]
![image](https://github.com/user-attachments/assets/5d154dc4-d919-43a9-9fca-da2d7191fff2)

More improvements for this feature in a367d4091348b96cad6ec84865a8ce650947ae80. Now, missing asset or object will be logged with contextual info about source reference (eg. specific asset path+type+id or specific actor/scritp name+type+id).

I'm sure we will keep improving this feature to make it even easier to find missing references or data problems.
