### ISSUE TITLE
Make animation events more visible. 

### ISSUE THREAD

**Issue by Muzz** [FlaxEngine/FlaxEngine#2419]
**Issue description:**
When you first make an animation event on a long animation, often it's impossible to see where an event was placed, especially as the events get smaller when you zoom out, and when they are first spawned they are next to the initial line. 

![image](https://github.com/FlaxEngine/FlaxEngine/assets/2074204/3e5fc629-786b-462a-9242-42fa4a394d48)

I would suggest that we draw a diamond, or a dot like blender does. If it's more than one frame, draw a bar behind the dot to show the length

![image](https://github.com/FlaxEngine/FlaxEngine/assets/2074204/2b3f0abe-27ae-4b85-b250-5393d27e6871)

also pick a color that is more visible. 

**Flax version:**
Master

**Comment by mafiesto4** [comment]
Added in cd2f96e3c01bc867b1abc95760edcc2549d407e7.

![image](https://github.com/FlaxEngine/FlaxEngine/assets/3464853/0091412f-db77-44c6-a1dc-95909ebd0a99)
