### ISSUE TITLE
Context aware graphics settings

### ISSUE THREAD

**Issue by Muzz** [FlaxEngine/FlaxEngine#2422]
**Issue description:**
Graphics settings show all settings for all options atm, this is confusing and messy, we should have sub options depending on what's relevant. 

For example i have FAA set here but have irrelevant options. 
![image](https://github.com/FlaxEngine/FlaxEngine/assets/2074204/57db240c-606b-4056-b594-177bdf9f3c3e)

**Comment by Menotdan** [comment]
Fixed by #2424
