### ISSUE TITLE
Pass in enum paramaters to animation graph. 

### ISSUE THREAD

**Issue by Muzz** [FlaxEngine/FlaxEngine#2428]
**Issue description:**
We use enums in our game code to drive states, but are stuck using an int to control them in the graph. It'd be a nice upgrade to be able to pass in and do checks on the enums.

**Comment by mafiesto4** [comment]
Anim Graph supports enums both in flow logic and as parameters inputs:
![image](https://github.com/FlaxEngine/FlaxEngine/assets/3464853/591281cb-9c19-49a0-92de-26917a12a37b)

![image](https://github.com/FlaxEngine/FlaxEngine/assets/3464853/fca6d6af-e839-4be0-b47d-441890e00f4e)
