### ISSUE TITLE
Anim Graph crashes on load or PIE.

### ISSUE THREAD

**Issue by OnyeNacho** [FlaxEngine/FlaxEngine#2434]
**Issue description:**
Each time I try to load the Anim Graph I created or use it on an animated model in PIE, it crashes the entire editor with this error prompt message.

![Issue](https://github.com/FlaxEngine/FlaxEngine/assets/2350777/be492067-c8f7-4b9c-9992-4e797bb6206d)
[Log_2024_04_13_04_27_38.txt](https://github.com/FlaxEngine/FlaxEngine/files/14968928/Log_2024_04_13_04_27_38.txt)

**Steps to reproduce:**
Just click on an Anim Graph created from version 1.6 or 1.7. You can also try using it to an animated mesh in the scene and testing via Play In Editor mode.

**Minimal reproduction project:**
[Problem.zip](https://github.com/FlaxEngine/FlaxEngine/files/14968938/Problem.zip)

**Flax version:**
1.8

**Comment by OnyeNacho** [comment]
This may be similar, however at least the reporter manage to access his Anim Graph, only to crash after he tried to modify it.
https://github.com/FlaxEngine/FlaxEngine/issues/2427

I cannot even access the AG at all without a crash.

**Comment by mafiesto4** [comment]
Fixed in 3f6dd92a68d0d9f8beacc92c8e2c43dea7bb3270.

**Comment by OnyeNacho** [comment]
> Fixed in [3f6dd92](https://github.com/FlaxEngine/FlaxEngine/commit/3f6dd92a68d0d9f8beacc92c8e2c43dea7bb3270).

Thank you. I will download this build and try it.
