### ISSUE TITLE
Shift selecting multiple Actors in different tree depths sometimes causes an editor crash

### ISSUE THREAD

**Issue by xxSeys1** [FlaxEngine/FlaxEngine#2436]
**Issue description:**

When selecting multiple actors in different depths of the tree, this sometimes causes the editor to crash.

I made a video that first shows the crash and then shows my attempt at reproducing, which does not work:

https://github.com/FlaxEngine/FlaxEngine/assets/111653551/6e044d26-2344-4558-b3e1-2ce40b41cdb6

Here is the log, there is no Crash_ folder:
[Log_2024_04_14_13_16_02.txt](https://github.com/FlaxEngine/FlaxEngine/files/14970464/Log_2024_04_14_13_16_02.txt)

**Steps to reproduce:**

1. Select an actor
2. Shift click on another actor that is not in the same tree level as the first selected actor
3. Watch the editor crash (or not?)

**Minimal reproduction project:**

Here are both prefabs.
**Crashes in my project, but not in a new project**
[Pre_Player.zip](https://github.com/FlaxEngine/FlaxEngine/files/14970452/Pre_Player.zip)

**My attempt of reproducing**
[ShiftSelect.zip](https://github.com/FlaxEngine/FlaxEngine/files/14970451/ShiftSelect.zip)

**Flax version:**

1.8

**Comment by mafiesto4** [comment]
Fixed in 171fc276fb1907d8947353a9ebed55fed281bd62.
