### ISSUE TITLE
[Proposal] After entering play mode and exiting, switch back to previous editor

### ISSUE THREAD

**Issue by xxSeys1** [FlaxEngine/FlaxEngine#2440]
**Issue description:**

Picture this: Your iterating over an asset and want to enter play mode to see the asset in game.
So you enter play mode, check your asset, see something you want to change and then exit play mode.

Now you have to click on the editor of your asset because on exiting play mode, the game panel stays focused.
This may sound like a minor and easy to overcome issue, but it's really limiting iteration speed and introduces an unnecessary click.

https://github.com/FlaxEngine/FlaxEngine/assets/111653551/6fffaa4a-2d37-4025-8580-d4a413dd8af9

My fix would be that the editor remembers which asset editor was last focused before entering play mode and then re- focuses that editor once play mode is exited.

An editor setting may be useful here, because people may expect the current behavior.

**Steps to reproduce:**

1. Open an asset in an editor
2. Dock that editor in the same areas as the Game panel
3. Enter play mode
4. Watch how the editor does not go back to the previous editor but stays in the Game panel

**Minimal reproduction project:**

none

**Flax version:**

1.8

**Comment by mafiesto4** [comment]
Good idea. Just to keep people informed: Editor settings has option `FocusG ame Win On Play` which can be disabled to not focus game window when staring play mode. It would be nice if it could re-focus back the state on play end,
