### ISSUE TITLE
Weird crash when calling function

### ISSUE THREAD

**Issue by xxSeys1** [FlaxEngine/FlaxEngine#2441]
**If anyone has a more descriptive issue title, pls change it or comment below :)**

**Issue description:**

After calling the `PlayRandom` method, the editor/ game freezes and then crashes with the error message shown in the second screenshot
**The Script**
![image](https://github.com/FlaxEngine/FlaxEngine/assets/111653551/62f7cceb-4059-4527-939d-5caeb13d739c)
[Script.zip](https://github.com/FlaxEngine/FlaxEngine/files/14972093/Script.zip)

**Error Message**
![image](https://github.com/FlaxEngine/FlaxEngine/assets/111653551/711aba91-86af-48c7-82c1-62116fba412f)

**Steps to reproduce:**

None :(

**Minimal reproduction project:**

none

**Flax version:**

1.8

**Comment by mafiesto4** [comment]
You override the `AudioSource::OnEnable` but don't call base class so it caused a crash as audio clip was not registered. Fixed crash here: d729eb2b247f5cea9efda94b4e000c8278129b88 but you should modify the script by adding this into override `OnEnable` method:
```cs
public override void OnEnable()
{
    base.OnEnable();
...
```
