### ISSUE TITLE
Skeleton debug view in editor. 

### ISSUE THREAD

**Issue by Muzz** [FlaxEngine/FlaxEngine#2443]
**Issue description:**
The skeleton view in the asset windows is great, but when setting up a ragdoll you aren't in that window, so adding in skeleton view would greatly assist this task. 

Plus it would help debug situations with code interacting with the anim graph.

**Comment by mafiesto4** [comment]
Added in ce67c3a98d0b1fb1f2e04760aa6154ee5688065d.
