### ISSUE TITLE
Attempting to reimport an animation with a translation causes a crash

### ISSUE THREAD

**Issue by envision3d** [FlaxEngine/FlaxEngine#2445]
**Steps to reproduce:**
1. Import animation
2. Open animation
3. Change `Translation` value
4. Reimport

![image](https://github.com/FlaxEngine/FlaxEngine/assets/17469837/b347228e-1f6d-4b37-84a5-8dbb33353e7c)

**Flax version:**
master

**Comment by mafiesto4** [comment]
Fixed in 00492a33a3751d97070833c96edc0dc73a959920.
