### ISSUE TITLE
Currently selected actor gets deselected when rotating the camera with Alt+ LMB and releasing Alt before LMB

### ISSUE THREAD

**Issue by xxSeys1** [FlaxEngine/FlaxEngine#2447]
**Issue description:**

When rotating the view around an actor using Alt + LMB, then releasing Alt before LMB, as soon as you release LMB you deselect the currently selected actor.

https://github.com/FlaxEngine/FlaxEngine/assets/111653551/ec36e490-b86f-4d8b-b4d4-9a44a599af00

**Steps to reproduce:**

1. Select an actor
2. Pan around it using Alt + LMB
3. Release Alt before LMB
4. Release LMB
5. Watch the currently selected actor getting deselected

**Minimal reproduction project:**

none

**Flax version:**

1.8

**Comment by mafiesto4** [comment]
Fixed in 446c1edafc0623a0941d6ca7b19e27213adaf527.
