### ISSUE TITLE
Crash caused by Change in Inheritance

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#245]
I've found a bug that results in this crash:

![image](https://user-images.githubusercontent.com/35228400/108131201-09e96d00-7105-11eb-961d-71a872c75623.png)

I had a Script attached to the Player originally called the MovementInputScript which was attached to the Player object.
I renamed the Script in the Editor to PlayerMovementScript.
I then opened Visual Studio and made the PlayerMovementScript derived from the MovementBaseScript. When I compiled the scripts and opened the Player Prefab the MovementInput / PlayerMovement Script was missing. 

I tried to reattached the PlayerMovementScript and received the above crash. To fix the issue I had to manually strip the following code from the .JSON file. It appears that it wasn't updated correctly:

	{
		"ID": "5b4906284dfa80bfaaf58d9d5ac9e1b4",
		"TypeName": "Game.MovementInputScript",
		"ParentID": "284b3434471036d53016e284ea5873eb",
		"V": {
	"IsPlayerControlled": true,
	"Body": "53f812b54fcc0e072299fbbc05f11e46" }
	}

After stripping the above I was able to open the Player Prefab and re-add the PlayerMovementScript

**Comment by mafiesto4** [comment]
Fixed in 0c74e2ff9d77b5952fff3a3e8f92a6fe9230b898.
