### ISSUE TITLE
[Bug] Copy Asset Id in content isn't formatted correctly

### ISSUE THREAD

**Issue by Myterian** [FlaxEngine/FlaxEngine#2450]
When using a function like `Content.LoadAsync`, we can use a guid to load assets. The guid needs to be formatted like: 2f07c94c-2251-4ce6-aa2e-f97c0527f4ac.

But when you right click on an asset in the content folder and select `Copy asset ID`, the guid is formatted like:
2f07c94c4ce622517cf92eaaacf42705

I used this for icon display on custom actors and it caused a bit of trouble. I'm pretty sure it's not supposed to be like that

**Steps to reproduce:**
1. Right click and copy the ID of any asset.
2. Create a script that just logs the Asset.ID of the same asset to the console
3. They are differently formatted

**Minimal reproduction project:**
Basic Project

**Flax version:**
1.8.6510

**Comment by mafiesto4** [comment]
That's on purpose because we don't use C#'s Guid formatting but our own Guid (from C++ codebase).
Use those two functions to handle conversion between `Guid` <-> `string`:
```
var id = FlaxEngine.Json.JsonSerializer.ParseID("2f07c94c4ce622517cf92eaaacf42705");
var str = FlaxEngine.Json.JsonSerializer.GetStringID(id);
```
