### ISSUE TITLE
StaticModel in prefab with lightmap settings crashes during rendering.

### ISSUE THREAD

**Issue by Menotdan** [FlaxEngine/FlaxEngine#2454]
**Issue description:**
I have a prefab which contains a static model, and I happened to set some lightmap settings. This causes a crash during thumbnail rendering for the prefab, and also during rendering the prefab window itself.

**Steps to reproduce:**
1. Import the prefab attached.
2. Crash while it tries to render the thumbnail.

[lightmap-bug-prefab.zip](https://github.com/FlaxEngine/FlaxEngine/files/15015571/lightmap-bug-prefab.zip)

**Flax version:**
master at c83b74c85d14233e36a7c3728bdd97f53f2be339

**Comment by mafiesto4** [comment]
Fixed in 5e086809aece7d5c62f39c8e388360782584482d.
