### ISSUE TITLE
[Bug] Broken Blend Shapes

### ISSUE THREAD

**Issue by Myterian** [FlaxEngine/FlaxEngine#2459]
**Issue description:**
Blend shapes in flax seem to push the geometry upwards or in all axis in addition to what the blend shape is supposed to look.

How it looks in Blender
![blender](https://github.com/FlaxEngine/FlaxEngine/assets/30194679/17420081-cd6b-40bd-bcd9-c69dfee727be)

How it looks in Flax
![flax](https://github.com/FlaxEngine/FlaxEngine/assets/30194679/0ad4ddae-b166-4082-be0a-0ab6457661df)

**Minimal reproduction project:**
Basic

**Flax version:**
1.8.6510

**Comment by mafiesto4** [comment]
Could you attach or DM me (eg. on Discord) that source file (eg. `fbx`) to quickly investigate it?

Probably coordinates conversion code needs a fix for blend shapes importing.

**Comment by mafiesto4** [comment]
Fixed in 6aacea99ab883fabb4c696498d05ab24c7d6cf31 and 1072b90c5b523a55e3f14352e12f97a9ec6b4e8b
