### ISSUE TITLE
Importing high resolution skinned mesh appears to cause some deformation in a weird way.

### ISSUE THREAD

**Issue by Menotdan** [FlaxEngine/FlaxEngine#2460]
**Issue description:**
Someone in the discord reported a messy import of a skinned mesh when they applied subdivisions to it to make it look smoother. They say it works in unity but in flax does this:
![image](https://github.com/FlaxEngine/FlaxEngine/assets/32620310/93c7f873-f48a-4c36-a4e6-b17f7c6f88cf)
Importing it as a static mesh doesn't produce this result.

**Steps to reproduce:**
Import linked fbx file as a skinned model. Go close to the head of the person and look at the nose and lips, and they have jagged edges.

**Minimal reproduction model:**
Uploaded to discord:
https://discord.com/channels/437989205315158016/538664104856911883/1230872126274277417

**Flax version:**
1.8 and master at c83b74c85d14233e36a7c3728bdd97f53f2be339

**Comment by MCPE357** [comment]
I really need this fixed

**Comment by MCPE357** [comment]
![Screenshot 2024-04-19 095038](https://github.com/FlaxEngine/FlaxEngine/assets/89349227/55d24128-42c4-45a1-b49b-88a44a02d819)
thats how it is in unity

**Comment by mafiesto4** [comment]
When a model is imported as non-Animated it looks fine so I guess it's some precision issue in animated model skinning:

![image](https://github.com/FlaxEngine/FlaxEngine/assets/3464853/e56ffd9d-645b-4c44-ad24-964193fdeea7)

**Comment by MCPE357** [comment]
> When a model is imported as non-Animated it looks fine so I guess it's some precision issue in animated model skinning:
> 
> ![image](https://private-user-images.githubusercontent.com/3464853/324185244-e56ffd9d-645b-4c44-ad24-964193fdeea7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2Mjc1NDEsIm5iZiI6MTcxMzYyNzI0MSwicGF0aCI6Ii8zNDY0ODUzLzMyNDE4NTI0NC1lNTZmZmQ5ZC02NDViLTRjNDQtYWQyNC05NjQxOTNmZGVlYTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjBUMTUzNDAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGZhZmM1ZTFkZWExOTBjNzE3MjI4N2ZlZjFjNjdkOGNkZmRmZWZjZWU5ZTI0NjA2NTEzM2RiYjZiMWU4NzMxZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.A28y26uWJLuIC9jBV9ueiHL5xohgh5aSaQvtWLebeu0)

Yes, it happens when the model has subdivision surface or high density and a skeleton at the same time

**Comment by mafiesto4** [comment]
Fixed in 568a69081d4f404c5f4e47d790e7751a8159fc35.
