### ISSUE TITLE
Referencing a script in a field is broken

### ISSUE THREAD

**Issue by xxSeys1** [FlaxEngine/FlaxEngine#2465]
**Issue description:**

When making a field in the properties panel that has the type of a class that inherits from script, you can drag in a script.
This however causes a problem where the properties panel shows a script set, but when you try to do anything with the reference  to that script you get a a null error.

I've talked with @Menotdan about this and they mentioned that this may have something to do with the scripts guid.

This only happens some times and I can't reliably reproduce it, but it either happens instantly after dragging the script in or after you change something to any of the related scripts and they have to recompile.

This is a breaking bug and it sucks :(

**Steps to reproduce:**

1. Make a public variable Foo of a type that inherits from script B in script A
2. Add script A to an actor
3. Add script B to the same actor
4. Drag script B into Foo using the 3 lines hamburger menu like item
5. `Debug.Log()` Foo. If you're "lucky" it logs "Foo", but most likely it will log "null"

**Minimal reproduction project:**

none

**Flax version:**

1.8

**Comment by mafiesto4** [comment]
I think the problem here was that when using `Play Game` mode of play button, instead of `Play Scenes` it wasn;t saving the scenes. I fixed it in ca0fb8cf630a23b9f6d90349247a7c1d8d5ead26. If it still occurs feel free to reopen this issue.
