### ISSUE TITLE
HSV to RGB shader nodes

### ISSUE THREAD

**Issue by stefnotch** [FlaxEngine/FlaxEngine#247]
**Issue description:**
It would be really useful to have `HSV to RGB` and `RGB to HSV` shader nodes. For example, generating a rainbow becomes quite easy that way.

Some simple references regarding how the functions could look can be found here
https://www.shadertoy.com/view/MsS3Wc
https://www.shadertoy.com/view/4lVBW1

**Flax version:**
Flax 1.0

**Comment by W2Wizard** [comment]
I couldn't resist not doing this :D

Coming Soon™
![image](https://user-images.githubusercontent.com/63303990/108523783-9bf0a180-72ce-11eb-85c5-9c99f3994e91.png)

**Comment by mafiesto4** [comment]
Fixed by #256
