### ISSUE TITLE
Deleting animation event from animation timeline while holding selection breaks window 

### ISSUE THREAD

**Issue by caelanreid** [FlaxEngine/FlaxEngine#2471]
**Issue description:**
When clicking to select a missing or unmissing animation event, if you press delete while mouse is held on the selection the window will break, freeze, vertical mouse movements will wrap around the window. 

**Steps to reproduce:*

In an animation timeline, place an animation event, then click to select the event, holding the click, now press delete to delete the event. This should put the entire window into a broken state

**Flax version:**
Master

**Comment by mafiesto4** [comment]
Fixed in b7dc0dd0044a0d8fe1b4183b132960706c8ff0dc.
