### ISSUE TITLE
Nested animations broken. 

### ISSUE THREAD

**Issue by Muzz** [FlaxEngine/FlaxEngine#2472]
**Issue description:**
I think the event fixes in nested animations broke something. 

![image](https://github.com/FlaxEngine/FlaxEngine/assets/2074204/60245696-90dd-4125-96af-d6f7f5370d71)

If you create an empty animation then add a nested animation, nothing happens. 

**Steps to reproduce:**
Create empty animation right clicking in editor, add animation. Nothing happens. 

**Minimal reproduction project:**
[Nested_animations_busted.zip](https://github.com/FlaxEngine/FlaxEngine/files/15059386/Nested_animations_busted.zip)

**Flax version:**
Master

**Comment by mafiesto4** [comment]
Fixed in 5f02b4173a927ee494862957d6de10b2a966bed0. That was a typo bug.
