### ISSUE TITLE
[Suggestion] Improve XML comments in the editor

### ISSUE THREAD

**Issue by mtszkarbowiak** [FlaxEngine/FlaxEngine#2478]
The suggestion for future is to properly handle tags in XML comments in the editor. For example *actor* has visible `<see cref=...>...`.

A basic version would just remove XML tags or add some formatting. An expansion could allow the developer to just between docs: Clicking *script* in *actor*'s tooltip could jump to script's docs, open web browser or anything else.

The feature is low-priority but can improve UX, especially in bigger projects.

**Comment by Chikinsupu** [comment]
@mafiesto4 i think this can be closed? Atleast the basic solution described here got implemented with #2696 

![image](https://github.com/user-attachments/assets/234e508b-7738-40f1-b0de-9e7614cba8dd)
![image](https://github.com/user-attachments/assets/66f99396-46f9-49a1-90b0-252810b14d0d)
