### ISSUE TITLE
Foliage Losing Shadows when reducing the Cull distance

### ISSUE THREAD

**Issue by buzzdx** [FlaxEngine/FlaxEngine#2489]
When reducing the cull distance of foliage from the default 10000 to 5000, half of the foliage loses their shadows. Further reduction makes more and more shadows go away.

Screenshots showcasing the effect:

![foliageshadows](https://github.com/FlaxEngine/FlaxEngine/assets/26144397/c6eefb03-ab27-44f3-b490-551d36d1b016)

![foliage_noshadows](https://github.com/FlaxEngine/FlaxEngine/assets/26144397/3950991a-34d1-479f-b2ee-2c2b6a109509)

**Flax version:**
Version 1.8.6510

**Comment by buzzdx** [comment]
I've been working a bit more with foliage and came across another way that seemingly break the shadows of them. This time it happens when increasing the shadow draw distance higher than the default 5000.

This is at 5k:
![grafik](https://github.com/FlaxEngine/FlaxEngine/assets/26144397/c1f93cf9-e7eb-4b9c-a028-9a9860c8160a)

At 10k:
![grafik](https://github.com/FlaxEngine/FlaxEngine/assets/26144397/3833687e-3f99-45fc-9db7-d5faa16f67b3)

And at 20k nor more shadows at all:
![grafik](https://github.com/FlaxEngine/FlaxEngine/assets/26144397/fa5fd18e-4ece-403f-b473-07acb6094c0a)

Maybe it is related.

**Comment by mafiesto4** [comment]
Fixed in b8cb1a828a4f089eaf807ac5d13577295b5a30a3,
