### ISSUE TITLE
Unable to run on macOS

### ISSUE THREAD

**Issue by dontcrash** [FlaxEngine/FlaxEngine#249]
Is there any way to get this going? I have attempted to clone it and run it through mono and build etc but end up with seg faults

**Comment by jb-perrier** [comment]
Unfortunately Flax does not support macOS yet.

**Comment by dontcrash** [comment]
May I ask if this is planned for development? For now I am running Windows virtualised to try Flax out but performance is not great sadly :(

**Comment by jb-perrier** [comment]
It is planned but i can't give you any deadline.
You can check the trello ticket here : https://trello.com/c/T9olHMiI

**Comment by mafiesto4** [comment]
Tracking ticket: https://trello.com/c/HcCxrJiV/39-macos-port

**Comment by dontcrash** [comment]
Thank you for the quick response time! I’ll check out Trello

**Comment by mafiesto4** [comment]
macOS support is here: https://flaxengine.com/blog/flax-1-3-released/
