### ISSUE TITLE
Animation engine shows wrong Animation clips

### ISSUE THREAD

**Issue by cNori** [FlaxEngine/FlaxEngine#2490]
**Issue description:**

https://github.com/FlaxEngine/FlaxEngine/assets/162097313/e99bb61c-32ee-4de9-a48e-a039bd3d63e5

**note:**
i was working before

**Flax version:**
[master](https://github.com/FlaxEngine/FlaxEngine/commit/705856da24b9bb8ba8c39b74087ef7dc3b09ba01)

**Comment by mafiesto4** [comment]
Maybe reimport failed? Anything in the log? Can you share that animation file?

**Comment by cNori** [comment]
> Maybe reimport failed?

nope

> Anything in the log?

nope

> Can you share that animation file?

animation file will not help u this is something to do with the engine
u really did not look at the video closely

**Comment by mafiesto4** [comment]
Hmm Object Index is `-1` so it picks the first animation from the file and maybe it was a ref pose. I added selecting the longest animation as default one which should skip any ref poses from exported file: e925af534ebaa093a49f772990bf3a637e0cadaf
