### ISSUE TITLE
[Suggestion] Getting a tag via Tags.Get("Any String") will result in having a temporary tag being created

### ISSUE THREAD

**Issue by alcoranpaul** [FlaxEngine/FlaxEngine#2492]
**Issue description:**
Getting a tag by using Tags.Get(String nameTag), nameTag doesn't even have to be define in Layers and Tags Settings, ends up being created temporarily until you close Flax Engine.

**Expected**
Using Tags.Get with a not defined tag from Layers and Tags Settings, would return a null or a false Boolean, indicating that the retrieval has failed.

**Steps to reproduce:**
- Create a Define or not define tags in Layers And Tags
- Create a script
- In the script, call `Tags.Get(tagName);`
- Run Play in Editor then stop it
- Go to any Actors and check the tag, it should result in having an additional Tag that is "tagName"
- Go to Layers And Tags Setting, here it would not be defined until you close down the Engine.

**Video**

https://github.com/FlaxEngine/FlaxEngine/assets/67833935/79e4fd00-4095-4fac-a3be-f1eb68ee6a3b
- (480p quality as it larger than 10mb)

https://github.com/FlaxEngine/FlaxEngine/assets/67833935/2ea69498-c060-400a-b166-cf45e5f1e68f
- Here you can see that the "INCONSISTEN_TAG" is being shown in the Actor Tags but not in the Layers and Tags Settings
- Until I restarted is when it doesn't show up

**Flax version:**
Master

**Comment by Menotdan** [comment]
The documentation for the function explicitly mentions that it creates the tag if it doesn't exist.

**Comment by alcoranpaul** [comment]
Didn't realize that it "Gets or **adds** the tag." but nonetheless, it should only get a define tag instead of creating an undefined one

**Comment by Menotdan** [comment]
> Didn't realize that it "Gets or **adds** the tag." but nonetheless, it should only get a define tag instead of creating an undefined one

It's used internally for this but I can agree it could be separated.

**Comment by mafiesto4** [comment]
We could add `FindTag` that would return empty tag if it not exists. But the idea here is that tags can be created no only from a single Layers and tags asset but from Prefabs/Levels/Code to improve usability of this system. Under the hood tags are just `uint32` so using them in code is very performance. Finally, tags have nice integration in Editor thus are good for Designers to play with setups of maps/gameplay/etc.

**Comment by alcoranpaul** [comment]
> We could add `FindTag` that would return empty tag if it not exists. But the idea here is that tags can be created no only from a single Layers and tags asset but from Prefabs/Levels/Code to improve usability of this system. Under the hood tags are just `uint32` so using them in code is very performance. Finally, tags have nice integration in Editor thus are good for Designers to play with setups of maps/gameplay/etc.

The FindTag would be a nice addition. So I guess this wouldnt be an issue but a suggestion. I will rename this into a suggestion instead then

**Comment by mafiesto4** [comment]
Added in 5e5497ff18623a6f7b233aef5187424118ebe9e7
