### ISSUE TITLE
Editor crash: the GenericEditor is unrolling a cyclical reference infinitely

### ISSUE THREAD

**Issue by lifeformed** [FlaxEngine/FlaxEngine#2493]
When I click on a specific actor sometimes, the editor hangs, then crashes. 
When I pause the debugger I see this loop: 
![image](https://github.com/FlaxEngine/FlaxEngine/assets/1567199/d3d6b29e-b00f-490d-ae42-ca8c0f6648d0)

It looks like the GenericEditor is forever building a nested container group when trying to view my script. 
![image](https://github.com/FlaxEngine/FlaxEngine/assets/1567199/a0a3f897-7efc-47e4-9b1a-2189b42ce07a)

The field it's stuck on is an interface.  The field has a reference to another script that derives from a class that implements that interface.  That script has a reference to this original actor, which completes the cycle.

I don't quite have time narrowing down a repro but I'll try.  I think whatever GenericEditor normally does to avoid cycles might've missed it because of the cycle being abstracted away through multiple steps and interfaces?

**Comment by mafiesto4** [comment]
@lifeformed Could you post a sample code that caused it?

**Comment by lifeformed** [comment]
> @lifeformed Could you post a sample code that caused it?

Okay I was able to reproduce it, it's quite straightforward:

`using FlaxEngine;

public interface IX
{
    IY Y { get; set; }
}

public interface IY { }

public class XImpl : IX
{
    public IY Y { get; set; }
}

public class TEST : Script, IY
{
    public IX X = null;
    public override void OnStart()
    {
        base.OnStart();
        X = new XImpl();
        X.Y = this;
    }
}
`

In a blank project on Master, putting this on an actor and then click on it in the Scene causes it to hang and then crash. It's trying to generate the editor UI for X->Y->X->Y->etc...

**Comment by mafiesto4** [comment]
Fixed in 9d830eb1e2174ced763ac6176a6dd4c7efc7c140.
