### ISSUE TITLE
OnLateFixedUpdate() + PhysX

### ISSUE THREAD

**Issue by GhettoScouser** [FlaxEngine/FlaxEngine#2494]
**Issue description:**
Accessing rigidbody inside `OnLateFixedUpdate()` causes PhysX errors

**Error**
`[ 00:23:19.776 ]: [Error] PhysX Error! Code: 8.
PxRigidDynamic::setGlobalPose() not allowed while simulation is running. Call will be ignored.
Source: F:\FlaxEngineDotnet\Cache\Intermediate\Deps\PhysX\physx\source\physx\src\NpRigidDynamic.cpp : 97.
[ 00:23:19.776 ]: [Error] PhysX Error! Code: 8.
PxRigidActor::getWorldBounds() not allowed while simulation is running (except during PxScene::collide()).
Source: F:\FlaxEngineDotnet\Cache\Intermediate\Deps\PhysX\physx\source\physx\src\NpRigidActorTemplate.h : 301`

**Flax version:**
Master Branch 26/04/24

**Comment by mafiesto4** [comment]
We will need to sync and wait fro physx results before calling Late Update but keep it optimized if possible to waste as late as possible for multi-threaded simulation.
