### ISSUE TITLE
UI Label Resizing Inconsistent

### ISSUE THREAD

**Issue by alcoranpaul** [FlaxEngine/FlaxEngine#2496]
**Issue description:**
With a UI Label, 
- if you enable the following below. And Change the size in real time. The result is that it doesnt change the Transform Dimensions
> - Auto Width
> - Auto Height
> - Auto Fit Text
- Also, when changing the size of the font, the X and Y transform point of the label changes even though I have anchored it in the middle center

**Expected**
- Enabling Auto Width, Height, and Fit Text would automatically resize the transform and would be anchored
- [Maybe a solution?] Similar to Unity with its Auto Size, you only need to modify the Transform dimension rather than the text font. (Unity Video attached)
> - You can also see that changing the font doesn't change the position transform of it as well

**Steps to reproduce:**
- Create a UI label under UI Canvas
- Enable flag: Auto width, height, and Fit Text
- Change the Size, you will notice that it doesn't change the dimensions
- Disable same flags, then it will either do nothing or update the transform
- Repeat the enabling, disabling, and size modification

**Video**

https://github.com/FlaxEngine/FlaxEngine/assets/67833935/45cca57d-4bfd-4c55-9cda-5a7cb75051c3

https://github.com/FlaxEngine/FlaxEngine/assets/67833935/906beea7-c96c-44f2-8728-0ac4fea46f50

**Flax version:**
Master

**Comment by mafiesto4** [comment]
Fixed in 262c536d7f93c480b39f33c6b2d3c8b495577aea and c9817b25a306f99c721f2a452863939d478a665b.
