### ISSUE TITLE
[USABILITY REQUEST] Animation Blend2D allow to delete selected point with Delete key.

### ISSUE THREAD

**Issue by MrCapy0** [FlaxEngine/FlaxEngine#2505]
**Issue description:**
Would be nice have the Delete key to delete the selected point in the Blend2D node. 
![image](https://github.com/FlaxEngine/FlaxEngine/assets/167662176/b7c68b15-3d31-4d1e-a27b-d791fde991e8)

**Flax version:**
1.8.1

**Comment by mafiesto4** [comment]
Added in 1ef487a5ccb6fdb86b436c6cbadae4f47d46b1bf.
