### ISSUE TITLE
Annoying but minor bug in Animation Graph

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#251]
This is an annoyance / bug within the Animation Graph.

Please see this film to see the bug in action / reproduce:
https://drive.google.com/file/d/1X94_WBlu5YmJGTxjrRkCWLh_tNQociU7/view?usp=sharing

**Comment by stefnotch** [comment]
Ah, modifying the values of the multi blend 1D node doesn't update the animation graph's save button.

**Comment by LCRW** [comment]
![image](https://user-images.githubusercontent.com/21992724/108629724-3e3c9080-7459-11eb-8e4d-0b4c9dba57c9.png)
works as expected on fresh build from master.
