### ISSUE TITLE
[Suggestion] Be able to have the option for controlling child Transform dimensions of Vertical and Horizontal Panels

### ISSUE THREAD

**Issue by alcoranpaul** [FlaxEngine/FlaxEngine#2511]
I would like to request the option for UI Vertical and Horizontal panels to have an option to not force the child actors to follow the panel's height or width respectively.
- Additionally, the option for manipulating the alignment of the children as seen with unity below

In my UI, I wanted the Quit button to be a little bit smaller for its width but the width of the button was locked making the button to be a little bit not pleasing for me

![image](https://github.com/FlaxEngine/FlaxEngine/assets/67833935/13025fd9-9fc6-4235-a607-82565f783dfb)

In Unity
![image](https://github.com/FlaxEngine/FlaxEngine/assets/67833935/0b905653-bf6b-402f-a133-dfe43b903000)

**Workaround**
- Put a Control, like ContainerControl, for the parent of the Button then I can control the Width of it

**Comment by mafiesto4** [comment]
Added in a8354720df03b86cada18f4445ccc7d63450b5b0.
