### ISSUE TITLE
Prefab Window not save/load editor state for actor fields

### ISSUE THREAD

**Issue by MrCapy0** [FlaxEngine/FlaxEngine#2517]
**Issue description:**
Different of the property window of the main editor, the Prefabs window not save the state, you need to reopen all fields again all times.

**Steps to reproduce:**
1. Open a prefab
2. Open some script fields
3. Close prefab editor
4. Open again...
https://github.com/FlaxEngine/FlaxEngine/assets/167662176/ce9d9f7e-90ae-442b-977c-8dda0d97f506

**Flax version:**
1.8.1

**Comment by xxSeys1** [comment]
You mean this: https://github.com/FlaxEngine/FlaxEngine/issues/2431 ?

**Comment by MrCapy0** [comment]
@xxSeys1 Oh, yes, so it's a duplicated issue, i'll close it.
