### ISSUE TITLE
Objects registry issue when setting parent to null during game

### ISSUE THREAD

**Issue by stefnotch** [FlaxEngine/FlaxEngine#252]
**Issue description:**
When setting an actor parent to null during a running game, Flax ends up complaining about `Objects registry already contains object with ...` once you stop the game.

Here is a log of such a run
```
[ 00:00:58.548 ]: [Info] [PlayMode] Start
[ 00:00:58.564 ]: [Info] Changing editor state from FlaxEditor.States.EditingSceneState to FlaxEditor.States.PlayingState
[ 00:00:58.564 ]: [Info] Apply game settings
[ 00:00:58.564 ]: [Info] Collecting scene data
[ 00:00:58.564 ]: [Info] Saving scene Main to bytes
[ 00:00:58.569 ]: [Info] Scene saved! Time 5 ms
[ 00:00:58.569 ]: [Info] Cleanup graph for scene 'Main'
[ 00:00:58.569 ]: [Info] Unloding 1 lightmap(s)
[ 00:00:58.570 ]: [Info] Gathered 1 scene(s)!
[ 00:00:58.570 ]: [Info] Creating scenes
[ 00:00:58.573 ]: [Info] Loading scene...
[ 00:00:58.573 ]: [Info] Loading 1 lightmap(s)
[ 00:00:58.586 ]: [Info] Created graph for scene 'Main' in 0 ms
[ 00:00:58.586 ]: [Info] Scene loaded in 13 ms
[ 00:00:58.590 ]: [Info] [PlayMode] Enter
[ 00:01:02.262 ]: [Info] [PlayMode] Stop
[ 00:01:02.295 ]: [Info] Changing editor state from FlaxEditor.States.PlayingState to FlaxEditor.States.EditingSceneState
[ 00:01:02.295 ]: [Info] Restoring scene data
[ 00:01:02.295 ]: [Info] Cleanup graph for scene 'Main'
[ 00:01:02.296 ]: [Info] Unloding 1 lightmap(s)
[ 00:01:02.303 ]: [Info] Loading scene...
[ 00:01:02.304 ]: [Info] Loading 1 lightmap(s)
[ 00:01:02.304 ]: [Error] Objects registry already contains object with ID=398e37fc4db178f2fcfae298038b6e0c (type 'FlaxEngine.HingeJoint')! Trying to register object  (FlaxEngine.HingeJoint; 398e37fc4db178f2fcfae298038b6e0c) (type 'FlaxEngine.HingeJoint').
[ 00:01:02.304 ]: [Error] Objects registry already contains object with ID=f401d6da4683e2c6fa0f01b770233566 (type 'BasicTemplate.BasicTemplate.SetParentToNull')! Trying to register object BasicTemplate.BasicTemplate.SetParentToNull (type 'BasicTemplate.BasicTemplate.SetParentToNull').
[ 00:01:02.314 ]: [Info] Created graph for scene 'Main' in 1 ms
[ 00:01:02.314 ]: [Info] Scene loaded in 11 ms
[ 00:01:02.314 ]: [Info] Restored previous scenes
[ 00:01:02.319 ]: [Info] [PlayMode] Exit
[ 00:01:45.550 ]: [Info] Command: C:\Users\Stefnot
```

**Steps to reproduce:**
1. Add the following script to your scripts

```cs
using System;
using FlaxEngine;

namespace BasicTemplate
{
    public class SetParentToNull : Script
    {
        public override void OnEnable()
        {
            Actor.Parent = null;
        }
    }
}
```

2. Attach the script to an actor
3. Disable the script by clicking on that checkbox
4. Start the game
5. Enable the script
6. Stop the game
7. Check out the output log

**Flax version:**
Current Flax from the 1.1 branch, at commit c25abfda65d0ea5130503c2d6f8085a14fed522f

**Comment by honzapatCZ** [comment]
Btw the same happens using SetParent(null)

**Comment by mafiesto4** [comment]
I'm not sure if it's a bug in the engine. That's the game code that unlinks the objects from the scene structure and doesn't delete it - resulting in a memory leak. The engine warns about it as we have objectID to collision after restoring scenes by editor.

If the object is unlinked from scene (eg. for object pooling) it can be linked back later or deleted by the game.

**Comment by stefnotch** [comment]
If it's intentional behavior, then we should probably document it. (Maybe in the documentation for `Actor.Parent`)

I kinda would have expected that setting `Actor.Parent` to null would detach the script. And then, if nothing references the script anymore, it gets garbage collected (and cleaned up on the C++ side)?

**Comment by mafiesto4** [comment]
Scripts and Actors don't use garbage collection thus they will leak. If the actor should be removed from the scene then use `Destroy` method (with optional timeout).
