### ISSUE TITLE
CustomEditor structs returned as a coppy from Values[0]

### ISSUE THREAD

**Issue by cNori** [FlaxEngine/FlaxEngine#2523]
**Issue description:**

any attemps of seting value are not working
any attempts of calling a SetValue (*1) from editor API is not setting destination

```c#
var at = Values[0] as Item.Attribute?;
CheckBox box = layout.Checkbox("Value").CheckBox;
box.Checked = at.Value.GetValue<bool>();
box.StateChanged += (CheckBox box) =>
{
       at.Value.SetValue(box.State == CheckBoxState.Checked);
       (*1)
};
```
[edit] 
-Item is a class 
-Attribute is a struct

**Flax version:**

[c5520f2](https://github.com/FlaxEngine/FlaxEngine/commit/c5520f27770a0ae10e0b4cb88219ec00e374e5ce)

**Comment by mafiesto4** [comment]
In C# structures are passed by value by design. In Custom Editors when changing structure property we do manual 'up' propagation of the value to set struct value in the outer container (eg. class member).
