### ISSUE TITLE
Scene outliner (ListView of scene objects) is not working correctly, showing nothing in certain situations.

### ISSUE THREAD

**Issue by buzzdx** [FlaxEngine/FlaxEngine#2527]
When having lots of items in the scene outliner, it starts to behave weirdly. That is, when scrolling down, parts of the listview or even the fill view go blank.

Here you see the top of my outliner:
![grafik](https://github.com/FlaxEngine/FlaxEngine/assets/26144397/689729ee-618c-409d-a1a1-0d009c435a1e)

A bit scrolled down, the top vanishes:
![grafik](https://github.com/FlaxEngine/FlaxEngine/assets/26144397/e6163ee5-c789-440f-bdc9-749d9bbbb44c)

More down and everything is gone:
![grafik](https://github.com/FlaxEngine/FlaxEngine/assets/26144397/3b1a3971-9a3a-4e66-8db0-0380ca2ce0e3)

**Flax version:**
1.8.6511.1

**Comment by mafiesto4** [comment]
Regression from recent perf improvements to TreeNode rendering. Fixed in #2521
