### ISSUE TITLE
Consecutive `LocalizedString` fields breaking the editor

### ISSUE THREAD

**Issue by mtszkarbowiak** [FlaxEngine/FlaxEngine#2530]
**Issue description:**

Declaring 2 `LocalizedString` API fields breaks the editor.

**Steps to reproduce:**

Declare JSON asset with 2 `LocalizedString`s in a row.

```
API_FIELD()
LocalizedString Name;

API_FIELD()
LocalizedString Description;
```

![image](https://github.com/FlaxEngine/FlaxEngine/assets/69864511/c1df2c88-41b3-49ff-8ac1-f34e6035af87)

Fortunately, if something is put between, the bug is not triggered.

```
API_FIELD()
LocalizedString Name;

API_FIELD()
int32 EloSiema;

API_FIELD()
LocalizedString Description;
```

![image](https://github.com/FlaxEngine/FlaxEngine/assets/69864511/a63d700f-c0d5-45c8-a6fc-60335e7b84e4)

**Flax version:**

1.7.2

**Comment by mafiesto4** [comment]
Fixed in 68eb8b9f212db01edde27d1805abefd53df2100f.
