### ISSUE TITLE
Mouse cursor does not hide and change cursor shapen when focussing flax editor with right click in viewport

### ISSUE THREAD

**Issue by xxSeys1** [FlaxEngine/FlaxEngine#2531]
**Issue description:**

When focusing the editor by right clicking into the viewport and moving the viewport camera the mouse cursor stays visible and does not change cursor shape until you restart the editor.

I can (almost, sometimes it does not happen wtf) reliably reproduce this by what I described in the sentence above, but it also happens seemingly at random sometimes.

https://github.com/FlaxEngine/FlaxEngine/assets/111653551/fcdded34-3601-445c-b50b-4a97ee9d92ff

While not breaking it's really annoying.

**Steps to reproduce:**

1. Open the Flax editor
2. Focus a window that's not editor related and that's on the same screen as the editor
3. Right click into the editor viewport and move the camera

**Minimal reproduction project:**

none

**Flax version:**

1.8.1

**Comment by Tryibion** [comment]
I have not been able to reproduce this.

**Comment by xxSeys1** [comment]
Can u try with a flax window undocked from the main window?

**Comment by Tryibion** [comment]
It looks like I can get it to trigger if the Flax Editor main window is not full screen and the Game Editor Window is undocked. Then if I defocus the editor and then refocus on the Game Editor Window, it will not hide the mouse.
