### ISSUE TITLE
A way to download other versions of minor versions when a different patch version is installed

### ISSUE THREAD

**Issue by xxSeys1** [FlaxEngine/FlaxEngine#2543]
**Issue description:**

When I have 1.8.1 installed for example I can't install 1.8.0. But what if there is a breaking bug in 1.8.1 (that's also not fixed in master yet)?
Sure you could fix it yourself or see if someone has fixed it and merge that pr in a custom fork and then build the engine but why do all that if 1.8 works?

![image](https://github.com/FlaxEngine/FlaxEngine/assets/111653551/8c753801-ef09-414b-b83a-4220912e958b)

I think the launcher should allow users to install every release of flax.

**Steps to reproduce:**

none

**Minimal reproduction project:**

none

**Flax version:**

doesn't matter :)

**Comment by mafiesto4** [comment]
We don't have resources to host minor revisions. Maybe in future if userbase grows.
