### ISSUE TITLE
[Proposal] Make curves an asset just like materials etc.

### ISSUE THREAD

**Issue by xxSeys1** [FlaxEngine/FlaxEngine#2544]
**Issue description:**

Unreal allows (forces) you to create a new curve asset when wanting to use a curve. This asset can be edited in a separate editor called the curve editor.

I think this is a better approach than having the curve in the properties panel, because it allows you to re- use a curve. Also right now a curve gets lost when applying a script with a curve to a new actor.

This would also be a great moment to implement #1029.

Also now is prolly the best time to discuss this because of a lot of stuff in #2455 (planned for 1.9) would have to be done (a bit) differently if this is implemented.

**Steps to reproduce:**

none

**Minimal reproduction project:**

none

**Flax version:**

1.8.1

**Comment by MrCapy0** [comment]
I don't like "force" to create an asset. I like the original idea of use curves on any place like Unity or the current curve of Flax. You can create a JsonAsset with reusable data (and curves) if you want.

**Comment by xxSeys1** [comment]
Ok I tried json assets and that's exactly what I wanted, gonna close this.
