### ISSUE TITLE
pre-skinned normal and position material nodes are broken

### ISSUE THREAD

**Issue by Muzz** [FlaxEngine/FlaxEngine#2549]
**Issue description:**
Preskinned normal and position are both currently broken. 

I have great need to have these for doing some procedural materials. thanks!

**Steps to reproduce:**
make a material, make a preskinned normal node and plug it into emissive, notice how it's black. 

**Flax version:**
master

![image](https://github.com/FlaxEngine/FlaxEngine/assets/2074204/2b9b0555-d07b-4f13-9ec8-4fda6f7ce50b)

**Comment by mafiesto4** [comment]
It looks like it was available in Vertex Shader only. You can use VS to PS interpolation to access it in Pixel Shader:
![image](https://github.com/user-attachments/assets/732821fb-a004-4b2e-9953-74fcd7406a75)

But I think we can fix it in code too.

**Comment by mafiesto4** [comment]
Fixed in be395304ec7b12f548388920819e5d0b2f98051e,
