### ISSUE TITLE
Cannot load scene without game modules loaded.

### ISSUE THREAD

**Issue by sonczyponcze** [FlaxEngine/FlaxEngine#255]
After installation of JDK and Android SDK, per this: https://docs.flaxengine.com/manual/platforms/android.html instructions I'm unable to load any project, getting error:

"Missing game modules
Cannot load scene without game script modules. Please fix the compilation issues"

![image](https://user-images.githubusercontent.com/24634983/108599754-62359e80-7393-11eb-9b4e-188a052c39a6.png)

[Log_2021_02_20_15_45_26.txt](https://github.com/FlaxEngine/FlaxEngine/files/6015201/Log_2021_02_20_15_45_26.txt)

**Flax version:**
Flax 1.0

**Comment by sonczyponcze** [comment]
Dear FLAX team, what does closing this issue means ? 
Is it going to be solved with next FLAX version, or should I take some action (what?) to solve it ?
humble regards
ts

**Comment by mafiesto4** [comment]
It's fixed here: <https://github.com/FlaxEngine/FlaxEngine/commit/68b4fdb9c3f6a23caaf8e4d509d307e0d6168b6e> so you can manually compile editor and get changes or wait for the next engine update. We usually publish them monthly 1-2 times after major updates. The next update with this fix will be probably `1.1` version early in March.

**Comment by sonczyponcze** [comment]
Błąd: ""Missing game modules. Cannot load scene without game script modules. Please fix the compilation issues"
Nadal występuje, w dokładnie takich samych okolicznościach jak poprzednio - po instalacji Android Studio + JDK. 
Flax Engine 1.2
ts
