### ISSUE TITLE
Terrain artifacts

### ISSUE THREAD

**Issue by Wc4ever** [FlaxEngine/FlaxEngine#2555]
Then I move camera artifacts appears on terrain.

https://github.com/FlaxEngine/FlaxEngine/assets/7123610/9ab709cf-4cfa-413f-baa8-a8c55605d9b4

![before](https://github.com/FlaxEngine/FlaxEngine/assets/7123610/e1d0a1a9-48f5-4e61-a67e-cd20e93fff8d)

![after](https://github.com/FlaxEngine/FlaxEngine/assets/7123610/4177afe7-e5a8-40fd-910a-e627f39da04e)

Heightmap:
![World1Height](https://github.com/FlaxEngine/FlaxEngine/assets/7123610/6b9933cc-e8f8-4117-8323-e38bbf138725)

Patches 1x1 chunck size 255 height scale 52500

Flax 1.8.1

**Comment by Wc4ever** [comment]
Ok sorry for duplicate seems like my issue has the same nature with [this one](https://github.com/FlaxEngine/FlaxEngine/issues/2256)

**Comment by Andre13187** [comment]
Hello, maybe changing the Near plane and Far plane values can help.

**Comment by mafiesto4** [comment]
Fixed in e5f0e05d43f3359cd5fdf1eaaab7096b93ca6103.
