### ISSUE TITLE
Material rendering bug then using Textures Group

### ISSUE THREAD

**Issue by Wc4ever** [FlaxEngine/FlaxEngine#2559]
**Issue description:**
Material renders black region then using Texture Group.

**Steps to reproduce:**
1. Setup Textures Groups.
2. Include textures in textures group.
3. Setup basic material via materail graph using textures from step 2.
4. Add static mesh(for example cube) on scene with materail from step 3.
5. Restart Flax Editor.
6. Move camera. On some distance cube appears to be black.

**Minimal reproduction project:**
![image](https://github.com/FlaxEngine/FlaxEngine/assets/7123610/37cf04b0-9827-499d-b203-44b08e195830)

**Flax version:**
1.8.1

**Comment by mafiesto4** [comment]
Fixed in fc9aa5c1840421f5b7d1e17fb1509d7c9cb10810.
