### ISSUE TITLE
CSG brush selection outline shows in game even though debug draw is disabled

### ISSUE THREAD

**Issue by xxSeys1** [FlaxEngine/FlaxEngine#2561]
**Issue description:**

The yellow outline that shows when a CSG brush is selected shows in game even when debug draw is disabled for the game panel.
No big deal but I can see this getting in the way of something.
Also shows in play mode.

https://github.com/FlaxEngine/FlaxEngine/assets/111653551/7b06b1fc-d0ee-495e-b88f-f732bdf68074

**Steps to reproduce:**

1. Create a CSG brush
2. Select it
3. Go to the game panel or enter play mode

**Minimal reproduction project:**

none

**Flax version:**

1.8.1

**Comment by mafiesto4** [comment]
I was unable to reproduce it on the latest `master`. Are you sure the debug draw was not enabled for Game view? If it happens again feel free to reopen this ticket.
