### ISSUE TITLE
Game won't launch on Android

### ISSUE THREAD

**Issue by goottime** [FlaxEngine/FlaxEngine#2562]
**Issue description:**
The game does not launch on Android. After starting the game, the splash screen appears and the app ends.

**Steps to reproduce:**
1. Copy the official sample [GraphicsFeaturesTour](https://github.com/FlaxEngine/FlaxSamples/tree/master/GraphicsFeaturesTour).
2. Build a version for Android.
3. Install the game on your device and launch it.

**Logs:** [log.txt](https://github.com/FlaxEngine/FlaxEngine/files/15224837/log.txt)

https://github.com/FlaxEngine/FlaxEngine/assets/96193346/0ce2216c-ca65-4735-a6ae-824538d1f3c4

**Minimal reproduction project:**
[GraphicsFeaturesTour](https://github.com/FlaxEngine/FlaxSamples/tree/master/GraphicsFeaturesTour)

**Device:**
Xiaomi Redmi Note 8 Pro; Android 13 (crDroid)

**Flax version:**
1.8.1

**Comment by mafiesto4** [comment]
```
FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7aec9e6740)
Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 20561 (Load Thread 0), pid 20503 (icsfeaturestour)

```

**Comment by mafiesto4** [comment]
I tested the latest `master` build with Android (Samsung Galaxy S23) and it works fine. Probably sth we fixed recently when doing some code sanity fixes.
