### ISSUE TITLE
[Proposal] Rename `IsActuallyPlayingSth` to `IsActuallyPlaying`

### ISSUE THREAD

**Issue by xxSeys1** [FlaxEngine/FlaxEngine#2565]
**Issue description:**

The *Sth* is just weird in a programming context and `IsActuallyPlaying` tells the user equally as well/ bad what the method is doing.

This breaks the api and also is just a visual thing, so I'd add this in 2.0 or with a new audio system if Flax gets one.

**Steps to reproduce:**

none

**Minimal reproduction project:**

none

**Flax version:**

1.8.1

**Comment by mafiesto4** [comment]
Good idea to rename it (let's keep old name as deprecated until removal in 2.0).
