### ISSUE TITLE
[BUG] Scene hierarchy not rendering properly

### ISSUE THREAD

**Issue by Harloys** [FlaxEngine/FlaxEngine#2570]
**Issue description:**
If you parent Directional Light to the first child of the scene it might break render of hierarchy 

**Steps to reproduce:**
Create new scene, delete all objects, add new Actor, add Directional light as child to this Actor
Now add new Actors as childs of Scene, after 50 actors hierarchy won't render properly

https://github.com/FlaxEngine/FlaxEngine/assets/73179432/81fa45e5-77e1-4ee7-a97f-a9aa7f5b0a36

**Flax version:**
1.8.6511.1

**Comment by Menotdan** [comment]
This was fixed in master I believe.

**Comment by Harloys** [comment]
Just checked, the bug is still there

**Comment by Menotdan** [comment]
@GoaLitiuM Could you take a look at this?

**Comment by mafiesto4** [comment]
Probably fixed in #2521
