### ISSUE TITLE
The Apk file exported from FlaxEngine is too large

### ISSUE THREAD

**Issue by WOLFxxxxxx** [FlaxEngine/FlaxEngine#2571]
<!

**Comment by mafiesto4** [comment]
What build type? In `Development` and `Debug` builds we include debug symbols to have crashes/debugging working properly. What's your `Release` build size? Do you use ASTC compression enabled in Android Platform settings?

**Comment by WOLFxxxxxx** [comment]
Release 80MB

**Comment by mafiesto4** [comment]
I tested [Basic Template](https://github.com/FlaxEngine/FlaxSamples/tree/master/BasicTemplate) project (a single cube with a sky) in Release.

Apk contents:
* Flax Content: 17MB
* C# Runtime: 13MB
* C# code: 8MB
* FlaxGame: 19MB
* 3rd party libs: 11MB

Asset stats:
```
Cooked 80 assets, total assets: 80, total content packages size: 17 MB
FlaxEngine.Texture                 :   17 assets of total size 13.81 Mb
FlaxEngine.Shader                  :   30 assets of total size 1.75 Mb
FlaxEngine.CubeTexture             :    2 assets of total size 1 Mb
FlaxEngine.Material                :    5 assets of total size 175.89 Kb
FlaxEngine.FontAsset               :    1 assets of total size 168.06 Kb
FlaxEngine.Model                   :    6 assets of total size 121.79 Kb
FlaxEngine.JsonAsset               :   18 assets of total size 13.95 Kb
FlaxEngine.SceneAsset              :    1 assets of total size 4.49 Kb
Output .NET files size: 16 MB
```

I think we could:
* remove `pdb` files from C# code in Release (1.3MB savings)
* expose `UseSmallCode` into engine project file to enable `FavorSizeOrSpeed.SmallCode` when compiling engine and save on engine lib size
* maybe there is a way to compress `apk` file? it's `zip` file and when using `7zp` with Maximum compression level I've got 22MB which is way less than default apk from Gradle.

Finally, if you want to save more space I would recommend using C++ only scripting and use engine with `"UseCSharp": false` set in `Flax.flaxproj`, then your game won't ship C# runtime libs nor so many 3rd party libs (eg. `mono`). But then you need to write your code in C++ only and cannot use in-built GUI which depends on C#.

**Comment by WOLFxxxxxx** [comment]
Thank you very much

**Comment by mafiesto4** [comment]
If you enable **For Distribution** in **Build Settings** then apk size goes down to `25MB` which is fine to me. I'll make it enabled in `Release` builds.

![image](https://github.com/FlaxEngine/FlaxEngine/assets/3464853/b482fb7a-e2d0-41d1-844d-aca1bf1dab61)
