### ISSUE TITLE
Navigating interface jump count equal to number of canvases issue

### ISSUE THREAD

**Issue by mtszkarbowiak** [FlaxEngine/FlaxEngine#2574]
**Issue description:**

Navigating through focusable UI controls makes two changes instead of one.

**Steps to reproduce:**

1. Create canvas.
2. Add 3 buttons (for example vertically).
3. Just navigate (I mean... try) through them.

The bug is triggered whenever nav-target is manually set or not and auto-focus is used.

**Flax version:**

1.7.2, 1.8.1, master

Note: For some reason Flax 1.7.2 expected navigation events to be in 'Pressing' mode. During migration to 1.8.1 I needed to switch to 'Press' mode.

This issue impact my project very much. It is problematic.

Suggestion: Add something to debug navigation. Just arrows (like Unity) would be enough.

**Comment by mtszkarbowiak** [comment]
Small update

It turns out that number of jumps is directly correlated to number of active canvases. (No matter what is their configuration.)

**Comment by mafiesto4** [comment]
Fixed in 0a4e89e29b5427a6bbd384f9f3ba65f57e7ea1f4 (tested both in Editor and cooked Game).
