### ISSUE TITLE
[Bindings generator] generates invalid code on c# side

### ISSUE THREAD

**Issue by cNori** [FlaxEngine/FlaxEngine#2582]
**Issue description:**
error CS0426: The type name 'Item' does not exist in the type 'Item.AttributeMarshaller'
error CS0411: The type arguments for method 'NativeInterop.ConvertArray<TSrc, TDst>(Span<TSrc>, Func<TSrc, TDst>)' cannot be inferred from the usage. Try specifying the type arguments explicitly.

**Steps to reproduce:**
- create script structure like this
```c++
Item : public Script
{
   struct Attribute : ...
   {

   };
};
struct RuntimeItem  : ...
{
   API_FIELD() Array<Item::Attribute> Attributes;
};
```
compile
get the errors

[edit]
genereted ouput
```c#
        internal static void Free(RuntimeItemInternal unmanaged)
        {
            ManagedString.Free(unmanaged.Name);
            if (unmanaged.m_ItemAsset != IntPtr.Zero) { ManagedHandle.FromIntPtr(unmanaged.m_ItemAsset).Free(); }
            if (unmanaged.Attributes != IntPtr.Zero) { ManagedHandle handle = ManagedHandle.FromIntPtr(unmanaged.Attributes); Span<Item.AttributeMarshaller.Item.AttributeInternal> values = (Unsafe.As<ManagedArray>(handle.Target)).ToSpan<Item.AttributeMarshaller.Item.AttributeInternal>(); foreach (var value in values) { Item.AttributeMarshaller.Free(value); } (Unsafe.As<ManagedArray>(handle.Target)).Free(); handle.Free(); }
        }
```

**Comment by GoaLitiuM** [comment]
The following compiles just fine, are you missing `API_STRUCT()` from the `Attribute` struct?
```cpp
API_CLASS() class GAME_API Item : public Script
{
API_AUTO_SERIALIZATION();
DECLARE_SCRIPTING_TYPE(Item);

    API_STRUCT() struct GAME_API Attribute
    {
        DECLARE_SCRIPTING_TYPE_MINIMAL(Attribute);
    };

    // [Script]
    void OnEnable() override;
    void OnDisable() override;
    void OnUpdate() override;
};

API_STRUCT() struct GAME_API RuntimeItem
{
    DECLARE_SCRIPTING_TYPE_MINIMAL(RuntimeItem);
    API_FIELD() Array<Item::Attribute> Attributes;
};```

**Comment by cNori** [comment]
> The following compiles just fine, are you missing `API_STRUCT()` from the `Attribute` struct?
> ```cpp
> API_CLASS() class GAME_API Item : public Script
> {
> API_AUTO_SERIALIZATION();
> DECLARE_SCRIPTING_TYPE(Item);
> 
>     API_STRUCT() struct GAME_API Attribute
>     {
>         DECLARE_SCRIPTING_TYPE_MINIMAL(Attribute);
>     };
> 
>     // [Script]
>     void OnEnable() override;
>     void OnDisable() override;
>     void OnUpdate() override;
> };
> 
> API_STRUCT() struct GAME_API RuntimeItem
> {
>     DECLARE_SCRIPTING_TYPE_MINIMAL(RuntimeItem);
>     API_FIELD() Array<Item::Attribute> Attributes;
> };
> ```

I have it in the source but i striped from ishue for redability

**Comment by mtszkarbowiak** [comment]
I think, for structs you should use `DECLARE_SCRIPTING_TYPE_STRUCTURE`.

**Comment by cNori** [comment]
found the place for a patch
BindingsGenerator.CSharp.cs:~1640
this will fix it 

                            string originalElementType = originalType[0..^2];

                            if (internalType)
                            {
                                // Marshal blittable array elements back to original non-blittable elements
                                string originalElementTypeMarshaller = originalElementType + "Marshaller";
                                //[Nori_SC note]
                                //Find all characters after last . as a example if the c++ type is Class.Struct it will generate a invalid c# code
                                //with will look like this <Class>.<Struct>Marshaller.<Class>.<Struct>Internal
                                //valid code looks like this <Class>.<Struct>Marshaller.<Struct>Internal

                                var startindex = originalElementType.LastIndexOf('.') + 1;

                                string internalElementType = $"{originalElementTypeMarshaller}.{originalElementType[startindex..]}Internal";

**Comment by GoaLitiuM** [comment]
The final code that reproduces the issue:
```cpp
API_CLASS() class GAME_API Item : public Script
{
API_AUTO_SERIALIZATION();
DECLARE_SCRIPTING_TYPE(Item);

    API_STRUCT() struct GAME_API Attribute
    {
        DECLARE_SCRIPTING_TYPE_MINIMAL(Attribute);
        API_FIELD() String foo;
    };

    // [Script]
    void OnEnable() override;
    void OnDisable() override;
    void OnUpdate() override;
};

API_STRUCT() struct GAME_API RuntimeItem
{
    DECLARE_SCRIPTING_TYPE_MINIMAL(RuntimeItem);
    API_FIELD() Array<Item::Attribute> Attributes;
};
```
