### ISSUE TITLE
Error when loading a new project with 1.8.1

### ISSUE THREAD

**Issue by MudhenTV** [FlaxEngine/FlaxEngine#2597]
There is an odd bug when using the master branch, 1.8.1 of Flax. If I make a new project or use one of the Flax Samples, as soon as the editor opens, it starts spamming the console with errors about not being able to save an Asset or a thumbnail because one of the cache files are in use. It seems to be lock on another thread or something like that. It then attempts to release a handle to it, but goes into an endless loop of errors. This might be unrelated, but I noticed that when this happens, it also fails to load some assets in the Sample projects, and I also cant open any of the Shaders, it just crashes the window.
![image_2024-05-13_134506053](https://github.com/FlaxEngine/FlaxEngine/assets/89992464/367ba0ff-8152-4a28-ac9b-e227dc9fb511)

**Comment by cNori** [comment]
bug has been replicated by me
with sync to the master

last sync ~ 203f03a597a5749cf77c24f69479022a6e8a2cac (worked fine)
curent sync https://github.com/FlaxEngine/FlaxEngine/commit/44006dd53396362d57e05dc07f74be0e0a58fbb0 (with this bug)
