### ISSUE TITLE
ScriptingObject::CreateManagedInternal() tries to get Managed class name when there is no managed class assigned

### ISSUE THREAD

**Issue by klukule** [FlaxEngine/FlaxEngine#26]
**Issue description:**
ScriptingObject::CreateManagedInternal() checks for existence of Managed counterpart for given scripting object, if none is found it tries to print Warning message... here is the problem, it uses ToString() which gets it's name from Managed Class. 
This results in Access Violation exception

**Steps to reproduce:**
- Create Visual Script
- Add GetKeyboard node
- Connect it to some node which will use it
- Hit play

**Minimal reproduction project:**
- none, see images
![image](https://user-images.githubusercontent.com/3607341/102777502-f9c94180-4390-11eb-8535-0ea7b6b98d4f.png)
![image](https://user-images.githubusercontent.com/3607341/102777531-08aff400-4391-11eb-9bca-8e3abe39f009.png)

**Flax version:**
1.0 (Source build Commit #96457a0adc62bb26725ca1b6250b5c29b221f68d)

**Comment by mafiesto4** [comment]
Fixed in #71 and 140fae3fa17c23ba5bf4ba951ce94784f40b6c5a
