### ISSUE TITLE
Duplicating a control with children swaps first and second child around

### ISSUE THREAD

**Issue by xxSeys1** [FlaxEngine/FlaxEngine#2601]
**Issue description:**

When duplicating a control with CTRL + D the order of the first and second child is swapped.

*Here's a screenshot of the "aftermath" of the bug*

![image](https://github.com/FlaxEngine/FlaxEngine/assets/111653551/8d2913f1-6b1a-48e0-8e24-0b5b76affb86)

**Steps to reproduce:**

This is the thing: I have no idea. 

Every bug I find in the ui editor is unreplicatable for whatever reason. It happened out of nowhere, an editor restart "fixed" it.

I'll try to repro this but no promise that I can.

**Minimal reproduction project:**

none

**Flax version:**

1.8.1

**Comment by mafiesto4** [comment]
Test prefab: [UI Prefab.zip](https://github.com/FlaxEngine/FlaxEngine/files/15378329/UI.Prefab.zip)

I was unable to repoduce it for now.

**Comment by xxSeys1** [comment]
I've tried reproducing this a bunch and I can't.
Gonna close it for now, maybe it was a weird edge case or user error.

Also never had it happen again when using the ui editor
