### ISSUE TITLE
Cursor sometimes stays in cursor lock after leaving play mode

### ISSUE THREAD

**Issue by xxSeys1** [FlaxEngine/FlaxEngine#2602]
**Issue description:**

When using `Screen.CursorLock == CursorLockMode.Clipped`, sometimes the cursor stays confined to the game window.

**Steps to reproduce:**

Nothing currently, will update this if I find any.

**Minimal reproduction project:**

none

**Flax version:**

1.8.1

**Comment by Tryibion** [comment]
Should have been fixed here <https://github.com/FlaxEngine/FlaxEngine/pull/2551>
