### ISSUE TITLE
[Suggestion] Decal Layers or Decal Object Mask

### ISSUE THREAD

**Issue by Myterian** [FlaxEngine/FlaxEngine#2603]
It'd be nice to have a way to include or exclude a set objects or singluar objects, to control where decals can draw on. Currently they draw on everything withing the decal box, meaning blood can appear and disappear on a characters shoe as you walk through a decal

**Comment by Menotdan** [comment]
There is an option on material slots in models to disable decals drawing on them but a more advanced system could be useful.

**Comment by Myterian** [comment]
I mean, that is not an ideal solution. But it helps in this case. At least until the character is supposed to get decals, too

**Comment by Tryibion** [comment]
Duplicate of <https://github.com/FlaxEngine/FlaxEngine/issues/967>
