### ISSUE TITLE
Two Bone IK Animation wired after 1.8 update

### ISSUE THREAD

**Issue by MCPE357** [FlaxEngine/FlaxEngine#2610]
Issue description: I am not sure if this is engine bug or outdated project but on 1.7.2 works fine and in 1.8+ the legs position is off
![Screenshot 2024-05-17 044141](https://github.com/FlaxEngine/FlaxEngine/assets/89349227/bdb10c52-6a0c-43bc-a7a2-bcd6a3e09848)
![Screenshot 2024-05-17 043951](https://github.com/FlaxEngine/FlaxEngine/assets/89349227/23504134-5174-4ba0-b5cc-99dc6de082ba)

Steps to reproduce: Download this project https://github.com/PrecisionRender/CharacterControllerPro  . Open the folder and there is Flax project go to MainMenu scene or ThirdPersonDemo scene on version 1.8 to see the issue. Open flax 1.7.2 to see how it is supposed to work.

Flax version: 1.8+

**Comment by mafiesto4** [comment]
I think #2421 broke it.

**Comment by mafiesto4** [comment]
I reverted that PR in 73f68c102d9a84cbbd360c6ac53663c457b7686d to make it work.

**Comment by MCPE357** [comment]
> I reverted that PR in [73f68c1](https://github.com/FlaxEngine/FlaxEngine/commit/73f68c102d9a84cbbd360c6ac53663c457b7686d) to make it work.

Using the newest Master branch 97314377172f294753ded61e9e47f37f4a6f7584 the problem is not solved

**Comment by mafiesto4** [comment]
Another issue with new ik:

https://github.com/FlaxEngine/FlaxEngine/assets/3464853/6bd5e46f-ba6c-4936-95b2-77c0f50ac56a

**Comment by mafiesto4** [comment]
Reverted back to 1.8 logic.
