### ISSUE TITLE
Visual scripting bug - Wrong input type displayed in array add input

### ISSUE THREAD

**Issue by Plumepackdev** [FlaxEngine/FlaxEngine#2613]
Tested on main branch up-to-day as of the time of writing.
![imageik](https://github.com/FlaxEngine/FlaxEngine/assets/139954560/a36fc80c-9848-4395-98b4-7602c45eb802)

I was debugging a visual script with an Array Add node in it. I had a breakpoint passed that node and while hitting the breakpoint, I hovered my mouse over the Array Add node "item" input, which displayed "Array" as the item, while it was clearly (for the array plugged into the "array" input and for the item I was actually inputing) not an Array, but an actor.

To replicate, try making a visual script, create an array and try to add an item to it through the script. Add a breakpoint to the "set" node, and hover over the "item" input.

**Comment by mafiesto4** [comment]
Should be fixed now. OR at least I wasn't able to reproduce it now.
