### ISSUE TITLE
Problem with "Get Node Transform (local space)" and "Get Node Transform (model space)"

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#262]
There is an issue with the Get Node Transforms.
They are missing their execution pins.

![image](https://user-images.githubusercontent.com/35228400/108615338-1b10e180-7457-11eb-91e7-a0b98a523652.png)

I tried to fix the source myself by changing the .CS to:
`NodeElementArchetype.Factory.Output(0, string.Empty, typeof(void), 1),`

I also updated the .CPP to reflect the new structure but clearly I'm doing something wrong as the transform never seems to work correctly.
![image](https://user-images.githubusercontent.com/35228400/108615448-4a741e00-7458-11eb-9819-4703fa4a4c98.png)

**Comment by mafiesto4** [comment]
The idea behind the `Get Node Transform` nodes (local and model space) is that they don't use this white flow arrow which contains a bones transformations. Here is an example of usage:

![image](https://user-images.githubusercontent.com/3464853/108628180-cb7fe500-7459-11eb-869a-d5b68369936f.png)

The white pins are not execution flow signals like in Visual Script but the value flow like in Material Graph.

**Comment by stefnotch** [comment]
Would it be reasonable to change the icon of the white pins in the animation graph, since their meaning is quite different?

**Comment by mafiesto4** [comment]
I guess yeah, we could use a bone icon for this or an animated pose.

**Comment by Evildea** [comment]
I like the idea of using an animated pose icon. I assumed it worked exactly like the visual scripting because they looked the same. Thanks for clearing that up.

**Comment by stefnotch** [comment]
By the way, if anyone is interested in fixing this, here is the relevant part of the source code
https://github.com/FlaxEngine/FlaxEngine/blob/87a290b45c73d90b0eec5fa89a3a6d4a56603638/Source/Editor/Surface/Elements/Box.cs#L515-L519
