### ISSUE TITLE
bindings gen bug again

### ISSUE THREAD

**Issue by cNori** [FlaxEngine/FlaxEngine#2626]
**Issue description:**
```c#
namespace Foo
{
class Foo
{
        private static IFoo FooInterface
        {
            get { return Internal_GetFooInterface(); }
            set { Internal_SetFooInterface(FlaxEngine.Object.GetUnmanagedInterface(value, typeof(Foo.IFoo))); } <-- invalid c# code here
        }
}
namespace Foo
{
    [Unmanaged]
    public unsafe partial interface IFoo
    {
    }
}
}
```
**Steps to reproduce:**
create plugin Foo
enable c++
create class Foo
create interface IFoo
use IFoo inside Foo
compile

**Comment by Tryibion** [comment]
Looks like a clashing namespace and class name...

**Comment by cNori** [comment]
> Looks like a clashing namespace and class name... not sure what the fix is... maybe not fully qualifying the name?

it will solve it
