### ISSUE TITLE
UI Controls don't receive `Update` event

### ISSUE THREAD

**Issue by mtszkarbowiak** [FlaxEngine/FlaxEngine#2627]
**Issue description:**

Custom UI controls don't receive invokes on `override void Update(float deltaTime)` event method. This breaks existing controls.

**Steps to reproduce:**

1. Create a custom control.
2. Declare aforementioned overriding method.

**Flax version:**

1.8, I think it was NOT in 1.7

**Comment by Tryibion** [comment]
Works fine for me... even runs while not in play mode.

**Comment by mtszkarbowiak** [comment]
I was preparing the code when it clicked it my brain: `Update` is not invoked if the checkbox *Receives Events* for the canvas is checked off. The comment for this checkbox says though that it should be used to disable **input** events.

**Comment by Tryibion** [comment]
I see. I guess the question is, should it call update if that is uncheck marked? there could be inputs firing in the update loop....

**Comment by mtszkarbowiak** [comment]
I think it should. My understanding is the following:

1. Creating a canvas which does not receive input is useful. It may be used for Player's HUD which never interacts with mouse, just displays info.
2. Such canvas should still be update-able. For example health bars, map markers, etc. Time dependence allows for animations. That's why it takes delta time as a param.
3. Control has separate `Update` and `Draw` to distinguish the process of drawing and updating state, meaning that the engine may draw the control multiple times between updates, and vice versa. (As I remember Unity can do that.)
4. Ultimately, to modify if a script is *updating*, the engine uses `Enabled`. If so, the controls should follow it.
