### ISSUE TITLE
[Suggestion] Add option to chose prefab root actor class when create it from content folder menu

### ISSUE THREAD

**Issue by Snakemonster** [FlaxEngine/FlaxEngine#2632]
It's pretty annoying when you want to create prefab with root actor like CharacterController, RigidBody, CustomActorClasses, etc from Content folder menu. To do that, you need to create actor with desired class on scene, and only then add that actor as prefab.

It will be more comfortable to see popup window to choose what Actor class will be as root actor class before creating prefab (like JsonAssets, Visject, etc).

**Comment by mafiesto4** [comment]
Will be added soon in #2415
