### ISSUE TITLE
Pasting previously copied sprites does not work in sprite atlas

### ISSUE THREAD

**Issue by tecnessino** [FlaxEngine/FlaxEngine#2643]
**Issue description**:
Pasting previously copied sprites does not work in sprite atlas

**Steps to reproduce**:
Just create a sprite atlas, copy sprites and paste

Flax version:
Latest

**Comment by mafiesto4** [comment]
Added copy-paste context menu option to sprite group panel in 69240424526d42b92511b292b57686940deccf4b.
