### ISSUE TITLE
Importing normals of fbx meshes done in Blender 4.x broken

### ISSUE THREAD

**Issue by Ovahlord** [FlaxEngine/FlaxEngine#2651]
**Issue description:**
- According to some tests with a contributor in the discord, it turns out that importing a mesh with the normals exported from blender 4.x results in messed up normals on importing.

The blender mesh
![Screenshot 2024-05-25 090507](https://github.com/FlaxEngine/FlaxEngine/assets/18347559/3c5ec618-ec93-442c-a033-bc5939ffb42e)

The imported mesh in engine
![Screenshot 2024-05-25 090415](https://github.com/FlaxEngine/FlaxEngine/assets/18347559/b657aae6-0c3c-484a-996e-a34f93d56a68)

**Steps to reproduce:**
1. Use this blend project to export the mesh in Blender 4 (I used 4.1 in this case)
[Blob.zip](https://github.com/FlaxEngine/FlaxEngine/files/15442110/Blob.zip)

2. Import the fbx into Flax without calculating the normals in-engine
3. Place the mesh into the scene and observe the normals are all messed up

**Flax version:**
1.8

**Comment by cNori** [comment]
flax does not handle quads correctly
cheak the tralagulate before the export or use
https://github.com/cNori/Blender-Link
with will do the same thing

**Comment by mafiesto4** [comment]
Fixed in #2672
