### ISSUE TITLE
TAA+Downsampling is broken

### ISSUE THREAD

**Issue by Bits360** [FlaxEngine/FlaxEngine#2689]
**Issue description:**
TAA+Downsampling doesnt work correctly together, and causes heavy jitter and INTENSE blur on the bottom of the screen, but looks fine on the top

**Steps to reproduce:**
1: Lower res
2: Turn on TAA
3: Look at screen

**Minimal reproduction project:**
https://drive.google.com/file/d/1kUAPDYWPjpEMAnU8-CcHSLvBQSvPieCY/view?usp=sharing

Project sets screen res to 50% to make jitter and blur on the bottom of the screen extremely obvious

**Flax version:**
1.8.2

**Comment by mafiesto4** [comment]
I was unable to reproduce it on the latest `master`. Also, that repro project link seams to be outdated.

If you still have this issue please reopen it and attach that repro project (refresh link) or describe it better with some gif/img.
