### ISSUE TITLE
UV-flipbook is broken. The sequence is broken if the frame number is not rounded to integer and on the vertical border.

### ISSUE THREAD

**Issue by DoubleSinoptic** [FlaxEngine/FlaxEngine#2690]
uv-flipbook is broken. The sequence is broken if the frame number is not rounded to integer and on the vertical border.
This breaks the animation sequence through flipbook
set frameXY - 5 - 5
set frame index: 4.9999 
expected frame coord: (0, 1) 
resulting frame coord: (0, 0)

[FlipbookBug.zip](https://github.com/user-attachments/files/15678002/FlipbookBug.zip)

**Comment by mafiesto4** [comment]
Fixed in 21ed4a2371f527161af58b89a57cc32b477b9a2a.
