### ISSUE TITLE
Infinity grid does not works with Large Worlds enabled

### ISSUE THREAD

**Issue by MrCapy0** [FlaxEngine/FlaxEngine#2697]
**Issue description:**
I can't compile the editor myself.
![image](https://github.com/FlaxEngine/FlaxEngine/assets/167662176/d981fe05-e148-4555-b98a-87a452bc7fb7)
 
I have tried a quick fix of the double types but the grid is not rendering.

**Flax version:**
https://github.com/FlaxEngine/FlaxEngine/commit/0bb21ef4a036114ab265a8a2755b45f013748c05

**Comment by mafiesto4** [comment]
Fixed in b1fd1783411e72faca1987412399c86bea94fff0.
