### ISSUE TITLE
Thai Text issues

### ISSUE THREAD

**Issue by wutipong** [FlaxEngine/FlaxEngine#27]
**Issue description:**
 Flax doesn't seem to support Thai (or any other non-Latin languages, I assume). 

The main problem is the output in the viewport are not correctly shaped.  Some glyphs are not correctly placed. This is usally caused by lacking of open type support. AFAIK only a handful of game engine do support this, including Unreal Engine 4, and probably Godot.

From skimming through the code I don't find any open type shaping function, so I assume that text shaping support is currently zero. Probably only truetype layout is supported at the moment.

Also I found that after pressing play and pause, the text somehow changed into something else entirely. Possibly access violation ?

Last but not least, When entering in the GUI textbox, all glyph are displayed as a placeholder (a box with an X inside). 

**Steps to reproduce:**
I create a `TextRender` object, assign a font into it, input some Thai text ( the phrase "ตะปุ่มตะป่ำ" is used as it is short yet demonstrate this issue very well), and then flip the object upside down to get it right side up.

![image](https://user-images.githubusercontent.com/3213191/102789293-7f231500-43d6-11eb-8d14-6e0cafaaadbd.png)

After pressing `Play`, the input text somehow changed and no longer the original text.

![image](https://user-images.githubusercontent.com/3213191/102789373-a7127880-43d6-11eb-9151-f9df6f28e1b5.png)

Then press the pause button, the input text get changed one more time.

![image](https://user-images.githubusercontent.com/3213191/102789451-c4474700-43d6-11eb-95e7-df7ea99c0c4e.png)

**Minimal reproduction project:**

[MyProject.zip](https://github.com/FlaxEngine/FlaxEngine/files/5724943/MyProject.zip)

**Flax version:**

1.0

**Comment by VNNCC** [comment]
The default font that is used by the Editor is called [Roboto-Regular](https://fonts.google.com/specimen/Roboto), which doesn't support these character.

**Comment by W2Wizard** [comment]
You can change the font to a font that does support these characters like [Arial Unicode](https://www.fonts.com/font/monotype/arial-unicode?QueryFontType=Web&src=GoogleWebFonts) additionally all fonts in the engine can be changed quite easily as well if required. Hope this helps!

**Comment by wutipong** [comment]
Well reverting the font to Thai font file (eg. Arial) might help, at least just to make the string readable. However it probably doesn't help the issue in the last screenshot where the string got update to something else entirely after pressing play. 

I will be testing this later today and will let you guys know.

Ideally it would be nice to have OpenType text shaping, but that can be expensive in the run time.

**Comment by W2Wizard** [comment]
Has it helped with your second issue btw?

**Comment by stefnotch** [comment]
This is where the text gets serialized

https://github.com/FlaxEngine/FlaxEngine/blob/8158c94d26c1cc233933e638b810f55602f7f394/Source/Engine/UI/TextRender.cpp#L398

which, I think, calls
https://github.com/FlaxEngine/FlaxEngine/blob/8158c94d26c1cc233933e638b810f55602f7f394/Source/Engine/Serialization/Serialization.h#L307

and this ends up calling

https://github.com/FlaxEngine/FlaxEngine/blob/8158c94d26c1cc233933e638b810f55602f7f394/Source/Engine/Platform/Win32/Win32StringUtils.cpp#L188-L192

**Comment by mafiesto4** [comment]
Yeah scenes and prefabs are in `UTF-8` format but we use `rapidjson` which can support encoding conventions (https://rapidjson.org/md_doc_encoding.html). It guess it would be nice to have. Especially when making game localization in custom Json assets.

**Comment by mafiesto4** [comment]
Sorry for the late fixing but UTF-8 and UTF-16 characters are not properly decoded from Json files. Will be available in 1.1 update soon.
