### ISSUE TITLE
Transparent, Additive and Multiply materials is not reflecting the SDF world.

### ISSUE THREAD

**Issue by abrasivetroop** [FlaxEngine/FlaxEngine#2703]
**Issue description:**
Transparent materials do not reflect the SDF world.

Opaque material with metalic set to 1
![image](https://github.com/FlaxEngine/FlaxEngine/assets/47716519/a123738d-bba5-4364-a23e-259b991d9bcb)

Transparent material with metalic and opacity set to 1
![image](https://github.com/FlaxEngine/FlaxEngine/assets/47716519/b815794b-9535-4ca1-a686-493a446e53b1)

Same transparent material with SSR
![image](https://github.com/FlaxEngine/FlaxEngine/assets/47716519/3ea8b610-8558-4b01-906b-f5dd2d2f1406)

**Steps to reproduce:**
1. Create a transparent material and set it's opacity to 1
2. Enable DDGI and software reflections
3. No SDF reflections on transparent material at all
**Minimal reproduction project:**

**Flax version:**

**Comment by HydrogenC** [comment]
I guess this is because that the forward pass (which handles non-opaque objects) is executed after the reflections pass, as is written in `Renderer.cpp`:  
<https://github.com/FlaxEngine/FlaxEngine/blob/f52059522b524daddb1ad2659647d41db8ff2496/Source/Engine/Renderer/Renderer.cpp#L547>  
<https://github.com/FlaxEngine/FlaxEngine/blob/f52059522b524daddb1ad2659647d41db8ff2496/Source/Engine/Renderer/Renderer.cpp#L581>

**Comment by abrasivetroop** [comment]
So if this is simply an error in render execution order, solving it shouldn't be too hard?

**Comment by HydrogenC** [comment]
> So if this is simply an error in render execution order, solving it shouldn't be too hard?

I suppose it's more difficult. Since effects like reflections and SSR shaders relies on GBuffer to acquire information, and that forward pass doesn't write to the GBuffer, a separate implementation has to be created.

**Comment by abrasivetroop** [comment]
Okay thanks for the explanation!

**Comment by abrasivetroop** [comment]
@HydrogenC How about using the information from the last frame to add the reflections? That would be easier to implement I think.

**Comment by HydrogenC** [comment]
> @HydrogenC How about using the information from the last frame to add the reflections? That would be easier to implement I think.

That's unneccessary though. What is needed to do reclections is just normal and world position, and they can be calculated and passed through the vertex shader. With these information we can handle reflections in the same way as opaque materials.

**Comment by abrasivetroop** [comment]
Okay I see thanks for explaining!

**Comment by HydrogenC** [comment]
@abrasivetroop Well, I read all of the code involved and I have to correct what I've said before.  
The reflection feature itself has already be integrated into the forward pass in the current version, but the true problem is that SDF tracing isn't implemented for forward materials. It would take another 2 constants and 7 additional texture slots to implement SDF reflection tracing and I'm trying to find a way to implement that :(

**Comment by abrasivetroop** [comment]
@HydrogenC Oh damn, thanks for trying! This is one of the things that bothered me a lot in my poolrooms demo because the reflections didn't look right with only SSR but if you can pull it off this would be a great addition!

**Comment by HydrogenC** [comment]
I opened a pull request for this.
