### ISSUE TITLE
Ui elements taborder

### ISSUE THREAD

**Issue by ptcsoderlund** [FlaxEngine/FlaxEngine#2704]
**Issue description:**
When i edit Transform for UIControl and try to tab to next setting, it dissappears or jumps to strange places.

**Steps to reproduce:**

Add an UIControl. Edit "Left" or "Right" for transform , then press tab.

**Flax version:**

1.8.2

**Comment by mafiesto4** [comment]
Fixed by adding explicit navigation path into UI Control transform editor: 8f0cf3b8ef78d052edc3525791c72fe5c1a0a91d
