### ISSUE TITLE
CharacterController.SimpleMove is not usable in its current state

### ISSUE THREAD

**Issue by Vizepi** [FlaxEngine/FlaxEngine#2726]
**Issue description:**
CharacterController.SimpleMove is supposed to take a user velocity and manage gravity on its own.  
However, as the method is implemented right now, the gravity velocity is never accumulated frame to frame.  
This leads to CharacterController only slightly falling each frame instead of gaining vertical speed.  

**Steps to reproduce:**
- Open the provided project
- Open the scene
- Play
- Press Up-Arrow until the capsule is in the air
- Observe its vertical velocity is not increasing as it should

**Minimal reproduction project:**
[Project.zip](https://github.com/user-attachments/files/15930362/Project.zip)

**Flax version:**
1.8.2

**Host**
Windows 11  
Laptop Acer Nitro V 15 (ANV15-51-754J)

**Comment by mafiesto4** [comment]
Fixed by #2758
