### ISSUE TITLE
There's no such thing as a Launcher

### ISSUE THREAD

**Issue by warethis-dev** [FlaxEngine/FlaxEngine#2734]
I've tried, searched everywhere.. people talk about a launcher, there's even some screenshots but there's literally no launcher available anywhere. I, after a very long time, was able to build the engine for Linux but there is no launcher and i'm pretty sure it's a myth at this point. I can't find it for any OS let alone Linux.

**Comment by Menotdan** [comment]
No, it exists, in fact its what's downloaded when you do the windows download. The launcher isn't cross platform though, someone made a cross-platform launcher but its not official and its not maintained at this point I think.
![image](https://github.com/FlaxEngine/FlaxEngine/assets/32620310/4cbdd84e-237b-42f3-80ef-c85963d0c85b)
Here is a screenshot from the launcher open on my PC

The cross-platform launcher is at https://github.com/MineBill/Seed

**Comment by warethis-dev** [comment]
if the launcher's not cross platform, how can anyone even use the engine cross platform then? Everything says "open the launcher and start a project" really? i've put 12 solid hours into Flax now and i still haven't got a single scene with a primitive object in it. I've just installed Unity an hour ago and I'm already using it.

**Comment by tecnessino** [comment]
Build it from scratch or use Seed. That is the solution. Building is easy and everything documented

**Comment by warethis-dev** [comment]
where? where is everything documented? I spent 3 hours yesterday digging through documentation trying and trying to build the engine only to find here in the github Issues that if you have Linux Mint you need to install g++-12 as a dependency and like magic.. i had an engine but i still didn't have a launcher and none of the documentation was worth anything because no launcher
