### ISSUE TITLE
Negative scale does not work with colliders

### ISSUE THREAD

**Issue by MrCapy0** [FlaxEngine/FlaxEngine#2737]
I'm using convex / triangle mesh as collider and i can't inver the collider using negative scale, like (-1, 1, 1) or (1, 1, -1).

https://github.com/FlaxEngine/FlaxEngine/assets/167662176/f6797222-6222-4c37-9c07-60053d2bb63b

Note:
I'm using large worlds.

**Minimal reproduction project:**
[Model.zip](https://github.com/user-attachments/files/16019411/Model.zip)

**Flax version:**
master

**Comment by abrasivetroop** [comment]
This happens without large worlds as well! I remember finding out about this months ago but I forgot to report it! Thanks for reporting.
