### ISSUE TITLE
Visject pasting fails

### ISSUE THREAD

**Issue by stefnotch** [FlaxEngine/FlaxEngine#274]
**Issue description:**
Certain nodes, like the `Add` node are prone to failing when pasting

Caused by something in https://github.com/FlaxEngine/FlaxEngine/blob/master/Source/Editor/Surface/VisjectSurface.CopyPaste.cs

**Steps to reproduce - long winded way**
1. Open a Visject Surface
2. Create a Vector2 node
3. Create an add node after it and connect it to the Vector2 node
4. Write a value in the add node
5. Copy it
6. Paste it
![image](https://user-images.githubusercontent.com/10220080/108832352-b88d2200-75cb-11eb-9005-151ec2b18305.png)

**Steps to reproduce - quick way**
Copy the following text and paste it
```json
{
	"Nodes": [
		{
			"GroupID": 3,
			"TypeID": 1,
			"ID": 18,
			"X": 0,
			"Y": 0,
			"Values": [
				{
					"Value": {
						"$type": "FlaxEngine.Vector2, FlaxEngine.CSharp",
						"X": 0.0,
						"Y": 0.2
					}
				},
				{
					"Value": {
						"$type": "FlaxEngine.Vector2, FlaxEngine.CSharp",
						"X": 0.1,
						"Y": 3.7
					}
				}
			],
		}
	]
}
```

**Flax version:**
Flax 1.1

**Comment by stefnotch** [comment]
By the way, for Visject nodes, it would be convenient if we could copy them without all the formatting. That would make it much easier to share them on space constrained online forums or Discord.

**Comment by mafiesto4** [comment]
Works fine on the latest Flax 1.6 version. Probably fixed some time ago.
