### ISSUE TITLE
Strange DDGI artifacts

### ISSUE THREAD

**Issue by abrasivetroop** [FlaxEngine/FlaxEngine#2743]
**Issue description:**
I am not entirely sure how to explain what I am seeing here so I just call it "ghosting". Best I can do is to demonstrate it with photos.

First problem is this strange ghosting happening with meshes that has a hole in it. This effect almost feels like a parallax effect when the camera is moving.

![image](https://github.com/FlaxEngine/FlaxEngine/assets/47716519/5643f9cb-2228-4d42-be1c-173f95430082)

![image](https://github.com/FlaxEngine/FlaxEngine/assets/47716519/c74c387f-5b10-439d-a5bc-5f0405936e5e)

Another issue is this strange self relfecting

![image](https://github.com/FlaxEngine/FlaxEngine/assets/47716519/bc29b888-7019-4ff6-8019-5b0ec70554a7)

Here is Global Surface Atlas of the same screenshot.

![image](https://github.com/FlaxEngine/FlaxEngine/assets/47716519/bebaa8cd-9ad6-4453-839c-fd08b86919dc)

The effect is more promiment with lower intensities.

![image](https://github.com/FlaxEngine/FlaxEngine/assets/47716519/648d289d-e3b4-4b78-ab09-1b83c2ccc499)

![image](https://github.com/FlaxEngine/FlaxEngine/assets/47716519/da979273-b1c3-4a50-a799-13aeed8d0b48)

**Steps to reproduce:**
Here is the models and the texture I use in the screenshots.
[modular.zip](https://github.com/user-attachments/files/16068308/modular.zip)

**Flax version:**
1.8.2

**Comment by abrasivetroop** [comment]
Here is a video demonstration

https://github.com/FlaxEngine/FlaxEngine/assets/47716519/0c2b387f-bea3-46f2-9a72-0cb62964c158

**Comment by mafiesto4** [comment]
This looks like kind of self-reflection bug.

**Comment by abrasivetroop** [comment]
Yes it seems so. I should have mentioned disabling Software Tracing removes all these artifacts so it's definitely some sort of self-reflection bug.

**Comment by abrasivetroop** [comment]
This is how it looks in a dark room. Software tracing is enabled and there is a Directional Light and a Sky in the scene. Disabling those gets rid of this.

![image](https://github.com/FlaxEngine/FlaxEngine/assets/47716519/d1fc5f99-eca8-4701-bd80-921437fda463)

**Comment by mafiesto4** [comment]
Fixed in e7f1afdfaa00726527c6299d750d77aca929188e.
