### ISSUE TITLE
Editor window doesn't handle mouse correctly when in isometric mode

### ISSUE THREAD

**Issue by Taugeshtu** [FlaxEngine/FlaxEngine#2748]
**Issue description:**
When switching Editor window's camera into isometric mode, I cannot select objects, cannot operate gizmos - something potentially wrong with mouse interaction handling, raycasting or something?

**Steps to reproduce:**
1. Open Editor window with some objects in scene
2. Select one of the objects, have a modifying gizmo show (definitely works with translation, rotation, and scale gizmos)
3. Switch camera to orthographic mode
4. Try operating the gizmo, or selecting objects

**Minimal reproduction project:**
Built-in "Basic Scene" project template is sufficient

**Flax version:**
1.8.6512.2

**Video:**

https://github.com/FlaxEngine/FlaxEngine/assets/6285293/75b7c6f3-3830-42c4-aa23-405a7c7d4bff

**Comment by mafiesto4** [comment]
Fixed in 2542adba92bc3ef519b4d15a7ed80292efaa2f70,
