### ISSUE TITLE
Static variables not cleared between Editor runs

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#275]
**Issue description:**
I have a static string that I use between during my game. I fill this static string with input from the keyboard. I've noticed that between Editor runs this static string doesn't appear to be cleared as it maintains input from the previous session.

**Steps to reproduce:**
1. Setup a class that uses a static string
2. Create an input system that adds to that static string during play.
3. End the play session
4. Start the play session and check the contents of that static string, you'll notice that the static string hasn't been cleared.

Please see this video to see the issue in action:
https://user-images.githubusercontent.com/35228400/108921756-ab833800-768a-11eb-9920-639c7b22dddb.mp4

You can use my test project for testing purposes:
[Test Project.zip](https://github.com/FlaxEngine/FlaxEngine/files/6032330/Test.Project.zip)

**Comment by mafiesto4** [comment]
That's because we don't reload scripting when entering the play mode. It's intended behaviour. Note that Editor is written in C# so it would affect it too.
