### ISSUE TITLE
Behaviour tree blackboard is ignoring Boolean changes

### ISSUE THREAD

**Issue by Zacoriot** [FlaxEngine/FlaxEngine#2790]
**Issue description:**

The "Is Player Visible" blackboard variable should reflect the value of the "_IsPlayerIsVisible()" from my KidnapperAI.cs. however it always return the value of true despite the "_IsPlayerIsVisible()" returning the correct values.

The Enemy should only follow the player when inside of the vision cone and it has line of sight. instead it always follows the player and ignores the _IsPlayerIsVisible() value.

I personally feel the issue is to do with the Behaviour tree.

**Steps to reproduce:**

1. Download the .Zip provided
2. Open the project in Flax Engine
3. Open the SandboxArena.scene
4. Run the game

**Minimal reproduction project:**

[FadedLightStandard.zip](https://github.com/user-attachments/files/16325933/FadedLightStandard.zip)

**Flax version:**

1.8.2

**Comment by Tryibion** [comment]
I traced it down to here <https://github.com/FlaxEngine/FlaxEngine/blob/master/Source/Engine/AI/BehaviorKnowledge.cpp#L71> seems like after it is set, the value returns 1 instead of 0 like it was set to.

**Comment by Zacoriot** [comment]
> I traced it down to here https://github.com/FlaxEngine/FlaxEngine/blob/master/Source/Engine/AI/BehaviorKnowledge.cpp#L71 seems like after it is set, the value returns 1 instead of 0 like it was set to.

Okay, so how do you think I can solve this?

**Comment by mafiesto4** [comment]
Fixed in 1e43b031ba32ed8d7d0784039b503c614d1bda8e.
