### ISSUE TITLE
Vehicle physics instable at low framerate

### ISSUE THREAD

**Issue by MrCapy0** [FlaxEngine/FlaxEngine#2796]
**Issue description:**

The vehicle suspension/collision is too unstable when running in low fps and this can be a problem if i have complex environments with others vehicles on low-end pcs, on my case, it's impossible to have a good gameplay in 30 fps because the vehicle jumps and have a aggressive jittering.

Pls, take a look on the discussion here:
https://discord.com/channels/437989205315158016/790657150674141265/1265313208202432542

My physics/time settings of the test: (i know 60 fps is essential, but i think this can help to simulate how will happen on low end pcs)
![image](https://github.com/user-attachments/assets/7747027e-aebd-476f-9042-8c9d5021a019)

Also, any fps variation can cause issues with collisions when on high speed.

Test with 30 fps 

https://github.com/user-attachments/assets/3e2e0fa6-84b0-4830-9271-1be43cf4148a

but 60fps + all fine

https://github.com/user-attachments/assets/1a3a97bb-707f-44de-9f5b-ec05f807120f

**Steps to reproduce:**

Test different fps settings

https://github.com/user-attachments/assets/57f27c8d-269b-4bb5-a214-8f7a511e281c

**Minimal reproduction project:**
[MyProject - Copy.zip](https://github.com/user-attachments/files/16363467/MyProject.-.Copy.zip)

**Flax version:**
https://github.com/FlaxEngine/FlaxEngine/commit/d879b8e064dc05a535419e54ba7bb40d42b92e43

**Comment by mafiesto4** [comment]
Fixed in 2a1706decb5afc48f3d87ae6a15e20ade760c66b.
