### ISSUE TITLE
[Bug] Audio in game sounds different from editor

### ISSUE THREAD

**Issue by Myterian** [FlaxEngine/FlaxEngine#2799]
**Issue description:**
I disabled `HRTF` in the `Audio Settings` in editor, because it improved the audio quality, but in the cooked game the audio sounds like `HRTF` is still on. Editor and Game are on the same platform (Windows). 

This is how it sounds in Editor with `HRTF` disabled

https://github.com/user-attachments/assets/dba99745-0f52-437b-8945-25685b52a6bc

This is how it sounds in Game (and also in Editor with `HRTF` enabled)

https://github.com/user-attachments/assets/cf03a525-b056-4243-bde0-dfa9abedccae

**Steps to reproduce:**
1. Import audio (it should sound worse than the not imported version)
2. Disable HRTF in audio settings (now audio should sound good)
3. Cook and run game (Audio is bad again)

**Minimal reproduction project:**
Base

**Flax version:**
1.8.6512.2

**Comment by Myterian** [comment]
After testing a bit it seems that `Audio Settings` don't get applied for Cooked games. This can be worked around with a script that just sets `HRTF` to disabled

**Comment by Tryibion** [comment]
If you can, test out this branch <https://github.com/Tryibion/FlaxEngine/tree/apply-hrtf-init>. It looks like you were correct that the HRTF setting was not applied on init. This should add that. If you can test and it works, I will make a PR with that fix.

**Comment by Myterian** [comment]
I'll give it a go next week. But bear with me, I've never tried to compile anything

**Comment by mafiesto4** [comment]
Fixed in #2799

**Comment by Myterian** [comment]
Just want to confirm this issue is fixed now
