### ISSUE TITLE
Bug replaying particle system before it finishes playing

### ISSUE THREAD

**Issue by Lumina97** [FlaxEngine/FlaxEngine#280]
**Issue description:**
Created a particle effect, placed it in the world, got a reference to it in script, called ParticleEffect.ResetSimulation(); twice and it crashed the editor when I call the function when the particle hasn't finished playing. I believe it's caused by the smoke effect but not 100% sure

**Steps to reproduce:**
Take given particle effect, Place in the world and call ParticleEffect.ResetSimulation();  on it when its already playing.

**Minimal reproduction project:**
[Particle Effects.zip](https://github.com/FlaxEngine/FlaxEngine/files/6051882/Particle.Effects.zip)

**Flax version:** 
1.0 (launcher)

**Comment by mafiesto4** [comment]
I tested this and I was unable to reproduce the crash on 1.1. Maybe the problem was already fixed. I tested repetitive effect resets and went through the code to find any issues.

**Comment by mafiesto4** [comment]
Tested again on Flax 1.6 and works fine.
