### ISSUE TITLE
[ Usability ] Add option to select json asset script

### ISSUE THREAD

**Issue by MrCapy0** [FlaxEngine/FlaxEngine#2805]
**Issue description:**

Currently there is no a way to quickly find the script of custom json assets
![image](https://github.com/user-attachments/assets/749e5aa6-d565-4951-903c-22cb11232747)

Would be good have it like scripts
![image](https://github.com/user-attachments/assets/c85899d8-a711-45cd-8be7-c7b896f0d0b0)

**Flax version:**
1.8.2

**Comment by Tryibion** [comment]
Maybe something like this?
![image](https://github.com/user-attachments/assets/b717a738-2b24-48fe-8ca5-c8f30381fb7c)

**Comment by MrCapy0** [comment]
Yeeess very nice, thanks @Tryibion
