### ISSUE TITLE
Crash after closing the Editor.

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#281]
**Issue description:**
I'm currently building Flax from source. Every now and then when I close the editor I experience a crash. This happens after the editor closes. Today I managed to get a log of this crash.

The Logs and dump are available here: https://drive.google.com/file/d/1wlydKeyMlmjEaaQ8WlHVAJ2UnjsdPUYj/view?usp=sharing

**Steps to reproduce:**
There are no particular steps.

**Flax version:**
Flax Master Branch

**Comment by mafiesto4** [comment]
It looks like related to this https://github.com/mono/mono/issues/16731 and fixed here https://github.com/FlaxEngine/FlaxEngine/commit/cdf66372e6c6169ca97349bd284bf2aa856f3aa3.
Running Flax with an environment variable `MONO_GC_DEBUG=4:sgen-gc,check-remset-consistency,nursery-canaries` would create a dump file in the project folder with Mono GC log and in case of this type of crash, it would contain info about the cause of the crash.

**Comment by Evildea** [comment]
I'll close this for now and reopen if needed
