### ISSUE TITLE
Drawing 2D text in Editor viewport using DebugDraw. Where to find suitable ProjectPoint method?

### ISSUE THREAD

**Issue by RomanZhu** [FlaxEngine/FlaxEngine#2814]
I have an actor in the world.
I want to draw 2D text attached to him in the editor viewport. Imagine leaving notes in the scene for level design.
![image](https://github.com/user-attachments/assets/c54379f6-99f1-438c-a175-6a5cd831a3c0)

This works only in the Game viewport:
```csharp
    public override void OnDebugDraw() {
        //Works to draw in game window
        Camera.MainCamera.ProjectPoint(Transform.Translation, out var pos);
        DebugDraw.DrawText(Text, pos, Color.Black);

        //How to get camera in editor viewport to project from?
    }
```

So I tried to find the camera that renders the editor viewport and found this: `Editor.Instance.Windows.EditWin.Viewport.ViewportCamera`

But this is not a real camera and doesn't have the same ProjectPoint method

How to output 2D text using DebugDraw in the Editor viewport?

**Comment by mtszkarbowiak** [comment]
If you need projection only to draw debug text in 3D space you already have an overload for that: `DebugDraw.DrawText(string text, Vector3 position, Color color, [...])`

**Comment by RomanZhu** [comment]
I need to draw in 2D space

**Comment by mafiesto4** [comment]
You can easily access main editor viewport info (projection, view matrices): `Editor.Instance.MainTransformGizmo.Owner.Viewport`

**Comment by RomanZhu** [comment]
I can access it, but having user friendly API is important (for similar reason why Camera actor has those Un/ProjectPoint API)

**Comment by mafiesto4** [comment]
Added in c1a5db616e0f45beebbfb572b0c33c073075ff24. Example usage:
```cs
FlaxEditor.Editor.Instance.MainTransformGizmo.Owner.Viewport.ProjectPoint(Transform.Translation, out var pos);
```
