### ISSUE TITLE
[BUG] The network profiler is very incorrect. Basic use of the HLAPI for networking results in much high transfer rates than previously expected.

### ISSUE THREAD

**Issue by lifeformed** [FlaxEngine/FlaxEngine#2815]
I was debugging performance issues with our networked game. I implemented a bytes-in/out-per-second metric to display in game, but noticed a big discrepancy with the profiler values. It claims to display bytes-per-second, but it's actually showing bytes-per-update.

Here's the relevant code:

![image](https://github.com/user-attachments/assets/ae626e16-482d-49e7-bd54-2ef5e7313c5e)

`avgStats.TotalDataSent` and `avgStats.TotalDataReceived` finds the average of all the data in the samples, but the samples are per update, not per second. Since the samples are already culled to just the last second, it doesn't need the division steps.

The implications of this are that networked data rates are significantly higher than expected. The Arizona Framework Sample with one host and one client shows in the profiler a reasonable 600 bytes per second sent from the server, but it's actually 36 kB per second! I confirmed this in Wireshark:

![image](https://github.com/user-attachments/assets/89f4dfae-d8dd-4a11-8961-3af3d8b69fe9)

I know the Networking stuff is still new and in progress, but this bug may have been hiding how unperformant it has been. The data transfer is currently too high to use for serious game testing. In our game we were starting to get to around 4MB/s on the server, and that's only with a small number of networked objects in use. I think we'll have to implement our own replication system for now.

**Comment by mafiesto4** [comment]
Thanks for noticing this issue! Fixed stats in 128321c655d1c5480df8a1496fafab5c0c75e5c7. For Flax 1.10 we have scheduled optimizing network replicator (lots of potential ways to make it more performant).

**Comment by mafiesto4** [comment]
Turns out another fix was needed for this chart in: https://github.com/FlaxEngine/FlaxEngine/commit/4ddf1a2cc87af8e2ae14b064188d2cc098ffce5b

Also, I started optimizing network streams by adding `NetworkKey` which sends `Guid` or `StringAnsi` (esp. for typenames, method names) as `uint32` which reduced idle send rate from that 36kB/s to around 6kB/s: 443fe5dbcbea59f0a361058cffb9199bf030d520

More improvements are incoming in Flax 1.10.

**Comment by mafiesto4** [comment]
c94052513e6d2bcb62dc64512063cd7a8a6c9310 does another large network optimization by checking if replicated data didn't change. This should improve the scalability of the system. Now, Arizona Framework Sample shows around 5kB/s which seams way better than initial 36kB/s. More improvements to come (roadmap: https://trello.com/c/sAbapCCH/335-networking-roadmap).
