### ISSUE TITLE
[BUG] After moving actor camera follow and then trying to duplicate it, position stays locked

### ISSUE THREAD

**Issue by xxSeys1** [FlaxEngine/FlaxEngine#2816]
**Issue description:**

Title.

https://github.com/user-attachments/assets/ebf1d9da-9a27-47a5-9805-01bb2d1715e9

Even after letting go of Shift the weird snapping back to old position behavior stays.

**Steps to reproduce:**

1. Select Actor
2. Move it with Camera follow (Alt)
3. Try duplicating it (Shift)

**Minimal reproduction project:**

none

**Flax version:**

lastest launcher master

**Comment by mafiesto4** [comment]
Fixed in 6534136632a655e6a5fe15ca52b8fbb2f5ff9b43.
