### ISSUE TITLE
Problem accessing XmlElement

### ISSUE THREAD

**Issue by AlTheSlacker** [FlaxEngine/FlaxEngine#2818]
**Issue description:**
I can't seem to access XmlElement when using System.Xml Although this appears to be OK from Unity.

**Steps to reproduce:**
using FlaxEngine;
using System.Xml;
namespace Game;

public class xmlTest : Script
{
    public void TestMethod(XmlElement element){}
}

Appears OK in VSC, but Flax produces the error:
error CS1069: The type name 'XmlElement' could not be found in the namespace 'System.Xml'

**Flax version:**
1.8.2

**Comment by Tryibion** [comment]
You need to add the include into your Game.Build.cs file.

Example of what you need to add into the setup method in your Game.Build.cs file:
`options.ScriptingAPI.SystemReferences.Add("System.Xml");`

Flax only includes a limited number of namespaces by default within the standard c# libraries.

**Comment by AlTheSlacker** [comment]
Thanks for that, I tried:
Game.Build.cs

using Flax.Build;
using Flax.Build.NativeCpp;

public class Game : GameModule
{
    /// <inheritdoc />
    public override void Init()
    {
        base.Init();

        // C#-only scripting
        BuildNativeCode = false;
    }

    /// <inheritdoc />
    public override void Setup(BuildOptions options)
    {
        base.Setup(options);

        options.ScriptingAPI.IgnoreMissingDocumentationWarnings = true;
	options.ScriptingAPI.SystemReferences.Add("System.Xml");
		

        // Here you can modify the build options for your game module
        // To reference another module use: options.PublicDependencies.Add("Audio");
        // To add C++ define use: options.PublicDefinitions.Add("COMPILE_WITH_FLAX");
        // To learn more see scripting documentation.
    }
}

but still get:
error CS1069: The type name 'XmlElement' could not be found in the namespace 'System.Xml'. This type has been forwarded to assembly 'System.Xml.ReaderWriter, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' Consider adding a reference to that assembly.

But I am unsure how to change my reference or the type forwarding. Can you help?

**Comment by Tryibion** [comment]
Looks like it is telling you that you need this `options.ScriptingAPI.SystemReferences.Add("System.Xml.ReaderWriter");`

**Comment by AlTheSlacker** [comment]
That works, thanks so much for your help.
