### ISSUE TITLE
Attempting to access undefined scenes causes CTD

### ISSUE THREAD

**Issue by AlTheSlacker** [FlaxEngine/FlaxEngine#2822]
**Issue description:**
using Level.GetScene(1); when only a single scene (id = 0) exists causes a table error followed by a crash to desktop.

**Steps to reproduce:**
Actor emptyActor = New<Actor>();
emptyActor.Name = "test";
emptyActor.Parent = Level.GetScene(1);

**Flax version:**
1.8.2

**Comment by mafiesto4** [comment]
Yeah we should have soft-assertions that simply report error and return `null` in such case (favor `CHECK` instead of hard `ASSERT` macro).
