### ISSUE TITLE
Editor on Linux sometimes keeps dialogs open until an option is chosen

### ISSUE THREAD

**Issue by iizudev** [FlaxEngine/FlaxEngine#2823]
Sometimes, in the editor (Debug, Development, and Release) when you do anything that makes it open a popup menu, the 
menu may stay on the screen until an option is selected (more rarely it is even unclickable). Also there are visual glitches in the text of the menu options.

**Logs**: https://pastebin.com/ua00NLZ4

**Flax version:** 1.8 (a more exact version is in the logs)

[Recording of the bug (on YouTube)](https://youtu.be/x3w-DUtqbw4)

**Comment by GoaLitiuM** [comment]
The glitching looks similar caused by issues fixed in #2715, so that is probably already fixed in the upcoming versions (it's already in master branch).

**Comment by mafiesto4** [comment]
@iizudev You can try downloading the latest daily `master` build and see if it works fine now: https://github.com/FlaxEngine/FlaxEngine/actions/runs/10242543584

**Comment by iizudev** [comment]
> @iizudev You can try downloading the latest daily `master` build and see if it works fine now: https://github.com/FlaxEngine/FlaxEngine/actions/runs/10242543584

The issue is fixed
