### ISSUE TITLE
[Bug] Bindings generator: Missing conversion of .f [C++] to .0f [C#]

### ISSUE THREAD

**Issue by WolfInABowl** [FlaxEngine/FlaxEngine#2829]
**Issue description:**
The bindings generator doesn't convert the C++ syntax of `.f` to `.0f` when generating C# code. `.f` is valid syntax in C++ but invalid in C#, resulting in a compilation error.

**Steps to reproduce:**
1. Create a C++ script (in a project with `BuildNativeCode = true;` in its .Build.cs)
2. Add `API_FIELD() float Foo = 1.f;`  and compile the code.

**Flax version:**
1.8.2, August 6 2024 master

**Comment by mtszkarbowiak** [comment]
If this is being changed, maybe some bullet points from this list would get addressed?
https://github.com/FlaxEngine/FlaxEngine/issues/2237
