### ISSUE TITLE
Editing a procedural Static Model Entry via C# does nothing

### ISSUE THREAD

**Issue by alcoranpaul** [FlaxEngine/FlaxEngine#2835]
**Issue description:**

When creating a [procedural generated mesh](https://docs.flaxengine.com/manual/graphics/models/generate-model.html), then editing the Static Model entries: `StaticModel.Entries[0].ShadowMode` and `StaticModel.Entries[0].ReceiveDecals` does not change anything in run-time.

**Steps to reproduce:**
1. Follow the steps in creating a [procedural generated mesh](https://docs.flaxengine.com/manual/graphics/models/generate-model.html).
2. In the `OnStart` method, add the following below the `GetOrAddChild<StaticModel>()`: 
- `childModel.Entries[0].ShadowsMode = ShadowsCastingMode.None;`
- `childModel.Entries[0].ReceiveDecals = false;`

**Note**
I also had added this line `_model.MaterialSlots[0].ShadowsMode = ShadowsCastingMode.None;` below `_model = Content.CreateVirtualAsset<Model>();`

so this was **before** 
![image](https://github.com/user-attachments/assets/0051bb23-2c99-4d69-b89e-124c4d921acb)

**after**
![image](https://github.com/user-attachments/assets/b75aefce-24d5-4a2a-946d-e5915cff909d)

- You can still see that it receives shadows when though I have set them to not recieve

**Full code**
```csharp
public override void OnStart()
{
	// Create dynamic model with a single LOD with one mesh
	_model = Content.CreateVirtualAsset<Model>();
	Debug.Log($"Actor: {Actor.ID}");
	Debug.Log($"Mode: {_model.ID}");
	_model.SetupLODs(new[] { 1 });
	_model.MaterialSlots[0].ShadowsMode = ShadowsCastingMode.None;

	var colData = Content.CreateVirtualAsset<CollisionData>();
	Debug.Log($"CollisionData: {colData.ID}");
	UpdateMesh(_model.LODs[0].Meshes[0], colData);

	meshCollider = Actor.GetOrAddChild<MeshCollider>();
	Debug.Log($"MeshCollider: {meshCollider.ID}");
	meshCollider.CollisionData = colData;
	meshCollider.IsTrigger = true;
	meshCollider.TriggerEnter += OnTriggerEntered;
	meshCollider.TriggerExit += OnTriggerExit;

	// Create or reuse child model
	childModel = Actor.GetOrAddChild<StaticModel>();
	Debug.Log($"GEneerated model: {_model.ID}");
	childModel.Entries[0].ShadowsMode = ShadowsCastingMode.None;
	childModel.Entries[0].ReceiveDecals = false;
	childModel.Model = _model;
	childModel.LocalScale = new Float3(1);
	childModel.SetMaterial(0, Material);
}
```
**Flax version:**
Master `||` 1.8.2

**Comment by Tryibion** [comment]
It may be time to review how c# properties work. StaticModel.Entries is a property so it will return a copy of the Entries array. To change value you need to set StaticModel.Entries array once the value is changed. 

Example code:

var entries = StaticModel.Entries;
entries[0].ReceiveDecals = false;
StaticModel.Entries = entries;


I also don't recommend changing the models material slots though code as that will actually change values on the model asset which may cause confusion at some point if you have multiple of the same models in the game.
