### ISSUE TITLE
[BUG] Trying to view asset reference graph crashes the engine

### ISSUE THREAD

**Issue by xxSeys1** [FlaxEngine/FlaxEngine#2840]
**Issue description:**

When trying to view an assets reference graph (Right Click -> Show asset references graph) the editor crashes with the following popup:
![image](https://github.com/user-attachments/assets/a59bb525-31b1-4db7-89ae-a7fda30196bd)

This is the crash folder from the Logs:
[Crash_2024_08_08_22_04_18.zip](https://github.com/user-attachments/files/16552906/Crash_2024_08_08_22_04_18.zip)

**Steps to reproduce:**

1. Try to view an assets reference graph

**Minimal reproduction project:**

none

**Flax version:**

latest master launcher as of 8/8/2024 (not happening in 1.8.2)

**Comment by mafiesto4** [comment]
Fixed in 5a7080c9c070efc3efb17063a3b2193fa65e9915.
