### ISSUE TITLE
[UX/ BUG] Lerp output socket becomes hard to drag on when lerp is in Float/ Vector4 mode

### ISSUE THREAD

**Issue by xxSeys1** [FlaxEngine/FlaxEngine#2846]
**Issue description:**

![image](https://github.com/user-attachments/assets/0ded6af8-cff2-4d70-ad54-bb1085f11145)
*(it's hidden behind the 2 last components of the Float4 input)*

My suggestion would be to increase the width of the lerp node (maybe only if it's in Float/ Vector4 mode?) so that the output is not obstructed anymore.

**Steps to reproduce:**

1. Create a Vector/ Float4 (f.e. with pack Float/ Vector4)
2. Add a lerp node and pass the Vector/ Float 4 into the B input

**Minimal reproduction project:**

none

**Flax version:**

current master as of 8/10/2024

**Comment by mtszkarbowiak** [comment]
The issue is even more problematic when there are very small constants e.g. 0.00001. Then 2D vector (or sometimes even a scalar!) is completely invisible.
