### ISSUE TITLE
Ability to change property text color / style in the property window for both name and value

### ISSUE THREAD

**Issue by AlTheSlacker** [FlaxEngine/FlaxEngine#2847]
**Issue description:**
Feature request. I would like to be able to change the appearance of the text in the property window, particularly for script public fields names and values. For example if an editor change resulted in a field having a value other than the default, I would like the ability to change the white text to red for the value.

It would also be useful to have an editor onchanged event for script property fields.

**Comment by mtszkarbowiak** [comment]
In Flax world you can do it completely differently, with properties:

```CSharp

[NoSerialize, HideInEditor]
private FieldType _fieldName;

[Serialize, ShowInEditor]
public FieldType FieldName {
	get => _fieldName;
	set {
		_fieldName = value;
		OnFieldChanged();
	}
}

```

If necessary and your code and editor trigger different events you can go even further:

```CSharp
[NoSerialize, HideInEditor]
private FieldType _fieldName;

[Serialize, ShowInEditor]
private FieldType FieldName {
	get => _fieldName;
	set {
		_fieldName = value;
		OnFieldChangedByEditor();
	}
}

[NoSerialize, HideInEditor]
public FieldType FieldName {
	get => _fieldName;
	set {
		_fieldName = value;
		OnFieldChangedByCode();
	}
}

```

Specific point of serialization varies on your needs. Of course, if you have only a getter than it can't be a point of serialization.

**Comment by Tryibion** [comment]
It also sounds like the perfect use case for a custom editor <https://docs.flaxengine.com/manual/scripting/custom-editors/index.html>

**Comment by AlTheSlacker** [comment]
> In Flax world you can do it completely differently, with properties:
> 
> ```cs
> [NoSerialize, HideInEditor]
> private FieldType _fieldName;
> 
> [Serialize, ShowInEditor]
> public FieldType FieldName {
> 	get => _fieldName;
> 	set {
> 		_fieldName = value;
> 		OnFieldChanged();
> 	}
> }
> ```
I'm using this at the moment, but due to the large number of fields I was hoping for a simpler way.

**Comment by mtszkarbowiak** [comment]
Then custom editor it is.

**Comment by AlTheSlacker** [comment]
> It also sounds like the perfect use case for a custom editor https://docs.flaxengine.com/manual/scripting/custom-editors/index.html

Maybe for you guys, but I just spent several hours trying to figure out how to use it for my use case and have given up. What I want is for my properties to appear normal (white) in the property window if they are the default (empty constructor values) and green if not. But I need it to work for a large number of classes and properties (including lists) so I don't want to bespoke anything for one particular class or property name. I got as far as: 

`using FlaxEngine;
using FlaxEditor.CustomEditors;
using FlaxEditor.CustomEditors.Editors;
using System;
using System.Reflection;

[CustomEditor(typeof(Actor))]
public class MyScriptEditor : GenericEditor
{
    private object _defaultInstance;

    public override void Initialize(LayoutElementsContainer layout)
    {
        base.Initialize(layout);

        // Initialize default instance of the target type
        _defaultInstance = Activator.CreateInstance(Values[0].GetType());

        // Iterate through each property of the target object
        foreach (var property in Values[0].GetType().GetProperties(BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly))
        {
            if (property.CanRead && property.CanWrite)
            {
                // Get current value of the property
                var propertyValue = property.GetValue(Values[0]);
                // Get default value of the property
                var defaultValue = property.GetValue(_defaultInstance);

                // Determine if the value is the default
                bool isDefault = propertyValue.Equals(defaultValue);

                // Create a label with a custom message
                var propertyLabel = layout.Label(property.Name + (isDefault ? " (Default)" : " (Modified)"));
                propertyLabel.Label.TextColor = isDefault ? Color.Blue : Color.Yellow;


            }
        }
    }
}
`

testing on:
`using FlaxEngine;

[CustomEditor(typeof(MyScriptEditor))]
public class MyActor : Actor
{
    private int _MyColorProperty;

    public int MyColorProperty
    {
        get => _MyColorProperty;
        set {
            _MyColorProperty = value;
            // call something to update color
        }
    }

    public MyActor()
    {
        MyColorProperty = 1;
    }
}`


But could not figure a way to make the color replace the existing property label color instead of creating a new label. And using the get;set; approach I could not figure out how to call the customeditor to update.

**Comment by Tryibion** [comment]
Here is an example for a script:

Script:
```
public class MyTestScript : Script
{
    [DefaultValue("")]
    public string TestingString = "";

    [DefaultValue(1)]
    public int TestInt = 1;
}
```

Custom Editor that changes color when it is not the default value. Keep in mind that flax uses the `DefaultValue` attribute to register the default value.
```
[CustomEditor(typeof(MyTestScript)), DefaultEditor]
public class MyTestScriptEditor : GenericEditor
{
    
    public override void Initialize(LayoutElementsContainer layout)
    {
        base.Initialize(layout);
    }

    public override void Refresh()
    {
        base.Refresh();
        foreach (var editor in Layout.Editors)
        {
            foreach (var child in editor.ChildrenEditors)
            {
                if (child.CanRevertDefaultValue)
                {
                    child.LinkedLabel.TextColor = Color.Green;
                }
                else
                {
                    child.LinkedLabel.TextColor = FlaxEngine.GUI.Style.Current.Foreground;
                }
            }
        }
    }
}
```

**Comment by AlTheSlacker** [comment]
@Tryibion Thank you, that was incredibly helpful. I know it's all there in the source, but it would be great to see some more focus on documentation in the future.
