### ISSUE TITLE
[Proposal]  Exclude scripts from being stopped by Time.GamePaused

### ISSUE THREAD

**Issue by ThePhantomMask** [FlaxEngine/FlaxEngine#2864]
**Issue description:**
Personally I'd like a feature that allows a script to always remain active even when Time.GamePaused is true.
I thought of it as a small icon to the left of the script setting that you can choose between Default and Always.

**Steps to reproduce:**
None

**Minimal reproduction project:**
None

**Flax version:**
**1.8.2 & latest master**

**Comment by mafiesto4** [comment]
You can plug into `Scripting.Update` event to get updates no matter the scripting paused state.

**Comment by ThePhantomMask** [comment]
> You can plug into `Scripting.Update` event to get updates no matter the scripting paused state.

Is it possible to see an example of how to do this?

**Comment by ThePhantomMask** [comment]
> You can plug into `Scripting.Update` event to get updates no matter the scripting paused state.

Is it possible to see an example of how to do this?

**Comment by mafiesto4** [comment]
```cs
public class MyScript : FlaxEngine.Script
{
    /// <inheritdoc />
    public override void OnEnable()
    {
        Scripting.Update += Tick;
    }

    /// <inheritdoc />
    public override void OnDisable()
    {
        Scripting.Update -= Tick;
    }

    private void Tick()
    {
        Debug.Log("Time.GamePaused = " + Time.GamePaused);
    }
}
```
