### ISSUE TITLE
[Bug] AudioClip Assertion failed

### ISSUE THREAD

**Issue by Myterian** [FlaxEngine/FlaxEngine#2866]
**Issue description:**
One of my players had this error showing up almost every time he quit the game
![Tales_of_the_Cerulean_Sea_18_08_2024_22_11_08](https://github.com/user-attachments/assets/2b8b125b-7c72-49c1-aa4b-3f1da06b153a)

Quitting the game is done via `Engine.RequestExit`. You can't consistently reproduce it, but there are times when quitting a game will crash an assertion, so hopefully this can help getting rid of that.

**Comment by mafiesto4** [comment]
Fixed in 1c840539c65abfdace34b3055fb34e71cf3974f3.
