### ISSUE TITLE
Can't press "create project" button, Window dont fit to my desktop.

### ISSUE THREAD

**Issue by L928** [FlaxEngine/FlaxEngine#2874]
The "Create new project" window does not fit on my desktop, and I can't make it smaller.
Therefore, I cant't create a new project, since the important things like selecting a project path and the "Create Project" button are at the window bottom, which is beyond the boundaries of my monitor / desktop.

I suggest fixing this by allowing to change the window size.

I try to workaround it by trying the command line in the mean time.

Thank you for spending you valuable time on noticing my report.

I add a screenshot:

![image](https://github.com/user-attachments/assets/870b172b-07c5-4f71-97c0-720918b7a67f)

**Comment by mafiesto4** [comment]
Fixed for the next Launcher update (scheduled before 1.9 release)
