### ISSUE TITLE
Unable to add a script to Actor on Linux

### ISSUE THREAD

**Issue by lasonpeter** [FlaxEngine/FlaxEngine#2886]
**Issue description:**

While trying to add a script (Chunk.cs in this case) to any empty actor or a model actor, the editor gives a 
`[ 00:03:53.671 ]: [Error] Exception has been thrown during Window.OnDragDrop.
Object reference not set to an instance of an object.`
error occurs while using Linux after some time 
The log file is here:
[Log_2024_08_26_08_52_09.txt](https://github.com/user-attachments/files/16745284/Log_2024_08_26_08_52_09.txt)

**Steps to reproduce:**
Create empty Actor or Model Actor in scene and try to add a Script to it.

**Minimal reproduction project:**
[PlanetGeneration.zip](https://github.com/user-attachments/files/16745269/PlanetGeneration.zip)

**Flax version:**
Version: 1.8.6512.2

**Comment by Tryibion** [comment]
Your script `Chunk.cs` is missing an empty ctor so it can not be created via drag and drop onto an actor in the editor.

**Comment by Tryibion** [comment]
I would also suggest not using constructors in classes that inherit from `Script` and `Actor`. Instead use the scripting events (OnAwake, OnStart, etc.).
