### ISSUE TITLE
Pressing "Show generated shader code" button in particle emitter editor crashes the editor

### ISSUE THREAD

**Issue by xxSeys1** [FlaxEngine/FlaxEngine#2896]
**Issue description:**

![image](https://github.com/user-attachments/assets/699f58e4-523a-4809-bf36-0ce6ee0d5a24)
When pressing this button the editor crashes.

[Crash_2024_06_04_13_29_02.zip](https://github.com/user-attachments/files/16808197/Crash_2024_06_04_13_29_02.zip)

**Steps to reproduce:**

1. Create a Particle Emmiter
2. Choose one the templates
3. Press the button
4. 🧨

**Minimal reproduction project:**

none

**Flax version:**

latest master as of 8/30/2024
1.8.2

**Comment by mafiesto4** [comment]
Fixed in e7dc58c596941c56193acc4e4bbe534d773625f7.
