### ISSUE TITLE
[Crash] Editor crashes when switching tabs

### ISSUE THREAD

**Issue by xxSeys1** [FlaxEngine/FlaxEngine#2898]
**Issue description:**

Sometimes (haven't found a way to repro it yet at all) the editor crashes when switching to another tab that's docked in the main editor window.

I think this may happen when switching to a tab of an asset that has been open for a longer time but of which the tab I haven't used recently.

I now have this happen every time I tab back into the editor from vscode. The editor crashes when scripts have finished compiling. I think this may be the same issue as described here.

Had this happen maybe 5 times.

Also there does not seem to be a crash folder.

**Steps to reproduce:**

I don't know :(

**Minimal reproduction project:**

none

**Flax version:**

latest launcher master as of 8/30/2024
First noticed ~three days ago (~8/27/2024)

**Comment by mafiesto4** [comment]
Backported in 25aa5bee85bebfe934e01ce87e74386f37078714
