### ISSUE TITLE
Source code templates

### ISSUE THREAD

**Issue by mtszkarbowiak** [FlaxEngine/FlaxEngine#2906]
First issue is that new source code mixed both CRLF/LF and Tabs/Spaces. It would be beneficial it the engine allowed to select those in the settings.

The second is that for bigger project it would be beneficial to have ability to add custom templates (or at least have a template with no source code inside).

**Comment by Tryibion** [comment]
I added <https://github.com/FlaxEngine/FlaxEngine/pull/2907>. This make is relatively easy to add a script template, although there is still manual work involved.

You will need to create a new proxy, but you can override the `GetTemplatePath` method to point to the template that you create.
```
[ContentContextMenu("New/C#/My new template")]
public class TestingCSProxy : CSharpProxy 
{
    public override string Name => "My new template";
    protected override void GetTemplatePath(out string path)
    {
        path = "Path to your template";
    }
}
```

Then you will need to add the new proxy to the content database via an EditorPlugin.
