### ISSUE TITLE
[Proposal] A method similar to `Actor.GetChildren` & `Actor.GetChild<Type>()` for Gui Controls

### ISSUE THREAD

**Issue by xxSeys1** [FlaxEngine/FlaxEngine#2908]
**Issue description:**

I'm working on a debug console, for which I need some gui, so I spawn a prefab when a scene loads.

I needed a way to the textbox I use for the commands, so I tried 
```cs
UiCanvas.GetChild<TextBox>();
```
which won't work since `TextBox` is not an `Actor`.

I suggest adding a method to Gui nodes to get a child based on type. Similar to the current method for getting children on `Actor`.

**Steps to reproduce:**

see *Issue description*

**Minimal reproduction project:**

none

**Flax version:**

1.8.2
latest launcher master as of 9/3/2024

**Comment by WolfInABowl** [comment]
I think you can use
```cs
UiCanvas.GUI.GetChild<TextBox>();
```

**Comment by xxSeys1** [comment]
Thanks a lot!
