### ISSUE TITLE
[Suggestion] Material Window - Display Decal Blending Mode only when using Decal Domain

### ISSUE THREAD

**Issue by WolfInABowl** [FlaxEngine/FlaxEngine#2919]
The `Decal Blending Mode` parameter is always visible, even when the `Domain` is not set to `Decal`. This parameter could instead be shown in the `General` group.
Additionally, when the `Domain` _is_ set to decal, the `Shading Model` and `Blend Mode` parameters have no effect. It would make sense for these parameters to be hidden or at least locked.
With both of these changes, `Decal Blending Mode` would appear in place of `Blend Mode`, which would make more sense.
(There's an inconsistency with the terms Blend Mode and Blend*ing* Mode, but that's another nitpick)

**Comment by mafiesto4** [comment]
Fixed in ce23c2efafb46156a45067fcb8af5b0875dd0fea.
