### ISSUE TITLE
JSON asset which should apper in create menu must be marked with Attribute

### ISSUE THREAD

**Issue by honzapatCZ** [FlaxEngine/FlaxEngine#292]
Currently the menu is very cluttered, so few nice things:
- it should be necessity to mark classes you want here with some atttribute(currently it will use all classes in all assemblies)
- the attribute could support something like addToContextMenu, so instead of create file setting it could have entry in the New context menu/sub menus

**Comment by mafiesto4** [comment]
Assets ca use `ContentContextMenu` attribute to nicely inhect creation of them in the Content window. Example:
```cpp
[ContentContextMenu("New/My Game/Asset 1")]
public class MyAsset1
{
...
```

Docs: https://docs.flaxengine.com/manual/scripting/tutorials/custom-asset.html#asset-creation-utility

(there is similar feature for custom actor types: `ActorContextMenu`)
