### ISSUE TITLE
Rich Text Label

### ISSUE THREAD

**Issue by honzapatCZ** [FlaxEngine/FlaxEngine#293]
Formatting support to override text visuals at some parts like
"Iam <color=red>Red</color> and Iam <bold>Bold</bold> <size=55>Iam huge</size>"

**Note**: that I might look at this myself in my GameUI, which is currently in progress

**Comment by stefnotch** [comment]
[`RichTextBox`](https://github.com/FlaxEngine/FlaxEngine/blob/master/Source/Engine/UI/GUI/Common/RichTextBox.cs) has that sort of styling

**Comment by honzapatCZ** [comment]
> [`RichTextBox`](https://github.com/FlaxEngine/FlaxEngine/blob/master/Source/Engine/UI/GUI/Common/RichTextBox.cs) allows for that sort of styling.
Can it be set to Read only?

**Comment by stefnotch** [comment]
Yes, it inherits from `TextBox` which has a [`Readonly`](https://github.com/FlaxEngine/FlaxEngine/blob/c3e3e70f96413598e407a899a7c8c327cb6ab8b0/Source/Engine/UI/GUI/Common/TextBoxBase.cs#L177) property

**Comment by honzapatCZ** [comment]
> Yes, it inherits from `TextBox` which has a [`Readonly`](https://github.com/FlaxEngine/FlaxEngine/blob/c3e3e70f96413598e407a899a7c8c327cb6ab8b0/Source/Engine/UI/GUI/Common/TextBoxBase.cs#L177) property

Then why does Label exist/ why doesnt it have rich variant

**Comment by mafiesto4** [comment]
Ah yes. Docs: https://docs.flaxengine.com/manual/ui/controls/rich-text-box.html
