### ISSUE TITLE
[Regression] SkyBox Actor renders as black

### ISSUE THREAD

**Issue by WolfInABowl** [FlaxEngine/FlaxEngine#2943]
Using the latest master, after the 1.9 stuff was merged, the `SkyBox` Actor appears to be broken. It renders as completely black, no matter the `Cube Texture`, `Panoramic Texture`, or `Custom Material`.
A 1.8 project, with a working `SkyBox`, exhibits this issue when upgraded to the latest master.

OS: Windows 10, confirmed also present on Windows 11
GPU: Nvidia RTX 2080, confirmed also present on AMD RX 6700 XT
Version: Master as of Sept 24th (1.9)

**Comment by mafiesto4** [comment]
Thx for quick report. Fixed in 2ad9c7f4d5aa3215504cdb6702e4239f97c89697.
