### ISSUE TITLE
Spurious error message when importing obj models with C#

### ISSUE THREAD

**Issue by AlTheSlacker** [FlaxEngine/FlaxEngine#2965]
[Error] Missing file 'file name of actual file with .flax extension'
This [Error] is reported in the output log as a Red message, this is not related to previously reported Assimp translation messages [info].

When importing an obj file to use as an asset, the file name with the extension changed to .flax is reported as missing, although the import then completes successfully.

Edit:
Upon re-importing the model the error is not reported, but if the asset is deleted and then re-imported then the error is back. It appears that the import is checking for the asset before the import has completed.

**Steps to reproduce:**
Attached is a zip file containing a single C# class that adds an import button to the editor and a sample obj file, use the button to import the obj file.

**Flax version:**
1.8.2

[objtest.zip](https://github.com/user-attachments/files/17255776/objtest.zip)

**Comment by AlTheSlacker** [comment]
After further testing it has become apparent that model = Content.Load<Model>(path); is not waiting for the Load to complete, I suspect that perhaps the import translator is executed in a separate thread. Performance appears to be the same as model = Content.LoadAsync<Model>(path); This can be seen in the output log by adding a Debug.Log("complete"); after the load line, in the output log you will see "complete" followed by a number of import translator messages. This is a bit of a pain as there appears to be no trivial way to be sure when the asset is available.

**Comment by AlTheSlacker** [comment]
I have found the issue. The code I'm using is:

Editor.Instance.ContentImporting.Import(sourcePath, outputLocation, true, modelImportSettings);
model = Content.Load<Model>(flaxPath);
Debug.Log("model: " + model);

The problem is **not** Content.Load

The problem is caused by the threading of ContentImporting.Import that results in the import not completing in time to load the asset.  I've put the model = Content.Load<Model>(flaxPath); into its own async task with a fixed Task.Delay, but this is really bad for performance when loading many files to become assets. It would be extremely useful to have an option to run the import in the main thread. I plan to move to a loop test approach to try and improve my use case, but it's still rather ugly.

**Comment by AlTheSlacker** [comment]
Here's my horrible hack around it in case anyone else has this problem:

Task.Run(() => LoadModelWithCheckAsync(flaxPath));

private async Task LoadModelWithCheckAsync(string flaxPath, int maxWaitTimeMs = 10000, int checkIntervalMs = 500)
{
    int elapsed = 0;
    while (!File.Exists(flaxPath) && elapsed < maxWaitTimeMs)
    {
        await Task.Delay(checkIntervalMs);
        elapsed += checkIntervalMs;
    }
    
    if (File.Exists(flaxPath))
    {
        model = Content.Load<Model>(flaxPath);
    }
    else
    {
        Debug.Log("Can't find asset: " + flaxPath + ", asset not there or taking too long to load.");
    }
}

**Comment by mafiesto4** [comment]
@AlTheSlacker We create separate thread for Content Importing. You can use `Editor.Instance.ContentImporting.IsImporting` to check if import action is active instead of checking for file existence. There is also event `ImportingQueueEnd` to inform about queue processing end but it's called from that other thread so watch out for race conditions.
