### ISSUE TITLE
Global illumination giving weird results on my integrated graphic card

### ISSUE THREAD

**Issue by HydrogenC** [FlaxEngine/FlaxEngine#2981]
**Issue description:**
The whole scene looks weird after I enabled Global Illumination when I am running Flax on my integrated graphics card (Intel UHD Graphics). 
PS: I'm fully aware that Global Illumination is too heavy for an integrated graphics, but still, it shouldn't have behaved like that.  
DDGI disabled: 
![image](https://github.com/user-attachments/assets/710c822e-aba9-48ad-b57b-80dbfee3dfc1)
DDGI enabled: 
![image](https://github.com/user-attachments/assets/3e16d4c7-2c59-4528-b6c2-c61f060e5697)

Additional information:  
When I run Flax (Debug configuration) from Visual Studio with debugger attached, it gives the following error as soon as the scene appears in the editor.  
![image](https://github.com/user-attachments/assets/e9515e6c-773f-429e-a425-e531030f98ab)
![image](https://github.com/user-attachments/assets/5d60530f-187a-47f7-89dc-af361dc86f7c)

**Steps to reproduce:**
Run Flax on a integrated graphics card and open "Graphics Features Tour", then enable global illumination, mode "DDGI".  

**Minimal reproduction project:**

Graphics Features Tour

**Flax version:**

Can reproduce on 1.8 and 1.9-develop.

**Comment by mafiesto4** [comment]
You could try testing it on Low quality mode. Also, check if Global SDF and Global Surface Atlas debug views are working. Most likely a combination of not enough memory + driver issues.

**Comment by HydrogenC** [comment]
Yeah it's driver issues.
