### ISSUE TITLE
File -> Save All/Save Scenes will sometimes not save at all or thrown an exception

### ISSUE THREAD

**Issue by Davvex87** [FlaxEngine/FlaxEngine#2987]
**Issue description:**
Saving the scene may not really save to the scene file or will crash the editor entirely! 
When the engine does crash upon saving a scene, an assertion exception is thrown:
![image](https://github.com/user-attachments/assets/e435ab88-635e-447a-b05b-f3f6164535e4)
I do not know much about how the engine is made but its referencing a header file inside an F designated drive, designation which I do not have as a drive on my computer.

**Files:**
[Log File](https://drive.google.com/file/d/18K1LDy7-Pbq4uQmknbqxdBzMRK-9daaH/view?usp=sharing)
[Dump File](https://drive.google.com/file/d/1m1kIS-UIp36mjRvEk-vPfUQvi0D0WPNH/view?usp=sharing)

**Steps to reproduce:**
Simply create a new project, create a Scene object, open and fill it up with actors, attempt to save and exit, open the project back up and it may or may not have saved your changes made to the scene.

**Minimal reproduction project:**
The project that I've had this issue manifesting recently can be downloaded [here](https://drive.google.com/file/d/10YpTPy8Ome0fF00keLLNZ9dzCMCQEt3s/view?usp=sharing), with everything including cache and user specific settings.

**Flax version:**
1.8.2

**Other Info:**
- This issue happens on all of my machines (desktop and laptop**s**), all running Windows 11.
- I do have the default C++ building tools provided by VS2022 installed on every device.
- Saving and switching scenes within the project appears to make it save correctly, but with a higher chance of an exception being thrown, though that may just be a coincidence, take this information with a grain of salt.
- In the project that this issue has been manifesting recently I am using Git to develop with other people, but I doubt that is helping the issue to manifest as it happens with every project.
- Only scenes are not saving, everything else like project configuration, prefabs and other assets appear to save just fine.

**Comment by Davvex87** [comment]
It happened again, upon checking the Output Log window this was printed out:
![image](https://github.com/user-attachments/assets/cb49b4be-f113-4117-8225-d28d97cda793)

Strangely, newly added actors to the scene after the last save and prior this error vanished from the scene, however actors already present in the scene before saving with no success had all of their components/properties saved and showing correctly on the editor preview window but their physical values displayed on the properties window have not, for example - positions of meshes are in the spot that I moved them to but the origin point and coordinates say otherwise, its as if there was a pivot offset added.

Before:
![image](https://github.com/user-attachments/assets/b1c4f2e7-be55-4479-86bb-ba163c7ca41b)
After:
![image](https://github.com/user-attachments/assets/adad00a6-ee43-41c0-bdc8-c7b538b32547)

(This is a prefab)

**Comment by Davvex87** [comment]
Running out of storage disk can also cause the scene to not save and the editor will never tell that to the user unless if the output window is checked. But this issue is not caused by storage space insufficiency.

**Comment by mafiesto4** [comment]
Issue in the crash log was caused by incorrect code after Visual Script was deleted even tho it was still used. Fixed for 1.9 in 9f078a6e3ce7bd09da8280b42bbdecc4dd33d1ab.
