### ISSUE TITLE
I shouldn't require android ndk to open a scene.

### ISSUE THREAD

**Issue by jayrulez** [FlaxEngine/FlaxEngine#3]
**Issue description:**

Trying to open a scene fails if android ndk is not installed.
![image](https://user-images.githubusercontent.com/78807/102612508-cc656500-40fe-11eb-8f29-d351b455a93f.png)

**Steps to reproduce:**

Create a basic project on a system with no android sdk.

Try to open the default scene for editing.

**Minimal reproduction project:**

**Flax version:**

**Comment by mafiesto4** [comment]
Could you try reinstall? I pushed a fix just 10s ago.

**Comment by jayrulez** [comment]
Works now.

When creating a project, the launcher should allow selecting which version of flax to use to create the project as there seemed to be a mismatch when I tried that lead to this problem.
