### ISSUE TITLE
Controls position should be around pivot/center

### ISSUE THREAD

**Issue by honzapatCZ** [FlaxEngine/FlaxEngine#300]
It makes much more sense for the position to be:
Around center
or
Around pivot point

I know this might be a breaking feature, but its better to have it at this point than later

**Comment by mafiesto4** [comment]
Actually right now, controls don't have position nor size but just anchors and offsets. This makes it possible to perform any docking/anchoring of the control regarding the parent container (https://github.com/FlaxEngine/FlaxEngine/blob/master/Source/Engine/UI/GUI/Control.Bounds.cs#L299).

UI should display anchors, pivot point, and some handler for control bounds editing in the viewport.
