### ISSUE TITLE
Failure to export a Build of my project

### ISSUE THREAD

**Issue by ThePhantomMask** [FlaxEngine/FlaxEngine#3004]
**Issue description:**
When I try to export a build of my game, it fails by giving me two errors, I have tried opening another project that has already been created, but in that case it is actually exported.
[Log_2024_10_20_21_21_00.txt](https://github.com/user-attachments/files/17451811/Log_2024_10_20_21_21_00.txt)

**Steps to reproduce:**
1. Start the project on the editor
2. Go to Game Cooker.
3. Start exporting

**Minimal reproduction project:**
I put it on Google Drive because it exceeds the MB limit 
https://drive.google.com/file/d/1tMsJU4alsDYEUd1lK1abaQJefaqutId9/view?usp=sharing

**Flax version:**
master or 1.9 version

**Comment by mafiesto4** [comment]
Fixed in f62c77c35ce568a9ff87111dfc0b1e28ece60d0f
