### ISSUE TITLE
Property drawing order in inspector should respect order as in source + inheritance property order

### ISSUE THREAD

**Issue by honzapatCZ** [FlaxEngine/FlaxEngine#301]
This was talked over on discord, specially that its not easy
I know that but its a real problem
AND
Inheritance
If you inherit something, it makes sense that your new properties are drawn at the start/end else it gets put somewhere in between which is, atleast, unpractical.
If reflection provides incosistent results, which I doubt, could we like make own parser?

UPDATE:
Looks like MemberInfo.MetadataToken could be the way to go, gonna investigate that and possibly make a PR

**Comment by Evildea** [comment]
I second this. It's rather annoying having all your properties come in to the editor in alphabetical order.

**Comment by honzapatCZ** [comment]
> I second this. It's rather annoying having all your properties come in to the editor in alphabetical order.

Yep, please up the PR itself too

**Comment by honzapatCZ** [comment]
Btw @mafiesto4  looks like unity uses just plain GetMembers, without any sorting etc., you shouldn't rely on that, but its not mandatory
https://answers.unity.com/questions/822926/how-does-unity-sort-fields-in-the-order-of-their-d.html

**Comment by mafiesto4** [comment]
#792
