### ISSUE TITLE
Game cooker skips some assets

### ISSUE THREAD

**Issue by ZaPx64** [FlaxEngine/FlaxEngine#3013]
**Issue description:**
The game cooker skips packaging assets that are referenced through animation events only. The asset graph for those assets (in my case sound assets) shows no references too.

**Steps to reproduce:**
- Acquire a mesh with animation
- Add an animation event that plays a sound (e.g. [this one from the docs](https://docs.flaxengine.com/manual/animation/animation/anim-events.html?tabs=code-csharp))
- Import a sound asset and use it in the animation event
- The sound does not get exported and the cooked game produces a warning in the log

**Workaround**
- Add missing sounds or directories to additional asset folders in the build settings.

**Flax version:**
1.9

**Comment by mafiesto4** [comment]
Fixed in 9f9564895e158cf07bb9fcddc945a3939430c928.

**Comment by ZaPx64** [comment]
Thank you very much! 💪

**Comment by ZaPx64** [comment]
@mafiesto4 Thought this was gone, but the issue is still present in 1.11. My cooker cache was just fine. Workaround is limiting the editor process affinity to one single CPU.
Let me know if you need anything, many builds result in faulty assets in my project, so it's easy to replicate.
Flax 1.11

EDIT: Arg, wrong ticket. I was referring to this: https://github.com/FlaxEngine/FlaxEngine/issues/3515 - I think it should be fixed in 1.12, nvm then.
