### ISSUE TITLE
[Bug] Generate Script Project Files in Editor doesn't work

### ISSUE THREAD

**Issue by Myterian** [FlaxEngine/FlaxEngine#3018]
**Issue description:**
Pressing `Generate Script Project Files` will result in an error (see bottom of log). Project files aren't created, resulting in VSCode intellisense not working.

**Steps to reproduce:**
1. Download 1.9 or current master (24.10.24)
2. Also install Windows Target Platform
3. Try generate project files

**Minimal reproduction project:**
Basic

**Flax version:**
1.9.6605

[Log_2024_10_24_00_09_22.txt](https://github.com/user-attachments/files/17498724/Log_2024_10_24_00_09_22.txt)

**Comment by Myterian** [comment]
Is the fix in todays master build, that you get from launcher? If so, I got bad news

**Comment by mafiesto4** [comment]
Yeah it should be in todays master. Okay I'll check this issue again

**Comment by Myterian** [comment]
Tested todays (26.10) master, issue is still there, unfortunatly. [Log_2024_10_26_14_23_44.txt](https://github.com/user-attachments/files/17531013/Log_2024_10_26_14_23_44.txt)

Just to make sure, I downloaded 1.8.2 and ran `Generate Project Script Files`, it works with that version.
I attached both Build Logs from the `Intermediate` cache folder here:

[Log_1.8.txt](https://github.com/user-attachments/files/17531044/Log_1.8.txt)
[Log_1.9.txt](https://github.com/user-attachments/files/17531045/Log_1.9.txt)

Out of curiosity I skimmed thru the `Intermediate` cache folder. This is just some reaching and trying, maybe it help, probably doesn't. If you need something to hunt this but down, let me know

The differences here that I found:
 - In 1.9, only the `GameEditorTarget` folder is generated, in 1.8 there are four folders called `BuildScripts`, `GameEditorTarget` and `GameTarget` and `Unused`
 - BuilderRulesInfo.txt had a different number at top of file
 - In the folder `Intermediate > GameEditorTarget > Windows` there is one folder in 1.9 called `Development`, but in 1.8 there are three folders called `Debug`, `Development`, `Release`
 - In `Intermediate > BuildScripts` there is a folder called AnyCpu. I'm probably reaching a lot, the only time I've seen AnyCpu was in `Builder.Project.cs`. Maybe the recent update there has something to do with it? I've got an old cpu (2012), so i.e. it can't run the tracy profiler without custom recompile. Maybe a similar situation here?

**Comment by mafiesto4** [comment]
Maybe 4d1541aa1d0561839e751d8b36637843be2fdcea will fix it

**Comment by Myterian** [comment]
So, I went thru the [Continuous Deployment Builds](https://github.com/FlaxEngine/FlaxEngine/actions/workflows/cd.yml) to see if an older master version still works for me and what I found is that [1244](https://github.com/FlaxEngine/FlaxEngine/actions/runs/10987633952) is the last version without error. [1245](https://github.com/FlaxEngine/FlaxEngine/actions/runs/11006938758) is the first time I can't generate the solution file. Also, the error thrown looks different than in the newer logs, maybe that helps.
[Log_1245.txt](https://github.com/user-attachments/files/17547399/Log_1245.txt)

**Comment by mafiesto4** [comment]
I've added another blind fix in 04ac3160e4041a6053c03ed08447d1286e342385. If still not working then feel free to DM me or attach here that project you have - only `flaxproj` and `Build.cs` files you have (no need to attach other game scripts nor content).

**Comment by Myterian** [comment]
Hey, the error change from line `304` to `305` in `VisualStudioCodeProjectGenerator.cs`. Progress xD 
No, but here are the files you were asking [RPG-ErrorExport.zip](https://github.com/user-attachments/files/17555826/RPG-ErrorExport.zip)

**Comment by mafiesto4** [comment]
Okay now it was easy to track and fix: 4153024c21c2628805c3456b7541959427e955fd

**Comment by Myterian** [comment]
Hey, thanks. The fix works, no more error. There is a catch, tho, in that the solution file doesn't seem to be properly generated (as in it's missing all the csproj references). Do you have an idea about that, or is this something for a new issue?

**Comment by mafiesto4** [comment]
Well, `RPG.flaxproj` uses `GameTarget=GameTarget` which is missing in the `zip` you provided so it failes to generate project for it (but works fine for `Journal` plugin)

**Comment by Myterian** [comment]
Right, I may have deleted them from the zip. They're still in the project, tho, so that shouldn't be an issue. Do you mind having another look with the target files included?

**Comment by Myterian** [comment]
Thanks, I appreciate that. Let me know if you need something else
[RPG-WithTargetFiles.zip](https://github.com/user-attachments/files/17578364/RPG-WithTargetFiles.zip)

**Comment by Myterian** [comment]
So, I got it working, but more by coincidence then intention. I wanted to try large worlds and have installed visual studio community 2022, with desktop development c++ and .net desktop development workloads to make a custom compile of flax. But now version 1.9 release and 1.9 master from the launcher download is working again.

Is there maybe a new dependency or something, that one need to run flax?
Also, might be related to #3040

**Comment by mafiesto4** [comment]
I've got one issue related to this fixed here: 7f571a647f3b07be089c3a458f8797132827080b. Then all projects were generated and vscode configs too:

![image](https://github.com/user-attachments/assets/1cd75d7b-afd6-4bb6-8310-d87cd2e1bd7c)

**Comment by Myterian** [comment]
Awesome

**Comment by Myterian** [comment]
Man, I hate to bring bad news, but flax won't generate script files on it's own with the current update.

For some reaseon, it works perfectly fine, when Visual Studio 2022 is installed with Desktop Development C++ and it's Buildtools are installed. Only installed, doesn't need to be started or anything.
![Flaxrequirements](https://github.com/user-attachments/assets/fea2870c-92ab-4ffd-aa93-b3a3641544cc)

I'm just curious if this is expected or if this is something worth investigating?

**Comment by mafiesto4** [comment]
Could you post the latest log file?

**Comment by Myterian** [comment]
Of course
[Build Logs with VS installed.txt](https://github.com/user-attachments/files/17649532/Build.Logs.with.VS.installed.txt)
[Editor Logs with VS installed.txt](https://github.com/user-attachments/files/17649533/Editor.Logs.with.VS.installed.txt)

[Build Logs without VS.txt](https://github.com/user-attachments/files/17649579/Build.Logs.without.VS.txt)
[Editor Logs without VS.txt](https://github.com/user-attachments/files/17649580/Editor.Logs.without.VS.txt)
