### ISSUE TITLE
CanvasScaler behavior differs from Unity’s CanvasScaler when resizing game window

### ISSUE THREAD

**Issue by alcoranpaul** [FlaxEngine/FlaxEngine#3020]
### **Expectation**
I expected a **similar behavior** of the UI under Canvas Scalar to the behavior of UI in Unity's Canvas.

In Unity video below, you can see that I have set the `CanvasScaler` to `1920x1080` with matching to `Height`. And as I re-scale the game window, the UI under the Canvas Game Object gets smaller and is the same position throughout this process. So say if the UI is on the center it will stay on the center. As shown in the video below:

https://github.com/user-attachments/assets/614b26eb-ecd9-49fa-9a46-a0677495105c

### **Result**
In Flax engine, I tried to do a similar approach. I set the Canvas Scaler to `1920x1080` for the `Resolution Max` and set the `Resolution Mode` to `Vertical` or Height. As I resize the game window, the UI enlarges rather than shrinking down. As shown in the video below:

https://github.com/user-attachments/assets/d963804d-fb61-4274-8bd1-85988396997d

- I even tested it with the documentation in https://docs.flaxengine.com/manual/ui/controls/canvas-scaler.html but it yielded the same results. 
- I also tried to figure it out on the resolution scale but there was no info on it on the documentation and I wasn't sure on how to use it.

## **Steps to reproduce:**
1. Make `UICanvas` then add `CanvasScaler`
2. Set the `Resolution Max` to `1920x1080` and `Resolution Min` to`640x480`
3. Set `Resolution Mode` to `Vertica`l or `Shortest` side
4. Resize Game Window to shrink down

**Flax version:**
Master (10-23-2024 CDT) || 1.9.6605

**Comment by Tryibion** [comment]
Simplest way around this is to add a keyframe in the resolution curve and set it to 0,0 and then set the resolution min parameter to 1,1

**Comment by alcoranpaul** [comment]
That solution worked! Thanks!
It would be helpful if this became the default behavior for the CanvasScalar. Alternatively, adding it as an option or including it in the Manual would also be beneficial.
