### ISSUE TITLE
PhysicsColliderActor.ClosestPoint returning invalid vector if Large World is enabled

### ISSUE THREAD

**Issue by MrCapy0** [FlaxEngine/FlaxEngine#3023]
**Issue description:**

PhysicsColliderActor.ClosestPoint does not work with LargeWorld.

**Steps to reproduce:**

Use this script

```
public class MyScript : Script
{
    public Collider Coll;

    public override void OnUpdate()
    {
        Coll.ClosestPoint(Actor.Position, out var pos);
        Debug.Log(pos);
    }
}
```

1. Add the script to some object.
2. Add a collider on the scene and assign the collider to the script.
3. Check the Output log

Using large world:
![image](https://github.com/user-attachments/assets/b44f4de8-428e-4a3c-abef-414d95a672c7)

Without large world
![image](https://github.com/user-attachments/assets/fcdaeaa9-6e4c-49a7-86af-c9184ad1d322)

**Flax version:**
1.9 master

**Comment by mafiesto4** [comment]
Fixed in https://github.com/FlaxEngine/FlaxEngine/commit/ae4a4a8e571b4b7215336cc6789b4450213e321c.
