### ISSUE TITLE
UI Anchor drawer

### ISSUE THREAD

**Issue by MrCapy0** [FlaxEngine/FlaxEngine#3024]
**Issue description:**
Pls, add a visual indicator for UI control anchors like this.
![image](https://github.com/user-attachments/assets/547672ac-4d83-48f2-b392-1d8b2697b6b3)
![gif](https://docs.unity3d.com/Packages/com.unity.ugui@1.0/manual/images/UI_Anchored4.gif)

The unity UI anchor drawer allow to change the anchors positions too.

**Flax version:**
1.9 master

**Comment by Tryibion** [comment]
Duplicate #2575
