### ISSUE TITLE
strongly need feature : discard current scene changes (like unity)

### ISSUE THREAD

**Issue by jzq740176597** [FlaxEngine/FlaxEngine#3035]
**Issue description:**

beside the missing feature (see title), even I reload the current loaded scene (with unsaved changes) by dbl-click scene-asset in content window, It prompted "If you want to save the changes" => I choose "NO" Then **Nothing happens.** no reload action at all. 

So the situation now a little sucks.  **ONLY way** to restore the orig-state of the sceen is press UNDO over and over OR quit Then Reopen the engine.

**Steps to reproduce:**

**Flax version:**
1.9

**Comment by Tryibion** [comment]
This could be because of Auto save which will save the state every so often. you can disable auto save in the Editor Options.

**Comment by Tryibion** [comment]
Ah, I think i misread originally. as of right now, you are correct that the scene will not "reload" when clicking on the same scene asset. As a workaround you can unload the scene and then open it again for the same effect.

**Comment by jzq740176597** [comment]
Still, I really hope you guys CAN consider add a "discard changes" as a shortcut.  rather than steps: Located the scene-asset first & dbl-click it And face a "yes or no" dlg again ,too tedious I think.
