### ISSUE TITLE
feature Request: hope CAN SAVE & USE window-layout acrossing projects

### ISSUE THREAD

**Issue by jzq740176597** [FlaxEngine/FlaxEngine#3036]
I wander if it's appropriate to put the request here. So sorry if not. I just a 10-years unity-dev now going to migrate to flax.

**Flax version:**
1.9

**Comment by Tryibion** [comment]
Yep. go to Windows > Save window layout and you can have as many window layouts as you want and can switch between them with the context menu item below it. They will save across projects.
![image](https://github.com/user-attachments/assets/fd8c41f2-fefc-4861-894d-9a28cf8d63a1)

**Comment by jzq740176597** [comment]
Yes, I tried & i works like a charm. the doc missing lead me a little. Said The layout is pre-project manner, so silly. sorry for bother
