### ISSUE TITLE
Inconsistent serialization/deserialization of custom network objects

### ISSUE THREAD

**Issue by envision3d** [FlaxEngine/FlaxEngine#3042]
**Issue description:**
I'm creating my own custom tooling on top of the high level networking functionality, and ran into a problem with inconsistent serialization of custom objects.  It seems that data is serialized and/or deserialized in an inconsistent order with the code provided.

After some testing, I believe I've noticed a pattern that the serialization seems to be consistent and the problem lies more on the order of deserialization, but I'm not 100% sure on that.

**Steps to reproduce:**
1. Download test project
2. Cook and run multiple clients
3. Host on one, connect local on others
4. Repeat until "!!! Problem" is noticed in the log

**Minimal reproduction project:**
[networkissue.zip](https://github.com/user-attachments/files/17612085/networkissue.zip)

**Flax version:**
1.10 with custom code added to Object.cs:

```
/// <summary>
/// Initializes a new instance of the <see cref="Object"/>.
/// <param name="id">Id to assign to the object.</param>
/// </summary>
protected Object(Guid id)
{
    // Construct missing native object if managed objects gets created in managed world
    if (__unmanagedPtr == IntPtr.Zero)
    {
        Internal_ManagedInstanceCreated(this, FlaxEngine.Interop.NativeInterop.GetTypeHolder(GetType()).managedClassPointer);
        if (__unmanagedPtr == IntPtr.Zero)
            throw new Exception($"Failed to create native instance for object of type {GetType().FullName} (assembly: {GetType().Assembly.FullName}).");
    }

    __internalId = id;
}
```

**Comment by mafiesto4** [comment]
Okay so instead of using specific objectId for spawned object I added `NetworkReplicator.AddObjectIdMapping` method which can be used to link objects on connected peers so they will be properly synced. After this, the following code works fine:

```cs
public class DataPackage : FlaxEngine.Object, INetworkSerializable
{
    private Guid _myid; // cache custom network id of this object

...

    public DataPackage(string identifier, Guid guid, object defaultValue, Action<object> valueChangedHandler = null) 
        //: base(guide) // don't use this custom ctor
    {
        _myid = guide;
...
    }

    void OnDisconnected()
    {
        NetworkReplicator.RemoveObject(this);
    }

    public void AddToReplicator(FlaxEngine.Object parent = null)
    {
        Debug.Log($"[ReplicatedValue ({identifier}) ({currentValue.GetType()})] Adding data package to replicator: {ID})");

        NetworkReplicator.AddObject(this, parent);
        NetworkReplicator.AddObjectIdMapping(this, ref _myid); // <- added this
    }

...
}
```
