### ISSUE TITLE
Crash occurs when creating a Prefab then changing the Root component to a Canvas

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#305]
**Issue description:**
Crash occurs when creating a Prefab then changing the Root component to a Canvas, deleting the root, then saving.

**Steps to reproduce:**
1. Create a Prefab
2. Add a Gui Canvas
3. Press Save
4. Set the Canvas as the root
5. Delete the root
6. Press Save
7. Experience Crash

Please see this video of steps taken: https://drive.google.com/file/d/1WuzzkXjJIIVgh_h-6BT9AZP4wTjI2UAg/view?usp=sharing
Logs are here: [Log.txt](https://github.com/FlaxEngine/FlaxEngine/files/6089676/Log.txt)
No memory dump files were created.

**Flax version:**
Current Branch 1.1

**Comment by mafiesto4** [comment]
Fixed in 793bb502f55c82767cd4914c9a330aeb63c334e9 (and in some other commits in the past).
