### ISSUE TITLE
[BUG] When creating a new terrain, it no longer displays in the editor

### ISSUE THREAD

**Issue by xxSeys1** [FlaxEngine/FlaxEngine#3050]
**Issue description:**

When creating a new terrain, some default material used to be applied to it to make it visible in the editor.
However, that is no longer the case in the latest master version and probably also in 1.9.

Note that the material would not get set as the material in the inspector, it's just some temporary material to make the terrain visible in the editor.

New terrain in 1.8.2:
![image](https://github.com/user-attachments/assets/02b3a2b9-26f9-4792-a393-41eed5ee4c4c)
New terrain in latest master (ignore the skybox):
![image](https://github.com/user-attachments/assets/77046ad3-7e42-4292-8f36-603df2697f8a)

**Steps to reproduce:**

1. Create a new terrain in the toolbox, default settings work fine

**Minimal reproduction project:**

none

**Flax version:**

latest master 1.9.6605

**Comment by Tryibion** [comment]
@mafiesto4, not sure what changed, but the default terrain material needs to be changed to the `Terrain` domain and the shading model needs to be set to `Lit` for the default to work again. You can change them and push, or here is the changed file.
[DefaultTerrainMaterial.zip](https://github.com/user-attachments/files/17692832/DefaultTerrainMaterial.zip)

**Comment by mafiesto4** [comment]
My bad. Fixed in 2532a57b0b44720d61f79eae54957abc415c501d.
