### ISSUE TITLE
Curve evaluation via `Evaluate` returns a different value than what is visually shown

### ISSUE THREAD

**Issue by alcoranpaul** [FlaxEngine/FlaxEngine#3051]
**Issue description:**

By changing the **_tangent in and out_** to not equal 0, calling `Evaluate` would return a different value than what is shown visually in the editor.

**Steps to reproduce:**
Reference: https://docs.flaxengine.com/manual/scripting/advanced/curve.html
1. Create a script that has a BezierCurve<float> taken from the reference
    - `public BezierCurve<float> FloatCurve = new BezierCurve<float>(new BezierCurve<float>.Keyframe(0, 0), new BezierCurve<float>.Keyframe(1, 1));`
2. Add the following keyframes: Keyframe 1: (0,100,0,0), Keyframe 2: (4, 500, 171.9213, 0). Note that value, time, and # of keyframes is arbitrary.
    - ![image](https://github.com/user-attachments/assets/af3b841e-fa95-4f0a-8077-a1f8845d49d5)
    - Image above is what I see visually in the editor. You can note that
      - Time 0: 100
      - Time 1: Close to 100
      - Time 2: near 200
      - Time 3: slightly above 300
      - Time 4: 500

4. OnStart, loop through the last keyframe's time and Evaluate each time and print out the result. Or follow the code below

```csharp
public class testCurve : Script
{
	public BezierCurve<float> FloatCurve = new BezierCurve<float>(new BezierCurve<float>.Keyframe(0, 0), new BezierCurve<float>.Keyframe(1, 1));
	public override void OnStart()
	{
		for (int i = 0; i <= FloatCurve.Keyframes[1].Time; i++)
		{
			FloatCurve.Evaluate(out float result, i, false);
			Debug.Log($"Keyframe {i}: {result}");
		}
	}
}
```
**Case 1** is where the tangent in of the last keyframe is `171.9213`. This is the result of the information above!
```csharp
[ 00:19:48.695 ]: [Info] Keyframe 0: 100
[ 00:19:48.696 ]: [Info] Keyframe 1: 194.73524
[ 00:19:48.696 ]: [Info] Keyframe 2: 385.96063
[ 00:19:48.696 ]: [Info] Keyframe 3: 534.20575
[ 00:19:48.696 ]: [Info] Keyframe 4: 500
```

**Case 2** is where the tangent in of the last keyframe is `-151.69873`
  - ![image](https://github.com/user-attachments/assets/e1d153b7-eb71-411c-a673-c3f30934532d)
```csharp
[ 00:24:05.513 ]: [Info] Keyframe 0: 100
[ 00:24:05.513 ]: [Info] Keyframe 1: 134.05649
[ 00:24:05.514 ]: [Info] Keyframe 2: 224.15062
[ 00:24:05.514 ]: [Info] Keyframe 3: 352.16946
[ 00:24:05.514 ]: [Info] Keyframe 4: 500

```

And in the case where both tangent in and out is 0 for both keyframes. The evaluation of each time is the same visually;
  - ![image](https://github.com/user-attachments/assets/e946b8f3-79e9-4793-abcc-3d1698414e32)
  - ![image](https://github.com/user-attachments/assets/08c45b66-caef-4976-a908-2ce4d2617c70)

```csharp
[ 00:26:54.761 ]: [Info] Keyframe 0: 100
[ 00:26:54.761 ]: [Info] Keyframe 1: 162.5
[ 00:26:54.761 ]: [Info] Keyframe 2: 300
[ 00:26:54.761 ]: [Info] Keyframe 3: 437.5
[ 00:26:54.762 ]: [Info] Keyframe 4: 500
```

**Flax version:**
Master (Nov 11 2024 CDT) || 1.9.6605

**Comment by mafiesto4** [comment]
Fixed drawing in 57628c3d5f744fb1578fb340ef9f6d12367457b3. Also, curve editor got lots of quality improvements for usability.
