### ISSUE TITLE
[Suggestion] OnEnable event timing

### ISSUE THREAD

**Issue by Myterian** [FlaxEngine/FlaxEngine#3053]
**Issue description:**
I noticed the way the `OnEnable` event works is on an individual actors basis, so doing `OnAwake`, `OnStart` and then `OnEnable`, before moving to the next actor and so on. 

If one want to use `OnEnable` for registering events on- or referencing other actors, there can be a bad situation when the other actor is not initialized yet. Which results in an error thrown.

So, my suggestion is to invoke `OnEnable` event after the actors in all loaded scenes have been initialized (ie. after `OnStart`). This also aligns with the [docs better, where it say](https://docs.flaxengine.com/manual/scripting/events.html#initialization) 

> Then OnStart/OnEnable should be utilized for cross-object interactions (eg. register to a game manager, cache player scripts, etc.).

as it doesn't mention hierarchy dependency.

**Steps to reproduce:**

This is my current production case
1. Create a script with an event, that references an actor and a method on that actor and invokes that method in `OnEnable` 
2. Place the script on an actor that is above the referenced actor in the hierarchy (can be in other scene, too)
3. Run the game

Another case is
1. Create a script that sets a static actor property in `OnAwake` (in my case it's a reference to the main camera)
2. Create another script that fetches the reference to the static actor. Place this script on an actor in the hierarchy above the camera
3. Run the game

**Minimal reproduction project:**
Basic

**Flax version:**
1.9.6605

**Current "Workaround"**
is to go into the script that fetches the reference to an actor and use `Scripting.InvokeOnUpdate` to set the references on the first update, when everything is initialized.

**Comment by Tryibion** [comment]
I think the only issue implementing this would be performance having to loop through all of the scripts in a scene multiple times.

**Comment by mafiesto4** [comment]
Well, engine invokes `OnAwake` after all actors and scripts are deserialized, then there is another initialization phrase with `OnEnable`/`OnStart` so you can split init logic for those static actors to setup in `OnAwake` and handle cross-object inetractions in `OnEnable`.

Feel free to attach a sample script that would express the issue you;'re talking about.

**Comment by Myterian** [comment]
[EventTiming.zip](https://github.com/user-attachments/files/17804197/EventTiming.zip)
 I set up a sample project, so I don't need to write a whole paragraph. The gist in this scenario is that one script registers a static reference to an actor in one scene and an actor in another scene tries to access it. The scripts itself are pretty simple

**Comment by mafiesto4** [comment]
Ah okay so the problem here is you mess with cross-level references. I would use GamePlugin for this as it would be easy to mess when one level is loaded an another not (eg. during streaming). If both actors are in the same level then it works fine.
