### ISSUE TITLE
ContainerControl.Raycast keeps hitting UI that has its UICanvas on World Space Canvas Mode

### ISSUE THREAD

**Issue by alcoranpaul** [FlaxEngine/FlaxEngine#3054]
**Issue description:**

I have set a UICanvas' Render mode to `World Space Face Camera` via Editor. I wanted to test if my mouse is over a UI using Flax's documentation in https://docs.flaxengine.com/manual/ui/tutorials/raycast-ui.html
Upon starting the game, it seems that `ContainterControl.Raycast` is hitting my `World Space Face Camera` UI regardless of position.

**Expectation**
I expected that `ContainerControl.Raycast` would not hit the UI that is in `World Space` and would only hit `Screen Space` UI.

**Use case**
I am using World Space Face Camera UI for my Health Bar for my units in my game. It would not be ideal if I keep hitting the Health bar when I don't intend to interact with it or check if my mouse if over it. Since it is not intended for the Player to interact with the Health bar.

**Steps to reproduce:**
1. Create a `UICanvas` in Scene window.
2. Set its Render Mode to `World Space Face Camera`. Optional (enable Ignore Depth)
3. Set some arbitrary UIControl as children in the `Canvas Scaler`. In my case, I added a `ProgressBar` child.
4. In `Canvas Scaler`, I set Width and Height to zero and set its bounds and pivot to the center and disable Clip and cull Children.
5. Add/Attach a script in the ProgressBar or in any Actor that has the following
```csharp
	public override void OnUpdate()
	{
		var ui = RootControl.GameRoot;
		var pos = Input.MousePosition;
		if (ui.RayCast(ref pos, out var hit))
		{
			Debug.Log("UI hit over: " + hit.GetType().Name
			);
		}
	}
```

**My Resuls**

https://github.com/user-attachments/assets/664ca1ef-a8c6-438b-97f9-d1ffebce320d

---
##### UPDATE
I have a workaround. On the Editor if I want a UI to be `WorldSpaceFaceCamera`, I set it in the editor.
- Then I attach a script to the CanvasUI. 
- `OnAwake`, I set the CavnasUi `Rendermode` to `ScreenSpace` and then` OnEnable`/`OnStart` I set it to` WorldSpaceFaceCamera`.

This would mean that I need to have a scrip attach to every UICanvas or have a reference to them in a class to set them to `ScreenSpace` then `WorldSpaceFaceCamera`

**Flax version:**
Master || 1.9.6605

**Comment by alcoranpaul** [comment]
another ui that is hitting is Panel UI.
Setup is that Panel UI is a child of UICanvas, with mode Screen Space.
Excluding the Top Left where it doesnt hit it.


https://github.com/user-attachments/assets/a863a4ea-d198-49ad-8a05-920b0b58a83e

**Comment by Tryibion** [comment]
For world space UI, I got it working this this

```
public override void OnUpdate()
{
     var ui = Actor.As<UICanvas>().GUI;
     var pos = ui.PointFromScreen(Input.MouseScreenPosition);
     if (ui.RayCast(ref pos, out var hit))
     {
         Debug.Log("UI hit over: " + hit.GetType().Name);
     }
}
```

**Comment by alcoranpaul** [comment]
> For world space UI, I got it working well with this code. I cant seem to replicate the raycast always hitting the world space ui... but you can always use the canvas gui to start the raycast to make sure it is only hitting what you actually want it to hit.
> 
> ```
> public override void OnUpdate()
> {
>      var ui = Actor.As<UICanvas>().GUI;
>      var pos = ui.PointFromScreen(Input.MouseScreenPosition);
>      if (ui.RayCast(ref pos, out var hit))
>      {
>          Debug.Log("UI hit over: " + hit.GetType().Name);
>      }
> }
> ```

This one solves my particular problem. Specifying on which Canvas to know if the mouse hits something is a good solution!

My suggestion then is to put this in the docs since this wasn't clear for me that you can specify which Canvas to raycast from
