### ISSUE TITLE
UI Issue (Green Border is not displaying correctly)

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#306]
**Issue description:**
![image](https://user-images.githubusercontent.com/35228400/110112306-ac903400-7e05-11eb-887d-dc9528e20b85.png)

UI Green Border doesn't display correctly in World Space. See the video here: https://drive.google.com/file/d/1HvQkqnpJhXwbJycyflNadAYXTnpL3_2s/view?usp=sharing

**Flax version:**
Branch 1.1

**Comment by jb-perrier** [comment]
Yeah that's because the green border just work for screen space, it has to be implemented for world space/camera space.

**Comment by mafiesto4** [comment]
I'm sure we should tackle this when working on UI editing tools with gizmos/handles and handle 3D UI too. Good suggestion.

**Comment by mafiesto4** [comment]
Fixed after recent UI Editor refactor.
