### ISSUE TITLE
Add more script template options

### ISSUE THREAD

**Issue by MrCapy0** [FlaxEngine/FlaxEngine#3061]
**Issue description:**

Pls, add more cm options like create custom json asset or editor window
![image](https://github.com/user-attachments/assets/215a1369-ef32-402c-aa89-47ea52b4fcff)

**Flax version:**
1.9 master

**Comment by xxSeys1** [comment]
Also one for for an interface

**Comment by Tryibion** [comment]
I did write docs for how to create your own script templates <https://docs.flaxengine.com/manual/scripting/advanced/templates.html>

**Comment by xxSeys1** [comment]
That's nice, however I think some more commonly used templates should come with the engine by default

**Comment by Tryibion** [comment]
Added in #3073
