### ISSUE TITLE
Additive scenes in editor

### ISSUE THREAD

**Issue by ptcsoderlund** [FlaxEngine/FlaxEngine#3068]
**Issue description:**
I am using a scene as gameinstance scene.
From there i will do additive scene loading depending on gameinstance state.
When i have gameinstance scene open in editor i can drag a subscene additively into editor (main menu scene for example).
But I cannot remove scenes from editor.

**Steps to reproduce:**
Create two scenes and drag & drop them into editor scene (window->scene).
Right click and try to "delete" any scene.
Not working.

**Flax version:**
1.9

**Comment by Tryibion** [comment]
It is a little hidden, but if you right click on the scene in the scene tree window, then there is an unload scene option. You may have to scroll down in the context menu if it is not showing.

**Comment by ptcsoderlund** [comment]
> It is a little hidden, but if you right click on the scene in the scene tree window, then there is an unload scene option. You may have to scroll down in the context menu if it is not showing.

Ahh, yes. I had to scroll, got ui scale on.
So it´s by design that "delete" is not supposed to remove scenes?

**Comment by Tryibion** [comment]
Correct, delete should not do anything on a scene in the scene tree.

**Comment by Tryibion** [comment]
I submitted this PR <https://github.com/FlaxEngine/FlaxEngine/pull/3070> which disables those options which should not be used.
