### ISSUE TITLE
Deleting a UI Control, such as a label, doesn't automatically update the Prefab viewer.

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#307]
**Issue description:**
Deleting a UI Control, such as a label, doesn't automatically update the Prefab viewer. The user has to close the prefab viewer and then reopen it.
![image](https://user-images.githubusercontent.com/35228400/110118761-f5001f80-7e0e-11eb-9a8a-2a0bb6e8b3c8.png)

**Steps to reproduce:**
Please see this video to see the issue in action:
https://drive.google.com/file/d/1ul1miD8ClkoEXXgtoE9XfuoY1cqEN3l-/view?usp=sharing

**Flax version:**
Branch 1.1

**Comment by mafiesto4** [comment]
Fixed in e6d3242670f1f49791b12d25f0ee44e36c5abe0e.
