### ISSUE TITLE
[Bug] It's not possible assign a input event on InputEvent in editor.

### ISSUE THREAD

**Issue by MrCapy0** [FlaxEngine/FlaxEngine#3075]
**Issue description:**

I can't assign the shot event.

https://github.com/user-attachments/assets/a38eadae-cbca-4b3e-ae8f-032bcbd43297

**Minimal reproduction project:**

```
public InputAxis Axis;
public InputEvent ShotEvent;
```

**Flax version:**
1.9 master with large world enabled.

**Comment by MrCapy0** [comment]
Oh, i was missing the `new InputEvent()`

**Comment by mtszkarbowiak** [comment]
@MrCapy0 Not sure if you noticed that, but `InputEvent` is `IDisposable`
