### ISSUE TITLE
Ticking Auto Width on a Label changes the justification from Centered to Left Aligned

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#308]
**Issue description:**
Ticking Auto Width on a Label changes the justification from Centered to Left Aligned:
![image](https://user-images.githubusercontent.com/35228400/110121627-bd937200-7e12-11eb-9964-4bb0ea6b7827.png)
![image](https://user-images.githubusercontent.com/35228400/110121764-e7e52f80-7e12-11eb-9c96-5319cfb9dc4c.png)

**Flax version:**
Branch 1.1

**Comment by mafiesto4** [comment]
It disables the justification to properly calculate and draw text with auto-layout which works fine for single-lines but in this case, for multi-line text it should do more processing for proper placement.

**Comment by mafiesto4** [comment]
Fixed by 160dfa5dc7a0bd24a325e95c607ea9e079f2ee91.
