### ISSUE TITLE
Show highlight when select an actor by editor property

### ISSUE THREAD

**Issue by MrCapy0** [FlaxEngine/FlaxEngine#3091]
Unity adds a highlight when i click on a gameObject property on editor. This help a lot to find actors on scene tree.

I think this is a good feature to add in flax

![image](https://github.com/user-attachments/assets/2c15ba3c-d4a4-4d60-baee-d2ed040e6f42)

**Flax version:**
1.10 master

**Comment by xxSeys1** [comment]
I've got something working where when you click on the actor in the field, it selects it in the scene tree.

I can also try to add only highlighting, but idk if I can successfully implement that.

Is selecting only okay as well?

**Comment by MrCapy0** [comment]
@xxSeys1 Maybe one click show the highlight and double click select the actor. But the selection with double click was already implemented, no?

**Comment by xxSeys1** [comment]
Ur right, lemme try to get the highlight thing working

**Comment by xxSeys1** [comment]
Does Unity have some animations (like the color changing slightly or the box shrinking/ expanding)?

**Comment by MrCapy0** [comment]
@xxSeys1 
[2024-12-07 15-45-24.webm](https://github.com/user-attachments/assets/8e467c57-2042-4012-a791-1e2892ee99d9)
