### ISSUE TITLE
Request: Recorder tool

### ISSUE THREAD

**Issue by MrCapy0** [FlaxEngine/FlaxEngine#3095]
**Issue description:**
Currently there is no a way to create nice movies, trailers or render cinematics.

Unity have a Recorder tool that allow render gameplays or cinematics in diferent resolutions (very usefull if i want to make my game trailer in 4K even i not have a highend machine).

Pls, consider this feature, i know that it's hard to do, but will increase a lot Flax games quality.

https://docs.unity3d.com/Packages/com.unity.recorder@2.5/manual/RecordingRecorderWindow.html

**Flax version:**
1.10 master

**Comment by mafiesto4** [comment]
Scene Animation window contains rendering utility for high-res trailers recording with offline method:

https://docs.flaxengine.com/manual/animation/scene-animations/scene-animation.html#rendering-animation

**Comment by MrCapy0** [comment]
Thanks @mafiesto4. I think this will help me for now, but i think this issue can be reopened to add the feature on future as  low priority. 

A recorder tool is important yet because this can create video files more easily and record the audio too (important if i'm making a gameplay).
