### ISSUE TITLE
Scene breaking bug when using Polish characters in labels.

### ISSUE THREAD

**Issue by michalzembron** [FlaxEngine/FlaxEngine#310]
**Issue description:**
When I type text using Polish characters into a Label component, and then run a scene, the editor freezes. Only way to fix it after start is to kill the Editor process via task manager, relaunch project and delete broken scene.

**Steps to reproduce:**
1. Create simple scene with UICanvas and UIControl of Label type.
2. Write for example "ŁŁŁŁ" into Text box.
3. Start game
![1](https://user-images.githubusercontent.com/59204659/110215359-a489d000-7ea9-11eb-808e-4f3126a374dc.jpg)
![2](https://user-images.githubusercontent.com/59204659/110215363-a94e8400-7ea9-11eb-8b03-52cec806bb40.jpg)
![3](https://user-images.githubusercontent.com/59204659/110215367-ae133800-7ea9-11eb-9e85-5980eb045e7f.jpg)

**Minimal reproduction project:**
Simple scene with UICanvas and UIControl of Label type.

**Flax version:**
1.0

**Comment by michalzembron** [comment]
Same thing happens when using custom font that supports Polish language.

**Comment by mafiesto4** [comment]
o kurde!

**Comment by mafiesto4** [comment]
Fixed.
