### ISSUE TITLE
[Issue] Cannot add UI Control in a Prefab/Widget

### ISSUE THREAD

**Issue by alcoranpaul** [FlaxEngine/FlaxEngine#3100]
**Issue description:**
I wanted to make a Health Bar in `World Space Canvas` but when adding a UI Control as a child of UI Canvas that was made as a Prefab/Widget, it will not add.

**Steps to reproduce:**
1. In content window, RMB then click on Widget
2. Set `initialization mode` to Canvas
3. RMB `UICanvas` then add Control, see to it that error/warning will be thrown

**Log**
[Log_2024_12_11_23_50_15.txt](https://github.com/user-attachments/files/18106170/Log_2024_12_11_23_50_15.txt)

**Videos**

Creating a Widget

https://github.com/user-attachments/assets/dc58ced4-2cb0-4c3a-96ab-61e1ffb0fa86

Creating Prefab with World Space Canvas

https://github.com/user-attachments/assets/9c32b959-eee1-4c26-9d6e-ee4d5a29ec19

**Flax version:**

Master || 1.9.6606

**Comment by xxSeys1** [comment]
Had that same problem yesterday, can confirm this happens.
