### ISSUE TITLE
Crash on flying around the scene

### ISSUE THREAD

**Issue by TheStripyCat** [FlaxEngine/FlaxEngine#3106]
**Issue description:**

Crash while "flying" around the scene using WASDQE buttons. It showed an error message about arrays.
![Screenshot 2024-12-13 174127](https://github.com/user-attachments/assets/d02cd7fb-e680-4d40-bcef-7930ecaf7fb2)

[Log.txt](https://github.com/user-attachments/files/18127909/Log.txt)

**Steps to reproduce:**

The problematic area is around Y -1800 global position,  child Lights of actor Floor26. If I tried flying around the same height as those lights the engine crashed. My GI and SDF setting were on high. I lowered them to medium and couldn't easily reproduce the crash.

**Minimal reproduction project:**

[VTMGameJam.zip](https://github.com/user-attachments/files/18127898/VTMGameJam.zip)

**Flax version:**
latest master

**Comment by xxSeys1** [comment]
@mafiesto4 Can u look into this (when u have the time ofc)?

[Someone on the discord is saying they are getting this crash quite frequently](https://discord.com/channels/437989205315158016/538664104856911883/1317625365539061911) whilst in the middle of a game jam.

**Comment by mafiesto4** [comment]
Should be fixed in fa8f50ead13f1653c699f230c3aa935b389fa41a.
