### ISSUE TITLE
UIControl Local Location

### ISSUE THREAD

**Issue by honzapatCZ** [FlaxEngine/FlaxEngine#311]
In conjunction with #309 and #299
It would be nice to have Local Location for UIControl
This location would be based around the anchor point, so for example when anchored in the middle and the position being also in middle, the ui could show X: 0, Y 0, when anchored in center but dragged somewhere else, it could be -50, 50(somewhere left and top)
This could also make group moving of controls easier.

**Comment by Evildea** [comment]
Yeah, I agree. This is probably the most logical way of doing things. Have an anchor point then a local location that scales according to screen size.

**Comment by honzapatCZ** [comment]
> Yeah, I agree. This is probably the most logical way of doing things. Have an anchor point then a local location that scales according to screen size.

No to screen size but parent size basically subtract paren.size*anchor if they are the same if not its technically not needed but it could like take the minanchor

**Comment by Evildea** [comment]
This is what I'm thinking. A setup similar to how UE4 does it. This is very intuitive. 
![image](https://user-images.githubusercontent.com/35228400/110224866-dc3d5a00-7f33-11eb-99a5-e7224df70a22.png)

**Comment by honzapatCZ** [comment]
@mafiesto4  what do you think

**Comment by mafiesto4** [comment]
Added with #417

**Comment by honzapatCZ** [comment]
Hey a month later I solved my own issue, great

**Comment by honzapatCZ** [comment]
Good job @honzapatCZ 
Thank you @honzapatCZ
