### ISSUE TITLE
UI Issue - Issue with Manual and Automatic Line Breaks

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#315]
**Issue description:**
Automatically line breaks generated by a final spaces can clash with manually set line breaks.
Which results in the following issue:
![image](https://user-images.githubusercontent.com/35228400/110257990-7664d700-7ff4-11eb-82ee-181ddd048df4.png)

They also don't take manual line breaks into account when generating automatic breaks.
![image](https://user-images.githubusercontent.com/35228400/110258053-cfcd0600-7ff4-11eb-9e7e-25a66e044a60.png)

**Steps to reproduce:**
Just create this setup.

**Flax version:**
Branch 1.1

**Comment by mafiesto4** [comment]
It might be fixed after recent improvements to Label as I cannot reproduce it now. In case of the issue still being active pls send this prefab to checkout (without other resources, just prefab asset).

**Comment by Evildea** [comment]
I'll close for now and reopen if need be
