### ISSUE TITLE
Minor Issue - Rename Popup

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#317]
**Issue description:**
I went to rename an object and the rename popup spawn across to the opposite screen. Not a real issue but thought you all should be aware.
![image](https://user-images.githubusercontent.com/35228400/110271626-855f7f80-801c-11eb-8dd9-403a8465115c.png)

**Flax version:**
Branch 1.1

**Comment by mafiesto4** [comment]
Fixed in 759dc98737fab5cd29d58d68b2933311b00459b7
