### ISSUE TITLE
Uninitalised Lists cause crashes if accessed during runtime

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#318]
**Issue description:**
The following code will cause the editor to crash when accessed during a game:

```
List<Actor> MyList; // I forget to add '= new List<Actor>()'
MyList.Add(RandomActor);
```

Due to the fact that I'm used to working with C++, I sometimes forget to add the 'new List<Actor>()' part and this can cause the editor to crash if I try to access that list during runtime. Probably need some type of check in place to warn the user with a red error that they are trying to access an unitialised list. Alternatively, instead of crashing the editor this should kill the Game with a message telling the player why it was killed.

**Flax version:**
Branch 1.1

**Comment by mafiesto4** [comment]
The only thing I get with this code is an exception in C# that is handled with error log:
```
[Warning] Exception has been thrown during . Object reference not set to an instance of an object.
Stack strace:
  at Game.AIMovementScript.OnFixedUpdate () [0x0000f] in MyScript.cs:40 
  at (wrapper native-to-managed)
[Warning] Exception has been thrown during .
Object reference not set to an instance of an object
```

**Comment by mafiesto4** [comment]
Maybe it was specific to a particular method in Script/Actor? Like `OnEnable` or in the constructor?

**Comment by Evildea** [comment]
I'll close this for now as I can't remember exactly in what class or function it happened. When I happens again next time I'll create a ticket that covers that specific case.
