### ISSUE TITLE
Scene serialization bug

### ISSUE THREAD

**Issue by honzapatCZ** [FlaxEngine/FlaxEngine#319]
**Issue description:**
If you create like proxied property to some private variable, field is private and marked Serialize, property is public marked NoSerialize, everything saves fine with just this, but once you inherit this class, the inherited class wont get properly saved

**Steps to reproduce:**
Go into the scene assign something to both Parent actor and Child script actor, save and relaod scene/look into the scene file
Parent got saved, child did not

**Minimal reproduction project:**
https://github.com/honzapatCZ/Flax-Ser-Bug

**Comment by honzapatCZ** [comment]
Ok its an issue with private members
so the thing is, if its private but specifically marked as Serialize shouldn't it still work? or like atleas throw some warning that it's not a good idea to do in the first place

**Comment by mafiesto4** [comment]
After testing this, it looks like a limitation (or design) of C# `Type.GetFields` that doesn't return `private` fields from inherited classes. This could be solved manually at performance cost but for now I would just make it a limitation of the serialization, specified here:  https://github.com/FlaxEngine/FlaxDocs/commit/7c8af3c5a31e3c81f04d9218ae6d8e9e3c89a0fc.
Also, that warning (in Editor-only) would be a good idea.

**Comment by honzapatCZ** [comment]
What would be the performance cost? I really think such forgotten inherited field could realy be mind breaking bug, especially given as a non marked field is private by default.

**Comment by mafiesto4** [comment]
The cost of calling `Type.GetFields` for each inherited class and iterating over those lists to find any missing inherited private fields/properties. If that's a common problem we could try to solve it but I'm afraid that in most cases current state is fine and performance should be favored.

**Comment by honzapatCZ** [comment]
Could in that case the mono runtime override default behaviour for unmarked fields? Ie that they begave as protected by default?

**Comment by mafiesto4** [comment]
It looks like the default design in C# to not return those private fields from base classes (https://docs.microsoft.com/en-us/dotnet/api/system.type.getfields?view=net-6.0):

![image](https://user-images.githubusercontent.com/3464853/181789060-9acc01f4-ee9b-4e75-91c1-cad8bd1368f7.png)

Changing the default access specifier is not a good idea and actually would require some C# compiler hacks I guess.

**Comment by honzapatCZ** [comment]
Well Unity does it somehow, but Iam starting to think they are using some completely different reflection system.

Ill see if we can hack around the reflection system to expose private ones too.

**Comment by honzapatCZ** [comment]
Seems like this limit is built into mono
https://github.com/mono/mono/blob/5d2e3bc3b3c8184d35b2f7801e88d96470d367c4/mono/metadata/icall.c
