### ISSUE TITLE
Editor Strings can't handle Unicode Characters

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#320]
**Issue description:**
The Text Renderer Supports Unicode:
![image](https://user-images.githubusercontent.com/35228400/110419174-e8b8e280-80ec-11eb-9fa8-b2a60b621556.png)

However, if I try to add some Unicode characters such as, "ĉ, ĝ, ĥ, ĵ, ŝ" from Esperanto to a public string in the editor and assign them to the Text Render, then the field changes from this:
![image](https://user-images.githubusercontent.com/35228400/110420045-97a9ee00-80ee-11eb-8e6b-9e1fe3db50f7.png)

To this:
![image](https://user-images.githubusercontent.com/35228400/110420209-fc654880-80ee-11eb-9258-d2a3c0fb50f7.png)

Finally, if you do the same thing through C# it works fine:
```
string text = "ĉ, ĝ, ĥ, ĵ, ŝ";
Actor.As<TextRender>().Text = text;
```
![image](https://user-images.githubusercontent.com/35228400/110420624-c96f8480-80ef-11eb-86c2-0a2552369d07.png)

Final Note. This also applies to a List in the Editor.
`public List<string>`

**Flax version:**
Branch 1.1

**Comment by mafiesto4** [comment]
The problem was not related to Editor per se but to the C++ -> C# serialization wrapping part so basically C# deserialization from Json was not encoding UTF-8 characters property. Now it's fixed.
