### ISSUE TITLE
It's impossible to rotate the Text Render with the Gizmos

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#321]
**Issue description:**
It's impossible to rotate the Text Render with the Gizmos. The Text Render just doesn't rotate.
![image](https://user-images.githubusercontent.com/35228400/110420832-4ac71700-80f0-11eb-9040-e80a99a58eb3.png)

**Steps to reproduce:**
1. Add a Text Render to the Scene.
2. Try to rotate it using the Gizmos.

**Flax version:**
Branch 1.1

**Comment by nicolasmanz** [comment]
It seems that the blue axis has some kind of weird constraints. The rest work fine at least on my end.

**Comment by Evildea** [comment]
Weird, all the axis had this issue for me. Strange that for you it was only the blue.

**Comment by mafiesto4** [comment]
Fixed recently when doing Gizmos improvements for 1.1
