### ISSUE TITLE
Scaling Z-axis of Text Render scales the X-axis

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#322]
**Issue description:**
Scaling the Z-axis of the Text Render with the Gizmo, actually starts to scale the X-axis a little.
![image](https://user-images.githubusercontent.com/35228400/110421068-d640a800-80f0-11eb-9de6-5083e8f6c526.png)

Also, the Text Render and the Sprite Render probably should hide the Z-axis of Gizmo as it is useless for these objects.

**Steps to reproduce:**
1. Add a Text Render
2. Try scale the Z-axis and watch what happens to the X-axis.

**Flax version:**
Branch 1.1

**Comment by mafiesto4** [comment]
Fixed in 7ff5ebb45da81d4ff0669123ddcdd967b923b8c4
