### ISSUE TITLE
Scaling Gizmo is unintuitive.

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#323]
**Issue description:**
There appears to be something really off with the scaling Gizmo. In the video when I scale up, I then change my mind in an attempt to scale down, but it appears I'm locked into scaling in only one direction. 
I feel that this is quite unintuitive, at least for me.

Please see the video below to understand what I mean.
https://user-images.githubusercontent.com/35228400/110421962-95499300-80f2-11eb-8222-c50a6bb54087.mp4

**Flax version:**
Branch 1.1

**Comment by W2Wizard** [comment]
Yeah I also think that the way how the gizmo works currently, including rotation and translation is very janky and a bit annoying to use.

**Comment by W2Wizard** [comment]
#200 Caused this issue because now delta will always be positive:
https://github.com/FlaxEngine/FlaxEngine/blob/d67282680896f72c0ebfe83fbb6c93de68afd22f/Source/Editor/Gizmo/TransformGizmoBase.cs#L302-L323

**Comment by mafiesto4** [comment]
Fixed in 7ff5ebb45da81d4ff0669123ddcdd967b923b8c4
