### ISSUE TITLE
UI Bug: Can't add a Panel or Container to a Vertical Panel

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#325]
**Issue description:**
I have the following structure. The "ERROR" is the control I'm trying to set to a Container or Panel but everytime I do it just teleports me back up to the base.
![image](https://user-images.githubusercontent.com/35228400/110549904-df7c5400-8186-11eb-9a42-c64c7cef3973.png)

**Steps to reproduce:**
To see the issue in action, watch this video. In the video I'm trying to add another container or panel to the Vertical Panel but it never works. There are no errors generated.
https://user-images.githubusercontent.com/35228400/110549993-05a1f400-8187-11eb-9aad-99eba5cdab49.mp4

**Flax version:**
Branch 1.1

**Comment by Evildea** [comment]
I have the newest updates of Branch 1.1. So perhaps your test doesn't mimic mine perfectly?

**Comment by LCRW** [comment]
1.1 has been merged to master, and no longer exists

**Comment by LCRW** [comment]
that is weird, something happened with that specific control, but if i remove it and add a fresh one it works as expected.

**Comment by Evildea** [comment]
The problem is, that this issue pops up a a lot for me. Controls just break and then I'm forced to destroy them completely. Sometimes it happens to multiple controls at once. Which as you can imagine becomes very annoying.

**Comment by LCRW** [comment]
well the error is related to anchors, my stack trace when adding that prefab
`[ 01:32:08.162 ]: [Warning] Inner exception. Object reference not set to an instance of an object.
Stack strace:
  at FlaxEngine.GUI.Control.get_AnchorMin () [0x00000] in C:\Users\Watso\source\repos\FlaxEngine\Source\Engine\UI\GUI\Control.Bounds.cs:36 
`

**Comment by mafiesto4** [comment]
Fixed in abe635ad9b2cc0bd8156386848ff3f2141ba7916. Also, I think it fixed many other hidden issues in Custom Editor where sometimes it was sending exceptions under the hood and it was super hard to track why. Thanks for reporting this. Especially with this sample prefab that reproduced this issue. Very helpful 💯
