### ISSUE TITLE
UI Issue: Turning off and then on the IsActive of the UICanvas messes up the Vertical Panel

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#326]
**Issue description:**
Turning off and then on the **IsActive** of the **UICanvas** messes up the **Vertical Panel**:

Before Turning off:
![image](https://user-images.githubusercontent.com/35228400/110554470-f9ba3000-818e-11eb-9eeb-3545579d0862.png)
After Turning back on:
![image](https://user-images.githubusercontent.com/35228400/110554538-1eaea300-818f-11eb-9a57-58ef0c4c0a99.png)

Further exploration shows that this bug can be avoided by turning off "Auto Size" for the Vertical Panel. Therefore, the issue is probably related to autosizing. I would explore the source and try fix the issue myself but I'm working on a tight deadline to get this prototype done.

**Flax version:**
Master Branch

**Comment by mafiesto4** [comment]
Fixed by https://github.com/FlaxEngine/FlaxEngine/commit/845da14e6aabd6641dbd0fce5e137ae885996dd4.
