### ISSUE TITLE
Sending a space to a Text Render will cause the Editor to crash

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#327]
**Issue description:**
Using the following code causes the Editor to crash:

```
private TextRender Dialogue;
Dialogue.Text = " ";
```

The error message:
![image](https://user-images.githubusercontent.com/35228400/110566905-c7b3c880-81a4-11eb-8269-c006dc4a70a2.png)

**Flax version:**
Master Branch

**Comment by mafiesto4** [comment]
Fixed in https://github.com/FlaxEngine/FlaxEngine/commit/544a043c5623e4d7b1d0951ee05922f23159f50d
