### ISSUE TITLE
Unable to focus on spline point

### ISSUE THREAD

**Issue by W2Wizard** [FlaxEngine/FlaxEngine#328]
**Issue description:**
You can't focus on each individual spline point when having a point selected and pressing F, just lerps to 0.

**Steps to reproduce:**
1. Create a spline
2. Add some points
3. Select one and press F
4. Fail

**Flax version:**
Current master branch / 1.1

https://user-images.githubusercontent.com/63303990/110697242-5e57a800-81ec-11eb-910c-7106103476df.mp4

**Comment by mafiesto4** [comment]
Fixed in https://github.com/FlaxEngine/FlaxEngine/commit/4ae3fccfd9c2c8550b60a7a1861471f4d5deca73.
