### ISSUE TITLE
UI Bug: Green Box not affected by Margins

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#329]
**Issue description:**
You can see the issue here:
![image](https://user-images.githubusercontent.com/35228400/110709129-d6a38500-824f-11eb-9f07-2429d4a1d953.png)

**Steps to reproduce:**
Simply create a label using the settings I have provided.

**Flax version:**
Master Branch

**Comment by mafiesto4** [comment]
That's because the green box shows the control area, not the text bounds for the label. In this case, the margins are making the text go outside but don't change the control bounds.
