### ISSUE TITLE
Cannot Import Blender Model

### ISSUE THREAD

**Issue by TimMHunter** [FlaxEngine/FlaxEngine#33]
**Issue description:**
Tried to import a Blender model to the engine. The dialog disappears after selecting "Import" but the model doesn't appear in the engine for use.

Video: https://youtu.be/f-ioTsAjq5k

**Steps to reproduce:**
1. Select the Import function.
2. Select a Blender file.
3. Using the default settings, hit the Import button.

**Minimal reproduction project:**
Used the default starting template.

**Flax version:**
1.0

**Comment by jb-perrier** [comment]
Can you post your logs ?

**Comment by TimMHunter** [comment]
> Can you post your logs ?

[ 00:00:24.979 ]: [Info] Importing file 'D:\3D Models/Grass 1.blend' to 'C:\Users/theti/Documents/Flax Projects/Testing/Content/Models/Grass 1.flax'...
[ 00:00:24.980 ]: [Info] Importing model from 'D:\3D Models/Grass 1.blend'
[ 00:00:25.029 ]: [Info] Assimp 4.1.1750033687
[ 00:00:25.030 ]: [Info] [Assimp]: Info,  T4692: Load D:\3D Models/Grass 1.blend 
[ 00:00:25.032 ]: [Info] [Assimp]: Info,  T4692: Found a matching importer for this file format: Blender 3D Importer  http://www.blender3d.org. 
[ 00:00:25.032 ]: [Info] [Assimp]: Info,  T4692: Import root directory is 'D:\3D Models\' 
[ 00:00:25.032 ]: [Info] [Assimp]: Info,  T4692: BLEND: Blender version is 2.80 (64bit: true, little endian: true) 
[ 00:00:25.042 ]: [Info] [Assimp]: Info,  T4692: (Stats) Fields read: 12, pointers resolved: 1, cache hits: 0, cached objects: 1 
[ 00:00:25.043 ]: [Info] [Assimp]: Error, T4692: BLEND: Expected at least one object with no parent 
[ 00:00:25.043 ]: [Warning] BLEND: Expected at least one object with no parent
[ 00:00:25.043 ]: [Warning] D:\3D Models/Grass 1.blend
[ 00:00:25.043 ]: [Warning] 27728527
[ 00:00:25.043 ]: [Error] Cannot import model file. BLEND: Expected at least one object with no parent
[ 00:00:25.043 ]: [Error] Cannot import file 'D:\3D Models/Grass 1.blend'! Result: Error
[ 00:00:25.044 ]: [Warning] Failed to import D:\3D Models/Grass 1.blend to C:\Users/theti/Documents/Flax Projects/Testing/Content/Models\Grass 1.flax

**Comment by jb-perrier** [comment]
Looks like it's an issue with assimp : https://github.com/assimp/assimp/issues/3316
I don't think we can do more until they fix it.

You probably should trying using the FBX format.

**Comment by mafiesto4** [comment]
Importing blender files seems to be working now properly. In case of a specific file issue please open a separate ticket with that invalid file uploaded. Otherwise, I would recommend using FBX file format as it's industry standard and is very well supported in Flax.
