### ISSUE TITLE
UI Bug: Prefab Viewer and Game don't always match up

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#330]
**Issue description:**
This happens a lot. Things take on one position in the Prefab but have a totally different in the game. Sometimes closing Flax Editor and reopening resolves the issue, but not always.

To fix this issue, I have to manually delete the UI Prefab in the scene and re-drag it in. There seems to be an issue with UI Prefabs where changes aren't always updated.
![image](https://user-images.githubusercontent.com/35228400/110710279-b248a800-8251-11eb-8ccc-160e29150fa6.png)

**Steps to reproduce:**
There are no specific steps I can give.

**Flax version:**
Master Branch

**Comment by mafiesto4** [comment]
Yeah the UI preview in Prefab editor window needs more love to make it more stable and usable.

**Comment by mafiesto4** [comment]
Fixed in v1.2 (prefabs changes sync and apply refactor).
