### ISSUE TITLE
UI Bug: SceneTree Context menu + Scrollbar bugs

### ISSUE THREAD

**Issue by W2Wizard** [FlaxEngine/FlaxEngine#332]
**Issue description:**
There are 3 separate issues regarding the context menu:

### 1: Scrollbar overlaps items in panel
Initially I tried to fix this issue by checking if the scrollbar was visible and then adjusting the margin so it won't cover the arrows.
![image](https://user-images.githubusercontent.com/63303990/110772999-88e14980-825c-11eb-815d-d0b7c40aed45.png)

### 2: Scrollbar not null and marked as visible even when not
This lead me to finding out that even if there is NO scrollbar the value is not null and the properties `Enabled` & `Visible` keep returning true for the scrollbar, even if its is not there.
![image](https://user-images.githubusercontent.com/63303990/110773119-b0d0ad00-825c-11eb-8b5a-bfee3e6c335d.png)

### 3: Context Menu fails to update correctly
And during me trying to fix my initial issue I noticed that the context menu just fails to update correctly when rightclicking on different actors. However selecting any option will result in the new actor being added to the correct actor it was meant to go to for instance.

https://user-images.githubusercontent.com/63303990/110773773-6439a180-825d-11eb-9689-348901f5f386.mp4

**Steps to reproduce:**
Issue 1 & 2 are reproducible by checking the context menu and checking for the scrollbar in:
https://github.com/FlaxEngine/FlaxEngine/blob/d67282680896f72c0ebfe83fbb6c93de68afd22f/Source/Editor/Windows/SceneTreeWindow.ContextMenu.cs#L22-L28

Issue 3 is just right clicking and things here and there and notice the issue.

**Flax version:**
Master branch

**Comment by mafiesto4** [comment]
Those scroll bar issues were fixed in the latest `master`.
