### ISSUE TITLE
Game crash after changing window mode to fullscreen from code

### ISSUE THREAD

**Issue by michalzembron** [FlaxEngine/FlaxEngine#333]
**Issue description:**
Whenever I'm changing window mode by "Screen.IsFullscreen = true;" game crashes. I tried switching from dx11 to dx12 and the same thing happens (GTX 1050 notebook). Also I tried to force launch the game with dedicated graphics, but It didnt help at all and I checked this on another machine with GTX 1660 Ti.
![dx11](https://user-images.githubusercontent.com/59204659/110787790-14afa180-826e-11eb-9065-32ed3f024065.png)
![dx12](https://user-images.githubusercontent.com/59204659/110788028-5dfff100-826e-11eb-949a-87c236cacc14.png)

**Steps to reproduce:**
1. Create a scene with script attached to any component.
2. In OnStart write "Screen.IsFullscreen = true;".
3. Run Game Cooker and build the game.
4. Run the game and wait for crash.

**Minimal reproduction project:**
Any project with a basic scene.

**Flax version:**
1.0

**Comment by Evildea** [comment]
I just tested this on my computer and also got the same error message:
![image](https://user-images.githubusercontent.com/35228400/110789935-887c9900-82c4-11eb-88e0-83a18983b691.png)

I'm using:
- DirextX 12
- Nividia GeForce GTX 1060

**Comment by jb-perrier** [comment]
Should be solved by #336 . Keep us updated !
