### ISSUE TITLE
Broken dropDown when items are added through code or in the editor

### ISSUE THREAD

**Issue by michalzembron** [FlaxEngine/FlaxEngine#334]
**Issue description:**
When a few items are added to dropDown, they are not displayed properly.
![dropDownBug](https://user-images.githubusercontent.com/59204659/110799292-4ed37000-827b-11eb-9e0a-643e6514954a.png)

**Steps to reproduce:**
1. Create basic scene with dropDown.
2. Add items (in editor or in code, It doesn't matter).
3. Start the game and click on drop down.

**Flax version:**
1.0

**Comment by michalzembron** [comment]
So just fyi, Dropdowns are still completely broken in Flax 1.1 🙁

**Comment by mafiesto4** [comment]
Fixed by 6001eb88fa47deac9ed1cb447122d79b6f5df1e2
