### ISSUE TITLE
Exception Access Violation crash when trying to export project to Windows

### ISSUE THREAD

**Issue by colludium** [FlaxEngine/FlaxEngine#337]
**Issue description:**
I am unable to export any project to Windows build. The editor crashes with:

![image](https://user-images.githubusercontent.com/2897225/110909010-7d972800-8307-11eb-8e8a-4ce2f93fabc7.png)

Here is the crash dump:

[Logs.zip](https://github.com/FlaxEngine/FlaxEngine/files/6128372/Logs.zip)

**Steps to reproduce:**
Load an example project and then try to build it.

**Minimal reproduction project:**
Example projects will suffice.

**Flax version:**
1.0

**Comment by mafiesto4** [comment]
Thanks for the report! This one is hard to solve. I'm unable to reproduce it and stack trace from crashdump doesn't say anything useful but will keep digging.

![image](https://user-images.githubusercontent.com/3464853/111080416-ac2b2380-84fe-11eb-8359-92fb5abb5ede.png)

**Comment by colludium** [comment]
Thanks! I've tried uninstalling and reinstalling a couple of times but no change. I guess it could be something very odd about my system that's causing the problem (W10, Lenovo laptop, nothing amazing hardware or software wise). I'll update if I can.
