### ISSUE TITLE
Game Cooker broken for Windows (Branch 1.1)

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#338]
**Issue description:**
This commit has broken the Windows Game Cooker.
![image](https://user-images.githubusercontent.com/35228400/111027510-d8826980-8444-11eb-849c-7e25d4111a6a.png)
Suspect this line:
![image](https://user-images.githubusercontent.com/35228400/111027531-f223b100-8444-11eb-89f1-0f0e5c56b0db.png)
Games cooked using this commit result in the following (not lack of .exe):
![image](https://user-images.githubusercontent.com/35228400/111027550-0a93cb80-8445-11eb-9abe-82078aa95438.png)

Games cooked using the commit prior to this one result in the following:
![image](https://user-images.githubusercontent.com/35228400/111027563-1d0e0500-8445-11eb-9081-10b695fa7a5c.png)

**Flax version:**
Branch 1.1

**Comment by mafiesto4** [comment]
Does it fix the problem:
https://github.com/FlaxEngine/FlaxEngine/commit/82a00399264f79f9c8f35e6222558a252c958641
?

**Comment by Evildea** [comment]
Yeap, this fixed the issue
