### ISSUE TITLE
I can't generate Terrain Maps

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#344]
**Issue description:**
I'm unable to generate a terrain map when I press on the "Create New Terrain" button:
![image](https://user-images.githubusercontent.com/35228400/111248238-a0a23e80-865d-11eb-87b4-1b6b91f3bde9.png)

Please see the error log:
[Log_2021_03_16_13_42_53.txt](https://github.com/FlaxEngine/FlaxEngine/files/6145714/Log_2021_03_16_13_42_53.txt)

**Steps to reproduce:**
Use Branch 1.1 and press on "Create New Terrain"

**Flax version:**
Branch 1.1

**Comment by mafiesto4** [comment]
It was related to recent Dpi improvements. The problem was with calculating UI layout before the window was shown. Fixed here: .
