### ISSUE TITLE
UI: Container Background Color is throwing an error

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#345]
Can't change the background color after setting it once:
![image](https://user-images.githubusercontent.com/35228400/111254224-b10be680-8668-11eb-91a0-4bd51471d98b.png)

You can see the issue here when I try to set the Background Color:
https://user-images.githubusercontent.com/35228400/111254206-a94c4200-8668-11eb-9454-de7a41b2531d.mp4

Log:
[Log_2021_03_16_14_59_38.txt](https://github.com/FlaxEngine/FlaxEngine/files/6146011/Log_2021_03_16_14_59_38.txt)

**Flax version:**
Branch 1.1

**Comment by mafiesto4** [comment]
It was related to recent Dpi improvements. The problem was with calculating UI layout before the window was shown. Fixed here: https://github.com/FlaxEngine/FlaxEngine/commit/691df4cb8075c26ebbab33b192310a5090c68499.
