### ISSUE TITLE
UI Bug: Prefab seems to have different order to game

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#346]
**Issue description:**
The game seems to operate on a different order to the prefab.
![image](https://user-images.githubusercontent.com/35228400/111306867-dde1ed00-86ac-11eb-9498-3cd725b017d9.png)

Here is my prefab:
[SpellBook1.zip](https://github.com/FlaxEngine/FlaxEngine/files/6148806/SpellBook1.zip)

**Flax version:**
Branch 1.1

**Comment by mafiesto4** [comment]
Fixed by 878fee505f08c9ee4e0d5b1c9831c17a8c9d562b and a479f1daf62983cedbedabb2049643ad0918c455.
