### ISSUE TITLE
GamePlugin initialization order/Level.SceneLoaded event

### ISSUE THREAD

**Issue by honzapatCZ** [FlaxEngine/FlaxEngine#349]
In my plugin I subscribe to Level.SceneLoaded (and ofcourse unsubscribe in Deintinitialize) the problem is the action is invoked when play ends and scene is refreshed for the editor and thats not good
(+ it doesnt get triggered when I subscibe in onInitialize so I need to trigger it manually but thats no big deal)

**Comment by mafiesto4** [comment]
Fixed in 3e3b0e795156b2c6a01dcd1bc956a04ca90446c7
