### ISSUE TITLE
Per Monitor DPI Awareness

### ISSUE THREAD

**Issue by stefnotch** [FlaxEngine/FlaxEngine#35]
**Issue description:**
Flax is currently DPI aware, however, it is possible that different monitors have a different DPI.

To properly and reasonably elegantly implement [this](https://docs.microsoft.com/en-us/archive/msdn-magazine/2014/february/windows-with-c-write-high-dpi-apps-for-windows-8-1), I suppose that we'll need a DPI scale property for each window. And the C++ side has to take care of correctly updating it.

**Steps to reproduce:**
You need Windows 10 and two monitors
1. Change the scaling on both monitors
2. Open Flax
3. Move the window from one monitor to the other
4. Maximize the window

**Flax version:**
Flax 1.0

**Comment by jb-perrier** [comment]
I think it's the way it need to be handled, for now using flax on multiple monitor with different res/dpi scale is sometimes very frustrating.
