### ISSUE TITLE
UI Bug: Prefab Viewer doesn't update IsActive feature correctly

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#350]
**Issue description:**
Prefab Viewer doesn't update the IsActive feature properly when reopening a Prefab. 
Please see the attached video:
https://user-images.githubusercontent.com/35228400/111395994-3dbeaf00-8712-11eb-821c-867075e77db1.mp4

Here is my Prefab for testing purposes:
[SpellBookPrefab.zip](https://github.com/FlaxEngine/FlaxEngine/files/6152900/SpellBookPrefab.zip)

**Flax version:**
Branch 1.1

**Comment by mafiesto4** [comment]
Seams to be fixed while fixing previous issues here: df497bf68426cc7e4ab35252fabed417310b4e38 + 675bb93fd503384dc78f25ec1e6fa88685b80c79 + f194004ebfa73cc73da01f58504fb50c692bbd95
