### ISSUE TITLE
Prefab Bug: Making Changes to a prefab doesn't affect other Prefabs it is included in

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#351]
**Issue description:**
![image](https://user-images.githubusercontent.com/35228400/111397056-7c556900-8714-11eb-9fef-b991c097a69c.png)

I have a Prefab called Player that contains another Prefab called Spellbook.
I made changes to the Spellbook (i.e. I renamed it and added more to its hierarchy). These changes don't seem to have updated in the Player Prefab.

Here is my Player Prefab and my Spell Book Prefab for testing:
[Prefabs.zip](https://github.com/FlaxEngine/FlaxEngine/files/6152935/Prefabs.zip)

**Flax version:**
Branch 1.1

**Comment by mafiesto4** [comment]
It should be fixed now as objects are properly created and destroyed in nested prefabs. Now time for #357...
