### ISSUE TITLE
UI Issue: Can't make a Horizontal Panels have a different Transform to what it has been assigned automatically

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#353]
**Issue description:**
I have two Horizontal Panels that are both sitting under separate Vertical Panels. The way I've set it up is that they should perfectly overlay so I can turn one off and the other on during gameplay. The problem is I can't perfectly line then up because the two panels have adopted very slightly different Transforms and I can't overright them.

To see the issue, watch this video:
https://user-images.githubusercontent.com/35228400/111399175-ec65ee00-8718-11eb-9a71-0f80d9028086.mp4

Here is the Prefab for testing purposes:
[SpellBookPrefab.zip](https://github.com/FlaxEngine/FlaxEngine/files/6153043/SpellBookPrefab.zip)

**Flax version:**
Branch 1.1

**Comment by jb-perrier** [comment]
You SpellBook control have their marings set to 5, but ObjectiveLog to 2. That's why the horizontal panel keep being moved to pos 5.

**Comment by mafiesto4** [comment]
Yeah setting the same margin for both of them makes those panels aligned nicely.

**Comment by Evildea** [comment]
Don't know how I overlooked this. Sorry guys.
