### ISSUE TITLE
UI Bug: Vertical Order isn't being maintained when one Prefab nested in another

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#357]
**Issue description:**
![image](https://user-images.githubusercontent.com/35228400/111548675-285b8a80-87cf-11eb-996b-6692c76eaad7.png)

Here are the Prefabs:
[Nesting.zip](https://github.com/FlaxEngine/FlaxEngine/files/6160227/Nesting.zip)

**Flax version:**
Branch 1.1 (With all updates as of 3/18/21)

**Comment by mafiesto4** [comment]
Yeah I just started fixing it as I discovered it while fixing #351

**Comment by mafiesto4** [comment]
Fixed by https://github.com/FlaxEngine/FlaxEngine/commit/a21f6d1b9fbb4b7cd27848c7e61d966d4cde3ca9.
