### ISSUE TITLE
UI Bug: Multi-Line Text isn't giving itself more space

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#358]
**Issue description:**
I'm not sure if this is a bug or not, but the multiline text isn't expanding its bounds to give itself more space in the Vertical Box. As a result, it starts to overlap the Progress Bar.
![image](https://user-images.githubusercontent.com/35228400/111549428-41b10680-87d0-11eb-895e-47ca728256a7.png)

**Flax version:**
Branch 1.1

**Comment by mafiesto4** [comment]
In this case the label will change dimensions when **Auto Height** is checked. It works like this on the current `1.1` branch:
![image](https://user-images.githubusercontent.com/3464853/111642285-3c6ab080-87fe-11eb-9ed0-c2e66281084d.png)

**Comment by mafiesto4** [comment]
Issue confirmed when using Word Wrapping (or Character Wrapping) - height is not automatically calculated for wrapped lines

**Comment by mafiesto4** [comment]
Fixed by 7dd67b5ae3db897c122213238b15b9991b9162da.
