### ISSUE TITLE
UI Suggestion: UI Face to Camera

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#359]
**Issue description:**
The new Sprite Render has an option called "Face Camera". I think World Space UI would really profit if it had this option as well. This is handy so you can have the UI follow an object in the world but always face the Camera. Like a healthbar or a Name.
![image](https://user-images.githubusercontent.com/35228400/111551514-7921b200-87d4-11eb-92ec-fdec8842193e.png)

**Flax version:**
Branch 1.1

**Comment by mafiesto4** [comment]
Added in 29e06eb6963dfefe74d9019765bd531184fb3e0b.
