### ISSUE TITLE
Deleting script from C# that is still attached to Prefab is messy.

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#360]
**Issue description:**
I deleted a script from C# that I didn't need anymore. Unfortunately, that script was still referenced by a heap of Prefabs. They are now angry at me. As you can see from the messages in the Output log. I suppose the only way to resolve these issues at the moment is to manually edit the Json files.
![image](https://user-images.githubusercontent.com/35228400/111554018-a02eb280-87d9-11eb-9b1e-287425cb1437.png)

**Steps to reproduce:**
1. Make a Script
2. Add it to an Actor
3. Delete the script from within C#
4. Check the output log

**Flax version:**
Branch 1.1

**Comment by mafiesto4** [comment]
That's intended behavior. The message can be *fixed* either by adding that missing script or by resaving that prefab in editor (edit any property in prefab, undo, save, solved).

This *feature* makes it easy to track any missing scripts: for example when someone forgets to commit one `.cs` file or removes Visual Script that was used in a project so it will warn - also during game cooking so developers can fix problems in a game.
