### ISSUE TITLE
UI Bug: Progress Bar broken in World Space

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#361]
**Issue description:**
The Progress Bar works in Screen Space both through the Editor and Code but breaks for World Space both through the Editor and Code.

**Steps to reproduce:**
Watch this video here:
https://user-images.githubusercontent.com/35228400/111556295-4e3c5b80-87de-11eb-9646-ed13f6338956.mp4

**Flax version:**
Branch 1.1

**Comment by mafiesto4** [comment]
Fixed in 7a12a6c2805a5990a1792792cad5fae26a2af5ab. Thanks for reporting that one!
