### ISSUE TITLE
Nested Prefab still crashing when changes are made

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#362]
**Issue description:**
I know you pushed a fix for this already but the issue occurred again. This StatsDialogue Prefab is crashing (it is part of many other Prefabs include the Player Prefab). This occurs when I try to add a Vertical Panel to the StatsDialogue Prefab.

[StatsDialoguePrefab.zip](https://github.com/FlaxEngine/FlaxEngine/files/6161145/StatsDialoguePrefab.zip)

**Flax version:**
Branch 1.1

**Comment by mafiesto4** [comment]
I was unable to reproduce it on the recent `1.1`. In this case probably the crash log would help (crashdump is not needed, just log),

**Comment by Evildea** [comment]
If it happens again within the next week, I'll update this ticket. If it doesn't happen again after that I'll close the ticket.
