### ISSUE TITLE
Changes to Prefab which is nested in another Prefab don't update the scene

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#364]
**Issue description:**
Ok, let me try break this down.

The StatsDialoguePrefab is inside the TutorialNPC Prefab.
The TutorialNPC Prefab is in the scene.

I've noticed when I make changes to the StatsDialoguePrefab, it updates the TutorialNPC Prefab, but it doesn't appear to always update the Scene Prefab. I've attached my 2 Prefabs + the Scene where you can see the Scene hasn't been updated correctly:
[StatsDialoguePrefab.zip](https://github.com/FlaxEngine/FlaxEngine/files/6161322/StatsDialoguePrefab.zip)

Here is the log (where it starts to puke errors):
[Log_2021_03_18_15_40_59.txt](https://github.com/FlaxEngine/FlaxEngine/files/6161343/Log_2021_03_18_15_40_59.txt)

The only way to fix this issue at the moment is to delete every object that contains that changed Prefab and readd them to the Scene.

**Flax version:**
Branch 1.1 (I have the newest updates you've pushed)

**Comment by mafiesto4** [comment]
Fixed in v1.2 (prefabs changes sync and apply refactor).
