### ISSUE TITLE
Annoyance: Dragging Objects into the Scene then manipulating them with Gizmo can be annoying

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#367]
**Issue description:**
This is more an annoyance than anything else. Sometimes when I drag an actor into the scene from the content browser. The editor window doesn't become focused which means I'm unable to immediately use any of the gizmos. This means I have to then manually click on the window. Next the move gizmo sometimes doesn't automatically work either. You can see the problems in the attached video:
https://user-images.githubusercontent.com/35228400/111711368-a38c7180-889f-11eb-9151-e89a06441bee.mp4

**Flax version:**
Branch 1.1

**Comment by mafiesto4** [comment]
Fixed 4efd411045439dbc92ee39c6be43de0a5d039a70.
Now viewport gets auto-focused and mouse is handled in a proper way. Works for both Level and Prefab viewports.
