### ISSUE TITLE
New "World Space Face Camera" draws UI upside down and back to front

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#370]
**Issue description:**
You can see a screenshot here:
![image](https://user-images.githubusercontent.com/35228400/111853197-119f6a00-896e-11eb-90d0-ab574fac8173.png)
I also tried it in a new project just to be sure:
![image](https://user-images.githubusercontent.com/35228400/111853341-bd48ba00-896e-11eb-883e-bd5ee48fd00d.png)

**Flax version:**
Branch 1.1

**Comment by mafiesto4** [comment]
Fixed by 59b975499fccbfd9f8a968b0903980c0b2281e30
