### ISSUE TITLE
UI Face Camera doesn't always work perfectly.

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#371]
**Issue description:**
The new Branch 1.1 feature to make the UI face the camera doesn't always perfectly work. For example, here the UI is facing the camera but it has a weird angle to it.
![image](https://user-images.githubusercontent.com/35228400/111923231-489e8880-8af2-11eb-89bf-c6a8fa380f95.png)

**Flax version:**
Branch 1.1

**Comment by mafiesto4** [comment]
This might be related to the fact that UICanvas faces camera in this mode based on it's center so if it's large and text is placed in the top area then it might not look perfect. In this case you could align text in the middle.

**Comment by Evildea** [comment]
It's not the shape of the UICanvas. I made the canvas perfectly fit the size of the Label. Additionally, I made sure it was standing alone so it wouldn't be affected by a parent. Here's a video of me showing how it seems to rotate the more the center of the camera viewport gets from the object.
https://user-images.githubusercontent.com/35228400/112095447-a0231e00-8bf0-11eb-94ca-8c0ca3e10d06.mp4

**Comment by mafiesto4** [comment]
Fixed in 934258aadbbfb57bca35a913c4c47a9fbbc37c13. Does it work as expected now?

**Comment by Evildea** [comment]
Yeap works perfectly now!
