### ISSUE TITLE
Material not updating on connection removal

### ISSUE THREAD

**Issue by stefnotch** [FlaxEngine/FlaxEngine#372]
**Issue description:**
When you remove a connection in the Visject material editor, the material doesn't re-compile.
This is apparently a regression. Uh oh

**Steps to reproduce:**
1. Create a material
2. Connect a color/texture to the `Color` output
3. Remove the connection by dragging from the color output.

![image](https://user-images.githubusercontent.com/10220080/111965839-7e457080-8af6-11eb-9223-37231e2c5f85.png)

**Flax version:**
Flax 1.1, latest from master

**Comment by mafiesto4** [comment]
Fixed by b3e16a6b66ee5b41ba3891bbe531ff5b491a513a.
