### ISSUE TITLE
Custom Actor Icons

### ISSUE THREAD

**Issue by honzapatCZ** [FlaxEngine/FlaxEngine#373]
Custom gizmos, from own icons to juse easy to set stuff in the editor
![image](https://user-images.githubusercontent.com/26117393/111967658-9918e480-8af8-11eb-870e-3d28c65b5c5a.png)

**Comment by stefnotch** [comment]
I'm a bit confused, since I associate gizmos with those 3D things.

What exactly is this asking for?

**Comment by honzapatCZ** [comment]
Well ok, those are more like icons

**Comment by mafiesto4** [comment]
Custom actor icons added. See docs: https://docs.flaxengine.com/manual/scripting/tutorials/custom-actor.html?tabs=code-csharp#actor-with-an-icon

**Comment by Withaust** [comment]
With my PR this is also available to be set on per-actor basis https://github.com/FlaxEngine/FlaxEngine/pull/1041
