### ISSUE TITLE
[Question] Is it able to use the latest msvc toolset

### ISSUE THREAD

**Issue by HydrogenC** [FlaxEngine/FlaxEngine#374]
**Issue description:**
I have the MSVC toolset v142 installed, however it outputs this message

> Missing MSVC toolset v140 (VS 2015 C++ build tools)

I wonder if it is able to use the latest toolset instead of v140. 
But I cannot find anything related in the docs. 
The README says "Install Microsoft Visual C++ 2015 v140 toolset **or newer**"
Also, the latest Win10 SDK seems to be not detected. 

**Steps to reproduce:**
None

**Minimal reproduction project:**
None

**Flax version:**
1.0

**Comment by mafiesto4** [comment]
Yeah `1.0` version didn't support the newer toolsets properly. It's fixed for `1.1` update (coming out this week).

**Comment by HydrogenC** [comment]
> Yeah `1.0` version didn't support the newer toolsets properly. It's fixed for `1.1` update (coming out this week).

Thanks for replying.
