### ISSUE TITLE
UI Bug: Anchor issues with Vertical Panel

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#378]
**Issue description:**
I've added a button to a Vertical Box. The Vertical Box is set to Stretch. However, if I set the Button to a Horizontal Center Stretch it positions itself far off to the left.
![image](https://user-images.githubusercontent.com/35228400/112082997-69420d80-8bda-11eb-80de-bb5907016296.png)

See the following video to understand what I mean:
https://user-images.githubusercontent.com/35228400/112082835-21bb8180-8bda-11eb-9de6-ceb041ada233.mp4

Here is the Prefab:
[MainMenu.zip](https://github.com/FlaxEngine/FlaxEngine/files/6186446/MainMenu.zip)

**Flax version:**
Branch 1.1

**Comment by mafiesto4** [comment]
Fixed in e8c98566653e257948587a934bde03b69416de63.
