### ISSUE TITLE
Game Viewport Bug: All Controls Disappear after script update

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#379]
**Issue description:**
Basically, if you have a UI in the game port and you update the scripts that UI completely disappears until you press Play. To understand watch me perform this action in the attached video:

https://user-images.githubusercontent.com/35228400/112084029-3c8ef580-8bdc-11eb-87ac-674eef3a4bb4.mp4

**Flax version:**
Branch 1.1

**Comment by mafiesto4** [comment]
Fxied some time ago.
