### ISSUE TITLE
UI Bug: Changing font size of control doesn't immediately adjust height

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#380]
**Issue description:**
Basically, the control doesn't adjust its size even though "auto height" is set immediately after changing the font size. Instead you have to turn "auto height" off and back on to make it recalculate.

Here is a video of the issue:
https://user-images.githubusercontent.com/35228400/112084713-6563ba80-8bdd-11eb-85b6-bbe30888a822.mp4

**Flax version:**
Branch 1.1

**Comment by mafiesto4** [comment]
Fixed in 16f81cc1841ddeeb94585374b440c36eedf90ea6.
