### ISSUE TITLE
UI Bugs: Two New UI Bugs

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#385]
**Issue description:**
First, watch the video to see each UI bug in action.
https://user-images.githubusercontent.com/35228400/112247864-1e42fb80-8ca9-11eb-8aec-80905e493102.mp4

### Unintuitive Height (Not a bug just annoying)
When the anchor is set to the bottom it would be a lot more intuitive that Height expand the area upwards as opposed to pushing it downwards further off the screen.
![image](https://user-images.githubusercontent.com/35228400/112247218-0d45ba80-8ca8-11eb-9461-f40c096b93fc.png)

### Duplicating a control sometimes results in the original control breaking
Once this happens, everything else starts to break in the UI. It's like a cascading failure.
![image](https://user-images.githubusercontent.com/35228400/112247458-7299ab80-8ca8-11eb-8b40-6d6e4303c2be.png)

### Labels and Images don't layout correctly
It appears that Labels and Images just don't adjust to fit eachother.
![image](https://user-images.githubusercontent.com/35228400/112247721-e89e1280-8ca8-11eb-84ac-b6bb1d62311a.png)
Here is a test Prefab:
[Test (2).zip](https://github.com/FlaxEngine/FlaxEngine/files/6194027/Test.2.zip)
Ticking "Auto Size" doesn't help either as the Panel just collapses:
![image](https://user-images.githubusercontent.com/35228400/112248196-aa552300-8ca9-11eb-9340-89eb024c267d.png)

**Flax version:**
Master Branch

**Comment by mafiesto4** [comment]
3) Fixed in d3bdc3cf8b0ee73ac45830751380cee5f885914c and 9f79d0e3c49b1ca66a644a8ad48bbf4261410915.

**Comment by Menotdan** [comment]
@mafiesto4 I think 1 is fixed (height from bottom anchors seems to work correct when I was using it) and I would think 2 is fixed as well right?

**Comment by mafiesto4** [comment]
Yeah all issues here seam to work fine now. Regarding no. 1 editor allows to easily snap/tweak anchor points and Height can expand relative to the anchor (eg. bottom of the control or top or middle).
