### ISSUE TITLE
Missing Shortcut Key (Shift + Home)

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#386]
**Issue description:**
The short cut keys Shift + Home are a common windows shortcut key combination that will select all the text in a text box from the current cursor point back to the beginning of the line.
[More Information](https://defkey.com/what-means/shift-home)

I'm so used to using this combination in other programs that its lack of usability in text boxes in Flax is a little annoying. For example in the Label Control:
![image](https://user-images.githubusercontent.com/35228400/112250153-0a999400-8cad-11eb-9df0-da1973e8013b.png)

**Flax version:**
Master

**Comment by mafiesto4** [comment]
Fixed in 5c495b987bba765e1a7723001be76da629c6a889.
