### ISSUE TITLE
Y Gizmo Rotation Reversed

### ISSUE THREAD

**Issue by nocxtious** [FlaxEngine/FlaxEngine#39]
**Issue description:**

Manually rotating an actor with the Y gizmo handle is reversed, where X and Z are not.

**Steps to reproduce:**

1. Open a project
2. Grab actor and switch to rotation gizmo
3. Rotate actor along Y axis using handle

**Minimal reproduction project:**

1. New or existing project

**Flax version:**

1.0.6214 (last commit pulled: 2c6a70b74460270be34d22b954c0fc0496a89068)

https://user-images.githubusercontent.com/72276215/102940889-96154600-446e-11eb-8978-044e7f28a676.mp4

**Comment by mafiesto4** [comment]
Fixed by #60
