### ISSUE TITLE
Shadow jiggling

### ISSUE THREAD

**Issue by trsh** [FlaxEngine/FlaxEngine#390]
https://user-images.githubusercontent.com/3727523/112359888-6c242780-8cda-11eb-9eec-d48d0b35e7af.mp4

Not mine project. Can't share anything but https://drive.google.com/file/d/1jz_whHEGHCRLKV_JyTR3YNE5ZuN7_KV4/view

```
Jimi Vacarians — Today at 7:50 PM
I've reported it internally, i don't know if there is an issue
```

**Comment by jb-perrier** [comment]
For now a workaround is to considerably increase csm resolution way over the "Ultra" quality setting.  In my project i'm using a 8K res, the ultra setting is 2k.

**Comment by trsh** [comment]
> For now a workaround is to considerably increase csm resolution way over the "Ultra" quality setting. In my project i'm using a 8K res, the ultra setting is 2k.

Thanks for the tip. But this needs to be addressed as high priority, so we don't need workarounds.

**Comment by GoaLitiuM** [comment]
Probably not a bug, but an enhancement to how shadow should be rendered. Maybe something like this could be adapted for improving this: http://dev.theomader.com/stable-csm/

**Comment by mafiesto4** [comment]
I added `View Snapping` mode based on [ShaderX7 - Practical Cascaded Shadows Maps](https://www.slideshare.net/ProjectAsura/ss-66370182?next_slideshow=1) in 0a474772900d97b62c62ae3c0df41d8d497b7559. Tested different scenes and it looks more stable. Ofc, it might jitter in certain camera/light angles and for certain geometry. In future, raytraced shadows are the way to go.
