### ISSUE TITLE
Some build configurations refer to incorrect solution configurations

### ISSUE THREAD

**Issue by HydrogenC** [FlaxEngine/FlaxEngine#392]
Flax master. Visual Studio 2019. 
Configuration "**Editor.Windows.Debug**" should refer to "**Editor.Debug|Win64**" but it actually refers to "Editor.Debug|Any CPU".
Configuration "**Game.XboxOne.Release**" should refer to "**Game.Debug|XboxOne**" but it actually refers to "Debug|XboxOne". 
The two mismatches above can be inspected in the "batch build" panel in VS. 

<img width="354" alt="屏幕截图 2021-03-27 092206" src="https://user-images.githubusercontent.com/33123710/112706246-099b7900-8ede-11eb-8b95-c9bb115ce5f4.png">
<img width="355" alt="屏幕截图 2021-03-27 092244" src="https://user-images.githubusercontent.com/33123710/112706250-0bfdd300-8ede-11eb-9607-53605349a5b1.png">

**Comment by GoaLitiuM** [comment]
Does this work now as expected? We removed the default "Debug" and "Release" configurations from engine projects, so "Debug|XboxOne" shouldn't exist anymore.
