### ISSUE TITLE
Plugins aren't loading properly!

### ISSUE THREAD

**Issue by Crawcik** [FlaxEngine/FlaxEngine#397]
**Issue description:**
Plugins aren't adding to visual studio project file as reference

**Steps to reproduce:**
Just try adding plugin to project and add this option:
options.PrivateDependencies.Add("Plugin");
It will not show in vs project

**Minimal reproduction project:**
[Burgers.zip](https://github.com/FlaxEngine/FlaxEngine/files/6218028/Burgers.zip)

**Flax version:**
1.1

**Comment by LCRW** [comment]
So I just tried that project in latest version, it works properly in FlaxEditor, by building plugin first then compiling burgers from the editor, but confirm unable to build in visual studio as plugin is not being resolved.
