### ISSUE TITLE
Infinite script compilation loop

### ISSUE THREAD

**Issue by Crawcik** [FlaxEngine/FlaxEngine#398]
**Issue description:**
Whenever I open the project it's stuck in a loop, compilating scripts forever. It was perfectly fine in previous version

**Steps to reproduce:**
It is hard to tell so check project bellow. Maybe I screwed up something

**Minimal reproduction project:**
[Burgers.zip](https://github.com/FlaxEngine/FlaxEngine/files/6218028/Burgers.zip)

**Flax version:**
1.1

**Comment by mafiesto4** [comment]
Add this to `Network.flaxproj`:
```json
"EditorTarget": "NetworkTarget",
```
so it will work fine.

Also, fixed in: d85a020971c1f88c17cf5ccb53ebd31060c8a296
