### ISSUE TITLE
Apple Support?

### ISSUE THREAD

**Issue by RPG3D** [FlaxEngine/FlaxEngine#40]
any plain to support macOS & iOS?

**Comment by jayrulez** [comment]
Yes, they're on the roadmap.

**Comment by honzapatCZ** [comment]
Who would wanna support that with their weird way of managing, monopoly and certification?

**Comment by mafiesto4** [comment]
macOS support is already in Flax: https://docs.flaxengine.com/manual/platforms/mac.html
Source: https://github.com/FlaxEngine/FlaxEngine/tree/master/Source/Engine/Platform/Mac
Soon we will work on iOS too.
