### ISSUE TITLE
Project conversion is bugged

### ISSUE THREAD

**Issue by michalzembron** [FlaxEngine/FlaxEngine#401]
**Issue description:**
So in Flax 1.0 there was a bug that you couldn't go fullscreen by "Screen.IsFullscreen = true;" and It's fixed in Flax 1.1, the only problem is that It's fixed only for new projects in version 1.1. In my case I had project made in 1.0, converted it to 1.1 and the problem still exists, but now without any errors, now It just freezes.

**Steps to reproduce:**
1. Create project in version 1.0.
2. Add simple scene with button and a script attached to it.
3. Create an OnClick method so when the button is pressed It triggers Screen.IsFullScreen = true.
4. Convert this project to 1.1, build the game and click the button.

**Minimal reproduction project:**
Basic project in version 1.0 with button and a script.

**Flax version:**
1.1

**Comment by HydrogenC** [comment]
Additionally, when I open a 1.0 project with 1.1, it can't print anything out in the console.
