### ISSUE TITLE
Copying new log after clearing partially fails

### ISSUE THREAD

**Issue by stefnotch** [FlaxEngine/FlaxEngine#402]
**Issue description:**
When you clear the output log, then recompile the scripts and then try to copy the entire new log, only the first two lines get copied (or maybe the first 255 characters)

**Steps to reproduce:**
1. Open output log
2. Right click, clear
3. Recompile scripts
4. Select all 
5. Copy
6. Paste somewhere else

**Flax version:**
Flax 1.1

**Comment by TaylerMauk** [comment]
I was able to recreate the issue without clearing the log. Just attempt to copy lines where one was generated by `ScriptsBuilderImpl::compileGameScriptsAsyncInner()` and the clipboard text will end with that line.

I was able to get the copy to work by stripping the last character from the log command at https://github.com/FlaxEngine/FlaxEngine/blob/d11a9d4d8fba865f1a11399f4b037334f85b294d/Source/Engine/Platform/Windows/WindowsPlatform.cpp#L938

But this mystery character does not seem to be present when the value of `args` is logged within `ScriptsBuilderImpl::compileGameScriptsAsyncInner()`.

The value of the character appears to be 0x00, so maybe a rogue null terminator?
