### ISSUE TITLE
PxController::getUpDirection & PxController::setUpDirection not exposed through CharacterController

### ISSUE THREAD

**Issue by EnokViking** [FlaxEngine/FlaxEngine#405]
Like the title suggests, these two methods have been left out from the CharacterController implementation.
https://docs.nvidia.com/gameworks/content/gameworkslibrary/physx/guide/Manual/CharacterControllers.html#up-vector
They're declared in PxControllerDesc.h

**Comment by jb-perrier** [comment]
I've exposed these funcs, but before making a PR it probably need some more work and checks. Using SetUpDirection can make the character to overlap nearby geometry, so we need to use the `overlap recovery module` in order to keep things clean.

**Comment by EnokViking** [comment]
> I've exposed these funcs, but before making a PR it probably need some more work and checks. Using SetUpDirection can make the character to overlap nearby geometry, so we need to use the `overlap recovery module` in order to keep things clean.

Given how it's implemented it makes sense to just expose that as a setting I feel. A call to PxControllerManager::setOverlapRecovery applies to all CCT's in the simulation. A possible solution to enable similar behaviour on a per CCT basis is to include a simple overlap check and resolve it with the translation vector returned by PxGeometryQuery::computePenetration.

**Comment by mafiesto4** [comment]
Added in #435
