### ISSUE TITLE
Opening Visual Studio project from Flax Editor doesn't work properly

### ISSUE THREAD

**Issue by Crawcik** [FlaxEngine/FlaxEngine#406]
**Issue description:**
1. Button "File->Open scripts project" does nothing
2. Attempting to open a project by double-clicking a script in the editor will open only the file, not the entire solution

**Minimal reproduction project:**
Any flax project will work

**Flax version:**
1.1

**Comment by HydrogenC** [comment]
I also met with this problem.

**Comment by Crawcik** [comment]
I found that it only occurs when the "Source Code Editor" in "Editor Options" is set to "Default" or "System Default".

I tried to find the issue but breakpoints aren't working from me.

**Comment by Crawcik** [comment]
> 
> 
> Do you use Visual Studio as code editor in options? Do you have Flax.VS installed? (https://marketplace.visualstudio.com/items?itemName=Flax.FlaxVS)

I used "Default" option in Flax and I don't have Flax.VS

**Comment by HydrogenC** [comment]
I set it to "Visual Studio" but don't have Flax.VS installed. It also doesn't work.

**Comment by petrminarik-star** [comment]
Even with Flax.VS only the cs file is opened. Switching "Source Code Editor" to any value does not have any effect. I have installed both VS2017 and VS2019.

**Comment by Crawcik** [comment]
Fixed in 1.2
