### ISSUE TITLE
Spline gap

### ISSUE THREAD

**Issue by stefnotch** [FlaxEngine/FlaxEngine#408]
**Issue description:**
I tried out a spline with the default cube and noticed an odd gap. It only ever seems to happen on the top side of the spline.
The same issue happens with the default cylinder when you rotate it by 90 degrees.

![image](https://user-images.githubusercontent.com/10220080/112968901-0a861200-914d-11eb-9006-9063326e3503.png)

**Steps to reproduce:**
Create a spline with a spline model. And then set the model to the default cube.

Alternatively, check out Scene 0 in the reproduction project.

**Minimal reproduction project:**
https://github.com/stefnotch/anime-rendering-experiments/tree/51d118328b3a04b3ea4c4a0aa1fd9971ec4b68dd

**Flax version:**
Flax 1.1

**Comment by mafiesto4** [comment]
Probably some floating-point precision issues.

**Comment by mafiesto4** [comment]
Changing pre-transform scale to sth like `1.01` at one of the axes fixes the gap?

**Comment by stefnotch** [comment]
I thought so as well, but couldn't quite hunt the issue down. It might still be something slightly different.

Changing the pre-transform scale sadly doesn't fix it

So, this is what it looks like (from another angle)
![image](https://user-images.githubusercontent.com/10220080/113053315-6f228a80-91a8-11eb-8109-af896e45ba2b.png)

Changing the pre-transform Z position to 100 makes the gap a bit smaller
![image](https://user-images.githubusercontent.com/10220080/113053474-98431b00-91a8-11eb-8012-f9bac92b428e.png)

To fully remove that gap, one has to increase the pre-transform position a bit more, to about 210. Funnily enough, at that point I can move the spline however I want and the gap doesn't re-appear

![image](https://user-images.githubusercontent.com/10220080/113053616-c0cb1500-91a8-11eb-934f-59d2431c9718.png)
