### ISSUE TITLE
Spline cannot click on middle point

### ISSUE THREAD

**Issue by stefnotch** [FlaxEngine/FlaxEngine#409]
**Issue description:**
I messed around with a spline a fair bit until I got into a situation where I suddenly couldn't click on the point in the middle.

![image](https://user-images.githubusercontent.com/10220080/112968901-0a861200-914d-11eb-9006-9063326e3503.png)

**Steps to reproduce:**
Check out Scene 0 in the reproduction project. Same reproduction project as in issue #408

**Minimal reproduction project:**
https://github.com/stefnotch/anime-rendering-experiments/tree/51d118328b3a04b3ea4c4a0aa1fd9971ec4b68dd

**Flax version:**
Flax 1.1

**Comment by mafiesto4** [comment]
Fixed in 77f971693226109c22d46f994eb11949abded0c8.
