### ISSUE TITLE
Rendering broken on Linux

### ISSUE THREAD

**Issue by fadyosman** [FlaxEngine/FlaxEngine#410]
**Issue description:**
Rendering is broken in linux.

**Steps to reproduce:**
Open any of the samples.

![materials](https://user-images.githubusercontent.com/7545898/113030681-26f66e80-918e-11eb-8a3e-bb91a002ccd3.png)
![Screenshot_20210330_192533](https://user-images.githubusercontent.com/7545898/113030703-2c53b900-918e-11eb-8a4b-a6fc02f38dd3.png)

**Flax version:**
Linux version downloaded from https://flaxengine.com/download/

I am using nvidia gtx 1060 on Ubuntu 20.04.2 LTS.

**Comment by fadyosman** [comment]
@W2Wizard @mafiesto4

I am running this from the command line but I don't see any errors or warnings on the console (I don't believe those GTK warnings are related), is there a way I can generate a more verbose log?

![Screenshot_20210331_004724](https://user-images.githubusercontent.com/7545898/113066357-b0bc3100-91ba-11eb-901a-2757763a47ed.png)

**Comment by Flavelius** [comment]
In the project's folder there's a Logs subfolder in which you can find more verbose output

**Comment by mafiesto4** [comment]
Yeah `<project>\Logs`. Latest file from there. You can also run engine with `-std` flag to get output to the console.

**Comment by fadyosman** [comment]
Thanks @mafiesto4,

The following is the log, I can see warnings about invalid assets, I cloned the samples repository without any modifications.

[Log_2021_03_30_19_24_33.txt](https://github.com/FlaxEngine/FlaxEngine/files/6250102/Log_2021_03_30_19_24_33.txt)

**Comment by mafiesto4** [comment]
It looks like assets are missing (eg. asset id `71bfcf2443a50f1f0bc9a8ba1adbb28a` is in-built normal map texture for default material). Can you verify that files were extracted properly from the archive?
![image](https://user-images.githubusercontent.com/3464853/113687784-fbf9a680-96c8-11eb-8794-4b1b3ff7d577.png)

**Comment by fadyosman** [comment]
Hi @mafiesto4,

I think you were right I re-downloaded the editor and it did work, sorry for wasting your time on this, somehow the files got corrupted.
