### ISSUE TITLE
Ability to download artifacts in Github Action builds

### ISSUE THREAD

**Issue by HydrogenC** [FlaxEngine/FlaxEngine#416]
Building the engine on a mid-performance laptop takes a lot of time and I have to repeat it every time there are new commits. Also, the various dependencies takes a lot of disk space. Is there a way to enable artifact downloading in Github Actions builds?

**Comment by mafiesto4** [comment]
This feature has been added to Flax Launcher (a while ago), some docs about it for newcomers: https://docs.flaxengine.com/manual/get-started/get-flax.html
