### ISSUE TITLE
Lighting broken when project is opened while other program is focused

### ISSUE THREAD

**Issue by ArtyIF** [FlaxEngine/FlaxEngine#421]
**Issue description:**
When I was opening a sample project, I alt-tabbed out of the window, like I usually do (hello Unity). When I got in the editor, I found every object to be lit improperly (Sky didn't work, baked lighting only) I restarted the editor, this time not clicking away, and the lighting worked as intended.

**Steps to reproduce:**
1. Open any project
2. Switch to any other program before the loading splash appears
3. Wait until the project is loaded and switch back
4. Notice how lighting doesn't work properly

**Minimal reproduction project:**
The Basic template should do

**Flax version:**
1.1.6217

**Comment by mafiesto4** [comment]
Thanks for reporting. I guess it might be related to the first project startup and something that is not cached properly when editor is out-of-focus (we yield to not use too much CPU power when user is not focusing Editor). I think I had sth similar in a past so let's keep this ticket open and try to track this down!

**Comment by ArtyIF** [comment]
> 
> 
> Thanks for reporting. I guess it might be related to the first project startup and something that is not cached properly when editor is out-of-focus (we yield to not use too much CPU power when user is not focusing Editor). I think I had sth similar in a past so let's keep this ticket open and try to track this down!

It's not only on the first project startup. It happens every startup if the editor's out-of-focus.

**Comment by mafiesto4** [comment]
Could you post a log file of that editor run at which artifact appear?

**Comment by ArtyIF** [comment]
> 
> 
> Could you post a log file of that editor run at which artifact appear?

Just opened the project while out-of-focus. Weirdly, nothing unusual happened. Maybe I was misremembering things.
