### ISSUE TITLE
Using an API_FUNCTION inside a class inheriting ISerializable fails to compile

### ISSUE THREAD

**Issue by LCRW** [FlaxEngine/FlaxEngine#423]
```
#include <Engine/Core/ISerializable.h>
#include <Engine/Scripting/ScriptingType.h>

API_CLASS(Namespace = "NativeBug", Abstract) class NATIVEBUG_API IModule : public ISerializable
{
API_AUTO_SERIALIZATION();
DECLARE_SCRIPTING_TYPE_NO_SPAWN(IModule);

protected:
	API_FIELD() int SomeInt = 0;
	IModule(int c) : SomeInt(c) { }
public:
	// Uncomment the line below to produce compile failure.
	// API_FUNCTION() void DoSomething() { } 
};
```

**Steps to reproduce:**
Paste above code in to a header in a native code module. Build solution to verify it compiles. Then uncomment the DoSomething function and see that it fails to compile.

**Flax version:**
1.1 From Launcher

**Comment by LCRW** [comment]
So I found a decent workaround by inheriting from PersistentScriptingObject and ISerializable.

**Comment by mafiesto4** [comment]
But you can use 'API_INTERFACE'  in this case to expose method template for implantation as documented here: https://docs.flaxengine.com/manual/scripting/cpp/interfaces.html
