### ISSUE TITLE
Bug: Gameplay Globals

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#427]
**Issue description:**
Can't delete Values from the list. Please see the attached video to see the bug in action.
https://user-images.githubusercontent.com/35228400/113813080-92ee5d80-97b2-11eb-8084-fbfded825644.mp4

**Flax version:**
Windows: Master Branch

**Comment by mafiesto4** [comment]
Fixed in d073a13f57e037922f3694efa84571d166fb5529
