### ISSUE TITLE
Bug: Gameplay Globals are broken for "Color" Parameters

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#428]
**Issue description:**
I have a Gameplay Globals Object that I access through C#
![image](https://user-images.githubusercontent.com/35228400/113814095-77845200-97b4-11eb-9b40-29227b2c1223.png)

I'm able to access all variables correctly except for the Color.

Using the following code:
```
Enemy = (Color)GameColours.GetValue("Enemy");
Debug.Log(GameColours.GetValue("Enemy"));
```

Results in the following value being returned:
![image](https://user-images.githubusercontent.com/35228400/113814287-be724780-97b4-11eb-87ba-85f192f40226.png)

**Flax version:**
Master Branch

**Comment by Crawcik** [comment]
Weird, I works fine for me

**Comment by jb-perrier** [comment]
Yeah , i've tried many combination and i haven't succeded to reproduce the issue. Maybe it's a tricky edge case.

**Comment by mafiesto4** [comment]
Works for me too :sweat_drops:
