### ISSUE TITLE
Transform gizmos not scaling in orthographic view. Unusable viewpoints.

### ISSUE THREAD

**Issue by sorugd** [FlaxEngine/FlaxEngine#436]
Orthographic view transform gizmos are not scaling when zooming in/out.
Also transform gizmos not working as expected when using orthographic view and viewpoints.

![flax-gizmos](https://user-images.githubusercontent.com/3464853/236667088-509f70cd-cba2-4db2-9d54-edd1376e0338.gif)

Flax version: 1,1

**Comment by mafiesto4** [comment]
The bigger, the better xD

**Comment by NoriteSC** [comment]
fixed in https://github.com/FlaxEngine/FlaxEngine/pull/1695

**Comment by mafiesto4** [comment]
Fixed in #1695
