### ISSUE TITLE
Color Picker gives values higher than 1.0

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#437]
Color Picker gives values higher than 1.0
![image](https://user-images.githubusercontent.com/35228400/113951988-17df8280-9858-11eb-85cf-a1472120d12a.png)

Master Branch

**Comment by mafiesto4** [comment]
It supports HDR colors so it doesn't clamp the component values but it looks like some precision issue to tackle.

**Comment by mafiesto4** [comment]
Fixed in 79d393b3ef83367cd70adceef807259f8ab06f38.
