### ISSUE TITLE
UI Bugs: Various UI Bugs all related to Auto Width and Auto Height

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#438]
I have discovered more UI bugs. Actually, I've been aware of them for a while but been too lazy to report them as I had work arounds.

All issues are visible in this film: https://user-images.githubusercontent.com/35228400/113955621-70664e00-985f-11eb-8f1a-3766954edba9.mp4

### Auto Width and Auto Height
These buttons don't automatically readjust the following things:

**Offsets for Anchor points**
This is especially problematic for Labels whose bounds will scale in size to accommodate the text. Unfortunately, they're not recalculating their offsets for the anchor positions. You can see this in action in the film at 36 seconds in.
![image](https://user-images.githubusercontent.com/35228400/113955228-a9ea8980-985e-11eb-8b89-ec3bbf63c677.png)

**Font Style or Font Size**
If you change the Font Style or Size the label doesn't automatically update its offset for the anchor. You can see this at 51 seconds in the film.

**Margins**
If you change the Margin the label doesn't automatically update its size and offset. You can see this at 1:26 in the film

**Flax version:**
Master Branch

**Comment by mafiesto4** [comment]
Actually, I tried to fix it locally to update label bounds when the user changes AutoHeight or AutoWidth but it breaks the other editing actions: for instance if you have placed a label with a custom offset from the center of the upper parent control edge then changing those properties simply breaks exiting UI layout. I guess in this UI system for auto-centered controls simply make the control docked to the top with text being centered or use vertical panel as a parent container for more control over positioning.

When using scripts you can also control the placement to automatically place the control in the anchor location:
```cs
control.SetAnchorPreset(AnchorPresets.TopCenter, false);
```

*I checked and Unity doesn't support automatic text/label item sizing based on text size and Unreal works the same as Flax.

**Comment by mafiesto4** [comment]
😢
