### ISSUE TITLE
Scene navigation issues in the editor viewport

### ISSUE THREAD

**Issue by ecstaticcoder** [FlaxEngine/FlaxEngine#44]
While editing a 4km x 4km test terrain with Flax Engine 1.0.6214, I found that the terrain editing tools were very intuitive, but unfortunately I also experienced a few annoying issues with the viewport navigation itself :

1/ [PROPOSAL] I think it would be of great help when editing a big scene if the viewport navigation behaved a bit more like in Unity, so that the cursor keys move the viewport camera :
- into the direction you are currently facing (fly mode);
- with progressive acceleration until reaching some maximum speed after a few seconds;
- with the possibility to use a higher speed factor using the Control key modifier;
- with the possibility to move vertically relatively to the direction you are facing with the Shift key modifier (or the PageUp/PageDown keys).

2/ [BUG] the values I set for "Default Movement Speed" and "Default Far Plane" in the "Editor Options > Viewport" panel seem to be completely ignored, so I'm left seeing only a very small part of the terrain, and using a much too slow speed while using the cursor keys or the mouse wheel to navigate the scene.

**Comment by stefnotch** [comment]
You can already do a number of those things, it's just that [the controls are a bit different from what you're used to](https://docs.flaxengine.com/manual/editor/windows/viewport.html#controls). 

Regarding the bug report, yep, I can confirm that that happens to me as well.

**Comment by ecstaticcoder** [comment]
Thanks for pointing me out that precise documentation page I was looking for !!!

I can confirm that your viewport navigation ergonomics are indeed very well designed, and actually better than those of Unity once you get used to them :)

I still hope that at some point the options panel values will be used, as not being able to fix the far plane distance remains a problem to me when editing terrain from a distance.

And to be honest with you I had actually googled "flax engine shortcuts" and "flax engine editor shortcuts" as a first step instead of reading the whole documentation from A to Z.

As you see with no success, so I must inform you that at the moment your fantastic documentation still doesn't get Google's interest as it desserves...

**Comment by stefnotch** [comment]
Glad I could help! And yep, I'm also hoping that Google eventually properly indexes the documentation. 

In the editor, when you click on that [`View` widget](https://docs.flaxengine.com/manual/editor/windows/viewport.html#widgets), you can set the far plane. If that doesn't work properly, please open a new issue
