### ISSUE TITLE
Focus issue

### ISSUE THREAD

**Issue by Akira1San** [FlaxEngine/FlaxEngine#441]
**Issue description:**
When focus is centered the orbit is wrong in my opinion. Made a vid:
https://www.youtube.com/watch?v=kdvEdPvPq6I
In the video i show that the blender focus(centered) is correct compared to the Flax one.
Using the Blender focus is more intuitive for workflow.

**Steps to reproduce:**
Select an actor and press F key then use mouse to orbit.

**Flax version:**
Flax 1.1 OS Win 10.

**Comment by stefnotch** [comment]
So, the issue is that the focusing doesn't zoom in?

**Comment by Akira1San** [comment]
The issue is that the orbiting is not centered like in blender. Ones you start moving the mouse, its like in a boat.

**Comment by stefnotch** [comment]
The camera is a 'fly-camera'. If you want to orbit around an object, like in a 3D modeling software, use [`Alt`+`Left Mouse Button`](https://docs.flaxengine.com/manual/editor/windows/viewport.html). I hope that helps :)

**Comment by Akira1San** [comment]
I overlooked that, thx.

**Comment by grace-oh** [comment]
Flycamera
