### ISSUE TITLE
Flax Engine Error: Missing game modules 

### ISSUE THREAD

**Issue by XorbiterGit** [FlaxEngine/FlaxEngine#443]
**Issue description:**
 Tried to open game scene or a new project 
![error](https://user-images.githubusercontent.com/38113433/114281396-723a3800-9a3e-11eb-96b3-e2f45a4b74fa.PNG)
got error: "  cannot load scene without game script mdoule. Please fix the compilation issues

**Steps to reproduce:**

**Minimal reproduction project:**
Recommended as it greatly speeds up debugging. Drag and drop a zip archive to upload it

**Flax version:**
Flax 1.1

**Comment by jb-perrier** [comment]
That's because your scripts ( C# / C++ ) doesn't compile, you can check logs for more info.
