### ISSUE TITLE
Spline disappears with narrow viewport

### ISSUE THREAD

**Issue by stefnotch** [FlaxEngine/FlaxEngine#444]
**Issue description:**
When the editor window is very narrow and tall, the splines sometimes visually disappear

Normal view
![image](https://user-images.githubusercontent.com/10220080/114283760-b2ec7e00-9a4b-11eb-9168-1d702d8cb234.png)

Narrow view (still works)
![image](https://user-images.githubusercontent.com/10220080/114283773-c26bc700-9a4b-11eb-9e59-1f989458fbb9.png)

Even narrower view (breaks)
![image](https://user-images.githubusercontent.com/10220080/114283775-cac40200-9a4b-11eb-9fed-19a28f244f1f.png)

**Steps to reproduce:**
1. Grab https://github.com/stefnotch/anime-rendering-experiments
2. Open it and take a look at the spline
3. Make the editor viewport tall and thin
4. Fly around a bit

This sometimes also reproduces with a normally sized viewport, but that's somewhat tricky to pull off

**Minimal reproduction project:**
https://github.com/stefnotch/anime-rendering-experiments

**Flax version:**
Flax 1.1

**Comment by mafiesto4** [comment]
Probably bug related to culling. Is this spline created from code or from editor?

**Comment by stefnotch** [comment]
From the editor

**Comment by mafiesto4** [comment]
If you're able to reproduce this issue easily then you could copy/paste the spline actor. Maybe that's related to a particular placement of the spline and model (we estimate bounds based on model max bounds deformation over spline).

**Comment by stefnotch** [comment]
Okay, I've been trying to reproduce this for 15 minutes now and am struggling to properly reproduce it... I did manage to do it once or twice initially, but nothing after that. 
I'll close this issue and reopen it when I finally manage to reproduce it properly :)
