### ISSUE TITLE
C# Script: property set of Surface.Material does't work

### ISSUE THREAD

**Issue by freakydude** [FlaxEngine/FlaxEngine#445]
**Issue description:**
Hi Developers,

i tried to set the material of a surface from a BoxBrush by C# Script.
After setting the **material** property, the property is still _null_. 

**Steps to reproduce:**

Code something like: 

```
var main = new BoxBrush();
main.Surfaces[0].Material = material;
var result = main.Surfaces[0].Material;
```

Here is `result == null`
*Expected* `result == material`

Workaround as proposed by @stefnotch : 
```
var main = new BoxBrush();
var surfaces = main.Surfaces;
surfaces[0].Material = null;
main.Surfaces = surfaces;
``` 

That helps until it is fixed. 

**Flax version:**
1.1.6217

**Comment by mafiesto4** [comment]
That's because `BrushSurface` is a value type. Added helper method for material setting easily in 3bfeb1db763d6491c434b72209627cb6ff5998e2
