### ISSUE TITLE
C++ Scripting causes exceptions and crashes

### ISSUE THREAD

**Issue by W2Wizard** [FlaxEngine/FlaxEngine#447]
### Issue description:
Trying to work with C++ results in issues where it crashes the editor and it fails to compile. I've attached the project that causes it.

Theres not much to be said really because everytime I try to compile something regarding C++ I get various exceptions:

**Steps to reproduce:**
#### Crash on first start
1. Open up project
2. Hit play
3. Get the crash.

#### Fail to attach any scripts
1. Before hitting play, press recompile scripts.
2. Try to attach any script
3. Get Exceptions

#### On engine startup:
![image](https://user-images.githubusercontent.com/63303990/114305638-559f0e00-9ad9-11eb-8389-08ba0e1c676c.png)

#### When trying to attach a script:
![image](https://user-images.githubusercontent.com/63303990/114305714-b1699700-9ad9-11eb-8019-07ea45201753.png)

### Minimal reproduction project:
[BrickBuild.zip](https://github.com/FlaxEngine/FlaxEngine/files/6291839/BrickBuild.zip)

### Crash Log & Dump:
[Crash_2021_04_11_15_15_02.zip](https://github.com/FlaxEngine/FlaxEngine/files/6291849/Crash_2021_04_11_15_15_02.zip)

### Flax version:
1.1.6217

**Comment by W2Wizard** [comment]
Ok so it seems like whatever it is, its not reproducible with a source build (at least for me) because when I did that all the issues went away 🤷🏻‍♂️

**Comment by mafiesto4** [comment]
Umm I was unable to reproduce it 😢

**Comment by W2Wizard** [comment]
Then closed it shall stay until maybe by some miracle it happens again
