### ISSUE TITLE
[Discussion] UI Coordinate Spaces

### ISSUE THREAD

**Issue by stefnotch** [FlaxEngine/FlaxEngine#448]
**Feature request/discussion:**
https://discord.com/channels/437989205315158016/437989205315158018/830820806207602748 and above

1. Using pixels could be discouraged in favor of some alternatives
   - e.g. `% of parent`, `% of screen`, `font size`, `normalized size`
   - Reasoning for this is that pixel sizes and screen resolutions are all but consistent
   - We pretty much need fancy layouting algorithms to handle cases like "squares should stay squares"
   - Related: https://gamedev.stackexchange.com/questions/2159/what-coordinate-system-to-use-to-handle-2d-ui
![image](https://user-images.githubusercontent.com/10220080/114310528-445efd00-9aeb-11eb-8eef-68e7b137a961.png)

**Flax version:**
Flax 1.1

**Comment by LCRW** [comment]
Whilst we brushed on this in discord, maybe some sort of brief could be developed here in order for this to work, and be fine-tuned. UI needs an arbitrary pixel space, we need an engine setting for a default resolution, maybe this could be the actual bounds of the pixel space to keep things simpler.

**Comment by honzapatCZ** [comment]
OK you are completely missing the idea of current UI system. I have some PRs that make the UI system more editor friendly like unity. But the concepts are actually in Flax. What are the real problems? 
percentages? use anchors
keep square? now thats a bit of a problem, Iam sure there's some component, but eventually there should be some RootControl wide scaler, where you would specify some UI dimensions and model stuff around that.

**Comment by LCRW** [comment]
@honzapatCZ  This is a discussion on a feature spec, and how it should be implemented, one way is to integrate it in to the existing ui, but that is not the only option here. The UI stack could continue without even knowing about this feature, if required.

**Comment by honzapatCZ** [comment]
> @honzapatCZ This is a discussion on a feature spec, and how it should be implemented, one way is to integrate it in to the existing ui, but that is not the only option here. The UI stack could continue without even knowing about this feature, if required.

Yeyeye I know, we discussed yesterday on discord. I still dont get much of the benefit, but thats up to you.

**Comment by LCRW** [comment]
Ok here is how Unity approaches the problem [https://docs.unity3d.com/Packages/com.unity.ugui@1.0/manual/HOWTO-UIMultiResolution.html#scaling-with-screen-size](url)

**Comment by mafiesto4** [comment]
So we need sth like **Canvas Scaler** I guess but let's make it in-built inside **UI Canvas**.

**Comment by LCRW** [comment]
yeh thats one way, another simpler way i thought of,  was to make screen space configurable, similar to what honza had mentioned before.
Have a UI section in the Graphics settings where you can set a reference resolution for screen space.
Say reference is 1280 x 720.
Screen space in the configured project would then be 1280x720, so ui has a reference to calculated fixed-width.
UI canvas and controls, would continue to store normalized position and size properties as appropriate. When using the editor on those ui components, however imagine something like a UI transform that shows values scaled to the reference resolution. So you have a button that is 1.0 or 100% width. UI Transform would show that as 1280 width or w/e reference resolution is.
Apart from allowing devs to design for resolutions they don't have access to, it could also come in handy for multiple devs working on same project, storing a reference resolution would help standardise the workflow.

**Comment by LCRW** [comment]
[Unreal](https://docs.unrealengine.com/en-US/InteractiveExperiences/UMG/HowTo/ScalingUI/index.html) handles it purely from a DPI perspective.

**Comment by honzapatCZ** [comment]
With the scaling I would like to see something like Min screen size and Max Screen size, where like everything below min would be scaled and above would be scaled, but between it would move according to anchors etc.. this way you could have kinda sreen adapting, where lets say you would define min HD and max FullHD, so let's say would deisgn it for HD and it would be crammed together, then on FullHD it would still be usable, but 4K wouldn't be, so the scaling from FullHD to 4K would kick in.

**Comment by LCRW** [comment]
I was reading [this](https://benui.ca/unreal/ui-resolution/) and it shows good screenshots of things like editor settings in UE4.  
So you would be able to do exactly that by managing a DPI curve, which controls the scaling for individual resolutions. 
The curve also allows for ApplicationScale so you can add user scaling options.

**Comment by honzapatCZ** [comment]
> yeh thats one way, another simpler way i thought of, was to make screen space configurable, similar to what honza had mentioned before.
> Have a UI section in the Graphics settings where you can set a reference resolution for screen space.
> Say reference is 1280 x 720.
> Screen space in the configured project would then be 1280x720, so ui has a reference to calculated fixed-width.
> UI canvas and controls, would continue to store normalized position and size properties as appropriate. When using the editor on those ui components, however imagine something like a UI transform that shows values scaled to the reference resolution. So you have a button that is 1.0 or 100% width. UI Transform would show that as 1280 width or w/e reference resolution is.
> Apart from allowing devs to design for resolutions they don't have access to, it could also come in handy for multiple devs working on same project, storing a reference resolution would help standardise the workflow.

I believe this setting is already in GameSettings

**Comment by mafiesto4** [comment]
Added **Canvas Scaler** control in https://github.com/FlaxEngine/FlaxEngine/commit/d09dfd1f613c007911d999ac398ba82bc228a5df which implements this feature but also adds more functionalities (constant UI scale, DPI-based scaling, etc.). It should be fairly enough to properly scale game UI. I wrote some docs about it too:: https://github.com/FlaxEngine/FlaxDocs/blob/1.5/manual/ui/controls/canvas-scaler.md
