### ISSUE TITLE
[Proposal] VisibleIfAttribute should have counterpart HideIfAttribute instead of invert parameter

### ISSUE THREAD

**Issue by Muchaszewski** [FlaxEngine/FlaxEngine#449]
**Proposal description:**
Instead of having bool "invert" in `VisibleIfAttribute` its counterpart should be `HideIfAttribute`. This would be more obvious from code editor building.

Consider the following code:
```
[VisibleIf(memberName, false)]
public string Foo...
```
vs
```
[HideIf(memberName)]
public string Foo...
```

`HideIfAttribute` would be more in OOP spirit than undescriptive parameter for `VisibleIfAttribute`.

`inverted` can be left for compatibility reasons as well as added to HideIf - if someone choose to use it

**Comment by mafiesto4** [comment]
Would be nice to have. Also, you can use the member name of the property and use custom expression there with negation or any other more cplex checking.

**Comment by honzapatCZ** [comment]
Could this be closed if ShowIf has Invert?
@mafiesto4
