### ISSUE TITLE
Duplicating Splines adds extra keyframes

### ISSUE THREAD

**Issue by stefnotch** [FlaxEngine/FlaxEngine#452]
**Issue description:**
Selecting a spline and hitting `Ctrl`+`D` leads to unexpected results

**Steps to reproduce:**
1. Add a spline (2 keyframes)
2. Select the spline in the scene tree
3. Hit Ctrl+D
4. Move the new spline
5. Look at the number of keyframes that the splines now have

**Flax version:**
Flax 1.1

**Comment by mafiesto4** [comment]
Fixed in 55155630ca8cf422d4eedab5bd62be3a85ec6887
