### ISSUE TITLE
API_EVENT MClass bug

### ISSUE THREAD

**Issue by LCRW** [FlaxEngine/FlaxEngine#459]
**Issue description:**
When using API_EVENT you get a compile error due to missing MClass.h header
The bindings generator fails to add an include for MClass to the Gen.cpp

**Steps to reproduce:**
Try using API_EVENT without adding include to ".../MClass.h".

**Workaround**
add #include <Engine/Scripting/ManagedCLR/MClass.h> to file you define you API_EVENT

**Flax version:**
1.1

**Comment by LCRW** [comment]
I have written a fix for this but i am having issues with my fork so I am just going to post here as its a simple one liner:
Add the following to BindingsGenerator.cpp.cs at line # 1197:
```CppIncludeFiles.Add("Engine/Scripting/ManagedCLR/MClass.h");```

**Comment by mafiesto4** [comment]
Fixed by eabab8301d3c2eaf7dfc18ae8d952ef774192a00,
