### ISSUE TITLE
Tooltip flickering

### ISSUE THREAD

**Issue by W2Wizard** [FlaxEngine/FlaxEngine#460]
**Issue description:**
When hovering over a certain element that displays a tooltip, flickering occurs when you suddenly lose focus such as pressing the windows key and then refocus on the editor.

**Steps to reproduce:**
1. Hover over an element with a tooltip
2. Press the windows key
3. Move the cursors somewhere outside the focused window.

**Examples**

https://user-images.githubusercontent.com/63303990/115061227-30e7d380-9ee9-11eb-88ea-ef3cbedfe709.mp4

https://user-images.githubusercontent.com/63303990/115061235-3513f100-9ee9-11eb-9dea-f747c07c562f.mp4

**Flax version:**
1.1.6217

**Comment by mafiesto4** [comment]
Fixed by #469
