### ISSUE TITLE
what is lfs?

### ISSUE THREAD

**Issue by gituser1024** [FlaxEngine/FlaxEngine#461]
git download uncompleted.

**Comment by stefnotch** [comment]
[Git Large File Storage (LFS)](https://git-lfs.github.com/) is used to store really large files in a repository. 

For example, on GitHub, repositories are limited to ~1 GB for understandable reasons. So, Flax uses Git LFS to store some heavyweight binary files on [its own GitLab server](https://github.com/FlaxEngine/FlaxEngine/blob/master/.lfsconfig).
