### ISSUE TITLE
Protected internal access specifier causes a crash!

### ISSUE THREAD

**Issue by Crawcik** [FlaxEngine/FlaxEngine#473]
**Issue description:**
Protected internal access specifier always crashes during compilation
It crashes in `MMethod.Mono.cpp` file at line `49`
Probably bad flags in switch statement

**Steps to reproduce:**
Set method, property, etc. to protected internal

**Flax version:**
Master branch

**Comment by Crawcik** [comment]
Okay, its caused because it checks for `PROTECTED_AND_INTERNAL`. But in C# keyword `protected internal` means `PROTECTED_OR_INTERNAL`. Also `PROTECTED_AND_INTERNAL` is has no keyword in c#

**Comment by mafiesto4** [comment]
Fixed by #474.
