### ISSUE TITLE
Game wont load if installed into nonstandard named path

### ISSUE THREAD

**Issue by honzapatCZ** [FlaxEngine/FlaxEngine#480]
Problem, the current directory resolving doesnt support unicode-extended characters (eg: í, č, etc...) as a result a lot of people will experience errors trying to load game with Flaxengine, if its downloaded to downlaods in their profile that has their name in it.
eg "C:\Users\Jan Patrovský\Downloads\Game\Mono\lib\mono\4.5\mscorlib.dll" wont resolve correctly and will just silently exit.

**Comment by mafiesto4** [comment]
While engine itself supports UTF-16 all over the place we have problematic libs using pure-ansi `char*`:
* Mono - probably we will need to duplicate `Mono` files into temp directory that has okish path. We do sth similar on Android where we unzip compressed Mono data to be stored in local phone storage for easier access.
* Assimp - importer already can duplicate asset file to import it from temp path

**Comment by mafiesto4** [comment]
Fixed when we switched to .NET 7

**Comment by mafiesto4** [comment]
Actually, I did some tests and fixes some issues in 74a69b8f132fd7591c572dcd63b9aed77568f8d0. Now it works nicely when running game from any Unicode path.
