### ISSUE TITLE
High level overview of the UI

### ISSUE THREAD

**Issue by honzapatCZ** [FlaxEngine/FlaxEngine#481]
@mafiesto4  We need to take a highground look at the ui, its still very unusable.

**Comment by mafiesto4** [comment]
For 1.8 we're made lots of improvements for UI and Editing UIs.

![ui_editor_resizing_widget](https://github.com/FlaxEngine/FlaxEngine/assets/3464853/cbf15e18-f7d8-4036-ae6a-92bebbffcf02)
