### ISSUE TITLE
IBrushEditor doesnt respect VisibleIf Attribute

### ISSUE THREAD

**Issue by honzapatCZ** [FlaxEngine/FlaxEngine#484]
IBrushEditor is handled in a very weird way(not to mention it doesnt support extending it by eg.. querying all implementations of IBrush rather than having a static list). It also doesnt respect the VisibleIf(and probably many other) attribute/attributes.

**Comment by mafiesto4** [comment]
Fixed in 4ad8b8bb19c6cb583e334c362dc848ae2fc6f3d7.
