### ISSUE TITLE
Hierarchy node dragging animation

### ISSUE THREAD

**Issue by honzapatCZ** [FlaxEngine/FlaxEngine#485]
Please turn off the animation of node draggind for 10+ items. It's very annoying to see slowly the nodes moving to their new parent.

**Comment by stefnotch** [comment]
Which nodes are you referring to? There are multiple things that could be called nodes.

**Comment by honzapatCZ** [comment]
The hierarchy nodes, eg actors represented in the Hierarchy panel

**Comment by mafiesto4** [comment]
Fixed in 1.8
