### ISSUE TITLE
Changing scene errors editor window

### ISSUE THREAD

**Issue by honzapatCZ** [FlaxEngine/FlaxEngine#486]
When you change a scene the selected object in editor becomes null which in turns spams your console with errors. Prob. not a thing you want.

**Comment by stefnotch** [comment]
I can't reproduce this, what steps are needed to reproduce?

Basically, I opened a scene, selected an object and then opened a different scene. That works.

**Comment by honzapatCZ** [comment]
> I can't reproduce this, what steps are needed to reproduce?
> 
> Basically, I opened a scene, selected an object and then opened a different scene. That works.

Do it ingame, like select something, than from game unload a scene and load another ano and you will get editor errors

**Comment by mafiesto4** [comment]
Fixed by 4392e07cd64ed62e56edaf0b58f2ba657cba667b.
