### ISSUE TITLE
Prefab error can easily waste hours of your work

### ISSUE THREAD

**Issue by honzapatCZ** [FlaxEngine/FlaxEngine#488]
If an error happens in the serialization/deserialization process the file is saved, but if the error happened it might have like 1/3 of its contents. Not a good thing.

**Comment by stefnotch** [comment]
That sounds super irritating. Any clues regarding how to reproduce this?

**Comment by honzapatCZ** [comment]
> That sounds super irritating. Any clues regarding how to reproduce this?

Just have prefabs with a lot of options. Eg in my case it was UI + couple it with the list editing bug, where it slowly gained size, but that still doesnt justify the destructive workflow. Like I get that the error happens, but why does it save straight afterwards, if it knows it errored out.

**Comment by mafiesto4** [comment]
Prefab data is saved to file at once from already serialized data so the only issue that might cause broken files is when sth wrong happens in-between of synchronizing nested prefabs or prefab instances data sync.
Was it C# exception or C++ native crash or other error? Do you have a log for that (would help)?

**Comment by honzapatCZ** [comment]
2 of my favorite logs, could be one of them:
[Log.txt](https://github.com/FlaxEngine/FlaxEngine/files/6397263/Log.txt)
[Log.txt](https://github.com/FlaxEngine/FlaxEngine/files/6397272/Log.txt)

**Comment by mafiesto4** [comment]
Thanks. It might be related to issue with prefab root object changing (#489).
```
[Warning] Applying prefab changes with modified root object. Root object id: 1b7bb7934e6eb6ba84cab7bbf6c6c3f2, new root: EmptyActor (FlaxEngine.EmptyActor; fce03c7044a887f54d1053923f4de479)
```

**Comment by honzapatCZ** [comment]
> Thanks. It might be related to issue with prefab root object changing (#489).
> 
> ```
> [Warning] Applying prefab changes with modified root object. Root object id: 1b7bb7934e6eb6ba84cab7bbf6c6c3f2, new root: EmptyActor (FlaxEngine.EmptyActor; fce03c7044a887f54d1053923f4de479)
> ```

Then that's a wrong log, Regarding this issue, it happens when
malformed json: it fails to load something, or it parses it just partially  and then resaves it, just the partial thing, which is wrong
or when there's some error(idk how to reproduce it, maybe have a big prefab???) and it just errors out on saving: "Failed to serialize value: "(now something from I think UICanvas like RenderMode) and that just completely breaks the engine, you get an error, crash, or crash on play.

**Comment by mafiesto4** [comment]
Prefabs got more quality and stability last year but of course, there are areas and cases where we can fix/improve usage.

I think it would be better to open separate tracking tickets with specific prefab issues (reproducible).

Also, every known prefab issue should have an automated test added first (that proves it doesn't work) and then be fixed. This helps to maintain stability and ensures that we don't break existing prefab fixes. Example tests for prefabs: https://github.com/FlaxEngine/FlaxEngine/blob/master/Source/Engine/Tests/TestPrefabs.cpp (reparenting prefab objects, adding/removing prefab objects, etc.).
