### ISSUE TITLE
Richtextbox missing documentation and/or use case

### ISSUE THREAD

**Issue by honzapatCZ** [FlaxEngine/FlaxEngine#490]
Title says it all

**Comment by mafiesto4** [comment]
* Add `XML` tags parsing and text formatting including:
  * text color
  * font size
  * font style
  * text underline
  * text shadow
  * text outline
* Add docs

**Comment by mafiesto4** [comment]
Rich Text Box supports HTML tags: https://docs.flaxengine.com/manual/ui/controls/rich-text-box.html
