### ISSUE TITLE
Reimporting texture atlases crashes

### ISSUE THREAD

**Issue by W2Wizard** [FlaxEngine/FlaxEngine#494]
**Issue description:**
I paid dearly finding this bug as reimporting my Atlas texture crashed the engine along with reverting `ALL` my progress inside the asset  once I re-opened the asset.

https://user-images.githubusercontent.com/63303990/116630799-37983100-a954-11eb-938b-7b2b1a800925.mp4

**Steps to reproduce:**
1. Import the atlas texture.
2. Create a few new sprites
3. Save & hit reimport.
4. Crash...

**Minimal reproduction asset:**
`Download this texture atlas`

![IconAtlas](https://user-images.githubusercontent.com/63303990/116630115-f6ebe800-a952-11eb-843d-c2b142c34810.png)

Here are the [Dump & Log](https://cdn.discordapp.com/attachments/538664104856911883/837426400494878820/Crash_2021_04_29_19_47_15.zip)

**Flax version:**
1.1.6217

**Comment by mafiesto4** [comment]
Fixed in 36d06ccaa3c7061724f411386420e045de12a2a7 and 480947e0a98a455f5ef509fcd807f9e95440ab87
