### ISSUE TITLE
Reimporting causes Sprite sections to double

### ISSUE THREAD

**Issue by W2Wizard** [FlaxEngine/FlaxEngine#495]
**Issue description:**
Literally just importing and spamming the Import button magically doubles the sprite sections??

https://user-images.githubusercontent.com/63303990/116631276-05d39a00-a955-11eb-9c94-ce830f4bc460.mp4

**Steps to reproduce:**
1. Download the texture from #494.
2. Import it.
3. Hit Reimport as much as you want.
4. Now you have 2000 Sprite entries.

**Flax version:**
1.1.6217

**Comment by mafiesto4** [comment]
Fixed in 480947e0a98a455f5ef509fcd807f9e95440ab87.
Also, added option to delete sprites, right click on sprite drop down panel header: 94476783dac460e9601122c9b7fc22af12d34fd3
