### ISSUE TITLE
Slider doesn't account for minimum and maximum sizes when smoothly scaling

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#499]
I'm using a limit on the variables for the designer.
![image](https://user-images.githubusercontent.com/35228400/116950588-d2806a80-acc8-11eb-8adf-8212fb6f358d.png)

However, if I use the slider the value jumps instantly between 0 or 2. This isn't very useful and should actually smoothly move between the two. I'm assuming its because the slider doesn't account for minimum and maximum sizes.
![image](https://user-images.githubusercontent.com/35228400/116950628-ef1ca280-acc8-11eb-8375-568f570a874a.png)

**Flax version:**
Flax 1.1

**Comment by mafiesto4** [comment]
Fixed in rev 2dff188eac9d260337a73a2d6ec4b129442830a0
