### ISSUE TITLE
Foliage is unpaintable on highterrain

### ISSUE THREAD

**Issue by MeshVoid** [FlaxEngine/FlaxEngine#5]
**Issue description:**

Hi! Congratulations on your launch! Foliage is unpaintable on high terrain. For some reason, foliage is not being placed on terrain that has some height. Also, already placed foliage doesn't adapt to terrain changes.

**Steps to reproduce:**

Bug 1: Foliage is unpaintable on high terrain.

1 - Open any project
2 - Create terrain
3 - create basic foliage brush with any model, say, a capsule
4 - make some hills, slopes, and etc in terrain editor using sculpt tools
5 - paint foliage on highground
6 - foliage will not be placed.

Bug 2: Foliage is unpaintable on high terrain.

1 - Enter sculpt mode in terrain
2 - change height values underneath already placed foliage.
3 - see that foliage won't move, it will remain there.

**Minimal reproduction project:**
None, reproducible in any empty project.

**Flax version:**

Flax version 1.0

**Comment by W2Wizard** [comment]
Bit of an old issue thats been sitting on the backburner for too long, the main issue is that in this line:
https://github.com/FlaxEngine/FlaxEngine/blob/d27edbf5a901c0ddea1458dd0e788c335a9a9dc4/Source/Editor/Tools/Foliage/FoliageTools.cpp#L223

Triangles count is 0 when painting on elevated terrain.
