### ISSUE TITLE
Dragging multiple instances of the same Prefab into the scene results in them all having exactly the same name

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#501]
Dragging multiple instances of the same Prefab into the scene results in them all having exactly the same name. This makes it difficult to identify them. I recommend a number such as (1) then (2) be postfixed.

You can see that in action here:
https://user-images.githubusercontent.com/35228400/116951098-5f77f380-acca-11eb-957c-6c0b84474782.mp4

**Flax version:**
1.1

**Comment by mafiesto4** [comment]
Fixed in rev 401bd1c1257373027767bb4715127324abfa4a4b
