### ISSUE TITLE
In-game VSync can't be turned off

### ISSUE THREAD

**Issue by michalzembron** [FlaxEngine/FlaxEngine#503]
**Issue description:**
VSync is always turned on, disabling it through "Graphics Settings" in the editor or in standalone game by "Graphics.UseVSync = false;" doesn't work.

**Minimal reproduction project:**
Any project.

**Flax version:**
1.1.6218

**Comment by mafiesto4** [comment]
I tested it and VSync disabling works. The problem you might have is that VSync was disabled but the game FPS was limited by **Time Settings**. If you change Draw/Update/FixedUpdate FPS to 0 it will go unlimited:

![image](https://user-images.githubusercontent.com/3464853/118249464-bf7a5100-b4a5-11eb-8f88-9cc5ee871521.png)

Docs: <https://docs.flaxengine.com/manual/editor/game-settings/time-settings.html>

**Comment by michalzembron** [comment]
Yes, finally ! I don't know why I didn't checked in the docs nor in the other settings besides Graphics, Physics and Windows Settings, thanks ! 😄
