### ISSUE TITLE
Debugging headless mode OnStart() is unreliable/broken (Windows/Rider)

### ISSUE THREAD

**Issue by herocrab** [FlaxEngine/FlaxEngine#509]
**Issue description:**
~~Running a game on Windows in headless mode does not appear to work. I run a game in normal mode, "everything works," I add the headless flag and run the game and it appears that no scripts are started (OnStart()).~~ [Edit] It seems that mono debugger is not able to reliable connect or debug headless games.

https://docs.flaxengine.com/manual/editor/advanced/command-line-access.html

**Steps to reproduce:**
1) Create a project.
2) Run the game using command-line options of -headless, specify the debugger port "-debug 127.0.0.1:50000"
3) Attempt to debug the game by inserting a break point.

**Flax version:**
1.1

**Comment by herocrab** [comment]
Looking into this further, I've seen it work once in headless mode. It's not clear to me what the issue is. If I launch the debugger and run the game in normal mode my breakpoints are hit reliably. If I launch the debugger and run the game in headless mode my breakpoints are not hit.

**Comment by mafiesto4** [comment]
It works pretty fine for me.

My workflow:
1) Setup game project with C# scripts
2) Cook game (in Development)
3) Run `.\FlaxGame.exe -headless -debug 127.0.0.1:50000`
4) Set configuration in Visual Studio to **Game.Debug** | **Win64**
5) Open **Tools -> Attach To Flax** and enter the same debugger address (`127.0.0.1:50000`)
6) Breakpoint hit

Did you go the same way or sth different?

**Comment by herocrab** [comment]
I’m using the same approach but with Rider. I will try with Game.Debug, but with whatever the default method was it was only hitting break points very infrequently.

**Comment by herocrab** [comment]
@mafiesto4 I created a new project, disabled Godot and Unity plugins and tested this approach with Rider.

What I am seeing may be related to another bug or an order of operations issue, when I opened this issue I was only attempting to break point inside OnStart(). This does not reliably work for me.

However if I break point inside FixedUpdate() the break is hit reliably. 

Is it possible the debugger is not connected before OnStart() is called? I am even launching the debugger before hand.

Any recommendations on how to reliably debug OnStart()?

**Comment by herocrab** [comment]
Closing this issue, the initial OnStart can be captured by delaying scripts until the debugger is connected.

**Comment by mafiesto4** [comment]
So it's  caused by `OnStart` being called before the debugger gets attached.
The solution could be to add `suspend=y,timeout=3000` into `--debugger-agent=` options:

https://github.com/FlaxEngine/FlaxEngine/blob/5745e4e522745a719d4a7f7c2b1db02d1239a5db/Source/Engine/Scripting/ManagedCLR/MCore.Mono.cpp#L425-L433

**Comment by mafiesto4** [comment]
@W2Wizard I implemented it here: <https://github.com/FlaxEngine/FlaxEngine/commit/16e67780adfd84737a4337210f014d6b6ee526d6>. So running engine with `-debugwait` cmd line will make it wait up to 5s for the debugger to attach.

**Comment by herocrab** [comment]
Wow! Thanks! You are very responsive.
