### ISSUE TITLE
Debug stack trace

### ISSUE THREAD

**Issue by Muchaszewski** [FlaxEngine/FlaxEngine#51]
**Proposal description:**
Debug Log, Error, Warninge etc. should always have stack trace to find stray logs.

Possible resolutions:
1. Debug should have full stack trace
 + Very nice/Usefull
 + Verbose

 - Slow
 - Use a a lot of memory
 - Make a bloat in log file

2. Debug should have name of the namespace::Class.Method + line nubmer or File name + line number
 + Clean
 + Fast
 + Usefull
 + Small size

 - Still might be thought to identify in edge cases
 - Doesn't provide context (sometimes required, but one can add it themselves)

**Comment by mafiesto4** [comment]
Now Debug Log entries contain stack trace and can be copies/opened (with double-click, right-click or via keyboard).

![image](https://user-images.githubusercontent.com/3464853/109304354-6e5ea780-783c-11eb-9b6e-1d11bf16fde5.png)

It works also when calling `DebugLog::*` from C++ script:

![image](https://user-images.githubusercontent.com/3464853/109304497-abc33500-783c-11eb-9c3b-37bff1cf1a6b.png)
