### ISSUE TITLE
!!!Cant load game!!!(even Editor in some cases)

### ISSUE THREAD

**Issue by honzapatCZ** [FlaxEngine/FlaxEngine#510]
Built game wont load, Graphics initialization error.

[Log.txt](https://github.com/FlaxEngine/FlaxEngine/files/6437805/Log.txt)
[Minidump.zip](https://github.com/FlaxEngine/FlaxEngine/files/6437808/Minidump.zip)

**Comment by jb-perrier** [comment]
I have the same issue, i'm investigating this.

**Comment by demainn** [comment]
I have the same error but when opening a project. Occurs when the folder "ProjectName\Cache\Shaders" does not exist. It can even be empty for the project to work properly. But it could be another bug. Should I add this as a new issue?

**Comment by jb-perrier** [comment]
Well for some reason, i can't reproduce the issue.

**Comment by honzapatCZ** [comment]
> Well for some reason, i can't reproduce the issue.
> Can you all check if the project folder is not in Read Only ?

Take master branch and create a project -> fail
Take old project use master branch and remove Cache -> fail

**Comment by mafiesto4** [comment]
Fixed in a8f0035b8bfcc5cec42ff7fbecb9bd08c29b4278.
