### ISSUE TITLE
Saving Localization Settings with empty Localized String Table element results in a crash

### ISSUE THREAD

**Issue by demainn** [FlaxEngine/FlaxEngine#514]
**Issue description:**
Saving Localization Settings with empty Localized String Table element results in a crash
Log:  [Log.txt](https://github.com/FlaxEngine/FlaxEngine/files/6453940/Log.txt)

![crash1](https://user-images.githubusercontent.com/60449247/117701522-a03ea380-b1c7-11eb-8e1d-7e24fa8085b2.png)

![crash2](https://user-images.githubusercontent.com/60449247/117700569-7cc72900-b1c6-11eb-86c2-8abd33987dfe.png)

**Steps to reproduce:**

1. Create Localization Settings
2. Add new Element under "Localized String Tables" (don't select any asset)
3. Save settings

**Flax version:**
1.1

**Comment by mafiesto4** [comment]
Fixed in 0509f9710f9e9d463e583e9fa621ad2c03ba53b2.
