### ISSUE TITLE
Can't load project if folder "ProjectName\Cache\Shaders" does not exist.

### ISSUE THREAD

**Issue by demainn** [FlaxEngine/FlaxEngine#516]
**Issue description:**
"Failed to initialize Graphics" error occurs when trying to load project, which doesn't have folder with path "ProjectName/Cache/Shaders".

**Steps to reproduce:**
1. Create a new empty project or use an existing one.
2. Ensure "ProjectName/Cache/Shaders" folder does not exist.
3. Open a project.

To make the project work again, create an empty folder with the same path.

**Flax version:**
1.1 (current master branch)

**Comment by jb-perrier** [comment]
Duplicate #510 .

**Comment by LCRW** [comment]
If your cache doesn't exist, you need to right click the flaxproj and Generate Project files, or use the option in the editor to rebuild the cache. This works with no cachae folder at all.

**Comment by mafiesto4** [comment]
Fixed in a8f0035b8bfcc5cec42ff7fbecb9bd08c29b4278.
