### ISSUE TITLE
Text doesn't fit Labels correctly

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#518]
There seems to be a strange issue going on with Labels and possibly fonts.

Basically, the **Auto Width** and **Auto Height** aren't measuring the size of the label text correctly. This results in the label wrapping in a weird way. Setting the Margin to 0 for all sides doesn't help either. This issue is really annoying as the box scales but is always is one character too small.

You can see a video of the effect here:
https://user-images.githubusercontent.com/35228400/118080891-e3825780-b3fd-11eb-8668-2efef99763a9.mp4

**Flax version:**
Master Github

**Comment by mafiesto4** [comment]
The issue was reproduceable when using `TextWrapping.WrapChars`. Fixed in b2ecceab441d7d5d0cff1ed6b958a20a8ddc4b48.
