### ISSUE TITLE
Nested Editor Rendering Issue

### ISSUE THREAD

**Issue by stefnotch** [FlaxEngine/FlaxEngine#52]
**Issue description:**

I tried out nested List editors `List<List<string>>` in the process of trying to improve the current Dictionary editors and stumbled upon a bug where a duplicated label will jump into the child.

**Steps to reproduce:**
1) Add a script with a nested list

```csharp
[ExecuteInEditMode]
public class Script0 : Script
{
	[NoSerialize]
	public List<List<string>> AList = new List<List<string>>();

	private void Start()
	{
		AList.Add(new List<string> { "Flux", "Bear", "Qux" });
		AList.Add(new List<string> { "Press on", "my add", "button" });
	}
}
```
2) Click on the add button of a child

![2019-05-31_22-43-20](https://user-images.githubusercontent.com/10220080/58733720-974ad200-83f5-11e9-912c-cb62f0b0a584.gif)

**Minimal reproduction project:**

[NestedEditors.zip](https://github.com/FlaxEngine/FlaxAPI/files/3242806/NestedEditors.zip)

**Flax version:**

0.4.6181

**Comment by mafiesto4** [comment]
Does #542 helped with this issue?

**Comment by stefnotch** [comment]
Works beautifully now 🥳
