### ISSUE TITLE
Snapping snaps based on origin and not bounding box

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#522]
Pressing the "End" key will snap an object to the ground. However, it currently snaps the object to the ground based on its origin. This isn't really that useful. It should snap based on the objects bounding box. This is how UE4 works.

Here is a video of this:

https://user-images.githubusercontent.com/35228400/118397520-b7820300-b697-11eb-939d-2a1326eb5957.mp4

Suggest that pressing "end" snap the object to the ground based on bounding box and not origin.

**Flax version:**
Master

**Comment by mafiesto4** [comment]
Fixed in d11166082c566809c474ac4a4ef347689df38bc1 and 63c9cdfc31fae9fb81fc14998e0096991f99f9cd
