### ISSUE TITLE
In orthographic top down view Z-axis movement tool is broken

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#530]
**Issue description:**
Please see this attached video for what I mean:
https://user-images.githubusercontent.com/35228400/119419264-40a2d500-bd3d-11eb-88aa-06f411d1818f.mp4

**Flax version:**
Master Branch

**Comment by mafiesto4** [comment]
Fixed in 969db604e5ff6b4ccdafaabf3d17bb3ab11e7698. Using single gizmo axis should be more stable now.
