### ISSUE TITLE
Changing between Perspective and Orthographic and Top View etc in Editor is a mess

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#531]
**Issue description:**
Currently when you change views is a mess as you're always teleported back to the center of the world which makes changing views a massive waste of time. Please see this video to understand the issue:
https://user-images.githubusercontent.com/35228400/119419723-3d5c1900-bd3e-11eb-965d-c51879e52602.mp4

**Flax version:**
Master Branch

**Comment by jb-perrier** [comment]
Strange, the code is supposed to keep the camera focused on the selected object. Will check that today.

**Comment by mafiesto4** [comment]
Fixed in 29860b838eb46086b8eadbaf97c6b37377688b36.
