### ISSUE TITLE
Free Camera Speed Setting is forgotten after you close the Prefab

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#536]
Free Camera Speed Setting is forgotten after you close the Prefab. It always just resets to 1 which is annoying when jumping between multiple Prefabs
![image](https://user-images.githubusercontent.com/35228400/119747155-72e73a80-bed5-11eb-884c-59d95bd2c433.png)

**Flax version:**
Master Branch

**Comment by mafiesto4** [comment]
You can change the default speed in **Tools** -> **Options** -> **Viewport** -> **Default Movement Speed**. Eg. set it to `4` so it will be used when opening prefabs. You can also use mouse wheel to quickly adjust the speed of the camera movement.
