### ISSUE TITLE
Weird lighting with Normals in Flax

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#541]
We have this weird issue in Flax where the normal map is causing the hair on our characters to create weird reflections:
![image](https://user-images.githubusercontent.com/35228400/120272394-61949880-c2f0-11eb-8ae5-ed4df43f6523.png)

We thought maybe it was the normal map so we tried both one made for OpenGL and one made for DirectX and the issue persists.

We then loaded the exact same model into Unreal Engine and Flax to cross compare and its clear that something weird is happening with the normals / lightning. I've tried adjusting the light seeings and rotate the sun and nothing seems to stop this weird issue.
![image](https://user-images.githubusercontent.com/35228400/120272452-77a25900-c2f0-11eb-8bf6-896bac3b4223.png)
![image](https://user-images.githubusercontent.com/35228400/120272875-16c75080-c2f1-11eb-8224-069715a5b308.png)

As you can imagine this is driving my artists insane.

Model and Textures:
[HairModelAndTextures.zip](https://github.com/FlaxEngine/FlaxEngine/files/6573681/HairModelAndTextures.zip)

**Flax version:**
Master

**Comment by artkez** [comment]
Have you set the texture type to "Normal Map"? I get the same result when it is set to "Grayscale":
![image](https://user-images.githubusercontent.com/33177434/120293821-49138680-c2ce-11eb-99ae-524356d5f6aa.png)

![image](https://user-images.githubusercontent.com/33177434/120293942-63e5fb00-c2ce-11eb-872b-790f42883e07.png)

**Comment by mafiesto4** [comment]
Yeah using it as Normal Map helps. 

![image](https://user-images.githubusercontent.com/3464853/120305701-5d0cb780-c2d1-11eb-8d89-e0e9c6446c27.png)

Flax Editor has some auto-detection for texture type on import based on filename but it uses postfix to detect texture type.

https://github.com/FlaxEngine/FlaxEngine/blob/8a942922fedf371453879f2d8f5ff383e0e335b8/Source/Editor/Content/Import/TextureImportEntry.cs#L428-L437

**Comment by Evildea** [comment]
Yes, we are setting it as a normal map.

**Comment by Evildea** [comment]
Ok, here is a screenshot of my setup:
![image](https://user-images.githubusercontent.com/35228400/120320722-d635fa00-c325-11eb-9761-f64d0ab5b9d7.png)

**Comment by mafiesto4** [comment]
Try wit `Normal Map` node instead of `Texture` node when sampling that normal map in a material.

**Comment by Evildea** [comment]
Ok, now I feel like an idiot. I used the normal node correctly for every other texture but some how just totally missed it for the hair >.< Sorry for wasting your time!
