### ISSUE TITLE
UWP Type not registered(prob name mismatch)

### ISSUE THREAD

**Issue by honzapatCZ** [FlaxEngine/FlaxEngine#543]
Ok Iam iterating on the UWP bug
so it seems that for 
FlaxEngine.winmd there isnt an implementation.(thats said in the message)
so idk, prob some naming issue
Btw just tried it with Flax Sample so its not my retardet code

TLDR:
Error at line 23 in App.cs

**Comment by honzapatCZ** [comment]
Just adding to this problem, this happens when you try to package for store:
`ILTransform : warning ILT0010: Could not find assembly 'System.ComponentModel.TypeConverter, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' referenced by 'FlaxEngine.CSharp'.`

**Comment by mafiesto4** [comment]
UWP platform is now deprecated. We use GDK for Xbox native support now.
