### ISSUE TITLE
Set as Root broken

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#544]
Maybe the same issue as this ticket: https://github.com/FlaxEngine/FlaxEngine/issues/489

**Issue description:**
When setting the root and saving, nothing actually updates. You can see that here in this video:
https://user-images.githubusercontent.com/35228400/120568871-23b28400-c458-11eb-9522-caa98f0c4931.mp4

**Flax version:**
Master Branch

**Comment by honzapatCZ** [comment]
Yes, thats basically it.

**Comment by mafiesto4** [comment]
I fixed this feature and made it more reliable 7fc3e65849bfa9bb88510b831ee4ba8bf0e30c15. Reopen this ticket if occurs again (on latest master or in the next engine update `1.2`).
