### ISSUE TITLE
Crashes on loading scenes

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#545]
No sure if this is a bug or intentional?

The following code works fine:
```
Level.UnloadSceneAsync(Scene);
Level.LoadSceneAsync(LevelToOpen.ID);
```

The following code crashes the engine:
```
Level.UnloadScene(Scene);
Level.LoadScene(LevelToOpen.ID);
```
![image](https://user-images.githubusercontent.com/35228400/120570820-4a72b980-c45c-11eb-8291-d963cec580de.png)

**Flax version:**
Master Branch

**Comment by mafiesto4** [comment]
Probably fixed some time ago, cannot reproduce it anymore.
