### ISSUE TITLE
Copied script reference turns into null

### ISSUE THREAD

**Issue by stefnotch** [FlaxEngine/FlaxEngine#55]
**Issue description:**

I was playing around with copy-pasting actors and stumbled upon a case where a script reference turns into null.
![image](https://user-images.githubusercontent.com/10220080/73830154-72b8bc80-4804-11ea-86a7-b36af11cde10.png)

**Steps to reproduce:**

1. Attach the script to an actor
2. Manually set the references in the editor
3. Duplicate the actor
4. The reference inside the object will end up being null.
```csharp
public class SerializePlez : Script
{
    public class HoldsAScriptReference
    {
        public SerializePlez ScriptReference { get; set; }
    }

    public HoldsAScriptReference ReferenceHolder { get; set; } = new HoldsAScriptReference();

    public SerializePlez SelfReference { get; set; }
}
```

**Minimal reproduction project:**

**Flax version:**

**Comment by mafiesto4** [comment]
Fixed in c47907c0c305944b64fdc7120eadd54a0e261d10
