### ISSUE TITLE
Suggestion: A way to reorder lists

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#551]
**Issue description:**
We need a way to reorder things in a list. Currently, there is no way to do this so if you need to reorder something after creating it, you basically need to delete many entries. If there is a Flax way of doing this then I'm not sure what it is. Current code for this list is:

`public List<MenuItem> Fields = new List<MenuItem>();`

![image](https://user-images.githubusercontent.com/35228400/121983647-0032f600-cdd5-11eb-88b0-763df8dac4be.png)

**Flax version:**
Master Branch

**Comment by mafiesto4** [comment]
You can right-click on an item label to use contextual actions:
![image](https://user-images.githubusercontent.com/3464853/122010944-e76a1680-cdbb-11eb-9cc5-0b5d74a1e2f0.png)

**Comment by Evildea** [comment]
Oh! I didn't even realize this. Maybe we need to think up ways to make this more obvious for idiots like me. Anyways, this sorts out my issue.
