### ISSUE TITLE
GUI Material display a little off-center

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#552]
**Issue description:**
GUI Material display seems a little wonky. Basically it seems to have been shoved into the bottom left corner.
![image](https://user-images.githubusercontent.com/35228400/122147884-1310fd80-ce9d-11eb-89f0-c0a9cd9d738f.png)

**Flax version:**
Master Branch

**Comment by mafiesto4** [comment]
Fixed in f1b3f71b097bb718b8961f3aafb98548bae098cc.
