### ISSUE TITLE
GUI material flicker effect

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#553]
**Issue description:**
When turning parameters on and off, the GUI flickers a bit:
https://user-images.githubusercontent.com/35228400/122149222-14432a00-ce9f-11eb-8dfd-d0eb5a795823.mp4

Obviously not world ending but figured you guys would want to know about it.

**Flax version:**
Master Branch

**Comment by mafiesto4** [comment]
That's because the editor generates the shader source code that is later compiled and the material gets reloaded. I would say it's rather fast (0.1s - 0.5s) but for parameters tweaking, we could add an additional `Preview` tab just like AnimGraph editor does.
