### ISSUE TITLE
Visual Studio 2019 compile error

### ISSUE THREAD

**Issue by Alad53** [FlaxEngine/FlaxEngine#554]
GetMSBuildPath:

```
@echo off

rem Copyright (c) 2012-2020 Wojciech Figat. All rights reserved.

**set MSBUILD_PATH="C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe"**

if not exist "%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" goto VsWhereNotFound
for /f "delims=" %%i in ('"%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere" -latest -products * -requires Microsoft.Component.MSBuild -property installationPath') do (
	if exist "%%i\MSBuild\15.0\Bin\MSBuild.exe" (
		set MSBUILD_PATH="%%i\MSBuild\15.0\Bin\MSBuild.exe"
		goto End
	)
)
:VsWhereNotFound

if exist "%ProgramFiles(x86)%\MSBuild\14.0\bin\MSBuild.exe" (
	set MSBUILD_PATH="%ProgramFiles(x86)%\MSBuild\14.0\bin\MSBuild.exe"
	goto End
)

call :GetInstallPath Microsoft\VisualStudio\SxS\VS7 15.0 MSBuild\15.0\bin\MSBuild.exe
if not errorlevel 1 goto End
call :GetInstallPath Microsoft\MSBuild\ToolsVersions\14.0 MSBuildToolsPath MSBuild.exe
if not errorlevel 1 goto End
call :GetInstallPath Microsoft\MSBuild\ToolsVersions\12.0 MSBuildToolsPath MSBuild.exe
if not errorlevel 1 goto End
call :GetInstallPath Microsoft\MSBuild\ToolsVersions\4.0 MSBuildToolsPath MSBuild.exe
if not errorlevel 1 goto End

exit /B 1
:End
exit /B 0

:GetInstallPath
for /f "tokens=2,*" %%A in ('REG.exe query HKCU\SOFTWARE\%1 /v %2 2^>Nul') do (
	if exist "%%B%%3" (
		set MSBUILD_PATH="%%B%3"
		exit /B 0
	)
)
for /f "tokens=2,*" %%A in ('REG.exe query HKLM\SOFTWARE\%1 /v %2 2^>Nul') do (
	if exist "%%B%3" (
		set MSBUILD_PATH="%%B%3"
		exit /B 0
	)
)
for /f "tokens=2,*" %%A in ('REG.exe query HKCU\SOFTWARE\Wow6432Node\%1 /v %2 2^>Nul') do (
	if exist "%%B%%3" (
		set MSBUILD_PATH="%%B%3"
		exit /B 0
	)
)
for /f "tokens=2,*" %%A in ('REG.exe query HKLM\SOFTWARE\Wow6432Node\%1 /v %2 2^>Nul') do (
	if exist "%%B%3" (
		set MSBUILD_PATH="%%B%3"
		exit /B 0
	)
)
exit /B 1
```

Project Settings:

![w](https://user-images.githubusercontent.com/86076716/122455771-6eceaa00-cfb5-11eb-8eac-f478394a4eaa.JPG)

Errors:

![2](https://user-images.githubusercontent.com/86076716/122455857-8ad24b80-cfb5-11eb-88cb-1237af26bb9f.JPG)
![5](https://user-images.githubusercontent.com/86076716/122455943-a178a280-cfb5-11eb-921e-589508e49d28.JPG)

**Comment by mafiesto4** [comment]
We don't use `msbuild` but our own `Flax.Build` (it generates files based on C++ API with missing types from that errors).
See install instructions: https://github.com/FlaxEngine/FlaxEngine#windows
* Run GenerateProjectFiles.bat
* Open Flax.sln and set solution configuration to Editor.Development and solution platform to Win64
* Build Flax project
* Set Flax (C++) or FlaxEngine (C#) as startup project

**Comment by GoaLitiuM** [comment]
Having wrong configuration set in VS script solution is often causing these weird errors, make sure it's set to any Editor.* or Game.* configurations instead of Debug or Release.

**Comment by Alad53** [comment]
I did what you said but a new problem came up.

Project Settings:

![345](https://user-images.githubusercontent.com/86076716/122475827-e4467480-cfcd-11eb-9e89-58ab24844dd0.JPG)


Error: 

![44](https://user-images.githubusercontent.com/86076716/122475763-cf69e100-cfcd-11eb-9d91-a342f9721a03.JPG)

**Comment by Alad53** [comment]
++

![we3](https://user-images.githubusercontent.com/86076716/122579339-7b0e4200-d05d-11eb-999a-439c283b6efb.png)
![we3](https://user-images.githubusercontent.com/86076716/122579438-937e5c80-d05d-11eb-8612-43b34fd7baed.png)

Settings
![34](https://user-images.githubusercontent.com/86076716/122579629-c32d6480-d05d-11eb-85c5-8b3cc589eacc.JPG)
![3245](https://user-images.githubusercontent.com/86076716/122579704-d9d3bb80-d05d-11eb-8ea0-4525c4d28616.JPG)

**Comment by mafiesto4** [comment]
You can build manually with cmd line:
```
.\Development\Scripts\Windows\CallBuildTool.bat -build -log -arch=x64 -platform=Windows -configuration=Development -buildtargets=FlaxEditor
```
just like CI does on Gitbug Actions:
https://github.com/FlaxEngine/FlaxEngine/runs/2859367141?check_suite_focus=true

**Comment by Alad53** [comment]
Hi @mafiesto4,

![3](https://user-images.githubusercontent.com/86076716/122591605-da734e80-d06b-11eb-8086-ae1bcb1f2db6.png)

![43](https://user-images.githubusercontent.com/86076716/122591747-13132800-d06c-11eb-9e0e-db32b3519f86.png)

![365](https://user-images.githubusercontent.com/86076716/122591864-3dfd7c00-d06c-11eb-8993-ee09c75331fd.png)

**Comment by mafiesto4** [comment]
Wow this looks very strange 👀 Did you cloned repo with Git LFS? Do you have proper read/write permissions to the repo folder so the build can go through? You could send the build tool log that could help to identify the problem from `<repo>\Cache\Intermediate\Log.txt`.

**Comment by Alad53** [comment]
@mafiesto4,

Yes I downloaded using "LFS" and it has write and read permission

[Log.txt](https://github.com/FlaxEngine/FlaxEngine/files/6678860/Log.txt)

**Comment by mafiesto4** [comment]
Okay this log helped, I think the problem might be with language locale on your system that breaks the string comparisions in some places in a build tool.
Does this fixed the problem: bf1a30c5c6930f6f773f6d2f9d2a813eb053fce4? Try current `master`.

**Comment by Alad53** [comment]
Solved thank you! @mafiesto4,

When the Flax editor opens, it tells me to open a project. How can I create a new project?
![dsa](https://user-images.githubusercontent.com/86076716/122614956-4c5d8f00-d090-11eb-9abb-e853bd81b317.JPG)

**Comment by mafiesto4** [comment]
You can use Flax Samples:
https://github.com/FlaxEngine/FlaxSamples
or use Flax Launcher to create new projects:
https://flaxengine.com/download/
