### ISSUE TITLE
FlaxVS plugin should be optional

### ISSUE THREAD

**Issue by GoaLitiuM** [FlaxEngine/FlaxEngine#556]
Currently the FlaxEditor project does not open without this extension present, I get this following error when attempting to open the solution file in Visual Studio:
![image](https://user-images.githubusercontent.com/4064397/122775579-f288df00-d2b2-11eb-8c54-b477b9a27964.png)

This can be worked around by removing the `{BE633490-FBA4-41EB-80D4-EFA312592B8E}` ProjectTypeGuid from FlaxEngine.csproj, but this shouldn't be needed for compilation or browsing the code.

**Comment by mafiesto4** [comment]
It is optional as `Flax.Build` skips this custom GUID if `Flax.VS` is not installed. See:
https://github.com/FlaxEngine/FlaxEngine/blob/ef831b855966b9a4df6a3cd7d1b098a87b53d17c/Source/Tools/Flax.Build/Projects/VisualStudio/VisualStudioInstance.cs#L33-L47
Maybe it was incorrectly detected after uninstall or you need to regenerate project files after change?

**Comment by GoaLitiuM** [comment]
No, Visual Studio itself does not know what to do with the unknown GUID without the plugin, so the project remains unloaded in the solution.

**Comment by GoaLitiuM** [comment]
I was trying out the new Visual Studio 2022 which doesn't have the plugin supported. I wasn't aware of this detection code at all. It doesn't account for the fact that user could be opening the solution in another version of VS which doesn't have the plugin installed but some other installation may have it.

**Comment by mafiesto4** [comment]
As we've migrated to .NET 7, `Flax.VS` extension is not unused (in-built dotnet debugger is better and works with the latest C#).
