### ISSUE TITLE
Setting Blur Panel to a high value causes an engine crash

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#558]
**Issue description:**
Setting the blur panel to a value of 50 causes the engine to crash.
![image](https://user-images.githubusercontent.com/35228400/122861479-e5c3c400-d362-11eb-9493-dde62b5fc38c.png)

**Flax version:**
Master

**Comment by mafiesto4** [comment]
Fixed in 72599b18ce03d6d6e003413724e2d28b3d873a49.
Although the blur darkens the image with very large strength, not sure if it's an another bug or just thing of using Gaussian Blur there.
