### ISSUE TITLE
UI Bug with IsActive

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#559]
**Issue description:**
Seems to be a bug with the **IsActive** in the Prefab view. See the video below. Basically, when turning isActive off and then back on the UI isn't redrawn.
https://user-images.githubusercontent.com/35228400/123040729-8f748500-d437-11eb-8949-84cabd685012.mp4

**Flax version:**
Master Branch

**Comment by mafiesto4** [comment]
Fixed in c4fc7b7e5dd562f4632aa4f9813118ac7021ab0d.
