### ISSUE TITLE
Weird animations blending with "Multi Blend 2D"

### ISSUE THREAD

**Issue by artkez** [FlaxEngine/FlaxEngine#561]
![image](https://user-images.githubusercontent.com/33177434/123541986-c99f9880-d74f-11eb-86b0-a9830f1d9c18.png)
![image](https://user-images.githubusercontent.com/33177434/123541994-d3c19700-d74f-11eb-9cd0-4e8fbeccbaaf.png)
Hey.
I've setup a simple Flax project for reproducing, just run it and hold movement keys (WASD) in Game Mode.
[AnimsBlending.zip](https://github.com/FlaxEngine/FlaxEngine/files/6721448/AnimsBlending.zip)

**Comment by mafiesto4** [comment]
Thanks for reporting this and providing the sample project. Fixed in 9e3d7cbbc9fe23c126ceea4c4bf452b130969c6d.

https://user-images.githubusercontent.com/3464853/124111340-78521a80-da69-11eb-89d6-be1599096764.mp4

**Comment by artkez** [comment]
Niiiice!
