### ISSUE TITLE
Incorrect normal map shading of the Terrain

### ISSUE THREAD

**Issue by NordonOscillius** [FlaxEngine/FlaxEngine#562]
**Issue description:**

Normal map used in a terrain material affects shading in an incorrect way. The "brightness - darkness" relief picture doesn't correspond to light orientation relative to the surface of the terrain.

**Steps to reproduce:**

1. (Optional) Create a new scene in the editor and delete/disable the Floor actor.
2. Create a new Terrain with default settings (Main Menu -> Scene -> Create terrain -> Create).
3. Make sure that the following actors are present in the scene:
3.1. The Sky actor called "Sky" (if it's not present, create one).
3.2. The DirectionalLight actor called "Sun" (if it's not present, create one).
4. Make sure that Sky actor's Sun Light setting references the Sun actor (select Sky actor -> go to Inspector -> Sun section -> Sun Light; it should be set to "Sun (DirectionalLight)"). If it doesn't, set this setting to the Sun DirectionalLight.
5. (Optional) Create and setup a reference cube to better see the issue.
5.1. Create a new Cube (Toolbox -> Basic Models -> Cube; drag it into the viewport).
5.2. Set Cube Position to (500, 0, 500) in the Inspector.
5.3. Set Cube Scale to (4, 4, 4) in the Inspector.
5.4. Navigate in the viewport so that Terrain, Cube and Sun actors were visible at the same time.
6. Make sure that no material is assigned to Terrain so that it uses default terrain material (select Terrain actor -> go to Inspector -> Terrain section -> Material setting; it should be set to "No asset selected"). Now the Cube actor (if it has been created) uses the default material with the same normal map as that of the default terrain material.
7. Select the Sun DirectionalLight and set its Rotation to (10, 0, 0).
8. Rotate the Sun DirectionalLight around Y axis using the Inspector or Rotate Gizmo. The normal shading of the Terrain actor won't correspond to the Sun's position. If the reference cube was set up in step 5, you should clearly see the difference between correct Cube normal map shading and incorrect Terrain normal map shading.

**Minimal reproduction project:**

[TerrainShadingIssue.zip](https://github.com/FlaxEngine/FlaxEngine/files/6728011/TerrainShadingIssue.zip)
Open Content/TerrainShadingIssue/T00_TerrainIssueScene scene.
There are two terrains: Terrain and Terrain Fixed. Enable/disable them to see the difference.

**Workaround**
1. In the Content window, go to Flax/Content/Engine, right-click the DefaultTerrainMaterial, select Copy and Paste it somewhere in your project.
2. Give the copy another name, "DefaultTerrainMaterialCopy".
3. Double-click the DefaultTerrainMaterialCopy material to open it.
4. In the material editor, locate the Normal Map node moving right-to-left: Material node (the rightmost one) -> Normal slot -> Multiply node -> Normal Map node.
5. Disable connection leading from Normal Map node to Multiply node on the right.
6. Negate the X output of the Normal Map node: Normal Map node -> mouse grag from its X output -> add a Negate node. We'll refer to this node as "Negate X" node.
7. Negate the Y output of the Normal Map node: Normal Map node -> mouse grag from its Y output -> add a Negate node. We'll refer to this node as "Negate Y" node.
8. Combine modified components of the Normal Map into a Vector3 (X and Y flipped):
8.1. Locate the "Negate Y" node -> mouse drag from its Result output -> add a Pack Vector3 node. Now the Result output of the "Negate Y" node should be connected with the X input of the Pack Vector3 node.
8.2. Locate the "Negate X" node -> connect its Result output with the Y input of the Pack Vector3 node.
8.3. Locate the Normal Map node -> connect its Z output with the Z input of the Pack Vector3 node.
9. Locate the Pack Vector3 node -> connect its Value output with the A input of the Multiply node.
10. Save the DefaultTerrainMaterialCopy material and close material editor.
11. Select the Terrain actor.
12. Drag DefaultTerrainMaterialCopy to Terrain's Material slot (Inspector -> Terrain section -> Material setting).
13. Select the Sun actor and rotate it around Y axis to check shading.
![terrain-mat-issue-01](https://user-images.githubusercontent.com/2660364/123675182-1ae08280-d84b-11eb-8796-23a5fc6978e9.png)

**Flax version:**

1.1.6218

**Comment by mafiesto4** [comment]
Wow strange that none noticed this earlier xD

**Comment by mafiesto4** [comment]
Fixed in e0a2904dbf6f8c6f1d0dd8ef903ed1efd31c8c58.
