### ISSUE TITLE
FBX Animation fails to loop

### ISSUE THREAD

**Issue by stefnotch** [FlaxEngine/FlaxEngine#565]
**Issue description:**
I tried importing a FBX model with a perfectly looping animation. I did make sure that the animation is a perfect loop by importing it into Blender.

However, in Flax, the animation is not a perfect loop. Instead, at some frame, it jumps backwards a bit and then resumes.

The FBX file, which is both a skinned model and an animation is here:
[WindTurbine.zip](https://github.com/FlaxEngine/FlaxEngine/files/6766014/WindTurbine.zip)

**Steps to reproduce:**
1. Import the `WindTurbine.fbx` as a skinned model. Rename that model. 
2. Then import the same `WindTurbine.fbx` as an animation
3. Create an animation graph and hook them up.
(Alternatively, just download the reproduction project)
4. Start the animation and wait a few seconds. At first, it seems to be going smoothly
5. A few seconds later, it jumps backwards a bit.

**Minimal reproduction project:**
[WindProject.zip](https://github.com/FlaxEngine/FlaxEngine/files/6766034/WindProject.zip)

**Flax version:**
Flax 1.1

**Comment by mafiesto4** [comment]
Fixed in a59429c954b04048bfa91841ffe12923ba6b3313.

![image](https://user-images.githubusercontent.com/3464853/125061903-1a978100-e0ae-11eb-8ce1-5a95d51fd69e.png)
