### ISSUE TITLE
FBX import animation problem

### ISSUE THREAD

**Issue by d-bug** [FlaxEngine/FlaxEngine#567]
**Issue description:**
I imported an animated fbx model both as skinned model and as animation, using the default import settings
[SK_armcv.zip](https://github.com/FlaxEngine/FlaxEngine/files/6793836/SK_armcv.zip)
. The skinned model imported correctly but when played the animation, the mesh slightly deformed.

**Flax version:**
1.1.6218

**Comment by mafiesto4** [comment]
It looks okish on the current `master`. Probably fixed by a59429c954b04048bfa91841ffe12923ba6b3313. Does it look as it supposed to?

https://user-images.githubusercontent.com/3464853/126159796-c348c9a0-3dd7-4787-8cef-31cd07e78ed9.mp4

**Comment by d-bug** [comment]
I know it is a Blender's FBX standard exporter problem. I re-exported the animation with a Blender's better FBX exporter and the animation plays without any issues. Thank you.

https://user-images.githubusercontent.com/4577504/126182449-6d431144-e262-45bc-9cc6-bd0db72ee316.mp4
