### ISSUE TITLE
Location of the new Engine Version is not the same as Launcher location

### ISSUE THREAD

**Issue by Muchaszewski** [FlaxEngine/FlaxEngine#57]
**Issue description:**
The location of the new Engine Version is not the same as the Launcher location

**Steps to reproduce:**

1. Use Launcher to install at D:/ instead of default C:/
2. Add new Engine Version 
![image](https://user-images.githubusercontent.com/5092066/99197809-f42a7b80-2794-11eb-91f9-9e19e0ec85b4.png)
(should be D:/)

I expect this is true for any other change within the path of the Launcher and result new Engine Version will not use it.

**Minimal reproduction project:**
None

**Flax version:**
Any

**Comment by honzapatCZ** [comment]
I dont think thats the intended behaviour, the launcher is just another program
BUT
Something like library location in steam could be incorporated into Flax Launcher, also changing the location of default projects from the default Documents\Flax

**Comment by mafiesto4** [comment]
Fixed for the next launcher update.
