### ISSUE TITLE
Crash on importing model into Flax

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#572]
Crash importing model into Flax:
![image](https://user-images.githubusercontent.com/35228400/126582502-b5665f81-1366-47a0-ba16-2d53342b6814.png)

Log:
[OutputLog.txt](https://github.com/FlaxEngine/FlaxEngine/files/6859656/OutputLog.txt)

Model:
[Test.zip](https://github.com/FlaxEngine/FlaxEngine/files/6859659/Test.zip)

**Flax version:**
Master Branch

**Comment by mafiesto4** [comment]
Fixed in 383ea4d6035a66826513910d5de3acf94b688a9e.
