### ISSUE TITLE
Recommend: Turn "Calculate Tangents" off by Default

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#573]
I recommend this setting be turned off by default. I just spent two hours trying to figure out why some of my normals were messed up on random models. If someone is importing their models from an art program they would have already calculated these.
![image](https://user-images.githubusercontent.com/35228400/126592671-68f09614-0741-45dd-9f60-84ea62ddea43.png)

**Flax version:**
Master Branch

**Comment by mafiesto4** [comment]
Fixed in 3a5c2129858733a29c44e444a9ae220db4880ab7. Additionally there are new options to preview model normals and tangents in the editor:
![image](https://user-images.githubusercontent.com/3464853/126617394-21badbc7-7148-4c03-ba32-19c087be65d0.png)
