### ISSUE TITLE
Menu popping up in the wrong position

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#576]
**Issue description:**
Right clicking in the Scene tree results in the menu popping up way in the wrong position. This seems to be a new issue as I didn't experience this in the past.
![image](https://user-images.githubusercontent.com/35228400/127947160-fcf067a2-459e-4125-8b02-b0797e641e3d.png)

**Flax version:**
Master Branch

**Comment by mafiesto4** [comment]
Fixed in 1b3c74c3eb21c98d547a576cd3005d7f21353b47
