### ISSUE TITLE
Flashing UI on Linux

### ISSUE THREAD

**Issue by dzerofive** [FlaxEngine/FlaxEngine#579]
**Issue description:**
Flashing UI and _Right Mouse Button Menu_ disappears if I hover over any button after "_New >_" on Manjaro 5.10.42-1. Not sure if second one intended or not though. [Video demonstration](https://youtu.be/qgVFQn2VH-U).

**Steps to reproduce:**
1. Launch;
2. Hover cursor over some elements.

**Minimal reproduction project:**
Literally default project from Download page.

**Flax version:**
1.1.6218

**Comment by mafiesto4** [comment]
It was fixed for 1.2 (as far as I remember). Can you check with the latest Linux binary from: <https://flaxengine.com/download/>
(the 1.2 download link was updated with a delay for Linux, sorry)

**Comment by dzerofive** [comment]
Same in 1.2.6222.

**Comment by mafiesto4** [comment]
Hmm something with Vulkan renderer. Could you post a log of Editor run with this issue but using `Debug` build? From `Binaries/Editor/Linux/Debug/FlaxEditor`. I guess what are exact GPU stats there and if debug layers say the about this.

**Comment by dzerofive** [comment]
Here it is, run with `./Binaries/Editor/Linux/Development/FlaxEditor -project "./Flax.flaxproj" -std -amd`. From log folder, same as in terminal: [Log_2021_08_08_20_27_36.txt](https://github.com/FlaxEngine/FlaxEngine/files/6951203/Log_2021_08_08_20_27_36.txt)
My GPU is RX580 8Gb.

**Comment by ryliejamesthomas** [comment]
I'm also having the same issue, with a more extreme effect. Also on Arch Linux, also with an AMD GPU (but RX570).

**Comment by ryliejamesthomas** [comment]
Worth noting that the flashing is now fixed for me (except for what I assume is a splash screen, can't see it enough to tell), but there are other severe GUI issues I'll report separately.

**Comment by mafiesto4** [comment]
Yeah this was the same issue that caused that problem like here #664 #667 which all were fixed by 3abbafa53074e89d681084ca83192015cc157649
