### ISSUE TITLE
Handle missing texture at import

### ISSUE THREAD

**Issue by abgenullt** [FlaxEngine/FlaxEngine#58]
Hi,
if I import a FBX model, that has a reference to a not existing texture (a bought model), it will not create the material at all.
I think, it would be better, if the material would be created with appropriate settings but with a warning, that the texture could not be found.

Regards
abgenullt

**Comment by mafiesto4** [comment]
Not a case anymore as Flax will be able to create materials for imported models and if texture is missing then the material will use solid color - and still can be setup in Editor.
