### ISSUE TITLE
StringView::GetText() is broken.

### ISSUE THREAD

**Issue by Zbyl** [FlaxEngine/FlaxEngine#584]
**Issue description:**
StringView::GetText() is broken. It can return non-null-terminated strings, and yet the codebase almost everywhere assumes that returned strings will be null-terminated.
This must have generated a lot of crashes and bugs already, and will continue to do so in the future.

The most reasonable solution is to remove StringView::GetText() function, as there is no way to fix it.
Keeping existing semantics with the current name will inevitably lead to errors in the future, as a sister function in String class do guarantee to return a null-terminated string.

**Flax version:**
Current master branch.

**Comment by Zbyl** [comment]
I'm preparing a pull request for this.

**Comment by mafiesto4** [comment]
In general, we try to not rely on null-terminated strings as having `StringView` with cached length is better for perf and usage (eg. making substrings and etc.).

Also, note the doc comment in `StringViewBase`:
```cpp
// Represents static text view as a sequence of characters. Characters sequence might not be null-terminated.
```

**Comment by Zbyl** [comment]
I have prepared a draft PR #592 that fixes a lot of issues with StringView::GetText(). It is not yet sufficiently tested.

**Comment by Zbyl** [comment]
PR #592 is ready for review.
