### ISSUE TITLE
Unhandled Exception: 0xe06d7363 on opening first project

### ISSUE THREAD

**Issue by Sarund9** [FlaxEngine/FlaxEngine#586]
**Issue description:**

I get this error when I launch my first project
![image](https://user-images.githubusercontent.com/53350334/128618585-cd12261e-9cc1-4db5-a3dc-eb0cac8cbd56.png)
Unhandled Exception: 0xe06d7363

**Steps to reproduce:**

System:
* Windows 7 64 bit
* GTX 1080 GPU

Steps:
1. Install Flax Launcher on F\: drive
2. Install Engine Version 1.2 on F\: drive
3. Create New Empty Project on F\: drive
4. Open Project

**Flax version:** 1.2

**Comment by mafiesto4** [comment]
Could you post a log from the project folder inside the directory `Logs`? It will help. Or even the might be inside that Logs folder another folder with crash information like documented here:  https://docs.flaxengine.com/manual/platforms/index.html#crash-logs

**Comment by Sarund9** [comment]
[Here a full Log](https://github.com/FlaxEngine/FlaxEngine/files/6950951/Log_2021_08_08_23_22_11.txt)
Seems to be an issue with KERNELBASE.dll during loading?

**Comment by mafiesto4** [comment]
It's probably fixed by #581 as it was crashing somewhere inside localization service init.

**Comment by Sarund9** [comment]
I Updated the engine to latest version and the Error disappeared.
