### ISSUE TITLE
Importing model from Blender unnecessarily fills holes

### ISSUE THREAD

**Issue by Kozioll** [FlaxEngine/FlaxEngine#593]
[
[model.zip](https://github.com/FlaxEngine/FlaxEngine/files/6956804/model.zip)
](![1](https://user-images.githubusercontent.com/74010035/128758262-f4e02f13-9836-479e-8190-7f4cad4ef5a3.PNG))

**Issue description:**

**Steps to reproduce:**

**Minimal reproduction project:**

**Flax version:**

**Comment by klukule** [comment]
I do belive that the issue might be in the mesh directly, since even microsoft 3D viewer shows similar errors (see attached image). Might be due to triangulation etc...

![image](https://user-images.githubusercontent.com/3607341/128762829-abf1a794-201e-4db4-a2ef-1769e1e34da6.png)

**Comment by mafiesto4** [comment]
https://discord.com/channels/437989205315158016/438021321134309377/874389312781832252
