### ISSUE TITLE
NetworkPeer Disconnect(NetworkConnection) crash

### ISSUE THREAD

**Issue by EinScott** [FlaxEngine/FlaxEngine#598]
**Issue description:**
Calling validNetworkPeer.Disconnect(validNetworkConnection) causes an access violation crash.

**Steps to reproduce:**
Grab the NetworkingSample project and paste
```
if (Input.GetKeyDown(KeyboardKeys.F))
{
    NetworkSession.Instance.DisconnectPlayer(GameSession.Instance.Players[0]);
}
```
into LocalPlayerScript OnUpdate

Join a server instance with a client instance build, press F in the server instance.
(that will end up calling _peer.Disconnect(con...))

**Flax version:**
1.2.6223

**Comment by Erdroy** [comment]
Thank you for the report.
Fixed with bb4d94e
