### ISSUE TITLE
Build errors on latest VulkanSDK

### ISSUE THREAD

**Issue by dragonCASTjosh** [FlaxEngine/FlaxEngine#6]
**Issue description:**
Decided to make a ticket for the issue for better tracking, When building with vulkan SDK version 1.2.154.1 i get the following errors

![error](https://user-images.githubusercontent.com/3044415/102674606-e05ca580-4196-11eb-8039-895b4a023b37.png)

**Flax version:**
1.0 source

**Comment by dragonCASTjosh** [comment]
Update:
Initial compile errors are fixed, currently resolving some validation errors before i can make a pull request

**Comment by jb-perrier** [comment]
Compilation works fine with sdk 1.2.162, have you tried this latest version?

**Comment by dragonCASTjosh** [comment]
> 1.2.162

Strange that your version is working as the enums that are throwing errors are straight up removed from the latest VulkanSDK. If i was to guess i would have to say your maybe not building Vulkan

Version 1.1.77: https://github.com/KhronosGroup/Vulkan-Headers/blob/sdk-1.1.77/include/vulkan/vulkan_core.h#L1111
Latest: https://github.com/KhronosGroup/Vulkan-Headers/blob/master/include/vulkan/vulkan_core.h#L1420

**Comment by jb-perrier** [comment]
Yeah , you are right , for some reason the build system was choosing an old sdk version, will change that.

**Comment by mafiesto4** [comment]
Fixed in #7
