### ISSUE TITLE
SimpleMove does not accumulate gravity over time

### ISSUE THREAD

**Issue by ScottLongley** [FlaxEngine/FlaxEngine#604]
**Issue description:**

The SimpleMove method in CharacterController.cpp is not implemented correctly and does not accumulate gravity over time.

**Steps to reproduce:**

Create a CharacterController Actor with a collider, and have it call SimpleMove(Vector3.Zero). The CharacterController's velocity will read (0.00f, -16.35f, 0.00f) each frame without change.

**Minimal reproduction project:**

**Flax version:**

master (dee4537 at time of issue)

**Comment by mafiesto4** [comment]
Fixed by #2758
