### ISSUE TITLE
Weird Physics Stuff Happening

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#606]
I decided to download the First Person Shooter Template for a tutorial idea. As soon as I opened this happened. Something weird going on with Flax physics:

https://user-images.githubusercontent.com/35228400/129849978-5b80c99b-2b67-408c-a3a7-cf5f3aa4d12b.mp4

**Flax version:**
1.2.6223

**Comment by jb-perrier** [comment]
I can reproduce the issue, but haven't found the reason for now.

**Comment by NIKEA-SOFT** [comment]
This is not the only problem.
Try to hold down the shot key for a while, and then release and you will get an acceleration to move.

**Comment by mafiesto4** [comment]
The world is upside down! 😨 

It might be something related to the center of mass in rigid bodies. I will check it...

**Comment by mafiesto4** [comment]
Fixed 151454db2cbcb9ca77309eceea39a582ced70460
