### ISSUE TITLE
Animations Screw up if you change Import Transform

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#610]
There is a bug with Import Transform and Animations. Please see this video:
https://user-images.githubusercontent.com/35228400/130458909-3d713339-3965-4eb4-b6af-a6c71d93fe8b.mp4

**Flax version:**
Master Branch

**Comment by mafiesto4** [comment]
If model uses import transformation (it's applied to the skeleton as well) then you might need to use the same transformation for imported animation. Does it fixes the problem?

**Comment by Evildea** [comment]
I just tried adding the same transformation to the animations and it just resulted in a different distortion.

**Comment by mafiesto4** [comment]
Fixed in 58967e739a1d764646d9867bd1dbe5fe42fdb3a9.
