### ISSUE TITLE
Bug with "Show Debug Draw"

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#611]
Please see the attached video:
https://user-images.githubusercontent.com/35228400/130459344-4331fa30-e65c-40cd-9407-034d23210058.mp4

**Flax version:**
Master Branch

**Comment by mafiesto4** [comment]
Potentially it could be fixed recently here 09e2b737f0087f04a55ad1d20435caa607b94fe7 as I got similar crash.

**Comment by Evildea** [comment]
Yeah, this sorted it.

**Comment by mafiesto4** [comment]
Another follow-up fix for this issue: https://github.com/FlaxEngine/FlaxEngine/commit/d8f72daf94a70a403d0164020487699b5424ea57. Should not happen anymre now.
