### ISSUE TITLE
Vertices count diffrence between flax and blender

### ISSUE THREAD

**Issue by Mallvac** [FlaxEngine/FlaxEngine#616]
**Issue description:**
There is 3,8 times more verts in flax than blender but triangles count seem to be unchanged.

**Steps to reproduce:**
- Export a model from blender into fbx
- Import fbx into flax

Model Used :
[model.zip](https://github.com/FlaxEngine/FlaxEngine/files/7059952/model.zip)

**Flax version:**
1.2

**Comment by jb-perrier** [comment]
Explained by @whocares on discord : 

![](https://i.imgur.com/YWZYEjd.png)
