### ISSUE TITLE
GenerateProjectFiles.bat failed

### ISSUE THREAD

**Issue by wallpap3r** [FlaxEngine/FlaxEngine#62]
Run GenerateProjectFiles.bat failed.
Output after adding ```echo "MSBUILD_PATH" ``` in CallBuildTool.bat
```
Generating Flax Engine project files...
"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe"
Missing Android SDK. Cannot build for Android platform.
Missing Linux Toolchain. Cannot build for Linux platform.
Missing MSVC toolset v140 (VS 2015 C++ build tools). Cannot build for Windows platform.
Done!
```

**Comment by W2Wizard** [comment]
>  Missing MSVC toolset v140 (VS 2015 C++ build tools). Cannot build for Windows platform
Go to Visual Studio -> Tools -> Tools and Features -> Individual components: Search for '140' and select the first and only option.

![image](https://user-images.githubusercontent.com/63303990/103136866-5e9fd700-46c4-11eb-9bb3-18fb9fa20dd1.png)

The other errors are jsut missing SDK's that you can get incase you need them.

**Comment by wallpap3r** [comment]
> > Missing MSVC toolset v140 (VS 2015 C++ build tools). Cannot build for Windows platform
> 
> Go to Visual Studio -> Tools -> Tools and Features -> Individual components: Search for '140' and select the first and only option.
> 
> ![image](https://user-images.githubusercontent.com/63303990/103136866-5e9fd700-46c4-11eb-9bb3-18fb9fa20dd1.png)
> 
> The other errors are jsut missing SDK's that you can get incase you need them.

Thanks, it works. I installed v140 build tool manually and it failed. It seems install into the visual studio directory is the valid way.
