### ISSUE TITLE
Accessing Shader Folder Crahses Editor

### ISSUE THREAD

**Issue by Athomield** [FlaxEngine/FlaxEngine#621]
**Issue description:**
When I try to access the shader folder  in "Flax>Content>Shaders" the editor crashes and gives this error
![cccc](https://user-images.githubusercontent.com/7095418/131691250-0ae0e074-0739-4d4c-8fd6-3d6ff2b0552d.PNG)

**Flax version:**
1.2 with standard cube scene

**Comment by mafiesto4** [comment]
Could you post a log from: `<project_folder\Logs` ? We gonna need more info what happened (it looks like sth related to your GPU).

**Comment by lucasdessy** [comment]
Hey! I have the same problem, I will attach mine.
[Crash_2021_09_01_14_52_09.zip](https://github.com/FlaxEngine/FlaxEngine/files/7093355/Crash_2021_09_01_14_52_09.zip)

**Comment by Athomield** [comment]
Yepp here it is
[Logs.zip](https://github.com/FlaxEngine/FlaxEngine/files/7094403/Logs.zip)

**Comment by mafiesto4** [comment]
Thanks for the logs. In both cases it's related to D3D11 Compute shader initialization. Could you try running **Debug build** (D3D debug layer will tell about failure cause)?

@lucasdessy Simply run `C:\Program Files (x86)/Flax/Flax_1.2/Binaries/Editor/Win64/Debug/FlaxEditor.exe` and reproduce the crash (after opening the project).

@Athomield Simply run `C:\Program Files (x86)/Flax/Flax_master/Binaries/Editor/Win64/Debug/FlaxEditor.exe` and reproduce the crash (after opening the project).

In both cases it will say probably sth about Compute not supported. I wonder why. We already have nice checks for compute features and your Nvidia GPUs should work just fine.

**Comment by NotHyper-474** [comment]
I have the same issue but it only happens in my integrated Intel GPU which has DX10.1, I use it when for some reason my Nvidia 9500 GT renderers everything as black.

I tried opening a project with Debug build using the Intel GPU and got this instead of the expected "Compute not supported" message.
![image](https://user-images.githubusercontent.com/40342021/131931623-e95fba81-5c18-4666-843e-205b789410b6.png)

Here is the Logs folder of the project, if it is of any use here.
[Logs.zip](https://github.com/FlaxEngine/FlaxEngine/files/7102507/Logs.zip)

**Comment by mafiesto4** [comment]
That's totally strange issue. You could try to use Vulkan (add `-vulkan` to cmd lien when starting editor) rendering backend or D3D10 (`-d3d10`). Those should work better I guess.

**Comment by mafiesto4** [comment]
@lucasdessy Would you be able to compile editor locally and run it in Debug build to see where it crashes on your PC?

Or even easier you can extract `.pdb` files into 1.2 engine (`engine/Binaries/Editor/Win64/...`) from our official debug symbols downloaded from here: <https://vps2.flaxengine.com/store/builds/Package_1_02_06224/EditorDebugSymbols.zip>. Then if you run Debug build it will print exact crash stack trace into the log.

Kind of complex thing as we're unable to reproduce this problem 😄

**Comment by lucasdessy** [comment]
[Crash_2021_09_17_21_23_07.zip](https://github.com/FlaxEngine/FlaxEngine/files/7181658/Crash_2021_09_17_21_23_07.zip)
Sorry for the delay, been working on something else. Now it does print the stack trace. Hope it helps you!

**Comment by mafiesto4** [comment]
It crashes on Compute shader creation. Probably GPU driver doesn't support it. Could you run Debug build? So we could get info why it doesn't load it?

**Comment by mafiesto4** [comment]
We've got some improvements to prevent crashing when GPU driver doesn't support a specific shader in 7e81fdbd758fab7c089b1dcc47f3b7c81cd384cd.
