### ISSUE TITLE
How to open shader files under the "Content " folder

### ISSUE THREAD

**Issue by GuDuJian-J-Zhang** [FlaxEngine/FlaxEngine#622]
**Issue description:**

**Steps to reproduce:**

**Minimal reproduction project:**

**Flax version:**

**Comment by Erdroy** [comment]
Is this related to this issue #621?
If not, then what do you mean by opening the shader files? Materials or you want to write shaders using code?

**Comment by GuDuJian-J-Zhang** [comment]
> Is this related to this issue #621?
> If not, then what do you mean by opening the shader files? Materials or you want to write shaders using code?
Thanks for your reply.
I mean how can i open and read the shader files as ASCII format in a text editor. For now it's in binary format.
For example, i want to know how the SelectionOutlineMaterial.flax achieves  it's effect. I open this shader file by [vscode](https://code.visualstudio.com/), but the editor show me the message as below:
![FE1D88F5-D5DC-4ca5-B85F-50B27FA97A76](https://user-images.githubusercontent.com/21232983/132149558-149d3413-3a23-4a55-ac73-1aa72fa71565.png)

**Comment by Erdroy** [comment]
Sorry for late reply.

You can open (double click) these directly in Flax Engine, or take a look at our repository here: [Shaders](https://github.com/FlaxEngine/FlaxEngine/tree/master/Source/Shaders)
![image](https://user-images.githubusercontent.com/7634316/132491228-81e4c3ea-a328-4330-9b24-b66138937e8b.png) 

We've implemented shaders using HLSL code and our visual material editor.

**Comment by GuDuJian-J-Zhang** [comment]
> Sorry for late reply.
> 
> You can open (double click) these directly in Flax Engine, or take a look at our repository here: [Shaders](https://github.com/FlaxEngine/FlaxEngine/tree/master/Source/Shaders)
> ![image](https://user-images.githubusercontent.com/7634316/132491228-81e4c3ea-a328-4330-9b24-b66138937e8b.png)
> 
> We've implemented shaders using HLSL code and our visual material editor.

Got it.  Thank you very much
