### ISSUE TITLE
Android graphics bug

### ISSUE THREAD

**Issue by VadimBoev** [FlaxEngine/FlaxEngine#627]
I compiled default example "basic"
On Windows - no problem, all working good!
On Android - have problem with graphics (https://www.youtube.com/watch?v=HhYcTjQuhlU)

Flax version: 1.2.6224

p.s. And it "killed" fps in game

How to fix this bug?

**Comment by mafiesto4** [comment]
It looks like some problems with Vulkan rendering. Recently we did some improvements for it but this flickering looks like some issues with constant buffers data. Thanks for reporting this, we will try to fix it.

**Comment by VadimBoev** [comment]
is this problem solved?

**Comment by mafiesto4** [comment]
It's been some time and we had lots of improvements/fixes to Vulkan and Android platforms so I guess you could check it on your phone.

**Comment by mafiesto4** [comment]
We've done lots of improvements over past years such as async scene rendering, ASTC textures support and so on. Thus rendering on mobile is way faster than it was before.

**Comment by VadimBoev** [comment]
async scene rendering - what is the principle of how it works?

**Comment by VadimBoev** [comment]
> We've done lots of improvements over past years such as async scene rendering, ASTC textures support and so on. Thus rendering on mobile is way faster than it was before.

async scene rendering - what is the principle of how it works?

**Comment by mafiesto4** [comment]
> > We've done lots of improvements over past years such as async scene rendering, ASTC textures support and so on. Thus rendering on mobile is way faster than it was before.
> 
> async scene rendering - what is the principle of how it works?

It uses multiple threads to draw scene objects (collect draw calls). More info:
https://docs.flaxengine.com/manual/release-notes/1_5/index.html#performance-optimizations

![image](https://github.com/FlaxEngine/FlaxEngine/assets/3464853/f585e69b-1497-4f93-a61e-3ee0c5ab7074)
