### ISSUE TITLE
Maximizing window via Windows Snap causes black box over taskbar.

### ISSUE THREAD

**Issue by PrecisionRender** [FlaxEngine/FlaxEngine#629]
**Issue description:**
When dragging the Flax Editor to the top of the screen to maximize using Windows Snap, a black box appears over the taskbar until the Flax Editor is restored down again.

**Steps to reproduce:**
1. Open Flax Editor
2. Restore down
3. Drag to the top of the screen and release

**Minimal reproduction project:**
None needed.

**Flax version:**
Version 1.2.6224

**Comment by mafiesto4** [comment]
For me, it looks like just occasional flickers while docking or snapping the window but that's because we're using a custom window toolbar. You can fallback to default by checking **Interface -> Use Native Window System** in the Editor options.

**Comment by Vizepi** [comment]
I don't know what you mean by "occasional flickers", but it makes all the window bar black and stays black (no flickering, no return to normal after some time). The Native Window System trick effectively prevent the issue from happening though.

**Comment by mafiesto4** [comment]
It should work far better now after fix 11b88cc6219382ed856c7695690e42cdfccaa8d9. If you still encounter this issue please reopen this ticket.
