### ISSUE TITLE
Crash when dragging material into scene view

### ISSUE THREAD

**Issue by Swiggies** [FlaxEngine/FlaxEngine#640]
**Issue description:**

Dragging a material into the scene view causes the engine to crash with error.
![image](https://user-images.githubusercontent.com/38583668/135809724-9643295b-763e-418e-8e92-75ce01d12a14.png)

Log File: [Log.txt](https://github.com/FlaxEngine/FlaxEngine/files/7276162/Log.txt)

**Steps to reproduce:**

Drag a material into the scene view to try and apply that material to an object.

**Flax version:**

1.2.6225

**Comment by mafiesto4** [comment]
Fixed in: 1b88f8ce3f9a70576a300d177023d063280ce886.
