### ISSUE TITLE
TextBox created from code not working correctly in cooked game

### ISSUE THREAD

**Issue by HarvyThyme** [FlaxEngine/FlaxEngine#641]
Creating a TextBox from code works fine in editor but doesn't in a cooked game. The background of RichTextBox shows in full build but doesn't seam to work at all. Haven't tested any other Controls.

Steps to reproduce:
1.make TextBox variable
2. create new TextBox in OnEnabled of script 
3. set TextBox.Parent = RootControl.GameRoot
4. add script to actor in level
5. play in editor the TextBox will show up
6. go to game cooker and build game
7. open game and the TextBox wont show

**Minimal reproduction project:**
Couldn't seem to upload zip so : 
https://drive.google.com/file/d/1U09ww1LEfXTBOTln7jLZhSP2t6-148QV/view?usp=sharing

Flax verions: 1.2.6224

**Comment by mafiesto4** [comment]
Finally implemented in 88eca13eb3539aa43e0bc2863f2f2fb3250d4188
