### ISSUE TITLE
Foliage disappears when reimporting model as skinned mesh

### ISSUE THREAD

**Issue by nothingTVatYT** [FlaxEngine/FlaxEngine#643]
**Issue description:**
When you import a (tree) model and use it as foliage, then adapt it and reimport as a skinned mesh it will disappear in the scene and the foliage settings. Even when you reimport the model once more as a static model it won't appear again.

**Flax version:**
1.2.6224

**Comment by mafiesto4** [comment]
The foliage holds reference to model asset so when it gets reimported as skinned model, the reference gets cleared and it would be hard to fix it.
