### ISSUE TITLE
Missing UI on existing foliage

### ISSUE THREAD

**Issue by nothingTVatYT** [FlaxEngine/FlaxEngine#644]
**Issue description:**
Editing an existing foliage does not show what is configured but clicking on the correct spot opens a selector box.

The UI looks like there should be something as it says "Select foliage" and in fact there should be a tree there. Clicking in the black space above this hint actually opens a selector so it seems like the UI is there but invisible.

**Steps to reproduce:**
It happens all the time.

**Flax version:**
2.1.6224 Linux editor
![Screenshot from 2021-10-06 21-52-09](https://user-images.githubusercontent.com/34131388/136274042-2431fb10-6e2e-4814-afd2-a37be7ce6b5c.png)

**Comment by mafiesto4** [comment]
Editor auto-selects the first foliage actor if there is one valid on a scene when you click the Foliage mode in a Toolbox. If you want to edit foliage in this mode, simply select that foliage manually (in Scene tree window).
