### ISSUE TITLE
Crash in LoadingThread.Join() when closing the editor on Linux

### ISSUE THREAD

**Issue by nothingTVatYT** [FlaxEngine/FlaxEngine#661]
**Issue description:**
The editor crashed with a segfault in LoadingThread::Join() on thread->Join() when the editor is closed.
As far as I can see the var thread is a nullptr when the crash is reported in a debugger although it's checked before but as this is a blocking function it may be the var is set to NULL in another thread.

**Steps to reproduce:**
Happens every time I close the editor.

**Flax version:**
Current master branch as of 2021 Oct 22nd

**Comment by mafiesto4** [comment]
Should be fixed in 4322563eed619c69e2950c16089902bf8212afa4
