### ISSUE TITLE
Linux, stability problem with logs

### ISSUE THREAD

**Issue by xenogenesi** [FlaxEngine/FlaxEngine#662]
Using the editor I am having some stability problems, often compromising the scene, it is not clear to me if I am doing something wrong (I launch the editor without arguments), in the backtraces I often notice formatting functions of the strings connected to the log.

While playing around with an idle-> walk transaction in an animgraph it often crashed trying to log the `Cannot cast Variant from {0} to {1}` message, certainly due to the fact that I was using the wrong nodes, `Axis (Y) > Float (0f)`.

```diff
--- a/Source/Engine/Core/Types/Variant.cpp
+++ b/Source/Engine/Core/Types/Variant.cpp
@@ -2999,7 +2999,9 @@ Variant Variant::Cast(const Variant& v, const VariantType& to)
         break;
     default: ;
     }
-    LOG(Error, "Cannot cast Variant from {0} to {1}", v.Type, to);
+    {
+    // LOG(Error, "Cannot cast Variant from {0} to {1}", v.Type, to);
+    }
     return Null;
 }
 
```

I commented the line for that message and it got better for that problem but continued to have problems with logs, often related to free null. With a bit of debugging I have often noticed that when this happens empty messages are passed, it is not clear to me why, I have added the same length control that is used for Windows and the stability is much improved.

```diff
--- a/Source/Engine/Core/Log.cpp
+++ b/Source/Engine/Core/Log.cpp
@@ -221,7 +221,11 @@ void Log::Logger::ProcessLogMessage(LogType type, const StringView& msg, fmt_fla
         fmt_flax::format(w, TEXT("{}"), (const Char*)msg.Get());
     }
 #else
-    fmt_flax::format(w, TEXT("{}"), (const Char*)msg.Get());
+    const int32 msgLength = msg.Length();
+    if (msgLength > 1)
+    {
+        fmt_flax::format(w, TEXT("{}"), (const Char*)msg.Get());
+    }
 #endif
 }
 
```

**Comment by mafiesto4** [comment]
Fixed in cf94cd937a7a72aa9828bf63f47d945084963d8f.
