### ISSUE TITLE
Vulkan crashes and freezes graphics card

### ISSUE THREAD

**Issue by Crawcik** [FlaxEngine/FlaxEngine#664]
**Issue description:**
 Vulkan is busted for a long time but recently i found out it even crashes graphics card.
If project uses only Vulkan then everything goes white. (probably some postfx option is busted in vulkan)
When project uses particles then everything crashes and freezes. After few second flax crashes too and Vulkan gives error `VK_ERROR_DEVICE_LOST` at `Engine/GraphicsDevice/Vulkan/QueueVulkan.cpp:51` (in that time graphic card is still freezed)
  
![20211101_120442.jpg](https://user-images.githubusercontent.com/42977680/139664657-5cb9c110-2576-4b82-903a-417078586bcc.jpg)
![20211101_115836.jpg](https://user-images.githubusercontent.com/42977680/139664670-0716d449-e890-46c8-b257-a6be0efd00c8.jpg)

 ​**Minimal reproduction project:** 
 - OS: Win & Linux (in my case freezed in manjaro linux)
 - VulkanSDK
 - Any project file with particles
  
 ​**Flax version:** 
 ​master

**Comment by mafiesto4** [comment]
What GPU do you use? Or maybe please send a log so maybe it will contain some useful info.

**Comment by Crawcik** [comment]
Graphics card: AMD Radeon 5700X
[Log.txt](https://github.com/FlaxEngine/FlaxEngine/files/7482439/Log.txt)

**Comment by Crawcik** [comment]
Without vulkan, its even more busted 
![image](https://user-images.githubusercontent.com/42977680/140956164-d0d7d782-bff2-43d0-994f-bbc501736cdb.png)

**Comment by mafiesto4** [comment]
Log file is useful, could you run Debug build with Vulkan too? It should log more info.

**Comment by Crawcik** [comment]
@mafiesto4 Hi, anything new on this topic?

**Comment by mafiesto4** [comment]
Not yet :/

**Comment by Crawcik** [comment]
Finally it has been fixed! Thanks @mafiesto4 !
