### ISSUE TITLE
Menu closes when a submenu closes

### ISSUE THREAD

**Issue by nothingTVatYT** [FlaxEngine/FlaxEngine#668]
**Issue description:**
Every time you hover over a menu item that brings up a submenu and leave that item not only does the submenu close but the parent as well. This happens in the Linux editor and makes it almost impossible to get anything done.

**Video showing the issue:**
https://discord.com/channels/437989205315158016/538664104856911883/901217501948555416

**Flax version:**
1.2.6224 up to at least current master Nov. 11th 2021

**Comment by mafiesto4** [comment]
Fixed in #936
