### ISSUE TITLE
gltf,glb format cannot import its texture and material

### ISSUE THREAD

**Issue by aslyr** [FlaxEngine/FlaxEngine#669]
**Issue description:**
when i export model from blender as gltf,glb,and use Flax import it,it cannot include texture and material,but if i use godot engine import it ,it work well, i must export this model as .gltf .bin .texture  it can work 

**Steps to reproduce:**

**Minimal reproduction project:**

Flax version:*1.2*

**Comment by aslyr** [comment]
[catwoman.zip](https://github.com/FlaxEngine/FlaxEngine/files/7554287/catwoman.zip)
It's just a suggestion, not critical, and if it doesn't work out, I'll move on to another format

**Comment by stefnotch** [comment]
I can confirm that it fails to import the textures. I suppose Flax doesn't import textures that are included in some model formats (`.glb` in this case). This issue can stay open until that gets addressed.

**Comment by Menotdan** [comment]
Bump, would like this fixed!

**Comment by mafiesto4** [comment]
Added support for importing embedded textures from `Assimp` in bed736a8eeb8ab5bad5c82458d9324edde88685e

![catwoman](https://github.com/FlaxEngine/FlaxEngine/assets/3464853/1737c060-d58c-4fb0-bc0d-10a5173cb26c)
