### ISSUE TITLE
Incorrect imported blend shapes with more than one mesh in the model

### ISSUE THREAD

**Issue by David-Ochoa** [FlaxEngine/FlaxEngine#672]
**Issue description:**
When the model has more than one mesh and these meshes share a blend shape the imported blend shape is distorted.

**Steps to reproduce:**
Import the attached model, check the blend shapes and they are distorted.
I'm also uploadig the Blender file in case it's required to test export options.
[Example video](https://youtu.be/vQ1TZMjRFMM)

**Minimal reproduction project:**
Not required, import the attached model.

**Flax version:**
Version 1.2

[Test.zip](https://github.com/FlaxEngine/FlaxEngine/files/7615644/Test.zip)

[TestBlendFile.zip](https://github.com/FlaxEngine/FlaxEngine/files/7615670/TestBlendFile.zip)

**Comment by David-Ochoa** [comment]
I was messing with the source code and after commenting [this line](https://github.com/FlaxEngine/FlaxEngine/blob/af305dc3765c266606e51122599f663dc4db7347/Source/Engine/Tools/ModelTool/ModelTool.OpenFBX.cpp#L742) the blend shapes were imported correctly.
[Result](https://youtu.be/hDooOcvSV3o)

**Comment by David-Ochoa** [comment]
Of course I don't know the details of the importer (and I'm not saying this is the solution) but it may help find what the problem is.

**Comment by mafiesto4** [comment]
Thanks! I did this fix here: c0bcb54044c1b6800e77bcd0d40609ec1b5b6caa. And also tested various different models with blend shapes and it seams that it improved a lot.
