### ISSUE TITLE
Flax Editor window is buggy and un-snappy when being dragged around or maximized

### ISSUE THREAD

**Issue by PrecisionRender** [FlaxEngine/FlaxEngine#676]
**Issue description:**
When dragging around the window to maximize it via Windows snap, which is how I usually maximize my windows, the Flax Editor bugs out by turning black and causes graphics issues with my taskbar. The window also feels very slow when resizing or maximizing/minimizing via the buttons on the window. The fallback is to switch to the native window mode, which fixes the taskbar issues completely. It still leaves the buggy/un-snappy Flax Editor window, though. A related/old issue is #629. Video below:

https://user-images.githubusercontent.com/89754713/144933764-af35b4a8-94a5-49b6-b2b4-0268b788ae0e.mp4

**Steps to reproduce:**
Open Flax editor and try dragging it around, maximizing it, or resizing it.

**Minimal reproduction project:**
None needed.

**Flax version:**
1.2.6224 (My graphics hardware is an Nvidia GeForce RTX 2060 Max-Q)

**Comment by BoomerDev** [comment]
Could be an issue with Windows 11..

**Comment by PrecisionRender** [comment]
> Could be an issue with Windows 11..

No, I had the same issue with Windows 10 before I upgraded. I've had Flax since early this year, before Windows 11 was even announced.

**Comment by mafiesto4** [comment]
It should work far better now after fix 11b88cc6219382ed856c7695690e42cdfccaa8d9. If you still encounter this issue please reopen this ticket.
