### ISSUE TITLE
Incorrect loop when animation is shorter than 1 second

### ISSUE THREAD

**Issue by David-Ochoa** [FlaxEngine/FlaxEngine#679]
**Issue description:**

When the animation is shorter than 1 second the loop pauses until a second is completed. In the video there are two animations, it's the same animation scaled in the authoring tool previous to importing.

https://user-images.githubusercontent.com/13645633/145622477-77db6b74-56e6-4dd8-ac3d-2440ec8a7187.mp4

**Steps to reproduce:**
Add the assests to any project, open the Animation Graph and change between animations. The shortest one pauses when looping.

**Minimal reproduction project:**
Assets: [TestLoop.zip](https://github.com/FlaxEngine/FlaxEngine/files/7694731/TestLoop.zip)

**Flax version:**
1.2

**Comment by mafiesto4** [comment]
It looks like the imported animation has missing keyframes:
![image](https://user-images.githubusercontent.com/3464853/145710548-98c74518-908c-4bf3-b8fb-a832d3a57392.png)

I wonder why is that? Is the source animation empty? Or maybe the imported length is not valid?

**Comment by David-Ochoa** [comment]
These are the original animations, maybe it's an import issue
[Animations.zip](https://github.com/FlaxEngine/FlaxEngine/files/7699085/Animations.zip)
.

**Comment by David-Ochoa** [comment]
I converted the animations from DAE to DBX using the FBX converter (I've had problems importing the COLLADA format and the FBX is more reliable). The time in the file is clearly stated, maybe hte converter is the problem?
[AnimationsDAE.zip](https://github.com/FlaxEngine/FlaxEngine/files/7699096/AnimationsDAE.zip)
