### ISSUE TITLE
Custom window title bars still are "maximized" after dragging them around

### ISSUE THREAD

**Issue by PrecisionRender** [FlaxEngine/FlaxEngine#683]
**Issue description:**
After maximizing windows in Flax Engine, then dragging them using the custom title bar, the OS still thinks they are maximized. (You can tell even easier on Window 11, because the windows usually have rounded corners, unless they are maximized)

https://user-images.githubusercontent.com/89754713/147840305-e867e820-48c2-4e2f-b626-6bd4147e3558.mp4

**Steps to reproduce:**

1. Undock a window
2. Maximize it
3. Drag it using the custom title bar

**Minimal reproduction project:**
None needed.

**Flax version:**
1.2.6226

**Comment by mafiesto4** [comment]
Fixed by #835
