### ISSUE TITLE
Unable to drag a custom window with native title bar when maximized

### ISSUE THREAD

**Issue by PrecisionRender** [FlaxEngine/FlaxEngine#684]
**Issue description:**
When a dock window is maximized, you are unable to drag it around using the native window system.

https://user-images.githubusercontent.com/89754713/147840348-5c237fa7-79ad-4f00-861b-eea900056d55.mp4

**Steps to reproduce:**

1. Undock a window
2.Maximize it
3. Try dragging the native window title bar

**Minimal reproduction project:**
None needed

**Flax version:**
1.2.6226

**Comment by mafiesto4** [comment]
Fixed by #835
