### ISSUE TITLE
Editor freezes when compiling/reloading scripts

### ISSUE THREAD

**Issue by herocrab** [FlaxEngine/FlaxEngine#685]
**Issue description:**
My Flax editor freezes often when compiling/reloading scripts. It happens nearly 20% of the time. I will update some code and click back to the editor, the editor begins reloading scripts and makes it to around 30%-sh and freezes. I can use task manager to kill the frozen process (not responding) and then restart flax and it loads the updated source files. I use Rider and have tested multiple versions and builds of the engine/editor. 

**Steps to reproduce:**
Editing any C# code and clicking back to the editor.

**Flax version:**
I am currently on d202c8b864b4430e90fa47cd646a092820e137ae but this has happened to me on many versions since I began using Flax. I've attached the Tracy capture of this.

I'd like to continue working a project and hopefully release/ship a game with Flax, any help is appreciated. Let me know what I can do to be of service in resolving the issue.

[script_reloading_freeze.zip](https://github.com/FlaxEngine/FlaxEngine/files/7824904/script_reloading_freeze.zip)

**Comment by mafiesto4** [comment]
It looks like this happens after C# assemblies unloading and probably inside `mono` code:

![image](https://user-images.githubusercontent.com/3464853/148818011-4f8c3384-8df0-40a6-86f6-888c8b04fc41.png)

As I was unable to catch this issue, it could be cool if you could hit debugger break during this freeze to see what code is executed there (or maybe sth in the log about mono assertion?).

**Comment by mafiesto4** [comment]
The problem is solved on the latest `1.6` branch that is using the latest .NET 7 with new hot-reload.
