### ISSUE TITLE
RayCastHit.UV bug

### ISSUE THREAD

**Issue by whocares77** [FlaxEngine/FlaxEngine#686]
**Issue description:**
RayCastHit.UV returns wrong value

https://user-images.githubusercontent.com/97740209/149522108-dec276c1-afe4-48c3-abf0-7e4aab74e335.mp4

**Steps to reproduce:**
I attached Flax Project so run it and enter Play Mode.

**Minimal reproduction project:**
[RaycastHitBug.zip](https://github.com/FlaxEngine/FlaxEngine/files/7870643/RaycastHitBug.zip)

**Flax version:**
1.2.6224

**Comment by whocares77** [comment]
I guess I misunderstood what it will to return. I thought its like Unity's (https://docs.unity3d.com/ScriptReference/RaycastHit-textureCoord.html)

**Comment by mafiesto4** [comment]
Okay so raycast returns the UVs of the hit triangle but not of the mesh geometry. To get the mesh triangle data (such as texture coordinates) use the following code:

```cs
public override void OnUpdate()
{
    Ray ray = _camera.ConvertMouseToRay(Input.MousePosition);
    if (Physics.RayCast(ray.Position, ray.Direction, out RayCastHit hit))
    {
        if (hit.Collider is MeshCollider meshCollider)
        {
            // Read the source geometry triangle based on the hit face index
            if (meshCollider.CollisionData.GetModelTriangle(hit.FaceIndex, out var meshBase, out var triangle))
            {
                if (meshBase is Mesh mesh)
                {
                    // Access static mesh data
                    var indexBuffer = mesh.DownloadIndexBuffer();
                    var vertexBuffer = mesh.DownloadVertexBuffer();

                    // Get the hit triangle data
                    ref var v0 = ref vertexBuffer[indexBuffer[triangle * 3 + 0]];
                    ref var v1 = ref vertexBuffer[indexBuffer[triangle * 3 + 1]];
                    ref var v2 = ref vertexBuffer[indexBuffer[triangle * 3 + 2]];

                    // Interpolate raycast UVs into the mesh triangle UVs
                    hit.UV = v0.TexCoord * (1.0f - hit.UV.X - hit.UV.Y) + v1.TexCoord * hit.UV.X + v2.TexCoord * hit.UV.Y;
                }
            }
        }

        MaterialBase material = hit.Collider.Parent.As<StaticModel>().GetMaterial(0);
        material.SetParameterValue("PaintPos", hit.UV);
        UIControl.Get<Label>().Text = $"X: {hit.UV.X} \nY: {hit.UV.Y}";
    }
}
```

You can use this code to extract more info from mesh like: vertex color, vertex normal, etc.
(more docs: https://github.com/FlaxEngine/FlaxDocs/blob/master/manual/physics/raycasting.md#example-raycast-with-mesh-data-access)
