### ISSUE TITLE
Unable to add parameters to Visual Script of type LayersMask

### ISSUE THREAD

**Issue by PrecisionRender** [FlaxEngine/FlaxEngine#688]
**Issue description:**
When adding a parameter to a Visual Script and selecting the type `LayersMask`, nothing happens. The script gets an unsaved asterisk, like it tried to add the parameter, but nothing shows up in the parameters list.

Log file:
[log.txt](https://github.com/FlaxEngine/FlaxEngine/files/8008417/log.txt)

**Steps to reproduce:**

1. Create a new Visual Script
2. Add a new parameter of type `LayersMask`

**Minimal reproduction project:**
[LayersMaskReproProject.zip](https://github.com/FlaxEngine/FlaxEngine/files/8008425/LayersMaskReproProject.zip)

**Flax version:**
1.3.6227

**Comment by mafiesto4** [comment]
Fixed in 3feeec1649929726d37aad54aa5a35eb2b5adbec
