### ISSUE TITLE
Terrain viewed inside PrefabWindow crashes editor

### ISSUE THREAD

**Issue by ScottLongley** [FlaxEngine/FlaxEngine#689]
**Issue description:**

It's possible to store Terrain inside a prefab and load it into the scene, but trying to edit the prefab from the PrefabWindow (double clicking the prefab) causes the Editor to crash (EXCEPTION_ACCESS_VIOLATION, crashes at https://github.com/FlaxEngine/FlaxEngine/blob/69a1e007a62fcee12d96991c811dc20a94321689/Source/Engine/Terrain/TerrainChunk.cpp#L98).

**Steps to reproduce:**

Create some new Terrain, drag it from the Scene hierarchy to the Content window to create a new prefab, hit enter to confirm the filename, the editor will crash. If you open the project back up and open the prefab, it will crash again.

**Minimal reproduction project:**

[terrain_crash.zip](https://github.com/FlaxEngine/FlaxEngine/files/8052103/terrain_crash.zip)

**Flax version:**

master ([69a1e00](https://github.com/FlaxEngine/FlaxEngine/commit/69a1e007a62fcee12d96991c811dc20a94321689) at time of issue)

**Comment by mafiesto4** [comment]
Fixes in 111a2f3b254553bd3f2fb9d79e2e8296560728c3.
