### ISSUE TITLE
Newly duplicated prefabs behave incorrectly inside PrefabWindow

### ISSUE THREAD

**Issue by ScottLongley** [FlaxEngine/FlaxEngine#690]
**Issue description:**

Dragging prefabs (sub prefab) into another prefab (main prefab) and saving is okay, but duplicating the prefabs (sub prefabs) inside the main prefab results in the sub prefabs to either completely lose its PrefabObjectID, or end up with the incorrect amount of child actors whenever the sub prefab is updated.

![2022-02-12 09-10-32-38](https://user-images.githubusercontent.com/29146264/153682932-b167c19d-0763-4793-958d-04a53ea236de.png)

This is mentioned in https://github.com/FlaxEngine/FlaxEngine/issues/385 but I thought this detailed issue might help nail the problem.

**Steps to reproduce:**

Create two prefabs (main_prefab and sub_prefab), open main_prefab and drag a sub_prefab into it. Duplicate sub_prefab (ctrl+c/v/d) and save main_prefab (there will be some warnings/errors in the logs). Open and edit sub_prefab by adding a child actor to it, save and close. Open main_prefab back up and the sub_prefabs will not have the correct children.

**Minimal reproduction project:**

[prefab_bug.zip](https://github.com/FlaxEngine/FlaxEngine/files/8052125/prefab_bug.zip)

**Flax version:**

master ([69a1e00](https://github.com/FlaxEngine/FlaxEngine/commit/69a1e007a62fcee12d96991c811dc20a94321689) at time of issue)

**Comment by mafiesto4** [comment]
Fixed in 1ef8bb723c83bad36079ab0d51c9a1769665e2e0 (automated test added for this prefab edit case)
