### ISSUE TITLE
Cursor is not clipped to Game Window in Full Screen Mode

### ISSUE THREAD

**Issue by herocrab** [FlaxEngine/FlaxEngine#692]
**Issue description:**
When using full screen (or any mode) the mouse cursor is not clipped or constrained to active game window. I understand that for borderless or windowed mode this is ok, but for full screen this is problematic in dual-monitor configurations. My mouse is able to move directly into the other monitor breaking edge scrolling RTS/MOBA like camera control.

There appears to be no CursorClip implemented in the engine source. 

It would be nice to implement Cursor Clipping for all modes, based on a setting, so that even windowed games can do things like edge scrolling.

**Steps to reproduce:**
1) Create a project.
2) Enable full screen mode.
3) Scroll from game window/monitor to other monitor directly.

**Minimal reproduction project:**

**Flax version:**
I am running daily build as of 2/16/2022.

**Comment by herocrab** [comment]
There is a PR for this here: 

https://github.com/FlaxEngine/FlaxEngine/pull/691

**Comment by herocrab** [comment]
@mafiesto4 Anychance for this in 1.4?

**Comment by mafiesto4** [comment]
Yeah sure, I'll add it to the 1.4 roadmap.

**Comment by mafiesto4** [comment]
#691 merged
