### ISSUE TITLE
Assertion failed on model export

### ISSUE THREAD

**Issue by Cynnar** [FlaxEngine/FlaxEngine#695]
**Issue description:**
Failed to export character mesh.

![ScreenHunter_1144 Mar  06 14 48](https://user-images.githubusercontent.com/6291044/156941859-fbd14193-e9e0-418c-a7ad-6b06a7ab8bcc.jpg)

**Steps to reproduce:**
Export character mesh

**Minimal reproduction project:**
Current project with characters.
Character location Content/Models/Character/Female (or Male)

[MakeHuman_Models.zip](https://github.com/FlaxEngine/FlaxEngine/files/8193485/MakeHuman_Models.zip)

**Flax version:**
1.3.6228

The error occurs every time I try to export the character mesh. I do have the character, the textures, and the materials in different locations than the original import. This is to make use of one material for the characters and use material instances for the different characters.

**Comment by GoaLitiuM** [comment]
Doesn't seem to reproduce anymore in latest master
