### ISSUE TITLE
Memory bug

### ISSUE THREAD

**Issue by DevXtreme2007** [FlaxEngine/FlaxEngine#697]
**Issue description:**
I tried to enter playmode and i got an error "unhandled exception"

[Log.txt](https://github.com/FlaxEngine/FlaxEngine/files/8238407/Log.txt)

**Steps to reproduce:**

**Minimal reproduction project:**

**Flax version:**
1.3

**Comment by mafiesto4** [comment]
The log is from version `1.2.6224`. Could you try to reproduce it on 1.3 version?

**Comment by DevXtreme2007** [comment]
[Log.txt](https://github.com/FlaxEngine/FlaxEngine/files/8256670/Log.txt)

**Comment by mafiesto4** [comment]
It seems that your script calls `RigidBody::AddForce` and it causes the crash. Is this rigidbody added to the scene? Do you call it in OnUpdate/OnAwake/OnEnable? You could attach minimal reproduction project zip so we could quickly fix it.

**Comment by DevXtreme2007** [comment]
But i don't get it, how can an addforce method cause a crash

**Comment by DevXtreme2007** [comment]
I feel It's a bug in the engine cos i tried it on a different engine and the same thing happened

**Comment by GoaLitiuM** [comment]
Probably related to #708. The RigidBody must not be kinematic for AddForce to work.

**Comment by mafiesto4** [comment]
Fixed by #711
