### ISSUE TITLE
OnLateUpdate, OnFixedUpdate override

### ISSUE THREAD

**Issue by ptcsoderlund** [FlaxEngine/FlaxEngine#707]
Is it just me or is OnLateUpdate and OnFixedUpdate not getting called in C++ Script?
```
    void OnLateUpdate() override;
    void OnFixedUpdate() override;
```

**Steps to reproduce:**
Add C++ script and override the methods given above.

**Flax version:**
1.3

**Comment by ptcsoderlund** [comment]
Guess its just me, i´m gonna close this and switch over to C# which I actually understand :)

**Comment by mafiesto4** [comment]
@ptcsoderlund You need to set `_tickLateUpdate=true` and `_tickFixedUpdate=true` in ctor to receive those ticks.

I'll add docs about it (and comment base method in `Script.h`) to prevent any future misunderstanding.

**Comment by ptcsoderlund** [comment]
Allright, cool.
Is that consistent over c++ and c#? Not totally sure but i think c# got onlateupdate tick only by overriding.

**Comment by mafiesto4** [comment]
In C# we have automatic detection for ticking if that method is overridden.

**Comment by ptcsoderlund** [comment]
I see. Thank you for the information and for taking your time.
You guys are awesome, and there is alot of potential in Flax engine.

I just have to learn to read the source code better so I can tag along for the ride.
