### ISSUE TITLE
Crash when using AddForce() or AddTorque() in RigidBody

### ISSUE THREAD

**Issue by PrecisionRender** [FlaxEngine/FlaxEngine#708]
**Issue description:**

When using `AddForce()` or `AddTorque()`, the engine crashes with this error message:
![image](https://user-images.githubusercontent.com/89754713/166294552-0d12cac6-ba5c-48ce-9c94-a390970c0a8e.png)
I suspect this happens with other RigidBody mehtods such as `AddRelativeTorque()`.

[Log.txt](https://github.com/FlaxEngine/FlaxEngine/files/8604918/Log.txt)

**Steps to reproduce:**
1. Create a RigidBody
2. Add a script that uses some RigidBody method

**Minimal reproduction project:**
[RigidBodyBug.zip](https://github.com/FlaxEngine/FlaxEngine/files/8604962/RigidBodyBug.zip)

**Flax version:**
1.3.6228

**Comment by GoaLitiuM** [comment]
Is the RigidBody kinematic? You can only add forces to non-kinematic rigid bodies. I can replicate this crash if the rigid body is indeed kinematic.

**Comment by PrecisionRender** [comment]
No, the RigidBody is not kinematic. That sounds like a separate bug.

**Comment by GoaLitiuM** [comment]
Yup. It seems to crash during `OnStart` calls or during first `OnUpdate` call, but not in `OnFixedUpdate`.

**Comment by PrecisionRender** [comment]
Sounds right to me.
