### ISSUE TITLE
Duplicate actors in prefab after moving actors in nested prefabs

### ISSUE THREAD

**Issue by GoaLitiuM** [FlaxEngine/FlaxEngine#718]
How to reproduce:
- Create empty prefabs A and B
- Drag prefab B into prefab A, save
- Create two actors under prefab B, save
- Move one of the actors under the other actor as a child, save
- In prefab A, the referenced prefab B has two identical children under the actor
![image](https://user-images.githubusercontent.com/4064397/171715878-8e71f8b6-cc12-4f97-a365-78079401b5cd.png)

**Flax version:** master branch.

**Comment by GoaLitiuM** [comment]
Duplicate of #690

**Comment by mafiesto4** [comment]
Actually this bug is a separate problem, different than #690

**Comment by mafiesto4** [comment]
Fixed here 8beb732cb9a1cd1d7032697e787549dbe4ccf828 (with new unit test: 99d1c1903ff7fcb5263299f3df996fe81693adcd)
