### ISSUE TITLE
UWP default project error

### ISSUE THREAD

**Issue by DJDQfff** [FlaxEngine/FlaxEngine#720]
* Flax Version :1.3 

* UWP project ,exported from flax defult scene(with a ball and a ground)
  *  target platform:2004
  *  lowest platform: from 2004 to 1803

* exception message:
  System.TypeLoadException:“Requested Windows Runtime type 'FlaxEngine.Game' is not registered.”

* position: 
  _game=new Game();

When it run ,debug threw such an exception:

I also tyied my custom project (added some contents),now it can't invoke debug exception.it crashed suddenly.

**Comment by Withaust** [comment]
UWP is now marked as a deprecated platform, I think now this issue might be irrelevant?

**Comment by mafiesto4** [comment]
Yeah this platform is not well supported and will be replaced with WindowsGDK (we already use GDK for Xbox).

**Comment by mafiesto4** [comment]
GPU platform implementation sources: https://github.com/FlaxEngine/FlaxEngine/tree/master/Source/Engine/Platform/GDK + https://github.com/FlaxEngine/FlaxEngine/tree/master/Source/Tools/Flax.Build/Platforms/GDK + https://github.com/FlaxEngine/FlaxEngine/tree/master/Source/Editor/Cooker/Platform/GDK
