### ISSUE TITLE
Assertion failed when opening a new Skeleton Mask

### ISSUE THREAD

**Issue by PrecisionRender** [FlaxEngine/FlaxEngine#723]
**Issue description:**
When opening a Skeleton Mask, an assertion fails, resulting in an editor crash.
![image](https://user-images.githubusercontent.com/89754713/172085458-a3348238-f53b-4071-8e41-2e84c73a7b4e.png)
[Log.txt](https://github.com/FlaxEngine/FlaxEngine/files/8841502/Log.txt)

**Steps to reproduce:**
1. Right-click on a skinned model and click New > Skeleton Mask
2. Double-Click the mask

**Minimal reproduction project:**

[SkeletonMaskBug.zip](https://github.com/FlaxEngine/FlaxEngine/files/8841508/SkeletonMaskBug.zip)

**Flax version:**
Flax Engine 1.3.6228

**Comment by mafiesto4** [comment]
Fixed here: bb2f8f34dc84554e74d116c13bba0cad9332e08e
