### ISSUE TITLE
No implemention for .winmd file

### ISSUE THREAD

**Issue by DJDQfff** [FlaxEngine/FlaxEngine#725]
When i export project for **Windows Store**,it showed such warning above.

It requires that you should give the implement for the winmd file ,otherwise the application won't register the information for it.

Compiling work is OK, but when i run the app ,it crashed.And showed the Exception :
**System.TypeLoadException:“Requested Windows Runtime type 'FlaxEngine.Game' is not registered.**

My flax project is default project.engine version 1.3

**Comment by mafiesto4** [comment]
We've deprecated UWP platform. It was not used by many developers and maintenance of it was hard due to Microsoft’s design. Also, Microsoft deprecated it in favor of Microsoft **Game Development Kit** (**GDK**) which is implemented in Flax and used for Xbox.
