### ISSUE TITLE
Use SplineLength actor freezes the editor or game runtime

### ISSUE THREAD

**Issue by cristhofermarques** [FlaxEngine/FlaxEngine#726]
**Issue description:**
 Editor freezes if call `SetSplinePoint(index, newPos)` and then `SplineLength`, was expected to get the spline length without problems.

A code example
![image](https://user-images.githubusercontent.com/65502434/173200578-5180881b-76c6-40fe-afcd-41f64b7ed21c.png)

 No logs on freeze

**Steps to reproduce:**

![image](https://user-images.githubusercontent.com/65502434/173200610-eceddc07-b761-4a89-a306-af7bad2849d4.png)

**Minimal reproduction project:**

[Test.zip](https://github.com/FlaxEngine/FlaxEngine/files/8884542/Test.zip)

**Flax version:**

1.3.6229(lastest master branch)

**Comment by mafiesto4** [comment]
Fixed in: 8158052ec796c34e7d4a63535c53439ec921ac69
