### ISSUE TITLE
Can't generate or import UV-Lightmaps

### ISSUE THREAD

**Issue by abgenullt** [FlaxEngine/FlaxEngine#730]
Hi,

I use a exported version of the blender default cube with an additional light map texture channel.
But in the flax editor import settings, I can't import it or generate a new one. If I click on import, the "lightmap uvs source" revert back to "disabled".

I'm using Flax 1.3 and have attached a sample project.

Regards 
abgenullt
[LightmapTest.zip](https://github.com/FlaxEngine/FlaxEngine/files/8943070/LightmapTest.zip)
.

**Comment by cristhofermarques** [comment]
try master branch

**Comment by abgenullt** [comment]
ok.. do you provide a daily or nightly build? On my machine, I currently can't build from source :(

**Comment by whocares77** [comment]
> ok.. do you provide a daily or nightly build? On my machine, I currently can't build from source :(

you can download CD (Continuous Deployment) builds (this is daily master branch build)

**Comment by abgenullt** [comment]
Thank you, it is working but the light map baking is now crashing..
Here is the log file. Maybe it helps.
[Log_2022_06_21_19_24_06.txt](https://github.com/FlaxEngine/FlaxEngine/files/8951103/Log_2022_06_21_19_24_06.txt)

**Comment by mafiesto4** [comment]
Should be fixed in the latest `master` and CD builds

**Comment by abgenullt** [comment]
Perfect, thank you!
