### ISSUE TITLE
Missing Material Parameters attributes from nested layers

### ISSUE THREAD

**Issue by mafiesto4** [FlaxEngine/FlaxEngine#731]
**Issue description:**
When populating nested material the parameters don't have their attributes preserved (probably need to copy parameters `Meta` data).

**Steps to reproduce:**
1. Create material A
2. Add parameter
3. Add Editor Group attribute to the parameter with a group name
4. Save material A
5. Create another material B with layer using material A
6. Save material B
7. Create instance of material B
8. Notice the group is missing (in instance created from material A it's there)

Material parameters don't have attributes (instance of material B):
![image](https://user-images.githubusercontent.com/3464853/177349316-e687d7a1-d550-4173-a7ec-c3ce96bf4029.png)

Correct display (instance of material A):
![image](https://user-images.githubusercontent.com/3464853/177349441-97132060-e6e7-4539-813e-30c52a2c8986.png)

**Flax version:**
`master` branch

**Comment by Myterian** [comment]
Same issue I'm facing currently. Any updates on this?

**Comment by mafiesto4** [comment]
Added in c62575612b32e85f131878327e7f5893833e52e9.
