### ISSUE TITLE
Incorrect animation blending in `BlendSpace1D`

### ISSUE THREAD

**Issue by PrecisionRender** [FlaxEngine/FlaxEngine#734]
**Issue description:**
When blending between animations using `BlendSpace1D`, the animations loop incorrectly. In the case of this character, the feet are moving very strangely.

https://user-images.githubusercontent.com/89754713/182277331-75bfbb1c-89c9-4c57-b224-ad6c4f7d5094.mp4

**Steps to reproduce:**
1. Create a `BlendSpace1D` and add some animations to it.
2. Set the X parameter to a value in between 2 animations.

**Minimal reproduction project:**
[AnimBugs.zip](https://github.com/FlaxEngine/FlaxEngine/files/9238513/AnimBugs.zip)

**Flax version:**
Flax 1.3.6228

**Comment by mafiesto4** [comment]
That's a common problem of many games and comes from the different lengths of walk and run animations where feet don't match. This could be solved/improved by using Sync Groups feature that is planned on a roadmap.
