### ISSUE TITLE
Camera jitter

### ISSUE THREAD

**Issue by kerelape** [FlaxEngine/FlaxEngine#740]
**Issue description:**
Camera movement (or propably rotation) is jumpy when its position is far from the center. The issue appears at about 1km (100000 units) and becomes highly visible closer to 5km (500000 units). This problem accurs in the Editor, Editor game mode, and in the built game, which makes it imposible to make any open world game

**Flax version:**
1.3

**Comment by mafiesto4** [comment]
That's normal limitation of `32bit` floating point values. For upcoming 1.4 update we've added optional `64bit` precision support and relative-to-camera rendering which makes it possible to create very large worlds (eg. of size 10 000 km):

![large-worlds-support](https://user-images.githubusercontent.com/3464853/188565152-ec974259-619c-468c-8b8d-18ccc97269ca.gif)

Docs: https://github.com/FlaxEngine/FlaxDocs/blob/master/manual/editor/large-worlds/index.md
