### ISSUE TITLE
`UseLargeWorlds`

### ISSUE THREAD

**Issue by kerelape** [FlaxEngine/FlaxEngine#741]
How do I enable double presicion for the current version of the engine (master branch)? I did change `UseLargeWorlds` to `true` in the `Flax.flaxproj` and have generated a new project with the engine, but it seems that it still uses float precision.

**Comment by mafiesto4** [comment]
After changing `UseLargeWorlds=true` you can build editor/game with `double`. I just tested it and worked fine for me. Maybe you didn't rebuild project? Also, we have Continious Integration setup on Github Action which build project with LargeWorlds enabled so we always know it compiles properly: https://github.com/FlaxEngine/FlaxEngine/actions/workflows/tests.yml

**Comment by kerelape** [comment]
Right... I didn't rebuild, thanks for help!

**Comment by kerelape** [comment]
I did rebuild it and it seems to work except the viewport camera. Looks like it still only uses `float` for `yaw` and `pitch` in the `EditorViewport` class.

**Comment by mafiesto4** [comment]
I think rotation doesn't need 64-bit precision but maybe some more testing could be put here to see if we could gain quality by using doubles.

**Comment by kerelape** [comment]
> I think rotation doesn't need 64-bit precision but maybe some more testing could be put here to see if we could gain quality by using doubles.

@mafiesto4 Seems weird but any other object rotates smoothly at any distance, but the camera doesn't
