### ISSUE TITLE
DirectX Error/crash on Shader Compile

### ISSUE THREAD

**Issue by Swiggies** [FlaxEngine/FlaxEngine#745]
**Issue description:**

My shader successfully compiled but is immediately met with an editor crash and the error
`DirectX error: E_INVALIDARG at F:\FlaxEngine\Source\Engine\GraphicsDevice\DirectX\DX11\GPUShaderDX11.cpp:93`

[LogWithDumpAndShader.zip](https://github.com/FlaxEngine/FlaxEngine/files/9532077/LogWithDumpAndShader.zip)

**Steps to reproduce:**

I just try to open my resulting shader asset in the editor to check if it compiles and if there's error and the editor immediately crashes and shows the DirectX Error.

**Flax version:**

1.4.6334

**Comment by mafiesto4** [comment]
The shader has several issues (compilation) but also after running Debug build with DirectX Debug layer it outputs:
```
D3D11 ERROR: ID3D11Device::CreateInputLayout: The provided input signature expects to read an element with SemanticName/Index: 'TEXCOORD'/0, but the declaration doesn't provide a matching name. [ STATE_CREATION ERROR #163: CREATEINPUTLAYOUT_MISSINGELEMENT]
```

So the problem is with the shader. Use Debug build of the FlaxEditor to have nice debug output from DirectX driver (`<engine>\Binaries\Editor\Win64\Debug\FlaxEditor.exe`).
