### ISSUE TITLE
Animation Graph causes crash

### ISSUE THREAD

**Issue by kerelape** [FlaxEngine/FlaxEngine#746]
Editor crashes when I change Root Motion state from `No Extraction` to `Enabled`.

[Log.txt](https://github.com/FlaxEngine/FlaxEngine/files/9532417/Log.txt)

Steps to reproduce: 
- Create an AnimationGraph;
- Enable root motion (may be done after the next step)
- Connect an animation node (with root motion enabled) to the output.

**Comment by kerelape** [comment]
If no nodes are connected to the output then works fine.

**Comment by kerelape** [comment]
[This assertion fails](https://github.com/kerelape/FlaxEngine/blob/2c4d578f7c7a58e21505919fc7a00f6d35d2189e/Source/Engine/Animations/Graph/AnimGroup.Animation.cpp#L48-L49)

**Comment by mafiesto4** [comment]
Fixed in c62efdc44a11fa8ed1bbd8ade5a9acdc2ec5c1af.
