### ISSUE TITLE
[QUESTION] Missing Android SDK and Vulkan SDK in Linux

### ISSUE THREAD

**Issue by MateusDornelles** [FlaxEngine/FlaxEngine#747]
Hi, how does the build program search for the android SDK and the vulkan SDK in Linux  ? I have both of them installed and when I run GenerateProjectFiles.sh it returns : 

Missing Android SDK. Cannot build for Android platform.
Building for Linux without Vulkan rendering backend (Vulkan SDK is missing)

Thanks.

**Comment by mafiesto4** [comment]
For Vulkan: set env variable `VULKAN_SDK`
For Android SDK: set env variable `ANDROID_SDK` for SDK and `ANDROID_NDK` for NDK
