### ISSUE TITLE
Terminology

### ISSUE THREAD

**Issue by kerelape** [FlaxEngine/FlaxEngine#750]
https://github.com/FlaxEngine/FlaxEngine/blob/66b452e90c6ae9f05dc9625b5978ac1aab2d316f/Source/Editor/Windows/SplashScreen.cpp#L29

Shouldn't we use `delete` instead of `remove`? It seems to be more common for windows to say `delete` rather than `remove`

**Comment by mafiesto4** [comment]
I'm not sure if it makes large difference.
