### ISSUE TITLE
DDGI adds "splotches" on terrain

### ISSUE THREAD

**Issue by Wolfos** [FlaxEngine/FlaxEngine#754]
When a light probe is close to the terrain (or intersects it), it will leave this kind of artifact:
![image](https://user-images.githubusercontent.com/695652/191710595-732f5721-bbfa-423d-84ef-d756c591edab.png)

**Comment by mafiesto4** [comment]
Fixed in 5c5fad6bb4f672886bcaeab441d2d19a33fa939a and 66f93744779120e8957f7d0d4e579a4d5511ed97.
