### ISSUE TITLE
Texture is not loading using guid

### ISSUE THREAD

**Issue by Leonidas300** [FlaxEngine/FlaxEngine#757]
Hello i have an issue with loading texture using guid.

`var guid = Guid.Parse("b914e1834270dd59a27bb1bda45275e6");
var tex = Content.Load<Texture>(guid);`

Tex is null always null. GUID is copied from editor with right mouse button-> copy asset id.
When I used new GUID instead Guid.Parse I get an error that GUID is not valid. So I think it's right way to do it.

I'm wrighting a simple plugin and wanted to load the texture but I can't.
When I use Content.GetEditorAssetPath(guid); it returns empty string.

**Flax version:**
1.4.6334

**Comment by mafiesto4** [comment]
You need to use `FlaxEngine.Json.ParseID("")` instead because it uses Flax-style of `Guid` (matches out C++ implementation) - Microsoft's GUID string is in a different format.

**Comment by Leonidas300** [comment]
> You need to use `FlaxEngine.Json.ParseID("")` instead because it uses Flax-style of `Guid` (matches out C++ implementation) - Microsoft's GUID string is in a different format.

Well I dont have ParseID function Visual Studio reads FlaxEngine.Json as namespace
Screenshot below
![Ashampoo_Snap_wtorek, 11 października 2022_07h19m15s_002_](https://user-images.githubusercontent.com/187730/195003540-88c1d093-da04-4dd6-bd55-c4249ee63efd.png)

**Comment by mafiesto4** [comment]
@Leonidas300 Ah sorry I meant `FlaxEngine.Json.JsonSerializer.ParseID`
