### ISSUE TITLE
Is it possible to integrate FlaxEngine into juce? 

### ISSUE THREAD

**Issue by iomeone** [FlaxEngine/FlaxEngine#76]
First , thank you for the amazing project ! 

I want to integrate flaxEngine into juce : https://github.com/juce-framework/JUCE

It has an opengl demo https://github.com/juce-framework/JUCE/blob/master/examples/GUI/OpenGLAppDemo.h
When you inherit OpenglAppComponent like at line 57, then you can draw your own thing using opengl. 
(as at line 100
https://github.com/juce-framework/JUCE/blob/7c797c8105c2d41872e6e8d08972624f0afd335d/examples/GUI/OpenGLAppDemo.h#L100)
    

Thank you for you time again !

**Comment by jb-perrier** [comment]
I don't know JUCE, but unfortunatly Flax has no OpenGL backend.

**Comment by iomeone** [comment]
> I don't know JUCE, but unfortunatly Flax has no OpenGL backend.

Ok, I see.  I thought flax support opengl, but it not.

Thanks anyway!
