### ISSUE TITLE
Fatal error when trying to set texture for terrain

### ISSUE THREAD

**Issue by sergeyvolkovich** [FlaxEngine/FlaxEngine#761]
**Issue description:**

If i trying to change terrain texture i get weird error.
![Снимок экрана от 2022-10-06 01-52-23](https://user-images.githubusercontent.com/104814533/194178239-a2583be0-83b8-4de1-972e-87902ab5545f.png)
P.S. 
my configuration is ArchLinux.
I5-2500k
8gb ram
r5-240

**Steps to reproduce:**

Create new scene, remove floor, and add terrain after that try, assign material in material submenu causes crash given with error.

**Minimal reproduction project:**

[Temp.zip](https://github.com/FlaxEngine/FlaxEngine/files/9719467/Temp.zip)

**Flax version:**

1.4

**Comment by mafiesto4** [comment]
It looks like an old GPU problem that doesn't have a proper Vulkan driver.
