### ISSUE TITLE
Script requirements

### ISSUE THREAD

**Issue by kerelape** [FlaxEngine/FlaxEngine#769]
Is there a way to specify what type of Actor a script can be attached to? Something like `[ActorType(typeof(Camera))]`. Also a tool to require other components to be beside the script like unity's `RequireComponent`?

**Comment by mafiesto4** [comment]
We have sth similar planned don a roadmap to require the script to be added in a fixed setup (eg. only to Camera actor). Thanks for bringing it up, we can prioritize it.

**Comment by brmassa** [comment]
The same for Prefab, allowing us to specify the class I want.

**Comment by Tryibion** [comment]
Completed in #1948
