### ISSUE TITLE
Replace JSON asset dropdown for autocomplete

### ISSUE THREAD

**Issue by brmassa** [FlaxEngine/FlaxEngine#771]
Figat, when creating a new JSON asset, there is a dialog box asking what class it should contain.

It's presented as a dropdown combo box, which is tedious when we have dozens or even hundreds of classes to choose from.

I suggest to replace it for a text field with autocomplete. Or drag and drop.

**Comment by mafiesto4** [comment]
It actually contains a search field where you can find type to create an asset. We support many types not to restrict users:

![image](https://user-images.githubusercontent.com/3464853/195898234-74439f35-f603-4a3a-81a5-24493fc7ddfd.png)

Maybe some hierarchy would be good or mentioned autocomplete but that's a lot of work for a simple thing in Editor.

**Comment by brmassa** [comment]
true. did not know this.
closing.
