### ISSUE TITLE
Unity's ScriptableObject's singleton-like behaviour for custom JSON Data asset

### ISSUE THREAD

**Issue by brmassa** [FlaxEngine/FlaxEngine#774]
Guys,

In Flax we can create custom json data but Unity's ScriptableObject goes beyond: the class has a singleton-like instantiation, so every Actor or Prefab that points to the same JSON Data would, in fact, share the same final object.

We have to instantiate JSON Data in each script, which not only creates multiple copies of the same data, but also cannot be easily used as a shared copy of data for multiple scripts.

So, the relevant ASSET is not the text file containing the JSON data, but the instantiated class. That is the asset.

regards

**Comment by mafiesto4** [comment]
JsonAsset in Flax have cached instance object: https://docs.flaxengine.com/manual/scripting/tutorials/custom-asset.html?tabs=code-csharp#4-use-asset-in-game (works for both C++ and C#). Even `SetInstance` can be used from C# to update C++ instance data.
