### ISSUE TITLE
Bug - Spline colliders mesh apparently don't deform correctly on cooked game when change keyframes

### ISSUE THREAD

**Issue by cristhofermarques** [FlaxEngine/FlaxEngine#775]
Spline colliders mesh apparently don't deform correctly on cooked game when change keyframes.

**Issue description:**

Bug video : https://youtu.be/GwDFUzTQ5jk

In my code, I do update the spline after each point movement. I don't know if I need to update something else.

**Steps to reproduce:**

**Minimal reproduction project:**

![image](https://user-images.githubusercontent.com/65502434/196232585-4654ed31-731f-44e9-9c0c-772cc4d2d55c.png)

**Flax version:**
Master branch

**Comment by mafiesto4** [comment]
Do you use **Support Cooking At Runtime** option from Physics Settings?
Docs: https://docs.flaxengine.com/manual/physics/colliders/collision-data.html#create-collision-data-from-code

**Comment by cristhofermarques** [comment]
No way, I forgot that, It's working. Thank you!
