### ISSUE TITLE
Will a gameplay system like Unreal Engine be added in the future?

### ISSUE THREAD

**Issue by CeSun** [FlaxEngine/FlaxEngine#778]
There are too many general-purpose engines on the market, and small studios and individual developers may need an engine that directly develops game logic without building wheels.

**Comment by Tryibion** [comment]
They are working on one right now called the Arizona Framework. You can see its development process on the roadmap -> https://trello.com/b/NQjLXRCP/flax-roadmap

**Comment by mafiesto4** [comment]
Exactly, the upcoming `Arizona Framework` will be a great foundation for many third-person, first-person games (shooters, RPGs) but also racing games. It will contain AI tools, camera utilities, Game Mode / Players, and Multiplayer support. It is developed as a part of our internal game production. We plan to release it soon to the public (with source code).
