### ISSUE TITLE
Black circle around the object in the model tab

### ISSUE THREAD

**Issue by PhyresiCompany** [FlaxEngine/FlaxEngine#779]
**Issue description:**

When I open a model tab, a black circle appears around my object.
When I maximize the tab the problem is solved as the black circle disappears

![Captura de Tela (411)](https://user-images.githubusercontent.com/101017436/196771537-3187d515-5902-4b91-9799-68f2d89a8cab.png)
![Captura de Tela (412)](https://user-images.githubusercontent.com/101017436/196771549-e9fb6df3-0fca-45fd-9026-ec1b319ccee7.png)

**Flax version:**
1.4

**Comment by mafiesto4** [comment]
Most likely due to large difference between Near and Far planes of the preview camera. Can be adjusted Via **View -> ..** options.
