### ISSUE TITLE
Auto LOD Generation Problem

### ISSUE THREAD

**Issue by RuanLucasGD** [FlaxEngine/FlaxEngine#784]
**Issue description:**

Automatic LOD generation problem:

***Original Model***
![image](https://user-images.githubusercontent.com/79365912/196853927-df3d406d-ab88-48f4-ad02-5ffb3cc26ac0.png)

***Unreal Auto LOD Generation (LOD Index 1/4)***
![image](https://user-images.githubusercontent.com/79365912/196854064-c7cfe5ee-5e59-4dc1-8351-3a846aff51b0.png)

***Flax Auto LOD Generation (LOD Index 1/4)***
![image](https://user-images.githubusercontent.com/79365912/196854215-0e383135-417b-4af6-969b-757763470f59.png)

Is there any specific import configuration to be able to generate the LOD without damaging the UV?

[MyProject.zip](https://github.com/FlaxEngine/FlaxEngine/files/9826152/MyProject.zip)

**Flax version:1.4.6334**

**Comment by mafiesto4** [comment]
Have you tried adjusting **Triangle Reduction** property on import settings? Flax default option might be too aggressive for this model thus producing worse results.

**Comment by RuanLucasGD** [comment]
even changing **Triangle Reduction** the problem still occurs, this also happened in other models

![image](https://user-images.githubusercontent.com/79365912/197423432-b25de434-b08d-442f-bf79-8ab8d9ed7e53.png)
![image](https://user-images.githubusercontent.com/79365912/197423413-1ba180fc-d3ca-4c09-bb4d-1ba17283e729.png)

**Comment by WolfPascal** [comment]
Same issue here:
It seems that during the automatic LOD generation while importing an FBX file, the texture / UV maps are scaled incorrectly. Attached is also the texture and a simple image of the UV mappings in Blender.

![grafik](https://github.com/FlaxEngine/FlaxEngine/assets/28809282/743bf07e-30f9-4f3c-b9c0-4234a1ff9a2d)
![grafik](https://github.com/FlaxEngine/FlaxEngine/assets/28809282/c026a070-0c94-4885-a872-02da2f067ec7)
![grafik](https://github.com/FlaxEngine/FlaxEngine/assets/28809282/fdc269db-1949-4161-a237-7b92333a66e0)
![grafik](https://github.com/FlaxEngine/FlaxEngine/assets/28809282/d9ec1d95-3a38-4be8-835b-04488ee93356)

**Comment by mafiesto4** [comment]
Could you attach a source model file with texture so we can improve the importer?

For upcoming Flax 1.7 we've added new options `Sloppy Optimization` and `LOD Target Error` which can be used to adjust LOD algorithm to be less aggressive and preserve more data. Maybe we should do it by default.

**Comment by RuanLucasGD** [comment]
@mafiesto4 @WolfPascal i made some tests and disabling Sloppy Optimization and setting target error to < 0.1 fix this problem
