### ISSUE TITLE
Audio can't loop!!

### ISSUE THREAD

**Issue by uotsab** [FlaxEngine/FlaxEngine#786]
**Issue description:**
The audio isn't looping even if IsLooping turned on AudioSource component. It meant to loop otherwise.

**Flax version:**
Flax Engine 1.4

**Comment by mafiesto4** [comment]
Fixed by #765 in https://github.com/plemsoft/FlaxEngine/commit/fd831f569c542a7100702f162e704e1bd3e59f5a and in 57e812d336e6470ce2b853e916fd4a31f36ca360
