### ISSUE TITLE
Crtl+S and/or auto-save on Prefab/JsonAsset dialog window

### ISSUE THREAD

**Issue by brmassa** [FlaxEngine/FlaxEngine#789]
Would be great to auto-save Prefabs and JsonAsstes changes while in the dialog window, just like Actors edited in the inspector.
At least a Crtl+s to save via keyboard.

As a bonus, we have to press exit the field (pressing enter) in order to register the field change. If one opens an asset, changes a value and closes the window immediately, without "registering" the change, all is lost. Consider implementing input registration for each key pressed, just like the autocomplete field.

**Comment by mafiesto4** [comment]
You can use Editor Options to configure auto-save: https://docs.flaxengine.com/manual/editor/options/index.html

**Comment by brmassa** [comment]
Auto save content respects the Frequency value, which does not make sense when editing an asset. It should be instantaneous on each value changed.
The Ctrl+S shortcut also do not work on the dialog.
Should I open another issue?

**Comment by mafiesto4** [comment]
Ah right, there is an issue with keyboard focus on Json Asset and input fields so Ctrl+S shortcut doesn't work.

**Comment by mafiesto4** [comment]
Fixed in e713273942c43faf8c8e25e16701a0b1ba8d8a46
