### ISSUE TITLE
Hinge Joint: Can't set drive velocity to negative values

### ISSUE THREAD

**Issue by abgenullt** [FlaxEngine/FlaxEngine#79]
Hi,

it is not possible to set the velocity of a hinge joint drive (maybe affects other joints, too) to a negative value, to rotate it in the other direction. The value always goes back to zero, if you try that.

Regards
abgenullt

**Comment by mafiesto4** [comment]
According to PhysX we cannot set it to a negative value (Flax performs clamp before calling lib function).
![image](https://user-images.githubusercontent.com/3464853/103383603-9c9d6080-4af3-11eb-93ee-41134b4bc620.png)

**Comment by abgenullt** [comment]
This could be really an issue here. The documentation is very confusing at this point.

It also says that "**The sign of this variable determines the rotation direction**".
I've created this issue https://github.com/NVIDIAGameWorks/PhysX/issues/373. 

Unfortunately I can't try this out myself but it would make sense that negative values are used to spin the other direction.

Regards
abgenullt

**Comment by Menotdan** [comment]
@mafiesto4 should this be re-opened temporarily? It looks like the range was in fact wrong in the docs, and it can be negative.
