### ISSUE TITLE
OnValidade method on Script

### ISSUE THREAD

**Issue by brmassa** [FlaxEngine/FlaxEngine#791]
Similar to Unity's MonoBehabiour, OnValidade method called by Editor and Runtime on loading the asset or on changing a field value.

Benefits: 
* It would be a workaround of issue #790 , allowing to check if the Prefab/JsonAsset/Actor field is pointing to a given class.
* Custom validation when entering values (i.e. using 2 floats for a range so one should be less or equal to the second)

**Comment by mafiesto4** [comment]
That's why you can use properties in C# and implement custom value validation in the setter method. No need for a custom Unity
style extensions.

**Comment by brmassa** [comment]
There is another use case that I often use: automatically rename the asset based on a mix of values. 

i.e.:
...
var newAssetName = "item " + this.Title +" "+ this.Level;
...

(it's Editor only)

@ mafiesto4,  How you suggest to implement this?

**Comment by mafiesto4** [comment]
You can make own `OnValidate` method and invoke it from all setters to perform validation for multiple properties.

**Comment by brmassa** [comment]
okay
