### ISSUE TITLE
CursorVisible and CursorLock not working in OnStart method

### ISSUE THREAD

**Issue by PhyresiCompany** [FlaxEngine/FlaxEngine#799]
**Steps to reproduce:**

https://user-images.githubusercontent.com/101017436/197611097-d409a418-fa70-4657-944b-39c4d4f416f3.mp4

**Minimal reproduction project:**
https://drive.google.com/file/d/12q9oBQVy5bQdJh8xf7-qcYsGP1EyyrhW/view?usp=sharing

**Flax version:**
1.4

**Comment by mafiesto4** [comment]
Fixed in e1836a222c9597d57ad27af74d38082cbab2ff63.
