### ISSUE TITLE
High CPU usage when editor run for long time (overnight)

### ISSUE THREAD

**Issue by Mummrik** [FlaxEngine/FlaxEngine#80]
**Issue description:**
I left the editor open overnight and resulted in very high cpu usage

**Steps to reproduce:**
Start editor and then just let it idle

**Screenshot:**

![bild](https://user-images.githubusercontent.com/33917460/103392396-f61a8500-4b1d-11eb-90e6-14df0e4b4c9f.png)

**Flax version:**
1.0.6214

**Comment by honzapatCZ** [comment]
I suppose this was some memory leak or something like that. I have regularly open Flax now and its ok even with pc being up for a whole month.

**Comment by mafiesto4** [comment]
We've got many improvements to stability and lower-perf usage of Editor which solved this: e06200926f474597e433b3f24d8f18dcdf507439 + da149d32cf7bb5f110252f4f7f80e210edfd1841. Finally, Editor will reduce FPS and usage when not focused (can be configured in Editor Options now.
