### ISSUE TITLE
Problem with Destroy Actor

### ISSUE THREAD

**Issue by PhyresiCompany** [FlaxEngine/FlaxEngine#800]
**Issue description:**
When an actor is destroyed, variables that reference that actor are not automatically set to null.

**Steps to reproduce:**

https://user-images.githubusercontent.com/101017436/197612283-8b0d7d80-ebef-4074-ab95-fbd004d66992.mp4

**Minimal reproduction project:**
https://drive.google.com/file/d/12q9oBQVy5bQdJh8xf7-qcYsGP1EyyrhW/view?usp=sharing

**Flax version:**
1.4

**Comment by PhyresiCompany** [comment]
> The actor references are not set to null, but you can check if the reference is valid with `if (control)`

I did that but it didn't solve the problem. As the variable is not null, **if will return true**
![Captura de Tela (440)](https://user-images.githubusercontent.com/101017436/197622437-30072bd6-2522-4053-a7cc-6852e15fc100.png)

**Comment by GoaLitiuM** [comment]
Invalid actor references are not always `null`, that's why the check fails. You need to use the implicit boolean operator to check if the reference is still valid (this additionally checks against `null`-values too):
```csharp
if (playerTransform) Actor.Position = playerTransform.Position + camOffSet;
```

**Comment by PhyresiCompany** [comment]
> Invalid actor references are not always `null`, that's why the check fails. You need to use the implicit boolean operator to check if the reference is still valid (this additionally checks against `null`-values too):
> 
> ```cs
> if (playerTransform) Actor.Position = playerTransform.Position + camOffSet;
> ```

Not working 

https://user-images.githubusercontent.com/101017436/198126513-c9690c09-ee8e-46b5-a00b-e01544058dde.mp4

**Comment by PhyresiCompany** [comment]
> Invalid actor references are not always `null`, that's why the check fails. You need to use the implicit boolean operator to check if the reference is still valid (this additionally checks against `null`-values too):
> 
> ```cs
> if (playerTransform) Actor.Position = playerTransform.Position + camOffSet;
> ```

To work without error I have to manually set the variable to null

Scene.FindScript<Camera>().playerTransform = null;
Scene.FindScript<Game.ManagerUI>().player = null;

**Comment by PhyresiCompany** [comment]
> Invalid actor references are not always , that's why the check fails. You need to use the implicit boolean operator to check if the reference is still valid (this additionally checks against -values too):`null``null`
> 
> ```cs
> if (playerTransform) Actor.Position = playerTransform.Position + camOffSet;
> ```

Thanks it worked, I had another script that also had my reference from my player. I used if()
