### ISSUE TITLE
Editor: improving List<> visual in inspector

### ISSUE THREAD

**Issue by brmassa** [FlaxEngine/FlaxEngine#803]
Lists<> are displayed in the inspector as uniform mass of items. It's hard to visually identify each item.  Suggest some QoL improvements

* odd/even background color
* margin/line between elements
* reduce a lot the size of each item's label ("Element 0", "Element 1", etc), since it's wasted space. Consider using only number with minimal width, given more space for the elements's own sub items.

![image](https://user-images.githubusercontent.com/13696218/197888450-bad60ce1-d3e5-4a15-8c61-276d1e6c7258.png)

**Comment by mafiesto4** [comment]
Yeah we should improve it visually to have better editing.

**Comment by mafiesto4** [comment]
Improved in #2208
