### ISSUE TITLE
Editor: Add arrow to indicate Actor components collapsed/opened state

### ISSUE THREAD

**Issue by brmassa** [FlaxEngine/FlaxEngine#805]
In the inspector, there is no visual cue to indicate that a certain category (General, Transform, Script, Control, etc) is collapsed or just empty. Suggest to add the same arrow used on drop combobox.

#QoL

![image](https://user-images.githubusercontent.com/13696218/197891554-956e1fcc-6c4b-4a92-b329-4389da2e702f.png)

**Comment by mafiesto4** [comment]
Implemented in #903
