### ISSUE TITLE
Flax not importing FBX Models from Desktop folder - Windows 11

### ISSUE THREAD

**Issue by RuanLucasGD** [FlaxEngine/FlaxEngine#806]
**Issue description:**

Any fbx model that is in the Desktop folder cannot be imported. The import window appears normally but when I click import, nothing happens.

[2022-10-25 22-56-47.webm](https://user-images.githubusercontent.com/79365912/197924048-bb2c6e87-9347-46ea-a813-9319423b6b9e.webm)

**Log:**
[ 00:04:00.649 ]: [Info] Importing file 'C:\Users/T-GAMER/OneDrive/Área de Trabalho/corolla 1980.fbx' to 'C:\Users/T-GAMER/OneDrive/Documentos/Flax Projects/MyProject/Content/corolla 1980.flax'...
[ 00:04:00.649 ]: [Info] Importing model from 'C:\Users/T-GAMER/OneDrive/Área de Trabalho/corolla 1980.fbx'
[ 00:04:00.649 ]: [Warning] Win32::GetLastError() = 0x2
[ 00:04:00.649 ]: [Error] Cannot import model file. Cannot load file.
[ 00:04:00.649 ]: [Error] Cannot import file 'C:\Users/T-GAMER/OneDrive/Área de Trabalho/corolla 1980.fbx'! Result: Error
[ 00:04:00.649 ]: [Warning] Failed to import C:\Users\T-GAMER\OneDrive\Área de Trabalho/corolla 1980.fbx to C:\Users/T-GAMER/OneDrive/Documentos/Flax Projects/MyProject/Content\corolla 1980.flax

Windows 11 Home Single
Version	21H2
Flax Engine Version: 1.4

**Comment by mafiesto4** [comment]
Fixed 6a5efdeb29db0b9fb3f30420425480ac6d89b338
