### ISSUE TITLE
3D sound getting distorted

### ISSUE THREAD

**Issue by CthulhuBaba** [FlaxEngine/FlaxEngine#815]
**Issue description:**
When the camera moves, the 3D sound is getting distorted. It's like the pitch is going up and down all of a sudden. You can listen from the link I gave.

I am using 16 bit mono wav for audio. I attached the Audio Listener to the camera. Audio Source settings are in defaut.

https://youtu.be/EHPR2ribFsk

**Flax version:**
1.4.6334

And here is the sound file, if you want to try: https://drive.google.com/file/d/13YcJ50TUq5syMAUhTGlqwC_x1z23rJ0G/view?usp=sharing

**Comment by mafiesto4** [comment]
I gave it a try and it was playing fine for me when I rotated the camera but maybe will need to test it again.

**Comment by CthulhuBaba** [comment]
Could you check this project? I deleted everything in the project, only the sounds remained. Yet the problem persists. 
https://drive.google.com/file/d/1dsvb-8ycIEN3mVQF5sOr7FcFGmv0pQhl/view?usp=share_link

**Comment by mafiesto4** [comment]
Okay so the problem exists in that project but it's due to an invalid setup:
Audio Listener attached to the Camera is moved and rotated thus making the unrealistic behavior - it should be placed very close to the camera just like human ears.

Also, `Min Distance` set to `0` on Audio Source makes the audio more like 2D (no attenuation) thus it would be better to use a bigger value for background bird noises (eg. 3000) or even make it a non-3D sound.

**Comment by CthulhuBaba** [comment]
Oh sorry for taking your time. Now the problem is gone but there is another problem. The sizes/scales of the models in my map are ten times larger than the standard model size.  So I need to move the camera fast. Let's say "MoveSpeed=300;"

In this case, the sound is still distorted due to the speed of the camera. Is there any way to prevent this?

**Comment by mafiesto4** [comment]
@CthulhuBaba You could try adjusting `DopplerFactor` in Audio Settings. Maybe it can help reduce this doppler-effect. due to high velocity movement2

**Comment by PrecisionRender** [comment]
> Okay so the problem exists in that project but it's due to an invalid setup:
> Audio Listener attached to the Camera is moved and rotated thus making the unrealistic behavior - it should be placed very close to the camera just like human ears.

@mafiesto4 Would you care to elaborate? I can't seem to find a setup that works correctly. Simply attaching the audio source to the character's head in a 3rd person context doesn't take into account where the player camera is and where it's looking, and most 3rd person games play audio relative to the camera, not the character itself.

**Comment by mafiesto4** [comment]
Fixed in:
* #963 - OpenAL coords were invalid
* dd9fa6e949b1168c4de8b25fbce9cdf73fa24612 - audio velocity passed to OpenAL/XAudio was too high (in cm^2 instead of m^2)

Now, the doppler effect sounds fine and your audio plays properly when camera moves around it.

**Comment by mafiesto4** [comment]
+ added `Doppler Factor` property per-source to manually control that effect eb613d3e8a8f49628c2b86f7251ce5485f58efe8
