### ISSUE TITLE
Using Smooth Mode/Brush causes chunks to split

### ISSUE THREAD

**Issue by CthulhuBaba** [FlaxEngine/FlaxEngine#817]
**Issue description:**
When I use the Smooth Mode in the ToolBox to edit the terrain, the chunks are getting splitted/disconnected. I showed all the steps in the video. https://youtu.be/GB-9TSAWNPw

**Flax version:**

1.4.6334
![smoothbrush](https://user-images.githubusercontent.com/31192693/200015211-2d1ca905-0747-4a9d-9d55-69f52db94202.jpg)

**Comment by AlTheSlacker** [comment]
I can see why this happens. In \FlaxEngine\Source\Editor\Tools\Terrain\Sculpt\SmoothMode.cs a bug is introduced where the code attempts to get the average height of the surrounding points, there are some Math.Max functions to prevent the heightmap request going out of range for a given patch, but this results in the values used to calculate the average height for the brush becoming dependent upon which patch is being used: When you brush near the patch boundaries you get inconsistent values. I couldn't figure a quick fix as you need to be able to sample from adjacent patches, which for me at least would significantly change this code. Smoothing is still broken for any terrain more than 1x1 patch in size as a result of this.

**Comment by AlTheSlacker** [comment]
Thanks for the fix. I see in your comments you talk about viewing the terrain height data as a single set of data: If it is of any use to you, this was my approach in https://github.com/AlTheSlacker/FlaxProcTerrain where I dump the entire terrain into a float array. In-editor performance seems good enough, if you want to take any code, help yourself.
