### ISSUE TITLE
editor crashed when click "build" button

### ISSUE THREAD

**Issue by cloud42** [FlaxEngine/FlaxEngine#82]
**Issue description:**

 when click "build" button at "game cooker" window, editer crashed, everytime...
but, there was a flaxgame.exe be created in 'Output\Win64', and run it ,say "can't load game",  and exit.

**Steps to reproduce:**

1.  new project  
2.  play it on game window, it's ok.
3.  open "game cooker" window, click "build" button,  then crashed.

**Minimal reproduction project:**

**Flax version:**

editor version: 1.0.6214

    ================================================
                SOME LOGFILE
    ================================================
    [ 00:00:47.330 ]: [Info] Restored previous scenes
    [ 00:00:47.340 ]: [Info] [PlayMode] Exit
    [ 00:01:09.181 ]: [Warning] Unknown asset type 'FlaxEditor.Content.Settings.PS4PlatformSettings' to use for asset picker filter.
    [ 00:01:09.183 ]: [Warning] Unknown asset type 'FlaxEditor.Content.Settings.XboxScarlettPlatformSettings' to use for asset picker filter.
    [ 00:05:09.676 ]: [Info] Auto save
    [ 00:10:09.980 ]: [Info] Auto save
    [ 00:10:35.447 ]: [Info] Building target
    [ 00:10:35.514 ]: [Info] Thread 'Game Cooker' ID=0x27b4 started with priority Highest
    [ 00:10:35.514 ]: [Info] Starting Game Cooker...
    [ 00:10:35.514 ]: [Info] Platform: Windows x64, Configuration: Development, Options: 0
    [ 00:10:35.514 ]: [Info] Output Path: E:\Flax_game_engine/flax_prjs/MyProject3/Output/Win64
    [ 00:10:35.516 ]: [Info] Starting scripts compilation for game...
    [ 00:10:35.517 ]: [Info] Command: "E:\Flax_game_engine/flax_engine/Flax_1.0/Binaries/Tools/Flax.Build.exe" -log -logfile="E:\Flax_game_engine/flax_prjs/MyProject3/Cache/Cooker/Windows/CompileLog.txt" -build -mutex -buildtargets=GameTarget -platform=Windows -arch=x64 -configuration=Development
    [ 00:10:40.285 ]: [Error] Not a UTF-8 string.
    [ 00:10:40.285 ]: [Info] 
    [ 00:10:40.285 ]: [Info] Deploying binaries from build E:\Flax_game_engine/flax_prjs/MyProject3/Binaries/GameTarget/Windows/x64/Development/GameTarget.Build.json
    [ 00:10:40.285 ]: [Info] Deploying binaries from build E:\Flax_game_engine/flax_engine/Flax_1.0/Source/Platforms/Windows/Binaries/Game/x64/Development/FlaxGame.Build.json
    [ 00:10:40.285 ]: [Info] Collecting binary module FlaxEngine
    [ 00:10:40.338 ]: [Info] Collecting binary module Game
    ================================================================
    [ 00:10:43.337 ]: [Error] 
    [ 00:10:43.337 ]: [Error] Critical error! Reason: Unhandled exception: EXCEPTION_ACCESS_VIOLATION reading address 0x38620000
    [ 00:10:43.337 ]: [Error] 
    [ 00:10:43.338 ]: [Info] Editor exit
    [ 00:10:43.338 ]: [Info] Changing editor state from FlaxEditor.States.EditingSceneState to FlaxEditor.States.ClosingState
    [ 00:10:43.341 ]: [Info] Select code editor null
    [ 00:10:43.347 ]: [Info] Main window is closing, reason: EngineExit
    [ 00:10:43.351 ]: [Info] Main window is closed
    [ 00:10:43.351 ]: [Info] Capture project icon screenshot
    [ 00:10:43.697 ]: [Error] Stack trace:
    [ 00:10:43.697 ]: [Error]     at VCRUNTIME140.dll::memcmp
    [ 00:10:43.697 ]: [Error] 
    [ 00:10:43.697 ]: [Error] Used Physical Memory: 5.19 GB (65%)
    [ 00:10:43.697 ]: [Error] Used Virtual Memory: 4.73 GB (0%)
    [ 00:10:43.697 ]: [Error] Process Used Physical Memory: 411.52 MB
    [ 00:10:43.697 ]: [Error] Process Used Virtual Memory: 417.24 MB
    [ 00:10:43.697 ]: [Error] Creating Mini Dump to E:\Flax_game_engine/flax_prjs/MyProject3/Logs/Crash_2021_01_02_03_15_00/Minidump.dmp
    [ 00:10:43.934 ]: [Error] 
    ================================================================
    [ 00:10:43.943 ]: [Error] Crash info collected.
    ================================================================

**Comment by Momodecangshu** [comment]
I met this yet!!!

**Comment by DisownedWheat** [comment]
I'm having the exact same issue in Flax 1.1

Log:
`================================================================
           Start of the log, 2021-04-01 09:06:18
================================================================
[ 00:00:00.004 ]: [Info] Flax Engine
[ 00:00:00.004 ]: [Info] Platform: Windows x64 (Development)
[ 00:00:00.004 ]: [Info] Version 1.1.6217
[ 00:00:00.004 ]: [Info] Compiled: Mar 28 2021 16:26:59
[ 00:00:00.004 ]: [Info] Compiled with Visual C++ 19.00.24245.00
[ 00:00:00.004 ]: [Info] Product: Flax Editor, Company: Flax
[ 00:00:00.004 ]: [Info] Current culture: en-AU
[ 00:00:00.004 ]: [Info] Command line: -project 'C:\Users\xxx\Documents\Flax Projects\FlaxSamples\ThirdPersonShooterTemplate'
[ 00:00:00.004 ]: [Info] Base directory: C:\Program Files (x86)/Flax/Flax_1.1
[ 00:00:00.004 ]: [Info] Temporary folder: C:\Users/xxx/AppData/Local/Temp/7c8fd5c0-43d4-1cff-92cb-278bb4fc621d
[ 00:00:00.004 ]: [Info] Project folder: C:\Users/xxx/Documents/Flax Projects/FlaxSamples/ThirdPersonShooterTemplate
[ 00:00:00.004 ]: [Info] Project name: ThirdPersonShooter
[ 00:00:00.004 ]: [Info] Computer name: SN-LPT-D001
[ 00:00:00.004 ]: [Info] User name: rob
[ 00:00:00.004 ]: [Info] CPU package count: 1, Core count: 4, Logical processors: 8
[ 00:00:00.004 ]: [Info] CPU Page size: 4 KB, cache line size: 64 bytes
[ 00:00:00.004 ]: [Info] L1 cache: 256 KB, L2 cache: 1 MB, L3 cache: 8 MB
[ 00:00:00.004 ]: [Info] Clock speed: 10 GHz
[ 00:00:00.005 ]: [Info] Physical Memory: 15.81 GB total, 11.84 GB used (74.85%)
[ 00:00:00.005 ]: [Info] Virtual Memory: 128 TB total, 4.15 GB used (0%)
[ 00:00:00.005 ]: [Info] Main thread id: 0x44b0, Process id: 24040
[ 00:00:00.005 ]: [Info] Desktop size: X:3840 Y:2160
[ 00:00:00.005 ]: [Info] Virtual Desktop size: X:0 Y:0 Width:3840 Height:2160
[ 00:00:00.005 ]: [Info] Screen DPI: 96
[ 00:00:00.005 ]: [Info] Microsoft Windows 10 Pro 64-bit (10.0)
[ 00:00:00.005 ]: [Info] Last project open version: 1.1.6217
[ 00:00:00.006 ]: [Info] Initialize Objects Removal Service...
[ 00:00:00.006 ]: [Info] Initialize Thread Pool...
[ 00:00:00.006 ]: [Info] Spawning 3 Thread Pool workers
[ 00:00:00.006 ]: [Info] Initialize Time...
[ 00:00:00.006 ]: [Info] Thread 'Thread Pool 1' ID=0x2208 started with priority Normal
[ 00:00:00.006 ]: [Info] Thread 'Thread Pool 0' ID=0x4790 started with priority Normal
[ 00:00:00.007 ]: [Info] Initialize ContentStorageManager...
[ 00:00:00.007 ]: [Info] Initialize Font Manager...
[ 00:00:00.007 ]: [Info] Thread 'Thread Pool 2' ID=0x5040 started with priority Normal
[ 00:00:00.007 ]: [Info] FreeType initialized, version: 2.10.0
[ 00:00:00.007 ]: [Info] Initialize Content...
[ 00:00:00.007 ]: [Info] Loading Asset Cache C:\Users/xxx/Documents/Flax Projects/FlaxSamples/ThirdPersonShooterTemplate/Cache/AssetsCache.dat...
[ 00:00:00.017 ]: [Info] Asset Cache loaded 175 entries in 10 ms (0 rejected)
[ 00:00:00.017 ]: [Info] Initialize Content Loading Manager...
[ 00:00:00.017 ]: [Info] Creating 2 content loading threads...
[ 00:00:00.017 ]: [Info] Initialize AssetsImportingManager...
[ 00:00:00.017 ]: [Info] Initialize AssetsExportingManager...
[ 00:00:00.017 ]: [Info] Initialize Shader Cache Manager...
[ 00:00:00.017 ]: [Info] Thread 'Load Thread 0' ID=0x264c started with priority Normal
[ 00:00:00.017 ]: [Info] Thread 'Load Thread 1' ID=0x46e8 started with priority Normal
[ 00:00:00.017 ]: [Info] Initialize Shaders Compilation Service...
[ 00:00:00.018 ]: [Info] Thread 'File System Watchers' ID=0x2d70 started with priority BelowNormal
[ 00:00:00.018 ]: [Info] Initialize Debug Draw...
[ 00:00:00.018 ]: [Info] Initialize GameSettings...
[ 00:00:00.020 ]: [Info] Initialize Input...
[ 00:00:00.020 ]: [Info] Initialize Audio...
[ 00:00:00.020 ]: [Info] Audio system initialization... (backend: OpenAL)
[ 00:00:00.036 ]: [Info] OpenAL version 1.19.1
[ 00:00:00.036 ]: [Info] [active] Speakers / Headphones (Realtek Audio)
[ 00:00:00.036 ]: [Info] U28E850 (Intel(R) Display Audio)
[ 00:00:00.036 ]: [Info] Rebuild audio contexts
[ 00:00:00.068 ]: [Info] Rebuild audio contexts
[ 00:00:00.082 ]: [Info] Initialize Graphics...
================================================================
[ 00:00:00.082 ]: [Info] Creating Graphics Device...
[ 00:00:00.136 ]: [Info] Adapter 0: 'Intel(R) UHD Graphics 620', DirectX 11
[ 00:00:00.136 ]: [Info] 	Dedicated Video Memory: 128 MB, Dedicated System Memory: 0 B, Shared System Memory: 7.91 GB, Output(s): 1
[ 00:00:00.138 ]: [Info] Adapter 1: 'Microsoft Basic Render Driver', DirectX 11
[ 00:00:00.138 ]: [Info] 	Dedicated Video Memory: 0 B, Dedicated System Memory: 0 B, Shared System Memory: 7.91 GB, Output(s): 0
[ 00:00:00.141 ]: [Info] Video output '\\.\DISPLAY1' 3840x2160 59.9966 Hz
[ 00:00:00.184 ]: [Info] Total graphics memory: 4.08 GB
[ 00:00:00.184 ]: [Info] Graphics Device created! Adapter: 'Intel(R) UHD Graphics 620', Renderer: DirectX 11, Shader Profile: DirectX SM5, Feature Level: SM5
================================================================
[ 00:00:00.186 ]: [Info] Initialize Windows Manager...
[ 00:00:00.186 ]: [Info] Initialize Scripting...
[ 00:00:00.186 ]: [Info] Mono debugger server at 127.0.0.1:41040
[ 00:00:00.186 ]: [Warning] Win32::GetLastError() = 0xcb
[ 00:00:00.197 ]: [Info] Mono version: 5.20.1 (Visual Studio built mono)
[ 00:00:00.197 ]: [Info] Assembly corlib loaded in 0ms
[ 00:00:00.207 ]: [Info] Caching classes for assembly corlib took 10ms
[ 00:00:00.219 ]: [Info] Caching classes for assembly FlaxEngine took 8ms
[ 00:00:00.220 ]: [Info] Assembly FlaxEngine loaded in 13ms
[ 00:00:00.259 ]: [Info] Using FlaxAPI in Development
[ 00:00:00.260 ]: [Info] Main render task created
[ 00:00:00.260 ]: [Info] Scripting Engine initializated! (time: 74ms)
[ 00:00:00.260 ]: [Info] Initialize Animation Manager...
[ 00:00:00.260 ]: [Info] Initialize Custom Editors Util...
[ 00:00:00.265 ]: [Info] Assembly 'FlaxEngine' scanned for custom editors in 5 ms
[ 00:00:00.265 ]: [Info] Initialize Viewport Icons Renderer...
[ 00:00:00.268 ]: [Info] Initialize Scripts Builder...
[ 00:00:00.268 ]: [Info] Initialize Physics...
[ 00:00:00.268 ]: [Info] Setup NVIDIA PhysX 4.1.1
[ 00:00:00.269 ]: [Info] Initialize Code Editing Manager...
[ 00:00:00.274 ]: [Info] Initialize Profiling Tools...
[ 00:00:00.274 ]: [Info] Initialize Editor Analytics...
[ 00:00:00.274 ]: [Info] Editor analytics service is disabled.
[ 00:00:00.274 ]: [Info] Initialize Game Cooker...
[ 00:00:00.274 ]: [Info] Initialize Render2D...
[ 00:00:00.274 ]: [Info] Initialize Renderer...
[ 00:00:00.280 ]: [Info] Initialize Scene Manager...
[ 00:00:00.280 ]: [Info] Initialize Terrain Manager...
[ 00:00:00.280 ]: [Info] Initialize Atmosphere Pre Compute...
[ 00:00:00.280 ]: [Info] Initialize Navigation...
[ 00:00:00.280 ]: [Info] Initialize Particle Manager...
[ 00:00:00.280 ]: [Info] Initialize Probes Renderer...
[ 00:00:00.280 ]: [Info] Initialize ShadowsOfMordor Builder...
[ 00:00:00.280 ]: [Info] Initialize CSG Builder...
[ 00:00:00.280 ]: [Info] Initialize Streaming Manager...
[ 00:00:00.280 ]: [Info] Initialize Prefab Manager...
[ 00:00:00.280 ]: [Info] Initialize Screen...
[ 00:00:00.280 ]: [Info] Initialize Plugin Manager...
[ 00:00:00.280 ]: [Info] Engine services are ready!
[ 00:00:00.280 ]: [Info] Showing splash screen
[ 00:00:00.307 ]: [Info] Setting up C# Editor...
[ 00:00:00.519 ]: [Info] Loaded project Flax, version 1.1.6217
[ 00:00:00.545 ]: [Info] Loaded project ThirdPersonShooter, version 1.0
[ 00:00:00.557 ]: [Info] Register Editor module FlaxEditor.Options.OptionsModule
[ 00:00:00.560 ]: [Info] Register Editor module FlaxEditor.Modules.ProjectCacheModule
[ 00:00:00.561 ]: [Info] Register Editor module FlaxEditor.Modules.SceneModule
[ 00:00:00.561 ]: [Info] Register Editor module FlaxEditor.Modules.WindowsModule
[ 00:00:00.572 ]: [Info] Register Editor module FlaxEditor.Modules.UIModule
[ 00:00:00.574 ]: [Info] Register Editor module FlaxEditor.Content.Thumbnails.ThumbnailsModule
[ 00:00:00.575 ]: [Info] Register Editor module FlaxEditor.Modules.SimulationModule
[ 00:00:00.575 ]: [Info] Register Editor module FlaxEditor.Modules.PrefabsModule
[ 00:00:00.575 ]: [Info] Register Editor module FlaxEditor.Modules.SceneEditingModule
[ 00:00:00.575 ]: [Info] Register Editor module FlaxEditor.Modules.ContentEditingModule
[ 00:00:00.576 ]: [Info] Register Editor module FlaxEditor.Modules.ContentDatabaseModule
[ 00:00:00.576 ]: [Info] Register Editor module FlaxEditor.Modules.ContentImportingModule
[ 00:00:00.577 ]: [Info] Register Editor module FlaxEditor.Modules.SourceCodeEditing.CodeEditingModule
[ 00:00:00.581 ]: [Info] Register Editor module FlaxEditor.Modules.ProgressReportingModule
[ 00:00:00.582 ]: [Info] Register Editor module FlaxEditor.Modules.ContentFindingModule
[ 00:00:00.587 ]: [Info] Changing editor state from  to FlaxEditor.States.LoadingState
[ 00:00:00.592 ]: [Info] Editor init
[ 00:00:00.593 ]: [Info] Options file path: C:\Users\xxx\AppData\Roaming\Flax\EditorOptions.json
[ 00:00:00.593 ]: [Info] Loading editor options
[ 00:00:00.749 ]: [Info] Editor options changed!
[ 00:00:01.058 ]: [Info] Project database created. Items count: 240
[ 00:00:01.060 ]: [Info] Previews cache count: 1 (capacity for 225 icons)
[ 00:00:01.063 ]: [Info] Add code editor System Default
[ 00:00:01.063 ]: [Info] Add code editor Visual Studio 2017
[ 00:00:01.063 ]: [Info] Add code editor Visual Studio 2019
[ 00:00:01.063 ]: [Info] Add code editor Visual Studio Code
[ 00:00:01.063 ]: [Info] Add code editor Default
[ 00:00:01.064 ]: [Info] Select code editor Visual Studio Code
================================================================
[ 00:00:01.096 ]: [Info] Starting scripts compilation...
[ 00:00:01.097 ]: [Info] Command: "C:\Program Files (x86)/Flax/Flax_1.1/Binaries/Tools/Flax.Build.exe" -log -logfile= -build -mutex -buildtargets=GameEditorTarget -skiptargets=FlaxEditor -platform=Windows -arch=x64 -configuration=Development
[ 00:00:01.212 ]: [Info] Flax.Build 1.0.7757
[ 00:00:01.964 ]: [Info] Building targets...
[ 00:00:01.980 ]: [Info] Found Android SDK at C:\Users\xxx\AppData\Local\Android\Sdk
Missing Linux Toolchain. Cannot build for Linux platform.
[ 00:00:02.028 ]: [Info] Building C# only
Building target GameEditorTarget in Development for Windows x64
[ 00:00:02.060 ]: [Info] Building referenced target Flax
[ 00:00:03.154 ]: [Info] Building for Windows without Vulkan rendering backend (Vulkan SDK is missing)
[ 00:00:04.022 ]: [Info] Found 12 valid and 0 invalid actions in Task Graph cache
Done!
Total time: 00:00:02.8328563
[ 00:00:04.037 ]: [Info] Scripts reloading start
[ 00:00:04.045 ]: [Info] Loading binary modules from build info file C:\Users/xxx/Documents/Flax Projects/FlaxSamples/ThirdPersonShooterTemplate/Binaries/GameEditorTarget/Windows/x64/Development/GameEditorTarget.Build.json
[ 00:00:04.045 ]: [Info] Loading binary module Game
[ 00:00:04.046 ]: [Info] Caching classes for assembly Game took 0ms
[ 00:00:04.046 ]: [Info] Assembly Game loaded in 1ms
[ 00:00:04.047 ]: [Info] Assembly 'Game' scanned for custom editors in 0 ms
[ 00:00:04.047 ]: [Info] Scripts reloading end. Total time: 10ms
[ 00:00:04.070 ]: [Info] Editor end init
[ 00:00:04.070 ]: [Info] Changing editor state from FlaxEditor.States.LoadingState to FlaxEditor.States.EditingSceneState
[ 00:00:04.231 ]: [Info] Loading editor windows layout from 'C:\Users/xxx/Documents/Flax Projects/FlaxSamples/ThirdPersonShooterTemplate/Cache/WindowsLayout.xml'
[ 00:00:04.340 ]: [Info] Closing splash screen
[ 00:00:04.348 ]: [Info] Loading default project scene
[ 00:00:04.353 ]: [Info] Changing editor state from FlaxEditor.States.EditingSceneState to FlaxEditor.States.ChangingScenesState
[ 00:00:04.374 ]: [Info] Loading scene...
[ 00:00:04.374 ]: [Info] Loading 1 lightmap(s)
[ 00:00:04.380 ]: [Info] Start searching asset with ID: 5b97dd854f2f3f724ccc7ca598534fce in 'C:\Users/xxx/Documents/Flax Projects/FlaxSamples/ThirdPersonShooterTemplate/Content'. 40 potential files to check...
[ 00:00:04.385 ]: [Info] Start searching asset with ID: 5b97dd854f2f3f724ccc7ca598534fce in 'C:\Program Files (x86)/Flax/Flax_1.1/Content'. 153 potential files to check...
[ 00:00:04.394 ]: [Warning] Cannot find 5b97dd854f2f3f724ccc7ca598534fce.
[ 00:00:04.394 ]: [Warning] Invalid asset ID (5b97dd854f2f3f724ccc7ca598534fce).
[ 00:00:04.395 ]: [Warning] Cannot perform workspace scan for '144525c941451d4a61906ab5866dfeb6'. Too often call. Time diff: 17 ms
[ 00:00:04.395 ]: [Warning] Invalid asset ID (144525c941451d4a61906ab5866dfeb6).
[ 00:00:04.420 ]: [Info] Created graph for scene 'Scene' in 13 ms
[ 00:00:04.420 ]: [Info] Changing editor state from FlaxEditor.States.ChangingScenesState to FlaxEditor.States.EditingSceneState
[ 00:00:04.421 ]: [Info] Scene loaded in 47 ms
[ 00:00:04.578 ]: [Info] Starting Atmosphere Pre Compute service
[ 00:04:18.536 ]: [Info] Starting scripts compilation...
[ 00:04:18.536 ]: [Info] Command: "C:\Program Files (x86)/Flax/Flax_1.1/Binaries/Tools/Flax.Build.exe" -log -logfile= -build -mutex -buildtargets=GameEditorTarget -skiptargets=FlaxEditor -platform=Windows -arch=x64 -configuration=Development -hotreload=".HotReload.1"
[ 00:04:18.727 ]: [Info] Flax.Build 1.0.7757
[ 00:04:20.429 ]: [Info] Building targets...
[ 00:04:20.477 ]: [Info] Found Android SDK at C:\Users\xxx\AppData\Local\Android\Sdk
Missing Linux Toolchain. Cannot build for Linux platform.
[ 00:04:20.589 ]: [Info] Building C# only
Building target GameEditorTarget in Development for Windows x64
[ 00:04:20.669 ]: [Info] Building referenced target Flax
[ 00:04:23.100 ]: [Info] Building for Windows without Vulkan rendering backend (Vulkan SDK is missing)
[ 00:04:26.061 ]: [Info] Found 12 valid and 0 invalid actions in Task Graph cache
Done!
Total time: 00:00:07.3506892
[ 00:04:26.109 ]: [Info] Scripts reloading start
[ 00:04:26.110 ]: [Info] Changing editor state from FlaxEditor.States.EditingSceneState to FlaxEditor.States.ReloadingScriptsState
[ 00:04:26.111 ]: [Info] Caching scene Scene
[ 00:04:26.151 ]: [Info] Cleanup graph for scene 'Scene'
[ 00:04:26.157 ]: [Info] Unloding 1 lightmap(s)
[ 00:04:26.159 ]: [Info] Start user scripts reload
[ 00:04:26.173 ]: [Info] Unloading game binary modules
[ 00:04:26.174 ]: [Info] Unloading managed assembly 'Game' (is reloading)
[ 00:04:26.221 ]: [Info] Loading binary modules from build info file C:\Users/xxx/Documents/Flax Projects/FlaxSamples/ThirdPersonShooterTemplate/Binaries/GameEditorTarget/Windows/x64/Development/GameEditorTarget.Build.json
[ 00:04:26.221 ]: [Info] Loading binary module Game
[ 00:04:26.222 ]: [Info] Caching classes for assembly Game took 0ms
[ 00:04:26.222 ]: [Info] Assembly Game loaded in 1ms
[ 00:04:26.223 ]: [Info] Assembly 'Game' scanned for custom editors in 0 ms
[ 00:04:26.223 ]: [Info] End user scripts reload
[ 00:04:26.224 ]: [Info] Restoring scene Scene
[ 00:04:26.224 ]: [Info] Loading scene...
[ 00:04:26.224 ]: [Info] Loading 1 lightmap(s)
[ 00:04:26.293 ]: [Info] Created graph for scene 'Scene' in 29 ms
[ 00:04:26.293 ]: [Info] Scene loaded in 69 ms
[ 00:04:26.293 ]: [Info] Prepare scene objects
[ 00:04:26.298 ]: [Info] Scripts reloading end. Total time: 189ms
[ 00:04:26.301 ]: [Info] Changing editor state from FlaxEditor.States.ReloadingScriptsState to FlaxEditor.States.EditingSceneState
[ 00:04:52.737 ]: [Info] Building target
[ 00:04:52.777 ]: [Info] Thread 'Game Cooker' ID=0x3c4c started with priority Highest
[ 00:04:52.778 ]: [Info] Starting Game Cooker...
[ 00:04:52.778 ]: [Info] Platform: Windows x64, Configuration: Development, Options: 0
[ 00:04:52.778 ]: [Info] Output Path: C:\Users/xxx/Documents/Flax Projects/FlaxSamples/ThirdPersonShooterTemplate/Output/Win64
[ 00:04:52.804 ]: [Info] Starting scripts compilation for game...
[ 00:04:52.805 ]: [Info] Command: "C:\Program Files (x86)/Flax/Flax_1.1/Binaries/Tools/Flax.Build.exe" -log -logfile="C:\Users/xxx/Documents/Flax Projects/FlaxSamples/ThirdPersonShooterTemplate/Cache/Cooker/Windows/CompileLog.txt" -build -mutex -buildtargets=GameTarget -platform=Windows -arch=x64 -configuration=Development
[ 00:04:53.010 ]: [Info] Flax.Build 1.0.7757
[ 00:04:55.040 ]: [Info] Building targets...
[ 00:04:55.102 ]: [Info] Found Android SDK at C:\Users\xxx\AppData\Local\Android\Sdk
[ 00:04:55.117 ]: [Info] Missing Linux Toolchain. Cannot build for Linux platform.
[ 00:04:55.242 ]: [Info] Building C# only
Building target GameTarget in Development for Windows x64
[ 00:04:55.338 ]: [Info] Building referenced target Flax
[ 00:04:59.121 ]: [Info] Building for Windows without Vulkan rendering backend (Vulkan SDK is missing)
[ 00:05:02.297 ]: [Info] Found 12 valid and 0 invalid actions in Task Graph cache
Done!
Total time: 00:00:09.3202708
[ 00:05:02.344 ]: [Info] Deploying binaries from build C:\Users/xxx/Documents/Flax Projects/FlaxSamples/ThirdPersonShooterTemplate/Binaries/GameTarget/Windows/x64/Development/GameTarget.Build.json
[ 00:05:02.344 ]: [Info] Deploying binaries from build C:\Program Files (x86)/Flax/Flax_1.1/Source/Platforms/Windows/Binaries/Game/x64/Development/FlaxGame.Build.json
[ 00:05:02.344 ]: [Info] Collecting binary module FlaxEngine
[ 00:05:02.774 ]: [Info] Collecting binary module Game
[ 00:05:04.882 ]: [Info] Auto save
================================================================
[ 00:05:07.114 ]: [Error] 
[ 00:05:07.114 ]: [Error] Critical error! Reason: Unhandled exception: EXCEPTION_ACCESS_VIOLATION reading address 0xdc64ffe0
[ 00:05:07.115 ]: [Error] 
[ 00:05:07.548 ]: [Error] Stack trace:
[ 00:05:07.548 ]: [Error]     at VCRUNTIME140.dll!memcpy()
[ 00:05:07.548 ]: [Error]     at FlaxEditor.exe!Asset::GetStaticClass()
[ 00:05:07.548 ]: [Error]     at FlaxEditor.exe!Asset::GetStaticClass()
[ 00:05:07.549 ]: [Error]     at FlaxEditor.exe!Asset::GetStaticClass()
[ 00:05:07.549 ]: [Error]     at FlaxEditor.exe!Asset::GetStaticClass()
[ 00:05:07.549 ]: [Error]     at FlaxEditor.exe!Asset::GetStaticClass()
[ 00:05:07.549 ]: [Error]     at FlaxEditor.exe!Asset::GetStaticClass()
[ 00:05:07.549 ]: [Error]     at KERNEL32.DLL!BaseThreadInitThunk()
[ 00:05:07.549 ]: [Error]     at ntdll.dll!RtlUserThreadStart()
[ 00:05:07.549 ]: [Error] 
[ 00:05:07.549 ]: [Error] Used Physical Memory: 12.82 GB (81%)
[ 00:05:07.549 ]: [Error] Used Virtual Memory: 4.69 GB (0%)
[ 00:05:07.549 ]: [Error] Process Used Physical Memory: 351.48 MB
[ 00:05:07.549 ]: [Error] Process Used Virtual Memory: 364.88 MB
[ 00:05:07.549 ]: [Error] Creating Mini Dump to C:\Users/xxx/Documents/Flax Projects/FlaxSamples/ThirdPersonShooterTemplate/Logs/Crash_2021_04_01_09_06_18/Minidump.dmp
[ 00:05:07.858 ]: [Error] 
================================================================
`

**Comment by DisownedWheat** [comment]
Running Flax as Administrator resolves the issue. Probably not an optimal solution but certainly doable.

**Comment by zzanp** [comment]
same in 1.2 and master branch

**Comment by mafiesto4** [comment]
It seems like a random crash and doesn't appear for some time. In case it comes back feel free to reopen this issue.
