### ISSUE TITLE
Flax Launch not downloading Master Version

### ISSUE THREAD

**Issue by RuanLucasGD** [FlaxEngine/FlaxEngine#824]
Hello, I've tried several times but I can never download the master version of Flax through its launcher, even running as an administrator (Windows 11)

**Comment by PrecisionRender** [comment]
Can confirm this issue. The Flax Launcher never downleads master builds.

**Comment by mafiesto4** [comment]
Yeah it looks like Github changes some APIs for files storage (see https://github.com/FlaxEngine/FlaxEngine/actions/runs/3476361704)

**Comment by mafiesto4** [comment]
Ah that's because we had no commits to the `master` branch for some days so the current build is fro the same revision number :)

**Comment by mafiesto4** [comment]
Also in case of problems with `master` build download in Launcher you can investigate or report problem with log file from `%appdata%\Flax\Client.log`.

For example, it shows me info about Github build:
```
Github info fetched in 1101 ms
Latest Github build from master branch (sha: 81c13825c5bacbc0eeb8ade2e36ac771f3816aaf)
```
