### ISSUE TITLE
Visual Studio / Visual Studio Code Auto Complete not working with Flax Master build

### ISSUE THREAD

**Issue by RuanLucasGD** [FlaxEngine/FlaxEngine#825]
Hello, I'm having problems trying to use any code editor when I click **"Generate script project files"** in the editor.
IDEs autocomplete stops working. If I try to go back to version 1.4 and generate the project scripts again, the auto complete works again

![image](https://user-images.githubusercontent.com/79365912/201454520-c82ef254-5fe5-4cc2-bb13-a39ac71422fb.png)

Note: The code editors don't work properly but Flax compiles the scripts normally

**Comment by mafiesto4** [comment]
I wonder if 84bd7da620c0a840402332c5c5e38f5885ef3f00 fixed it? Does it work fine in the latest `master` build?

**Comment by RuanLucasGD** [comment]
@mafiesto4 still does not work

**Comment by mafiesto4** [comment]
Fxed by #888
