### ISSUE TITLE
Incorrect value of VignetteColor In PostProcessSettings on reset value

### ISSUE THREAD

**Issue by RuanLucasGD** [FlaxEngine/FlaxEngine#831]
When creating any post processing configuration the default value of VignetteColor is (0, 0, 0.001) however if you reset the configuration the value goes to (0, 0, 1), an incorrect value.

*Expected:*
![image](https://user-images.githubusercontent.com/79365912/202876759-46681ca6-572e-4b61-9ad7-fe6f7f9fa88d.png)

*What happens:*
![image](https://user-images.githubusercontent.com/79365912/202876815-b9e01d30-bdae-43b6-a28a-440367bea2ae.png)

**Flax version:**
1.4

**Comment by mafiesto4** [comment]
Works fine for me. Can you check again? or maybe it was just that one-time bug

**Comment by RuanLucasGD** [comment]
@mafiesto4 here it still happens, when resetting the post processing settings the VignetteColor goes to (0, 0, 1) instead of (0, 0, 0.001)

**Comment by PhyresiCompany** [comment]
> 

I have the same problem
