### ISSUE TITLE
Casting result of binary AND operator for enums.

### ISSUE THREAD

**Issue by mtszkarbowiak** [FlaxEngine/FlaxEngine#832]
https://github.com/FlaxEngine/FlaxEngine/blob/76c1045444135c841d097fb69e9effa3f38c0d50/Source/Engine/Core/Types/BaseTypes.h#L146

Binary AND operator is the only operation, which has no casting to type T.

**Comment by mafiesto4** [comment]
Fixed in f127bbebe1638302d5bd0761d4922966dc12e94f
