### ISSUE TITLE
Actor selected in scene hierarchy gets deselected due to drag/drop operation.

### ISSUE THREAD

**Issue by Tryibion** [FlaxEngine/FlaxEngine#838]
**Issue description:**
Actor in scene hierarchy gets deselected when dragging actor into actor reference box.

**Steps to reproduce:**
Have an actor type exposed to the editor through a script. drag an actor from the scene hierarchy into the actor reference. It will set the reference but also de-select the current actor that was selected. This should keep the selected actor selected and not de-select it.

https://user-images.githubusercontent.com/71274967/204405825-a1ac782f-a070-4ab7-8aa4-16cd757780fd.mp4

**Flax version:**
1.4.6334

**Comment by RuanLucasGD** [comment]
I also have this problem
