### ISSUE TITLE
Engine crashing when trying to select font material (Vulkan)

### ISSUE THREAD

**Issue by Dugeor** [FlaxEngine/FlaxEngine#841]
**Issue description:**
The engine crashes when trying to open font material browser.
![image](https://user-images.githubusercontent.com/78104154/204555361-3a46eebd-9ae9-4158-9bb4-df269bcc3b4a.png)

**Steps to reproduce:**
Under `Highlight Color` in Label click the Material selector

**Flax version:**
1.4.6334

**Comment by mafiesto4** [comment]
Would be good if you could attach a log file here from that crash moment (from folder `Logs` in project directory).

**Comment by Crawcik** [comment]
I confirm

**Comment by mafiesto4** [comment]
It looks like #1289 which was fixed in 70f0fbe954fd37338df044e652f205201abdc1f6
