### ISSUE TITLE
Vertical Panel and Horizontal Panel Auto Size issue

### ISSUE THREAD

**Issue by Tryibion** [FlaxEngine/FlaxEngine#851]
**Issue description:**
If the UI Canvas is a child of an empty actor and there is a vertical or horizontal control with auto size enabled  then if the the empty Actor.IsActive  is set to false and then back to true, it moves the panel to a different location. This seems to be related to have an empty actor as the parent. I did it this way so that way I would have a blank actor to control my UI with.

**Steps to reproduce:**
Create an empty actor, make a UI canvas child, then make a vertical box control child with as few items in it. Have auto size enabled. Disable and re-enable the empty actor and the vertical box moves

https://user-images.githubusercontent.com/71274967/206949854-df5cba1b-ed20-42c5-bde8-85cf68308786.mp4

**Flax version:**
1.4.6334

**Comment by mafiesto4** [comment]
Fixed in 0a9f746abb662975ff6bddf00aa7ac8600b141c5.
