### ISSUE TITLE
Windows Game building failed!

### ISSUE THREAD

**Issue by PhyresiCompany** [FlaxEngine/FlaxEngine#854]
**Log file**
[Log_2022_12_14_23_13_42.txt](https://github.com/FlaxEngine/FlaxEngine/files/10223686/Log_2022_12_14_23_13_42.txt)

**Flax version:**
1.5.6335

**Comment by Withaust** [comment]
`MultiScaler.cpp` seems to be failing to build properly

**Comment by mafiesto4** [comment]
Works fine now.
