### ISSUE TITLE
New Actor Icons

### ISSUE THREAD

**Issue by Tryibion** [FlaxEngine/FlaxEngine#866]
Hello, I didnt know where to put this, so I am going to put this here. I think the icons for some of the actors (Sky, lights, decals, audio, etc.) could use an upgrade to look more modern. I made some icons that I think would work. Let me know what you think. You can use them in the engine. Let me know if you want any tweaks to any of them.

[New Icons.zip](https://github.com/FlaxEngine/FlaxEngine/files/10290481/New.Icons.zip)

Microphone:
![BetterMicrophone](https://user-images.githubusercontent.com/71274967/209229940-4147400f-3a5b-48fd-b3b4-8a4482651021.png)

Listener:
![Speaker](https://user-images.githubusercontent.com/71274967/209229964-278488db-cedd-4aa6-ac8d-d7883d24042c.png)

Light:
![Light](https://user-images.githubusercontent.com/71274967/209229984-254eb5e9-2d7a-4c04-88bc-899cce1ef57a.png)

Directional Light:
![DirectionalLight](https://user-images.githubusercontent.com/71274967/209230000-276ddeb6-8a39-455c-b08c-9ea5f42d242d.png)

Decal:
![Decal](https://user-images.githubusercontent.com/71274967/209230021-81afc66e-dfbc-4061-9264-e3efcacea228.png)

Particle Effect:
![ParticleEffect](https://user-images.githubusercontent.com/71274967/209230037-ec8a1232-9be3-4714-a4fc-5103bb06f06a.png)

Reflection Probe:
![ReflectionProbe](https://user-images.githubusercontent.com/71274967/209230060-28b862e9-8cd3-4b8f-924f-29a83d2b0668.png)

Scene Animation:
![SceneAnimation](https://user-images.githubusercontent.com/71274967/209230075-89d3f087-2c01-4661-bb3e-5eed9470ac48.png)

Sky:
![Sky](https://user-images.githubusercontent.com/71274967/209230088-257e36ec-e664-4ab5-946f-bfff8b89c6a2.png)

Skylight:
![SkyLight](https://user-images.githubusercontent.com/71274967/209230110-8db3088e-30a2-4723-aa4f-93de0860ad20.png)

**Comment by mafiesto4** [comment]
Those look great!

**Comment by mafiesto4** [comment]
Added in ae700cfbb8adf52608863df0aedfeec0a2cc23a6
