### ISSUE TITLE
Cooked linux binary doesn't run.

### ISSUE THREAD

**Issue by lavyadrian** [FlaxEngine/FlaxEngine#871]
**Issue description:**
When launching the cooked release executable of GraphicsFeaturesTour, you get an error message claiming "Failed to initialize GameSettings.", then it stops running.

**Steps to reproduce:**
Load GraphicsFeaturesTour sample project in Linux editor, cook a release version using the linux builder, run the produced binary.

**Flax version:**
1.4.6334

**Comment by mafiesto4** [comment]
I tested latest `master` on Ubuntu 18 and it works fine (Linux Editor cooked game in Development mode).

Anything specific from your configuration? Maybe need to remove `Cache`? Or old cooking data from project folder?

**Comment by lavyadrian** [comment]
Ok so I tried removing 'Cache' and it did nothing... same thing happened... I don't know what specifics of my config I should watch for...

**Comment by AnasASK** [comment]
I can confirm this issue, (Pop!_OS based on Ubuntu 22.04)
[Log_2023_09_20_17_06_42.txt](https://github.com/FlaxEngine/FlaxEngine/files/12674927/Log_2023_09_20_17_06_42.txt)

**Comment by mafiesto4** [comment]
It might be the case where cooked game executable cannot access game files properly - eg. due to file protection flags. I would ensure that cooked game folder contains `Content` subdirectory with `AssetsCache.dat`, `head`, `Data_0.flaxpac` files that can be accessed by game.
