### ISSUE TITLE
Player actor is not spawned in high level network

### ISSUE THREAD

**Issue by PhyresiCompany** [FlaxEngine/FlaxEngine#878]
**Issue description:**

- If I use "Actor" instead of "This"
On the host, the 2 players will be generated. The host player and the client player
But in the client, only 1 player will be generated.

```csharp
public override void OnEnable()
        {
            NetworkReplicator.AddObject(Actor);
        }

        public override void OnDisable()
        {
            NetworkReplicator.RemoveObject(Actor);
        }
```

- If I use "This" instead of "Actor" it works fine. 2 players are spawned on Host and Client.

```csharp
public override void OnEnable()
        {
            NetworkReplicator.AddObject(this);
        }

        public override void OnDisable()
        {
            NetworkReplicator.RemoveObject(this);
        }
```

Would it be correct to use the "Actor"? Why that way all the Actor would be synchronized. Now, using "This", only a part of the Actor script would be synchronized.

**Way I used to generate my players**

```csharp
private void ClientConnected(NetworkClient obj)
        {
            Debug.Log("Connected");
            myPlayer = PrefabManager.SpawnPrefab(playerPrefab, spawnLocation);
            NetworkReplicator.SpawnObject(myPlayer);
            NetworkReplicator.SetObjectOwnership(myPlayer, obj.ClientId);
        }
```

**Flax version:**
1.5.6335

**Comment by mafiesto4** [comment]
Yeah it looks like calling `NetworkReplicator.AddObject(Actor)` from script will override default spawn command over network thus it makes this bug. I would suggest using `NetworkReplicator.AddObject(this)`. Also, I adjusted `NetworkReplicator.SpawnObject(myPlayer)` method to by default use `hierarchical` spawn that will properly propagate ownership for sub-objects (5dd91d0cdcc2c8933d478ab8abcccb08a074ed52).
