### ISSUE TITLE
JSON SerializeDiff exception handling

### ISSUE THREAD

**Issue by stefnotch** [FlaxEngine/FlaxEngine#88]
**Issue description:**
When a property getter throws an error, Flax fails to serialize the script. This is expected.

However, this error also leads to Flax being unable to serialize the entire scene! That should ideally be improved (e.g. only fail to serialize a single script or property...)

Here is a log file
[Log_2021_01_03_22_18_52.txt](https://github.com/FlaxEngine/FlaxEngine/files/5761472/Log_2021_01_03_22_18_52.txt)

**Steps to reproduce:**
1. Add the following script to your project
2. Attach it to any actor
3. Check out the output log
4. Start the game/save the scene/do stuff
5. Check the output log

```cs
public class Test : Script
{
	public int DontTouchMe
	{
		get
		{
			throw new Exception("You asked for it! >:(");
		}
		set
		{
			throw new Exception("Why would you do that to me?");
		}
	}
}
```

The following, less pathologically silly, script also reproduces this error
```cs
public class Rotate : Script
{
	public Vector3 TransformRotation
	{
		get
		{
			Vector3 dummy;
			dummy.X = Actor.LocalOrientation.X;
			dummy.Y = Actor.LocalOrientation.Y;
			dummy.Z = Actor.LocalOrientation.Z;
			return dummy;
		}

		set
		{
			Actor.LocalOrientation = Quaternion.Euler(value);
		}
	}
}
```

**Flax version:**
Flax 1.0 - e5286510d1bda53a0e301afff825ed17a830a0b0

**Comment by mafiesto4** [comment]
Fixed in 2affebd3753c5d7fa7c68c8d5d6e36ea7e4cbbb8
