### ISSUE TITLE
Replace old tags in Layer and Tag settings in 1.5

### ISSUE THREAD

**Issue by Tryibion** [FlaxEngine/FlaxEngine#884]
Hello the List of tag strings in the `LayerAndTagsSettings` needs to be replaced with the new tag system. 

![image](https://user-images.githubusercontent.com/71274967/210156235-61eaad30-3e4d-4093-a5f0-7d2097036787.png)

Unless this is suppose to be this way still?

**Comment by mafiesto4** [comment]
This list is basically list of tags saved in the project (tag names) and are initialized into runtime `Tags.List` which is used by `Tag` structure.

**Comment by Tryibion** [comment]
Ah okay. So once the tag is added in the new system then it gets added to that list. Was a little confused. Thanks for clarifying. Should the tags also be deleted through the Layers and Tags setting asset?

**Comment by mafiesto4** [comment]
Yes, exactly. Tags can be removed here and won't appear in the list on the next Editor run (we cannot remove tag at runtime because it can already be in use anywhere in a project).

**Comment by Tryibion** [comment]
Is this location suppose to store sub tags as well? I only see it store a 1st level tag.

**Comment by mafiesto4** [comment]
It stores all tags in a project (at least defined ones - code can add own ones at runtime).
