### ISSUE TITLE
Editor crash while debugger is attached and compiling

### ISSUE THREAD

**Issue by MarshMello0** [FlaxEngine/FlaxEngine#895]
**Issue description:**
The Flax Editor crashes if you still have the debugger attached when compiling scripts. I am unsure if this makes a difference, but I am using JetBrains Rider.

Is this a Flax issue or a Mono issue? There may be a way for the program (Flax in this case) to tell mono to detach debuggers. Then you would unload mono. 

> [Error] Current Mono CLR method has thrown an inner exception 
>
 > Additional info: Message: * Assertion at ..\mono\mini\debugger-agent.c:3746, condition `tls->domain_unloading' not met  | Domain: Root

**Steps to reproduce:**
1. Create a new blank project
2. Create a new script
3. Open the script
4. Attach the debugger
5. Remove some code
6. Watch the editor crash

**Minimal reproduction project:**
[Flax Engine Debugger Crash.zip](https://github.com/FlaxEngine/FlaxEngine/files/10421289/Flax.Engine.Debugger.Crash.zip)

**Flax version:**
1.4 (I'm unable to install master for whatever reason)

**Comment by mafiesto4** [comment]
It's a known limitation of the current hot-reload implementation in Editor. For Flax 1.6 we're doping migration to .Net 7 which might work better hopefully.

**Comment by MarshMello0** [comment]
I am closing it as it's a "wontfix" issue. Hopefully, it will help explain the reasoning to others searching for answers.
