### ISSUE TITLE
UI selected marker with incorrect position

### ISSUE THREAD

**Issue by RuanLucasGD** [FlaxEngine/FlaxEngine#897]
Hello, when I change the resolution on the Game Window screen, the selected UI marker is not in the correct position.

![image](https://user-images.githubusercontent.com/79365912/213043351-1492e256-2e3c-48f4-a051-1555865185fb.png)
![image](https://user-images.githubusercontent.com/79365912/213042200-4d635d88-f918-423f-9379-fb317befc67d.png)

Free Aspect:
![image](https://user-images.githubusercontent.com/79365912/213043490-17571bc8-a444-4578-bc41-24c25ae37b74.png)

**Flax version:**
1.4.6334 (master build)

**Comment by mafiesto4** [comment]
Fixed in eaa63e679ead5c5c49257444c1098b34b4dc35da

**Comment by Tryibion** [comment]
@RuanLucasGD just a heads up, that commit was pushed to 1.5, so may not be in master until they are merged.

**Comment by RuanLucasGD** [comment]
@Tryibion thanks for reminding me
