### ISSUE TITLE
FlaxEditor doesn't remember which monitor it was on

### ISSUE THREAD

**Issue by jayrulez** [FlaxEngine/FlaxEngine#9]
**Issue description:**

The editor doesn't remember which monitor it was last used on before closing.

It becomes a bit annoying having to drag the editor window to the primary monitor whenever starting flax.

**Comment by jb-perrier** [comment]
It looks like the editor is opening where the mouse is.

**Comment by jayrulez** [comment]
> It looks like the editor is opening where the mouse is.

Not in my case. It always opens on the same display regardless of where the mouse is.

**Comment by jb-perrier** [comment]
It should be solved by #109 !

**Comment by mafiesto4** [comment]
Fixed by #109, in case of a new occurrence reopen this issue.
