### ISSUE TITLE
Changing the center of a character controller doesn't work

### ISSUE THREAD

**Issue by RuanLucasGD** [FlaxEngine/FlaxEngine#904]
Changing the center of a character controller doesn't work

**Steps to reproduce:**
* Create a character controller
* Add script to move to down
* Change the center of collider

**Minimal reproduction project:**
[MyProject1.zip](https://github.com/FlaxEngine/FlaxEngine/files/10475069/MyProject1.zip)

https://user-images.githubusercontent.com/79365912/213931578-e4ffa851-f879-4167-8598-ff3cc97e39fe.mp4

**Flax version:**
1.4

**Comment by mafiesto4** [comment]
Fixed in e02c4b6f982b4361d34d978c00ec98ecdf053b93
