### ISSUE TITLE
Search bars dont filter on first letter entered

### ISSUE THREAD

**Issue by Tryibion** [FlaxEngine/FlaxEngine#906]
**Issue description:**
Searching filters do not search on first letter

**Steps to reproduce:**
click on any search bar, type 1 letter of something you know is in the shown items. The items being search will not return anything until you type the second letter of the item you are searching for. I think that the first letter should also be search incase someone cant remember the name of something but knows that it started with a specific letter.

**Flax version:**
1.4.6334

**Comment by mafiesto4** [comment]
Actually, that's how it initially was implemented (see `QueryFilterHelper.MinLength`) to accept 2 or more characters for search. But we could improve it for single-character queries.

**Comment by Tryibion** [comment]
@mafiesto4 Was there a specific reason for wanting 2 character or more? If not, I think it would be good to do it off of single-character queries.

**Comment by mafiesto4** [comment]
Fixed in #907.
