### ISSUE TITLE
WindowsFileSystem::ShowOpenFileDialog returns garbage

### ISSUE THREAD

**Issue by divinon** [FlaxEngine/FlaxEngine#92]
**Issue description:**
Hello, on my system (Win8) sometimes WindowsFileSystem::ShowOpenFileDialog returns more than one values, the first is correct the others are garbage. 
This is because the "while (*ptr)" loop expects a double NULL at the end of "of.lpstrFile", but this is to be expected only with OFN_ALLOWMULTISELECT. I think that loop can be removed.

**Flax version:**
latest master

**Comment by divinon** [comment]
You sure already know but I must correct myself, the loop should be skipped only with multiSelect=false.

**Comment by jb-perrier** [comment]
Should be fixed with #93 .
Keep us updated with issue !

**Comment by divinon** [comment]
That should fix it, thanks.
