### ISSUE TITLE
Building scene data stalls editor

### ISSUE THREAD

**Issue by Tryibion** [FlaxEngine/FlaxEngine#942]
**Issue description:**

Building scene data stalls at 98.1% of building lightmaps. The editor also stalls so I have to force end its task via task manager. I believe that someone else in the discord also has this issue.

![image](https://user-images.githubusercontent.com/71274967/219529990-bb67853b-9214-49e4-814c-ccdedc5d4bf4.png)

[Log_2023_02_16_19_56_13.txt](https://github.com/FlaxEngine/FlaxEngine/files/10762500/Log_2023_02_16_19_56_13.txt)

**Steps to reproduce:**
Click the button to build scene data...

**Flax version:**
1.5.6337

**Comment by mafiesto4** [comment]
Potential fix in 8b050cf87e437a43f127e927dc67f650d326c3f2

**Comment by Tryibion** [comment]
Hmmm. Does not seem to have fixed it. It still hangs for me. 
[Log_2023_02_17_07_57_24.txt](https://github.com/FlaxEngine/FlaxEngine/files/10767443/Log_2023_02_17_07_57_24.txt)

Although If I delete my scene data now and then click the build scene data, it looks like I get a proper crash.
[Crash_2023_02_17_07_57_48.zip](https://github.com/FlaxEngine/FlaxEngine/files/10767454/Crash_2023_02_17_07_57_48.zip)

**Comment by Tryibion** [comment]
Still same issues... If I dont delete the current Scene data folder:
[Log_2023_02_17_09_25_19.txt](https://github.com/FlaxEngine/FlaxEngine/files/10768293/Log_2023_02_17_09_25_19.txt)

If I do delete the current scene data folder:
[Crash_2023_02_17_09_20_39.zip](https://github.com/FlaxEngine/FlaxEngine/files/10768296/Crash_2023_02_17_09_20_39.zip)

**Comment by mafiesto4** [comment]
That's strange, maybe 679757942fc76c18e8b6edadef295024f3d495ce will help

**Comment by Tryibion** [comment]
Still same results:
[Log_2023_02_17_09_33_15.txt](https://github.com/FlaxEngine/FlaxEngine/files/10768339/Log_2023_02_17_09_33_15.txt)

[Crash_2023_02_17_09_33_15.zip](https://github.com/FlaxEngine/FlaxEngine/files/10768343/Crash_2023_02_17_09_33_15.zip)

**Comment by Tryibion** [comment]
Project:

[TestingProject.zip](https://github.com/FlaxEngine/FlaxEngine/files/10768671/TestingProject.zip)

**Comment by Tryibion** [comment]
I just tried building lighting on a different project on a different computer and it stalled at the same point.

**Comment by Tryibion** [comment]
Odd... This works for me now. Not sure why it wasn't before...

**Comment by Tryibion** [comment]
This is working now
