### ISSUE TITLE
3D audio quality is poor

### ISSUE THREAD

**Issue by PrecisionRender** [FlaxEngine/FlaxEngine#951]
**Issue description:**
Flax Engine's 3D audio sounds really bad. Regular non-spatial audio sounds fine, but whenever an audio clip is marked as 3D, it gets butchered beyond belief, maybe by attenuation. Here's an example. Remember to unmute the GitHub videos.

**Song: Last Alliance - Missing in Action**

https://user-images.githubusercontent.com/89754713/220214834-d274eb68-0f4c-4f28-a377-9486c8d189f4.mp4

Compared to how it sounds in Godot, with the similar scene, audio attenuation settings, etc:

https://user-images.githubusercontent.com/89754713/220215411-fa39de4e-f9cf-41a1-adad-71dbe932a0bc.mp4

The audio in Godot sounds so much fuller and loud. The audio in Flax sounds like it's... underwater? Or like the player is wearing ear mufflers? Either way, it sounds very poor, and very quiet. Godot's version sounds pretty much the same as how the song actually sounds, and this is with attenuation on and distance filters.

**Steps to reproduce:**
1. Import audio and mark it as 3D.
2. Create a new `AudioSource` and have it play the audio clip you imported.
3. Play the game.

**Minimal reproduction project:**
Unable to share as music in the example is copyrighted. It should be simple enough to set up, though.

**Flax version:**
1.5.6338, on Windows 11.

**Comment by GoaLitiuM** [comment]
Have you tried this with XAudio2 backend? I remember noticing slightly lower audio quality as well with the default OpenAL backend, while XAudio2 sounded a bit clearer, but I don't remember the difference being as noticable as in this clip.

**Comment by PrecisionRender** [comment]
@GoaLitiuM No, how do I switch the backend?

**Comment by PrecisionRender** [comment]
@GoaLitiuM @mafiesto4 Could someone tell me what I need to do to change the audio backend? Does it require rebuilding from source?

**Comment by GoaLitiuM** [comment]
You can comment out the `useOpenAL` and uncomment the `useXAudio2` line in `Source/Engine/Audio/Audio.Build.cs` and rebuild the engine to turn on the XAudio2 backend. There is no way to change it during runtime at the moment.

**Comment by PrecisionRender** [comment]
@GoaLitiuM Thanks!

**Comment by PrecisionRender** [comment]
@GoaLitiuM The XAudio2 backend sounds almost the same, and it's way buggier. For instance, I can't even get the audio to play if the scene has an `AudioListener` actor.

**Comment by PrecisionRender** [comment]
Could this help improve the audio? #963

**Comment by mafiesto4** [comment]
Fixed by:
* #963
* 1ffe8a7b60264df43d6e88bd1352835fbb7f959d

Now, we do support playing multi-channel (eg. stereo) audio on spatial source via OpenAL `AL_SOFT_source_spatialize` extension. If it's not supported, then Flax will automatically convert audio to mono format so all other platforms can use it.
Also, attenuation distance was invalid because the value was in `meters` instead of in `centimeters` as Flax units.

That's how it sounds now:

https://user-images.githubusercontent.com/3464853/233381732-f5e71e7c-796e-4c87-855f-3cb07716a83a.mp4
