### ISSUE TITLE
Ctrl+W interferes with game mode

### ISSUE THREAD

**Issue by Oldman-Sam** [FlaxEngine/FlaxEngine#96]
**Issue description:**
ctrl+w shortcut can occur during game time.

**Steps to reproduce:**
frantically press ctrl+W a few times like your testing a feature for an fps controller :P

**Flax version:**
1.0

**Comment by BoomerDev** [comment]
By the looks of it, CTRL + W just closes the tabs such as Game, Editor, etc. I think it is more of an editor thing since you wouldn't be able to do that with an exported game. There may be some way to lock the keyboard somehow to prevent this.

**Comment by mafiesto4** [comment]
Yep, we should disable it for Game Window.

**Comment by BoomerDev** [comment]
Yeah... Probably a good idea.
