### ISSUE TITLE
Actors not properly flushed on Scene unload

### ISSUE THREAD

**Issue by farmisen** [FlaxEngine/FlaxEngine#97]
**Issue description:**

The editor crashes if you spawn a prefab, set it up to be destroyed with a delay then stop the game and modify and save the prefab. 

**Steps to reproduce:**

- run something like the following:
```
var bullet = PrefabManager.SpawnPrefab (BulletPrefab, bulletTransform);
Destroy (bullet, 5.0f);
```
- stop the game before the spawned actor got GCed
- edit the prefab
- save the prefab
- notice the error dialog:
![image](https://user-images.githubusercontent.com/229946/103615451-d9000080-4ee7-11eb-8cbd-481c9796b0c2.png)

**Flax version:**
1.0

**Comment by farmisen** [comment]
Crash report:
[Log.txt](https://github.com/FlaxEngine/FlaxEngine/files/5768667/Log.txt)

**Comment by mafiesto4** [comment]
Sorry for later reply. Actually, recently I added checks for prefab objects during prefab changes apply (8beb732cb9a1cd1d7032697e787549dbe4ccf828) so even if there are not yet GCed objects they will be skipped by prefab apply to prevent crash - force flush is fine but won't be needed now (I tested different cases of this bug).
