### ISSUE TITLE
(Question) lack of linearToSRgb conversion in the tonemap shader after ColorLookupTable

### ISSUE THREAD

**Issue by DoubleSinoptic** [FlaxEngine/FlaxEngine#974]
I studied the Tonemap/ColorGrading shader code, but could not find the place where the LinearColor to srgb gamma conversion takes place. if it should not be there could you tell me why? I would appreciate it.

**Comment by mafiesto4** [comment]
That's because we don't sRGB for window backuffer format (which maybe is not ideal).

Sorry for super late response.
