### ISSUE TITLE
UI highlights not working correctly when using canvas scalar and control transform not working correctly.

### ISSUE THREAD

**Issue by Tryibion** [FlaxEngine/FlaxEngine#977]
**Issue description:**
I have the canvas scalar set to scale with resolution on the longest side and the highlights for the controls in the game window are not correctly placed. It also looks like the x and y for the control transform of actors under the canvas scalar change when it resizes which makes placing items with the control transform not work very well.

The picture below is me having the vertical panel that is in the middle of the screen selected. You can see the highlights not correctly placed.
![image](https://user-images.githubusercontent.com/71274967/229243626-8da1ae55-8e0e-4627-b070-028bbd271c55.png)

**Flax version:**
1.5.6339

**Comment by Tryibion** [comment]
https://forum.flaxengine.com/t/flaxengine-ui-resizing/956/24

**Comment by mafiesto4** [comment]
Fixed in 44036a26d01b9edca51e908e9d1b8eda902d9a5d

**Comment by alec1o** [comment]
Thanks 😢
