### ISSUE TITLE
Model does not render correctly when using isometric camera.

### ISSUE THREAD

**Issue by RuanLucasGD** [FlaxEngine/FlaxEngine#980]
**Issue description:**

Model does not render correctly when using isometric camera.

**Steps to reproduce:**

1. Create model.
2. Create isometric camera.
3. If the model is small, the camera does not render
4. 
[2023-04-01 20-35-51.webm](https://user-images.githubusercontent.com/79365912/229324399-f0f0fd97-8b64-4ded-b951-8a3e285b8c8e.webm)

**Minimal reproduction project:**

[Game demo.zip](https://github.com/FlaxEngine/FlaxEngine/files/11130904/Game.demo.zip)

**Flax version:**
1.5

**Comment by mafiesto4** [comment]
Fixed in a5afa04f8f54bbb2c93b031467a840991ad99459.
