### ISSUE TITLE
`TextureMipData::GetPixels` consistently returns corrupted results

### ISSUE THREAD

**Issue by Withaust** [FlaxEngine/FlaxEngine#988]
**Issue description:**
Upon using some method that would provide `TextureData`, does not matter in an async unstaged manner or with direct staged getter, you would essentially need to access `TextureMipData` to read pixels. If you were going to use `TextureMipData::GetPixels`, it would produce garbage results, while using `TextureData's` raw `ByteContainer Data` member provides actual non-corrupted pixels in return. 

Here is an example, on the left I am passing `TextureData's` raw `ByteContainer Data` member into stb_image_write as a parameter, and on the right I am passing `Array<Color32>'s` pointer to the first member that came as a result of calling `TextureMipData::GetPixels`:

![image](https://user-images.githubusercontent.com/118038102/230929611-c6aeddea-82e7-4673-ac94-31f0c4ff2511.png)

**Steps to reproduce:**
Try visualizing any `R8G8B8A8_UNorm` texture with the results returned by `TextureMipData::GetPixels` to see that it produces corrupted results.

**Flax version:**
Flax 1.5.6338.0 on Windows 10

**Comment by mafiesto4** [comment]
Fixed in 8a44ea5a99018676b2e3ad91e5b2c8fce9c5df88
