### ISSUE TITLE
Creating a terrain with no scene crashes

### ISSUE THREAD

**Issue by W2Wizard** [FlaxEngine/FlaxEngine#99]
**Issue description:**
Creating a terrrain with no scene crashes the entire editor. Additionaly clicking on the create new foliage button produces an error when no scene is present.

**Steps to reproduce:**
1. Have no scene
2. Go to Toolbox->Terrain->Create Terrain
3. Press on create
4. RIP

**Minimal reproduction project:**
Any blank project will work.

**Flax version:**
1.0

**Comment by mafiesto4** [comment]
Fixed by #100
