### ISSUE TITLE
Clicking a UI button too often causes every second button press to drop

### ISSUE THREAD

**Issue by Bits360** [FlaxEngine/FlaxEngine#990]
**Issue description:**

When clicking a UI button too often, without moving your mouse, every second button press will be dropped, not displaying that the button has been pressed, or registering input.

No logs (does not throw an error.)

**Steps to reproduce:**

Click any button repeatedly without moving your mouse (there is some strange cooldown when it is not moved, which isnt intended, and is rather annoying)

**Minimal reproduction project:**

[MyDebugProject1.zip](https://github.com/FlaxEngine/FlaxEngine/files/11205557/MyDebugProject1.zip)

**Flax version:**

1.5 latest on launcher (also tested in 1.4, both on a fresh reinstall of the engine to ensure that wasnt the problem)

**Comment by mafiesto4** [comment]
Fixed in #1582
