### ISSUE TITLE
CSC : error CS1617: Invalid option '7.3' for /langversion; must be ISO-1, ISO-2

### ISSUE THREAD

**Issue by liyqxtu** [FlaxEngine/FlaxEngine#991]
Generating Flax Engine project files...
CSC : error CS1617: Invalid option '7.3' for /langversion; must be ISO-1, ISO-2
, Default or an integer in range 1 to 6. [C:\FlaxEngine\Source\Tools\Flax.Build
\Flax.Build.csproj]

**Comment by liyqxtu** [comment]
I have install vs2015 with sp3, it doesn's support DoNet7. I have no plan to upgrade the version. How to fixed it,?

**Comment by mafiesto4** [comment]
Yeah the current .NET Framework 4.5.2 we use in Flax is very old. You can download and install it from here: https://www.microsoft.com/en-us/download/details.aspx?id=42637

Upcoming .NET 7 will be included with Flax 1.6 - you can test it on branch `1.6` but it requires Visual Studio 2022 to be installed.
